PA_Education/TestMenifest/force-app/main/default/objects/Interface_Service_Detail__c/Interface_Service_Detail__c.object-meta.xml
<CustomObject>
    <description>Interface Service Detail</description>
    <label>Interface Service Detail</label>
    <nameField>
        <displayFormat>IF_D_{00000}</displayFormat>
        <label>Interface Service Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Interface_Service_Detail__c/fields/Interface_Service_Detail__c.field-meta.xml
<CustomField>
    <fullName>Interface_Service_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>상위항목의 시스템 ID를 선택(TABLE 타입인 경우, 필수 입력항목임)</description>
    <inlineHelpText>상위항목의 시스템 ID를 선택(TABLE 타입인 경우, 필수 입력항목임)</inlineHelpText>
    <label>상위항목 시스템ID</label>
    <referenceTo>Interface_Service_Detail__c</referenceTo>
    <relationshipLabel>Interface Service Detail</relationshipLabel>
    <relationshipName>Interface_Service_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Interface_Service_Detail__c/fields/Request_Column_Format__c.field-meta.xml
<CustomField>
    <fullName>Request_Column_Format__c</fullName>
    <description>(정의서) 요청 컬럼 포멧 |
데이터 처리를 위한 format을 기재
- 날짜, 핸드폰번호, 이메일 등 데이터 형식에 대한 포맷을 기재
- 함수를 적용할 경우에는 함수명+()로 기재</description>
    <inlineHelpText>(정의서) 요청 컬럼 포멧 |
데이터 처리를 위한 format을 기재
- 날짜, 핸드폰번호, 이메일 등 데이터 형식에 대한 포맷을 기재
- 함수를 적용할 경우에는 함수명+()로 기재</inlineHelpText>
    <label>데이터 포맷</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>yyyy-MM-dd</fullName>
            </value>
            <value>
                <fullName>yyyy-MM-dd HH:mm:ss</fullName>
            </value>
            <value>
                <fullName>hh:mm:ss</fullName>
            </value>
            <value>
                <fullName>yyyy-MM-dd&apos;T&apos;HH:mm:ss&apos;Z&apos;</fullName>
            </value>
            <value>
                <fullName>yyyyMMdd</fullName>
            </value>
            <value>
                <fullName>yyyy.MM.dd</fullName>
            </value>
            <value>
                <fullName>HH</fullName>
            </value>
            <value>
                <fullName>mm</fullName>
            </value>
            <value>
                <fullName>yyyy-MM-dd hh:mm</fullName>
                <isActive>false</isActive>
                <label>yyyy-MM-dd hh:mm</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Interface_Service_Detail__c/fields/Source_Column__c.field-meta.xml
<CustomField>
    <fullName>Source_Column__c</fullName>
    <description>필드명(영문) - 요청/응답 파라메터 필드를 기재(인터페이스 정의서 참고)</description>
    <inlineHelpText>필드명(영문) - 요청/응답 파라메터 필드를 기재(인터페이스 정의서 참고)</inlineHelpText>
    <label>소스필드</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Interface_Service_Detail__c/fields/Source_Column_Require_YN__c.field-meta.xml
<CustomField>
    <fullName>Source_Column_Require_YN__c</fullName>
    <description>소스필드의 필수여부를 기재
- 만약, Y인 경우에 값이 없으면 응답시 오류를 리턴함</description>
    <inlineHelpText>소스필드의 필수여부를 기재
- 만약, Y인 경우에 값이 없으면 응답시 오류를 리턴함</inlineHelpText>
    <label>소스필드 필수여부</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N</fullName>
                <default>true</default>
                <label>N</label>
            </value>
            <value>
                <fullName>Y</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Interface_Service_Detail__c/fields/Target_Column_Type__c.field-meta.xml
<CustomField>
    <fullName>Target_Column_Type__c</fullName>
    <description>Select 및 DML 쿼리 수행시 대상이 되는 컬럼 타입을 기재
- 일반항목은 Salesforece Object field 기본 타입과 동일하게 기재할 것
- 응답 시 List나 Map 정보인 경우에는 LIST 또는 MAP, MAP.STRING으로 기재
 ( MAP.STRING으로 설정 시 Map와 동일하게 쿼리가 수행되고, 응답시 Map의 내용을 0레벨에 표시함)</description>
    <inlineHelpText>Select 및 DML 쿼리 수행시 대상이 되는 컬럼 타입을 기재
- Salesforece Object field 기본 타입과 동일하게 기재할 것
- 응답 시 List나 Map 정보인 경우에는 LIST 또는 MAP, MAP.STRING으로 기재
  (MAP.STRING으로 설정 시 Map와 동일하게 쿼리가 수행되고, 응답시 Map의 내용을 0레벨에 표시함)</inlineHelpText>
    <label>대상컬럼타입</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/InterfaceHelper.cls
/**
 * 인터페이스 Helper 클래스
 */
public class InterfaceHelper {
    public InterfaceHelper() {}

    /**
     * 인터페이스 전달전 데이터 유효성을 체크함
     * 
     * @params data = 유효성 체크할 데이터
     * @params props = 데이터 속성 정보
     */
    /*
    Test Class 사용 하지 않아 제거 함. 2020.11.19
    public static String validation(Object datas, INTERFACE_SERVICE_DETAIL__C props, String in_out_type) {
        String msg = '';
        
        msg = isFormat(datas, props.TARGET_COLUMN_TYPE__C, props.REQUEST_COLUMN_FORMAT__C, props.SOURCE_COLUMN__C , in_out_type); // 데이터 타입체크
        msg += isRequired(datas, props.SOURCE_COLUMN_REQUIRE_YN__C, props.SOURCE_COLUMN__C , in_out_type); // 필수여부 체크

        return msg;
    }
    */
    /**
     * 데이터 포맷 일치여부 체크
     * 
     * @params data 검증할 데이터
     * @params type 데이터 타입
     * @params format 데이터 형식(날짜, 숫자에 대한 형식)
     * @return 체크결과(true, false)
     */
    public static String isFormat(Object data, String type, String format, String fieldID, String in_out_type) {
        String val = MetaDataHelper.getString2Object(data, format);
        String msg = '';
        
        try {
            MetaDataHelper.isValidaton2Object(val, type);
        } catch(Exception e) {
            //if(msg != null) { 
            if(in_out_type == 'IN') msg = MessageResource.getMessage(MessageResource.MSG_DATA_FORMAT_3_ERR, new List<String>{fieldID, type}) +' : ' + msg;
            else msg = MessageResource.getMessage(MessageResource.MSG_DATA_FORMAT_4_ERR, new List<String>{fieldID, type}) +' : ' + msg;
            //}
            System.debug(msg); 
        }

        return msg;
    }

    /**
     * 데이터 길이 체크(추후, 데이터 크기를 체크할 경우에 적용할 예정임)
     * 
     * @params data 검증할 데이터
     * @params cond 조건
     * @return 체크결과(true, false)
     */
    public static String isLength(Object data, String cond) {
        return null;
    }

    /**
     * 데이터 필수여부 체크
     * 
     * @params data 검증할 데이터
     * @params cond 조건
     * @return 체크결과(true, false)
     */
    public static String isRequired(Object data, String cond, String fieldID, String in_out_type) {
        String msg = '';
        String val = MetaDataHelper.getString2Object(data, null);

        if(cond == null) cond = 'N';

        if(cond == 'Y' && (val == null || val == '')) {
            if(in_out_type == 'IN') msg = MessageResource.getMessage(MessageResource.MSG_DATA_REQUIRED_1_ERR, new List<String>{fieldID});
            else msg = MessageResource.getMessage(MessageResource.MSG_DATA_REQUIRED_2_ERR, new List<String>{fieldID});
        }

        return msg;
    }

}