PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/BingoBoard__c.object-meta.xml
<CustomObject>
    <description>대유넥스티어 2023 송년회에서 사용 할 Bingo Board Object</description>
    <label>Bingo Board</label>
    <nameField>
        <displayFormat>Board-{0}</displayFormat>
        <label>Bingo Board No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_00__c.field-meta.xml
<CustomField>
    <fullName>Cell_00__c</fullName>
    <label>Cell_00</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_01__c.field-meta.xml
<CustomField>
    <fullName>Cell_01__c</fullName>
    <label>Cell_01</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_02__c.field-meta.xml
<CustomField>
    <fullName>Cell_02__c</fullName>
    <label>Cell_02</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_03__c.field-meta.xml
<CustomField>
    <fullName>Cell_03__c</fullName>
    <label>Cell_03</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_04__c.field-meta.xml
<CustomField>
    <fullName>Cell_04__c</fullName>
    <label>Cell_04</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_10__c.field-meta.xml
<CustomField>
    <fullName>Cell_10__c</fullName>
    <label>Cell_10</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_11__c.field-meta.xml
<CustomField>
    <fullName>Cell_11__c</fullName>
    <label>Cell_11</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_12__c.field-meta.xml
<CustomField>
    <fullName>Cell_12__c</fullName>
    <label>Cell_12</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_13__c.field-meta.xml
<CustomField>
    <fullName>Cell_13__c</fullName>
    <label>Cell_13</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_14__c.field-meta.xml
<CustomField>
    <fullName>Cell_14__c</fullName>
    <label>Cell_14</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_20__c.field-meta.xml
<CustomField>
    <fullName>Cell_20__c</fullName>
    <label>Cell_20</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_21__c.field-meta.xml
<CustomField>
    <fullName>Cell_21__c</fullName>
    <label>Cell_21</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_22__c.field-meta.xml
<CustomField>
    <fullName>Cell_22__c</fullName>
    <label>Cell_22</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_23__c.field-meta.xml
<CustomField>
    <fullName>Cell_23__c</fullName>
    <label>Cell_23</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_24__c.field-meta.xml
<CustomField>
    <fullName>Cell_24__c</fullName>
    <label>Cell_24</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_30__c.field-meta.xml
<CustomField>
    <fullName>Cell_30__c</fullName>
    <label>Cell_30</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_31__c.field-meta.xml
<CustomField>
    <fullName>Cell_31__c</fullName>
    <label>Cell_31</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_32__c.field-meta.xml
<CustomField>
    <fullName>Cell_32__c</fullName>
    <label>Cell_32</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_33__c.field-meta.xml
<CustomField>
    <fullName>Cell_33__c</fullName>
    <label>Cell_33</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_34__c.field-meta.xml
<CustomField>
    <fullName>Cell_34__c</fullName>
    <label>Cell_34</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_40__c.field-meta.xml
<CustomField>
    <fullName>Cell_40__c</fullName>
    <label>Cell_40</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_41__c.field-meta.xml
<CustomField>
    <fullName>Cell_41__c</fullName>
    <label>Cell_41</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_42__c.field-meta.xml
<CustomField>
    <fullName>Cell_42__c</fullName>
    <label>Cell_42</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_43__c.field-meta.xml
<CustomField>
    <fullName>Cell_43__c</fullName>
    <label>Cell_43</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_44__c.field-meta.xml
<CustomField>
    <fullName>Cell_44__c</fullName>
    <label>Cell_44</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoCell__c/BingoCell__c.object-meta.xml
<CustomObject>
    <description>대유넥스티어 2023 송년회에서 사용 할 Bingo Cell Object</description>
    <label>Bingo Cell</label>
    <nameField>
        <displayFormat>Cell-{0}</displayFormat>
        <label>Bingo Cell No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/BingoCell__c/fields/BingoBoard__c.field-meta.xml
<CustomField>
    <fullName>BingoBoard__c</fullName>
    <label>Bingo Board</label>
    <referenceTo>BingoBoard__c</referenceTo>
    <relationshipLabel>Bingo Cell</relationshipLabel>
    <relationshipName>Bingo_Cell</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoCell__c/fields/BingoMember__c.field-meta.xml
<CustomField>
    <fullName>BingoMember__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bingo Member</label>
    <referenceTo>BingoMember__c</referenceTo>
    <relationshipLabel>Bingo Cell</relationshipLabel>
    <relationshipName>Bingo_Cell</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoCell__c/fields/CellX__c.field-meta.xml
<CustomField>
    <fullName>CellX__c</fullName>
    <description>X 축 번호</description>
    <label>CellX</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoCell__c/fields/CellY__c.field-meta.xml
<CustomField>
    <fullName>CellY__c</fullName>
    <description>Y 축 번호</description>
    <label>CellY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoMember__c/BingoMember__c.object-meta.xml
<CustomObject>
    <description>대유넥스티어 2023 송년회에서 사용 할 Bingo Member Object</description>
    <label>Bingo Member</label>
    <nameField>
        <label>Bingo Member Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/classes/BingoForMCController_Test.cls
/**
 * Created by skdus on 2023-11-27.
 */

@IsTest
public with sharing class BingoForMCController_Test {
    @TestSetup
    static void dataInput(){
        List<BingoMember__c> testMembers = new List<BingoMember__c>();
        for (Integer i = 0; i < 25*12; i++) {
            BingoMember__c member = new BingoMember__c (
                    Name = String.valueOf(i)
            );
            System.debug('member Name ::'+member);
            testMembers.add(member);
        }
        insert testMembers;
        List<BingoBoard__c> listTestBoard = new List<BingoBoard__c>();
        for(Integer i=0;i<12;i++) {
            BingoBoard__c testBoard = new BingoBoard__c();
            if(i==0) {
                testBoard.Cell_00__c =1;
                testBoard.Cell_01__c =1;
                testBoard.Cell_02__c =1;
                testBoard.Cell_03__c =1;
                testBoard.Cell_04__c =1;
            }
            if(i==1) {
                testBoard.Cell_10__c =1;
                testBoard.Cell_11__c =1;
                testBoard.Cell_12__c =1;
                testBoard.Cell_13__c =1;
                testBoard.Cell_14__c =1;
            }
            if(i==2) {
                testBoard.Cell_20__c =1;
                testBoard.Cell_21__c =1;
                testBoard.Cell_22__c =1;
                testBoard.Cell_23__c =1;
                testBoard.Cell_24__c =1;
            }
            if(i==3) {
                testBoard.Cell_30__c =1;
                testBoard.Cell_31__c =1;
                testBoard.Cell_32__c =1;
                testBoard.Cell_33__c =1;
                testBoard.Cell_34__c =1;
            }
            if(i==4) {
                testBoard.Cell_40__c =1;
                testBoard.Cell_41__c =1;
                testBoard.Cell_42__c =1;
                testBoard.Cell_43__c =1;
                testBoard.Cell_44__c =1;
            }
            if(i==5) {
                testBoard.Cell_00__c =1;
                testBoard.Cell_10__c =1;
                testBoard.Cell_20__c =1;
                testBoard.Cell_30__c =1;
                testBoard.Cell_40__c =1;
            }
            if(i==6) {
                testBoard.Cell_01__c =1;
                testBoard.Cell_11__c =1;
                testBoard.Cell_21__c =1;
                testBoard.Cell_31__c =1;
                testBoard.Cell_41__c =1;
            }
            if(i==7) {
                testBoard.Cell_02__c =1;
                testBoard.Cell_12__c =1;
                testBoard.Cell_22__c =1;
                testBoard.Cell_32__c =1;
                testBoard.Cell_42__c =1;
            }
            if(i==8) {
                testBoard.Cell_03__c =1;
                testBoard.Cell_13__c =1;
                testBoard.Cell_23__c =1;
                testBoard.Cell_33__c =1;
                testBoard.Cell_43__c =1;
            }
            if(i==9) {
                testBoard.Cell_04__c =1;
                testBoard.Cell_14__c =1;
                testBoard.Cell_24__c =1;
                testBoard.Cell_34__c =1;
                testBoard.Cell_44__c =1;
            }
            if(i==10) {
                testBoard.Cell_00__c =1;
                testBoard.Cell_11__c =1;
                testBoard.Cell_22__c =1;
                testBoard.Cell_33__c =1;
                testBoard.Cell_44__c =1;
            }
            if(i==11) {
                testBoard.Cell_04__c =1;
                testBoard.Cell_13__c =1;
                testBoard.Cell_22__c =1;
                testBoard.Cell_31__c =1;
                testBoard.Cell_40__c =1;
            }

            listTestBoard.add(testBoard);
        }

        insert listTestBoard;

        List<BingoCell__c> testCells = new List<BingoCell__c>();
        for(Integer k=0;k<12;k++) {

            for (Integer i = 0; i < 5; i++) {
                for (Integer j = 0; j < 5; j++) {
                    BingoCell__c cell = new BingoCell__c(
                            BingoMember__c = testMembers[k*25+i*5+j].Id,
                            BingoBoard__c = listTestBoard[k].Id,
                            CellX__c = j,
                            CellY__c = i
                    );

                    testCells.add(cell);
                }
            }
        }
        insert testCells;


        //1~5
//        for(Integer i=0;i<5;i++) {
//            for(Integer j=0;j<5;j++) {
//                BingoForMCController.updateBingoCell(testMembers[0+j+25*i].Id);
//                BingoForMCController.updateBingoCell(testMembers[5+j+25*i].Id);
//                BingoForMCController.updateBingoCell(testMembers[10+j+25*i].Id);
//                BingoForMCController.updateBingoCell(testMembers[15+j+25*i].Id);
//                BingoForMCController.updateBingoCell(testMembers[20+j+25*i].Id);
//            }
//        }
//        //6~10
//        for(Integer i=5;i<10;i++) {
//            for(Integer j=0;j<5;j++) {
//                BingoForMCController.updateBingoCell(testMembers[0+j*5+25*i].Id);
//                BingoForMCController.updateBingoCell(testMembers[1+j*5+25*i].Id);
//                BingoForMCController.updateBingoCell(testMembers[2+j*5+25*i].Id);
//                BingoForMCController.updateBingoCell(testMembers[3+j*5+25*i].Id);
//                BingoForMCController.updateBingoCell(testMembers[4+j*5+25*i].Id);
//            }
//        }

    }

    @isTest
    static void test1() {
        Test.startTest();

        List<BingoMember__c> testMembers = new List<BingoMember__c>();
        testMembers =[
                SELECT Id
                FROM BingoMember__c
        ];

        List<String> result = BingoForMCController.printBingoLine();

        BingoForMCController.updateBingoCell(testMembers[0].Id);

        BingoForMCController.getAvailableMembers();
        BingoForMCController.getSelectedMembers();
        BingoForMCController.whoIsMostPopular();
        BingoForMCController.getAwards();
        BingoForMCController.getBingoLine();



        BingoForMCController.resetGame();
        Test.stopTest();
    }
}