PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/BingoBoard__c.object-meta.xml
<CustomObject>
    <description>대유넥스티어 2023 송년회에서 사용 할 Bingo Board Object</description>
    <label>Bingo Board</label>
    <nameField>
        <displayFormat>Board-{0}</displayFormat>
        <label>Bingo Board No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/BingoLine__c.field-meta.xml
<CustomField>
    <fullName>BingoLine__c</fullName>
    <defaultValue>&quot;none&quot;</defaultValue>
    <label>BingoLine</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/BoardOwner__c.field-meta.xml
<CustomField>
    <fullName>BoardOwner__c</fullName>
    <label>Bingo Board Owner</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_00__c.field-meta.xml
<CustomField>
    <fullName>Cell_00__c</fullName>
    <label>Cell_00</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_01__c.field-meta.xml
<CustomField>
    <fullName>Cell_01__c</fullName>
    <label>Cell_01</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_02__c.field-meta.xml
<CustomField>
    <fullName>Cell_02__c</fullName>
    <label>Cell_02</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_03__c.field-meta.xml
<CustomField>
    <fullName>Cell_03__c</fullName>
    <label>Cell_03</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_04__c.field-meta.xml
<CustomField>
    <fullName>Cell_04__c</fullName>
    <label>Cell_04</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_10__c.field-meta.xml
<CustomField>
    <fullName>Cell_10__c</fullName>
    <label>Cell_10</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_11__c.field-meta.xml
<CustomField>
    <fullName>Cell_11__c</fullName>
    <label>Cell_11</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_12__c.field-meta.xml
<CustomField>
    <fullName>Cell_12__c</fullName>
    <label>Cell_12</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_13__c.field-meta.xml
<CustomField>
    <fullName>Cell_13__c</fullName>
    <label>Cell_13</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_14__c.field-meta.xml
<CustomField>
    <fullName>Cell_14__c</fullName>
    <label>Cell_14</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_20__c.field-meta.xml
<CustomField>
    <fullName>Cell_20__c</fullName>
    <label>Cell_20</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_21__c.field-meta.xml
<CustomField>
    <fullName>Cell_21__c</fullName>
    <label>Cell_21</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_22__c.field-meta.xml
<CustomField>
    <fullName>Cell_22__c</fullName>
    <label>Cell_22</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_23__c.field-meta.xml
<CustomField>
    <fullName>Cell_23__c</fullName>
    <label>Cell_23</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_24__c.field-meta.xml
<CustomField>
    <fullName>Cell_24__c</fullName>
    <label>Cell_24</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_30__c.field-meta.xml
<CustomField>
    <fullName>Cell_30__c</fullName>
    <label>Cell_30</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_31__c.field-meta.xml
<CustomField>
    <fullName>Cell_31__c</fullName>
    <label>Cell_31</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_32__c.field-meta.xml
<CustomField>
    <fullName>Cell_32__c</fullName>
    <label>Cell_32</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_33__c.field-meta.xml
<CustomField>
    <fullName>Cell_33__c</fullName>
    <label>Cell_33</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_34__c.field-meta.xml
<CustomField>
    <fullName>Cell_34__c</fullName>
    <label>Cell_34</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_40__c.field-meta.xml
<CustomField>
    <fullName>Cell_40__c</fullName>
    <label>Cell_40</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_41__c.field-meta.xml
<CustomField>
    <fullName>Cell_41__c</fullName>
    <label>Cell_41</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_42__c.field-meta.xml
<CustomField>
    <fullName>Cell_42__c</fullName>
    <label>Cell_42</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_43__c.field-meta.xml
<CustomField>
    <fullName>Cell_43__c</fullName>
    <label>Cell_43</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/Cell_44__c.field-meta.xml
<CustomField>
    <fullName>Cell_44__c</fullName>
    <label>Cell_44</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/fm_BingoCount__c.field-meta.xml
<CustomField>
    <fullName>fm_BingoCount__c</fullName>
    <formula>IF(Cell_00__c + Cell_01__c + Cell_02__c + Cell_03__c + Cell_04__c = 5, 1, 0) +
IF(Cell_10__c + Cell_11__c + Cell_12__c + Cell_13__c + Cell_14__c = 5, 1, 0) +
IF(Cell_20__c + Cell_21__c + Cell_22__c + Cell_23__c + Cell_24__c = 5, 1, 0) +
IF(Cell_30__c + Cell_31__c + Cell_32__c + Cell_33__c + Cell_34__c = 5, 1, 0) +
IF(Cell_40__c + Cell_41__c + Cell_42__c + Cell_43__c + Cell_44__c = 5, 1, 0) +

IF(Cell_00__c + Cell_10__c + Cell_20__c + Cell_30__c + Cell_40__c = 5, 1, 0) +
IF(Cell_01__c + Cell_11__c + Cell_21__c + Cell_31__c + Cell_41__c = 5, 1, 0) +
IF(Cell_02__c + Cell_12__c + Cell_22__c + Cell_32__c + Cell_42__c = 5, 1, 0) +
IF(Cell_03__c + Cell_13__c + Cell_23__c + Cell_33__c + Cell_43__c = 5, 1, 0) +
IF(Cell_04__c + Cell_14__c + Cell_24__c + Cell_34__c + Cell_44__c = 5, 1, 0) +

IF(Cell_00__c + Cell_11__c + Cell_22__c + Cell_33__c + Cell_44__c = 5, 1, 0) +
IF(Cell_04__c + Cell_13__c + Cell_22__c + Cell_31__c + Cell_40__c = 5, 1, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bingo Count</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/fm_BingoLine1__c.field-meta.xml
<CustomField>
    <fullName>fm_BingoLine1__c</fullName>
    <formula>Cell_00__c + Cell_01__c + Cell_02__c + Cell_03__c + Cell_04__c = 5</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BingoLine1</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/fm_BingoLine2__c.field-meta.xml
<CustomField>
    <fullName>fm_BingoLine2__c</fullName>
    <formula>Cell_10__c + Cell_11__c + Cell_12__c + Cell_13__c + Cell_14__c = 5</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BingoLine2</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/fm_BingoLine3__c.field-meta.xml
<CustomField>
    <fullName>fm_BingoLine3__c</fullName>
    <formula>Cell_20__c + Cell_21__c + Cell_22__c + Cell_23__c + Cell_24__c = 5</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BingoLine3</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/fm_BingoLine4__c.field-meta.xml
<CustomField>
    <fullName>fm_BingoLine4__c</fullName>
    <formula>Cell_30__c + Cell_31__c + Cell_32__c + Cell_33__c + Cell_34__c = 5</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BingoLine4</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/fm_BingoLine5__c.field-meta.xml
<CustomField>
    <fullName>fm_BingoLine5__c</fullName>
    <formula>Cell_40__c + Cell_41__c + Cell_42__c + Cell_43__c + Cell_44__c = 5</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BingoLine5</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/fm_BingoLine6__c.field-meta.xml
<CustomField>
    <fullName>fm_BingoLine6__c</fullName>
    <formula>Cell_00__c + Cell_10__c + Cell_20__c + Cell_30__c + Cell_40__c = 5</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BingoLine6</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/fm_BingoLine7__c.field-meta.xml
<CustomField>
    <fullName>fm_BingoLine7__c</fullName>
    <formula>Cell_01__c + Cell_11__c + Cell_21__c + Cell_31__c + Cell_41__c = 5</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BingoLine7</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/fm_BingoLine8__c.field-meta.xml
<CustomField>
    <fullName>fm_BingoLine8__c</fullName>
    <formula>Cell_02__c + Cell_12__c + Cell_22__c + Cell_32__c + Cell_42__c = 5</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BingoLine8</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoBoard__c/fields/IsBingo__c.field-meta.xml
<CustomField>
    <fullName>IsBingo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsBingo</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoCell__c/BingoCell__c.object-meta.xml
<CustomObject>
    <description>대유넥스티어 2023 송년회에서 사용 할 Bingo Cell Object</description>
    <label>Bingo Cell</label>
    <nameField>
        <displayFormat>Cell-{0}</displayFormat>
        <label>Bingo Cell No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/BingoCell__c/fields/BingoBoard__c.field-meta.xml
<CustomField>
    <fullName>BingoBoard__c</fullName>
    <label>Bingo Board</label>
    <referenceTo>BingoBoard__c</referenceTo>
    <relationshipLabel>Bingo Cell</relationshipLabel>
    <relationshipName>Bingo_Cell</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoCell__c/fields/BingoMember__c.field-meta.xml
<CustomField>
    <fullName>BingoMember__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bingo Member</label>
    <referenceTo>BingoMember__c</referenceTo>
    <relationshipLabel>Bingo Cell</relationshipLabel>
    <relationshipName>Bingo_Cell</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoCell__c/fields/CellX__c.field-meta.xml
<CustomField>
    <fullName>CellX__c</fullName>
    <description>X 축 번호</description>
    <label>CellX</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoCell__c/fields/CellY__c.field-meta.xml
<CustomField>
    <fullName>CellY__c</fullName>
    <description>Y 축 번호</description>
    <label>CellY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoCell__c/fields/IsChecked__c.field-meta.xml
<CustomField>
    <fullName>IsChecked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Cell 선택 여부</description>
    <label>Is Checked</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoMember__c/BingoMember__c.object-meta.xml
<CustomObject>
    <description>대유넥스티어 2023 송년회에서 사용 할 Bingo Member Object</description>
    <label>Bingo Member</label>
    <nameField>
        <label>Bingo Member Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/BingoMember__c/fields/ClickedTime__c.field-meta.xml
<CustomField>
    <fullName>ClickedTime__c</fullName>
    <description>빙고 호명된 시간 저장</description>
    <label>ClickedTime</label>
    <type>DateTime</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/BingoMember__c/fields/IsChecked__c.field-meta.xml
<CustomField>
    <fullName>IsChecked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>선택 여부</description>
    <label>Is Checked</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/BingoForMCController.cls
/**
 * Created by skdus on 2023-11-07.
 */

public with sharing class BingoForMCController {
    public class CountWrapper implements Comparable {
        public String memberName;
        public Integer count;

        public CountWrapper(String memberName, Integer count) {
            this.memberName = memberName;
            this.count = count;
        }

        public Integer compareTo(Object obj) {
            CountWrapper other = (CountWrapper)obj;
            return other.count - this.count;
        }
    }

    @AuraEnabled
    public static List<BingoMember__c> getAvailableMembers() {
        List<BingoMember__c> listAvailableMembers = [
                SELECT Id, Name, IsChecked__c
                FROM BingoMember__c
                WHERE IsChecked__c = FALSE
        ];

        return listAvailableMembers;
    }

    @AuraEnabled
    public static List<BingoMember__c> getSelectedMembers() {
        List<BingoMember__c> listSelectedMembers = [
                SELECT Id, Name, IsChecked__c, ClickedTime__c
                FROM BingoMember__c
                WHERE IsChecked__c = TRUE
                ORDER BY ClickedTime__c
        ];

        List<BingoCell__c> listCell = [
                SELECT Id, IsChecked__c
                FROM BingoCell__c
                WHERE BingoMember__r.IsChecked__c = TRUE
        ];

        if (listCell != null) {
            for (BingoCell__c cell : listCell) {
                cell.IsChecked__c = true;
            }
            update listCell;
        }
        return listSelectedMembers;
    }

    @AuraEnabled
    public static void updateBingoCell(String memberId) {
        List<BingoCell__c> listBC = new List<BingoCell__c>();
        listBC = [
                SELECT Id, IsChecked__c, CellX__c, CellY__c, BingoBoard__r.Cell_00__c,
                        BingoBoard__r.Cell_01__c, BingoBoard__r.Cell_02__c, BingoBoard__r.Cell_03__c,
                        BingoBoard__r.Cell_04__c, BingoBoard__r.Cell_10__c, BingoBoard__r.Cell_11__c,
                        BingoBoard__r.Cell_12__c, BingoBoard__r.Cell_13__c, BingoBoard__r.Cell_14__c,
                        BingoBoard__r.Cell_20__c, BingoBoard__r.Cell_21__c, BingoBoard__r.Cell_22__c,
                        BingoBoard__r.Cell_23__c, BingoBoard__r.Cell_24__c, BingoBoard__r.Cell_30__c,
                        BingoBoard__r.Cell_31__c, BingoBoard__r.Cell_32__c, BingoBoard__r.Cell_33__c,
                        BingoBoard__r.Cell_34__c, BingoBoard__r.Cell_40__c, BingoBoard__r.Cell_41__c,
                        BingoBoard__r.Cell_42__c, BingoBoard__r.Cell_43__c, BingoBoard__r.Cell_44__c
                FROM BingoCell__c
                WHERE BingoMember__c =: memberId
        ];

        if (listBC != null) {
            List<BingoBoard__c> bingoBoardListToUpdate = new List<BingoBoard__c>();
            Set<Id> uniqueBoardIds = new Set<Id>();

            for (BingoCell__c bc : listBC) {
                bc.IsChecked__c = true;
                String fieldName = 'Cell_' + String.valueOf(bc.CellX__c).leftPad(1, '0') + String.valueOf(bc.CellY__c).leftPad(1, '0') + '__c';
                bc.BingoBoard__r.put(fieldName, 1);

                if (!uniqueBoardIds.contains(bc.BingoBoard__c)) {
                    bingoBoardListToUpdate.add(bc.BingoBoard__r);
                    uniqueBoardIds.add(bc.BingoBoard__c);
                }
            }

            update bingoBoardListToUpdate;
            update listBC;
        }

        List<BingoMember__c> listBM = [
                SELECT Id, IsChecked__c
                FROM BingoMember__c
                WHERE Id =: memberId
                LIMIT 1
        ];

        if (listBM != null) {
            for (BingoMember__c bm : listBM) {
                bm.IsChecked__c = true;
                bm.ClickedTime__c = Datetime.now();
            }
            update listBM;
        }
    }

    @AuraEnabled
    public static void resetGame() {
        List<BingoCell__c> listCell = [
                SELECT Id, IsChecked__c, CellX__c, CellY__c, BingoBoard__r.Cell_00__c,
                        BingoBoard__r.Cell_01__c, BingoBoard__r.Cell_02__c, BingoBoard__r.Cell_03__c,
                        BingoBoard__r.Cell_04__c, BingoBoard__r.Cell_10__c, BingoBoard__r.Cell_11__c,
                        BingoBoard__r.Cell_12__c, BingoBoard__r.Cell_13__c, BingoBoard__r.Cell_14__c,
                        BingoBoard__r.Cell_20__c, BingoBoard__r.Cell_21__c, BingoBoard__r.Cell_22__c,
                        BingoBoard__r.Cell_23__c, BingoBoard__r.Cell_24__c, BingoBoard__r.Cell_30__c,
                        BingoBoard__r.Cell_31__c, BingoBoard__r.Cell_32__c, BingoBoard__r.Cell_33__c,
                        BingoBoard__r.Cell_34__c, BingoBoard__r.Cell_40__c, BingoBoard__r.Cell_41__c,
                        BingoBoard__r.Cell_42__c, BingoBoard__r.Cell_43__c, BingoBoard__r.Cell_44__c
                FROM BingoCell__c
        ];
        System.debug('listCell::'+listCell);
        System.debug('listCellsize::'+listCell.size());

        if (listCell != null) {
            List<BingoBoard__c> bingoBoardListToUpdate = new List<BingoBoard__c>();
            Set<Id> uniqueBoardIds = new Set<Id>();
            for (BingoCell__c bc : listCell) {
                bc.IsChecked__c = false;
                String fieldName = 'Cell_' + String.valueOf(bc.CellX__c).leftPad(1, '0') + String.valueOf(bc.CellY__c).leftPad(1, '0') + '__c';
                bc.BingoBoard__r.put(fieldName, 0);

                if (!uniqueBoardIds.contains(bc.BingoBoard__c)) {
                    bingoBoardListToUpdate.add(bc.BingoBoard__r);
                    uniqueBoardIds.add(bc.BingoBoard__c);
                }
            }

            update bingoBoardListToUpdate;
            update listCell;
        }

        List<BingoMember__c> listMember = [
                SELECT Id, IsChecked__c
                FROM BingoMember__c
        ];

        if (listMember != null) {
            for (BingoMember__c memberToUpdate : listMember) {
                memberToUpdate.IsChecked__c = false;
            }
        }

        update listMember;

        List<BingoBoard__c> listBoard = [
                SELECT Id, IsBingo__c
                FROM BingoBoard__c
        ];

        if (listBoard != null) {
            for (BingoBoard__c board : listBoard) {
                board.IsBingo__c = false;
                board.BingoLine__c = 'none';
            }
        }

        update listBoard;
    }

    @AuraEnabled
    public static List<String> whoIsMostPopular() {
        Map<String, Integer> mapPM = new Map<String, Integer>();

        for (BingoCell__c cell : [SELECT BingoMember__r.Name FROM BingoCell__c WHERE BingoMember__c != NULL]) {
            String memberName = cell.BingoMember__r.Name;
            if (!mapPM.containsKey(memberName)) {
                mapPM.put(memberName, 0);
            }
            mapPM.put(memberName, mapPM.get(memberName) + 1);
        }

        List<CountWrapper> listCount = new List<CountWrapper>();
        for (String memberName : mapPM.keySet()) {
            listCount.add(new CountWrapper(memberName, mapPM.get(memberName)));
        }

        listCount.sort();

        List<String> listResult = new List<String>();
        Integer currentRank = 1;
        Integer currentCount = listCount[0].count;

        for (CountWrapper countWrapper : listCount) {
            String memberName = countWrapper.memberName;
            Integer count = countWrapper.count;

            if (count < currentCount) {
                currentRank++;
                currentCount = count;
            }

            if (currentRank == 11) {
                for (CountWrapper cw : listCount) {
                    String name = cw.memberName;
                    Integer cnt = cw.count;
                    if (cnt == currentCount) {
                        listResult.add(currentRank + '위: ' + name + '(' + cnt + ')');
                    }else {
                        break;
                    }
                }
                break;
            }

            listResult.add(currentRank + '위: ' + memberName + '(' + count + ')');
        }


        System.debug('Bingo Cell Count Map: ' + mapPM);
        System.debug('Sorted Count List: ' + listCount);
        System.debug('Final Result List: ' + listResult);

        return listResult;
    }

    @AuraEnabled
    public static List<String> getAwards() {
        List<BingoBoard__c> listBoard = [
                SELECT Name, fm_BingoCount__c, BoardOwner__c
                FROM BingoBoard__c
        ];

        List<String> listBingoComplete = new List<String>();
        for (BingoBoard__c board : listBoard) {
            if (board.fm_BingoCount__c >= 1) {
                listBingoComplete.add(board.BoardOwner__c);
            }
        }

        return listBingoComplete;
    }

    @AuraEnabled
    public static void getBingoLine() {
        List<BingoBoard__c> listBoard = [
                SELECT Name, fm_BingoCount__c, fm_BingoLine1__c, fm_BingoLine2__c, fm_BingoLine3__c,
                        fm_BingoLine4__c, fm_BingoLine5__c, fm_BingoLine6__c, fm_BingoLine7__c,
                        fm_BingoLine8__c, fm_BingoLine9__c, fm_BingoLine10__c, fm_BingoLine11__c,
                        fm_BingoLine12__c, BoardOwner__c, IsBingo__c, BingoLine__c
                FROM BingoBoard__c
                WHERE fm_BingoCount__c >= 1 AND BingoLine__c = 'none'
        ];

        for (BingoBoard__c board : listBoard) {
            if (board.fm_BingoLine1__c == true) {
                List<BingoCell__c> listCell = [
                        SELECT Id, BingoMember__r.Name, CellX__c, CellY__c
                        FROM BingoCell__c
                        WHERE BingoBoard__r.BoardOwner__c = :board.BoardOwner__c
                        AND CellX__c = 0
                        AND CellY__c IN (0, 1, 2, 3, 4)
                ];

                String line = '';
                for (BingoCell__c bc : listCell) {
                    line += bc.BingoMember__r.Name + ' ';
                }
                line += '(' + board.BoardOwner__c + ')';
                board.BingoLine__c = line;
            }else if (board.fm_BingoLine2__c == true) {
                List<BingoCell__c> listCell = [
                        SELECT Id, BingoMember__r.Name, CellX__c, CellY__c
                        FROM BingoCell__c
                        WHERE BingoBoard__r.BoardOwner__c = :board.BoardOwner__c
                        AND CellX__c = 1
                        AND CellY__c IN (0, 1, 2, 3, 4)
                ];

                String line = '';
                for (BingoCell__c bc : listCell) {
                    line += bc.BingoMember__r.Name + ' ';
                }
                line += '(' + board.BoardOwner__c + ')';
                board.BingoLine__c = line;
            }else if (board.fm_BingoLine3__c == true) {
                List<BingoCell__c> listCell = [
                        SELECT Id, BingoMember__r.Name, CellX__c, CellY__c
                        FROM BingoCell__c
                        WHERE BingoBoard__r.BoardOwner__c = :board.BoardOwner__c
                        AND CellX__c = 2
                        AND CellY__c IN (0, 1, 2, 3, 4)
                ];

                String line = '';
                for (BingoCell__c bc : listCell) {
                    line += bc.BingoMember__r.Name + ' ';
                }
                line += '(' + board.BoardOwner__c + ')';
                board.BingoLine__c = line;
            }else if (board.fm_BingoLine4__c == true) {
                List<BingoCell__c> listCell = [
                        SELECT Id, BingoMember__r.Name, CellX__c, CellY__c
                        FROM BingoCell__c
                        WHERE BingoBoard__r.BoardOwner__c = :board.BoardOwner__c
                        AND CellX__c = 3
                        AND CellY__c IN (0, 1, 2, 3, 4)
                ];

                String line = '';
                for (BingoCell__c bc : listCell) {
                    line += bc.BingoMember__r.Name + ' ';
                }
                line += '(' + board.BoardOwner__c + ')';
                board.BingoLine__c = line;
            }else if (board.fm_BingoLine5__c == true) {
                List<BingoCell__c> listCell = [
                        SELECT Id, BingoMember__r.Name, CellX__c, CellY__c
                        FROM BingoCell__c
                        WHERE BingoBoard__r.BoardOwner__c = :board.BoardOwner__c
                        AND CellX__c = 4
                        AND CellY__c IN (0, 1, 2, 3, 4)
                ];

                String line = '';
                for (BingoCell__c bc : listCell) {
                    line += bc.BingoMember__r.Name + ' ';
                }
                line += '(' + board.BoardOwner__c + ')';
                board.BingoLine__c = line;
            }else if (board.fm_BingoLine6__c == true) {
                List<BingoCell__c> listCell = [
                        SELECT Id, BingoMember__r.Name, CellX__c, CellY__c
                        FROM BingoCell__c
                        WHERE BingoBoard__r.BoardOwner__c = :board.BoardOwner__c
                        AND CellX__c IN (0, 1, 2, 3, 4)
                        AND CellY__c = 0
                ];

                String line = '';
                for (BingoCell__c bc : listCell) {
                    line += bc.BingoMember__r.Name + ' ';
                }
                line += '(' + board.BoardOwner__c + ')';
                board.BingoLine__c = line;
            }else if (board.fm_BingoLine7__c == true) {
                List<BingoCell__c> listCell = [
                        SELECT Id, BingoMember__r.Name, CellX__c, CellY__c
                        FROM BingoCell__c
                        WHERE BingoBoard__r.BoardOwner__c = :board.BoardOwner__c
                        AND CellX__c IN (0, 1, 2, 3, 4)
                        AND CellY__c = 1
                ];

                String line = '';
                for (BingoCell__c bc : listCell) {
                    line += bc.BingoMember__r.Name + ' ';
                }
                line += '(' + board.BoardOwner__c + ')';
                board.BingoLine__c = line;
            }else if (board.fm_BingoLine8__c == true) {
                List<BingoCell__c> listCell = [
                        SELECT Id, BingoMember__r.Name, CellX__c, CellY__c
                        FROM BingoCell__c
                        WHERE BingoBoard__r.BoardOwner__c = :board.BoardOwner__c
                        AND CellX__c IN (0, 1, 2, 3, 4)
                        AND CellY__c = 2
                ];

                String line = '';
                for (BingoCell__c bc : listCell) {
                    line += bc.BingoMember__r.Name + ' ';
                }
                line += '(' + board.BoardOwner__c + ')';
                board.BingoLine__c = line;
            }else if (board.fm_BingoLine9__c == true) {
                List<BingoCell__c> listCell = [
                        SELECT Id, BingoMember__r.Name, CellX__c, CellY__c
                        FROM BingoCell__c
                        WHERE BingoBoard__r.BoardOwner__c = :board.BoardOwner__c
                        AND CellX__c IN (0, 1, 2, 3, 4)
                        AND CellY__c = 3
                ];

                String line = '';
                for (BingoCell__c bc : listCell) {
                    line += bc.BingoMember__r.Name + ' ';
                }
                line += '(' + board.BoardOwner__c + ')';
                board.BingoLine__c = line;
            }else if (board.fm_BingoLine10__c == true) {
                List<BingoCell__c> listCell = [
                        SELECT Id, BingoMember__r.Name, CellX__c, CellY__c
                        FROM BingoCell__c
                        WHERE BingoBoard__r.BoardOwner__c = :board.BoardOwner__c
                        AND CellX__c IN (0, 1, 2, 3, 4)
                        AND CellY__c = 4
                ];

                String line = '';
                for (BingoCell__c bc : listCell) {
                    line += bc.BingoMember__r.Name + ' ';
                }
                line += '(' + board.BoardOwner__c + ')';
                board.BingoLine__c = line;
            }else if (board.fm_BingoLine11__c == true) {
                List<BingoCell__c> listCell = [
                        SELECT Id, BingoMember__r.Name, CellX__c, CellY__c
                        FROM BingoCell__c
                        WHERE BingoBoard__r.BoardOwner__c = :board.BoardOwner__c
                ];

                String line = '';
                for (BingoCell__c bc : listCell) {
                    if (bc.CellX__c == bc.CellY__c) {
                        line += bc.BingoMember__r.Name + ' ';
                    }
                }
                line += '(' + board.BoardOwner__c + ')';
                board.BingoLine__c = line;
            }else if (board.fm_BingoLine12__c == true) {
                List<BingoCell__c> listCell = [
                        SELECT Id, BingoMember__r.Name, CellX__c, CellY__c
                        FROM BingoCell__c
                        WHERE BingoBoard__r.BoardOwner__c = :board.BoardOwner__c
                ];

                String line = '';
                for (BingoCell__c bc : listCell) {
                    if (bc.CellX__c + bc.CellY__c == 4) {
                        line += bc.BingoMember__r.Name + ' ';
                    }
                }
                line += '(' + board.BoardOwner__c + ')';
                board.BingoLine__c = line;
            }
            board.IsBingo__c = true;
        }
        update listBoard;
    }

    @AuraEnabled
    public static List<String> printBingoLine() {
        List<BingoBoard__c> listBoard = [
                SELECT Id, IsBingo__c, BingoLine__c
                FROM BingoBoard__c
                WHERE IsBingo__c = True
        ];

        List<String> listReturn = new List<String>();
        for (BingoBoard__c board : listBoard) {
            listReturn.add(board.BingoLine__c);
        }

        return listReturn;
    }
}