PA_Education/TestMenifest/force-app/main/default/objects/CATS_TMP_ACQUIRE__c/CATS_TMP_ACQUIRE__c.object-meta.xml
<CustomObject>
    <label>매입내역</label>
    <nameField>
        <displayFormat>ACQUIRE-{YY}{MM}{DD}-{00000}</displayFormat>
        <label>매입내역 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/CATS_TMP_ACQUIRE__c/fields/ApprDate__c.field-meta.xml
<CustomField>
    <fullName>ApprDate__c</fullName>
    <label>(원)거래일자</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CATS_TMP_ACQUIRE__c/fields/MccName__c.field-meta.xml
<CustomField>
    <fullName>MccName__c</fullName>
    <label>VISA 업종명</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CATS_TMP_ACQUIRE__c/fields/MerchAddr1__c.field-meta.xml
<CustomField>
    <fullName>MerchAddr1__c</fullName>
    <label>가맹점 주소-1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CATS_TMP_ACQUIRE__c/fields/PurchDate__c.field-meta.xml
<CustomField>
    <fullName>PurchDate__c</fullName>
    <label>매입일자</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CATS_TMP_ACQUIRE__c/fields/PurchTime__c.field-meta.xml
<CustomField>
    <fullName>PurchTime__c</fullName>
    <label>매입시간</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CATS_TMP_ACQUIRE__c/fields/PurchTot__c.field-meta.xml
<CustomField>
    <fullName>PurchTot__c</fullName>
    <label>매입합계[원화]  = 매입원금(원화)+환가료</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CATS_TMP_ACQUIRE__c/fields/Seq__c.field-meta.xml
<CustomField>
    <fullName>Seq__c</fullName>
    <externalId>true</externalId>
    <label>일련번호</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CATS_TMP_ACQUIRE__c/fields/Tips1__c.field-meta.xml
<CustomField>
    <fullName>Tips1__c</fullName>
    <label>수정 봉사료</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>강의 Object</description>
    <label>Training</label>
    <nameField>
        <displayFormat>강의-{0000}</displayFormat>
        <label>강의 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCard__c/CorporateCard__c.object-meta.xml
<CustomObject>
    <label>법인카드</label>
    <nameField>
        <label>법인카드 이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCard__c/fields/CardNumber__c.field-meta.xml
<CustomField>
    <fullName>CardNumber__c</fullName>
    <externalId>true</externalId>
    <label>카드번호</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/CorporateCardBilling__c.object-meta.xml
<CustomObject>
    <label>법인카드청구내역</label>
    <nameField>
        <displayFormat>CB-{YY}{MM}-{00000}</displayFormat>
        <label>법인카드청구내역</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/fields/Acquire__c.field-meta.xml
<CustomField>
    <fullName>Acquire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>매입내역(승인)</label>
    <referenceTo>CATS_TMP_ACQUIRE__c</referenceTo>
    <relationshipLabel>법인카드청구내역</relationshipLabel>
    <relationshipName>CorporateCardBilling_CATS_TMP_ACQUIRE</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/fields/AcquireCancel__c.field-meta.xml
<CustomField>
    <fullName>AcquireCancel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>매입내역(취소)</label>
    <referenceTo>CATS_TMP_ACQUIRE__c</referenceTo>
    <relationshipLabel>법인카드청구내역 (매입내역(취소))</relationshipLabel>
    <relationshipName>CorporateCardBilling_CATS_TMP_ACQUIRE2</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/fields/BillingAmount__c.field-meta.xml
<CustomField>
    <fullName>BillingAmount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>결제금액</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/fields/BillingDate__c.field-meta.xml
<CustomField>
    <fullName>BillingDate__c</fullName>
    <label>결제일시</label>
    <type>DateTime</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/fields/BusinessType__c.field-meta.xml
<CustomField>
    <fullName>BusinessType__c</fullName>
    <label>업종</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/fields/CancelClassification__c.field-meta.xml
<CustomField>
    <fullName>CancelClassification__c</fullName>
    <label>매출취소구분</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/fields/CardNumber__c.field-meta.xml
<CustomField>
    <fullName>CardNumber__c</fullName>
    <label>카드번호</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/fields/CorporateCard__c.field-meta.xml
<CustomField>
    <fullName>CorporateCard__c</fullName>
    <label>법인카드</label>
    <referenceTo>CorporateCard__c</referenceTo>
    <relationshipLabel>법인카드청구내역</relationshipLabel>
    <relationshipName>CorporateCardBilling_CorporateCard</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/fields/CountryType__c.field-meta.xml
<CustomField>
    <fullName>CountryType__c</fullName>
    <label>국내외구분</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/fields/ExpectedBillingDate__c.field-meta.xml
<CustomField>
    <fullName>ExpectedBillingDate__c</fullName>
    <label>청구일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/fields/Seq__c.field-meta.xml
<CustomField>
    <fullName>Seq__c</fullName>
    <externalId>true</externalId>
    <label>매입 일련번호</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/fields/StoreAddress__c.field-meta.xml
<CustomField>
    <fullName>StoreAddress__c</fullName>
    <label>소재지</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/fields/StoreBusinessNumber__c.field-meta.xml
<CustomField>
    <fullName>StoreBusinessNumber__c</fullName>
    <label>사업자번호</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/fields/StoreName__c.field-meta.xml
<CustomField>
    <fullName>StoreName__c</fullName>
    <label>가맹점명</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/fields/Tips1__c.field-meta.xml
<CustomField>
    <fullName>Tips1__c</fullName>
    <label>봉사료</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <label>부가세</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/fields/VATYN__c.field-meta.xml
<CustomField>
    <fullName>VATYN__c</fullName>
    <label>부가세 YN</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/CorporateCardBillingMappingA_ba.cls
/************************************************************************************
 * Description : 매입내역(CATS_TMP_ACQUIRE__c)을 법인카드청구내역(CorporateCardBilling__c)로
 *               데이터 매핑작업 배치
 *
 * Ver      Date           Author          Modification
 * ===================================================================================
   1.0      2024-12-09     yr.lee          Create
*************************************************************************************/

public with sharing class CorporateCardBillingMappingA_ba implements Database.Batchable<sObject> {
    public Database.QueryLocator start(Database.BatchableContext bc) {
        Date dateLastMonth = Date.today().addMonths(-1);
        Integer year = dateLastMonth.year();
        Integer month = dateLastMonth.month();
        Date batchMonthStart = Date.newInstance(year, month, 1); // 해당월의 1일
        Date batchMonthEnd = dateLastMonth.toStartOfMonth().addMonths(1).addDays(-1); // 해당월의 말일
        String strBatchMonthStart = String.valueOf(batchMonthStart);
        String strBatchMonthEnd = String.valueOf(batchMonthEnd);

        String strQuery;
        strQuery =  ' SELECT Id, CardNo__c, PurchTot__c, Abroad__c, MccName__c, Class__c,' +
                ' SettDate__c, MerchAddr1__c, MerchBizNo__c, MerchName__c, PurchDate__c, PurchTime__c,' +
                ' VAT__c, VATYN__c, Tips1__c, Seq__c, ApprDate__c ';
        strQuery += ' FROM   CATS_TMP_ACQUIRE__c';
        strQuery += ' WHERE  ApprDate__c  >= :strBatchMonthStart '; 
        strQuery += ' AND    ApprDate__c  <= :strBatchMonthEnd ';
        System.debug('CorporateCardBillingMappingA_ba Query : ' + strQuery);

        return Database.getQueryLocator(strQuery);
    }

    public void execute(Database.BatchableContext bc, List<CATS_TMP_ACQUIRE__c> listTarget) {
        try {
            System.debug('listTarget :: ' + listTarget);
            Set<String> setCardNo = new Set<String>();
            Map<String, Id> mapCardNo = new Map<String, Id>();
            for(CATS_TMP_ACQUIRE__c objCTA : listTarget){
                setCardNo.add(objCTA.CardNo__c);
            }
            List<CorporateCard__c> listCorporateCards = [
                    SELECT Id, CardNumber__c
                    FROM CorporateCard__c
                    WHERE CardNumber__c IN :setCardNo
            ];
            for(CorporateCard__c objCC : listCorporateCards){
                mapCardNo.put(objCC.CardNumber__c, objCC.Id);
            }


            List<CorporateCardBilling__c> listCCBUpsert = new List<CorporateCardBilling__c>();
            CorporateCardBilling__c objTemp;
            for(CATS_TMP_ACQUIRE__c objCTA : listTarget){
                objTemp = new CorporateCardBilling__c();
                objTemp.CorporateCard__c = mapCardNo.get(objCTA.CardNo__c); //해당 카드번호에 맞는 값 찾기
                objTemp.Seq__c = String.valueOf(objCTA.Seq__c);
                //objTemp.CorporateCard__c = 'a3sF6000000V78pIAC';
                objTemp.CardNumber__c = objCTA.CardNo__c;
                objTemp.BillingAmount__c = objCTA.PurchTot__c;
                objTemp.BusinessType__c = objCTA.MccName__c;
                objTemp.ExpectedBillingDate__c = objCTA.SettDate__c != null ? Date.valueOf(objCTA.SettDate__c) : null;
                objTemp.StoreAddress__c = objCTA.MerchAddr1__c;
                objTemp.StoreBusinessNumber__c = objCTA.MerchBizNo__c;
                objTemp.StoreName__c = objCTA.MerchName__c;
                objTemp.VAT__c = objCTA.VAT__c;
                objTemp.VATYN__c = objCTA.VATYN__c;
                objTemp.Tips1__c = (objCTA.Tips1__c != null && objCTA.Tips1__c != '') ? Decimal.valueOf(objCTA.Tips1__c) : 0;
                objTemp.CountryType__c = '';
                if(objCTA.Abroad__c == 'A') objTemp.CountryType__c = '국내매출';
                if(objCTA.Abroad__c == 'B') objTemp.CountryType__c = '국외매출';
                if(objCTA.Class__c == 'A'){
                    objTemp.CancelClassification__c = '취소없음';
                    objTemp.Acquire__c = objCTA.Id;
                }
                if(objCTA.Class__c == 'B'){
                    objTemp.CancelClassification__c = '매입취소';
                    objTemp.AcquireCancel__c = objCTA.Id;
                }

                //BillingDate__c 설정
                String strDate = objCTA.ApprDate__c;
                String strTime = objCTA.PurchTime__c;
                if(objCTA.PurchTime__c == null || objCTA.PurchTime__c == '') strTime = '000000';
                if(strTime.length() != 6) strTime = '000000';

                //BillingDate__c 설정 - 시, 분, 초
                Integer hour = Integer.valueOf(strTime.substring(0, 2));
                Integer minute = Integer.valueOf(strTime.substring(2, 4));
                Integer second = Integer.valueOf(strTime.substring(4, 6));
                //BillingDate__c 설정 - 년, 월, 일
                Integer year = Integer.valueOf(strDate.substring(0, 4));
                Integer month = Integer.valueOf(strDate.substring(5, 7));
                Integer day = Integer.valueOf(strDate.substring(8, 10));
                Datetime billingDatetime = Datetime.newInstance(year, month, day, hour, minute, second);
                objTemp.BillingDate__c = billingDatetime;
                listCCBUpsert.add(objTemp);
                System.debug('objTemp :: ' + objTemp);
            }
            upsert listCCBUpsert Seq__c;
        }
        catch(Exception e) {
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            String[] to = new String[]{
                    'yerin.lee@daeunextier.com'
            };
            email.setToAddresses(to);
            email.setSubject('대유넥스티어 법인카드경비신청 Batch 에러');
            String body = '[Error Message]<br/>';
            body += e.getMessage();
            body += '<br/><br/>[Line Number]<br/>';
            body += e.getLineNumber();
            body += '<br/><br/>[Cause]<br/>';
            body += e.getCause();
            body += '<br/><br/>[Type Name]<br/>';
            body += e.getTypeName();
            email.setHtmlBody(body);
            System.debug('body :: ' + e.getMessage());
            OrgWideEmailAddress[] emailAddress = [SELECT Id FROM OrgWideEmailAddress WHERE Address = 'admin@daeunextier.com'];
            if(emailAddress.size() > 0){
                email.setOrgWideEmailAddressId(emailAddress.get(0).Id);
            }
            if(!Test.isRunningTest()) Messaging.sendEmail(new Messaging.SingleEmailMessage[]{email});
        }
    }

    public void finish(Database.BatchableContext bc) {

    }
}