PA_Education/TestMenifest/force-app/main/default/objects/Account/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <externalId>true</externalId>
    <label>코드</label>
    <length>2</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Account/fields/ShortName__c.field-meta.xml
<CustomField>
    <fullName>ShortName__c</fullName>
    <inlineHelpText>거래처를 식별할 수 있는 10자 이내의 짧은 명칭을 입력하세요.
계정 이름(Account.Name)은 사업자 등록증 상의 정식 명칭입니다.</inlineHelpText>
    <label>계정 이름(약어)</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>재고</label>
    <nameField>
        <label>재고코드</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Inventory__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>제조사</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.IsTypePurchase__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>재고</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Inventory__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>품목</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>재고</relationshipLabel>
    <relationshipName>Item</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Inventory__c/fields/ProcessProduct__c.field-meta.xml
<CustomField>
    <fullName>ProcessProduct__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>생산공정</label>
    <referenceTo>ProcessProduct__c</referenceTo>
    <relationshipLabel>재고</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Inventory__c/fields/Seq__c.field-meta.xml
<CustomField>
    <fullName>Seq__c</fullName>
    <label>Seq</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Inventory__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>창고</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>재고</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>품목</label>
    <nameField>
        <label>품목명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Item__c/fields/BarcodeStructure__c.field-meta.xml
<CustomField>
    <fullName>BarcodeStructure__c</fullName>
    <label>바코드 체계</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Item__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <externalId>true</externalId>
    <label>품목코드</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ProcessInfo__c/ProcessInfo__c.object-meta.xml
<CustomObject>
    <label>제품 BOM</label>
    <nameField>
        <label>이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/ProcessInfo__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>모든 공정 후 생산되는 품목</description>
    <inlineHelpText>모든 공정 후 생산되는 품목</inlineHelpText>
    <label>최종품목</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipName>ProcessInfo</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ProcessInfoDetail__c/ProcessInfoDetail__c.object-meta.xml
<CustomObject>
    <label>제품 BOM 상세</label>
    <nameField>
        <displayFormat>PID-{000000}</displayFormat>
        <label>공정상세정보 코드</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/ProcessInfoDetail__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>품목</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipName>ProcessInfoDetail</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ProcessInfoDetail__c/fields/ProcessInfo__c.field-meta.xml
<CustomField>
    <fullName>ProcessInfo__c</fullName>
    <label>공정정보</label>
    <referenceTo>ProcessInfo__c</referenceTo>
    <relationshipName>ProcessInfoDetail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ProcessInfoDetail__c/fields/Seq__c.field-meta.xml
<CustomField>
    <fullName>Seq__c</fullName>
    <label>공정상세순서</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ProcessProduct__c/ProcessProduct__c.object-meta.xml
<CustomObject>
    <label>생산공정</label>
    <nameField>
        <displayFormat>PP-{000000}</displayFormat>
        <label>생산공정 코드</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/ProcessProduct__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>날짜</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ProcessProduct__c/fields/ProcessInfo__c.field-meta.xml
<CustomField>
    <fullName>ProcessInfo__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>공정정보</label>
    <referenceTo>ProcessInfo__c</referenceTo>
    <relationshipLabel>생산공정</relationshipLabel>
    <relationshipName>ProcessProduct</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>창고</label>
    <nameField>
        <label>창고명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/classes/ObjectCreateTester.cls
/**
 * Object		: ObjectCreateTester.cls
 * Function		: 
 * Author		: Yohan.Kang.
 * Date			: 2015.2.28
 * Description	: 
 		Trigger 테스트에서 생성되는 개체 모음
 */
public with sharing class ObjectCreateTester {
    public static Account AC{
    	get{
    		if(AC==null){
		    	AC = new Account();
		    	AC.Name = 'Test Account';
		    	AC.Code__c = 'XZ';
				AC.ShortName__c = 'Test short Name';
    		}
	    	return AC;
    	}
    	private set;
    }
    //창고
    public static Warehouse__c WH{
    	get{
    		if(WH==null){
    			WH = new Warehouse__c();
    			WH.Name = '테스트 창고';
    		}
    		return WH;
    	}
    	private set;
    }
    //품목 Item__c
    public static Item__c IT{
    	get{
    		if(IT==null){
    			IT= new Item__c();
    			IT.Name = 'Test 품목';
    			IT.Code__c = 'Z99999911';
    			IT.BarcodeStructure__c = '{제품명}{수량(4)}{제조사}{제조일}{00}';
    		}
    		return IT;
    	}
    	private set;
    }
	
    public static Item__c subIT{
    	get{
    		if(subIT==null){
    			subIT= new Item__c();
    			subIT.Name = 'Test 품목2';
    			subIT.Code__c = 'Z99999912';
    			subIT.BarcodeStructure__c = '{제품명}{수량(4)}{제조사}{제조일}{00}';
    		}
    		return subIT;
    	}
    	private set;
    }	
	
    //재고 Inventory__c
    public static Inventory__c IV{
    	get{
    		if(IV==null){
    			IV = new Inventory__c();
    			
    			if(AC.ID==null) insert AC;
    			IV.Account__c = AC.Id;
    			
    			if(WH.Id==null) insert WH;
    			IV.Warehouse__c = WH.ID;
    			
    			if(IT.ID==null) insert IT;
    			IV.Item__c = IT.Id;
    		}
    		return IV;
    	}
    	private set;
    }
    
    //공정정보 ProcessInfo__c
    public static ProcessInfo__c PI{
    	get{
    		if(PI==null){
    			PI = new ProcessInfo__c();
    			
    			if(IT.Id==null) insert IT;
    			PI.Item__c = IT.Id;
    		}
    		return PI;
    	}
    	private set;
    }
    
    //공정상세정보 ProcessInfoDetail__c
    public static ProcessInfoDetail__c PID{
    	get{
    		if(PID==null){
    			PID = new ProcessInfoDetail__c();
    			
    			if(PI.Id==null) insert PI;
    			PID.ProcessInfo__c = PI.Id;
    			
    			if(SubIT.Id==null) insert SubIT;
    			PID.Item__c = SubIT.Id;
    			
    			PID.Seq__c = 1;
    		}
    		return PID;
    	}
    	private set;
    }
    
    //생산공정
    public static ProcessProduct__c PP{
    	get{
    		if(PP==null){
    			PP = new ProcessProduct__c();
    			PP.Date__c = system.today();
    		}
    		return PP;
    	}
    	private set;
    }
}