PA_Education/TestMenifest/force-app/main/default/objects/Account/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <externalId>true</externalId>
    <label>코드</label>
    <length>2</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Account/fields/ShortName__c.field-meta.xml
<CustomField>
    <fullName>ShortName__c</fullName>
    <inlineHelpText>거래처를 식별할 수 있는 10자 이내의 짧은 명칭을 입력하세요.
계정 이름(Account.Name)은 사업자 등록증 상의 정식 명칭입니다.</inlineHelpText>
    <label>계정 이름(약어)</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>재고</label>
    <nameField>
        <label>재고코드</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Inventory__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>제조사</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.IsTypePurchase__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>재고</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Inventory__c/fields/Assemset_Seq__c.field-meta.xml
<CustomField>
    <fullName>Assemset_Seq__c</fullName>
    <label>Assemset_Seq</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Inventory__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>품목</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>재고</relationshipLabel>
    <relationshipName>Item</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Inventory__c/fields/PartList__c.field-meta.xml
<CustomField>
    <fullName>PartList__c</fullName>
    <description>부품이 아닐경우 이 재고를 제작하는데 사용한 재고 코드 모음 (쉼표(,) 로 구분)</description>
    <label>PartList</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Inventory__c/fields/ProcessProduct__c.field-meta.xml
<CustomField>
    <fullName>ProcessProduct__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>생산공정</label>
    <referenceTo>ProcessProduct__c</referenceTo>
    <relationshipLabel>재고</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>품목</label>
    <nameField>
        <label>품목명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Item__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <externalId>true</externalId>
    <label>품목코드</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Item__c/fields/ProductItem__c.field-meta.xml
<CustomField>
    <fullName>ProductItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Tray, Box일경우 포함되어 있는 제품</description>
    <inlineHelpText>Tray, Box일경우 포함되어 있는 제품</inlineHelpText>
    <label>제품품목</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>품목</relationshipLabel>
    <relationshipName>PackageItem</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Outsoursing__c/Outsoursing__c.object-meta.xml
<CustomObject>
    <label>외주처리</label>
    <nameField>
        <displayFormat>OS{000000}</displayFormat>
        <label>외주처리 코드</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Outsoursing__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>업체</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>외주처리</relationshipLabel>
    <relationshipName>Outsoursing</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Outsoursing__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <label>재고</label>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>외주처리</relationshipLabel>
    <relationshipName>Outsoursing</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Outsoursing__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>품목</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>외주처리</relationshipLabel>
    <relationshipName>Outsoursing</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ProcessProduct__c/ProcessProduct__c.object-meta.xml
<CustomObject>
    <label>생산공정</label>
    <nameField>
        <displayFormat>PP-{000000}</displayFormat>
        <label>생산공정 코드</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/ProcessProduct__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>날짜</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ProcessProduct__c/fields/PartList__c.field-meta.xml
<CustomField>
    <fullName>PartList__c</fullName>
    <label>PartList</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ProcessProduct__c/fields/TraceabilityAssemsetId__c.field-meta.xml
<CustomField>
    <fullName>TraceabilityAssemsetId__c</fullName>
    <externalId>true</externalId>
    <label>TraceabilityAssemsetId</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/Outsoursing_tr_test.cls
/**
 * @description       : 
 *                      
 * @author            : hyunsoo.song@daeunextier.com
 * @group             :
 * @last modified on  : 2022-11-14
 * @last modified by  : hyunsoo.song@daeunextier.com
 * Modifications Log
 * Ver     Date             Author               Modification
 * 1.0   2022-11-14   hyunsoo.song@daeunextier.com   Initial Version
 */
@isTest
public with sharing class Outsoursing_tr_test {
    @isTest
    static void doTest(){
        Account AC = new Account();
        AC.Name = '테스트계정';
        AC.ShortName__c ='Test Short Name';
        insert AC;

        Item__c MasterIT = new Item__c();
        MasterIT.Name = '품목마스터';
        MasterIT.Code__c = 'ZX0000001';
        insert MasterIT;

        Item__c IT = new Item__c();
        IT.Name = '품목테스트';
        IT.Code__c = 'ZZ0000001';
        IT.ProductItem__c = MasterIT.Id;
        insert IT;

        ProcessProduct__c PP = new ProcessProduct__c();
        PP.Date__c = system.today();
        PP.PartList__c = IT.Code__c;
        PP.TraceabilityAssemsetId__c = 1;
        insert PP;


        Inventory__c IV = new Inventory__c();
        IV.Name = 'ZZ0000001000001';
        IV.Account__c = AC.id;
        IV.Item__c = IT.Id;
        IV.Assemset_Seq__c = 1;
        insert IV;

        Test.startTest();

        Outsoursing__c OS = new Outsoursing__c();
        OS.Item__c = IT.Id;
        OS.Inventory__c = IV.Id;
        insert OS;

        Test.stopTest();
    }
}