PA_Education/TestMenifest/force-app/main/default/objects/Account/fields/ShortName__c.field-meta.xml
<CustomField>
    <fullName>ShortName__c</fullName>
    <inlineHelpText>거래처를 식별할 수 있는 10자 이내의 짧은 명칭을 입력하세요.
계정 이름(Account.Name)은 사업자 등록증 상의 정식 명칭입니다.</inlineHelpText>
    <label>계정 이름(약어)</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ApprovalRelateList__c/ApprovalRelateList__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Use ApprovalRelateList 
page name : ApprovalRelatedListController_cls</description>
    <label>ApprovalRelateList</label>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/ApprovalRelateList__c/fields/ObjectType__c.field-meta.xml
<CustomField>
    <fullName>ObjectType__c</fullName>
    <label>ObjectType</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ApprovalRelateList__c/fields/RelatedObject__c.field-meta.xml
<CustomField>
    <fullName>RelatedObject__c</fullName>
    <label>RelatedObject</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ApprovalRelateList__c/fields/RelateObjectIcon__c.field-meta.xml
<CustomField>
    <fullName>RelateObjectIcon__c</fullName>
    <label>RelateObjectIcon</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense Application</label>
    <nameField>
        <displayFormat>EP-{YYYYMM}-{000000}</displayFormat>
        <label>경비신청 코드</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>승인상태</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Writing</fullName>
                <default>true</default>
                <label>작성</label>
            </value>
            <value>
                <fullName>Consider</fullName>
                <label>승인검토중</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>승인완료</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>승인거부</label>
            </value>
            <value>
                <fullName>Recall</fullName>
                <label>회수됨</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/Approver1__c.field-meta.xml
<CustomField>
    <fullName>Approver1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ExpenseApprover1</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>비고</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/FirstExpenseRequest__c.field-meta.xml
<CustomField>
    <fullName>FirstExpenseRequest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>일반 사원일 경우 &apos;사업부장/PM&apos;선택 &amp;&amp;
사업부장/PM일 경우 &apos;이응도 전무님&apos;선택</inlineHelpText>
    <label>1차 승인자 지정</label>
    <referenceTo>User</referenceTo>
    <relationshipName>FirstExpenseRequest</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Expense Application</relationshipLabel>
    <relationshipName>ExpenseApplication</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/SecondApproverSelection__c.field-meta.xml
<CustomField>
    <fullName>SecondApproverSelection__c</fullName>
    <defaultValue>false</defaultValue>
    <label>2차 승인 여부 (사업부장 / 팀장)</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>경비 구분</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>개인경비</fullName>
                <default>true</default>
                <label>개인경비</label>
            </value>
            <value>
                <fullName>법인카드</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/UseMonth__c.field-meta.xml
<CustomField>
    <fullName>UseMonth__c</fullName>
    <defaultValue>TEXT( MONTH( ADDMONTHS( TODAY() ,-1) ) )</defaultValue>
    <inlineHelpText>신청할 경비내역의 사용월을 입력합니다.</inlineHelpText>
    <label>경비 사용 월</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/UseYear__c.field-meta.xml
<CustomField>
    <fullName>UseYear__c</fullName>
    <defaultValue>TEXT( YEAR(  ADDMONTHS(TODAY(),-1)  ) )</defaultValue>
    <inlineHelpText>신청할 경비내역의 연도를 입력합니다.</inlineHelpText>
    <label>경비 사용 연도</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2013</fullName>
            </value>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
                <default>true</default>
                <label>2022</label>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/ExpenseDetail__c.object-meta.xml
<CustomObject>
    <label>Expense Detail</label>
    <nameField>
        <displayFormat>EPD-{000000}</displayFormat>
        <label>경비신청 상세 ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>경비신청금액</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Category1__c.field-meta.xml
<CustomField>
    <fullName>Category1__c</fullName>
    <label>사용목적</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category1</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Category2__c.field-meta.xml
<CustomField>
    <fullName>Category2__c</fullName>
    <label>비용구분</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category2</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>사용일시</label>
    <type>DateTime</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>내용</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Expense__c.field-meta.xml
<CustomField>
    <fullName>Expense__c</fullName>
    <label>경비신청 ID</label>
    <referenceTo>Expense__c</referenceTo>
    <relationshipName>ExpenseDetail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/ProjectBudget__c.field-meta.xml
<CustomField>
    <fullName>ProjectBudget__c</fullName>
    <formula>1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>프로젝트 예산</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>필요 시 회계 담당자가 수정.</inlineHelpText>
    <label>계정구분</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ExpenseType</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>프로젝트에 대한 기본정보를 관리하며, Deal Closing 이후 생성한다. 영업담당자가 계약 체결 후 기초 데이터를 작성하며, 프로젝트 진행 중에는 PM이 관리하고, 대금청구/지급 관련 정보는 회계에서 관리한다.</description>
    <label>프로젝트</label>
    <nameField>
        <label>프로젝트 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/ProjectBudget__c/ProjectBudget__c.object-meta.xml
<CustomObject>
    <label>프로젝트 비용 예산</label>
    <nameField>
        <label>프로젝트 비용 예산 신청명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/ProjectBudget__c/fields/Approver1__c.field-meta.xml
<CustomField>
    <fullName>Approver1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>BudgetApprover1</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ProjectBudget__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>비고</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ProjectBudget__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>프로젝트</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>프로젝트 비용 예산</relationshipLabel>
    <relationshipName>ProjectBudget</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ProjectBudgetDetail__c/ProjectBudgetDetail__c.object-meta.xml
<CustomObject>
    <label>프로젝트 비용 예산 상세</label>
    <nameField>
        <displayFormat>P-EXP-{YY}{MM}-{000}</displayFormat>
        <label>프로젝트 예산</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/ProjectBudgetDetail__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <formula>UnitPrice__c  *  Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>단가 * 수량</inlineHelpText>
    <label>금액</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ProjectBudgetDetail__c/fields/Category2__c.field-meta.xml
<CustomField>
    <fullName>Category2__c</fullName>
    <label>예산 구분</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category2</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ProjectBudgetDetail__c/fields/ProjectBudget__c.field-meta.xml
<CustomField>
    <fullName>ProjectBudget__c</fullName>
    <label>프로젝트 비용 예산</label>
    <referenceTo>ProjectBudget__c</referenceTo>
    <relationshipLabel>프로젝트 비용 예산 상세</relationshipLabel>
    <relationshipName>ProjectBudgetDetail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/ApprovalRelatedListController_Test.cls
@isTest
public  class ApprovalRelatedListController_Test {
    @isTest 
    static void test1() {

        /*ProcessInstanceStep*/
        /*processInstanceWorkItemList*/
        
         // Setup test data
        // This code runs as the system user
        
		/*1 .user Id*/
		
		Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
       	User user = new User(Alias = 'User'
                            , Email='SysAdminTestuser@earth.org'
                            , EmailEncodingKey='UTF-8'
                            , LastName='Testing'
                            , LanguageLocaleKey='en_US'
                            , LocaleSidKey='en_US'
                            , EmployeeNumber='AC100000'
                            , TimeZoneSidKey='Asia/Seoul'
                            , ProfileId = p.Id
                            , UserName='SysAdminTestuser@earth.org');
        insert user;

        /*Manager 및 2차승인자*/
        User user1 = new User(Alias = 'User1'
                            , Email='SysAdminTestuser1@earth.org'
                            , EmailEncodingKey='UTF-8'
                            , LastName='Testing1'
                            , LanguageLocaleKey='en_US'
                            , LocaleSidKey='en_US'
                            , EmployeeNumber='AC100001'
                            , TimeZoneSidKey='Asia/Seoul'
                            , ProfileId = p.Id
                            , UserName='SysAdminTestuser1@earth.org');
        insert user1;
        user.ManagerId = user1.Id;
        update user;

        /*1차승인자*/
        User user2 = new User(Alias = 'User2'
                            , Email='SysAdminTestuser1@earth.org'
                            , EmailEncodingKey='UTF-8'
                            , LastName='Testing2'
                            , LanguageLocaleKey='en_US'
                            , LocaleSidKey='en_US'
                            , EmployeeNumber='AC100002'
                            , TimeZoneSidKey='Asia/Seoul'
                            , ProfileId = p.Id
                            , UserName='SysAdminTestuser2@earth.org');
        insert user2;

        /*변경할 1차승인자*/
        User user3 = new User(Alias = 'User3'
                            , Email='SysAdminTestuser3@earth.org'
                            , EmailEncodingKey='UTF-8'
                            , LastName='Testing2'
                            , LanguageLocaleKey='en_US'
                            , LocaleSidKey='en_US'
                            , EmployeeNumber='AC100003'
                            , TimeZoneSidKey='Asia/Seoul'
                            , ProfileId = p.Id
                            , UserName='SysAdminTestuser3@earth.org');
        insert user3;

        String strYear = String.valueOf(System.today().year());
        String strMonth = String.valueOf(System.today().month());
		Expense__c expense2 = new Expense__c(FirstExpenseRequest__c = user.Id,
											UseYear__c = strYear,
											UseMonth__c = strMonth);
		insert expense2;

		ExpenseDetail__c expDetail = new ExpenseDetail__c(
											Expense__c = expense2.Id,
											Category1__c = '본사행정',
											Category2__c = '식비',
											Description__c ='경비신청.',
											Amount__c = 1000,
											Date__c = system.today()
        									);
		insert expDetail;


        Expense__c expense = new Expense__c();
        expense.ApprovalStatus__c = '작성';
        //expense.Type__c = '개인경비';
        expense.UseMonth__c = strMonth;
        expense.UseYear__c = strYear;
        expense.OwnerId = user.Id;
        expense.FirstExpenseRequest__c = user1.Id;
        expense.SecondApproverSelection__c = false;
        //expense.Approver1__c = user2.Id;
        insert expense;

        expense.FirstExpenseRequest__c = user3.Id;
        expense.SecondApproverSelection__c = true;
        update expense;
        Id id = user.Id;
        String userId = String.valueOf(id);

		project__c projectObj = new project__c();
        insert projectObj;

        ProjectBudget__c projectBudject = new ProjectBudget__c();
        projectBudject.Name = '[ABC상사]20181126-0000018 예산 신청';
        projectBudject.project__c = projectObj.Id;

        insert projectBudject;

        ProjectBudgetDetail__c bugetDetail = new ProjectBudgetDetail__c();
        bugetDetail.ProjectBudget__c = projectBudject.Id;
        insert bugetDetail;

        // Create an approval request for the expense

    	Account a = new Account(Name='Example');
        a.shortName__c = 'mh';
        insert a;

        ApprovalRelateList__c approvalRelated = new ApprovalRelateList__c();
        approvalRelated.ObjectType__c='Expense__c';
        approvalRelated.RelatedObject__c='ExpenseDetail__c:Expense__c';
        approvalRelated.RelateObjectIcon__c='ExpenseIcon__c:Expense__c';
        approvalRelated.Name= 'ApprovalRelateList';
        insert approvalRelated;

       	// ProcessInstanceId 가져오기
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(expense.Id);
        req1.setSubmitterId(user3.Id);
        req1.setProcessDefinitionNameOrId('New_Expenses_Approval2');
        req1.setSkipEntryCriteria(true);

        Approval.ProcessResult result = Approval.process(req1);

        system.debug('result.status:::'+result.getInstanceStatus());

        List<ProcessInstanceStep> instanceStepList = [SELECT Id, ProcessInstanceId FROM ProcessInstanceStep WHERE ProcessInstanceId =: result.getInstanceId()];

        List<ApprovalRelatedListController.wrapTargetObj> resultList1 = new List<ApprovalRelatedListController.wrapTargetObj>();
        //List<ApprovalRelatedListController.wrapTargetObj> resultList2 = new List<ApprovalRelatedListController.wrapTargetObj>();

		Test.startTest();

        ApprovalRelatedListController.doInit(instanceStepList[0].Id);

        expense.Approver1__c = user2.Id;
        update expense;

        Approval.ProcessSubmitRequest req2 = new Approval.ProcessSubmitRequest();
        req2.setComments('Submitting request for approval.');
        req2.setObjectId(expense.Id);
        req2.setSubmitterId(user3.Id);
        req2.setProcessDefinitionNameOrId('New_Expenses_Approval2');
        req2.setSkipEntryCriteria(true);

        Approval.ProcessResult result2 = Approval.process(req2);

        system.debug('result.status2:::'+result2.getInstanceStatus());

        List<ProcessInstanceWorkitem> processInstanceWorkItemList = [SELECT Id, ProcessInstanceId FROM ProcessInstanceWorkitem WHERE ProcessInstanceId =: result2.getInstanceId()];

		ApprovalRelatedListController.doInit(processInstanceWorkItemList[0].Id);

        Test.stopTest();

		    	 
   }
}