PA_Education/TestMenifest/force-app/main/default/objects/Account/fields/ShortName__c.field-meta.xml
<CustomField>
    <fullName>ShortName__c</fullName>
    <inlineHelpText>거래처를 식별할 수 있는 10자 이내의 짧은 명칭을 입력하세요.
계정 이름(Account.Name)은 사업자 등록증 상의 정식 명칭입니다.</inlineHelpText>
    <label>계정 이름(약어)</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Budget__c/Budget__c.object-meta.xml
<CustomObject>
    <label>예산</label>
    <nameField>
        <label>예산이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Budget__c/fields/BudgetAmount__c.field-meta.xml
<CustomField>
    <fullName>BudgetAmount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>예산금액 (입력용)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Budget__c/fields/BudgetType__c.field-meta.xml
<CustomField>
    <fullName>BudgetType__c</fullName>
    <label>예산배정단위</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BudgetType</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Budget__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>비고</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Budget__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>BudgetProject</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Budget__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>연도</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
            <value>
                <fullName>2036</fullName>
            </value>
            <value>
                <fullName>2037</fullName>
            </value>
            <value>
                <fullName>2038</fullName>
            </value>
            <value>
                <fullName>2039</fullName>
            </value>
            <value>
                <fullName>2040</fullName>
            </value>
            <value>
                <fullName>2041</fullName>
            </value>
            <value>
                <fullName>2042</fullName>
            </value>
            <value>
                <fullName>2043</fullName>
            </value>
            <value>
                <fullName>2044</fullName>
            </value>
            <value>
                <fullName>2045</fullName>
            </value>
            <value>
                <fullName>2046</fullName>
            </value>
            <value>
                <fullName>2047</fullName>
            </value>
            <value>
                <fullName>2048</fullName>
            </value>
            <value>
                <fullName>2049</fullName>
            </value>
            <value>
                <fullName>2050</fullName>
            </value>
            <value>
                <fullName>2051</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense Application</label>
    <nameField>
        <displayFormat>EP-{YYYYMM}-{000000}</displayFormat>
        <label>경비신청 코드</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>예산</label>
    <referenceTo>Budget__c</referenceTo>
    <relationshipLabel>Expense Application</relationshipLabel>
    <relationshipName>Expense_Application</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/BudgetType__c.field-meta.xml
<CustomField>
    <fullName>BudgetType__c</fullName>
    <label>사용목적</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BudgetType</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>비고</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/FirstExpenseRequest__c.field-meta.xml
<CustomField>
    <fullName>FirstExpenseRequest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>일반 사원일 경우 &apos;사업부장/PM&apos;선택 &amp;&amp;
사업부장/PM일 경우 &apos;이응도 전무님&apos;선택</inlineHelpText>
    <label>1차 승인자 지정</label>
    <referenceTo>User</referenceTo>
    <relationshipName>FirstExpenseRequest</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethod__c</fullName>
    <label>결제방식</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>개인카드/현금</fullName>
                <default>true</default>
                <label>개인카드/현금</label>
            </value>
            <value>
                <fullName>법인카드</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Expense Application</relationshipLabel>
    <relationshipName>ExpenseApplication</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/UseMonth__c.field-meta.xml
<CustomField>
    <fullName>UseMonth__c</fullName>
    <defaultValue>TEXT( MONTH( ADDMONTHS( TODAY() ,-1) ) )</defaultValue>
    <inlineHelpText>신청할 경비내역의 사용월을 입력합니다.</inlineHelpText>
    <label>경비 사용 월</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/UseYear__c.field-meta.xml
<CustomField>
    <fullName>UseYear__c</fullName>
    <defaultValue>TEXT( YEAR(  ADDMONTHS(TODAY(),-1)  ) )</defaultValue>
    <inlineHelpText>신청할 경비내역의 연도를 입력합니다.</inlineHelpText>
    <label>경비 사용 연도</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2013</fullName>
            </value>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
                <default>true</default>
                <label>2022</label>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/ExpenseDetail__c.object-meta.xml
<CustomObject>
    <label>Expense Detail</label>
    <nameField>
        <displayFormat>EPD-{000000}</displayFormat>
        <label>경비신청 상세 ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>경비신청금액</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Category1__c.field-meta.xml
<CustomField>
    <fullName>Category1__c</fullName>
    <label>사용목적</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category1</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Category2__c.field-meta.xml
<CustomField>
    <fullName>Category2__c</fullName>
    <label>비용구분</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category2</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>사용일시</label>
    <type>DateTime</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>내용</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Expense__c.field-meta.xml
<CustomField>
    <fullName>Expense__c</fullName>
    <label>경비신청 ID</label>
    <referenceTo>Expense__c</referenceTo>
    <relationshipName>ExpenseDetail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Oppty</label>
    <nameField>
        <label>영업기회 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Opportunity__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>고객사</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Opportunity__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>사업금액</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Opportunity__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>9. 기타 정보</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Opportunity__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>상위 영업기회</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>프로젝트에 대한 기본정보를 관리하며, Deal Closing 이후 생성한다. 영업담당자가 계약 체결 후 기초 데이터를 작성하며, 프로젝트 진행 중에는 PM이 관리하고, 대금청구/지급 관련 정보는 회계에서 관리한다.</description>
    <label>프로젝트</label>
    <nameField>
        <label>프로젝트 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/recordTypes/Project.recordType-meta.xml
<RecordType>
    <fullName>Project</fullName>
    <active>true</active>
    <description>프로젝트 사항 입력하는 Record Type</description>
    <label>프로젝트</label>
</RecordType>

PA_Education/TestMenifest/force-app/main/default/classes/ExpenseCreationCorporateCardCtrl_test.cls
/**
 * Created by Kwanwoo.Jeon on 2024-01-16.
 */

@IsTest
private class ExpenseCreationCorporateCardCtrl_test {
    @TestSetup
    static void setUp(){
        List<Budget__c> listBudget = new List<Budget__c>();

        listBudget.add(new Budget__c(
                Name = 'test',
                Year__c = string.valueOf(Date.today().year() -1),
                BudgetAmount__c = 10000000,
                BudgetType__c = '본사행정'
        ));
        listBudget.add(new Budget__c(
                Name = 'test2',
                Year__c = string.valueOf(Date.today().year()),
                BudgetAmount__c = 10000000,
                BudgetType__c = '본사행정'
        ));
        listBudget.add(new Budget__c(
                Name = 'test',
                Year__c = string.valueOf(Date.today().year() -1),
                BudgetAmount__c = 10000000,
                BudgetType__c = '영업'
        ));
        listBudget.add(new Budget__c(
                Name = 'test',
                Year__c = string.valueOf(Date.today().year() -1),
                BudgetAmount__c = 10000000,
                BudgetType__c = '임원 및 감사님'
        ));
        insert listBudget;
    }

    @IsTest
    static void doTest() {
        Test.startTest();

        Account acc = new Account(Name = 'Test 계정',
                ShortName__c = 'test');
        List<Account> acclist = new List<Account>();
        acclist.add(acc);
        insert acclist;

        Opportunity__c oppty = new Opportunity__c(Name = 'test 영업기회', AccountId__c = acc.Id);
        List<Opportunity__c> opptyList = new List<Opportunity__c>();
        opptyList.add(oppty);
        insert opptyList;

        Project__c project = new Project__c(Name = '본사공통');
        List<Project__c> projectList = new List<Project__c>();
        projectList.add(project);
        insert projectList;

        Project__c project1 = new Project__c(Name = '마케팅');
        List<Project__c> projectList1 = new List<Project__c>();
        projectList1.add(project1);
        insert projectList1;

        Profile p = new Profile();
        p = TestDataFactory.getProfile('System Admin');

        User user = new User(Alias = 'test1'
                , Email='SysAdminTestuser@earth.org'
                , EmailEncodingKey='UTF-8'
                , LastName='test'
                , FirstName='Testing'
                , LanguageLocaleKey='en_US'
                , LocaleSidKey='en_US'
                , EmployeeNumber='AC100000'
                , ProfileId = p.Id
                , TimeZoneSidKey='Asia/Seoul'
                , UserName='systemTestUser@earth.org'
                , Position__c = '9');

        insert user;

        String strYear = String.valueOf(System.today().year() -1);
        String strMonth = String.valueOf(System.today().month());

        Expense__c expense = new Expense__c(FirstExpenseRequest__c = user.Id,
                UseYear__c = strYear,
                UseMonth__c = strMonth,
                BudgetType__c = '본사행정',
                PaymentMethod__c = '법인카드');
        insert expense;

        Expense__c expense2 = new Expense__c(UseYear__c = strYear,
                UseMonth__c = strMonth,
                BudgetType__c = '영업',
                PaymentMethod__c = '법인카드');
        insert expense2;

        ExpenseDetail__c objED = new ExpenseDetail__c(
                Expense__c = expense.Id,
                Category1__c = '본사행정',
                Category2__c = '식비',
                Description__c = '배가고파서 회사카드로 참치를 먹었습니다 죄송합니다.',
                Amount__c = 1000,
                Date__c = system.today()
        );
        insert objED;

        ExpenseDetail__c objE2 = new ExpenseDetail__c(
                Expense__c = expense.Id,
                Category1__c = '본사행정',
                Category2__c = '식비',
                Description__c = '배가고파서 회사카드로 참치를 먹었습니다 죄송합니다.',
                Amount__c = 1000,
                Date__c = system.today()
        );
        insert objE2;

        List<Map<String, Object>> expDetailList = new List<Map<String, Object>>();
        expDetailList.add(new Map<String, Object>{
                'Expense'           => expense.Id,
                'Category1'         => '본사행정',
                'Category2'         => '식비',
                'Description'       => '배가고파서 회사카드로 참치를 먹었습니다 죄송합니다.',
                'Amount'            => 1000,
                'Dt'                => '2024-03-29 19:00:00'
            }
        );


        List<Map<String, Object>> expDetailList3 = new List<Map<String, Object>>();
        expDetailList3.add(new Map<String, Object>{
                'Expense'           => expense2.Id,
                'Category1'         => '영업',
                'Category2'         => '식비',
                'Description'       => 'Sales',
                'ProjectNameId'     => project.Id,
                'Amount'            => 1000,
                'OpportunityNameId' => oppty.Id,
                'PaymentType'       => '개인카드',
                'Dt'                => '2024-03-29 19:00:00'
            }
        );
        expDetailList3.add(new Map<String,Object>{
                'Expense'               => expense2.Id,
                'Category1'             => '영업',
                'Category2'             => '식비',
                'Description'           => 'Sales',
                'ProjectNameId'         => project.Id,
                'Amount'                => 1000,
                'OpportunityNameId'     => oppty.Id,
                'PaymentType'           => '개인카드',
                'Dt'                    => '2024-03-29 19:00:00'
            }
        );

        List<Id> idtemp = new List<Id>();
        idtemp.add(objED.Id);

        ExpenseCreationCorporateCardController.getInitData(expense.Id);
        ExpenseCreationCorporateCardController.getInitData(expense2.Id);

        system.debug(ExpenseCreationCorporateCardController.getPicklistValue('Expense__c', 'UseYear__c'));
        system.debug(ExpenseCreationCorporateCardController.getObjectFieldLabel('Expense__c'));
        system.debug(ExpenseCreationCorporateCardController.doSave(expense, expDetailList, idtemp));
        ExpenseCreationCorporateCardController.doSave(expense, expDetailList3, idtemp);


        Test.stopTest();

    }
}