PA_Education/TestMenifest/force-app/main/default/objects/Account/fields/ShortName__c.field-meta.xml
<CustomField>
    <fullName>ShortName__c</fullName>
    <inlineHelpText>거래처를 식별할 수 있는 10자 이내의 짧은 명칭을 입력하세요.
계정 이름(Account.Name)은 사업자 등록증 상의 정식 명칭입니다.</inlineHelpText>
    <label>계정 이름(약어)</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense Application</label>
    <nameField>
        <displayFormat>EP-{YYYYMM}-{000000}</displayFormat>
        <label>경비신청 코드</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/BudgetType__c.field-meta.xml
<CustomField>
    <fullName>BudgetType__c</fullName>
    <label>사용목적</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BudgetType</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>비고</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/FirstExpenseRequest__c.field-meta.xml
<CustomField>
    <fullName>FirstExpenseRequest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>일반 사원일 경우 &apos;사업부장/PM&apos;선택 &amp;&amp;
사업부장/PM일 경우 &apos;이응도 전무님&apos;선택</inlineHelpText>
    <label>1차 승인자 지정</label>
    <referenceTo>User</referenceTo>
    <relationshipName>FirstExpenseRequest</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethod__c</fullName>
    <label>결제방식</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>개인카드/현금</fullName>
                <default>true</default>
                <label>개인카드/현금</label>
            </value>
            <value>
                <fullName>법인카드</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Expense Application</relationshipLabel>
    <relationshipName>ExpenseApplication</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/UseMonth__c.field-meta.xml
<CustomField>
    <fullName>UseMonth__c</fullName>
    <defaultValue>TEXT( MONTH( ADDMONTHS( TODAY() ,-1) ) )</defaultValue>
    <inlineHelpText>신청할 경비내역의 사용월을 입력합니다.</inlineHelpText>
    <label>경비 사용 월</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/UseYear__c.field-meta.xml
<CustomField>
    <fullName>UseYear__c</fullName>
    <defaultValue>TEXT( YEAR(  ADDMONTHS(TODAY(),-1)  ) )</defaultValue>
    <inlineHelpText>신청할 경비내역의 연도를 입력합니다.</inlineHelpText>
    <label>경비 사용 연도</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2013</fullName>
            </value>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
                <default>true</default>
                <label>2022</label>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/ExpenseDetail__c.object-meta.xml
<CustomObject>
    <label>Expense Detail</label>
    <nameField>
        <displayFormat>EPD-{000000}</displayFormat>
        <label>경비신청 상세 ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>경비신청금액</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Category1__c.field-meta.xml
<CustomField>
    <fullName>Category1__c</fullName>
    <label>사용목적</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category1</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Category2__c.field-meta.xml
<CustomField>
    <fullName>Category2__c</fullName>
    <label>비용구분</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category2</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>사용일시</label>
    <type>DateTime</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>내용</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Expense__c.field-meta.xml
<CustomField>
    <fullName>Expense__c</fullName>
    <label>경비신청 ID</label>
    <referenceTo>Expense__c</referenceTo>
    <relationshipName>ExpenseDetail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>영업 관련 비용은 해당 영업기회를 선택하세요.</inlineHelpText>
    <label>영업기회</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipName>ExpenseDetail_Oppty</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>지출구분</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>개인카드</fullName>
            </value>
            <value>
                <fullName>법인카드</fullName>
            </value>
            <value>
                <fullName>현금</fullName>
            </value>
            <value>
                <fullName>세금계산서</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>2024.1. 기준 사용 X (Expense__c에서 프로젝트 입력)</description>
    <inlineHelpText>내부 경비 처리는 
&apos;본사공통&apos; 프로젝트를 선택하시고 
프로젝트 관련 비용은 해당 프로젝트를 선택하세요.</inlineHelpText>
    <label>프로젝트 (사용X)</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Expense Detail</relationshipLabel>
    <relationshipName>ExpenseDetail_Project</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Oppty</label>
    <nameField>
        <label>영업기회 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Opportunity__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>고객사</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Opportunity__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>사업금액</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Opportunity__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>9. 기타 정보</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Opportunity__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>상위 영업기회</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>프로젝트에 대한 기본정보를 관리하며, Deal Closing 이후 생성한다. 영업담당자가 계약 체결 후 기초 데이터를 작성하며, 프로젝트 진행 중에는 PM이 관리하고, 대금청구/지급 관련 정보는 회계에서 관리한다.</description>
    <label>프로젝트</label>
    <nameField>
        <label>프로젝트 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/recordTypes/Project.recordType-meta.xml
<RecordType>
    <fullName>Project</fullName>
    <active>true</active>
    <description>프로젝트 사항 입력하는 Record Type</description>
    <label>프로젝트</label>
</RecordType>

PA_Education/TestMenifest/force-app/main/default/classes/ExpenseCreationController_test.cls
/************************************************************************************
 * File Name   : QuoteCreation.cls
 * Author      : Jk.lee 
 * Date        : 2019.03.14
 * Target      : ExpenseCreationController_test.cls
 * Description : 경비 신청, 경비신청 상세를 입력하는 클래스 Test
 * Modification Log
 * ===================================================================================
 * Ver      Date            Author              Modification
 * ===================================================================================
   1.0      2019.03.19      JK.LEE        Create
*************************************************************************************/

@isTest
public class ExpenseCreationController_test {
    
    @isTest
	static void doTest() {
		Test.startTest();

		Account acc = new Account(Name = 'Test 계정',
								  ShortName__c = 'test');
		List<Account> acclist = new List<Account>();
		acclist.add(acc);
		insert acclist;

        Opportunity__c oppty = new Opportunity__c(Name = 'test 영업기회', AccountId__c = acc.Id);
		List<Opportunity__c> opptyList = new List<Opportunity__c>();
		opptyList.add(oppty);
		insert opptyList;

		Project__c project = new Project__c(Name = '본사공통');
		List<Project__c> projectList = new List<Project__c>();
		projectList.add(project);
		insert projectList;

		Project__c project1 = new Project__c(Name = '마케팅');
		List<Project__c> projectList1 = new List<Project__c>();
		projectList1.add(project1);
		insert projectList1;

        Profile p = new Profile();
        p = TestDataFactory.getProfile('System Admin');

        User user = new User(Alias = 'test1'
                            , Email='SysAdminTestuser@earth.org'
                            , EmailEncodingKey='UTF-8'
                            , LastName='test'
                            , FirstName='Testing'
                            , LanguageLocaleKey='en_US'
                            , LocaleSidKey='en_US'
                            , EmployeeNumber='AC100000'
                            , ProfileId = p.Id
                            , TimeZoneSidKey='Asia/Seoul'
                            , UserName='systemTestUser@earth.org'
							, Position__c = '9');

        insert user;

		String strYear = String.valueOf(System.today().year());
		String strMonth = String.valueOf(System.today().month());
		List<Expense__c> expenseList = new List<Expense__c>();
		Expense__c expense = new Expense__c(FirstExpenseRequest__c = user.Id,
											UseYear__c = strYear,
											UseMonth__c = strMonth,
											BudgetType__c = '본사행정',
											PaymentMethod__c = '법인카드');
		expenseList.add(expense);
		insert expenseList;


		List<Expense__c> expenseList2 = new List<Expense__c>();
		Expense__c expense2 = new Expense__c(UseYear__c = strYear,
											UseMonth__c = strMonth,
											BudgetType__c = '본사행정',
											PaymentMethod__c = '법인카드');

		expenseList.add(expense2);
		insert expenseList2;




		List<ExpenseDetail__c> expDetailList = new List<ExpenseDetail__c>();
		ExpenseDetail__c expDetail = new ExpenseDetail__c(
											Expense__c = expense.Id,
											Category1__c = '본사행정',
											Category2__c = '식비',
											Description__c ='배가고파서 회사카드로 참치를 먹었습니다 죄송합니다.',
											Amount__c = 1000,
											Date__c = system.today());
		expDetailList.add(expDetail);
		insert expDetailList;

		List<ExpenseDetail__c> expDetailList2 = new List<ExpenseDetail__c>();
		ExpenseDetail__c expDetail2 = new ExpenseDetail__c(
											Expense__c = expense.Id,
											Category1__c = '프로젝트',
											Category2__c = '식비',
											Description__c ='Salse',
											Project_Name__c =project.Id,
											Amount__c = 1000,
											Opportunity_Name__c = oppty.Id,
											Payment_Type__c= '개인카드',
											Date__c = system.today());
		expDetailList2.add(expDetail2);

		insert expDetailList2;

		List<ExpenseDetail__c> expDetailList3 = new List<ExpenseDetail__c>();
		ExpenseDetail__c expDetail3 = new ExpenseDetail__c(
											Expense__c = expense.Id,
											Category1__c = '영업',
											Category2__c = '식비',
											Description__c ='Salse',
											Project_Name__c =project.Id,
											Amount__c = 1000,
											Opportunity_Name__c = oppty.Id,
											Payment_Type__c= '개인카드',
											Date__c = system.today());
		expDetailList3.add(expDetail3);

		insert expDetailList3;



		ExpenseCreationController expenseController = new ExpenseCreationController();
        List<ExpenseDetail__c> listExpDetailTemp = new List<ExpenseDetail__c>();
		Map<String ,Object> mapExpDetail;
		List<Object> listObject = expDetailList;
		List<Object> listObject2 = new List<Object>();
		listObject2 = expDetailList2;



		List<Id> idtemp = new List<Id>();
		idtemp.add(expDetail.Id);

		Map<String, Object> mapReturnValue = ExpenseCreationController.getInitData(expense.Id);
		Map<String, Object> mapReturnValue2 = ExpenseCreationController.getInitData(expense2.Id);

		system.debug(ExpenseCreationController.getPicklistValue('Expense__c', 'UseYear__c'));
		system.debug(ExpenseCreationController.getObjectFieldLabel('Expense__c'));
		system.debug(ExpenseCreationController.doSave(expense, listObject, idtemp));
		ExpenseCreationController.doSave(expense, expDetailList2, idtemp);
		ExpenseCreationController.doSave(expense, expDetailList3, idtemp);


        Test.stopTest();
    }

}