PA_Education/TestMenifest/force-app/main/default/objects/Account/fields/ShortName__c.field-meta.xml
<CustomField>
    <fullName>ShortName__c</fullName>
    <inlineHelpText>거래처를 식별할 수 있는 10자 이내의 짧은 명칭을 입력하세요.
계정 이름(Account.Name)은 사업자 등록증 상의 정식 명칭입니다.</inlineHelpText>
    <label>계정 이름(약어)</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Oppty</label>
    <nameField>
        <label>영업기회 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Opportunity__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>고객사</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Opportunity__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>상위 영업기회</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Opportunity__c/fields/ProposalPM__c.field-meta.xml
<CustomField>
    <fullName>ProposalPM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>제안PM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunity_ProposalPM</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/Opportunity_tr_test.cls
/************************************************************************************
* File Name   	    : Opportunity_tr TestClass
* Author	  		: Yeonlim
* Date				: 2023-12-18
* Modification Log
* ===================================================================================
* Ver      Date            Author          Modification
* ===================================================================================
* 1.0      2023-12-18      Yeonlim           Create
************************************************************************************/
@IsTest
public with sharing class Opportunity_tr_test {
    @IsTest
    public static void Opportunity_tr_test() {
        Profile objProfile = [SELECT Id, Name FROM Profile WHERE Name = 'Daeu Nextier Employee' LIMIT 1];

        User objUser = TestObjectCreator.objUser;
        objUser.ProfileId = objProfile.Id;
        objUser.Position__c = '9';
        insert objUser;

        Account objAcc = new Account(
                Name = 'TEST1',
                ShortName__c = 'TEST1'
        );

        insert objAcc;

        Opportunity__c objOppty = new Opportunity__c(
                Name = 'TEST',
                AccountId__c = objAcc.Id
        );

        insert objOppty;

        objOppty.ProposalPM__c = objUser.Id;
        update objOppty;
    }
}