PA_Education/TestMenifest/force-app/main/default/objects/Account/fields/ShortName__c.field-meta.xml
<CustomField>
    <fullName>ShortName__c</fullName>
    <inlineHelpText>거래처를 식별할 수 있는 10자 이내의 짧은 명칭을 입력하세요.
계정 이름(Account.Name)은 사업자 등록증 상의 정식 명칭입니다.</inlineHelpText>
    <label>계정 이름(약어)</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Oppty</label>
    <nameField>
        <label>영업기회 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Opportunity__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>고객사</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Opportunity__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>상위 영업기회</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <description>견적 마스터 오브젝트</description>
    <label>견적</label>
    <nameField>
        <displayFormat>DNT-{YYYY}{MM}-{000}</displayFormat>
        <label>문서 번호</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Quote__c/fields/Quote_Account__c.field-meta.xml
<CustomField>
    <fullName>Quote_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>기회의 고객과 견적대상인 실고객이 다른경우
견적을 수신하는 실제 고객을 입력</description>
    <inlineHelpText>기회의 고객과 견적 수신 고객이 다른 경우에만 입력하세요.</inlineHelpText>
    <label>고객</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>견적</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Quote__c/fields/Quote_ConsultRemark__c.field-meta.xml
<CustomField>
    <fullName>Quote_ConsultRemark__c</fullName>
    <defaultValue>&quot;- 유효기간 : 견적일 기준 1주일입니다.&quot; &amp;  BR()  &amp;
&quot;- 결제조건 : 현금 결제 조건입니다.&quot; &amp;  BR()  &amp;
&quot;- 투입기간은 고객과 협의하에 변경될 수 있습니다.&quot;</defaultValue>
    <description>Default Value : &quot;- 유효기간 : 견적일 기준 4주일입니다.&quot; &amp; &quot;\r\n&quot; &amp;
&quot;- 결제조건 : 현금 결제 조건입니다.&quot; &amp; &quot;\r\n&quot; &amp;
&quot;- 업무범위의 변경에 따라 협의에 의해 투입기간이 변경 될 수 있습니다.&quot; &amp; &quot;\r\n&quot;</description>
    <label>비고(컨설팅)</label>
    <type>TextArea</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Quote__c/fields/Quote_Date__c.field-meta.xml
<CustomField>
    <fullName>Quote_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>Default Value : Today()
견적일은 당일 원칙으로 하나 전일 또는 익일에 작성 발송하는 경우를 위해 입력 가능토록 함</description>
    <label>견적일</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Quote__c/fields/Quote_LicenseRemark__c.field-meta.xml
<CustomField>
    <fullName>Quote_LicenseRemark__c</fullName>
    <defaultValue>&quot;- 라이선스는 년 단위 계약 갱신이 필요합니다.&quot; &amp;  BR()  &amp;
&quot;- 결제조건: 현금 결제 조건이고 통화는 USD입니다.&quot; &amp;  BR()  &amp;
&quot;- 사용자 라이선스 수량은 RFP를 기초로 작성되었고 사용자의 증가에 따라 변경될 수 있습니다.&quot;</defaultValue>
    <description>Default Value : &quot;- 라이선스는 년 단위 계약 갱신이 필요합니다.&quot; &amp; &quot;\r\n&quot; &amp;
&quot;- 결제조건: 현금 결제 조건이고 통화는 USD입니다.&quot; &amp; &quot;\r\n&quot; &amp;
&quot;- 사용자 라이선스 수량은 RFP를 기초로 작성되었고 사용자의 증가에 따라 변경될 수 있습니다.&quot;</description>
    <label>비고(라이센스)</label>
    <type>TextArea</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Quote__c/fields/Quote_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Quote_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>영업기회</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>견적</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Quote__c/fields/Quote_ShowVAT__c.field-meta.xml
<CustomField>
    <fullName>Quote_ShowVAT__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>견적서에 VAT 포함 금액을 표시 할 경우 체크하세요.</inlineHelpText>
    <label>VAT 별도 표시</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Quote__c/fields/Quote_Status__c.field-meta.xml
<CustomField>
    <fullName>Quote_Status__c</fullName>
    <defaultValue>&apos;Draft&apos;</defaultValue>
    <label>상태</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Wating</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Quote__c/fields/Quote_Subject__c.field-meta.xml
<CustomField>
    <fullName>Quote_Subject__c</fullName>
    <description>&apos;[&apos; &amp; Quote_Opportunity__r.Account_Name__r.Name &amp; &apos;]&apos; &amp; 
&apos; - &apos; &amp; Quote_Opportunity__r.Engagement_Description__c
를 Workflow에 설정</description>
    <inlineHelpText>입력하지 않는 경우 저장시
[기회명] + 기회 Engagement Description
으로 자동 설정됩니다.</inlineHelpText>
    <label>견적명</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Quote__c/fields/Quote_TrainingRemark__c.field-meta.xml
<CustomField>
    <fullName>Quote_TrainingRemark__c</fullName>
    <label>비고(교육)</label>
    <type>TextArea</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/QuoteItem__c.object-meta.xml
<CustomObject>
    <description>견적을 구성하는 Consulting 자원 또는 License 목록</description>
    <label>견적 상세</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_ConsultDiscountedPrice__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_ConsultDiscountedPrice__c</fullName>
    <label>할인 후 단가</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_ConsultLevel__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_ConsultLevel__c</fullName>
    <description>투입인력의 등급을 견적서에 표기를 원할 경우를 대비한 항목</description>
    <inlineHelpText>견적서에 투입인력 등급 표기 요청을 받은 경우 선택하십시요.</inlineHelpText>
    <label>등급</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chief</fullName>
            </value>
            <value>
                <fullName>Principal</fullName>
            </value>
            <value>
                <fullName>Supervisor</fullName>
                <default>true</default>
                <label>Supervisor</label>
            </value>
            <value>
                <fullName>특급</fullName>
            </value>
            <value>
                <fullName>고급</fullName>
            </value>
            <value>
                <fullName>중급</fullName>
            </value>
            <value>
                <fullName>초급</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
            <value>
                <fullName>Intermediate</fullName>
            </value>
            <value>
                <fullName>Junior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_ConsultListPrice__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_ConsultListPrice__c</fullName>
    <inlineHelpText>SFDC Consultant	Chief	   26,000,000 
SFDC Consultant	Principal	   22,000,000 
SFDC Consultant	Supervisor  16,000,000 
SFDC Developer	Chief	   22,000,000 
SFDC Developer	Principal	   16,000,000 
SFDC Developer	Supervisor  12,000,000</inlineHelpText>
    <label>표준단가 M/M</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_ConsultName__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_ConsultName__c</fullName>
    <defaultValue>&apos;TBD&apos;</defaultValue>
    <label>이름</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_ConsultType__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_ConsultType__c</fullName>
    <description>투입인력의 구분</description>
    <inlineHelpText>투입인력이 여러 역할을 담당한 경우 다중 선택하십시요.</inlineHelpText>
    <label>인력구분</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business Leader</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Project Leader</fullName>
            </value>
            <value>
                <fullName>Business Analyst</fullName>
            </value>
            <value>
                <fullName>SFDC Administrator</fullName>
            </value>
            <value>
                <fullName>SFDC Platform Developer</fullName>
            </value>
            <value>
                <fullName>SFDC Consultant</fullName>
            </value>
            <value>
                <fullName>SFDC Pardot Consultant</fullName>
            </value>
            <value>
                <fullName>SFDC Sales Cloud Consultant</fullName>
            </value>
            <value>
                <fullName>SFDC Service Cloud Consultant</fullName>
            </value>
            <value>
                <fullName>SFDC Marketing Cloud Consultant</fullName>
            </value>
            <value>
                <fullName>SFDC Field Service Lightning Consultant</fullName>
            </value>
            <value>
                <fullName>SFDC System Architect</fullName>
            </value>
            <value>
                <fullName>SFDC Technical Architect</fullName>
            </value>
            <value>
                <fullName>SFDC Application Architect</fullName>
            </value>
            <value>
                <fullName>I/F Specialist</fullName>
            </value>
            <value>
                <fullName>Migration Expert</fullName>
            </value>
            <value>
                <fullName>Front-end Developer</fullName>
            </value>
            <value>
                <fullName>Mobile Developer</fullName>
            </value>
            <value>
                <fullName>App Developer</fullName>
            </value>
            <value>
                <fullName>Web Publisher</fullName>
            </value>
            <value>
                <fullName>Web Designer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_FOC__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_FOC__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>FOC일 경우 체크하세요.
이 경우 금액이 계산되지 않습니다.</inlineHelpText>
    <label>FOC</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_LicenseDiscountedPrice__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_LicenseDiscountedPrice__c</fullName>
    <label>할인사용료(월)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_LicenseListPrice__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_LicenseListPrice__c</fullName>
    <label>표준사용료(월)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_LicenseNumberOfUser__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_LicenseNumberOfUser__c</fullName>
    <label>사용자</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_LicenseType__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_LicenseType__c</fullName>
    <label>라이선스 구분</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_Quote__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_Quote__c</fullName>
    <description>견적 마스터</description>
    <label>견적</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>견적 상세</relationshipLabel>
    <relationshipName>QuoteItem</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_SortOrder__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_SortOrder__c</fullName>
    <inlineHelpText>구분,등급,단가 순서보다 우선 적용되는 표기 순번입니다.</inlineHelpText>
    <label>순서</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_TrainingDescription__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_TrainingDescription__c</fullName>
    <label>상세항목</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_TrainingStandardPrice__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_TrainingStandardPrice__c</fullName>
    <label>표준수강료</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/recordTypes/Consulting.recordType-meta.xml
<RecordType>
    <fullName>Consulting</fullName>
    <active>true</active>
    <description>투입인력에 대한 상세 내역</description>
    <label>컨설팅</label>
</RecordType>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/recordTypes/License.recordType-meta.xml
<RecordType>
    <fullName>License</fullName>
    <active>true</active>
    <description>견적을 구성하는 라이센스 내역</description>
    <label>라이센스</label>
</RecordType>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/recordTypes/Training.recordType-meta.xml
<RecordType>
    <fullName>Training</fullName>
    <active>true</active>
    <description>교육 견적 상세 내역</description>
    <label>교육</label>
</RecordType>

PA_Education/TestMenifest/force-app/main/default/classes/QuoteCreation_test.cls
/************************************************************************************
 * File Name   : QuoteCreation_test.cls
 * Author      : Jk.lee 
 * Date        : 2019.03.04
 * Target      : QuoteCreation.cls
 * Description : QuoteCreation.cls Test Class
 * Modification Log
 * ===================================================================================
 * Ver      Date            Author              Modification
 * ===================================================================================
   1.0      2019.02.28      JK.LEE        Create
*************************************************************************************/

@isTest
private class QuoteCreation_test {

	@isTest
	static void doTest() {
		Test.startTest();
		QuoteCreation quoteCreate = new QuoteCreation();

		Account acc = new Account(Name = 'Test 계정',
								  ShortName__c = 'test');
		List<Account> acclist = new List<Account>();
		acclist.add(acc);
		insert acclist;

		Opportunity__c oppty = new Opportunity__c(Name = 'test 영업기회', AccountId__c = acc.Id);
		List<Opportunity__c> opptyList = new List<Opportunity__c>();
		opptyList.add(oppty);
		insert opptyList;
		
		Quote__c quote = new Quote__c(								
							Quote_Opportunity__c = oppty.Id, 
							Quote_Subject__c = 'TEST QUOTE',
							Quote_Date__c = System.today(), 
							Quote_Account__c = acc.Id, 
							Quote_Status__c = 'Draft',
							Quote_ShowVAT__c = false,
							//소계
							Quote_ConsultRemark__c = 'Test 컨설팅',
							Quote_LicenseRemark__c = 'Test 라이센스',
							Quote_TrainingRemark__c = 'Test 교육'
							);
		List<Quote__c> quoteList = new List<Quote__c>();
		quoteList.add(quote);
		insert quoteList;

		QuoteItem__c quoteItemCon = new QuoteItem__c (
										QuoteItem_Quote__c  = quote.Id , 
									  	RecordTypeId = '01290000000ukfTAAQ',
									  	QuoteItem_ConsultDiscountedPrice__c =500,
									  	QuoteItem_ConsultLevel__c ='Chief',
									  	QuoteItem_ConsultType__c = 'SFDC Consultant',
									  	QuoteItem_ConsultListPrice__c = 1000,
									  	QuoteItem_ConsultName__c = '테스트사원',
									  	QuoteItem_FOC__c = false,
									  	QuoteItem_SortOrder__c = 1,

										QuoteItem_LicenseType__c = '테스트 라이센스',
										QuoteItem_LicenseListPrice__c = 1000,
										QuoteItem_LicenseDiscountedPrice__c = 500,
										QuoteItem_LicenseNumberOfUser__c = 10,

										QuoteItem_TrainingDescription__c = '테스트 상세항목',
										QuoteItem_TrainingStandardPrice__c = 1000,
										QuoteItem_TrainingSalesPrice__c = 500,
										QuoteItem_TrainingCount__c = 10
													  );
		QuoteItem__c quoteItemLic = new QuoteItem__c(QuoteItem_Quote__c  = quote.Id , RecordTypeId = '01290000000ukfUAAQ' );
		QuoteItem__c quoteItemTra = new QuoteItem__c(QuoteItem_Quote__c  = quote.Id , RecordTypeId = '01290000000ukfTAAQ' );

		List<QuoteItem__c> quoteItemList = new List<QuoteItem__c>();
		quoteItemList.add(quoteItemCon);
		quoteItemList.add(quoteItemTra);
		quoteItemList.add(quoteItemLic);
		insert quoteItemList;


		//Delete List Id
		List<Id> deletedId = new List<Id>();
		deletedId.add(quoteItemcon.Id);
		
		Map<String, Object> mapReturnValue = QuoteCreation.getInitData(quote.Id, oppty.Id);
		system.debug(mapReturnValue);
		system.debug(QuoteCreation.getObjectFieldLabel('Quote__c'));
		system.debug(QuoteCreation.getCalcListPrice('Consultant', 'Principal'));
		system.debug(QuoteCreation.getPicklistValue('Quote__c', 'Quote_Status__c'));


		QuoteCreation.doSave((List<QuoteCreation.WrapperQuoteItem>) mapReturnValue.get('Consulting'), (List<QuoteCreation.WrapperQuoteItem>) mapReturnValue.get('License'), (List<QuoteCreation.WrapperQuoteItem>) mapReturnValue.get('Training'), deletedId, quote);

		Test.stopTest();
	}

	@testSetup 
	static void setData() {
		QuoteItemManage__c objQuoteItemManage = TestObjectCreator.objQuoteItemManage;
		insert objQuoteItemManage;
    }

}