PA_Education/TestMenifest/force-app/main/default/objects/Performance__c/Performance__c.object-meta.xml
<CustomObject>
    <description>인력, 매출 관련 필드</description>
    <label>성과</label>
    <nameField>
        <displayFormat>성과-{0000}</displayFormat>
        <label>성과</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Performance__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>성과 입력 날짜</description>
    <label>날짜</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Performance__c/fields/HeadCount__c.field-meta.xml
<CustomField>
    <fullName>HeadCount__c</fullName>
    <description>인력 Record Type 의 인원 Fields</description>
    <label>인원</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Performance__c/fields/Sales__c.field-meta.xml
<CustomField>
    <fullName>Sales__c</fullName>
    <description>매출 Reocrd type 의 연도 매출 Field</description>
    <label>매출</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/RenewalHPDaeuPerfomance_Test.cls
/************************************************************************************
 * File Name   : RenewalHPDaeuPerfomance_Test.cls
 * Author      : SungJu.Kang
 * Date        : 2022. 01. 03
 * Target      : RenewalHPDaeuPerfomance.cls
 * Description : RenewalHPDaeuPerfomance.cls Test Class
 * Modification Log
 * ===================================================================================
 * Ver      Date            Author              Modification
 * ===================================================================================
   1.0      2022. 01. 03   SungJu.Kang            Create
*************************************************************************************/

@IsTest
private class RenewalHPDaeuPerfomance_Test {
    @IsTest
    static void itShould(){
        Test.startTest();

        Performance__c objPerformance = new Performance__c();
        objPerformance.Sales__c = 100000000;
        objPerformance.HeadCount__c = 40;
        objPerformance.Date__c = Date.today();
        insert objPerformance;

        RenewalHPDaeuPerfomance.getPerformances();


        Test.stopTest();
    }
}