PA_Education/TestMenifest/force-app/main/default/objects/Performance__c/Performance__c.object-meta.xml
<CustomObject>
    <description>인력, 매출 관련 필드</description>
    <label>성과</label>
    <nameField>
        <displayFormat>성과-{0000}</displayFormat>
        <label>성과</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Performance__c/fields/fm_Year__c.field-meta.xml
<CustomField>
    <fullName>fm_Year__c</fullName>
    <formula>YEAR( Date__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>년도</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Performance__c/fields/HeadCount__c.field-meta.xml
<CustomField>
    <fullName>HeadCount__c</fullName>
    <description>인력 Record Type 의 인원 Fields</description>
    <label>인원</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Performance__c/fields/Sales__c.field-meta.xml
<CustomField>
    <fullName>Sales__c</fullName>
    <description>매출 Reocrd type 의 연도 매출 Field</description>
    <label>매출</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/RenewalHPDaeuPerfomance.cls
/**
 * =============================================
 * File Name    : RenewalHPDaeuPerfomance.cls
 * Author       : Chan Kang
 * Group        : Boundary
 * Date         : 2021. 12. 24
 * Description  : 대유 넥스티어 홈페이지 내 Performance 정보 가져오기
*/


public without sharing class RenewalHPDaeuPerfomance {
    @AuraEnabled
    public static List<Performance__c> getPerformances() {
        List<Performance__c> performances = [
                SELECT Id, fm_Year__c, Sales__c, HeadCount__c
                FROM Performance__c
        ];

        return performances;
    }
}