PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/CorporateCardBilling__c.object-meta.xml
<CustomObject>
    <label>법인카드청구내역</label>
    <nameField>
        <displayFormat>CB-{YY}{MM}-{00000}</displayFormat>
        <label>법인카드청구내역</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/fields/CorporateCard__c.field-meta.xml
<CustomField>
    <fullName>CorporateCard__c</fullName>
    <label>법인카드</label>
    <referenceTo>CorporateCard__c</referenceTo>
    <relationshipLabel>법인카드청구내역</relationshipLabel>
    <relationshipName>CorporateCardBilling_CorporateCard</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense Application</label>
    <nameField>
        <displayFormat>EP-{YYYYMM}-{000000}</displayFormat>
        <label>경비신청 코드</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>승인상태</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Writing</fullName>
                <default>true</default>
                <label>작성</label>
            </value>
            <value>
                <fullName>Consider</fullName>
                <label>승인검토중</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>승인완료</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>승인거부</label>
            </value>
            <value>
                <fullName>Recall</fullName>
                <label>회수됨</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/BudgetType__c.field-meta.xml
<CustomField>
    <fullName>BudgetType__c</fullName>
    <label>사용목적</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BudgetType</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>비고</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/FirstExpenseRequest__c.field-meta.xml
<CustomField>
    <fullName>FirstExpenseRequest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>일반 사원일 경우 &apos;사업부장/PM&apos;선택 &amp;&amp;
사업부장/PM일 경우 &apos;이응도 전무님&apos;선택</inlineHelpText>
    <label>1차 승인자 지정</label>
    <referenceTo>User</referenceTo>
    <relationshipName>FirstExpenseRequest</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethod__c</fullName>
    <label>결제방식</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>개인카드/현금</fullName>
                <default>true</default>
                <label>개인카드/현금</label>
            </value>
            <value>
                <fullName>법인카드</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/UseMonth__c.field-meta.xml
<CustomField>
    <fullName>UseMonth__c</fullName>
    <defaultValue>TEXT( MONTH( ADDMONTHS( TODAY() ,-1) ) )</defaultValue>
    <inlineHelpText>신청할 경비내역의 사용월을 입력합니다.</inlineHelpText>
    <label>경비 사용 월</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/UseYear__c.field-meta.xml
<CustomField>
    <fullName>UseYear__c</fullName>
    <defaultValue>TEXT( YEAR(  ADDMONTHS(TODAY(),-1)  ) )</defaultValue>
    <inlineHelpText>신청할 경비내역의 연도를 입력합니다.</inlineHelpText>
    <label>경비 사용 연도</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2013</fullName>
            </value>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
                <default>true</default>
                <label>2022</label>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/ExpenseDetail__c.object-meta.xml
<CustomObject>
    <label>Expense Detail</label>
    <nameField>
        <displayFormat>EPD-{000000}</displayFormat>
        <label>경비신청 상세 ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>사용일시</label>
    <type>DateTime</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>내용</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Expense__c.field-meta.xml
<CustomField>
    <fullName>Expense__c</fullName>
    <label>경비신청 ID</label>
    <referenceTo>Expense__c</referenceTo>
    <relationshipName>ExpenseDetail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/PriorExpenseApplication__c.field-meta.xml
<CustomField>
    <fullName>PriorExpenseApplication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>경비사전승인</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>이미 경비신청이 존재하는 사전승인입니다.</errorMessage>
        <filterItems>
            <field>PriorExpenseApplication__c.ApprovalStatus__c</field>
            <operation>equals</operation>
            <value>승인완료</value>
        </filterItems>
        <filterItems>
            <field>PriorExpenseApplication__c.fm_ExpenseApplicatedYn__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PriorExpenseApplication__c</referenceTo>
    <relationshipLabel>Expense Detail</relationshipLabel>
    <relationshipName>PriorExpenseApplication</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PriorExpenseApplication__c/PriorExpenseApplication__c.object-meta.xml
<CustomObject>
    <label>경비사전승인</label>
    <nameField>
        <label>경비사전승인 이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/PriorExpenseApplication__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>승인상태</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>작성중</fullName>
                <default>true</default>
                <label>작성중</label>
            </value>
            <value>
                <fullName>승인요청</fullName>
            </value>
            <value>
                <fullName>승인반려</fullName>
            </value>
            <value>
                <fullName>승인완료</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PriorExpenseApplication__c/fields/AttendeeNumber__c.field-meta.xml
<CustomField>
    <fullName>AttendeeNumber__c</fullName>
    <label>참석인원수</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PriorExpenseApplication__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>내용</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PriorExpenseApplication__c/fields/FirstExpenseRequest__c.field-meta.xml
<CustomField>
    <fullName>FirstExpenseRequest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>1차 승인자 지정</label>
    <referenceTo>User</referenceTo>
    <relationshipName>FirstExpenseRequest_User</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PriorExpenseApplication__c/fields/Place__c.field-meta.xml
<CustomField>
    <fullName>Place__c</fullName>
    <label>장소</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PriorExpenseApplication__c/fields/UseDate__c.field-meta.xml
<CustomField>
    <fullName>UseDate__c</fullName>
    <label>사용일자</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/ExpenseDetail_tr_test.cls
/*
	* ExpenseDetail_tr 테스트 클래스
	* 경비신청 ExpenseDetail
	* 2019년 03월 20일
	* 작성자: 이종경
*/

@IsTest(SeeAllData=true)
private class ExpenseDetail_tr_test {

	static testMethod void ExpenseDetail_tr_test() {
		Test.startTest();

		Profile p = new Profile();
		p = TestDataFactory.getProfile('System Admin');

		User user = new User(Alias = 'test1'
				, Email = 'SysAdminTestuser@earth.org'
				, EmailEncodingKey = 'UTF-8'
				, LastName = 'test'
				, FirstName = 'Testing'
				, LanguageLocaleKey = 'en_US'
				, LocaleSidKey = 'en_US'
				, EmployeeNumber = 'AC100000'
				, ProfileId = p.Id
				, TimeZoneSidKey = 'Asia/Seoul'
				, UserName = 'systemTestUser@earth.org'
				, Position__c = '9'
				);

		insert user;
		String strYear = String.valueOf(System.today().year());
		String strMonth = String.valueOf(System.today().month());
		List<Expense__c> expenseList = new List<Expense__c>();
		Expense__c expense = new Expense__c(FirstExpenseRequest__c = user.Id,
				UseYear__c = strYear,
				UseMonth__c = strMonth,
				BudgetType__c = '본사행정',
				PaymentMethod__c = '법인카드');
		expenseList.add(expense);
		insert expenseList;

		PriorExpenseApplication__c objPEA = new PriorExpenseApplication__c(
				Name = '테스트',
				UseDate__c = Date.today(),
				Place__c = '장소',
				AttendeeNumber__c = 1,
				Description__c = 'test',
				ApprovalStatus__c = '승인완료'
		);
		insert objPEA;

		CorporateCard__c objCC = new CorporateCard__c(
				Name = 'test',
				CardCompany__c = '06',
				CardNumber__c = '123456******7890',
				CardNickname__c = 'test card',
				EffectiveMonth__c = '2999.09',
				RealUser__c = UserInfo.getUserId()
				);
		insert objCC;

		CorporateCardBilling__c objCCB = new CorporateCardBilling__c(
				CorporateCard__c = objCC.Id,
				BillingDate__c = Date.today(),
				BillingAmount__c = 1000000
		);
		insert objCCB;


		List<ExpenseDetail__c> expDetailList = new List<ExpenseDetail__c>();
		List<ExpenseDetail__c> expDetailList1 = new List<ExpenseDetail__c>();
		List<ExpenseDetail__c> expDetailList2 = new List<ExpenseDetail__c>();
		List<ExpenseDetail__c> expDetailList3 = new List<ExpenseDetail__c>();
		List<ExpenseDetail__c> expDetailList4 = new List<ExpenseDetail__c>();
		List<ExpenseDetail__c> expDetailList5 = new List<ExpenseDetail__c>();
		List<ExpenseDetail__c> expDetailList6 = new List<ExpenseDetail__c>();

		ExpenseDetail__c expDetail = new ExpenseDetail__c(
				Expense__c = expense.Id,
				CorporateCardBilling__c = objCCB.Id,
				Category1__c = '본사행정',
				Category2__c = '고객접대',
				Description__c = '배가고파서 회사카드로 참치를 먹었습니다 죄송합니다.',
				Amount__c = 1000,
				Date__c = system.today());

		ExpenseDetail__c expDetail1 = new ExpenseDetail__c(
				Expense__c = expense.Id,
				Category1__c = '본사행정',
				Category2__c = '교육/훈련',
				Description__c = '배가고파서 회사카드로 참치를 먹었습니다 죄송합니다.',
				Amount__c = 1000,
				Date__c = system.today());

		ExpenseDetail__c expDetail2 = new ExpenseDetail__c(
				Expense__c = expense.Id,
				Category1__c = '본사행정',
				Category2__c = '도서인쇄비',
				Description__c = '배가고파서 회사카드로 참치를 먹었습니다 죄송합니다.',
				Amount__c = 1000,
				Date__c = system.today());

		ExpenseDetail__c expDetail3 = new ExpenseDetail__c(
				Expense__c = expense.Id,
				Category1__c = '본사행정',
				Category2__c = '소모품비',
				Description__c = '배가고파서 회사카드로 참치를 먹었습니다 죄송합니다.',
				Amount__c = 1000,
				Date__c = system.today());

		ExpenseDetail__c expDetail4 = new ExpenseDetail__c(
				Expense__c = expense.Id,
				Category1__c = '본사행정',
				Category2__c = '회의',
				Description__c = '배가고파서 회사카드로 참치를 먹었습니다 죄송합니다.',
				PriorExpenseApplication__c = objPEA.Id,
				Amount__c = 1000,
				Date__c = system.today());

		ExpenseDetail__c expDetail5 = new ExpenseDetail__c(
				Expense__c = expense.Id,
				Category1__c = '본사행정',
				Category2__c = '교통비',
				Description__c = '배가고파서 회사카드로 참치를 먹었습니다 죄송합니다.',
				Amount__c = 1000,
				Date__c = system.today());

		ExpenseDetail__c expDetail6 = new ExpenseDetail__c(
				Expense__c = expense.Id,
				Category1__c = '본사행정',
				Category2__c = '기타',
				Description__c = '배가고파서 회사카드로 참치를 먹었습니다 죄송합니다.',
				Amount__c = 1000,
				Date__c = system.today());

		expDetailList.add(expDetail);
		insert expDetailList;

		expDetailList.add(expDetail1);
		Upsert expDetailList;

		expDetailList.add(expDetail1);
		insert expDetailList1;

		expDetailList1.add(expDetail2);
		upsert expDetailList1;

		expDetailList3.add(expDetail3);
		insert expDetailList3;

		expDetailList3.add(expDetail4);
		upsert expDetailList3;

		expDetailList.add(expDetail5);
		insert expDetailList5;

		expDetailList.add(expDetail6);
		insert expDetailList6;

		Test.stopTest();

	}
}