PA_Education/TestMenifest/force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <description>견적 마스터 오브젝트</description>
    <label>견적</label>
    <nameField>
        <displayFormat>DNT-{YYYY}{MM}-{000}</displayFormat>
        <label>문서 번호</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Quote__c/fields/Quote_Contact__c.field-meta.xml
<CustomField>
    <fullName>Quote_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>견적을 수신하는 고객 담당자</description>
    <label>고객담당자</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>견적</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/QuoteItem__c.object-meta.xml
<CustomObject>
    <description>견적을 구성하는 Consulting 자원 또는 License 목록</description>
    <label>견적 상세</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_Quote__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_Quote__c</fullName>
    <description>견적 마스터</description>
    <label>견적</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>견적 상세</relationshipLabel>
    <relationshipName>QuoteItem</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/QuoteRenderController_Test.cls
@isTest
public class QuoteRenderController_Test{
    static User testUser;
    static Quote__c q;
    static {
        Profile p = TestDataFactory.getProfile('System Admin');
        testUser = TestDataFactory.createUser(p);   
        Contact c = new Contact(LastName = 'TestContact');
        insert c;
        q = new Quote__c(Quote_Contact__c = c.Id);
        insert q;
        List<RecordType> rtLst = [SELECT Id FROM RecordType WHERE SobjectType = 'QuoteItem__c'];
        String conRt = rtLst[0].Id;
        String lnsRt = rtLst[1].Id;
        String trnRt = rtLst[2].Id;
        List<QuoteItem__c> qiLst = new List<QuoteItem__c>();
        qiLst.add(new QuoteItem__c(QuoteItem_Quote__c = q.Id, RecordTypeId = conRt));
        qiLst.add(new QuoteItem__c(QuoteItem_Quote__c = q.Id, RecordTypeId = lnsRt));
        qiLst.add(new QuoteItem__c(QuoteItem_Quote__c = q.Id, RecordTypeId = trnRt));
        insert qiLst;
    }
    static TestMethod void QuoteRenderController_Test(){
        Test.startTest();
		System.runAs(testUser){        
            ApexPages.StandardController ctrl = new ApexPages.StandardController(q);  
        	QuoteRenderController hel = new QuoteRenderController(ctrl);
        }
        Test.stopTest();
    }
}