PA_Education/TestMenifest/force-app/main/default/objects/EformsignEnvironment__c/EformsignEnvironment__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Eformsign Environment</label>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignEnvironment__c/fields/ApiBaseUrl__c.field-meta.xml
<CustomField>
    <fullName>ApiBaseUrl__c</fullName>
    <label>Api Base Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignEnvironment__c/fields/ApiKey__c.field-meta.xml
<CustomField>
    <fullName>ApiKey__c</fullName>
    <label>API Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignEnvironment__c/fields/CompanyId__c.field-meta.xml
<CustomField>
    <fullName>CompanyId__c</fullName>
    <label>Company ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignEnvironment__c/fields/Privatekey__c.field-meta.xml
<CustomField>
    <fullName>Privatekey__c</fullName>
    <label>Private key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignEnvironment__c/fields/RepresentativeAdminEmail__c.field-meta.xml
<CustomField>
    <fullName>RepresentativeAdminEmail__c</fullName>
    <label>Representative Admin Email</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignToken__c/EformsignToken__c.object-meta.xml
<CustomObject>
    <label>eformsign Token</label>
    <nameField>
        <label>eformsign Token Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignToken__c/fields/AccessToken__c.field-meta.xml
<CustomField>
    <fullName>AccessToken__c</fullName>
    <label>Access Token</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignToken__c/fields/ExpireIn__c.field-meta.xml
<CustomField>
    <fullName>ExpireIn__c</fullName>
    <label>Expire In</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignToken__c/fields/RefreshToken__c.field-meta.xml
<CustomField>
    <fullName>RefreshToken__c</fullName>
    <label>Refresh Token</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignToken__c/fields/TokenIssuedDateTime__c.field-meta.xml
<CustomField>
    <fullName>TokenIssuedDateTime__c</fullName>
    <label>Token Issued DateTime</label>
    <type>DateTime</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignToken__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>eformsign_Token</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/EformsignTokenManager_Test.cls
/************************************************************************************
 * Description :
 * Ver      Date           Author          Modification
 * ===================================================================================
   1.0      2024-06-27     hs.jung          Create
*************************************************************************************/
@IsTest
private class EformsignTokenManager_Test {
    @isTest
    static void testRecentTokenNotNull() {
        Test.setMock(HttpCalloutMock.class, new HttpCalloutSuccessMock());
        EformsignToken__c objEformsignToken = new EformsignToken__c();
        objEformsignToken.Name = 'eftkName';
        objEformsignToken.AccessToken__c = 'et54345344535632sdfsdrt32';
        objEformsignToken.RefreshToken__c = 'et54345344535632sdfsdrt3223';
        objEformsignToken.User__c = UserInfo.getUserId();
        objEformsignToken.TokenIssuedDateTime__c = System.today() + 2 ;
        objEformsignToken.ExpireIn__c = 3600;
        insert objEformsignToken;

        EformsignEnvironment__c defaultConfig = new EformsignEnvironment__c();
        defaultConfig.ApiKey__c = 'apiKey';
        defaultConfig.Privatekey__c = 'privateKey';
        defaultConfig.CompanyId__c = 'companyId';
        defaultConfig.RepresentativeAdminEmail__c = 'https://kr-api.eformsign.com';
        defaultConfig.ApiBaseUrl__c = 'https://kr-api.eformsign.com';
        insert defaultConfig;

        test.startTest();
        EformsignTokenManager efTokenMg  = new EformsignTokenManager();
        efTokenMg.getAccessTokenSObject();
        efTokenMg.getAccessTokenForEmbeddeingJson();
        efTokenMg.requestNewToken();
        test.stopTest();
    }

    @isTest
    static void testRecentTokenNull2() {
        Test.setMock(HttpCalloutMock.class, new HttpCalloutSuccessMock());
        EformsignToken__c objEformsignToken = new EformsignToken__c();
        objEformsignToken.Name = 'eftkName';
        objEformsignToken.AccessToken__c = 'et54345344535632sdfsdrt32';
        objEformsignToken.RefreshToken__c = 'et54345344535632sdfsdrt3223';
        objEformsignToken.User__c = UserInfo.getUserId();
//        objEformsignToken.TokenIssuedDateTime__c = System.today() - 2 ;
        objEformsignToken.ExpireIn__c = 3600;
        insert objEformsignToken;

        EformsignEnvironment__c defaultConfig = new EformsignEnvironment__c();
        defaultConfig.ApiKey__c = 'apiKey';
        defaultConfig.Privatekey__c = 'privateKey';
        defaultConfig.CompanyId__c = 'companyId';
        defaultConfig.RepresentativeAdminEmail__c = 'https://kr-api.eformsign.com';
        defaultConfig.ApiBaseUrl__c = 'https://kr-api.eformsign.com';
        insert defaultConfig;

        test.startTest();
        EformsignTokenManager efTokenMg  = new EformsignTokenManager();
        efTokenMg.getAccessTokenSObject();
        efTokenMg.getAccessTokenForEmbeddeingJson();
        efTokenMg.requestNewToken();
        test.stopTest();
    }

    @isTest
    static void testRecentTokenNull3() {
        Test.setMock(HttpCalloutMock.class, new HttpCalloutSuccessMock());
        EformsignToken__c objEformsignToken = new EformsignToken__c();
        objEformsignToken.Name = 'eftkName';
        objEformsignToken.AccessToken__c = 'et54345344535632sdfsdrt32';
        objEformsignToken.RefreshToken__c = 'et54345344535632sdfsdrt3223';
        objEformsignToken.User__c = UserInfo.getUserId();
        objEformsignToken.TokenIssuedDateTime__c = System.today() - 2 ;
        objEformsignToken.ExpireIn__c = 3600;
        insert objEformsignToken;

        EformsignEnvironment__c defaultConfig = new EformsignEnvironment__c();
        defaultConfig.ApiKey__c = 'apiKey';
        defaultConfig.Privatekey__c = 'privateKey';
        defaultConfig.CompanyId__c = 'companyId';
        defaultConfig.RepresentativeAdminEmail__c = 'https://kr-api.eformsign.com';
        defaultConfig.ApiBaseUrl__c = 'https://kr-api.eformsign.com';
        insert defaultConfig;

        test.startTest();
        EformsignTokenManager efTokenMg  = new EformsignTokenManager();
        efTokenMg.getAccessTokenSObject();
        efTokenMg.getAccessTokenForEmbeddeingJson();
        efTokenMg.requestNewToken();
        test.stopTest();
    }

    // Http response
    private static HttpResponse newResponse(Integer statusCode) {
        HttpResponse response = new HttpResponse();
        response.setStatusCode(statusCode);
        String json = '{\n' +
                '                "api_key": {\n' +
                '                    "name": "salesforce",\n' +
                '                    "alias": "app",\n' +
                '                    "company": {\n' +
                '                        "company_id": "f752333198f24c46ae2085e04169da1a",\n' +
                '                        "name": "메가존클라우드",\n' +
                '                        "api_url": "https://kr-api.eformsign.com"\n' +
                '                    }\n' +
                '                },\n' +
                '                "oauth_token": {\n' +
                '                    "expires_in": 3600,\n' +
                '                    "token_type": "JWT",\n' +
                '                    "refresh_token": "aaa",\n' +
                '                    "access_token": "aaaY"\n' +
                '                }\n' +
                '            }';
//        response.setBody('{"access_token":"test"}');
        response.setBody(json);

        return response;
    }

    // StatusCode 200 Mock
    private class HttpCalloutSuccessMock implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest request) {
            HttpResponse response = newResponse(200);

            return response;
        }
    }
}