PA_Education/TestMenifest/force-app/main/default/objects/EformsignEnvironment__c/EformsignEnvironment__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Eformsign Environment</label>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignEnvironment__c/fields/ApiBaseUrl__c.field-meta.xml
<CustomField>
    <fullName>ApiBaseUrl__c</fullName>
    <label>Api Base Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignEnvironment__c/fields/ApiKey__c.field-meta.xml
<CustomField>
    <fullName>ApiKey__c</fullName>
    <label>API Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignEnvironment__c/fields/CompanyId__c.field-meta.xml
<CustomField>
    <fullName>CompanyId__c</fullName>
    <label>Company ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignEnvironment__c/fields/Privatekey__c.field-meta.xml
<CustomField>
    <fullName>Privatekey__c</fullName>
    <label>Private key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignEnvironment__c/fields/RepresentativeAdminEmail__c.field-meta.xml
<CustomField>
    <fullName>RepresentativeAdminEmail__c</fullName>
    <label>Representative Admin Email</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignTemplate__c/EformsignTemplate__c.object-meta.xml
<CustomObject>
    <description>이폼싸인 템플릿</description>
    <label>eformsign Template</label>
    <nameField>
        <label>eformsign Template Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignTemplate__c/fields/ObjectApiName__c.field-meta.xml
<CustomField>
    <fullName>ObjectApiName__c</fullName>
    <label>대상 개체명</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignTemplate__c/fields/TemplateId__c.field-meta.xml
<CustomField>
    <fullName>TemplateId__c</fullName>
    <externalId>true</externalId>
    <label>Template Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignTemplateField__c/EformsignTemplateField__c.object-meta.xml
<CustomObject>
    <label>eformsign Template Field</label>
    <nameField>
        <label>EformsignTemplateField Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignTemplateField__c/fields/EformsignTemplate__c.field-meta.xml
<CustomField>
    <fullName>EformsignTemplate__c</fullName>
    <label>이폼사인 템플릿</label>
    <referenceTo>EformsignTemplate__c</referenceTo>
    <relationshipLabel>eformsign Template Field</relationshipLabel>
    <relationshipName>eformsign_Template_Field</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignTemplateField__c/fields/TargetFieldApiName__c.field-meta.xml
<CustomField>
    <fullName>TargetFieldApiName__c</fullName>
    <label>대상 필드 API명</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignTemplateField__c/fields/TargetFieldType__c.field-meta.xml
<CustomField>
    <fullName>TargetFieldType__c</fullName>
    <label>Target Field Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignToken__c/EformsignToken__c.object-meta.xml
<CustomObject>
    <label>eformsign Token</label>
    <nameField>
        <label>eformsign Token Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignToken__c/fields/AccessToken__c.field-meta.xml
<CustomField>
    <fullName>AccessToken__c</fullName>
    <label>Access Token</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignToken__c/fields/ExpireIn__c.field-meta.xml
<CustomField>
    <fullName>ExpireIn__c</fullName>
    <label>Expire In</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignToken__c/fields/RefreshToken__c.field-meta.xml
<CustomField>
    <fullName>RefreshToken__c</fullName>
    <label>Refresh Token</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignToken__c/fields/TokenIssuedDateTime__c.field-meta.xml
<CustomField>
    <fullName>TokenIssuedDateTime__c</fullName>
    <label>Token Issued DateTime</label>
    <type>DateTime</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignToken__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>eformsign_Token</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/EformsignDocumentPageCtrl_Test.cls
/************************************************************************************
 * Description :
 * Ver      Date           Author          Modification
 * ===================================================================================
   1.0      2024-06-27     hs.jung          Create
*************************************************************************************/
@IsTest
private class EformsignDocumentPageCtrl_Test {
    @isTest
    static void testConstructor() {
        Test.setMock(HttpCalloutMock.class, new HttpCalloutSuccessMock());
        User objUser = TestObjectCreator.objUser;
        insert objUser;

        EformsignToken__c objEformsignToken = new EformsignToken__c();
        objEformsignToken.Name = 'test';
        objEformsignToken.AccessToken__c = 'test';
        objEformsignToken.RefreshToken__c = null;
        objEformsignToken.User__c = UserInfo.getUserId();
        objEformsignToken.TokenIssuedDateTime__c = System.today() + 2 ;
        objEformsignToken.ExpireIn__c = 3600;
        insert objEformsignToken;
        System.debug( 'objEformsignToken>>>> ' + objEformsignToken);

        EformsignEnvironment__c defaultConfig = new EformsignEnvironment__c();
        defaultConfig.ApiKey__c = 'apiKey';
        defaultConfig.Privatekey__c = 'privateKey';
        defaultConfig.CompanyId__c = 'companyId';
        defaultConfig.RepresentativeAdminEmail__c = 'https://kr-api.eformsign.com';
        defaultConfig.ApiBaseUrl__c = 'https://kr-api.eformsign.com';
        insert defaultConfig;

        EformsignTemplate__c objEformsignTemplate = new EformsignTemplate__c();
        objEformsignTemplate.Name = 'test';
        objEformsignTemplate.ObjectApiName__c = 'Account';
        objEformsignTemplate.TemplateId__c = 'TemplateId';
        insert objEformsignTemplate;

        Account objAccount = TestObjectCreator.objAccount;
        insert objAccount;

        PageReference pageRef = ApexPages.currentPage();
        ApexPages.currentPage().getParameters().put('objectApiName', 'Account');
        ApexPages.currentPage().getParameters().put('recordId', objAccount.Id);
        ApexPages.currentPage().getParameters().put('templateRecordId',objEformsignTemplate.Id);
        Test.setCurrentPage(pageRef);


        String templateRecordId = ApexPages.currentPage().getParameters().get('templateRecordId');
        EformsignTemplateField__c objeField = new EformsignTemplateField__c();
        objeField.Name = 'test';
        objeField.TargetFieldType__c = 'string';
        objeField.TargetFieldApiName__c = 'Name';
        objeField.EformsignTemplate__c = templateRecordId;
        insert objeField;


        String strJson = '{' +
                '"documentId": "12345",' +
                '"status": "completed",' +
                '"createdDate": "2024-06-27T00:00:00.000Z",' +
                '"details": "Document processing completed successfully."' +
                '}';
        Test.startTest();
        EformsignDocumentPageCtrl controller = new EformsignDocumentPageCtrl();
        System.assertNotEquals(null, controller.tokenUser);
        System.assertNotEquals(null, controller.tokenManager);
        controller.init();
        EformsignDocumentPageCtrl.insertDocumentId(strJson, 'templateRecordId', 'recordId', 'Account');
        Test.stopTest();
    }
    // Http response
    private static HttpResponse newResponse(Integer statusCode) {
        HttpResponse response = new HttpResponse();
        response.setStatusCode(statusCode);
        response.setBody('[{}]');

        return response;
    }

    // StatusCode 200 Mock
    private class HttpCalloutSuccessMock implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest request) {
            HttpResponse response = newResponse(200);

            return response;
        }
    }

}