PA_Education/TestMenifest/force-app/main/default/objects/TrekRecord__c/TrekRecord__c.object-meta.xml
<CustomObject>
    <description>실적 Object</description>
    <label>실적</label>
    <nameField>
        <displayFormat>실적-{0000}</displayFormat>
        <label>실적 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/TrekRecord__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <description>진행한 프로젝트 명</description>
    <label>프로젝트 명</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/TrekRecord__c/fields/StartYear__c.field-meta.xml
<CustomField>
    <fullName>StartYear__c</fullName>
    <description>ex) 2021,2020, 2019</description>
    <label>시작년도</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/HPTrekRecordsViewController_Test.cls
/**
 * Created by sjhyk on 2022-01-20.
 */

@IsTest
private class HPTrekRecordsViewController_Test {
    @IsTest
    static  void itShould() {
        Test.startTest();

        TrekRecord__c objTrekRecord = new TrekRecord__c();
        objTrekRecord.ProjectName__c = 'TESTProjectName';
        objTrekRecord.StartYear__c = '2022';
        objTrekRecord.OrderNum__c = 1;
        insert objTrekRecord;

        HPTrekRecordsViewController.doSearchTrekRecords();
        HPTrekRecordsViewController.getRecordById(objTrekRecord.Id);


        Test.stopTest();
    }
}