PA_Education/TestMenifest/force-app/main/default/objects/TrekRecord__c/TrekRecord__c.object-meta.xml
<CustomObject>
    <description>실적 Object</description>
    <label>실적</label>
    <nameField>
        <displayFormat>실적-{0000}</displayFormat>
        <label>실적 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/TrekRecord__c/fields/HPCheckBox__c.field-meta.xml
<CustomField>
    <fullName>HPCheckBox__c</fullName>
    <defaultValue>false</defaultValue>
    <description>값이 true 인 것만 홈페이지 노출</description>
    <label>홈페이지노출여부</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/TrekRecord__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <description>진행한 프로젝트 명</description>
    <label>프로젝트 명</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/RenewalHPDaeuTrekRecord_Test.cls
/************************************************************************************
 * File Name   : RenewalHPDaeuTrekRecord_Test.cls
 * Author      : SungJu.Kang
 * Date        : 2022. 01. 03
 * Target      : RenewalHPDaeuTrekRecord.cls
 * Description : RenewalHPDaeuTrekRecord.cls Test Class
 * Modification Log
 * ===================================================================================
 * Ver      Date            Author              Modification
 * ===================================================================================
   1.0      2022. 01. 03   SungJu.Kang            Create
*************************************************************************************/

@IsTest
private class RenewalHPDaeuTrekRecord_Test {
    @IsTest
    static void itShould() {
        Test.startTest();
        TrekRecord__c objTrekRecord = new TrekRecord__c();
        objTrekRecord.ProjectName__c = 'TESTProjectName';
        objTrekRecord.OrderNum__c = 1;
        objTrekRecord.HPCheckBox__c =true;
        insert objTrekRecord;

        RenewalHPDaeuTrekRecord.doSearchTrekRecords(true);
        RenewalHPDaeuTrekRecord.doSearchTrekRecords(false);
        RenewalHPDaeuTrekRecord.loadMoreTrekRecords(true);
        RenewalHPDaeuTrekRecord.loadMoreTrekRecords(false);
        RenewalHPDaeuTrekRecord.getRecordById(objTrekRecord.Id, true);
        RenewalHPDaeuTrekRecord.getRecordById(objTrekRecord.Id, false);
        Test.stopTest();
    }
}