PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense Application</label>
    <nameField>
        <displayFormat>EP-{YYYYMM}-{000000}</displayFormat>
        <label>경비신청 코드</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/ExpenseDetail__c.object-meta.xml
<CustomObject>
    <label>Expense Detail</label>
    <nameField>
        <displayFormat>EPD-{000000}</displayFormat>
        <label>경비신청 상세 ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>경비신청금액</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Category2__c.field-meta.xml
<CustomField>
    <fullName>Category2__c</fullName>
    <label>비용구분</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category2</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Expense__c.field-meta.xml
<CustomField>
    <fullName>Expense__c</fullName>
    <label>경비신청 ID</label>
    <referenceTo>Expense__c</referenceTo>
    <relationshipName>ExpenseDetail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/ExpenseBudgetGridController.cls
public without sharing class ExpenseBudgetGridController {

    private final Expense__c myExpense {get; set;}
    public List<DataWrapper> expenseBudgetList {
        get {
            if(expenseBudgetList == null) {
                expenseBudgetList = new List<DataWrapper>();
            }
            return expenseBudgetList;
        } 
        set;
    }
    private ApexPages.StandardController controller {get; set;}

    public ExpenseBudgetGridController(ApexPages.StandardController stdController) {
    controller = stdController;
        this.myExpense = (Expense__c)stdController.getRecord();
        setList();
    }

    public void setList(){
        Id expenseId = this.myExpense.Id;
        List<AggregateResult> listExpenseDetail = [
                SELECT      toLabel(Category2__c), Sum(Amount__c) Amount, COUNT(Id) Cnt
                FROM        ExpenseDetail__c
                WHERE       Expense__c =:expenseId
                GROUP BY    Category2__c];

        for(AggregateResult ar : listExpenseDetail){
            expenseBudgetList.add(new DataWrapper(ar));
        }

        system.debug('after total : '+ expenseBudgetList);
    }

    public class DataWrapper{
        public String  Category2 {get;set;}
        public Decimal amount {get;set;}
        public Integer cnt {get;set;}

        public DataWrapper(AggregateResult ar){
            Category2    = (String)ar.get('Category2__c');
            amount       = (Decimal)ar.get('Amount');
            cnt          = (Integer)ar.get('Cnt');
        }
    }
}