PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense Application</label>
    <nameField>
        <displayFormat>EP-{YYYYMM}-{000000}</displayFormat>
        <label>경비신청 코드</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Expense Application</relationshipLabel>
    <relationshipName>ExpenseApplication</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>프로젝트에 대한 기본정보를 관리하며, Deal Closing 이후 생성한다. 영업담당자가 계약 체결 후 기초 데이터를 작성하며, 프로젝트 진행 중에는 PM이 관리하고, 대금청구/지급 관련 정보는 회계에서 관리한다.</description>
    <label>프로젝트</label>
    <nameField>
        <label>프로젝트 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>종료 일자</label>
    <type>Date</type>
</CustomField>

Test/force-app/main/default/classes/Expense_tr.cls
public with sharing class Expense_tr extends TriggerHandler {
    
    private List<Expense__c> listExpenseNew {get;set;}
    
    

    


    public Expense_tr(){
        listExpenseNew=(List<Expense__c>) Trigger.new;
        
    }
    public override void beforeInsert(){
        
        
    }

    public override void afterInsert(){
        afterExpenseInsert();
    }

    public override void beforeUpdate(){
        
    }

    public override void afterUpdate(){
    }

    public override void beforeDelete(){
        
    }

    public void afterExpenseInsert() {
        Set<Id> setProject_Id=new Set<Id>();
        for(Expense__c e:listExpenseNew){
            setProject_Id.add(e.Project__c);
        }
    
        List<Project__c> listProject=new List<Project__c>();
        listProject=[
            select id,LastExpenseDate__c,EndDate__c
            from Project__c
            where id in:setProject_Id 
            and EndDate__c> :System.today()
        ];

        
        for(Project__c p:listProject){
            p.LastExpenseDate__c=date.today();
        }

        if(!listProject.isEmpty()){
            update listProject;
        }

        
    }



}