PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense Application</label>
    <nameField>
        <displayFormat>EP-{YYYYMM}-{000000}</displayFormat>
        <label>경비신청 코드</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>비고</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/FirstExpenseRequest__c.field-meta.xml
<CustomField>
    <fullName>FirstExpenseRequest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>일반 사원일 경우 &apos;사업부장/PM&apos;선택 &amp;&amp;
사업부장/PM일 경우 &apos;이응도 전무님&apos;선택</inlineHelpText>
    <label>1차 승인자 지정</label>
    <referenceTo>User</referenceTo>
    <relationshipName>FirstExpenseRequest</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Expense Application</relationshipLabel>
    <relationshipName>ExpenseApplication</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/SecondApproverSelection__c.field-meta.xml
<CustomField>
    <fullName>SecondApproverSelection__c</fullName>
    <defaultValue>false</defaultValue>
    <label>2차 승인 여부 (사업부장 / 팀장)</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/Submit_Date__c.field-meta.xml
<CustomField>
    <fullName>Submit_Date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>기안일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/UseMonth__c.field-meta.xml
<CustomField>
    <fullName>UseMonth__c</fullName>
    <defaultValue>TEXT( MONTH( ADDMONTHS( TODAY() ,-1) ) )</defaultValue>
    <inlineHelpText>신청할 경비내역의 사용월을 입력합니다.</inlineHelpText>
    <label>경비 사용 월</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/UseYear__c.field-meta.xml
<CustomField>
    <fullName>UseYear__c</fullName>
    <defaultValue>TEXT( YEAR(  ADDMONTHS(TODAY(),-1)  ) )</defaultValue>
    <inlineHelpText>신청할 경비내역의 연도를 입력합니다.</inlineHelpText>
    <label>경비 사용 연도</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2013</fullName>
            </value>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
                <default>true</default>
                <label>2022</label>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/ExpenseDetail__c.object-meta.xml
<CustomObject>
    <label>Expense Detail</label>
    <nameField>
        <displayFormat>EPD-{000000}</displayFormat>
        <label>경비신청 상세 ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>경비신청금액</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Category1__c.field-meta.xml
<CustomField>
    <fullName>Category1__c</fullName>
    <label>사용목적</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category1</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Category2__c.field-meta.xml
<CustomField>
    <fullName>Category2__c</fullName>
    <label>비용구분</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category2</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>사용일시</label>
    <type>DateTime</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>내용</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Expense__c.field-meta.xml
<CustomField>
    <fullName>Expense__c</fullName>
    <label>경비신청 ID</label>
    <referenceTo>Expense__c</referenceTo>
    <relationshipName>ExpenseDetail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>영업 관련 비용은 해당 영업기회를 선택하세요.</inlineHelpText>
    <label>영업기회</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipName>ExpenseDetail_Oppty</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>지출구분</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>개인카드</fullName>
            </value>
            <value>
                <fullName>법인카드</fullName>
            </value>
            <value>
                <fullName>현금</fullName>
            </value>
            <value>
                <fullName>세금계산서</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>2024.1. 기준 사용 X (Expense__c에서 프로젝트 입력)</description>
    <inlineHelpText>내부 경비 처리는 
&apos;본사공통&apos; 프로젝트를 선택하시고 
프로젝트 관련 비용은 해당 프로젝트를 선택하세요.</inlineHelpText>
    <label>프로젝트 (사용X)</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Expense Detail</relationshipLabel>
    <relationshipName>ExpenseDetail_Project</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Oppty</label>
    <nameField>
        <label>영업기회 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Opportunity__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>사업금액</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Opportunity__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>9. 기타 정보</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>프로젝트에 대한 기본정보를 관리하며, Deal Closing 이후 생성한다. 영업담당자가 계약 체결 후 기초 데이터를 작성하며, 프로젝트 진행 중에는 PM이 관리하고, 대금청구/지급 관련 정보는 회계에서 관리한다.</description>
    <label>프로젝트</label>
    <nameField>
        <label>프로젝트 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/classes/ExpenseNewController.cls
public class ExpenseNewController {

    public static List<Map<String, String>> getPicklistValue(String objectAPIName, String fieldName) {
        List<Map<String, String>> options = new List<Map<String, String>>();
        
        Schema.SObjectType sobject_type = Schema.getGlobalDescribe().get(objectAPIName);
        Schema.DescribeSObjectResult sobjectDescribe = sobject_type.getDescribe();
        Map<String, Schema.SObjectField> fieldMap = sobjectDescribe.fields.getMap();
        
        List<Schema.PicklistEntry> pickListValues = fieldMap.get(fieldName).getDescribe().getPickListValues();
        
        for (Schema.PicklistEntry pickListEntry : pickListValues) {
            if (pickListEntry.isActive()) options.add(new Map<String, String>{'value' => pickListEntry.getValue()
                                                                                , 'label' => pickListEntry.getLabel()
                                                                                , 'default' => String.valueOf(pickListEntry.isDefaultValue())
                                                                                });
        }
        return options;
    }
	//Field Label 갖고오는 Map Container
	@AuraEnabled
    public static Map<String, String> getObjectFieldLabel(String sObjectName){
		Schema.SObjectType schemaObject = Schema.getGlobalDescribe().get(sObjectName); 
		Schema.DescribeSobjectResult schemaObjectResult = schemaObject.getDescribe();
		Map<String, Schema.SObjectField> mapSchemaObjectResult = schemaObjectResult.fields.getMap();        

		Map<String, String> mapFieldLabel = new Map<String, String>();
		for(Schema.SObjectField obj : mapSchemaObjectResult.values()){                            
			Schema.DescribeFieldResult f = mapSchemaObjectResult.get(obj.getDescribe().getName()).getDescribe();
			//system.debug('mapFieldLabel: : : : '+mapFieldLabel);
			mapFieldLabel.put(f.getName(), f.getLabel());
		}

		return mapFieldLabel;
	}

	@AuraEnabled
    public static Map<String, Object> getInitData(Id expId){
        System.debug('getInitData For Parameter index throw=========Start');

    	//경비신청 레코드 조회
        Expense__c objExpense = new Expense__c();
        if(expId != null){
    	   objExpense = [SELECT ID,
    							 Name,
    							 Submit_Date__c,
    							 FirstExpenseRequest__c,
    							 FirstExpenseRequest__r.Name,
    							 SecondApproverSelection__c,
                                 UseYear__c,
                                 UseMonth__c
								 FROM Expense__c
								 WHERE Id =: expId
    							 ]; 

        }
        List<ExpenseDetail__c> listExpDetail = new List<ExpenseDetail__c>();
        if(expId != null){
    	//경비신청 상세 조회
    	   listExpDetail = [SELECT Id,
    								Name,
    								Date__c,
    								Category1__c,
    								Category2__c,
    								Payment_Type__c,
    								Amount__c,
                                    Description__c,
    								Project_Name__c,
    								Project_Name__r.Name,
    								Opportunity_Name__c,
    								Opportunity_Name__r.Name,
                                    Expense__c
    								FROM ExpenseDetail__c
    								WHERE Expense__c =: expId ORDER BY Date__c DESC, Category1__c
    								];
        }
        else{
        //초기 Init Row 생성
            listExpDetail = new List<ExpenseDetail__c>();
			ExpenseDetail__c objExpenseDetail= new ExpenseDetail__c(
                                                    Id = null,
                                                    Date__c = system.today(),
                                                    Category1__c = '본사행정',
                                                    Category2__c = '식비',
                                                    Payment_Type__c = '개인카드',
                                                    Amount__c = 0,
                                                    Description__c = '',
                                                    Project_Name__c = null,
                                                    Opportunity_Name__c = null,
                                                    Expense__c = expId
                                                    );
            listExpDetail.add(objExpenseDetail);
        }
			Map<String, Object> mapReturnValue = new Map<String, Object>{
				'Expense' => objExpense,
				'ExpenseDetail' => listExpDetail,
                'PicklistYear' => getPicklistValue('Expense__c', 'UseYear__c'),
                'PicklistMonth' => getPicklistValue('Expense__c', 'UseMonth__c'),
				'PicklistCategory1' => getPicklistValue('ExpenseDetail__c', 'Category1__c'),
				'PicklistCategory2' => getPicklistValue('ExpenseDetail__c', 'Category2__c'),
				'PicklistPayment' => getPicklistValue('ExpenseDetail__c', 'Payment_Type__c')
            };
        System.debug('mapReturnValue::_ ' + mapReturnValue);
        System.debug('getInitData For Parameter index throw=========End');

        return mapReturnValue;  
    } 


    

    @AuraEnabled
    public static String doSave(Expense__c objExp, List<Object> listExpDetail, List<Id> listDel) {
        List<ExpenseDetail__c> listExpDetailTemp = new List<ExpenseDetail__c>();
        ExpenseDetail__c objExpDetailTemp;

        //category1 의 본사행정 ,마케팅 선택시 자동으로 입력되는 Id 값
        Project__c projectCommon = [select Id, Name from Project__c where Name = '본사공통' limit 1];
        Project__c projectMarketing = [select Id, Name from Project__c where Name = '마케팅' limit 1];         
        Savepoint preSave = Database.setSavepoint();

        //19.08.07 검색 값 중복issue 분기로직 추가 kmh
        try {
            upsert objExp;

        } catch(DmlException dmlExcep) {
            System.debug('dmlExcep.getMessage() : ' + dmlExcep.getMessage());
            Database.rollback(preSave);
            return 'ERROR/에러가 발생했습니다./'+dmlExcep.getMessage();
        }

        Map<String, Object> mapExpDetail;
        for(Object objExpDetail : listExpDetail){
            mapExpDetail = (Map<String,Object>)Json.deserializeUntyped(Json.serialize(objExpDetail));

            objExpDetailTemp = new ExpenseDetail__c();
            if(objExpDetailTemp.Expense__c == null){
                objExpDetailTemp.Expense__c = objExp.Id;
            }
          
            if(objExpDetailTemp.Category1__c == '마케팅' && projectMarketing != null) {
                objExpDetailTemp.Project_Name__c  = projectMarketing.Id;
            } else if(objExpDetailTemp.Category1__c == '본사행정' && projectCommon != null) {
                objExpDetailTemp.Project_Name__c  = projectCommon.Id;
            }

            objExpDetailTemp.Category1__c = String.valueOf(mapExpDetail.get('Category1__c'));
            if(objExpDetailTemp.Category1__c == '프로젝트') {
                if(mapExpDetail.get('Project_Name__c') == null || String.valueOf(mapExpDetail.get('Project_Name__c')) == '') {
                    throw new AuraHandledException('프로젝트를 선택하세요.');
                }
                objExpDetailTemp.Id = String.valueOf(mapExpDetail.get('Id'));
                objExpDetailTemp.Amount__c = Decimal.valueOf(String.valueOf(mapExpDetail.get('Amount__c')));
                objExpDetailTemp.Project_Name__c = String.valueOf(mapExpDetail.get('Project_Name__c'));
                objExpDetailTemp.Description__c = String.valueOf(mapExpDetail.get('Description__c'));
                objExpDetailTemp.Category2__c = String.valueOf(mapExpDetail.get('Category2__c'));
                objExpDetailTemp.Date__c = Date.valueOf(String.valueOf(mapExpDetail.get('Date__c')));
                objExpDetailTemp.Payment_Type__c = String.valueOf(mapExpDetail.get('Payment_Type__c'));    
                objExpDetailTemp.Opportunity_Name__c = null;

                listExpDetailTemp.add(objExpDetailTemp);

            }
            else if(objExpDetailTemp.Category1__c == '영업') {
                if(mapExpDetail.get('Opportunity_Name__c') == null || String.valueOf(mapExpDetail.get('Opportunity_Name__c')) == '') {
                    throw new AuraHandledException('프로젝트를 선택하세요.');
                }
                objExpDetailTemp.Id = String.valueOf(mapExpDetail.get('Id'));
                objExpDetailTemp.Amount__c = Decimal.valueOf(String.valueOf(mapExpDetail.get('Amount__c')));
                objExpDetailTemp.Opportunity_Name__c = String.valueOf(mapExpDetail.get('Opportunity_Name__c'));
                objExpDetailTemp.Description__c = String.valueOf(mapExpDetail.get('Description__c'));
                objExpDetailTemp.Category2__c = String.valueOf(mapExpDetail.get('Category2__c'));
                objExpDetailTemp.Date__c = Date.valueOf(String.valueOf(mapExpDetail.get('Date__c')));
                objExpDetailTemp.Payment_Type__c = String.valueOf(mapExpDetail.get('Payment_Type__c'));
                objExpDetailTemp.Project_Name__c = null;

                listExpDetailTemp.add(objExpDetailTemp);
            }
            else {
                objExpDetailTemp.Id = String.valueOf(mapExpDetail.get('Id'));
                objExpDetailTemp.Amount__c = Decimal.valueOf(String.valueOf(mapExpDetail.get('Amount__c')));
                objExpDetailTemp.Project_Name__c = String.valueOf(mapExpDetail.get('Project_Name__c'));
                objExpDetailTemp.Opportunity_Name__c = String.valueOf(mapExpDetail.get('Opportunity_Name__c'));
                objExpDetailTemp.Description__c = String.valueOf(mapExpDetail.get('Description__c'));
                objExpDetailTemp.Category2__c = String.valueOf(mapExpDetail.get('Category2__c'));
                objExpDetailTemp.Date__c = Date.valueOf(String.valueOf(mapExpDetail.get('Date__c')));
                objExpDetailTemp.Payment_Type__c = String.valueOf(mapExpDetail.get('Payment_Type__c'));

                listExpDetailTemp.add(objExpDetailTemp);
            }
        }

        try {
            if(!listDel.isEmpty()) {     
                List<ExpenseDetail__c> listExpDetailDel = [SELECT Id FROM ExpenseDetail__c WHERE Id IN : listDel];
                delete listExpDetailDel;
            }
            
            if(!listExpDetailTemp.isEmpty()) {
                upsert listExpDetailTemp;
            }

        } catch(DmlException dmlExcep) {
            System.debug('dmlExcep.getMessage() : ' + dmlExcep.getMessage());
            Database.rollback(preSave);
            return 'ERROR/에러가 발생했습니다./'+dmlExcep.getMessage();
        }

        return 'SUCCESS/성공적으로 저장되었습니다./'+ objExp.Id;
    
    }
}