PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense Application</label>
    <nameField>
        <displayFormat>EP-{YYYYMM}-{000000}</displayFormat>
        <label>경비신청 코드</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>승인상태</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Writing</fullName>
                <default>true</default>
                <label>작성</label>
            </value>
            <value>
                <fullName>Consider</fullName>
                <label>승인검토중</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>승인완료</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>승인거부</label>
            </value>
            <value>
                <fullName>Recall</fullName>
                <label>회수됨</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Expense Application</relationshipLabel>
    <relationshipName>ExpenseApplication</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/ExpenseDetail__c.object-meta.xml
<CustomObject>
    <label>Expense Detail</label>
    <nameField>
        <displayFormat>EPD-{000000}</displayFormat>
        <label>경비신청 상세 ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>경비신청금액</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Category2__c.field-meta.xml
<CustomField>
    <fullName>Category2__c</fullName>
    <label>비용구분</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category2</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Expense__c.field-meta.xml
<CustomField>
    <fullName>Expense__c</fullName>
    <label>경비신청 ID</label>
    <referenceTo>Expense__c</referenceTo>
    <relationshipName>ExpenseDetail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/ProjectBudget__c.field-meta.xml
<CustomField>
    <fullName>ProjectBudget__c</fullName>
    <formula>1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>프로젝트 예산</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>프로젝트에 대한 기본정보를 관리하며, Deal Closing 이후 생성한다. 영업담당자가 계약 체결 후 기초 데이터를 작성하며, 프로젝트 진행 중에는 PM이 관리하고, 대금청구/지급 관련 정보는 회계에서 관리한다.</description>
    <label>프로젝트</label>
    <nameField>
        <label>프로젝트 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/ProjectBudget__c/ProjectBudget__c.object-meta.xml
<CustomObject>
    <label>프로젝트 비용 예산</label>
    <nameField>
        <label>프로젝트 비용 예산 신청명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/ProjectBudget__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>프로젝트</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>프로젝트 비용 예산</relationshipLabel>
    <relationshipName>ProjectBudget</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ProjectBudget__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>승인상태</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>작성중</fullName>
                <default>true</default>
                <label>작성중</label>
            </value>
            <value>
                <fullName>승인중</fullName>
            </value>
            <value>
                <fullName>승인완료</fullName>
            </value>
            <value>
                <fullName>반려</fullName>
            </value>
            <value>
                <fullName>회수</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ProjectBudgetDetail__c/ProjectBudgetDetail__c.object-meta.xml
<CustomObject>
    <label>프로젝트 비용 예산 상세</label>
    <nameField>
        <displayFormat>P-EXP-{YY}{MM}-{000}</displayFormat>
        <label>프로젝트 예산</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/ProjectBudgetDetail__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <formula>UnitPrice__c  *  Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>단가 * 수량</inlineHelpText>
    <label>금액</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ProjectBudgetDetail__c/fields/Category2__c.field-meta.xml
<CustomField>
    <fullName>Category2__c</fullName>
    <label>예산 구분</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category2</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ProjectBudgetDetail__c/fields/ProjectBudget__c.field-meta.xml
<CustomField>
    <fullName>ProjectBudget__c</fullName>
    <label>프로젝트 비용 예산</label>
    <referenceTo>ProjectBudget__c</referenceTo>
    <relationshipLabel>프로젝트 비용 예산 상세</relationshipLabel>
    <relationshipName>ProjectBudgetDetail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/ProjectBudgetExpenseGridController.cls
public without sharing class ProjectBudgetExpenseGridController {

    private final Project__c myPrj{get; set;}
    public List<DataWrapper> prjExpBgtList{get; set;}
    private ApexPages.StandardController controller {get; set;}

    // The extension constructor initializes the private member
    // variable mysObject by using the getRecord method from the standard
    // controller.
    public ProjectBudgetExpenseGridController(ApexPages.StandardController stdController) {
        controller = stdController;
        this.myPrj = (Project__c)stdController.getRecord();
       setList();
    }

    public void setList(){
        Id prjId = this.myPrj.Id;
        List<ProjectBudgetDetail__c> prjExpLst = [SELECT toLabel(Category2__c), Amount__c 
                                               FROM ProjectBudgetDetail__c 
                                              WHERE ProjectBudget__r.Project__c =:prjId
                                                AND ProjectBudget__r.Status__c in ('승인완료','Approved')];

        List<ExpenseDetail__c> expDtlLst = [SELECT toLabel(Category2__c), Amount__c FROM ExpenseDetail__c WHERE Expense__r.Project__c = :prjId
                                             AND Expense__r.ApprovalStatus__c in ('승인완료','Approved')];

        Map<String,DataWrapper> prjExpBgtMap = new Map<String, DataWrapper>();
        DataWrapper dwSumInit = new DataWrapper();   
        dwSumInit.type = '계';
        dwSumInit.budgetAmount = 0;
        prjExpBgtMap.put(dwSumInit.type,dwSumInit);

        for(ProjectBudgetDetail__c prjExp : prjExpLst){
            DataWrapper dw = prjExpBgtMap.get(prjExp.Category2__c);
            if(dw == null){
                dw = new DataWrapper();   
                dw.type = prjExp.Category2__c;
            }
            dw.budgetAmount += prjExp.Amount__c;
            prjExpBgtMap.put(dw.type,dw);  
            
            DataWrapper dwSum = prjExpBgtMap.get('계');
            dwSum.budgetAmount += prjExp.Amount__c;
            prjExpBgtMap.put(dwSum.type,dwSum);        
        }
        for(ExpenseDetail__c expDtl : expDtlLst){
            DataWrapper dw = prjExpBgtMap.get(expDtl.Category2__c);
            if(dw == null){
                dw = new DataWrapper();   
                dw.type = expDtl.Category2__c;
            }
            dw.expenseAmount += expDtl.Amount__c;  
            prjExpBgtMap.put(dw.type,dw);    
            
            DataWrapper dwSum = prjExpBgtMap.get('계');
            dwSum.expenseAmount += expDtl.Amount__c;  
            prjExpBgtMap.put(dwSum.type,dwSum);          
        }
        prjExpBgtList = prjExpBgtMap.values();
        prjExpBgtList.sort();
    }

    public class DataWrapper implements Comparable {
        public String type{get;set;}
        public Decimal budgetAmount{get;set;}
        public Decimal expenseAmount{get;set;}
        public Decimal remainAmount{
            get{
                return budgetAmount - expenseAmount;
            }
            set;
        }
        public DataWrapper(){
            budgetAmount = 0;
            expenseAmount = 0;
        }
        public Integer compareTo(Object compareTo){
            DataWrapper compareToWrapper = (DataWrapper)compareTo;
            if (type == compareToWrapper.type) return 0;
            if (type == '계') return 1;
            return -1; 
        }
    }
}