PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense Application</label>
    <nameField>
        <displayFormat>EP-{YYYYMM}-{000000}</displayFormat>
        <label>경비신청 코드</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>비고</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Expense Application</relationshipLabel>
    <relationshipName>ExpenseApplication</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/PerformProject__c.object-meta.xml
<CustomObject>
    <label>프로젝트 수행팀</label>
    <nameField>
        <displayFormat>PJ-{0000}</displayFormat>
        <label>Seq</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트 명</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>프로젝트 수행팀</relationshipLabel>
    <relationshipName>Project</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>프로젝트에 대한 기본정보를 관리하며, Deal Closing 이후 생성한다. 영업담당자가 계약 체결 후 기초 데이터를 작성하며, 프로젝트 진행 중에는 PM이 관리하고, 대금청구/지급 관련 정보는 회계에서 관리한다.</description>
    <label>프로젝트</label>
    <nameField>
        <label>프로젝트 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

Test/force-app/main/default/classes/PrintExpenseController.cls
/************************************************************************************
 * Description :
 *
 * Ver      Date           Author          Modification
 * ===================================================================================
   1.0      2022-09-06     yr.lee          Create
*************************************************************************************/

public with sharing class PrintExpenseController {
    public List<List<Expense__c>> listExpenseItem { get; set; }
   
    
    public PrintExpenseController() {
        //url속 "recordId" 라는 파라미터를 가져오는 코드
        Id recordId = ApexPages.currentPage().GetParameters().get('recordId');
        
        listExpenseItem=new List<List<Expense__c>>();
        //해당 Expense의 정보들을 가져오는 쿼리
        List<Expense__c> listExpense=
        [
            select Name, Description__c, Spending__c
            from Expense__c
            where Project__r.Id = :recordId
        ];

        List<Expense__c> currentPage=new List<Expense__c>();

        for (Integer i = 0; i < listExpense.size(); i++) {
            currentPage.add(listExpense[i]);
            if (Math.mod(i + 1, 20) == 0 || i == listExpense.size() - 1) {
                listExpenseItem.add(currentPage);
                currentPage = new List<Expense__c>();
            }
        }
        
    }

    @AuraEnabled
    public static String doSavePdf(String strRecordId) {
        String result = '';
        String vfPageUrl = '';
        
        try{
            vfPageUrl = '/apex/PrintExpense?recordId=' + strRecordId;
            PageReference templatePageReference = new PageReference(vfPageUrl);
        
        
            Blob templateBLOB;
            if (System.test.isRunningTest()){
                templateBLOB = Blob.valueOf('Unit test');
            } else {
                templateBLOB = templatePageReference.getContentAsPDF();
            }
            
            List<AggregateResult> cntDocument = new List<AggregateResult>();
            cntDocument = [
                    SELECT id
                    FROM ContentDocumentLink
                    WHERE LinkedEntityId = :strRecordId
                    GROUP BY Id
            ];
        
            ContentVersion objContentVersion = new ContentVersion();
            objContentVersion.Title                     = 'SAMPLE';
            objContentVersion.VersionData               = templateBLOB;
            objContentVersion.PathOnClient              = 'SAMPLE.pdf';
            objContentVersion.FirstPublishLocationId    = strRecordId;
        
            insert objContentVersion;
        
            objContentVersion = [
                    SELECT Id, ContentDocumentId 
                    FROM ContentVersion 
                    WHERE Id =:objContentVersion.Id
            ];
        
            List<ContentDocumentLink> listCdl = new List<ContentDocumentLink>([
                    SELECT Id, ShareType, Visibility
                    from ContentDocumentLink
                    where LinkedEntityId = :strRecordId
                    and ContentDocumentId = :objContentVersion.ContentDocumentId
            ]);
        
            result = 'success';
        
        } catch(Exception e){
            System.debug('Error line : ' + e.getLineNumber());
            System.debug('Error message : ' + e.getMessage());
            System.debug('Error  cause : ' + e.getCause());
            result = 'error';
        }
        
        return result;
    }
}