PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense Application</label>
    <nameField>
        <displayFormat>EP-{YYYYMM}-{000000}</displayFormat>
        <label>경비신청 코드</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>비고</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Expense Application</relationshipLabel>
    <relationshipName>ExpenseApplication</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/PerformProject__c.object-meta.xml
<CustomObject>
    <label>프로젝트 수행팀</label>
    <nameField>
        <displayFormat>PJ-{0000}</displayFormat>
        <label>Seq</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트 명</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>프로젝트 수행팀</relationshipLabel>
    <relationshipName>Project</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>프로젝트에 대한 기본정보를 관리하며, Deal Closing 이후 생성한다. 영업담당자가 계약 체결 후 기초 데이터를 작성하며, 프로젝트 진행 중에는 PM이 관리하고, 대금청구/지급 관련 정보는 회계에서 관리한다.</description>
    <label>프로젝트</label>
    <nameField>
        <label>프로젝트 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>종료 일자</label>
    <type>Date</type>
</CustomField>

Test/force-app/main/default/classes/ExpenseInfoDelete_ba.cls
global with sharing class ExpenseInfoDelete_ba implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts{
    global Boolean isError = false;
    global String strId;

    public ExpenseInfoDelete_ba() {
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        Date dateThreeMonthAgo = Date.today().addMonths(-3);
        String strQuery = 'SELECT Id ';
        strQuery += '   FROM Expense__c';
        strQuery += '   WHERE  Project__r.EndDate__c < :dateThreeMonthAgo  ';
        strQuery += '   ORDER BY Description__c  ';

        return DataBase.getQueryLocator(strQuery);
    }

    global void execute(Database.BatchableContext BC, List<Expense__c> listTarget){
        try {
            //Code Block
            for(Expense__c objExpense : listTarget){
                objExpense.Description__c = null;
            }

            update listTarget;
        }catch(Exception e) {
            this.isError = true;
            System.debug('Error ===================> Error : ' + e.getMessage() + '/' + e.getLineNumber());
        }
    }

    global void finish(Database.BatchableContext BC) {
    }
}