PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense Application</label>
    <nameField>
        <displayFormat>EP-{YYYYMM}-{000000}</displayFormat>
        <label>경비신청 코드</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/BudgetType__c.field-meta.xml
<CustomField>
    <fullName>BudgetType__c</fullName>
    <label>사용목적</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BudgetType</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>비고</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/ExpenseDetail__c.object-meta.xml
<CustomObject>
    <label>Expense Detail</label>
    <nameField>
        <displayFormat>EPD-{000000}</displayFormat>
        <label>경비신청 상세 ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>경비신청금액</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/BillingAmount__c.field-meta.xml
<CustomField>
    <fullName>BillingAmount__c</fullName>
    <label>결제금액</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/BusinessType__c.field-meta.xml
<CustomField>
    <fullName>BusinessType__c</fullName>
    <label>업종</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/CardCompany__c.field-meta.xml
<CustomField>
    <fullName>CardCompany__c</fullName>
    <label>카드사</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Category2__c.field-meta.xml
<CustomField>
    <fullName>Category2__c</fullName>
    <label>비용구분</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category2</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>사용일시</label>
    <type>DateTime</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>내용</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Expense__c.field-meta.xml
<CustomField>
    <fullName>Expense__c</fullName>
    <label>경비신청 ID</label>
    <referenceTo>Expense__c</referenceTo>
    <relationshipName>ExpenseDetail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/fm_Expense__c.field-meta.xml
<CustomField>
    <fullName>fm_Expense__c</fullName>
    <formula>Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>경비신청금액</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/fm_ProjectOppty__c.field-meta.xml
<CustomField>
    <fullName>fm_ProjectOppty__c</fullName>
    <formula>IF(ISPICKVAL(Category1__c, &quot;프로젝트&quot;)
				,  Project_Name__r.Name 
				, IF(ISPICKVAL(Category1__c, &quot;영업&quot;)
									, Opportunity_Name__r.Name
									, TEXT(Category1__c)
				  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>프로젝트(보고서)</label>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>잠재고객</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Expense Detail</relationshipLabel>
    <relationshipName>Expense_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>영업 관련 비용은 해당 영업기회를 선택하세요.</inlineHelpText>
    <label>영업기회</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipName>ExpenseDetail_Oppty</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/PriorExpenseApplication__c.field-meta.xml
<CustomField>
    <fullName>PriorExpenseApplication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>경비사전승인</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>이미 경비신청이 존재하는 사전승인입니다.</errorMessage>
        <filterItems>
            <field>PriorExpenseApplication__c.ApprovalStatus__c</field>
            <operation>equals</operation>
            <value>승인완료</value>
        </filterItems>
        <filterItems>
            <field>PriorExpenseApplication__c.fm_ExpenseApplicatedYn__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PriorExpenseApplication__c</referenceTo>
    <relationshipLabel>Expense Detail</relationshipLabel>
    <relationshipName>PriorExpenseApplication</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>2024.1. 기준 사용 X (Expense__c에서 프로젝트 입력)</description>
    <inlineHelpText>내부 경비 처리는 
&apos;본사공통&apos; 프로젝트를 선택하시고 
프로젝트 관련 비용은 해당 프로젝트를 선택하세요.</inlineHelpText>
    <label>프로젝트 (사용X)</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Expense Detail</relationshipLabel>
    <relationshipName>ExpenseDetail_Project</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/SalesType__c.field-meta.xml
<CustomField>
    <fullName>SalesType__c</fullName>
    <label>영업구분</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>기타</fullName>
            </value>
            <value>
                <fullName>잠재고객</fullName>
            </value>
            <value>
                <fullName>영업기회</fullName>
            </value>
            <value>
                <fullName>프로젝트</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/StoreAddress__c.field-meta.xml
<CustomField>
    <fullName>StoreAddress__c</fullName>
    <label>소재지</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/StoreName__c.field-meta.xml
<CustomField>
    <fullName>StoreName__c</fullName>
    <label>가맹점명</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>잠재고객</label>
    <nameField>
        <label>이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Oppty</label>
    <nameField>
        <label>영업기회 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Opportunity__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>사업금액</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Opportunity__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>9. 기타 정보</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PriorExpenseApplication__c/PriorExpenseApplication__c.object-meta.xml
<CustomObject>
    <label>경비사전승인</label>
    <nameField>
        <label>경비사전승인 이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/PriorExpenseApplication__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>내용</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PriorExpenseApplication__c/fields/ExpenseDetail__c.field-meta.xml
<CustomField>
    <fullName>ExpenseDetail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expense Detail</label>
    <referenceTo>ExpenseDetail__c</referenceTo>
    <relationshipLabel>경비사전승인</relationshipLabel>
    <relationshipName>PriorExpenseApplication_ExpenseDetail</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>프로젝트에 대한 기본정보를 관리하며, Deal Closing 이후 생성한다. 영업담당자가 계약 체결 후 기초 데이터를 작성하며, 프로젝트 진행 중에는 PM이 관리하고, 대금청구/지급 관련 정보는 회계에서 관리한다.</description>
    <label>프로젝트</label>
    <nameField>
        <label>프로젝트 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/classes/ExpenseBudgetGridCmpController.cls
public with sharing class ExpenseBudgetGridCmpController {

    @AuraEnabled
    public static Map<String, Object> getInit(Id recordId) {
        Expense__c objExpense = [
                SELECT Id, BudgetType__c
                FROM Expense__c
                WHERE Id =: recordId
        ];

        List<ExpenseDetail__c> listExpenseDetail = [
            SELECT Id, Name, FORMAT(Date__c) Date__c, Category2__c, Amount__c, Description__c, Project_Name__c,
                        Project_Name__r.Name, Opportunity_Name__c, Opportunity_Name__r.Name, Expense__c,
                        CardCompany__c, StoreName__c, BusinessType__c, StoreAddress__c,
                        fm_ProjectOppty__c, BillingAmount__c, PriorExpenseApplication__r.Name,
                        SalesType__c, Lead__c, Lead__r.Name, fm_Expense__c
            FROM ExpenseDetail__c
            WHERE Expense__c =: recordId
            ORDER BY Date__c, Category2__c
        ];

        return new Map<String, Object> {
            'objExpense'        => objExpense,
            'listExpenseDetail' => listExpenseDetail
        };
    }

    //Field Label 갖고오는 Map Container
    @AuraEnabled
    public static Map<String, String> getObjectFieldLabel(String sObjectName){
        Schema.SObjectType schemaObject = Schema.getGlobalDescribe().get(sObjectName);
        Schema.DescribeSObjectResult schemaObjectResult = schemaObject.getDescribe();
        Map<String, Schema.SObjectField> mapSchemaObjectResult = schemaObjectResult.fields.getMap();

        Map<String, String> mapFieldLabel = new Map<String, String>();
        for(Schema.SObjectField obj : mapSchemaObjectResult.values()){
            Schema.DescribeFieldResult f = mapSchemaObjectResult.get(obj.getDescribe().getName()).getDescribe();
            mapFieldLabel.put(f.getName(), f.getLabel());
        }
        return mapFieldLabel;
    }
}