PA_Education/TestMenifest/force-app/main/default/objects/Budget__c/Budget__c.object-meta.xml
<CustomObject>
    <label>예산</label>
    <nameField>
        <label>예산이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Budget__c/fields/BudgetType__c.field-meta.xml
<CustomField>
    <fullName>BudgetType__c</fullName>
    <label>예산배정단위</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BudgetType</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Budget__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>BudgetProject</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>프로젝트에 대한 기본정보를 관리하며, Deal Closing 이후 생성한다. 영업담당자가 계약 체결 후 기초 데이터를 작성하며, 프로젝트 진행 중에는 PM이 관리하고, 대금청구/지급 관련 정보는 회계에서 관리한다.</description>
    <label>프로젝트</label>
    <nameField>
        <label>프로젝트 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/fields/Completed__c.field-meta.xml
<CustomField>
    <fullName>Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>프로젝트가 종료되면 체크함.</inlineHelpText>
    <label>완료 여부</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/fields/PM__c.field-meta.xml
<CustomField>
    <fullName>PM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트 관리자</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PM</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/fields/PMEmail__c.field-meta.xml
<CustomField>
    <fullName>PMEmail__c</fullName>
    <label>PMEmail</label>
    <type>Email</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/Project_tr.cls
/** ==================================================================================
*   File Name   Project_tr
*   Author      : yj.kim
*   Date        : 2023.07.07
*   Description : 프로젝트 PM Email Update, 완료여부 = true 시 해당 PM에게 Email 전송
* ==================================================================================
*   Ver     Date            Author          Modification
* ==================================================================================
*   1.0     2023.07.04      yj.kim    Create
* ==================================================================================
**/

public with sharing class Project_tr extends TriggerHandler{

    private List<Project__c> listNew { get; set; }
    private List<Project__c> listOld { get; set; }
    private Map<Id, Project__c> mapNew { get; set; }
    private Map<Id, Project__c> mapOld { get; set; }

    public Project_tr() {
        listNew = (List<Project__c>) Trigger.new;
        listOld = (List<Project__c>) Trigger.old;
        mapNew = (Map<Id, Project__c>) Trigger.newMap;
        mapOld = (Map<Id, Project__c>) Trigger.oldMap;
    }

    public override void beforeInsert() {
        updatePMEmail();
    }

    public override void afterInsert() {
        createBudget();
    }

    public override void beforeUpdate() {
        updatePMEmail();
        sendEmail();
    }

    public override void afterUpdate() { }

    public override void beforeDelete() { }

    public override void afterDelete() { }

    public void updatePMEmail(){
        Set<Id> setPmUserId = new Set<Id>();
        for (Project__c objProject : listNew) {
            setPmUserId.add(objProject.PM__c);
        }

        Map<Id, User> mapPmUser = new Map<Id, User>([SELECT Id, email FROM User WHERE Id IN :setPmUserId]);
        for (Project__c objProject : listNew) {
            String email = objProject.PM__c == null || mapPmUser.get(objProject.PM__c) == null ? null : mapPmUser.get(objProject.PM__c).Email;
            objProject.PMEmail__c = email;
        }
    }

    public void sendEmail(){
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();

        List<String> setEmail = new List<String>();
        String projectId = '';

        for (Project__c objProject : listNew) {
            if(objProject.Completed__c == true && mapOld.get(objProject.Id).Completed__c == false){
                setEmail.add(objProject.PMEmail__c);
                projectId = objProject.Id;
            }
        }

        System.debug('setEmail : ' + setEmail);
        if(!setEmail.isEmpty()){
            email.setToAddresses(setEmail);
            email.setSubject('[' + listNew[0].Name + '] 프로젝트 인력평가 안내');
            String body = '안녕하세요, <br/>';
            body += '[' + listNew[0].Name + '] 프로젝트 투입 전체 투입인원평가를 진행해 주시기 바랍니다. <br/><br/>';
            body += '아래 링크를 누르시면 해당 프로젝트 레코드로 이동합니다. <br/>';
            body += '화면에서 [투입인력평가서] 버튼을 누르신 후 평가를 진행해주시기 바랍니다.';
            body += 'https://daeunextier.lightning.force.com/lightning/r/Project__c/' + listNew[0].Id + '/view <br/><br/>';
            body += '감사합니다.';
            email.setHtmlBody(body);

            OrgWideEmailAddress[] owea = [SELECT Id FROM OrgWideEmailAddress WHERE Address = 'admin@daeunextier.com'];
            System.debug('owea : ' + owea);
            if ( owea.size() > 0 ) {
                email.setOrgWideEmailAddressId(owea.get(0).Id);
            }

            try{
                if(!Test.isRunningTest()) Messaging.sendEmail(new Messaging.SingleEmailMessage[] { email });
                System.debug('success');
            }catch(Exception e){
                System.debug('error');
            }
        }

    }

    public void createBudget(){
        list<Budget__c> listBudget = new List<Budget__c>();
        for (Project__c obj : listNew) {
            System.debug(obj);
            listBudget.add(new Budget__c(
                    Project__c = obj.Id,
                    BudgetType__c = '프로젝트',
                    Name = 'triggerName'
            ));
        }
        if (!listBudget.isEmpty()) {
            insert listBudget;
        }
    }

}