PA_Education/TestMenifest/force-app/main/default/objects/Budget__c/Budget__c.object-meta.xml
<CustomObject>
    <label>예산</label>
    <nameField>
        <label>예산이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Budget__c/fields/BudgetAmount__c.field-meta.xml
<CustomField>
    <fullName>BudgetAmount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>예산금액 (입력용)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Budget__c/fields/BudgetType__c.field-meta.xml
<CustomField>
    <fullName>BudgetType__c</fullName>
    <label>예산배정단위</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BudgetType</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Budget__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>BudgetProject</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Budget__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>연도</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
            <value>
                <fullName>2036</fullName>
            </value>
            <value>
                <fullName>2037</fullName>
            </value>
            <value>
                <fullName>2038</fullName>
            </value>
            <value>
                <fullName>2039</fullName>
            </value>
            <value>
                <fullName>2040</fullName>
            </value>
            <value>
                <fullName>2041</fullName>
            </value>
            <value>
                <fullName>2042</fullName>
            </value>
            <value>
                <fullName>2043</fullName>
            </value>
            <value>
                <fullName>2044</fullName>
            </value>
            <value>
                <fullName>2045</fullName>
            </value>
            <value>
                <fullName>2046</fullName>
            </value>
            <value>
                <fullName>2047</fullName>
            </value>
            <value>
                <fullName>2048</fullName>
            </value>
            <value>
                <fullName>2049</fullName>
            </value>
            <value>
                <fullName>2050</fullName>
            </value>
            <value>
                <fullName>2051</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense Application</label>
    <nameField>
        <displayFormat>EP-{YYYYMM}-{000000}</displayFormat>
        <label>경비신청 코드</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>예산</label>
    <referenceTo>Budget__c</referenceTo>
    <relationshipLabel>Expense Application</relationshipLabel>
    <relationshipName>Expense_Application</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/BudgetType__c.field-meta.xml
<CustomField>
    <fullName>BudgetType__c</fullName>
    <label>사용목적</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BudgetType</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Expense Application</relationshipLabel>
    <relationshipName>ExpenseApplication</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/UseYear__c.field-meta.xml
<CustomField>
    <fullName>UseYear__c</fullName>
    <defaultValue>TEXT( YEAR(  ADDMONTHS(TODAY(),-1)  ) )</defaultValue>
    <inlineHelpText>신청할 경비내역의 연도를 입력합니다.</inlineHelpText>
    <label>경비 사용 연도</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2013</fullName>
            </value>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
                <default>true</default>
                <label>2022</label>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/ExpenseDetail__c.object-meta.xml
<CustomObject>
    <label>Expense Detail</label>
    <nameField>
        <displayFormat>EPD-{000000}</displayFormat>
        <label>경비신청 상세 ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>경비신청금액</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Expense__c.field-meta.xml
<CustomField>
    <fullName>Expense__c</fullName>
    <label>경비신청 ID</label>
    <referenceTo>Expense__c</referenceTo>
    <relationshipName>ExpenseDetail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>프로젝트에 대한 기본정보를 관리하며, Deal Closing 이후 생성한다. 영업담당자가 계약 체결 후 기초 데이터를 작성하며, 프로젝트 진행 중에는 PM이 관리하고, 대금청구/지급 관련 정보는 회계에서 관리한다.</description>
    <label>프로젝트</label>
    <nameField>
        <label>프로젝트 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/fields/Salesforce_Industry__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Industry__c</fullName>
    <label>Salesforce 산업분류</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>자동차</fullName>
            </value>
            <value>
                <fullName>통신</fullName>
            </value>
            <value>
                <fullName>소비재</fullName>
            </value>
            <value>
                <fullName>교육</fullName>
            </value>
            <value>
                <fullName>에너지 및 유틸리티</fullName>
            </value>
            <value>
                <fullName>금융 서비스</fullName>
            </value>
            <value>
                <fullName>공공부문</fullName>
            </value>
            <value>
                <fullName>헬프케어 및 생명과학</fullName>
            </value>
            <value>
                <fullName>제조업</fullName>
            </value>
            <value>
                <fullName>미디어</fullName>
            </value>
            <value>
                <fullName>비영리</fullName>
            </value>
            <value>
                <fullName>리테일</fullName>
            </value>
            <value>
                <fullName>기술</fullName>
            </value>
            <value>
                <fullName>운송 및 호스피탈리티</fullName>
            </value>
            <value>
                <fullName>직접입력</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/fields/Salesforce_Product__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Product__c</fullName>
    <label>Salesforce 제품분류</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales Cloud</fullName>
            </value>
            <value>
                <fullName>Service Cloud</fullName>
            </value>
            <value>
                <fullName>Marketing Cloud</fullName>
            </value>
            <value>
                <fullName>Commerce Cloud</fullName>
            </value>
            <value>
                <fullName>Tableau</fullName>
            </value>
            <value>
                <fullName>MuleSoft</fullName>
            </value>
            <value>
                <fullName>Salesforce Platform</fullName>
            </value>
            <value>
                <fullName>Net Zero Cloud</fullName>
            </value>
            <value>
                <fullName>Nonprofit Cloud</fullName>
            </value>
            <value>
                <fullName>Experience Cloud</fullName>
            </value>
            <value>
                <fullName>직접입력</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/recordTypes/Project.recordType-meta.xml
<RecordType>
    <fullName>Project</fullName>
    <active>true</active>
    <description>프로젝트 사항 입력하는 Record Type</description>
    <label>프로젝트</label>
</RecordType>

PA_Education/TestMenifest/force-app/main/default/objects/ProjectBudget__c/ProjectBudget__c.object-meta.xml
<CustomObject>
    <label>프로젝트 비용 예산</label>
    <nameField>
        <label>프로젝트 비용 예산 신청명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/ProjectBudget__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>프로젝트</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>프로젝트 비용 예산</relationshipLabel>
    <relationshipName>ProjectBudget</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ProjectBudgetDetail__c/ProjectBudgetDetail__c.object-meta.xml
<CustomObject>
    <label>프로젝트 비용 예산 상세</label>
    <nameField>
        <displayFormat>P-EXP-{YY}{MM}-{000}</displayFormat>
        <label>프로젝트 예산</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/ProjectBudgetDetail__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <formula>UnitPrice__c  *  Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>단가 * 수량</inlineHelpText>
    <label>금액</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ProjectBudgetDetail__c/fields/BudgetType__c.field-meta.xml
<CustomField>
    <fullName>BudgetType__c</fullName>
    <label>예산구분</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ExpenseType</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/ExpenseApplicationTriggerHandler_Test.cls
/**
 * Created by JWJANG on 2023-10-04.
 */
@IsTest
private class ExpenseApplicationTriggerHandler_Test {
    @TestSetup
    static void doTestSetup() {
        List<Project__c> listProject = new List<Project__c>();
        listProject.add(new Project__c(Name = '본사공통', Salesforce_Product__c = 'Sales Cloud', Salesforce_Industry__c = '자동차'));
        listProject.add(new Project__c(Name = '마케팅', Salesforce_Product__c = 'Sales Cloud', Salesforce_Industry__c = '자동차'));
        listProject.add(new Project__c(Name = 'TEST Project', Salesforce_Product__c = 'Sales Cloud', Salesforce_Industry__c = '자동차'));
//        listProject.add(new Project__c(Name = 'TEST Project2', Salesforce_Product__c = 'Sales Cloud', Salesforce_Industry__c = '자동차'));
        insert listProject;

        Project__c objProject = [SELECT Id FROM Project__c WHERE Name = 'TEST Project' LIMIT 1];

        Budget__c obj = new Budget__c(
                Name = 'test',
                Year__c = string.valueOf(Date.today().year() -1),
                BudgetAmount__c = 10000000,
                BudgetType__c = '본사행정'
        );
        insert obj;

        Expense__c objExpense           = new Expense__c();
        objExpense.UseYear__c           = String.valueOf(Date.today().year());
        objExpense.UseMonth__c          = String.valueOf(Date.today().month());
        objExpense.ApprovalStatus__c    = 'Approved';
        objExpense.BudgetType__c        = '본사행정';
        objExpense.PaymentMethod__c     = '법인카드';
        insert objExpense;

        ExpenseDetail__c objExpenseDetail   = new ExpenseDetail__c();
        objExpenseDetail.Project_Name__c    = objProject.Id;
        objExpenseDetail.Expense__c         = objExpense.Id;
        objExpenseDetail.Category1__c       = '프로젝트';
        objExpenseDetail.Category2__c       = '식비';
        objExpenseDetail.Amount__c          = 1000;
        objExpenseDetail.Date__c            = Date.today();
        insert objExpenseDetail;

        Expense__c objExpense2           = new Expense__c();
        objExpense2.Project__c          = objProject.Id;
        objExpense2.UseYear__c           = String.valueOf(Date.today().year());
        objExpense2.UseMonth__c          = String.valueOf(Date.today().month());
        objExpense2.ApprovalStatus__c    = 'Approved';
        objExpense2.BudgetType__c        = '프로젝트';
        objExpense2.PaymentMethod__c     = '법인카드';
        insert objExpense2;

        ExpenseDetail__c objExpenseDetail2   = new ExpenseDetail__c();
        objExpenseDetail2.Expense__c         = objExpense2.Id;
        objExpenseDetail2.Category2__c       = '식비';
        objExpenseDetail2.Amount__c          = 1000;
        objExpenseDetail2.Date__c            = Date.today();
        insert objExpenseDetail2;
//
//        Project__c objProject2 = [SELECT Id FROM Project__c WHERE Name = 'TEST Project2' LIMIT 1];
//        Contract__c objContract = new Contract__c(
//                Name = 'Test Contract',
//                IsContract__c = true
//        );
//        insert objContract;
////
////        objProject2.Contract__c = objContract.Id;
////        update objProject2;
////
////        ProjectBudget__c objpBudget = new ProjectBudget__c(
////                Project__c = objProject2.Id,
////                Name = 'TestBudget'
////        );
////        insert objpBudget;
////
////        ProjectBudgetDetail__c objPBD = new ProjectBudgetDetail__c(
////                Category2__c = '식비',
////                Quantity__c = 1,
////                UnitPrice__c = 100,
////                ProjectBudget__c = objpBudget.Id
////        );
////        insert objPBD;
////
////        Expense__c objExpense3           = new Expense__c();
////        objExpense3.Project__c          = objProject2.Id;
////        objExpense3.UseYear__c           = String.valueOf(Date.today().year());
////        objExpense3.UseMonth__c          = String.valueOf(Date.today().month());
////        objExpense3.ApprovalStatus__c    = 'Approved';
////        objExpense3.BudgetType__c        = '프로젝트';
////        objExpense3.PaymentMethod__c     = '법인카드';
////        insert objExpense3;
////
////        ExpenseDetail__c objExpenseDetail3   = new ExpenseDetail__c();
////        objExpenseDetail3.Expense__c         = objExpense3.Id;
////        objExpenseDetail3.Category2__c       = '식비';
////        objExpenseDetail3.Amount__c          = 1000;
////        objExpenseDetail3.Date__c            = Date.today();
////        insert objExpenseDetail3;


    }

    @IsTest
    static void doTest() {
        List<Expense__c> listExpense = [SELECT Id, ApprovalStatus__c FROM Expense__c];
        System.debug(listExpense);
        for (Expense__c obj: listExpense){
            obj.ApprovalStatus__c = '승인완료';
        }

        Database.update(listExpense, false);
//        listExpense.get(0).ApprovalStatus__c = '승인완료';
//        update listExpense;
    }
}