PA_Education/TestMenifest/force-app/main/default/objects/Budget__c/Budget__c.object-meta.xml
<CustomObject>
    <label>예산</label>
    <nameField>
        <label>예산이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Budget__c/fields/BudgetType__c.field-meta.xml
<CustomField>
    <fullName>BudgetType__c</fullName>
    <label>예산배정단위</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BudgetType</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Budget__c/fields/fm_RemainingAmount__c.field-meta.xml
<CustomField>
    <fullName>fm_RemainingAmount__c</fullName>
    <formula>fm_BudgetAmount__c - UsedAmount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>예산잔여금액</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Budget__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>BudgetProject</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Budget__c/fields/UsedAmount__c.field-meta.xml
<CustomField>
    <fullName>UsedAmount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>해당 예산으로 신청된 경비 중 승인된 경비금액의 합 표시</description>
    <inlineHelpText>해당 예산으로 신청된 경비 중 승인된 경비금액의 합이 표시됩니다.</inlineHelpText>
    <label>예산사용금액</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Contract</label>
    <nameField>
        <label>계약명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Contract__c/fields/IsContract__c.field-meta.xml
<CustomField>
    <fullName>IsContract__c</fullName>
    <defaultValue>false</defaultValue>
    <label>계약체결</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense Application</label>
    <nameField>
        <displayFormat>EP-{YYYYMM}-{000000}</displayFormat>
        <label>경비신청 코드</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>승인상태</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Writing</fullName>
                <default>true</default>
                <label>작성</label>
            </value>
            <value>
                <fullName>Consider</fullName>
                <label>승인검토중</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>승인완료</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <label>승인거부</label>
            </value>
            <value>
                <fullName>Recall</fullName>
                <label>회수됨</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>예산</label>
    <referenceTo>Budget__c</referenceTo>
    <relationshipLabel>Expense Application</relationshipLabel>
    <relationshipName>Expense_Application</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/BudgetType__c.field-meta.xml
<CustomField>
    <fullName>BudgetType__c</fullName>
    <label>사용목적</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BudgetType</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Expense Application</relationshipLabel>
    <relationshipName>ExpenseApplication</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <label>상신금액합계</label>
    <summarizedField>ExpenseDetail__c.Amount__c</summarizedField>
    <summaryForeignKey>ExpenseDetail__c.Expense__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/ExpenseDetail__c.object-meta.xml
<CustomObject>
    <label>Expense Detail</label>
    <nameField>
        <displayFormat>EPD-{000000}</displayFormat>
        <label>경비신청 상세 ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>경비신청금액</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Expense__c.field-meta.xml
<CustomField>
    <fullName>Expense__c</fullName>
    <label>경비신청 ID</label>
    <referenceTo>Expense__c</referenceTo>
    <relationshipName>ExpenseDetail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/fm_approvalStatus__c.field-meta.xml
<CustomField>
    <fullName>fm_approvalStatus__c</fullName>
    <formula>TEXT(Expense__r.ApprovalStatus__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>승인상태</label>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>2024.1. 기준 사용 X (Expense__c에서 프로젝트 입력)</description>
    <inlineHelpText>내부 경비 처리는 
&apos;본사공통&apos; 프로젝트를 선택하시고 
프로젝트 관련 비용은 해당 프로젝트를 선택하세요.</inlineHelpText>
    <label>프로젝트 (사용X)</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Expense Detail</relationshipLabel>
    <relationshipName>ExpenseDetail_Project</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/PerformProject__c.object-meta.xml
<CustomObject>
    <label>프로젝트 수행팀</label>
    <nameField>
        <displayFormat>PJ-{0000}</displayFormat>
        <label>Seq</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트 명</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>프로젝트 수행팀</relationshipLabel>
    <relationshipName>Project</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>프로젝트에 대한 기본정보를 관리하며, Deal Closing 이후 생성한다. 영업담당자가 계약 체결 후 기초 데이터를 작성하며, 프로젝트 진행 중에는 PM이 관리하고, 대금청구/지급 관련 정보는 회계에서 관리한다.</description>
    <label>프로젝트</label>
    <nameField>
        <label>프로젝트 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>계약</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>프로젝트</relationshipLabel>
    <relationshipName>Project</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/fields/fm_RemainingExpense__c.field-meta.xml
<CustomField>
    <fullName>fm_RemainingExpense__c</fullName>
    <formula>ru_Budget__c - TotalExpense__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>잔여 예산</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/fields/TotalExpense__c.field-meta.xml
<CustomField>
    <fullName>TotalExpense__c</fullName>
    <defaultValue>0</defaultValue>
    <description>(구) 0. 전체비용</description>
    <label>경비신청금액</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/recordTypes/Project.recordType-meta.xml
<RecordType>
    <fullName>Project</fullName>
    <active>true</active>
    <description>프로젝트 사항 입력하는 Record Type</description>
    <label>프로젝트</label>
</RecordType>

PA_Education/TestMenifest/force-app/main/default/classes/ExpenseApplicationTriggerHandler.cls
/**
 * Created by JWJANG on 2023-10-04.
 */
public with sharing class ExpenseApplicationTriggerHandler extends TriggerHandler {
    private static List<Expense__c> listNew {get; set;}
    private static List<Expense__c> listOld {get; set;}
    private static Map<Id, Expense__c> mapNew {get; set;}
    private static Map<Id, Expense__c> mapOld {get; set;}

    public ExpenseApplicationTriggerHandler() {
        listNew = (List<Expense__c>) Trigger.new;
        listOld = (List<Expense__c>) Trigger.old;
        mapNew = (Map<Id, Expense__c>) Trigger.newMap;
        mapOld = (Map<Id, Expense__c>) Trigger.oldMap;
    }

    public override void beforeInsert() { }

    public override void beforeUpdate() { }

    public override void afterInsert() { }

    public override void afterUpdate() {
//        updateTotalExpense();
        updateBudgetUsedAmount();
    }

    /**
     * Expense Application (Expense__c) 변경 시, 프로젝트 별 경비신청금액 업데이트
     */
//    private void updateTotalExpense() {
//        System.debug('[updateTotalExpense] Start !!!');
//        try {
//            // 대상 프로젝트 조회
//            List<AggregateResult> listEDToProjectId = [
//                    SELECT Expense__r.Project__c
//                    FROM ExpenseDetail__c
//                    WHERE Expense__c IN :mapNew.keySet()
//                    AND Expense__r.BudgetType__c = '프로젝트'
//                    GROUP BY Expense__r.Project__c
//            ];
//
//            if(!listEDToProjectId.isEmpty()) {
//                Set<String> setProjectId = new Set<String>();
//                for(AggregateResult objExpenseDetail : listEDToProjectId) {
//                    setProjectId.add(String.valueOf(objExpenseDetail.get('Expense__r.Project__c')));
//                }
//                System.debug(String.format('Target Project ID : [{0}] {1}', new List<Object>{ setProjectId.size(), setProjectId }));
//
//                // 프로젝트 경비신청 금액 합산
//                List<ExpenseDetail__c> listExpenseDetail = [
//                        SELECT Id, Amount__c, fm_approvalStatus__c, Project_Name__c, Expense__r.Project__c
//                        FROM ExpenseDetail__c
//                        WHERE Expense__r.Project__c IN :setProjectId AND fm_approvalStatus__c IN ('Consider', 'Approved')
//                ];
//
//                Map<String, Project__c> mapProject = new Map<String, Project__c>();
//                for(ExpenseDetail__c objExpenseDetail : listExpenseDetail) {
//                    Project__c objProject = mapProject.get(objExpenseDetail.Expense__r.Project__c);
//                    if(objProject == null) {
//                        objProject = new Project__c(Id = objExpenseDetail.Expense__r.Project__c, TotalExpense__c = 0);
//                    }
//
//                    objProject.TotalExpense__c += objExpenseDetail.Amount__c;
//                    mapProject.put(objProject.Id, objProject);
//                }
//                System.debug(String.format('Target Project : [{0}] {1}', new List<Object>{ mapProject.size(), mapProject }));
//
//                if(!mapProject.isEmpty()) {
//                    update mapProject.values();
//                }
//            }
//        } catch (Exception e) {
//            System.debug(String.format('[{0}] {1}', new List<Object>{ e.getLineNumber(), e.getMessage() }));
//        }
//
//        System.debug('[updateTotalExpense] End !!!');
//    }

    /**
    * Expense Application (Expense__c) 승인 시, 예산, 프로젝트 오브젝트의 사용금액 내역에 추가
    */
    private void updateBudgetUsedAmount(){
        Map<Id,Decimal> mapBudgetIdToExpense = new Map<Id, Decimal>();
        Map<Id,Id> mapPrjToBudget = new Map<Id, Id>();

        for (Expense__c obj : listNew){
            if (obj.ApprovalStatus__c != mapOld.get(obj.Id).ApprovalStatus__c && new list<String>{'Approved', '승인완료'}.contains(obj.ApprovalStatus__c)) {
                if (mapBudgetIdToExpense.get(obj.Budget__c) == null) {
                    mapBudgetIdToExpense.put(obj.Budget__c, obj.TotalAmount__c);
                }else{
                    mapBudgetIdToExpense.put(obj.Budget__c, mapBudgetIdToExpense.get(obj.Budget__c) + obj.TotalAmount__c);
                }

                if (obj.BudgetType__c == '프로젝트' && obj.Project__c != null) {
                    mapPrjToBudget.put(obj.Project__c, obj.Budget__c);
                }
            }
        }
        if (!mapBudgetIdToExpense.isEmpty()) {
            set<Id> setOverBudget = new Set<Id>();

            //Budget__c에 사용한 비용 가감
            List<Budget__c> listBudget = new List<Budget__c>([
                    SELECT  Id, UsedAmount__c, fm_RemainingAmount__c, Project__r.Contract__c, Project__r.Contract__r.IsContract__c
                    FROM    Budget__c
                    WHERE   Id IN : mapBudgetIdToExpense.keySet()
            ]);

            System.debug('listBudget :: ' + listBudget);
            if (!listBudget.isEmpty()) {
                for (Budget__c obj : listBudget){
                     //예산초과 체크
                    if (obj.fm_RemainingAmount__c < mapBudgetIdToExpense.get(obj.Id)) {
                        //프로젝트가 아닌 경우 OR 프로젝트가 인데 계약필드가 있고 계약이 성사된 경우에만 예산초과 validation 적용

                        if (!mapPrjToBudget.values().contains(obj.Id)
                                || (mapPrjToBudget.values().contains(obj.Id) && obj.Project__r.Contract__c != null && obj.Project__r.Contract__r.IsContract__c)) {
                            setOverBudget.add(obj.Id);
                            break;
                        }
                    }
                        obj.UsedAmount__c = obj.UsedAmount__c == null?  mapBudgetIdToExpense.get(obj.Id) : obj.UsedAmount__c + mapBudgetIdToExpense.get(obj.Id);
                }
                update listBudget;
            }

            System.debug('setOverBudget :: ' + setOverBudget);

            //Project__c에 사용한 비용 가감
            List<Project__c> listPrj = new List<Project__c>([
                    SELECT  Id, TotalExpense__c, fm_RemainingExpense__c
                    FROM    Project__c
                    WHERE   Id IN : mapPrjToBudget.keySet()
            ]);
            if (!listPrj.isEmpty()) {
                for (Project__c obj : listPrj){
                    if (!setOverBudget.contains(mapPrjToBudget.get(obj.Id))) {
                        obj.TotalExpense__c = obj.TotalExpense__c == null? mapBudgetIdToExpense.get(mapPrjToBudget.get(obj.Id)) : obj.TotalExpense__c + mapBudgetIdToExpense.get(mapPrjToBudget.get(obj.Id));
                    }

                }
                update listPrj;
            }

            for (Expense__c obj : listNew){
                if (setOverBudget.contains(obj.Budget__c)) {
                    obj.addError('신청금액이 예산을 초과합니다.');
                }
            }

        }
    }
}