PA_Education/TestMenifest/force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>잠재고객</label>
    <nameField>
        <label>이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Lead__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>회사명</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Lead__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>이메일</label>
    <type>Email</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Lead__c/fields/LeadSource__c.field-meta.xml
<CustomField>
    <fullName>LeadSource__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>웹</fullName>
                <default>true</default>
                <label>Web문의</label>
            </value>
            <value>
                <fullName>Cold Call</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
                <label>고객추천</label>
            </value>
            <value>
                <fullName>직접요청</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
                <label>SFDC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Lead__c/fields/PersonalInformationUseAgreement__c.field-meta.xml
<CustomField>
    <fullName>PersonalInformationUseAgreement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>개인정보 수집 및 활용 동의</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Lead__c/fields/PersonalInformationUseAgreementDate__c.field-meta.xml
<CustomField>
    <fullName>PersonalInformationUseAgreementDate__c</fullName>
    <label>개인정보 수집 및 활용 동의 변경일</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Lead__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>연락처</label>
    <type>Phone</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Lead__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>솔루션 문의</fullName>
            </value>
            <value>
                <fullName>컨설팅 문의</fullName>
            </value>
            <value>
                <fullName>제휴 문의</fullName>
            </value>
            <value>
                <fullName>유지보수, 하자보수문의</fullName>
            </value>
            <value>
                <fullName>기타 문의</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Lead__c/fields/WebMessage__c.field-meta.xml
<CustomField>
    <fullName>WebMessage__c</fullName>
    <label>문의 내용</label>
    <length>130000</length>
    <type>Html</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Lead__c/fields/WebSubject__c.field-meta.xml
<CustomField>
    <fullName>WebSubject__c</fullName>
    <label>문의 제목</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/RenewalHPContactFormController.cls
/**
 * ==================================================================================
 * File Name         : RenewalHPContactFormContrller
 * Author            : Changjoo.Sohn
 * Group             : Daeu Nextier
 * Description       : Any questions of Renewal Homepage Page
 * Modification Logs
 * ==================================================================================
 *   Ver     Date          Author          Modification
 * ==================================================================================
 *   1.0   2022-01-27     Changjoo.Sohn   Initial Version
**/
public without sharing class RenewalHPContactFormController {
    @AuraEnabled
    public static List<Map<String, String>> getPickListValues(String objectType, String selectedField) {
        List<Map<String, String>> pickListValuesList = new List<Map<String, String>>();
        Schema.SObjectType convertToObj = Schema.getGlobalDescribe().get(objectType);
        Schema.DescribeSObjectResult res = convertToObj.getDescribe();
        Schema.DescribeFieldResult fieldResult = res.fields.getMap().get(selectedField).getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for(Schema.PicklistEntry pickListVal : ple) {
            if(pickListVal.getValue() =='None') continue;

            pickListValuesList.add(new Map<String, String>{
                    'label' => pickListVal.getLabel(),
                    'value' => pickListVal.getValue()
            });
        }
        return pickListValuesList;
    }

    @AuraEnabled
    public static String doSave(Map<String, Object> paramMap){
        System.debug('paramMap: ' + paramMap);
        String strName = String.valueOf(paramMap.get('Name'));
        String strCompany = String.valueOf(paramMap.get('Company'));
        String strMobile = String.valueOf(paramMap.get('Mobile'));
        String strEmail = String.valueOf(paramMap.get('Email'));
        String strType = String.valueOf(paramMap.get('LeadType'));
        String strSubject = String.valueOf(paramMap.get('Subject'));
        String strDescription = String.valueOf(paramMap.get('Description'));

        Lead__c objLead = new Lead__c();
        objLead.Name = strName;
        objLead.Company__c = strCompany;
        objLead.Phone__c = strMobile;
        objLead.Email__c = strEmail;
        objLead.LeadSource__c = '웹';
        objLead.Type__c = strType;
        objLead.WebSubject__c = strSubject;
        objLead.WebMessage__c = strDescription;
        objLead.PersonalInformationUseAgreement__c = true;
        objLead.PersonalInformationUseAgreementDate__c = Date.today();
        insert objLead;

        return '0';
    }
}