PA_Education/TestMenifest/force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>잠재고객</label>
    <nameField>
        <label>이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Lead__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>회사명</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Lead__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>이메일</label>
    <type>Email</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Lead__c/fields/InterestProduct__c.field-meta.xml
<CustomField>
    <fullName>InterestProduct__c</fullName>
    <label>흥미 제품군</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>InterestProduct</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Lead__c/fields/LeadSource__c.field-meta.xml
<CustomField>
    <fullName>LeadSource__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>웹</fullName>
                <default>true</default>
                <label>Web문의</label>
            </value>
            <value>
                <fullName>Cold Call</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
                <label>고객추천</label>
            </value>
            <value>
                <fullName>직접요청</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
                <label>SFDC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Lead__c/fields/WebMessage__c.field-meta.xml
<CustomField>
    <fullName>WebMessage__c</fullName>
    <label>문의 내용</label>
    <length>130000</length>
    <type>Html</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Lead__c/fields/WebSubject__c.field-meta.xml
<CustomField>
    <fullName>WebSubject__c</fullName>
    <label>문의 제목</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/TestSupport.cls
/**
 * Object       : TestSupport.cls
 * Function     : Lead로 Insert
 * Author       : Yohan.Kang.
 * Date         : 2013.10.7
 * Description  : 
 */
public without sharing class TestSupport {
    public String username {get; set;}
    public String Company {get; set;}
    public String email {get; set;}
    public string subject{get; set;}
    public string message{get; set;}
    public string InterestProduct{get; set;}
    public string LeadSource{get; set;}
    
    public boolean IsErrorIsCompany{get; set;}
    public boolean IsErrorIsName{get; set;}
    public boolean IsErrorIsEmail{get; set;}
    public boolean IsErrorValidEmail{get; set;}
    
    public boolean IsRegistedOk{get; set;}
    
    public TestSupport(){
        IsErrorIsName = false;
        IsErrorIsEmail = false;
        IsErrorValidEmail = false;
        IsRegistedOk = false;
    }
    
    public pageReference registerLead(){
        IsErrorIsName = false;
        IsErrorIsEmail = false;
        IsErrorValidEmail = false;
        IsErrorIsCompany = false;
        
        if(Company==null || Company==''){
            IsErrorIsCompany = true;
        }
        
        if(username==null || username==''){
            IsErrorIsName = true;
        }
        
        if(email==null || email==''){
            IsErrorIsEmail = true;
        }
        
        if(!IsErrorIsEmail && !validateEmail(email)){
            IsErrorValidEmail = true;
        }
        
        if(IsErrorIsCompany || IsErrorIsName || IsErrorIsEmail || IsErrorValidEmail){
            return null;
        }
       
        Lead__c LD = new Lead__c();
        //Lead LD = new Lead();
        Ld.Name = username;
        Ld.Company__c = Company;
        Ld.LeadSource__c = '웹';
        LD.Email__c = email;
        LD.InterestProduct__c = InterestProduct;
        LD.WebSubject__c = subject;
        LD.WebMessage__c = message;
        insert LD;
        
        IsRegistedOk = true;
        return null;
    }
    
    private Boolean validateEmail(String email) {
        Boolean res = true;
        
        String emailRegex = '^[a-zA-Z0-9._|\\\\%#~`=?&/$^*!}{+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,4}$'; // source: http://www.regular-expressions.info/email.html
        Pattern MyPattern = Pattern.compile(emailRegex);
        Matcher MyMatcher = MyPattern.matcher(email);
        
        if (!MyMatcher.matches()) 
            res = false;
        return res; 
    }
    
}