PA_Education/TestMenifest/force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>잠재고객</label>
    <nameField>
        <label>이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Lead__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>회사명</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Lead__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>이메일</label>
    <type>Email</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Lead__c/fields/InterestProduct__c.field-meta.xml
<CustomField>
    <fullName>InterestProduct__c</fullName>
    <label>흥미 제품군</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>InterestProduct</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Lead__c/fields/LeadSource__c.field-meta.xml
<CustomField>
    <fullName>LeadSource__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>웹</fullName>
                <default>true</default>
                <label>Web문의</label>
            </value>
            <value>
                <fullName>Cold Call</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
                <label>고객추천</label>
            </value>
            <value>
                <fullName>직접요청</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
                <label>SFDC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Lead__c/fields/WebMessage__c.field-meta.xml
<CustomField>
    <fullName>WebMessage__c</fullName>
    <label>문의 내용</label>
    <length>130000</length>
    <type>Html</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Lead__c/fields/WebSubject__c.field-meta.xml
<CustomField>
    <fullName>WebSubject__c</fullName>
    <label>문의 제목</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/TestSupportTester.cls
@isTest
private class TestSupportTester{
    static testMethod void myUnitTest() {
        test.startTest();
        
        TestSupport con = new TestSupport ();
        
        con.registerLead();
        con.username = 'name';
        con.email = 'sj.kim@daeunextier.com';
        con.subject = 'test';
        con.message = 'test2';
        con.interestProduct = 'Service Cloud';
        con.leadsource = '웹';
        con.company = 'test';

        con.registerLead();



		Lead__c LD = new Lead__c();
        //Lead LD = new Lead();
        Ld.Name = con.username;
        Ld.Company__c = con.Company;
        Ld.LeadSource__c = '웹';
        LD.Email__c = con.email;
        LD.InterestProduct__c = con.InterestProduct;
        LD.WebSubject__c = con.subject;
        LD.WebMessage__c = con.message;
        insert LD;



        
        
        test.stopTest();
    }
}