PA_Education/TestMenifest/force-app/main/default/objects/DailyTraining__c/DailyTraining__c.object-meta.xml
<CustomObject>
    <description>신입사원의 일일 업무 보고 개체</description>
    <label>업무일지</label>
    <nameField>
        <displayFormat>{YY}/{MM}-{000}</displayFormat>
        <label>업무일지</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/DailyTraining__c/fields/Dt_Date__c.field-meta.xml
<CustomField>
    <fullName>Dt_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>일일보고 일자</description>
    <label>일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/DailyTraining__c/fields/Dt_EduName__c.field-meta.xml
<CustomField>
    <fullName>Dt_EduName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>진행중인 교육 프로그램</description>
    <label>교육 프로그램</label>
    <referenceTo>EduCurriculum__c</referenceTo>
    <relationshipLabel>업무일지</relationshipLabel>
    <relationshipName>Dt_EduName</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/DailyTraining__c/fields/Dt_EmployeeName__c.field-meta.xml
<CustomField>
    <fullName>Dt_EmployeeName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>업무일지를 작성하는 사원의 이름</description>
    <label>사원</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>업무일지</relationshipLabel>
    <relationshipName>Dt_EmployeeName</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/DailyTraining__c/fields/Dt_Mentor__c.field-meta.xml
<CustomField>
    <fullName>Dt_Mentor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>담당멘토</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>업무일지 (담당멘토)</relationshipLabel>
    <relationshipName>Dt_Mentor</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/DailyTraining__c/fields/Dt_UserName__c.field-meta.xml
<CustomField>
    <fullName>Dt_UserName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>사원 명</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Dt_UserName</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EduCurriculum__c/EduCurriculum__c.object-meta.xml
<CustomObject>
    <description>신입대상 교육 프로그램 관리 개체</description>
    <label>교육 프로그램</label>
    <nameField>
        <label>프로그램 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/EduCurriculum__c/fields/Edu_Active__c.field-meta.xml
<CustomField>
    <fullName>Edu_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>현재 활성화 되어 있는 교육 프로그램</description>
    <label>활성화</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EduCurriculum__c/fields/Edu_Category__c.field-meta.xml
<CustomField>
    <fullName>Edu_Category__c</fullName>
    <description>프로그램 수강 대상자의 직무를 구분하기 위한 필드</description>
    <label>관련분야</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Edu_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Dev.</fullName>
            </value>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EduCurriculum__c/fields/Edu_Type__c.field-meta.xml
<CustomField>
    <fullName>Edu_Type__c</fullName>
    <description>교육 프로그램의 종류를 구분 짓기 위한 필드</description>
    <label>구분</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trailmix</fullName>
            </value>
            <value>
                <fullName>Superbadges</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Off-Line</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/MainRole__c.field-meta.xml
<CustomField>
    <fullName>MainRole__c</fullName>
    <label>직무</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Management</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ListViewButton/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/MentorUser__c.field-meta.xml
<CustomField>
    <fullName>MentorUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>담당멘토 명</label>
    <referenceTo>User</referenceTo>
    <relationshipName>MentorUser</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>직급</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>총괄사장</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>대표이사</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>센터장</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>감사</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>부사장</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>전무</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>상무</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>수석</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>이사</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>부장</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>책임</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>차장</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>과장</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>대리</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>선임</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>선임(수습)</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>사원</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>사원(수습)</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>인턴</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>사원 Object를 User Object간 Relationship 생성</inlineHelpText>
    <label>사용자 명</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/RemainEducationController_test.cls
@isTest
public class RemainEducationController_test {
    
    public static User userMentor;
    public static User userNew;
    // Test Setup method to create test data
    @testSetup
    static void setupData() {
        User userThis=[
            SELECT Id, Name, Profile.Name, UserRole.Name
            FROM User
            WHERE Id = :UserInfo.getUserId()
        ];

       
        
        System.runAs(userThis){
            // Create a test user
            Profile p = [SELECT Id FROM Profile WHERE Name='Standard User' LIMIT 1];
            UserRole r = [SELECT Id FROM UserRole WHERE Name='Platform Member'];

            User userMentor=new User(
                alias = 'mentor', email='testMentor_121124@test.com', 
                emailencodingkey='UTF-8', lastname='testMentor_121124', 
                languagelocalekey='en_US', 
                localesidkey='en_US', profileid = p.Id, userroleid = r.Id,
                timezonesidkey='America/Los_Angeles', 
                username='test12@daeunextier.com');
                
            insert userMentor;
            
            User userNew=new User(
                alias = 'new', email='testMentee_121124@test.com', 
                emailencodingkey='UTF-8', lastname='testMentee_121124', 
                languagelocalekey='en_US', 
                localesidkey='en_US', profileid = p.Id, userroleid = r.Id,
                timezonesidkey='America/Los_Angeles', 
                username='test21@daeunextier.com');

            insert userNew;

            //employee 생성
            Employee__c empMentor = new Employee__c(
                Name = 'Test_Emp121124_1',
                User__c=userMentor.Id,
                OwnerId = userMentor.Id,
                MainRole__c = 'Developer',
                Position__c = '8'
            );
            insert empMentor;

            Employee__c empNew=new Employee__c(
                Name = 'Test_Emp121124_2',
                User__c=userNew.Id,
                OwnerId = userNew.Id,
                MainRole__c = 'Developer',
                Position__c = '13',
                MentorUser__c=userMentor.Id
            );
            insert empNew;

            //교육 프로그램 생성
            EduCurriculum__c curriculum1 = new EduCurriculum__c(
                Name = 'Curriculum 1',
                Edu_Type__c='Certification',
                Edu_Category__c = 'Dev.',
                Edu_Active__c = true
                );
            EduCurriculum__c curriculum2 = new EduCurriculum__c(
                Name = 'Curriculum 2',
                Edu_Type__c='Off-Line',
                Edu_Category__c = 'ALL',
                Edu_Active__c = true
                );
            EduCurriculum__c curriculum3 = new EduCurriculum__c(
                Name = 'Curriculum 3',
                Edu_Type__c='Off-Line',
                Edu_Category__c = 'Admin',
                Edu_Active__c = true
                );
            insert new List<EduCurriculum__c> { curriculum1, curriculum2,curriculum3 };
                
            //업무일지 생성
            DailyTraining__c training = new DailyTraining__c(
                Dt_UserName__c = userNew.Id,
                Dt_EduName__c = curriculum1.Id,
                Dt_Mentor__c=empMentor.Id,
                Dt_EmployeeName__c=empNew.Id,
                Dt_Date__c=System.today()
                );
            insert training;
        }
    }
        
    
    @isTest
    static void testGetUserRoles() {
        User testUser=[
            SELECT Id
            FROM User
            WHERE Alias = 'new'
        ];
        
        System.runAs(testUser){
            Test.startTest();
            Map<String,Boolean> mapRole=RemainEducationController.getUserRoles();
            Test.stopTest();
        }
    }

    @isTest
    static void testGetAllEmployeeRemain() {
        Test.startTest();
        
        List<Map<String, Object>> remainEducation = RemainEducationController.getAllEmployeeRemain();
        
        Test.stopTest();
    }

    @isTest
    static void testGetAllEmployeeInProgress() {
        Test.startTest();
        
        List<Map<String, Object>> inProgress = RemainEducationController.getAllEmployeeInProgress();
        
        Test.stopTest();
    }

    @isTest
    static void testGetName() {

        User testUser=[
            SELECT Id
            FROM User
            WHERE Alias = 'new'
        ];

        System.runAs(testUser){
            Test.startTest();
        
            String name = RemainEducationController.getName();
            
            Test.stopTest();
        }
    }   

    @isTest
    static void testGetAllMenteeRemain(){
        User testUser=[
            SELECT Id
            FROM User
            WHERE Alias = 'mentor'
        ];

        System.runAs(testUser){
            Test.startTest();
            
            List<Map<String, Object>> menteeList = RemainEducationController.getAllMenteeRemain();
            
            Test.stopTest();
        }
    }

    @isTest
    static void testGetAllMenteeInProgress(){
        User testUser=[
            SELECT Id
            FROM User
            WHERE Alias = 'mentor'
        ];

        System.runAs(testUser){
            Test.startTest();
            
            List<Map<String, Object>> menteeList = RemainEducationController.getAllMenteeInProgress();
            
            Test.stopTest();
        }
    }
    @isTest
    static void testGetRemainEducation() {

        User testUser=[
            SELECT Id
            FROM User
            WHERE Alias = 'new'
        ];

        System.runAs(testUser){
            Test.startTest();
        
            List<Map<String, Object>> remainEducation = RemainEducationController.getRemainEducation();
            Test.stopTest();
        }    
    }

    @isTest
    static void testGetInProgressEducation() {

        User testUser=[
            SELECT Id
            FROM User
            WHERE Alias = 'new'
        ];

        System.runAs(testUser){
            Test.startTest();
        
            List<Map<String, Object>> inProgressEducation = RemainEducationController.getInProgressEducation();
            
            Test.stopTest();
        }
    }

    @isTest
    static void testGetRemainEducation_emp() {

        User testUser=[
            SELECT Id
            FROM User
            WHERE Alias = 'new'
        ];

        Employee__c objEmp=[
            SELECT Id, OwnerId
            FROM Employee__c
            WHERE Name = 'Test_Emp121124_2'
        ];

        System.runAs(testUser){
            Test.startTest();
        
            List<Map<String, Object>> remainEducation = RemainEducationController.getRemainEducation(objEmp);
            Test.stopTest();
        }    
    }

    @isTest
    static void testGetInProgressEducation_emp() {

        User testUser=[
            SELECT Id
            FROM User
            WHERE Alias = 'new'
        ];

        Employee__c objEmp=[
            SELECT Id, OwnerId
            FROM Employee__c
            WHERE Name = 'Test_Emp121124_2'
        ];

        System.runAs(testUser){
            Test.startTest();
        
            List<Map<String, Object>> inProgressEducation = RemainEducationController.getInProgressEducation(objEmp);
            
            Test.stopTest();
        }
    }
}