PA_Education/TestMenifest/force-app/main/default/objects/UrgentNotice__c/UrgentNotice__c.object-meta.xml
<CustomObject>
    <description>긴급 공지 용도 Object</description>
    <label>Urgent Notice</label>
    <nameField>
        <displayFormat>긴급 공지-{0000}</displayFormat>
        <label>긴급 공지 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/UrgentNotice__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>긴급공지 내용</description>
    <label>내용</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/UrgentNotice__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>Front로 공지가 노출 종료되는 날짜</description>
    <label>공지 종료일</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/UrgentNotice__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>Front로 노출되는 공지의 시작일</description>
    <label>공지 시작일</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/UrgentNotice__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>주제</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/RenewalHPNotice_Test.cls
/************************************************************************************
 * File Name   : RenewalHPNotice_Test.cls
 * Author      : SungJu.Kang
 * Date        : 2022. 01. 03
 * Target      : RenewalHPNotice.cls
 * Description : RenewalHPNotice.cls Test Class
 * Modification Log
 * ===================================================================================
 * Ver      Date            Author              Modification
 * ===================================================================================
   1.0      2022. 01. 13   SungJu.Kang            Create
*************************************************************************************/

@IsTest
private class RenewalHPNotice_Test {
    @IsTest
    static void itShould() {
        Test.startTest();
        UrgentNotice__c objUrgentNotice = new UrgentNotice__c();
        objUrgentNotice.Subject__c = 'Test Subject';
        objUrgentNotice.Description__c = 'Test Description';
        objUrgentNotice.StartDate__c = Date.today().addDays(-3);
        objUrgentNotice.EndDate__c = Date.today().addDays(3);
        insert objUrgentNotice;

        RenewalHPNotice.getUrgentNotice();

        Test.stopTest();
    }
}