PA_Education/TestMenifest/force-app/main/default/objects/FormRequest__c/FormRequest__c.object-meta.xml
<CustomObject>
    <description>재직증명서등(추후 추가될 수 있음)을 요청
승인 출력하기위한 오브젝트</description>
    <label>증명서</label>
    <nameField>
        <displayFormat>DNT. {YY}-{MM}{000}</displayFormat>
        <label>문서번호</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/FormRequest__c/fields/FormRequest_Title__c.field-meta.xml
<CustomField>
    <fullName>FormRequest_Title__c</fullName>
    <defaultValue>$User.Title</defaultValue>
    <inlineHelpText>사용자 정보에 있는 값이 기본값이며 
값이 없거나 다를 경우 입력하세요.</inlineHelpText>
    <label>직급</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/FormRequestController.cls
/**
 * Created by choiyuna on 2022-11-11.
 */

public with sharing class FormRequestController {

    public FormRequest__c formRequest { get; set; }
    public String title_Eng { get; set; }
    private final String recordId;

    public FormRequestController(ApexPages.StandardController controller) {
        if (ApexPages.currentPage().getParameters().get('id') != null) {
            recordId = ApexPages.currentPage().getParameters().get('id');
        }

        if (formRequest == null) {
            formRequest = new FormRequest__c();
        }

        if (String.valueOf(Id.valueOf(recordId).getSobjectType()) == 'FormRequest__c') {
            if (recordId != null) {
                formRequest = [
                        SELECT Id, FormRequest_Title__c
                        FROM FormRequest__c
                        WHERE Id = :recordId
                ];
            }
        }

        if (formRequest.FormRequest_Title__c != null) {
            switch on formRequest.FormRequest_Title__c {
                when '대표이사' {
                    title_Eng = 'CEO';
                }
                when '부사장' {
                    title_Eng = 'Vice President';
                }
                when '전무' {
                    title_Eng = 'Executive Vice President';
                }
                when '상무' {
                    title_Eng = 'Managing Director';
                }
                when '이사' {
                    title_Eng = 'Director';
                }
                when '부장' {
                    title_Eng = 'General Manager';
                }
                when '차장' {
                    title_Eng = 'Deputy General Manager';
                }
                when '과장' {
                    title_Eng = 'Manager';
                }
                when '대리' {
                    title_Eng = 'Assistant Manager';
                }
                when '사원' {
                    title_Eng = 'Staff';
                }
                when '센터장' {
                    title_Eng = 'Head of GDC center';
                }
                when '인턴' {
                    title_Eng = 'Intern';
                }
                when else {
                    title_Eng = 'None';
                }
            }
        }
    }
}