PA_Education/TestMenifest/force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Contract</label>
    <nameField>
        <label>계약명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Contract__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>고객사</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/TrekRecord__c/TrekRecord__c.object-meta.xml
<CustomObject>
    <description>실적 Object</description>
    <label>실적</label>
    <nameField>
        <displayFormat>실적-{0000}</displayFormat>
        <label>실적 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/TrekRecord__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>고객사명 Object - Lookup</description>
    <label>고객사명</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>실적</relationshipLabel>
    <relationshipName>AccountDetail</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/TrekRecord__c/fields/ApproachSolution__c.field-meta.xml
<CustomField>
    <fullName>ApproachSolution__c</fullName>
    <label>적용 솔루션</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Tableau</fullName>
            </value>
            <value>
                <fullName>CDP</fullName>
            </value>
            <value>
                <fullName>Heroku</fullName>
            </value>
            <value>
                <fullName>기타</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/TrekRecord__c/fields/Challenge__c.field-meta.xml
<CustomField>
    <fullName>Challenge__c</fullName>
    <label>Challenge</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/TrekRecord__c/fields/OurApproach__c.field-meta.xml
<CustomField>
    <fullName>OurApproach__c</fullName>
    <label>Our Approach</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/TrekRecord__c/fields/ProjectName__c.field-meta.xml
<CustomField>
    <fullName>ProjectName__c</fullName>
    <description>진행한 프로젝트 명</description>
    <label>프로젝트 명</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/TrekRecord__c/fields/StartYear__c.field-meta.xml
<CustomField>
    <fullName>StartYear__c</fullName>
    <description>ex) 2021,2020, 2019</description>
    <label>시작년도</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/HPTrekRecordsViewController.cls
/**
 * ==================================================================================
 * File Name         : HPTrekRecordsViewController
 * Author            : Changjoo.Sohn
 * Group             : Daeu Nextier
 * Description       : 
 * Modification Logs
 * ==================================================================================
 *   Ver     Date          Author          Modification
 * ==================================================================================
 *   1.0   2022-01-18     Changjoo.Sohn   Initial Version
**/
public without sharing class HPTrekRecordsViewController {
    @AuraEnabled
    public static List<WrapperTrekRecord> doSearchTrekRecords() {
        //  전체 실적 리스트를 받아 리턴.
        List<TrekRecord__c> listTrekRecords = [
                SELECT Id, OrderNum__c, StartYear__c, Account__r.Name, ProjectName__c, Challenge__c, OurApproach__c, ApproachSolution__c
                FROM TrekRecord__c
                ORDER BY StartYear__c DESC, OrderNum__c ASC
        ];

        List<WrapperTrekRecord> listWrapperTrekRecords = new List<WrapperTrekRecord>();
        if(!listTrekRecords.isEmpty()){
            Integer idx = 1;
            for(TrekRecord__c objTrekRecord : listTrekRecords){
                listWrapperTrekRecords.add(new WrapperTrekRecord(idx, objTrekRecord));
                idx++;
            }
        }

        return listWrapperTrekRecords;
    }

    @AuraEnabled
    public static TrekRecord__c getRecordById(String recordId) {
        TrekRecord__c objTrekRecord = [
                SELECT Id, Account__r.Name, OrderNum__c, StartYear__c, OurApproach__c, Challenge__c, ProjectName__c, ApproachSolution__c
                FROM TrekRecord__c
                WHERE Id = :recordId
        ];

        return objTrekRecord;
    }

    public class WrapperTrekRecord {
        @AuraEnabled public String IndexNumber;
        @AuraEnabled public String Id;
        @AuraEnabled public String AccountName;
        @AuraEnabled public String ProjectName;
        @AuraEnabled public String StartYear;
        @AuraEnabled public String ApproachSolution;
        @AuraEnabled public String Challenge;
        @AuraEnabled public String OurApproach;
        @AuraEnabled public Integer OrderNum;

        public WrapperTrekRecord(Integer idx, TrekRecord__c objTrekRecord){
            this.IndexNumber = idx == null ? '' : String.valueOf(idx);
            this.Id = objTrekRecord.Id == null ? '' : String.valueOf(objTrekRecord.Id);
            this.AccountName = objTrekRecord.Account__r.Name == null ? '' : objTrekRecord.Account__r.Name;
            this.ProjectName = objTrekRecord.ProjectName__c == null ? '' : objTrekRecord.ProjectName__c;
            this.StartYear = objTrekRecord.StartYear__c == null ? '' : objTrekRecord.StartYear__c;
            this.ApproachSolution = objTrekRecord.ApproachSolution__c == null ? '' : objTrekRecord.ApproachSolution__c;
            this.Challenge = objTrekRecord.Challenge__c == null ? '' : objTrekRecord.Challenge__c;
            this.OurApproach = objTrekRecord.OurApproach__c == null ? '' : objTrekRecord.OurApproach__c;
            this.OrderNum = objTrekRecord.OrderNum__c == null ? 0 : Integer.valueOf(objTrekRecord.OrderNum__c);
        }
    }
}