PA_Education/TestMenifest/force-app/main/default/objects/EformsignTemplate__c/EformsignTemplate__c.object-meta.xml
<CustomObject>
    <description>이폼싸인 템플릿</description>
    <label>eformsign Template</label>
    <nameField>
        <label>eformsign Template Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignTemplate__c/fields/ObjectApiName__c.field-meta.xml
<CustomField>
    <fullName>ObjectApiName__c</fullName>
    <label>대상 개체명</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignTemplate__c/fields/TemplateId__c.field-meta.xml
<CustomField>
    <fullName>TemplateId__c</fullName>
    <externalId>true</externalId>
    <label>Template Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignToken__c/EformsignToken__c.object-meta.xml
<CustomObject>
    <label>eformsign Token</label>
    <nameField>
        <label>eformsign Token Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignToken__c/fields/AccessToken__c.field-meta.xml
<CustomField>
    <fullName>AccessToken__c</fullName>
    <label>Access Token</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignToken__c/fields/ExpireIn__c.field-meta.xml
<CustomField>
    <fullName>ExpireIn__c</fullName>
    <label>Expire In</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignToken__c/fields/RefreshToken__c.field-meta.xml
<CustomField>
    <fullName>RefreshToken__c</fullName>
    <label>Refresh Token</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignToken__c/fields/TokenIssuedDateTime__c.field-meta.xml
<CustomField>
    <fullName>TokenIssuedDateTime__c</fullName>
    <label>Token Issued DateTime</label>
    <type>DateTime</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignToken__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>eformsign_Token</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/EformsignTemplateManager_Test.cls
/************************************************************************************
 * Description :
 * Ver      Date           Author          Modification
 * ===================================================================================
   1.0      2024-07-01     hs.jung          Create
*************************************************************************************/
@IsTest
private class EformsignTemplateManager_Test {

    @IsTest
    static void testBehavior() {
        Test.setMock(HttpCalloutMock.class, new HttpCalloutSuccessMock());
        EformsignToken__c objEformsignToken = new EformsignToken__c();
        objEformsignToken.Name = 'eftkName';
        objEformsignToken.AccessToken__c = 'et54345344535632sdfsdrt32';
        objEformsignToken.RefreshToken__c = 'et54345344535632sdfsdrt3223';
        objEformsignToken.User__c = UserInfo.getUserId();
        objEformsignToken.TokenIssuedDateTime__c = System.today() + 2 ;
        objEformsignToken.ExpireIn__c = 3600;
        insert objEformsignToken;


        EformsignTemplate__c objEformsignTemplate = new EformsignTemplate__c();
        objEformsignTemplate.Name = 'test';
        objEformsignTemplate.ObjectApiName__c = 'Account';
        objEformsignTemplate.TemplateId__c = 'TemplateId';
        insert objEformsignTemplate;



        test.startTest();
        EformsignTemplateManager.Deletion efDelete = new EformsignTemplateManager.Deletion(objEformsignTemplate.Id);

        efDelete.execute();
        efDelete.databaseLogic();
        efDelete.sendRequest();

        test.stopTest();
    }

    private class RestMock implements HttpCalloutMock {

        public HTTPResponse respond(HTTPRequest req) {

            HTTPResponse res = new HTTPResponse();
            req.setHeader('Content-Type', 'application/json');
            req.setHeader('Authorization', 'Bearer ' + 'accessToken');
            res.setBody('{"api_key": {"company": {"api_url": "' + 'https://kr-api.eformsign.com' + '"}}}');
            res.setStatusCode(200);
            return res;
        }
    }

    // Http response
    private static HttpResponse newResponse(Integer statusCode) {
        HttpResponse response = new HttpResponse();

        response.setStatusCode(statusCode);
        response.setBody('{}');

        return response;
    }

    // StatusCode 200 Mock
    private class HttpCalloutSuccessMock implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest request) {
            HttpResponse response = newResponse(200);

            return response;
        }
    }
}