PA_Education/TestMenifest/force-app/main/default/objects/EformsignTemplate__c/EformsignTemplate__c.object-meta.xml
<CustomObject>
    <description>이폼싸인 템플릿</description>
    <label>eformsign Template</label>
    <nameField>
        <label>eformsign Template Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignTemplate__c/fields/IsDeletedInEformsign__c.field-meta.xml
<CustomField>
    <fullName>IsDeletedInEformsign__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Deleted In eformsign</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignTemplate__c/fields/IsDeployedF__c.field-meta.xml
<CustomField>
    <fullName>IsDeployedF__c</fullName>
    <formula>NOT(ISNULL(DeployedTemplateVersion__c))
&amp;&amp;
NOT(IsDeletedInEformsign__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Deployed</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignTemplate__c/fields/ObjectApiName__c.field-meta.xml
<CustomField>
    <fullName>ObjectApiName__c</fullName>
    <label>대상 개체명</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignTemplate__c/fields/TemplateId__c.field-meta.xml
<CustomField>
    <fullName>TemplateId__c</fullName>
    <externalId>true</externalId>
    <label>Template Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/EformsignTemplateCtrl.cls
/************************************************************************************
 * Description :
 * Ver      Date           Author          Modification
 * ===================================================================================
   1.0      2024-05-28     hs.jung          Create
*************************************************************************************/
public with sharing class EformsignTemplateCtrl {
    @AuraEnabled
    public static void deleteTemplate(String templateId) {
        EformsignTokenizedApiWorkflow mng = new EformsignTemplateManager.Deletion(templateId);
        mng.execute();
    }

    public static List<EformsignTemplate__c> getTemplatesBySObject(String objectApiName){
        return [
                SELECT Id, name, TemplateId__c
                FROM EformsignTemplate__c
                WHERE ObjectApiName__c = :objectApiName
                AND IsDeployedF__c = TRUE
                AND IsDeletedInEformsign__c = FALSE
                ORDER BY CreatedDate DESC
        ];
    }
}