PA_Education/TestMenifest/force-app/main/default/objects/EformsignTemplate__c/EformsignTemplate__c.object-meta.xml
<CustomObject>
    <description>이폼싸인 템플릿</description>
    <label>eformsign Template</label>
    <nameField>
        <label>eformsign Template Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignTemplate__c/fields/ObjectApiName__c.field-meta.xml
<CustomField>
    <fullName>ObjectApiName__c</fullName>
    <label>대상 개체명</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignTemplate__c/fields/TemplateId__c.field-meta.xml
<CustomField>
    <fullName>TemplateId__c</fullName>
    <externalId>true</externalId>
    <label>Template Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignTemplate__c/fields/TemplateVersion__c.field-meta.xml
<CustomField>
    <fullName>TemplateVersion__c</fullName>
    <label>Template Version</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/EformsignEditTemplatePageCtrl_Test.cls
/************************************************************************************
 * Description :
 * Ver      Date           Author          Modification
 * ===================================================================================
   1.0      2024-07-04     hs.jung          Create
*************************************************************************************/
@isTest
public with sharing class EformsignEditTemplatePageCtrl_Test {
    @isTest
    static void testConstructor() {
        // Test constructor initialization
        ApexPages.StandardSetController stdController = new ApexPages.StandardSetController(new List<Account>());
        EformsignEditTemplatePageCtrl controller = new EformsignEditTemplatePageCtrl(stdController);
        System.assertNotEquals(null, controller.tokenUser);
        System.assertNotEquals(null, controller.tokenManager);
    }

    @isTest
    static void testtamplateMap() {
        Map<String, String> tamplateMap = new Map<String, String>();
        tamplateMap.put('objectApiName', 'Account');
        tamplateMap.put('templateId', 'templateId1234');
        tamplateMap.put('templateVersion', '1');
        tamplateMap.put('templateName', 'templateName22');

        List<Map<String, String>> fieldInofs = new List<Map<String, String>>();

        fieldInofs.add(tamplateMap);

        EformsignTemplate__c objEformsignTemplate = new EformsignTemplate__c();
        objEformsignTemplate.Name = tamplateMap.get('templateName');
        objEformsignTemplate.ObjectApiName__c =  tamplateMap.get('objectApiName');
        objEformsignTemplate.TemplateId__c = tamplateMap.get('templateId');
        objEformsignTemplate.TemplateVersion__c =  Integer.valueof(tamplateMap.get('templateVersion'));
        insert objEformsignTemplate;


        Test.startTest();
        EformsignEditTemplatePageCtrl.getSObjectInfo('Account');
        EformsignEditTemplatePageCtrl.upsertTemplate(true, tamplateMap, fieldInofs);
        Test.stopTest();

    }
}