PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/Holiday__c.object-meta.xml
<CustomObject>
    <label>Holiday</label>
    <nameField>
        <displayFormat>H-{0000}</displayFormat>
        <label>Holiday No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_JoinDate__c.field-meta.xml
<CustomField>
    <fullName>Holiday_JoinDate__c</fullName>
    <label>입사일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_LastActivity__c.field-meta.xml
<CustomField>
    <fullName>Holiday_LastActivity__c</fullName>
    <label>최종 사용 내역</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_PeriodEnd__c.field-meta.xml
<CustomField>
    <fullName>Holiday_PeriodEnd__c</fullName>
    <description>수식 필드에 대한 상세설명 작성(필드 상세설명 수정일: 2021-12-23, 수정자: cj.sohn@daeunextier.com)
1. 입사일 기준여부가 TRUE일 때,
1-1) 금연도 입사월일이 오늘보다 작을 때, 금연도 입사월일 - 1 + 365
1-2) 금연도 입사월일이 오늘보다 크거나 같을 때, 금연도 입사월일 -1 + 0

ex) 오늘: 2021년 12월 23일
사원A: 입사일 2019-12-15 →  금연도 입사월일 (2021-12-15) → 연차만료일: 2022-12-15
사원B: 입사일 2020-12-28 → 금연도 입사월일 (2021-12-28) → 연차만료일: 2021-12-28
사원C: 입사일 2021-12-23 →  금연도 입사월일 (2021-12-23) → 연차만료일: 2022-12-22

2. 입사일 기준여부가 FALSE일 때,
2-1) 금연도 말일이 오늘보다 클 때, 전연도 말일 + 365
2-2) 금연도 말일이 오늘보다 작거나 같을 때, 전연도 말일 + 0 (가능성 0%)

ex) 오늘: 2021년 2월 4일, 금연도 말일: 2021년 12월 31일 → 연차만료일: 2021년 12월 31일

* 참고사항
Custom Setting(HolidaySetting__c)의 필드 및 값 정리 (2021-12-23 기준)
- 연차기준일(HoldayRuleDate__c): 2000. 1. 1
- 갱신일 이전 일수 차감여부(IsCeil__c): true
- 입사일 기준여부(JoinDateRule__c): false</description>
    <formula>IF(
    $Setup.HolidaySetting__c.JoinDateRule__c,
    DATE( YEAR(TODAY()), MONTH(Holiday_JoinDate__c), DAY(Holiday_JoinDate__c) ) - 1 +
    IF(
        DATE( YEAR(TODAY()), MONTH(Holiday_JoinDate__c), DAY(Holiday_JoinDate__c) ) &lt; TODAY(),
        365,
        0
    ),
    DATE( YEAR(TODAY()), MONTH($Setup.HolidaySetting__c.HoldayRuleDate__c ), DAY($Setup.HolidaySetting__c.HoldayRuleDate__c) ) - 1 +
    IF(
        DATE( YEAR(TODAY()), MONTH($Setup.HolidaySetting__c.HoldayRuleDate__c), DAY($Setup.HolidaySetting__c.HoldayRuleDate__c) ) &lt; TODAY(),
        365,
        0
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>연차만료일</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_Uncountable__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Uncountable__c</fullName>
    <defaultValue>0</defaultValue>
    <label>공무</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_Unpaid__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Unpaid__c</fullName>
    <defaultValue>0</defaultValue>
    <label>무급휴가</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_UseDays__c.field-meta.xml
<CustomField>
    <fullName>Holiday_UseDays__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>올해 연월차 사용일수</inlineHelpText>
    <label>연월차 사용일수</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_User__c.field-meta.xml
<CustomField>
    <fullName>Holiday_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>임직원</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Holiday</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/HolidayAction__c.object-meta.xml
<CustomObject>
    <description>HolidayAction__c</description>
    <label>휴가신청</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/FirstHolidayRequest__c.field-meta.xml
<CustomField>
    <fullName>FirstHolidayRequest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>1차 승인자 지정</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Holiday_Action1</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_AlternativeBase__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_AlternativeBase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Fill this if use Alternative Holiday.
If you can&apos;t see any rows then you don&apos;t have Alternative Holiday Register.</inlineHelpText>
    <label>Base of Alternative Holiday</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND ((2 AND 3 AND 4) OR (5 AND 6 AND 7))</booleanFilter>
        <filterItems>
            <field>HolidayAction__c.HolidayAction_IsConfirm__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.HolidayAction_Type__c</field>
            <operation>equals</operation>
            <value>Alternative Holiday</value>
        </filterItems>
        <filterItems>
            <field>HolidayAction__c.HolidayAction_Type__c</field>
            <operation>equals</operation>
            <value>Alternative Holiday Register</value>
        </filterItems>
        <filterItems>
            <field>HolidayAction__c.HolidayAction_AlternativeBase__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>$Source.HolidayAction_Type__c</field>
            <operation>equals</operation>
            <value>Alternative Holiday Register</value>
        </filterItems>
        <filterItems>
            <field>HolidayAction__c.HolidayAction_Type__c</field>
            <operation>equals</operation>
            <value>Alternative Holiday</value>
        </filterItems>
        <filterItems>
            <field>HolidayAction__c.HolidayAction_AlternativeBase__c</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>HolidayAction__c</referenceTo>
    <relationshipName>Holiday_Action</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Days__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Days__c</fullName>
    <inlineHelpText>Women&apos;s Holiday 1.
Alternative Holiday 0.
Other Holidays from 1 to 5.</inlineHelpText>
    <label>Days</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Description__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_IsConfirm__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_IsConfirm__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Confirm?</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_IsEmergency__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_IsEmergency__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check This field when you want use Holidays before approval process.</inlineHelpText>
    <label>Is emergency?</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Parent__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Parent__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Holiday</label>
    <referenceTo>Holiday__c</referenceTo>
    <relationshipName>Holiday_Action</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Type__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Annual Holiday</fullName>
                <label>연차</label>
            </value>
            <value>
                <fullName>Half-day Leave</fullName>
                <label>반차</label>
            </value>
            <value>
                <fullName>Reward Holiday</fullName>
                <label>대체휴가</label>
            </value>
            <value>
                <fullName>Reward Half-Holiday</fullName>
                <label>대체휴가(반차)</label>
            </value>
            <value>
                <fullName>Public Works</fullName>
                <label>공가(공무)</label>
            </value>
            <value>
                <fullName>Family Leave</fullName>
                <label>경조휴가</label>
            </value>
            <value>
                <fullName>Sick Leave</fullName>
                <label>병가(무급)</label>
            </value>
            <value>
                <fullName>Women Holiday</fullName>
                <label>생리휴가</label>
            </value>
            <value>
                <fullName>가족돌봄휴가</fullName>
            </value>
            <value>
                <fullName>출산휴가</fullName>
            </value>
            <value>
                <fullName>휴직</fullName>
            </value>
            <value>
                <fullName>육아휴직</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidaySetting__c/HolidaySetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>휴일관리 기준 설정</description>
    <label>HolidaySetting</label>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/HolidaySetting__c/fields/HoldayRuleDate__c.field-meta.xml
<CustomField>
    <fullName>HoldayRuleDate__c</fullName>
    <defaultValue>DATE(2000,1,1)</defaultValue>
    <description>입사일기준이 False일 경우
설정된 날짜(년도 무시)를 기준으로 연차 생성 및 사용일수 초기화를 한다.</description>
    <label>연차 기준일</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidaySetting__c/fields/IsCeil__c.field-meta.xml
<CustomField>
    <fullName>IsCeil__c</fullName>
    <defaultValue>true</defaultValue>
    <description>값이 True일 경우 연차 기준일 당시 만근을 하지 않아도 연차를 가산 및 이전 사용일수를 초기화 한다.
false일 경우 연차 기준일 당신 만근이 아니면 연차를 가산하지 않고 1년 근속 미만일 경우 사용일수를 초기화 하지 않는다
예) 올림일 경우 전년도 4월 입사자는 연차사용일수가 초기화 되고
전전년도 4월 입사자는 연차가 16일로 1일 가산 된다.
내림일 경우 전년도 4월 입사자는 연차일수가 초기화 되지 않고
전전년도 4월 입사자는 연차가 15일로 1일 가산은 다음해로 넘어간다.</description>
    <label>갱신일 이전 일수 차감여부</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidaySetting__c/fields/JoinDateRule__c.field-meta.xml
<CustomField>
    <fullName>JoinDateRule__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True일경우 입사일 기준으로 연차 생성 및 사용연차를 갱신한다.
False일경우 특정일 기준으로 연차 생성 및 사용연차를 갱신한다.</description>
    <label>입사일 기준여부</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/Holiday_Test.cls
@isTest
public class Holiday_Test{
    static User testUser;
    static TestMethod void HolidayEditListController_Test(){
        Profile p = TestDataFactory.getProfile('System Admin');
        
        testUser = TestDataFactory.createUser(p);   
        
        Test.startTest();
        
        HolidayEditListController hel = new HolidayEditListController();
        hel.doCreate();
        //hel.search();
        hel.hldChkLst[0].hld.Holiday_JoinDate__c = system.today().addYears(-1).addDays(-1);
        hel.hldChkLst[0].hld.Holiday_Unpaid__c = 1;
        hel.hldChkLst[0].hld.Holiday_Uncountable__c = 1;
        //hel.hldChkLst[0].hld.id = testUser.id;
        hel.doSave();
        hel.checkChange();
        hel.doSend();
        hel.checkChange();
        hel.doResetUnpaid();
        hel.checkChange();
        hel.doResetUncountable();
        hel.checkChange();
        hel.addDays = '2';
        hel.addDesc = null;
        hel.doAdd();
        hel.checkChange();
        hel.addDays = '3';
        hel.addDesc = 'test';
        hel.doAdd();
        hel.checkChange();
        hel.addDays = 'a';
        hel.addDesc = 'test';
        hel.doAdd();
        hel.checkChange();
        hel.checkChange();
        hel.doCancel();
        Test.stopTest();
    }
    static TestMethod void HolidayActionExtension_Test(){

        //Profile p = TestDataFactory.getProfile('System Admin');
        //testUser = TestDataFactory.createUser(p);   

        

        /*00e90000001qLEaAAM*/
        //Profile p = [select id from Profile where Name='System Administrator'];

      Test.startTest();

        Profile p = new Profile();
        p = TestDataFactory.getProfile('System Admin');   
        testUser = TestDataFactory.createUser(p);   
        //user1 = TestDataFactory.createUser(p);   

        //HolidayEditListController hel = new HolidayEditListController();
        //hel.doCreate();
        //string id = hel.hldChkLst[0].hld.Id;


        /*실제신청자*/
        User user = new User(Alias = 'test1'
                            , Email='SysAdminTestuser@earth.org'
                            , EmailEncodingKey='UTF-8'
                            , LastName='Testing'
                            , FirstName='Tester'
                            , LanguageLocaleKey='en_US'
                            , LocaleSidKey='en_US'
                            , EmployeeNumber='AC100000'
                            , ProfileId = p.Id
                            , TimeZoneSidKey='Asia/Seoul'
                            , UserName='systemTestUser@earth.org');
                                
        insert user;

        /*1차승인자*/
        User user1 = new User(Alias = 'UserTest'
                            , Email='SysAdminTestuser@earth.org'
                            , EmailEncodingKey='UTF-8'
                            , LastName='Testing1'
                            , LanguageLocaleKey='en_US'
                            , LocaleSidKey='en_US'
                            , EmployeeNumber='AC100001'
                            , ProfileId = p.Id
                            , TimeZoneSidKey='Asia/Seoul'
                            , UserName='SysAdminUserTest@earth.org');
                                
        insert user1;

        string id = user.id;
        HolidayAction__c ha = new HolidayAction__c();
        ha.HolidayAction_Parent__c = id;
        ApexPages.StandardController ctrl = new ApexPages.StandardController(ha);  

        //Holiday__c hae = new Holiday__c();
        //hae.Holiday_UseDays__c = 1;
        //hae.Holiday_User__c = user.Id;

        //insert hae;

        HolidayActionExtension hae = new HolidayActionExtension(ctrl);
        hae.hldyActn.Name = 'test';
        hae.hldyActn.FirstHolidayRequest__c = user1.Id;
        hae.hldyActn.HolidayAction_Description__c = 'test';
        hae.hldyActn.HolidayAction_Parent__c = id;
        hae.hldyActn.HolidayAction_IsConfirm__c = false;
        hae.hldyActn.HolidayAction_IsEmergency__c = false;
        hae.hldyActn.HolidayAction_Type__c = 'Alternative Holiday Register';
        hae.typeCheck();
        hae.hldyActn.HolidayAction_Type__c = 'Monthly Holiday';
        hae.typeCheck();
        hae.hldyActn.HolidayAction_Days__c = 6;
        hae.changeDay();
        hae.hldyActn.HolidayAction_Days__c = 5;
        hae.doSave();
        hae.doCancel();
        
        ha = new HolidayAction__c();
        ha.HolidayAction_Parent__c = id;
        ctrl = new ApexPages.StandardController(ha); 
        hae = new HolidayActionExtension(ctrl);
        hae.hldyActn.Name = 'test';
        hae.hldyActn.FirstHolidayRequest__c = user1.Id;
        hae.hldyActn.HolidayAction_Description__c = 'test';
        hae.hldyActn.HolidayAction_Parent__c = id;
        hae.hldyActn.HolidayAction_IsConfirm__c = false;
        hae.hldyActn.HolidayAction_IsEmergency__c = false;
        hae.hldyActn.HolidayAction_Type__c = 'Women Holiday';
        hae.typeCheck();
        hae.doSave();
        hae.doCancel();
            
        ha = new HolidayAction__c();
        ha.HolidayAction_Parent__c = id;
        ctrl = new ApexPages.StandardController(ha); 
        hae = new HolidayActionExtension(ctrl);
        hae.hldyActn.Name = 'test';
        hae.hldyActn.FirstHolidayRequest__c = user1.Id;
        hae.hldyActn.HolidayAction_Description__c = 'test';
        hae.hldyActn.HolidayAction_Parent__c = id;
        hae.hldyActn.HolidayAction_IsConfirm__c = false;
        hae.hldyActn.HolidayAction_IsEmergency__c = false;
        hae.hldyActn.HolidayAction_Type__c = 'Annual Holiday';
        hae.typeCheck();
        hae.doSave();
        hae.doCancel();  
        
        ha = new HolidayAction__c();
        ha.HolidayAction_Parent__c = id;
        ctrl = new ApexPages.StandardController(ha); 
        hae = new HolidayActionExtension(ctrl);
        hae.hldyActn.Name = 'test';
        hae.hldyActn.FirstHolidayRequest__c = user1.Id;
        hae.hldyActn.HolidayAction_Description__c = 'test';
        hae.hldyActn.HolidayAction_Parent__c = id;
        hae.hldyActn.HolidayAction_IsConfirm__c = false;
        hae.hldyActn.HolidayAction_IsEmergency__c = false;
        hae.hldyActn.HolidayAction_Type__c = 'Public Works';
        hae.typeCheck();
        hae.doSave();
        hae.doCancel();
        
        ha = new HolidayAction__c();
        ha.HolidayAction_Parent__c = id;
        ctrl = new ApexPages.StandardController(ha); 
        hae = new HolidayActionExtension(ctrl);
        hae.hldyActn.Name = 'test';
        hae.hldyActn.FirstHolidayRequest__c = user1.Id;
        hae.hldyActn.HolidayAction_Description__c = 'test';
        hae.hldyActn.HolidayAction_Parent__c = id;
        hae.hldyActn.HolidayAction_IsConfirm__c = false;
        hae.hldyActn.HolidayAction_IsEmergency__c = false;
        hae.hldyActn.HolidayAction_Type__c = 'Sick Leave';
        hae.typeCheck();
        hae.doSave();
        hae.doCancel();
        
        string refId = '';
        ha = new HolidayAction__c();
        ha.HolidayAction_Parent__c = id;
        ctrl = new ApexPages.StandardController(ha);  
        hae = new HolidayActionExtension(ctrl);
        hae.hldyActn.Name = 'test';
        hae.hldyActn.FirstHolidayRequest__c = user1.Id;
        hae.hldyActn.HolidayAction_Description__c = 'test';
        hae.hldyActn.HolidayAction_Parent__c = id;
        hae.hldyActn.HolidayAction_IsConfirm__c = false;
        hae.hldyActn.HolidayAction_IsEmergency__c = false;
        hae.hldyActn.HolidayAction_Type__c = 'Alternative Holiday Register';
        hae.typeCheck();
        hae.doSave();
        hae.doCancel();
        
        
        //refId = [SELECT Id FROM HolidayAction__c WHERE HolidayAction_Type__c = 'Alternative Holiday Register'].Id;
        //ha = new HolidayAction__c();
        //ha.HolidayAction_Parent__c = id;
        //ctrl = new ApexPages.StandardController(ha);   
        //hae = new HolidayActionExtension(ctrl);
        //hae.hldyActn.Name = 'test';
        //hae.hldyActn.FirstHolidayRequest__c = user1.Id;
        //hae.hldyActn.HolidayAction_Description__c = 'test';
        //hae.hldyActn.HolidayAction_Parent__c = id;
        //hae.hldyActn.HolidayAction_IsConfirm__c = false;
        //hae.hldyActn.HolidayAction_IsEmergency__c = true;
        //hae.hldyActn.HolidayAction_Type__c = 'Alternative Holiday';
        //hae.hldyActn.HolidayAction_AlternativeBase__c = refId;
        //hae.typeCheck();
        //hae.doSave();
        //hae.doCancel();

        /* 현재 사용하지 않는 휴가 주석처리함
         * LJK 2019-01-10
        */
        
        
        list<HolidayAction__c> haLst = [SELECT Id FROM HolidayAction__c];
        for(HolidayAction__c has : haLst)
            has.HolidayAction_IsConfirm__c = true;
        update haLst;
        Test.stopTest();
    }
    static TestMethod void HolidayMyInfoController_Test(){
        //Profile p = TestDataFactory.getProfile('System Admin');        
        //testUser = TestDataFactory.createUser(p);  

        Profile p = new Profile();
        p = TestDataFactory.getProfile('System Admin');   

        HolidayEditListController hel = new HolidayEditListController();
        hel.doCreate(); 


        /*실제신청자*/
        User user = new User(Alias = 'test1'
                            , Email='SysAdminTestuser@earth.org'
                            , EmailEncodingKey='UTF-8'
                            , LastName='Testing'
                            , FirstName='Tester'
                            , LanguageLocaleKey='en_US'
                            , LocaleSidKey='en_US'
                            , EmployeeNumber='AC100000'
                            , ProfileId = p.Id
                            , TimeZoneSidKey='Asia/Seoul'
                            , UserName='myInfoTESTuser@earth.org');
                                
        insert user;

        /*1차승인자*/
        User user1 = new User(Alias = 'UserTest'
                            , Email='SysAdminTestuser@earth.org'
                            , EmailEncodingKey='UTF-8'
                            , LastName='Testing1'
                            , LanguageLocaleKey='en_US'
                            , LocaleSidKey='en_US'
                            , EmployeeNumber='AC100001'
                            , ProfileId = p.Id
                            , TimeZoneSidKey='Asia/Seoul'
                            , UserName='myInfoApprover@earth.org');
                                
        insert user1;

        testUser = TestDataFactory.createUser(p);   

        Holiday__c spq = new Holiday__c();
        spq.Holiday_UseDays__c = 1;
        spq.Holiday_User__c = user.Id;

        insert spq;

        
        PageReference myVfPage = Page.MyHolidayInfo;
        Test.setCurrentPageReference(myVfPage);
       
        ApexPages.currentPage().getParameters().put('sfdc.userId',user.id);
        String id = ApexPages.currentPage().getParameters().get('sfdc.userId');

        //system.assertEquals(true,id!=null);
        Holiday__History hh = new Holiday__History(ParentId = spq.id, Field = 'Holiday_LastActivity__c');
        //Holiday__History hh2 = new Holiday__History(ParentId = spq.Holiday_User__c, Field = 'Holiday_LastActivity__c');
        //Holiday__History hh3 = new Holiday__History(ParentId = spq.Holiday_User__c, Field = 'Holiday_LastActivity__c');
        
        insert hh;
        //insert hh2;
        //hel.hldChkLst[0].hld.Holiday_LastActivity__c = 'test';
        //update hel.hldChkLst[0].hld;
        //insert hh3;


        Test.startTest();
        System.runAs(testUser){
            HolidayMyInfoController ac = new HolidayMyInfoController();
            spq.Holiday_LastActivity__c = 'test2';
            update spq;
            ac.Action();
            ac.RedirectToProfile();
            HolidayMyInfoController.HolidayHistoryClass hc = new HolidayMyInfoController.HolidayHistoryClass();
            hc.CreatedDate = spq.CreatedDate;
            hc.createdDateStr  = '' ;
            hc.user = '' ;
            hc.isNumeric = true ;
            hc.language = '' ;
            hc.actStrVerb1 = '' ;
            hc.actStrNoun = '' ;
            hc.actStrNounPosition = '' ;
            hc.actStrVerb2 = '' ;
            hc.actStrOldPosition = '' ;
            hc.actStrNewPosition = '' ;
            hc.actStrOldValue = '' ;
            hc.actStrNewValue = '' ;
            hc.actStrOldDecimal = null ;
            hc.actStrNewDecimal = null ;
            Holiday__History hstory = new Holiday__History();
            hc.history  = hstory;
            List<Holiday__History> hstoryList = new List<Holiday__History>();
            hstoryList.add(hstory);
            
        }
        Test.stopTest();
    }
    static testMethod void HolidaySchedulertTest() {
        HolidayEditListController hel = new HolidayEditListController();
        System.debug('hel.hldChkLst.size() : ' + hel.hldChkLst.size());
        hel.doCreate();
        // hel.search();
        System.debug('hel.hldChkLst.size() : ' + hel.hldChkLst.size());
        hel.hldChkLst[0].hld.Holiday_JoinDate__c = system.today().addYears(-2).addDays(1);
        hel.hldChkLst[0].hld.Holiday_LastActivity__c = '1';
        hel.hldChkLst[1].hld.Holiday_JoinDate__c = system.today().addYears(-1).addMonths(-6).addDays(-9);
        hel.hldChkLst[1].hld.Holiday_LastActivity__c = '2';
        hel.hldChkLst[2].hld.Holiday_JoinDate__c = system.today().addYears(-1).addMonths(-10).addDays(1);
        hel.hldChkLst[2].hld.Holiday_LastActivity__c = '3';
        hel.doSave();
        list<Holiday__c> hLst = [SELECT Holiday_LastActivity__c, Holiday_PeriodEnd__c FROM Holiday__c];
        insert new HolidaySetting__c(SetupOwnerId=UserInfo.getOrganizationId(), IsCeil__c= true, HoldayRuleDate__c = null, JoinDateRule__c = true);
        system.debug(hLst);
        // TO DO: implement unit test
        test.StartTest();
        //
       
        HolidayScheduler s = new HolidayScheduler() ;
        String sch = '0 1 0 * * ?';
        system.schedule('Test HolidayScheduler', sch, s);
 
        test.StopTest();
    }
}