PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/Holiday__c.object-meta.xml
<CustomObject>
    <label>Holiday</label>
    <nameField>
        <displayFormat>H-{0000}</displayFormat>
        <label>Holiday No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_JoinDate__c.field-meta.xml
<CustomField>
    <fullName>Holiday_JoinDate__c</fullName>
    <label>입사일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_LastActivity__c.field-meta.xml
<CustomField>
    <fullName>Holiday_LastActivity__c</fullName>
    <label>최종 사용 내역</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_PeriodEnd__c.field-meta.xml
<CustomField>
    <fullName>Holiday_PeriodEnd__c</fullName>
    <description>수식 필드에 대한 상세설명 작성(필드 상세설명 수정일: 2021-12-23, 수정자: cj.sohn@daeunextier.com)
1. 입사일 기준여부가 TRUE일 때,
1-1) 금연도 입사월일이 오늘보다 작을 때, 금연도 입사월일 - 1 + 365
1-2) 금연도 입사월일이 오늘보다 크거나 같을 때, 금연도 입사월일 -1 + 0

ex) 오늘: 2021년 12월 23일
사원A: 입사일 2019-12-15 →  금연도 입사월일 (2021-12-15) → 연차만료일: 2022-12-15
사원B: 입사일 2020-12-28 → 금연도 입사월일 (2021-12-28) → 연차만료일: 2021-12-28
사원C: 입사일 2021-12-23 →  금연도 입사월일 (2021-12-23) → 연차만료일: 2022-12-22

2. 입사일 기준여부가 FALSE일 때,
2-1) 금연도 말일이 오늘보다 클 때, 전연도 말일 + 365
2-2) 금연도 말일이 오늘보다 작거나 같을 때, 전연도 말일 + 0 (가능성 0%)

ex) 오늘: 2021년 2월 4일, 금연도 말일: 2021년 12월 31일 → 연차만료일: 2021년 12월 31일

* 참고사항
Custom Setting(HolidaySetting__c)의 필드 및 값 정리 (2021-12-23 기준)
- 연차기준일(HoldayRuleDate__c): 2000. 1. 1
- 갱신일 이전 일수 차감여부(IsCeil__c): true
- 입사일 기준여부(JoinDateRule__c): false</description>
    <formula>IF(
    $Setup.HolidaySetting__c.JoinDateRule__c,
    DATE( YEAR(TODAY()), MONTH(Holiday_JoinDate__c), DAY(Holiday_JoinDate__c) ) - 1 +
    IF(
        DATE( YEAR(TODAY()), MONTH(Holiday_JoinDate__c), DAY(Holiday_JoinDate__c) ) &lt; TODAY(),
        365,
        0
    ),
    DATE( YEAR(TODAY()), MONTH($Setup.HolidaySetting__c.HoldayRuleDate__c ), DAY($Setup.HolidaySetting__c.HoldayRuleDate__c) ) - 1 +
    IF(
        DATE( YEAR(TODAY()), MONTH($Setup.HolidaySetting__c.HoldayRuleDate__c), DAY($Setup.HolidaySetting__c.HoldayRuleDate__c) ) &lt; TODAY(),
        365,
        0
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>연차만료일</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_User__c.field-meta.xml
<CustomField>
    <fullName>Holiday_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>임직원</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Holiday</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/HolidayAction__c.object-meta.xml
<CustomObject>
    <description>HolidayAction__c</description>
    <label>휴가신청</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/FirstHolidayRequest__c.field-meta.xml
<CustomField>
    <fullName>FirstHolidayRequest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>1차 승인자 지정</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Holiday_Action1</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_AlternativeBase__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_AlternativeBase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Fill this if use Alternative Holiday.
If you can&apos;t see any rows then you don&apos;t have Alternative Holiday Register.</inlineHelpText>
    <label>Base of Alternative Holiday</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND ((2 AND 3 AND 4) OR (5 AND 6 AND 7))</booleanFilter>
        <filterItems>
            <field>HolidayAction__c.HolidayAction_IsConfirm__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$Source.HolidayAction_Type__c</field>
            <operation>equals</operation>
            <value>Alternative Holiday</value>
        </filterItems>
        <filterItems>
            <field>HolidayAction__c.HolidayAction_Type__c</field>
            <operation>equals</operation>
            <value>Alternative Holiday Register</value>
        </filterItems>
        <filterItems>
            <field>HolidayAction__c.HolidayAction_AlternativeBase__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>$Source.HolidayAction_Type__c</field>
            <operation>equals</operation>
            <value>Alternative Holiday Register</value>
        </filterItems>
        <filterItems>
            <field>HolidayAction__c.HolidayAction_Type__c</field>
            <operation>equals</operation>
            <value>Alternative Holiday</value>
        </filterItems>
        <filterItems>
            <field>HolidayAction__c.HolidayAction_AlternativeBase__c</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>HolidayAction__c</referenceTo>
    <relationshipName>Holiday_Action</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Days__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Days__c</fullName>
    <inlineHelpText>Women&apos;s Holiday 1.
Alternative Holiday 0.
Other Holidays from 1 to 5.</inlineHelpText>
    <label>Days</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Description__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_IsConfirm__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_IsConfirm__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Confirm?</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_IsEmergency__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_IsEmergency__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check This field when you want use Holidays before approval process.</inlineHelpText>
    <label>Is emergency?</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Parent__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Parent__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Holiday</label>
    <referenceTo>Holiday__c</referenceTo>
    <relationshipName>Holiday_Action</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Type__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Annual Holiday</fullName>
                <label>연차</label>
            </value>
            <value>
                <fullName>Half-day Leave</fullName>
                <label>반차</label>
            </value>
            <value>
                <fullName>Reward Holiday</fullName>
                <label>대체휴가</label>
            </value>
            <value>
                <fullName>Reward Half-Holiday</fullName>
                <label>대체휴가(반차)</label>
            </value>
            <value>
                <fullName>Public Works</fullName>
                <label>공가(공무)</label>
            </value>
            <value>
                <fullName>Family Leave</fullName>
                <label>경조휴가</label>
            </value>
            <value>
                <fullName>Sick Leave</fullName>
                <label>병가(무급)</label>
            </value>
            <value>
                <fullName>Women Holiday</fullName>
                <label>생리휴가</label>
            </value>
            <value>
                <fullName>가족돌봄휴가</fullName>
            </value>
            <value>
                <fullName>출산휴가</fullName>
            </value>
            <value>
                <fullName>휴직</fullName>
            </value>
            <value>
                <fullName>육아휴직</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/HolidayController_Test.cls
/*
* Component Name                : MyHolidayInfoLightning.cmp
* Component Controller          : MyHolidayInfoLightningController.js
* Component Helper              : MyHolidayInfoLightningHelper.js
* Component Contorlller Class   : HolidayController.cls
* Test Class                    : HolidayController_Test.cls
* Description                   : 휴가정보 Detail Test
* Modification Log 
* =============================================================== 
* Ver     Date          Author           Modification
* ===============================================================
  1.0   2018.08.27      JK.Lee             Create
  1.0   2018.11.20                         Modified
*/

@isTest
public class HolidayController_Test {
    static User testUser;

    @isTest
    static void HolidayController_Test() {

        Test.startTest();

        Profile p = TestDataFactory.getProfile('System Admin');
        Profile p2 = TestDataFactory.getProfile('System Admin');

        testUser = TestDataFactory.createUser(p);
        HolidayEditListController hel = new HolidayEditListController();
        hel.doCreate();
        string id = testUser.id;

        HolidayAction__c ha = new HolidayAction__c();
        ha.HolidayAction_Parent__c = id;
        ApexPages.StandardController ctrl = new ApexPages.StandardController(ha);

        HolidayActionExtension hae = new HolidayActionExtension(ctrl);
        //hae.hldyActn.Name = 'test';
        //hae.hldyActn.FirstHolidayRequest__c = testUser.Id;
        //hae.hldyActn.HolidayAction_Description__c = 'test';
        //hae.hldyActn.HolidayAction_Parent__c = id;
        //hae.hldyActn.HolidayAction_IsConfirm__c = false;
        //hae.hldyActn.HolidayAction_IsEmergency__c = false;
        //hae.hldyActn.HolidayAction_Type__c = 'Alternative Holiday Register';
        //hae.typeCheck();
        //hae.hldyActn.HolidayAction_Type__c = 'Monthly Holiday';
        //hae.typeCheck();
        //hae.hldyActn.HolidayAction_Days__c = 6;
        //hae.changeDay();
        //hae.hldyActn.HolidayAction_Days__c = 5;
        //hae.doSave();
        //hae.doCancel();

        ha = new HolidayAction__c();
        ha.HolidayAction_Parent__c = id;
        ctrl = new ApexPages.StandardController(ha);
        hae = new HolidayActionExtension(ctrl);
        hae.hldyActn.Name = 'test';
        hae.hldyActn.FirstHolidayRequest__c = testUser.Id;
        hae.hldyActn.HolidayAction_Description__c = 'test';
        hae.hldyActn.HolidayAction_Parent__c = id;
        hae.hldyActn.HolidayAction_IsConfirm__c = false;
        hae.hldyActn.HolidayAction_IsEmergency__c = false;
        hae.hldyActn.HolidayAction_Type__c = 'Women Holiday';
        hae.typeCheck();
        hae.doSave();
        hae.doCancel();

        ha = new HolidayAction__c();
        ha.HolidayAction_Parent__c = id;
        ctrl = new ApexPages.StandardController(ha);
        hae = new HolidayActionExtension(ctrl);
        hae.hldyActn.Name = 'test';
        hae.hldyActn.FirstHolidayRequest__c = testUser.Id;
        hae.hldyActn.HolidayAction_Description__c = 'test';
        hae.hldyActn.HolidayAction_Parent__c = id;
        hae.hldyActn.HolidayAction_IsConfirm__c = false;
        hae.hldyActn.HolidayAction_IsEmergency__c = false;
        hae.hldyActn.HolidayAction_Type__c = 'Annual Holiday';
        hae.typeCheck();
        hae.doSave();
        hae.doCancel();

        ha = new HolidayAction__c();
        ha.HolidayAction_Parent__c = id;
        ctrl = new ApexPages.StandardController(ha);
        hae = new HolidayActionExtension(ctrl);
        hae.hldyActn.Name = 'test';
        hae.hldyActn.FirstHolidayRequest__c = testUser.Id;
        hae.hldyActn.HolidayAction_Description__c = 'test';
        hae.hldyActn.HolidayAction_Parent__c = id;
        hae.hldyActn.HolidayAction_IsConfirm__c = false;
        hae.hldyActn.HolidayAction_IsEmergency__c = false;
        hae.hldyActn.HolidayAction_Type__c = 'Public Works';
        hae.typeCheck();
        hae.doSave();
        hae.doCancel();

        ha = new HolidayAction__c();
        ha.HolidayAction_Parent__c = id;
        ctrl = new ApexPages.StandardController(ha);
        hae = new HolidayActionExtension(ctrl);
        hae.hldyActn.Name = 'test';
        hae.hldyActn.FirstHolidayRequest__c = testUser.Id;
        hae.hldyActn.HolidayAction_Description__c = 'test';
        hae.hldyActn.HolidayAction_Parent__c = id;
        hae.hldyActn.HolidayAction_IsConfirm__c = false;
        hae.hldyActn.HolidayAction_IsEmergency__c = false;
        hae.hldyActn.HolidayAction_Type__c = 'Sick Leave';
        hae.typeCheck();
        hae.doSave();
        hae.doCancel();

        //string refId = '';
        //ha = new HolidayAction__c();
        //ha.HolidayAction_Parent__c = id;
        //ctrl = new ApexPages.StandardController(ha);  
        //hae = new HolidayActionExtension(ctrl);
        //hae.hldyActn.Name = 'test';
        //hae.hldyActn.FirstHolidayRequest__c = testUser.Id;
        //hae.hldyActn.HolidayAction_Description__c = 'test';
        //hae.hldyActn.HolidayAction_Parent__c = id;
        //hae.hldyActn.HolidayAction_IsConfirm__c = false;
        //hae.hldyActn.HolidayAction_IsEmergency__c = false;
        //hae.hldyActn.HolidayAction_Type__c = 'Alternative Holiday Register';
        //hae.typeCheck();
        //hae.doSave();
        //hae.doCancel();


        //refId = [SELECT Id FROM HolidayAction__c WHERE HolidayAction_Type__c = 'Alternative Holiday Register'].Id;
        //ha = new HolidayAction__c();
        //ha.HolidayAction_Parent__c = id;
        //ctrl = new ApexPages.StandardController(ha);   
        //hae = new HolidayActionExtension(ctrl);
        //hae.hldyActn.Name = 'test';
        //hae.hldyActn.FirstHolidayRequest__c = testUser.Id;
        //hae.hldyActn.HolidayAction_Description__c = 'test';
        //hae.hldyActn.HolidayAction_Parent__c = id;
        //hae.hldyActn.HolidayAction_IsConfirm__c = false;
        //hae.hldyActn.HolidayAction_IsEmergency__c = true;
        //hae.hldyActn.HolidayAction_Type__c = 'Alternative Holiday';
        //hae.hldyActn.HolidayAction_AlternativeBase__c = refId;
        //hae.typeCheck();
        //hae.doSave();
        //hae.doCancel();

        list<HolidayAction__c> haLst = [SELECT Id FROM HolidayAction__c];
        for (HolidayAction__c has : haLst) {
            has.HolidayAction_IsConfirm__c = true;
        }
        update haLst;

//        HolidayEditListController hels = new HolidayEditListController();
//        hels.doCreate();
//        System.debug('hels.hldChkLst.size() : ' + hels.hldChkLst.size());
//        ApexPages.currentPage().getParameters().put('sfdc.userId', hels.hldChkLst[0].hld.Holiday_User__c);
//        String ids = ApexPages.currentPage().getParameters().get('sfdc.userId');
//        system.assertEquals(true, ids != null);
//        Holiday__History hh = new Holiday__History(ParentId = hels.hldChkLst[0].hld.Id, Field = 'Holiday_LastActivity__c');
//        Holiday__History hh2 = new Holiday__History(ParentId = hels.hldChkLst[0].hld.Id, Field = 'Holiday_LastActivity__c');
//        Holiday__History hh3 = new Holiday__History(ParentId = hels.hldChkLst[0].hld.Id, Field = 'Holiday_LastActivity__c');

//        insert hh;
//        insert hh2;
//        hels.hldChkLst[0].hld.Holiday_LastActivity__c = 'test';
//        update hels.hldChkLst[0].hld;
//        insert hh3;


        HolidayEditListController heledit = new HolidayEditListController();
        heledit.doCreate();
        heledit.search();
        //heledit.hldChkLst[0].hld.Holiday_JoinDate__c = system.today().addYears(-2).addDays(1);
        //heledit.hldChkLst[0].hld.Holiday_LastActivity__c = '1';
        //heledit.hldChkLst[1].hld.Holiday_JoinDate__c = system.today().addYears(-1).addMonths(-6).addDays(1);
        //heledit.hldChkLst[1].hld.Holiday_LastActivity__c = '2';
        //heledit.hldChkLst[2].hld.Holiday_JoinDate__c = system.today().addYears(-1).addMonths(-10).addDays(1);
        //heledit.hldChkLst[2].hld.Holiday_LastActivity__c = '3';
        heledit.doSave();
        list<Holiday__c> hLst = [SELECT Holiday_LastActivity__c, Holiday_PeriodEnd__c FROM Holiday__c];
        system.debug(hLst);
        // TO DO: implement unit test


        //String recId = String.valueOf(heledit.hldChkLst[0].hld.id);

        HolidayController.getPermissionCheck(Id);
        HolidayController.getHoliday(Id);
        HolidayController.getHolidayHistory(Id);
        HolidayController.getHolidayAction(Id, true);
        HolidayController.getHolidayAction(Id, false);
        HolidayController.getObjectFieldLabel('Holiday__c');
        Test.stopTest();
    }
}