PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/Holiday__c.object-meta.xml
<CustomObject>
    <label>Holiday</label>
    <nameField>
        <displayFormat>H-{0000}</displayFormat>
        <label>Holiday No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_BenefitPaymentDays__c.field-meta.xml
<CustomField>
    <fullName>Holiday_BenefitPaymentDays__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>올해 수당 지급완료된 대체휴가일수</inlineHelpText>
    <label>대체휴가 수당 지급일수</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_User__c.field-meta.xml
<CustomField>
    <fullName>Holiday_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>임직원</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Holiday</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/RewardHoliday__c/RewardHoliday__c.object-meta.xml
<CustomObject>
    <description>대체휴가 발생 이력 관리용 Object</description>
    <label>대체휴가</label>
    <nameField>
        <displayFormat>RH-{000000}</displayFormat>
        <label>대체휴가 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/RewardHoliday__c/fields/BenefitPaymentYn__c.field-meta.xml
<CustomField>
    <fullName>BenefitPaymentYn__c</fullName>
    <defaultValue>false</defaultValue>
    <label>수당 지급 여부</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/RewardHoliday__c/fields/Paid_Holiday__c.field-meta.xml
<CustomField>
    <fullName>Paid_Holiday__c</fullName>
    <label>수당지급된 휴가</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/RewardHoliday__c/fields/Remain_Holiday__c.field-meta.xml
<CustomField>
    <fullName>Remain_Holiday__c</fullName>
    <formula>OccurHoliday__c - Use_Holiday__c -  Paid_Holiday__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>잔여휴가</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/RewardHoliday__c/fields/WorkUser__c.field-meta.xml
<CustomField>
    <fullName>WorkUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>휴일근무자</description>
    <label>휴일근무자</label>
    <referenceTo>User</referenceTo>
    <relationshipName>HR_WorkUser</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/RewardHoliday_tr.cls
/**
 * Created by Kwanwoo.Jeon on 2023-12-14.
 */

public without sharing class RewardHoliday_tr extends TriggerHandler{
    private static List<RewardHoliday__c> listNew {get; set;}
    private static List<RewardHoliday__c> listOld {get; set;}
    private static Map<Id, RewardHoliday__c> mapNew {get; set;}
    private static Map<Id, RewardHoliday__c> mapOld {get; set;}

    public RewardHoliday_tr() {
        listNew = (List<RewardHoliday__c>) Trigger.new;
        listOld = (List<RewardHoliday__c>) Trigger.old;
        mapNew  = (Map<Id, RewardHoliday__c>) Trigger.newMap;
        mapOld  = (Map<Id, RewardHoliday__c>) Trigger.oldMap;
    }

    public override void beforeInsert() {
    }
    public override void beforeUpdate() {
        changeBenefitPayment();
    }
    public override void afterInsert() {
    }
    public override void afterUpdate() {

    }
    
    //수당지급 여부 체크 시 해당 값 Holiday 오브젝트에 수량 업로드
    //afterUpdate에서는 필드가 락걸려서 업데이트 불가능 BeforeUpdate로 변경해서 진행
    public void changeBenefitPayment(){
        Map<Id, Decimal> mapUserIdToRewardCount = new Map<Id, Decimal>();
        Map<Id, Decimal> mapUserIdToRewardCountCancel = new Map<Id, Decimal>();
        for (RewardHoliday__c obj: listNew){
            System.debug('BenefitPaymentYn__c :: ' + obj.BenefitPaymentYn__c);
            if (obj.BenefitPaymentYn__c != mapOld.get(obj.Id).BenefitPaymentYn__c) {
                if(obj.BenefitPaymentYn__c){
                    obj.Paid_Holiday__c = obj.Remain_Holiday__c;
                    mapUserIdToRewardCount.put(obj.WorkUser__c, mapUserIdToRewardCount.get(obj.WorkUser__c) == null ? obj.Paid_Holiday__c : mapUserIdToRewardCount.get(obj.WorkUser__c) + obj.Paid_Holiday__c);
                }else{
                    System.debug('Paid_Holiday__c :: ' + obj.Paid_Holiday__c);
                    mapUserIdToRewardCountCancel.put(obj.WorkUser__c, mapUserIdToRewardCountCancel.get(obj.WorkUser__c) == null ? obj.Paid_Holiday__c : mapUserIdToRewardCountCancel.get(obj.WorkUser__c) + obj.Paid_Holiday__c);
                    obj.Paid_Holiday__c = 0;
                }
            }
        }

        if (!mapUserIdToRewardCount.isEmpty() || !mapUserIdToRewardCountCancel.isEmpty()) {
            list<Holiday__c> listHoliday = new List<Holiday__c>([SELECT Holiday_User__c, Holiday_BenefitPaymentDays__c from Holiday__c where Holiday_User__c in :mapUserIdToRewardCount.keySet() OR Holiday_User__c in :mapUserIdToRewardCountCancel.keySet()]);
            if (!listHoliday.isEmpty()) {
                for (Holiday__c obj : listHoliday){
                    if (mapUserIdToRewardCount.get(obj.Holiday_User__c) != null) {
                        obj.Holiday_BenefitPaymentDays__c += mapUserIdToRewardCount.get(obj.Holiday_User__c);
                    }
                    if (mapUserIdToRewardCountCancel.get(obj.Holiday_User__c) != null) {
                        obj.Holiday_BenefitPaymentDays__c -= mapUserIdToRewardCountCancel.get(obj.Holiday_User__c);
                    }
                }
                update listHoliday;
            }

        }
    }
}