PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/Holiday__c.object-meta.xml
<CustomObject>
    <label>Holiday</label>
    <nameField>
        <displayFormat>H-{0000}</displayFormat>
        <label>Holiday No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_User__c.field-meta.xml
<CustomField>
    <fullName>Holiday_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>임직원</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Holiday</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/RewardHoliday__c/RewardHoliday__c.object-meta.xml
<CustomObject>
    <description>대체휴가 발생 이력 관리용 Object</description>
    <label>대체휴가</label>
    <nameField>
        <displayFormat>RH-{000000}</displayFormat>
        <label>대체휴가 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/RewardHoliday__c/fields/BenefitPaymentYn__c.field-meta.xml
<CustomField>
    <fullName>BenefitPaymentYn__c</fullName>
    <defaultValue>false</defaultValue>
    <label>수당 지급 여부</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/RewardHoliday__c/fields/WorkingDate__c.field-meta.xml
<CustomField>
    <fullName>WorkingDate__c</fullName>
    <label>근무일자</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/RewardHoliday__c/fields/WorkingTime__c.field-meta.xml
<CustomField>
    <fullName>WorkingTime__c</fullName>
    <label>근무시간</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0.5일 (4시간)</fullName>
            </value>
            <value>
                <fullName>1일 (8시간)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/RewardHoliday__c/fields/WorkUser__c.field-meta.xml
<CustomField>
    <fullName>WorkUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>휴일근무자</description>
    <label>휴일근무자</label>
    <referenceTo>User</referenceTo>
    <relationshipName>HR_WorkUser</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/RewardHoliday_tr_Test.cls
/**
 * Created by Kwanwoo.Jeon on 2023-12-21.
 */

@IsTest
private class RewardHoliday_tr_Test {
    @TestSetup
    static void setup(){
        User objUser = TestObjectCreator.objUser;
        insert objUser;
        
        Holiday__c objHoliday = TestObjectCreator.objHoliday;
        objHoliday.Holiday_User__c = objUser.Id;
        insert objHoliday;

        RewardHoliday__c objRewardHoliday = new RewardHoliday__c();
        objRewardHoliday.WorkUser__c = objUser.Id;
        objRewardHoliday.WorkingDate__c = Date.today();
        objRewardHoliday.WorkingTime__c = '0.5일 (4시간)';
        insert objRewardHoliday;
    }

    @IsTest
    static void testBehavior() {
        RewardHoliday__c objRewardHoliday = [SELECT id, BenefitPaymentYn__c FROM RewardHoliday__c WHERE BenefitPaymentYn__c = FALSE LIMIT 1];
        objRewardHoliday.BenefitPaymentYn__c = true;
        update objRewardHoliday;
    }
}