PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/Holiday__c.object-meta.xml
<CustomObject>
    <label>Holiday</label>
    <nameField>
        <displayFormat>H-{0000}</displayFormat>
        <label>Holiday No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/CarriedOverOfLastYear__c.field-meta.xml
<CustomField>
    <fullName>CarriedOverOfLastYear__c</fullName>
    <defaultValue>0</defaultValue>
    <description>대유넥스티어 연차 계산법 기준이 회계연도로 변경되어 필드 생성 (생성일: 2022-12-27, 생성자: hyunsoo.song@daeunextier.com)

* 필드 설명
이 필드는 매년 12월 31일 23시 00분에 &apos;HolidayLastYearUpdate 매년 12월 31일 업데이트&apos; 스케줄러로 업데이트됨.</description>
    <inlineHelpText>전년도에 발생한 연차일수</inlineHelpText>
    <label>전년도 연차일수</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_Calculated__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Calculated__c</fullName>
    <description>대유넥스티어 사내 규칙에 맞는 연차여부 필드 수정으로 인한 예시 변경(수정일: 2021-12-31, 수정자: cj.sohn@daeunextier.com)
* 연차여부 수식 수정:
입사기준일인 경우, 입사일 + 365일
연차기준일(2020. 1. 1)인 경우, 입사일 다음년도 (연차 기준일)월 (연차 기준일)일 - 1

필드 설명
연차여부가 TRUE일 때, 15일 + 추가연차일수
연차여부가 FALSE일 때, 12 - (입사월 + 1)
ex)  오늘 2022년 3월 17일
       사원A: 입사일 2020-03-17 → 연차적용시작일(2020-12-31) → 연차여부 = TRUE → 15 + 0 개
       사원B: 입사일 2021-12-07 → 연차적용시작일(2021-12-31) → 연차여부 = TRUE → 15 + 0 개
       사원C: 입사일 2022-01-01 → 연차적용시작일(2022-12-31) → 연차여부 = FALSE → 12 - 1 = 11개
       사원D: 입사일 2022-01-04 → 연차적용시작일(2022-12-31) → 연차여부 = FALSE → 12 - (1 + 1) = 10개

휴가 연차일수 부여 개편으로 인한 수정(필드 수식 수정일: 2021-01-12, 필드 수정자: cj.sohn@daeunextier.com)
연차여부 수식 수정 이전 예시:
ex)  오늘 2021년 2월 4일
       사원A: 입사일 2020-12-07 → 연차적용시작일(2021-01-01) → 연차여부 = TRUE → 15 + 0 개
       사원B: 입사일 2021-01-01 → 연차적용시작일(2022-01-01) → 연차여부 = FALSE → 12 - 1 = 11개
       사원C: 입사일 2021-01-04 → 연차적용시작일(2022-01-01) → 연차여부 = FALSE → 12 - (1 + 1) = 10개</description>
    <formula>IF(
	Holiday_IsAnnualleave__c,
	15 + MIN(Holiday_Additionaldays__c , 10 ),
        IF(
                DAY(Holiday_JoinDate__c) = 1,
                IF(
	        	12 - (MONTH(Holiday_JoinDate__c) + 1) &lt; 0, 
	        	1,
	        	12 - MONTH(Holiday_JoinDate__c)
        	),
               	IF(
	        	12 - (MONTH(Holiday_JoinDate__c) + 1) &lt; 0, 
	        	0,
	        	12 - (MONTH(Holiday_JoinDate__c) + 1)
        	)
        )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>연차일수</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_GivenHolidays__c.field-meta.xml
<CustomField>
    <fullName>Holiday_GivenHolidays__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>추가적으로 부여된 연월차일수</inlineHelpText>
    <label>추가 부여 일수</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_IsAnnualleave__c.field-meta.xml
<CustomField>
    <fullName>Holiday_IsAnnualleave__c</fullName>
    <formula>Holiday_StartDate__c &lt;=  TODAY()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>연차여부</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_JoinDate__c.field-meta.xml
<CustomField>
    <fullName>Holiday_JoinDate__c</fullName>
    <label>입사일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_LastActivity__c.field-meta.xml
<CustomField>
    <fullName>Holiday_LastActivity__c</fullName>
    <label>최종 사용 내역</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_NoticeLevel__c.field-meta.xml
<CustomField>
    <fullName>Holiday_NoticeLevel__c</fullName>
    <label>공지 단계</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Need</fullName>
                <default>true</default>
                <label>Not Need</label>
            </value>
            <value>
                <fullName>1st Notice</fullName>
            </value>
            <value>
                <fullName>2nd Notice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_PeriodEnd__c.field-meta.xml
<CustomField>
    <fullName>Holiday_PeriodEnd__c</fullName>
    <description>수식 필드에 대한 상세설명 작성(필드 상세설명 수정일: 2021-12-23, 수정자: cj.sohn@daeunextier.com)
1. 입사일 기준여부가 TRUE일 때,
1-1) 금연도 입사월일이 오늘보다 작을 때, 금연도 입사월일 - 1 + 365
1-2) 금연도 입사월일이 오늘보다 크거나 같을 때, 금연도 입사월일 -1 + 0

ex) 오늘: 2021년 12월 23일
사원A: 입사일 2019-12-15 →  금연도 입사월일 (2021-12-15) → 연차만료일: 2022-12-15
사원B: 입사일 2020-12-28 → 금연도 입사월일 (2021-12-28) → 연차만료일: 2021-12-28
사원C: 입사일 2021-12-23 →  금연도 입사월일 (2021-12-23) → 연차만료일: 2022-12-22

2. 입사일 기준여부가 FALSE일 때,
2-1) 금연도 말일이 오늘보다 클 때, 전연도 말일 + 365
2-2) 금연도 말일이 오늘보다 작거나 같을 때, 전연도 말일 + 0 (가능성 0%)

ex) 오늘: 2021년 2월 4일, 금연도 말일: 2021년 12월 31일 → 연차만료일: 2021년 12월 31일

* 참고사항
Custom Setting(HolidaySetting__c)의 필드 및 값 정리 (2021-12-23 기준)
- 연차기준일(HoldayRuleDate__c): 2000. 1. 1
- 갱신일 이전 일수 차감여부(IsCeil__c): true
- 입사일 기준여부(JoinDateRule__c): false</description>
    <formula>IF(
    $Setup.HolidaySetting__c.JoinDateRule__c,
    DATE( YEAR(TODAY()), MONTH(Holiday_JoinDate__c), DAY(Holiday_JoinDate__c) ) - 1 +
    IF(
        DATE( YEAR(TODAY()), MONTH(Holiday_JoinDate__c), DAY(Holiday_JoinDate__c) ) &lt; TODAY(),
        365,
        0
    ),
    DATE( YEAR(TODAY()), MONTH($Setup.HolidaySetting__c.HoldayRuleDate__c ), DAY($Setup.HolidaySetting__c.HoldayRuleDate__c) ) - 1 +
    IF(
        DATE( YEAR(TODAY()), MONTH($Setup.HolidaySetting__c.HoldayRuleDate__c), DAY($Setup.HolidaySetting__c.HoldayRuleDate__c) ) &lt; TODAY(),
        365,
        0
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>연차만료일</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_Remain__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Remain__c</fullName>
    <description>4월1일 이전인 경우, 잔여일수=연차일수-사용일수+전년도 연차 잔여일수
3월31일 이후인 경우, 잔여일수=연차일수-사용일수

22.03.31
임시로 기준일을 12월 31일로 변경
변경전: TODAY() &lt;  DATE(YEAR(TODAY()), 4, 1)
변경후: TODAY() &lt;=  DATE(YEAR(TODAY()), 12, 31)</description>
    <formula>IF(
    TODAY() &lt;  DATE(YEAR(TODAY()), 4, 1),
    NULLVALUE( Holiday_Calculated__c , 0) -  NULLVALUE(Holiday_UseDays__c  , 0) +  Holiday_GivenHolidays__c + RemainOfLastYear__c ,
    NULLVALUE( Holiday_Calculated__c , 0) -  NULLVALUE(Holiday_UseDays__c  , 0) +  Holiday_GivenHolidays__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>전년도 잔여연차 사용을 임시로 올해 12월 31일까지 사용 가능하도록 변경되었습니다.</inlineHelpText>
    <label>잔여일수</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_UseDays__c.field-meta.xml
<CustomField>
    <fullName>Holiday_UseDays__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>올해 연월차 사용일수</inlineHelpText>
    <label>연월차 사용일수</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_User__c.field-meta.xml
<CustomField>
    <fullName>Holiday_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>임직원</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Holiday</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_WorkingYears__c.field-meta.xml
<CustomField>
    <fullName>Holiday_WorkingYears__c</fullName>
    <description>입사일 기준 근속 년수</description>
    <formula>YEAR(TODAY()) - YEAR(Holiday_JoinDate__c) 
+ IF(
   MONTH(TODAY()) * 100 + DAY(TODAY()) &gt;= 
   MONTH(Holiday_JoinDate__c) * 100 + 
   DAY( Holiday_JoinDate__c) 
   , 0 
   , -1
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>근속연수</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/UseDaysOfLastYear__c.field-meta.xml
<CustomField>
    <fullName>UseDaysOfLastYear__c</fullName>
    <defaultValue>0</defaultValue>
    <description>대유넥스티어 연차 계산법 기준이 회계연도로 변경되어 필드 생성 (생성일: 2022-12-27, 생성자: hyunsoo.song@daeunextier.com)

* 필드 설명
이 필드는 매년 12월 31일 23시 00분에 &apos;HolidayLastYearUpdate 매년 12월 31일 업데이트&apos; 스케줄러로 업데이트됨.</description>
    <inlineHelpText>전년도에 발생한 연월차 사용일수 - 전년도 추가부여일수</inlineHelpText>
    <label>전년도 연월차 사용일수</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidaySetting__c/HolidaySetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>휴일관리 기준 설정</description>
    <label>HolidaySetting</label>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/HolidaySetting__c/fields/IsCeil__c.field-meta.xml
<CustomField>
    <fullName>IsCeil__c</fullName>
    <defaultValue>true</defaultValue>
    <description>값이 True일 경우 연차 기준일 당시 만근을 하지 않아도 연차를 가산 및 이전 사용일수를 초기화 한다.
false일 경우 연차 기준일 당신 만근이 아니면 연차를 가산하지 않고 1년 근속 미만일 경우 사용일수를 초기화 하지 않는다
예) 올림일 경우 전년도 4월 입사자는 연차사용일수가 초기화 되고
전전년도 4월 입사자는 연차가 16일로 1일 가산 된다.
내림일 경우 전년도 4월 입사자는 연차일수가 초기화 되지 않고
전전년도 4월 입사자는 연차가 15일로 1일 가산은 다음해로 넘어간다.</description>
    <label>갱신일 이전 일수 차감여부</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidaySetting__c/fields/JoinDateRule__c.field-meta.xml
<CustomField>
    <fullName>JoinDateRule__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True일경우 입사일 기준으로 연차 생성 및 사용연차를 갱신한다.
False일경우 특정일 기준으로 연차 생성 및 사용연차를 갱신한다.</description>
    <label>입사일 기준여부</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/HolidayUpdateStatusBatch.cls
/**
 * @description       : 1) 사용일자 리셋
 *                      2) 1차 촉진 메일 대상자에 대한 NoticeLevel Update
 *                      3) 2차 촉진 메일 대상자에 대한 NoticeLevel Update
 *                      4) 추가 부여 일수 리셋
 *                      5) 신규 입사자 대상 Holiday__c 레코드 생성
 *                      6) 전년도 연차일수 및 전년도 연차 사용일수 초기화
 * @author            : 알 수 없음
 * Modifications Log
 * Ver   Date         Author                    Modification
 * 2.0   2021.01.12   CJ.Sohn                   Modified(추가 부여 일수 초기화)
**/
global class HolidayUpdateStatusBatch implements Database.Batchable<sObject> {

    global String query;

    global database.querylocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope){
        /*
        1. 사용일자 리셋
        2. 1차 촉진 메일
        3. 2차 만료 메일
        
        date today = system.today();
        date firstDate = system.today().addMonth(6).addDay(10);
        date secondDate = system.today().addMonth(2);
        string todayStr = string.valueOf(today.year()) + '-' + string.valueOf(today.month()) + '-' + string.valueOf(today.day());
        string firstDateStr = string.valueOf(firstDate.year()) + '-' + firstDate.valueOf(today.month()) + '-' + string.valueOf(firstDate.day());
        string secondDateStr = string.valueOf(secondDate.year()) + '-' + string.valueOf(secondDate.month()) + '-' + string.valueOf(secondDate.day());
        string query  = ' SELECT Holiday_User__c,Holiday_JoinDate__c, Holiday_IsAnnualleave__c,Holiday_PeriodEnd__c,Holiday_Calculated__c,Holiday_GivenHolidays__c,Holiday_UseDays__c,Holiday_Remain__c ';
        query += ' FROM Holiday__c ';
        query += ' where Holiday_PeriodEnd__c in( ' + todayStr + ' ,  ' + firstDateStr  + ' , ' + secondDateStr   + ' )';
        */
        list<Holiday__c> hldLst = (list<Holiday__c>)scope;
        list<Holiday__c> updateLst = new list<Holiday__c>();
        date today = system.today();
        date firstDate = today.addMonths(6).addDays(10);
        date secondDate = today.addMonths(2);
        HolidaySetting__c hs = HolidaySetting__c.getOrgDefaults();
        for(Holiday__c h : hldLst){
            //  만료일자가 오늘이고 (입사일기준이거나) 또는(입사일 기준이면서 올림이거나) 또는 (입사일 기준 내림이면서 근속 1년이상) 인경우만
            if(h.Holiday_PeriodEnd__c == today && (hs.JoinDateRule__c || (!hs.JoinDateRule__c && hs.IsCeil__c) || (!hs.JoinDateRule__c && !hs.IsCeil__c && h.Holiday_WorkingYears__c > 0))){
                decimal useDay = 0;
                //  string actStr = 'Reset use days.';
                /**
                 * @author            : cj.sohn@daeunextier.com
                 * @description       : 추가 부여 일수 초기화
                 * @last modified on  : 2021-01-12
                **/
                Decimal givenHolidays = 0;
                String actStr = 'Reset use days and given holidays.';
                h.Holiday_GivenHolidays__c = givenHolidays;
                /** ===============================END=============================== **/
                /**
                 * @author            : cj.sohn@daeunextier.com
                 * @description       : 전년도 연차일수 및 전년도 연차 사용일수 초기화
                 * @last modified on  : 2021-12-28
                */
                if(h.Holiday_PeriodEnd__c == today){
                    h.CarriedOverOfLastYear__c = 0;
                    h.UseDaysOfLastYear__c = 0;
                    if(h.Holiday_Remain__c > 0) {
                        h.CarriedOverOfLastYear__c = h.Holiday_Remain__c;
                    }
                }
                /** ===============================END=============================== **/
                if(h.Holiday_Remain__c < 0){
                    useDay = h.Holiday_Remain__c * -1;
                    actStr = string.valueOf(useDay) + 'Day(s) move to this year.';
                }
                h.Holiday_UseDays__c = useDay ;
                h.Holiday_LastActivity__c = actStr ;
                h.Holiday_NoticeLevel__c = 'Not Need';

                updateLst.add(h);
            }
            else if(h.Holiday_PeriodEnd__c == firstDate){
                //User usr = [SELECT Email,Name FROM User WHERE Id = :h.Holiday_User__c];
                //HolidayUtil.sendEmail('1st', usr, h);
                h.Holiday_NoticeLevel__c = '1st Notice';
                updateLst.add(h);
            }
            else if(h.Holiday_PeriodEnd__c == secondDate){
                //User usr = [SELECT Email,Name FROM User WHERE Id = :h.Holiday_User__c];
                //HolidayUtil.sendEmail('2nd', usr, h);
                h.Holiday_NoticeLevel__c = '2nd Notice';
                updateLst.add(h);
            }
        }
        update updateLst;
    }

    global void finish(Database.BatchableContext BC){
        /**
             * @author            : cj.sohn@daeunextier.com
             * @description       : 신규 입사자에 대한 Holiday__c Record 부여
             * @last modified on  : 2021-01-12
            **/
        HolidayManageController.doCreate();
        /** ===============================END=============================== **/
    }
}