PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/Holiday__c.object-meta.xml
<CustomObject>
    <label>Holiday</label>
    <nameField>
        <displayFormat>H-{0000}</displayFormat>
        <label>Holiday No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/CarriedOverOfLastYear__c.field-meta.xml
<CustomField>
    <fullName>CarriedOverOfLastYear__c</fullName>
    <defaultValue>0</defaultValue>
    <description>대유넥스티어 연차 계산법 기준이 회계연도로 변경되어 필드 생성 (생성일: 2022-12-27, 생성자: hyunsoo.song@daeunextier.com)

* 필드 설명
이 필드는 매년 12월 31일 23시 00분에 &apos;HolidayLastYearUpdate 매년 12월 31일 업데이트&apos; 스케줄러로 업데이트됨.</description>
    <inlineHelpText>전년도에 발생한 연차일수</inlineHelpText>
    <label>전년도 연차일수</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_Annual_Calculated__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Annual_Calculated__c</fullName>
    <description>대유넥스티어 연차 계산법 기준이 회계연도로 변경되어 새로운 연차일수 계산 필드 생성 (생성일: 2022-12-27, 생성자: hyunsoo.song@daeunextier.com)

* 필드 설명 
- 1월 1일에 연차 일괄 부여
월차만료일 존재 X -&gt; 기존입사자 : 연차일수 15개 + 추가 연차일수
월차만료일 존재 -&gt; 신규입사자 : 반올림((12.31 - 입사월일)/365*15) 

ex1) 오늘 2023년 1월 1일
사원A: 입사일 2022-05-16 → 월차만료일 존재 → 입사월일(05.16~12.31)/365*15 → 10개
사원C: 입사일 2022-01-01 → 월차만료일 존재 X → 15 + 0 → 15개
사원D: 입사일 2019-09-04 → 월차만료일 존재 X → 15 + 1 → 16개

ex2) 오늘 2022년 12월 27일
사원A: 입사일 2022-05-16 -&gt; 월차만료일 존재 -&gt; 0개</description>
    <formula>IF(
    ISNULL(Holiday_Monthly_Period__c),
    15 + MIN(Holiday_Additionaldays__c, 10),
    IF(
        DATE(YEAR(Holiday_JoinDate__c) + 1, 1, 1) &lt;= TODAY(),
        CEILING((DATE(YEAR(Holiday_JoinDate__c), 12, 31) - Holiday_JoinDate__c + 1 ) / 365 * 15), 0
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>올해 발생한 연차일수</inlineHelpText>
    <label>올해 연차일수</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_Calculated__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Calculated__c</fullName>
    <description>대유넥스티어 사내 규칙에 맞는 연차여부 필드 수정으로 인한 예시 변경(수정일: 2021-12-31, 수정자: cj.sohn@daeunextier.com)
* 연차여부 수식 수정:
입사기준일인 경우, 입사일 + 365일
연차기준일(2020. 1. 1)인 경우, 입사일 다음년도 (연차 기준일)월 (연차 기준일)일 - 1

필드 설명
연차여부가 TRUE일 때, 15일 + 추가연차일수
연차여부가 FALSE일 때, 12 - (입사월 + 1)
ex)  오늘 2022년 3월 17일
       사원A: 입사일 2020-03-17 → 연차적용시작일(2020-12-31) → 연차여부 = TRUE → 15 + 0 개
       사원B: 입사일 2021-12-07 → 연차적용시작일(2021-12-31) → 연차여부 = TRUE → 15 + 0 개
       사원C: 입사일 2022-01-01 → 연차적용시작일(2022-12-31) → 연차여부 = FALSE → 12 - 1 = 11개
       사원D: 입사일 2022-01-04 → 연차적용시작일(2022-12-31) → 연차여부 = FALSE → 12 - (1 + 1) = 10개

휴가 연차일수 부여 개편으로 인한 수정(필드 수식 수정일: 2021-01-12, 필드 수정자: cj.sohn@daeunextier.com)
연차여부 수식 수정 이전 예시:
ex)  오늘 2021년 2월 4일
       사원A: 입사일 2020-12-07 → 연차적용시작일(2021-01-01) → 연차여부 = TRUE → 15 + 0 개
       사원B: 입사일 2021-01-01 → 연차적용시작일(2022-01-01) → 연차여부 = FALSE → 12 - 1 = 11개
       사원C: 입사일 2021-01-04 → 연차적용시작일(2022-01-01) → 연차여부 = FALSE → 12 - (1 + 1) = 10개</description>
    <formula>IF(
	Holiday_IsAnnualleave__c,
	15 + MIN(Holiday_Additionaldays__c , 10 ),
        IF(
                DAY(Holiday_JoinDate__c) = 1,
                IF(
	        	12 - (MONTH(Holiday_JoinDate__c) + 1) &lt; 0, 
	        	1,
	        	12 - MONTH(Holiday_JoinDate__c)
        	),
               	IF(
	        	12 - (MONTH(Holiday_JoinDate__c) + 1) &lt; 0, 
	        	0,
	        	12 - (MONTH(Holiday_JoinDate__c) + 1)
        	)
        )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>연차일수</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_FamilyEvent_Count__c.field-meta.xml
<CustomField>
    <fullName>Holiday_FamilyEvent_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>경조휴가</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_GivenHolidays__c.field-meta.xml
<CustomField>
    <fullName>Holiday_GivenHolidays__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>추가적으로 부여된 연월차일수</inlineHelpText>
    <label>추가 부여 일수</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_IsAnnualleave__c.field-meta.xml
<CustomField>
    <fullName>Holiday_IsAnnualleave__c</fullName>
    <formula>Holiday_StartDate__c &lt;=  TODAY()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>연차여부</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_JoinDate__c.field-meta.xml
<CustomField>
    <fullName>Holiday_JoinDate__c</fullName>
    <label>입사일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_LastActivity__c.field-meta.xml
<CustomField>
    <fullName>Holiday_LastActivity__c</fullName>
    <label>최종 사용 내역</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_Monthly_Calculated__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Monthly_Calculated__c</fullName>
    <description>대유넥스티어 연차 계산법 기준이 회계연도로 변경되어 필드 생성 (생성일: 2022-12-27, 생성자: hyunsoo.song@daeunextier.com)

* 필드 설명
1. 입사 1년차 이상 (월차 만료일 == BLANK || 전년도 월차일수 == 11개)
: 0

2. 신규입사자
: 입사연도 다음 해로 변경될 시 다시 1부터 Count (단, 입사일자의 DAY에 해당하는 일자 하루 전 날 부여됨)

ex) 오늘 2023년 01월 13일
사원A: 입사일 2022-05-16 → 월차 만료일(2023-12-31) →  0개	(매달 15일에 월차 부여)
사원B: 입사일 2022-12-13 → 월차 만료일(2023-12-31) → 1개 	(매달 12일에 월차 부여)

사원C: 입사일 2022-01-01 → 월차 만료일(2023-12-31) → 0개	(전년도 월차 11개, 올해 월차 0개)
사원D: 입사일 2021-09-04 → 월차 만료일(BLANK) → 0개</description>
    <formula>IF(
    ISBLANK(Holiday_Monthly_Period__c) || MonthlyOfLastYear__c = 11, 0,
    IF(
        YEAR(Holiday_Monthly_Period__c) = YEAR(TODAY()),
        11 - MonthlyOfLastYear__c,
        IF(
            FLOOR((DATE(YEAR(TODAY()), 12, 31) - Holiday_JoinDate__c - 1) / 30) &gt; 11,
            11,
            FLOOR((DATE(YEAR(TODAY()), 12, 31) - Holiday_JoinDate__c - 1) / 30)
        )
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>올해 발생한 월차일수 (월차는 입사일에 해당하는 일자 하루 전 날 부여됩니다.)</inlineHelpText>
    <label>올해 월차일수</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_NoticeLevel__c.field-meta.xml
<CustomField>
    <fullName>Holiday_NoticeLevel__c</fullName>
    <label>공지 단계</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Need</fullName>
                <default>true</default>
                <label>Not Need</label>
            </value>
            <value>
                <fullName>1st Notice</fullName>
            </value>
            <value>
                <fullName>2nd Notice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_PeriodEnd__c.field-meta.xml
<CustomField>
    <fullName>Holiday_PeriodEnd__c</fullName>
    <description>수식 필드에 대한 상세설명 작성(필드 상세설명 수정일: 2021-12-23, 수정자: cj.sohn@daeunextier.com)
1. 입사일 기준여부가 TRUE일 때,
1-1) 금연도 입사월일이 오늘보다 작을 때, 금연도 입사월일 - 1 + 365
1-2) 금연도 입사월일이 오늘보다 크거나 같을 때, 금연도 입사월일 -1 + 0

ex) 오늘: 2021년 12월 23일
사원A: 입사일 2019-12-15 →  금연도 입사월일 (2021-12-15) → 연차만료일: 2022-12-15
사원B: 입사일 2020-12-28 → 금연도 입사월일 (2021-12-28) → 연차만료일: 2021-12-28
사원C: 입사일 2021-12-23 →  금연도 입사월일 (2021-12-23) → 연차만료일: 2022-12-22

2. 입사일 기준여부가 FALSE일 때,
2-1) 금연도 말일이 오늘보다 클 때, 전연도 말일 + 365
2-2) 금연도 말일이 오늘보다 작거나 같을 때, 전연도 말일 + 0 (가능성 0%)

ex) 오늘: 2021년 2월 4일, 금연도 말일: 2021년 12월 31일 → 연차만료일: 2021년 12월 31일

* 참고사항
Custom Setting(HolidaySetting__c)의 필드 및 값 정리 (2021-12-23 기준)
- 연차기준일(HoldayRuleDate__c): 2000. 1. 1
- 갱신일 이전 일수 차감여부(IsCeil__c): true
- 입사일 기준여부(JoinDateRule__c): false</description>
    <formula>IF(
    $Setup.HolidaySetting__c.JoinDateRule__c,
    DATE( YEAR(TODAY()), MONTH(Holiday_JoinDate__c), DAY(Holiday_JoinDate__c) ) - 1 +
    IF(
        DATE( YEAR(TODAY()), MONTH(Holiday_JoinDate__c), DAY(Holiday_JoinDate__c) ) &lt; TODAY(),
        365,
        0
    ),
    DATE( YEAR(TODAY()), MONTH($Setup.HolidaySetting__c.HoldayRuleDate__c ), DAY($Setup.HolidaySetting__c.HoldayRuleDate__c) ) - 1 +
    IF(
        DATE( YEAR(TODAY()), MONTH($Setup.HolidaySetting__c.HoldayRuleDate__c), DAY($Setup.HolidaySetting__c.HoldayRuleDate__c) ) &lt; TODAY(),
        365,
        0
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>연차만료일</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_PublicWorks_Count__c.field-meta.xml
<CustomField>
    <fullName>Holiday_PublicWorks_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>공가 사용일수</description>
    <label>공가</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_Remain__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Remain__c</fullName>
    <description>4월1일 이전인 경우, 잔여일수=연차일수-사용일수+전년도 연차 잔여일수
3월31일 이후인 경우, 잔여일수=연차일수-사용일수

22.03.31
임시로 기준일을 12월 31일로 변경
변경전: TODAY() &lt;  DATE(YEAR(TODAY()), 4, 1)
변경후: TODAY() &lt;=  DATE(YEAR(TODAY()), 12, 31)</description>
    <formula>IF(
    TODAY() &lt;  DATE(YEAR(TODAY()), 4, 1),
    NULLVALUE( Holiday_Calculated__c , 0) -  NULLVALUE(Holiday_UseDays__c  , 0) +  Holiday_GivenHolidays__c + RemainOfLastYear__c ,
    NULLVALUE( Holiday_Calculated__c , 0) -  NULLVALUE(Holiday_UseDays__c  , 0) +  Holiday_GivenHolidays__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>전년도 잔여연차 사용을 임시로 올해 12월 31일까지 사용 가능하도록 변경되었습니다.</inlineHelpText>
    <label>잔여일수</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_SickLeave_Count__c.field-meta.xml
<CustomField>
    <fullName>Holiday_SickLeave_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>병가 사용 횟수</description>
    <label>병가</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_Total_Remain__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Total_Remain__c</fullName>
    <description>대유넥스티어 연차 계산법 기준이 회계연도로 변경되어 필드 생성 (생성일: 2022-12-27, 생성자: hyunsoo.song@daeunextier.com)

* 필드 설명
- 신규 입사자 &amp; 기존 입사자
: 올해 월차일수 + 올해 연차일수 + 전년도 연차 잔여일수 + 추가부여일수 - 사용일수</description>
    <formula>BLANKVALUE(Holiday_Monthly_Calculated__c, 0) +  BLANKVALUE(Holiday_Annual_Calculated__c, 0) + BLANKVALUE(HolidayRemainOfLastYear__c, 0) +  Holiday_GivenHolidays__c
-  Holiday_UseDays__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>총 연월차일수 + 추가 부여 일수 - 연월차 사용일수</inlineHelpText>
    <label>연월차 잔여일수</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_Uncountable__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Uncountable__c</fullName>
    <defaultValue>0</defaultValue>
    <label>공무</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_Unpaid__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Unpaid__c</fullName>
    <defaultValue>0</defaultValue>
    <label>무급휴가</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_UseDays__c.field-meta.xml
<CustomField>
    <fullName>Holiday_UseDays__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>올해 연월차 사용일수</inlineHelpText>
    <label>연월차 사용일수</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_User__c.field-meta.xml
<CustomField>
    <fullName>Holiday_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>임직원</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Holiday</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_WomenHoliday_Count__c.field-meta.xml
<CustomField>
    <fullName>Holiday_WomenHoliday_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>생리휴가 사용일수</description>
    <label>생리휴가</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_WorkingYears__c.field-meta.xml
<CustomField>
    <fullName>Holiday_WorkingYears__c</fullName>
    <description>입사일 기준 근속 년수</description>
    <formula>YEAR(TODAY()) - YEAR(Holiday_JoinDate__c) 
+ IF(
   MONTH(TODAY()) * 100 + DAY(TODAY()) &gt;= 
   MONTH(Holiday_JoinDate__c) * 100 + 
   DAY( Holiday_JoinDate__c) 
   , 0 
   , -1
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>근속연수</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/RemainOfLastYear__c.field-meta.xml
<CustomField>
    <fullName>RemainOfLastYear__c</fullName>
    <formula>CarriedOverOfLastYear__c - UseDaysOfLastYear__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>전년도 연차 잔여일수</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/UseDaysOfLastYear__c.field-meta.xml
<CustomField>
    <fullName>UseDaysOfLastYear__c</fullName>
    <defaultValue>0</defaultValue>
    <description>대유넥스티어 연차 계산법 기준이 회계연도로 변경되어 필드 생성 (생성일: 2022-12-27, 생성자: hyunsoo.song@daeunextier.com)

* 필드 설명
이 필드는 매년 12월 31일 23시 00분에 &apos;HolidayLastYearUpdate 매년 12월 31일 업데이트&apos; 스케줄러로 업데이트됨.</description>
    <inlineHelpText>전년도에 발생한 연월차 사용일수 - 전년도 추가부여일수</inlineHelpText>
    <label>전년도 연월차 사용일수</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/HolidayController.cls
/**
 * Component Name                : MyHolidayInfoLightning.cmp
 * Component Controller          : MyHolidayInfoLightningController.js
 * Component Helper              : MyHolidayInfoLightningHelper.js
 * Component Contorlller Class   : HolidayController.cls
 * Test Class                    : HolidayController_Test.cls
 * Description                   : 휴가정보 Detail Class
 * Modification Log
 * ===============================================================
 * Ver     Date          Author           Modification
 * ===============================================================
   1.0   2018.08.27     MH.Kwak           Create
   2.0	 2019.04.12		JK.LEE			  Modified
   3.0   2021.12.28		CJ.Sohn           Holiday 조회하는 SOQL에서 전년도 연차일수 관련 필드 추가
*/


public without sharing class HolidayController{


	//Parent Role Id 체크
	public static Set<Id> getRoleId(Set<Id> listRoleIds , List<UserRole> listUserRole){
		Set<Id> currentIds = new Set<Id>();

		for (Id objIds : listRoleIds) {
			for (UserRole objUserRole : listUserRole) {
				if (objUserRole.ParentRoleId == objIds) {
					currentIds.add(objUserRole.Id);
					//Parent Role == 현재 유저 Role Id 랑 같은 경우
				}
			}
		}

		if (!currentIds.isEmpty()) {
			currentIds.addAll(getRoleId(currentIds, listUserRole));
		}

		system.debug('currentIds :' + currentIds);
		return currentIds;
	}


	//모든 Parent Role 조회
	/*
    public static Set<ID> getParentRoleId(Set<ID> roleIds) {

        Set<ID> currentRoleIds = new Set<ID>();
    
        
        for(UserRole ur :[select Id, ParentRoleId from UserRole where Id IN: roleIds]) {
            currentRoleIds.add(ur.ParentRoleId);
        }
    
        if(!currentRoleIds.isEmpty()) {
            currentRoleIds.addAll(getParentRoleId(currentRoleIds));
        }
    
        return currentRoleIds;
    }
	*/
	

	@AuraEnabled
	public static boolean getPermissionCheck(String userId){
		//리턴해 Permission 체크할 값
		Boolean holidayCheck = true;
		
		//1. 세션아이디로 User Role 조회
		//2. ParentRoleID를 조회해 
		//3. UserRole -> Role LIst 에 담아
		//4. UserId ->  ParentRoldId  조회
		//5. 자기 Role 아래에 있는 모든 RoleId  userRole id 쿼리
		//6. Where 절에 HAs RecordId 넣는다
		//7. 같은 Role 또는 본인이 아닌 조건
		//8. 생성자가 나인 조건 

		//현재 접속중인 세션 ID
		String systemUserId = UserInfo.getUserId();

		//현재 접속중인 Role ID
		Id roleId = UserInfo.getUserRoleId();
		Set<Id> listRoleIds = new Set<Id>();
		listRoleIds.add(roleId);

		//현재 접속중인 프로필
		User sessionProfile = [SELECT Id, Profile.Name FROM USER WHERE Id=: systemUserId ];
		String profileName = sessionProfile.Profile.Name;

		//모든 Role을 조회
        List<UserRole> listAllUserRole = [SELECT Id, ParentRoleId FROM UserRole];
        //해당 Role ID가 Role ID 값을 조회해 ParentRoleId 인지 조회
		Set<Id> listIdsRoleId = getRoleId(listRoleIds, listAllUserRole);

		////모든 Parent role 조회 
		//Set<Id> listParentRoleIds = getParentRoleId(listRoleIds);

		//HasRecordId로 불러온 유저
		User objHasRecIdUser = [SELECT Id, UserRoleId FROM User WHERE Id =: userId];

		//HasRecordId 유저의 Role 조회
       	//List<UserRole> listUserRole = [SELECT Id, ParentRoleId FROM UserRole WHERE Id =: objHasRecIdUser.UserRoleId];

		//Session Role과 HasRecord Role Id 가 같으면 안보이게.

		if (!listIdsRoleId.isEmpty()) {
			for (Id objRoleId : listIdsRoleId) {
				if (profileName == 'System Administrator' || profileName == 'System Admin') {
					holidayCheck = true;
				} else if (systemUserId == userId) {
					holidayCheck = true;
				} else if (objRoleId == objHasRecIdUser.UserRoleId) {
					holidayCheck = true;
				} else {
					holidayCheck = false;
				}
			}
		} else if (systemUserId == userId) {
			holidayCheck = true;
		} else {
			holidayCheck = false;
		}

		return holidayCheck;
	}

	@AuraEnabled
	public static List<Holiday__c> getHoliday(String userId) {
		List<Holiday__c> holiday = [SELECT Id, Holiday_NoticeLevel__c, Holiday_JoinDate__c, Holiday_LastActivity__c ,Holiday_WorkingYears__c, Holiday_PeriodEnd__c,
										   Holiday_IsAnnualleave__c, Holiday_Calculated__c, Holiday_GivenHolidays__c, Holiday_UseDays__c, Holiday_Remain__c,
										   Holiday_Uncountable__c, Holiday_Unpaid__c, CarriedOverOfLastYear__c, UseDaysOfLastYear__c, RemainOfLastYear__c,
										   Holiday_User__r.id, Holiday_User__c, Holiday_User__r.UserRole.Name, Holiday_User__r.ManagerId, Holiday_Monthly_Calculated__c,
										   Holiday_Annual_Calculated__c, Holiday_Total_Remain__c, Holiday_FamilyEvent_Count__c, Holiday_SickLeave_Count__c,
										   Holiday_WomenHoliday_Count__c, Holiday_PublicWorks_Count__c, MonthlyOfLastYear__c, HolidayRemainOfLastYear__c, Holiday_rewardDays__c,
										   Holiday_Total_Count__c, fm_Holiday_rewardRemainDays__c, Holiday_reward_Total_Count__c, Holiday_BenefitPaymentDays__c,
									       RewardHolidayTotalOfLastYear__c, RewardHolidayUseDaysOfLastYear__c, RewardHolidayRemainOfLastYear__c, RewardHolidayPaymentDaysOfLastYear__c

							FROM Holiday__c 
							WHERE Holiday_User__c =: userId
							//OR Holiday_User__r.UserRole.ParentRoleId =: users.ParentRoleId;
							];
		system.debug('holiday : ' + holiday);

		return holiday;								
	}

	@AuraEnabled
	public static List<HolidayAction__c> getHolidayAction(String userId, Boolean holidayPerm) {

		String systemUserId = UserInfo.getUserId();	
		User users  = [SELECT Id , UserRoleId, UserRole.Name, UserRole.ParentRoleId FROM USER WHERE Id =: systemUserId ];

		String strQry = 'SELECT Id, name, CreatedDate, HolidayAction_Type__c, HolidayAction_IsConfirm__c, ';
			   strQry +='HolidayAction_Approver__r.LastName, CreatedById, HolidayAction_Days__c,FirstHolidayRequest__c, SecondApproverRequest__c,';
//			   strQry +='FirstHolidayRequest__r.Name, SecondApproverSelection__c, HolidayAction_Parent__r.Holiday_User__c ';
		       strQry +='FirstHolidayRequest__r.Name, SecondApproverRequest__r.Name, HolidayAction_Parent__r.Holiday_User__c ';
			   strQry +='FROM HolidayAction__c ';

		List<HolidayAction__c> holidayAction = Database.query(strQry);

		//권한이 있는 경우 모두 조회
		if(holidayPerm){			
			strQry += 'WHERE HolidayAction_Parent__r.Holiday_User__c  = ' + '\'' + userId + '\' ';
			strQry += 'ORDER BY CreatedDate DESC';
			system.debug('1. isAccessible------------------------');
		}else{

		/*
		권한이 없는 경우 
		1. CreatedById 가 세션 유저  
		2. 레코드 Owner가 HasrecordId 유저
		3. 승인된 레코드는 보이지 않는다. 
		*/
			system.debug('2. isAccessible------------------------');
			strQry += 'WHERE CreatedById = ' + '\'' + systemUserId  + '\'  AND OwnerId  = ' + '\'' + userId  + '\' ' + ' AND HolidayAction_IsConfirm__c = false ';					
			strQry += 'ORDER BY CreatedDate DESC';
		}

		List<HolidayAction__c> returnStrQry = Database.query(strQry);
		system.debug('returnStrQry : '+returnStrQry);

		return returnStrQry;
	}


	@AuraEnabled
	public static List<Holiday__History> getHolidayHistory(String userId) {
		List<Holiday__c> h = [SELECT Id, Holiday_Calculated__c, Holiday_GivenHolidays__c, Holiday_IsAnnualleave__c, Holiday_JoinDate__c, Holiday_LastActivity__c,
									Holiday_NoticeLevel__c, Holiday_PeriodEnd__c, Holiday_Remain__c, Holiday_Uncountable__c, Holiday_Unpaid__c, Holiday_UseDays__c,
									Holiday_User__c, Holiday_WorkingYears__c, CarriedOverOfLastYear__c, UseDaysOfLastYear__c, RemainOfLastYear__c, Holiday_Monthly_Calculated__c,
									Holiday_Annual_Calculated__c, Holiday_Total_Remain__c, Holiday_FamilyEvent_Count__c, Holiday_SickLeave_Count__c, Holiday_WomenHoliday_Count__c,
									Holiday_PublicWorks_Count__c, MonthlyOfLastYear__c, HolidayRemainOfLastYear__c, Holiday_rewardDays__c, Holiday_Total_Count__c, fm_Holiday_rewardRemainDays__c,
									Holiday_reward_Total_Count__c, Holiday_BenefitPaymentDays__c
							FROM Holiday__c 
							WHERE Holiday_User__c = :userId limit 1];
		string hldId;
		for(Holiday__c objHoliday : h) {
			if(!h.isEmpty()) {
				hldId = objHoliday.Id;
			}
		}

		List<Holiday__History> returnHistoryInfo = [SELECT CreatedBy.Name, CreatedDate, Field, Id, NewValue, OldValue FROM Holiday__History WHERE ParentId = :hldId ORDER BY CreatedDate DESC Limit 50];
		system.debug('returnHistoryInfo =' + returnHistoryInfo);

		return returnHistoryInfo;
	}

	/*
	@AuraEnabled
	public static List<User> getUserCreatedDate(String userId){
		//String userId = UserInfo.getUserId();
		List<User> UserCreatedDate = [SELECT Id, CreatedDate 
		                              FROM User 
		                              WHERE Id NOT IN (SELECT Holiday_User__c FROM Holiday__c) 
		                              AND IsActive = true 
		                              AND UserType = 'Standard'];
		return UserCreatedDate;

	}
	

	@AuraEnabled
	public static List<ProcessInstance> getProcessInstance(String recordId){
  		system.debug('recordId :: ' + recordId);
		String userId = UserInfo.getUserId();
		//ProcessInstance Object에서 
		Id searchId = Id.valueOf(recordId);
		List<ProcessInstance> returnProcessInstance= [SELECT Id,ProcessDefinitionId,TargetObjectId,TargetObject.name
		 FROM ProcessInstance where TargetObjectId in (select id from HolidayAction__c where id=:searchId)];
		 return returnProcessInstance;
	}
	*/


	@AuraEnabled
    public static Map<String, String> getObjectFieldLabel(String sObjectName) {
		Schema.SObjectType schemaObject = Schema.getGlobalDescribe().get(sObjectName); 
		Schema.DescribeSobjectResult schemaObjectResult = schemaObject.getDescribe();
		Map<String, Schema.SObjectField> mapSchemaObjectResult = schemaObjectResult.fields.getMap();        

		Map<String, String> mapFieldLabel = new Map<String, String>();
		for(Schema.SObjectField obj : mapSchemaObjectResult.values()){                            
			Schema.DescribeFieldResult f = mapSchemaObjectResult.get(obj.getDescribe().getName()).getDescribe();
			system.debug('mapFieldLabel :: ' + mapFieldLabel);
			mapFieldLabel.put(f.getName(), f.getLabel());
		}

		return mapFieldLabel;
	}
}