PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/Holiday__c.object-meta.xml
<CustomObject>
    <label>Holiday</label>
    <nameField>
        <displayFormat>H-{0000}</displayFormat>
        <label>Holiday No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/CarriedOverOfLastYear__c.field-meta.xml
<CustomField>
    <fullName>CarriedOverOfLastYear__c</fullName>
    <defaultValue>0</defaultValue>
    <description>대유넥스티어 연차 계산법 기준이 회계연도로 변경되어 필드 생성 (생성일: 2022-12-27, 생성자: hyunsoo.song@daeunextier.com)

* 필드 설명
이 필드는 매년 12월 31일 23시 00분에 &apos;HolidayLastYearUpdate 매년 12월 31일 업데이트&apos; 스케줄러로 업데이트됨.</description>
    <inlineHelpText>전년도에 발생한 연차일수</inlineHelpText>
    <label>전년도 연차일수</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/fm_Holiday_rewardRemainDays__c.field-meta.xml
<CustomField>
    <fullName>fm_Holiday_rewardRemainDays__c</fullName>
    <description>2023-12-14 Holiday_rewardRemainDays__c 사용하지 않고 해당 formula 필드로 사용 예정</description>
    <formula>Holiday_reward_Total_Count__c - Holiday_rewardDays__c - Holiday_BenefitPaymentDays__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>총 대체휴가일수 - 대체휴가 사용일수 - 대체휴가 수당 지급일수</inlineHelpText>
    <label>대체휴가 잔여일수</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_Annual_Calculated__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Annual_Calculated__c</fullName>
    <description>대유넥스티어 연차 계산법 기준이 회계연도로 변경되어 새로운 연차일수 계산 필드 생성 (생성일: 2022-12-27, 생성자: hyunsoo.song@daeunextier.com)

* 필드 설명 
- 1월 1일에 연차 일괄 부여
월차만료일 존재 X -&gt; 기존입사자 : 연차일수 15개 + 추가 연차일수
월차만료일 존재 -&gt; 신규입사자 : 반올림((12.31 - 입사월일)/365*15) 

ex1) 오늘 2023년 1월 1일
사원A: 입사일 2022-05-16 → 월차만료일 존재 → 입사월일(05.16~12.31)/365*15 → 10개
사원C: 입사일 2022-01-01 → 월차만료일 존재 X → 15 + 0 → 15개
사원D: 입사일 2019-09-04 → 월차만료일 존재 X → 15 + 1 → 16개

ex2) 오늘 2022년 12월 27일
사원A: 입사일 2022-05-16 -&gt; 월차만료일 존재 -&gt; 0개</description>
    <formula>IF(
    ISNULL(Holiday_Monthly_Period__c),
    15 + MIN(Holiday_Additionaldays__c, 10),
    IF(
        DATE(YEAR(Holiday_JoinDate__c) + 1, 1, 1) &lt;= TODAY(),
        CEILING((DATE(YEAR(Holiday_JoinDate__c), 12, 31) - Holiday_JoinDate__c + 1 ) / 365 * 15), 0
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>올해 발생한 연차일수</inlineHelpText>
    <label>올해 연차일수</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_BenefitPaymentDays__c.field-meta.xml
<CustomField>
    <fullName>Holiday_BenefitPaymentDays__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>올해 수당 지급완료된 대체휴가일수</inlineHelpText>
    <label>대체휴가 수당 지급일수</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_FamilyEvent_Count__c.field-meta.xml
<CustomField>
    <fullName>Holiday_FamilyEvent_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>경조휴가</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_GivenHolidays__c.field-meta.xml
<CustomField>
    <fullName>Holiday_GivenHolidays__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>추가적으로 부여된 연월차일수</inlineHelpText>
    <label>추가 부여 일수</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_IsActive__c.field-meta.xml
<CustomField>
    <fullName>Holiday_IsActive__c</fullName>
    <formula>!ISBLANK(Employee__c) &amp;&amp; Employee__r.Status__c</formula>
    <label>재직여부</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_Monthly_Calculated__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Monthly_Calculated__c</fullName>
    <description>대유넥스티어 연차 계산법 기준이 회계연도로 변경되어 필드 생성 (생성일: 2022-12-27, 생성자: hyunsoo.song@daeunextier.com)

* 필드 설명
1. 입사 1년차 이상 (월차 만료일 == BLANK || 전년도 월차일수 == 11개)
: 0

2. 신규입사자
: 입사연도 다음 해로 변경될 시 다시 1부터 Count (단, 입사일자의 DAY에 해당하는 일자 하루 전 날 부여됨)

ex) 오늘 2023년 01월 13일
사원A: 입사일 2022-05-16 → 월차 만료일(2023-12-31) →  0개	(매달 15일에 월차 부여)
사원B: 입사일 2022-12-13 → 월차 만료일(2023-12-31) → 1개 	(매달 12일에 월차 부여)

사원C: 입사일 2022-01-01 → 월차 만료일(2023-12-31) → 0개	(전년도 월차 11개, 올해 월차 0개)
사원D: 입사일 2021-09-04 → 월차 만료일(BLANK) → 0개</description>
    <formula>IF(
    ISBLANK(Holiday_Monthly_Period__c) || MonthlyOfLastYear__c = 11, 0,
    IF(
        YEAR(Holiday_Monthly_Period__c) = YEAR(TODAY()),
        11 - MonthlyOfLastYear__c,
        IF(
            FLOOR((DATE(YEAR(TODAY()), 12, 31) - Holiday_JoinDate__c - 1) / 30) &gt; 11,
            11,
            FLOOR((DATE(YEAR(TODAY()), 12, 31) - Holiday_JoinDate__c - 1) / 30)
        )
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>올해 발생한 월차일수 (월차는 입사일에 해당하는 일자 하루 전 날 부여됩니다.)</inlineHelpText>
    <label>올해 월차일수</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_PublicWorks_Count__c.field-meta.xml
<CustomField>
    <fullName>Holiday_PublicWorks_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>공가 사용일수</description>
    <label>공가</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_reward_Total_Count__c.field-meta.xml
<CustomField>
    <fullName>Holiday_reward_Total_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>올해 발생한 대체휴가일수 + 전년도 대체휴가 잔여일수</inlineHelpText>
    <label>총 대체휴가일수</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_rewardDays__c.field-meta.xml
<CustomField>
    <fullName>Holiday_rewardDays__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>올해 대체휴가 사용일수</inlineHelpText>
    <label>대체휴가 사용일수</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_SickLeave_Count__c.field-meta.xml
<CustomField>
    <fullName>Holiday_SickLeave_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>병가 사용 횟수</description>
    <label>병가</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_Total_Remain__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Total_Remain__c</fullName>
    <description>대유넥스티어 연차 계산법 기준이 회계연도로 변경되어 필드 생성 (생성일: 2022-12-27, 생성자: hyunsoo.song@daeunextier.com)

* 필드 설명
- 신규 입사자 &amp; 기존 입사자
: 올해 월차일수 + 올해 연차일수 + 전년도 연차 잔여일수 + 추가부여일수 - 사용일수</description>
    <formula>BLANKVALUE(Holiday_Monthly_Calculated__c, 0) +  BLANKVALUE(Holiday_Annual_Calculated__c, 0) + BLANKVALUE(HolidayRemainOfLastYear__c, 0) +  Holiday_GivenHolidays__c
-  Holiday_UseDays__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>총 연월차일수 + 추가 부여 일수 - 연월차 사용일수</inlineHelpText>
    <label>연월차 잔여일수</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_UseDays__c.field-meta.xml
<CustomField>
    <fullName>Holiday_UseDays__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>올해 연월차 사용일수</inlineHelpText>
    <label>연월차 사용일수</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_WomenHoliday_Count__c.field-meta.xml
<CustomField>
    <fullName>Holiday_WomenHoliday_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>생리휴가 사용일수</description>
    <label>생리휴가</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/HolidayRemainOfLastYear__c.field-meta.xml
<CustomField>
    <fullName>HolidayRemainOfLastYear__c</fullName>
    <defaultValue>0.0</defaultValue>
    <description>대유넥스티어 연차 계산법 기준이 회계연도로 변경되어 필드 생성 (생성일: 2022-12-27, 생성자: hyunsoo.song@daeunextier.com)

* 필드 설명
이 필드는 매년 12월 31일 23시 00분에 &apos;HolidayLastYearUpdate 매년 12월 31일 업데이트&apos; 스케줄러로 업데이트됨.</description>
    <inlineHelpText>전년도에 발생한 연월차 사용 후 잔여일수</inlineHelpText>
    <label>전년도 연월차 잔여일수</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/MonthlyOfLastYear__c.field-meta.xml
<CustomField>
    <fullName>MonthlyOfLastYear__c</fullName>
    <description>대유넥스티어 연차 계산법 기준이 회계연도로 변경되어 필드 생성 (생성일: 2022-12-27, 생성자: hyunsoo.song@daeunextier.com)

* 필드 설명
이 필드는 매년 12월 31일 23시 00분에 &apos;HolidayLastYearUpdate 매년 12월 31일 업데이트&apos; 스케줄러로 업데이트됨.</description>
    <inlineHelpText>전년도에 발생한 월차일수</inlineHelpText>
    <label>전년도 월차일수</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/RewardHolidayPaymentDaysOfLastYear__c.field-meta.xml
<CustomField>
    <fullName>RewardHolidayPaymentDaysOfLastYear__c</fullName>
    <defaultValue>0</defaultValue>
    <label>전년도 대체휴가 수당 지급일수</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/RewardHolidayRemainOfLastYear__c.field-meta.xml
<CustomField>
    <fullName>RewardHolidayRemainOfLastYear__c</fullName>
    <defaultValue>0</defaultValue>
    <label>전년도 대체휴가 잔여일수</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/RewardHolidayTotalOfLastYear__c.field-meta.xml
<CustomField>
    <fullName>RewardHolidayTotalOfLastYear__c</fullName>
    <defaultValue>0</defaultValue>
    <label>전년도 대체휴가일수</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/RewardHolidayUseDaysOfLastYear__c.field-meta.xml
<CustomField>
    <fullName>RewardHolidayUseDaysOfLastYear__c</fullName>
    <defaultValue>0</defaultValue>
    <label>전년도 대체휴가 사용일수</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/UseDaysOfLastYear__c.field-meta.xml
<CustomField>
    <fullName>UseDaysOfLastYear__c</fullName>
    <defaultValue>0</defaultValue>
    <description>대유넥스티어 연차 계산법 기준이 회계연도로 변경되어 필드 생성 (생성일: 2022-12-27, 생성자: hyunsoo.song@daeunextier.com)

* 필드 설명
이 필드는 매년 12월 31일 23시 00분에 &apos;HolidayLastYearUpdate 매년 12월 31일 업데이트&apos; 스케줄러로 업데이트됨.</description>
    <inlineHelpText>전년도에 발생한 연월차 사용일수 - 전년도 추가부여일수</inlineHelpText>
    <label>전년도 연월차 사용일수</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/HolidayAction__c.object-meta.xml
<CustomObject>
    <description>HolidayAction__c</description>
    <label>휴가신청</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Date1__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Date1__c</fullName>
    <label>Date1</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Date2__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Date2__c</fullName>
    <label>Date2</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Date3__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Date3__c</fullName>
    <label>Date3</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Date4__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Date4__c</fullName>
    <label>Date4</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Date5__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Date5__c</fullName>
    <label>Date5</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Parent__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Parent__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Holiday</label>
    <referenceTo>Holiday__c</referenceTo>
    <relationshipName>Holiday_Action</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Type__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Annual Holiday</fullName>
                <label>연차</label>
            </value>
            <value>
                <fullName>Half-day Leave</fullName>
                <label>반차</label>
            </value>
            <value>
                <fullName>Reward Holiday</fullName>
                <label>대체휴가</label>
            </value>
            <value>
                <fullName>Reward Half-Holiday</fullName>
                <label>대체휴가(반차)</label>
            </value>
            <value>
                <fullName>Public Works</fullName>
                <label>공가(공무)</label>
            </value>
            <value>
                <fullName>Family Leave</fullName>
                <label>경조휴가</label>
            </value>
            <value>
                <fullName>Sick Leave</fullName>
                <label>병가(무급)</label>
            </value>
            <value>
                <fullName>Women Holiday</fullName>
                <label>생리휴가</label>
            </value>
            <value>
                <fullName>가족돌봄휴가</fullName>
            </value>
            <value>
                <fullName>출산휴가</fullName>
            </value>
            <value>
                <fullName>휴직</fullName>
            </value>
            <value>
                <fullName>육아휴직</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/HolidayLastYearUpdate_ba.cls
/**
 * @description       : 매년 12월 31일 11:00:00 에 '올해 월차일수, 올해 연차일수, 연월차 사용일수, 연월차 잔여일수'를
 *                      '전년도 월차일수, 전년도 연차일수, 전년도 연월차 사용일수, 전년도 연월차 잔여일수' 각각에 값 update.
 *                      
 * @author            : hyunsoo.song@daeunextier.com
 * @group             :
 * @last modified on  : 2022-12-29
 * @last modified by  : hyunsoo.song@daeunextier.com
 * Modifications Log
 * Ver     Date             Author                  Modification
 * 1.0   2022-12-29   hyunsoo.song@daeunextier.com  Initial Version
 * 2.0   2023-12-20   kwanwoo.jeon@daeunextier.com  대체휴가 관련 로직 추가
 * 2.1   2023-12-27   kwanwoo.jeon@daeunextier.com  전년도 연월차 사용일수를 전년도에 사용한 전체 연월차 일수가 아닌, 전년도에 발생한 연월차 일수 중에 사용한 연월차 일수로 표시되게 변경
 * 2.2   2024-01-02   kwanwoo.jeon@daeunextier.com  전년도 연월차 사용일수에 추가부여일수 추가
 */
public with sharing class HolidayLastYearUpdate_ba implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful {

    public Database.QueryLocator start(Database.BatchableContext bc) {
        String strQuery;
        strQuery = ' SELECT  Id, Name, Holiday_Total_Remain__c, Holiday_UseDays__c, Holiday_GivenHolidays__c, Holiday_Annual_Calculated__c, ' +
                    ' HolidayRemainOfLastYear__c, CarriedOverOfLastYear__c, UseDaysOfLastYear__c, Holiday_Monthly_Calculated__c, ' +
                    ' Holiday_reward_Total_Count__c, Holiday_rewardDays__c, Holiday_BenefitPaymentDays__c, fm_Holiday_rewardRemainDays__c, ' +
                    ' RewardHolidayRemainOfLastYear__c, RewardHolidayTotalOfLastYear__c, RewardHolidayUseDaysOfLastYear__c, RewardHolidayPaymentDaysOfLastYear__c ';
        strQuery += ' FROM   Holiday__c';
        strQuery += ' WHERE  (Holiday_Annual_Calculated__c != NULL OR Holiday_Annual_Calculated__c != 0)';
        strQuery += ' AND    Holiday_IsActive__c = TRUE';
        System.debug('[HolidayLastYearUpdate] Query : ' + strQuery);

        return Database.getQueryLocator(strQuery);
    }

    public void execute(Database.BatchableContext bc, List<Holiday__c> listHoliday) {
        System.debug('[HolidayLastYearUpdate] Execute Start !!');
        Map<Id, Holiday__c> mapTarget = new Map<Id, Holiday__c>();
        for(Holiday__c obj : listHoliday) {

            //2023.12.27 하형석 이사님 요청으로 전년도 연월차 사용일수를 전년도 잔여 보다 사용일수가 적을 경우 0, else 올해 사용한 연월차 사용일수로 설정
            //전년도 연월차 사용일수 = 0 || 연월차 사용일수 - 전년도 잔여일수
            obj.UseDaysOfLastYear__c = (obj.Holiday_UseDays__c - obj.Holiday_GivenHolidays__c) < obj.HolidayRemainOfLastYear__c? 0 : (obj.Holiday_UseDays__c- obj.Holiday_GivenHolidays__c) - obj.HolidayRemainOfLastYear__c;

            // 전년도 연차 잔여일수 (전년도 연월차 사용기한 때문에 분기처리)
            if(obj.Holiday_UseDays__c > obj.HolidayRemainOfLastYear__c || (obj.HolidayRemainOfLastYear__c == 0 || obj.HolidayRemainOfLastYear__c == null)) {
                // 전년도 연월차 잔여일수 = 연월차 잔여일수
                obj.HolidayRemainOfLastYear__c = obj.Holiday_Total_Remain__c;
            } else {
                // 전년도 연월차 잔여일수 = 올해 연차일수 + 올해 월차일수 + 추가 부여 일수
                obj.HolidayRemainOfLastYear__c = obj.Holiday_Annual_Calculated__c + obj.Holiday_Monthly_Calculated__c + obj.Holiday_GivenHolidays__c;
            }

            // 전년도 월차일수 = 올해 월차일수
            obj.MonthlyOfLastYear__c = obj.Holiday_Monthly_Calculated__c;
            //전년도 연차일수 = 올해 연차일수
            obj.CarriedOverOfLastYear__c = obj.Holiday_Annual_Calculated__c;

            // 전년도 연월차 데이터 계산 완료 이후, 연월차 사용일수 및 추가 부여일수 초기화
            obj.Holiday_UseDays__c = 0;
            obj.Holiday_GivenHolidays__c = 0;

            // 경조휴가, 병가, 생리휴가, 공가 초기화
            obj.Holiday_FamilyEvent_Count__c = 0;
            obj.Holiday_SickLeave_Count__c = 0;
            obj.Holiday_WomenHoliday_Count__c = 0;
            obj.Holiday_PublicWorks_Count__c = 0;

            //2023.12.20    kwanwoo.jeon    대체휴가 필드 설정
            //전년도 대체휴가일수 = 총 대체휴가일수 - 전년도 대체휴가일수(ex. 23년 대체휴가 발생 일수는 23년 총에서 22년 발생일수를 뺀 값)
            obj.RewardHolidayTotalOfLastYear__c = obj.Holiday_reward_Total_Count__c - obj.RewardHolidayTotalOfLastYear__c;
            //전년도 대체휴가 사용일수 = 올해 대체휴가 사용일수
            obj.RewardHolidayUseDaysOfLastYear__c = obj.Holiday_rewardDays__c;
            //전년도 잔여 대체휴가일수 = 올해 대체휴가 잔여 일수
            obj.RewardHolidayRemainOfLastYear__c = obj.fm_Holiday_rewardRemainDays__c;
            //전년도 대체휴가 수당 지급일수 = 올해 대체휴가 수당 지급일수
            obj.RewardHolidayPaymentDaysOfLastYear__c = obj.Holiday_BenefitPaymentDays__c;

            //올해 총 대체휴가일수 = 전년도 잔여 대체휴가 일수 (+ 올해 발생한 대체휴가 일수 이기 때문에 scheduler에서는 전년도 잔여 대체휴가로만 계산)
            obj.Holiday_reward_Total_Count__c = obj.RewardHolidayRemainOfLastYear__c;

            //대체휴가 초기화
            obj.Holiday_rewardDays__c = 0;
            obj.Holiday_BenefitPaymentDays__c = 0;

            mapTarget.put(obj.Id, obj);
        }

        System.debug('mapTarget.size()' + mapTarget);

        if(mapTarget.size() != 0) {
            try {
                list<HolidayAction__c> listHolidayAction = new List<HolidayAction__c>([
                                SELECT  Id, HolidayAction_Parent__c, HolidayAction_Type__c,
                                        HolidayAction_Date1__c, HolidayAction_Date2__c, HolidayAction_Date3__c, HolidayAction_Date4__c, HolidayAction_Date5__c,
                                        HolidayAction_Date6__c, HolidayAction_Date7__c, HolidayAction_Date8__c, HolidayAction_Date9__c, HolidayAction_Date10__c
                                FROM    HolidayAction__c
                                WHERE   HolidayAction_Parent__c in : mapTarget.keySet()
                                AND     CreatedDate = THIS_YEAR
                                AND     HolidayAction_IsConfirm__c = TRUE
                                AND    (HolidayAction_Date1__c    > THIS_YEAR
                                OR      HolidayAction_Date2__c    > THIS_YEAR
                                OR      HolidayAction_Date3__c    > THIS_YEAR
                                OR      HolidayAction_Date4__c    > THIS_YEAR
                                OR      HolidayAction_Date5__c    > THIS_YEAR
                                OR      HolidayAction_Date6__c    > THIS_YEAR
                                OR      HolidayAction_Date7__c    > THIS_YEAR
                                OR      HolidayAction_Date8__c    > THIS_YEAR
                                OR      HolidayAction_Date9__c    > THIS_YEAR
                                OR      HolidayAction_Date10__c   > THIS_YEAR)
                ]);

                System.debug('listHolidayAction.size()' + listHolidayAction.size());
                map<Id, Decimal> mapIdToDaysCount = new Map<Id, Decimal>();
                map<Id, Decimal> mapIdToRewardDaysCount = new Map<Id, Decimal>();
                if (!listHolidayAction.isEmpty()) {
                    Integer intThisYear = Date.today().year();
                    for (HolidayAction__c obj: listHolidayAction){
                        if (new List<String>{'Annual Holiday','Half-day Leave','Reward Holiday','Reward Half-Holiday'}.contains(obj.HolidayAction_Type__c)) {
                            Decimal cnt = 0;
                            cnt = obj.HolidayAction_Date1__c    != null && obj.HolidayAction_Date1__c.year()    > intThisYear     ? obj.HolidayAction_Type__c.contains('Half') ?  cnt + 0.5 : cnt + 1 : cnt;
                            cnt = obj.HolidayAction_Date2__c    != null && obj.HolidayAction_Date2__c.year()    > intThisYear     ? cnt + 1 : cnt;
                            cnt = obj.HolidayAction_Date3__c    != null && obj.HolidayAction_Date3__c.year()    > intThisYear     ? cnt + 1 : cnt;
                            cnt = obj.HolidayAction_Date4__c    != null && obj.HolidayAction_Date4__c.year()    > intThisYear     ? cnt + 1 : cnt;
                            cnt = obj.HolidayAction_Date5__c    != null && obj.HolidayAction_Date5__c.year()    > intThisYear     ? cnt + 1 : cnt;
                            cnt = obj.HolidayAction_Date6__c    != null && obj.HolidayAction_Date6__c.year()    > intThisYear     ? cnt + 1 : cnt;
                            cnt = obj.HolidayAction_Date7__c    != null && obj.HolidayAction_Date7__c.year()    > intThisYear     ? cnt + 1 : cnt;
                            cnt = obj.HolidayAction_Date8__c    != null && obj.HolidayAction_Date8__c.year()    > intThisYear     ? cnt + 1 : cnt;
                            cnt = obj.HolidayAction_Date9__c    != null && obj.HolidayAction_Date9__c.year()    > intThisYear     ? cnt + 1 : cnt;
                            cnt = obj.HolidayAction_Date10__c   != null && obj.HolidayAction_Date10__c.year()   > intThisYear     ? cnt + 1 : cnt;


                            if (cnt > 0) {
                                if (new List<String>{'Annual Holiday','Half-day Leave'}.contains(obj.HolidayAction_Type__c)) {
                                    mapIdToDaysCount.put(obj.HolidayAction_Parent__c, mapIdToDaysCount.get(obj.HolidayAction_Parent__c) != null ? mapIdToDaysCount.get(obj.HolidayAction_Parent__c) + cnt : cnt);
                                }else if(new List<String>{'Reward Holiday','Reward Half-Holiday'}.contains(obj.HolidayAction_Type__c)) {
                                    mapIdToRewardDaysCount.put(obj.HolidayAction_Parent__c, mapIdToRewardDaysCount.get(obj.HolidayAction_Parent__c) != null ? mapIdToRewardDaysCount.get(obj.HolidayAction_Parent__c) + cnt : cnt);
                                }
                            }
                        }
                    }
                    if (!mapIdToDaysCount.isEmpty()) {
                        for (Id holidayId : mapIdToDaysCount.keySet()){
                            //전년도 사용일수(-), 전년도 잔여일수(+), 올해 사용일수(+)
                            //cnt = 내년도에 사용한 연차일수 (ex. 23.12에 결제올린 24.1 연차)
                            //전년도 사용일수 < cnt가 많을 경우 전년도 잔여일수 += 전년도 사용일수/ 사용일수 = 0/ 올해 사용일수 + cnt
                            if (mapTarget.get(holidayId).UseDaysOfLastYear__c < mapIdToDaysCount.get(holidayId)) {
                                mapTarget.get(holidayId).HolidayRemainOfLastYear__c += mapTarget.get(holidayId).UseDaysOfLastYear__c; //전년도 잔여일수 += 전년도 사용일수
                                mapTarget.get(holidayId).UseDaysOfLastYear__c       = 0; //전년도 사용일수 = 0
                            }else{
                                mapTarget.get(holidayId).UseDaysOfLastYear__c       -= mapIdToDaysCount.get(holidayId); //전년도 사용일수(-)
                                mapTarget.get(holidayId).HolidayRemainOfLastYear__c += mapIdToDaysCount.get(holidayId); //전년도 잔여일수(+)
                            }
                            mapTarget.get(holidayId).Holiday_UseDays__c += mapIdToDaysCount.get(holidayId); //올해 사용일수(+)
                        }
                    }
                    if (!mapIdToRewardDaysCount.isEmpty()) {
                        for (Id holidayId : mapIdToRewardDaysCount.keySet()){
                            //전년도 대체휴가 사용일수(-), 전년도 대체휴가 잔여일수(+), 올해 총 대체휴가(+), 올해 대체휴가 사용일수(+)
                            mapTarget.get(holidayId).RewardHolidayUseDaysOfLastYear__c  -= mapIdToRewardDaysCount.get(holidayId);
                            mapTarget.get(holidayId).RewardHolidayRemainOfLastYear__c   += mapIdToRewardDaysCount.get(holidayId);
                            mapTarget.get(holidayId).Holiday_reward_Total_Count__c      += mapIdToRewardDaysCount.get(holidayId);
                            mapTarget.get(holidayId).Holiday_rewardDays__c              += mapIdToRewardDaysCount.get(holidayId);
                        }
                    }
                }
                update mapTarget.values();

            } catch (Exception e) {
                System.debug('error :: ' + e.getMessage() + ' // ' + e.getLineNumber());
            }
        }

        System.debug('[HolidayLastYearUpdate] Execute End !!');
    }

    public void finish(Database.BatchableContext bc) { }
}