PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/Holiday__c.object-meta.xml
<CustomObject>
    <label>Holiday</label>
    <nameField>
        <displayFormat>H-{0000}</displayFormat>
        <label>Holiday No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_User__c.field-meta.xml
<CustomField>
    <fullName>Holiday_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>임직원</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Holiday</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/SecondApproverSelection__c.field-meta.xml
<CustomField>
    <fullName>SecondApproverSelection__c</fullName>
    <formula>ChildHolidayAction__r.SecondApproverSelection__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>2차 승인 지정여부</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/HolidayAction__c.object-meta.xml
<CustomObject>
    <description>HolidayAction__c</description>
    <label>휴가신청</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/FirstHolidayRequest__c.field-meta.xml
<CustomField>
    <fullName>FirstHolidayRequest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>1차 승인자 지정</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Holiday_Action1</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Date1__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Date1__c</fullName>
    <label>Date1</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Parent__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Parent__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Holiday</label>
    <referenceTo>Holiday__c</referenceTo>
    <relationshipName>Holiday_Action</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Type__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Annual Holiday</fullName>
                <label>연차</label>
            </value>
            <value>
                <fullName>Half-day Leave</fullName>
                <label>반차</label>
            </value>
            <value>
                <fullName>Reward Holiday</fullName>
                <label>대체휴가</label>
            </value>
            <value>
                <fullName>Reward Half-Holiday</fullName>
                <label>대체휴가(반차)</label>
            </value>
            <value>
                <fullName>Public Works</fullName>
                <label>공가(공무)</label>
            </value>
            <value>
                <fullName>Family Leave</fullName>
                <label>경조휴가</label>
            </value>
            <value>
                <fullName>Sick Leave</fullName>
                <label>병가(무급)</label>
            </value>
            <value>
                <fullName>Women Holiday</fullName>
                <label>생리휴가</label>
            </value>
            <value>
                <fullName>가족돌봄휴가</fullName>
            </value>
            <value>
                <fullName>출산휴가</fullName>
            </value>
            <value>
                <fullName>휴직</fullName>
            </value>
            <value>
                <fullName>육아휴직</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/SecondApproverRequest__c.field-meta.xml
<CustomField>
    <fullName>SecondApproverRequest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>2차 승인자 지정</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Holiday_Action2</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/SecondApproverSelection__c.field-meta.xml
<CustomField>
    <fullName>SecondApproverSelection__c</fullName>
    <defaultValue>false</defaultValue>
    <label>2차 승인 여부</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/ApprovalHolidayShare_tr_Test.cls
@isTest
private class ApprovalHolidayShare_tr_Test {
	
	@isTest static void testMe() {
		Test.startTest();
		Profile profile = TestDataFactory.getProfile('System Administrator');

		ApprovalHolidayShare_tr approvalHolidayShare = new ApprovalHolidayShare_tr();
		/*경비 제출자*/
		User user = new User(Alias = 'User'
                            , Email='SysAdminTestuser@earth.org'
                            , EmailEncodingKey='UTF-8'
                            , LastName='Testing'
                            , LanguageLocaleKey='en_US'
                            , LocaleSidKey='en_US'
                            , EmployeeNumber='AC100000'
                            , TimeZoneSidKey='Asia/Seoul'
                            , ProfileId = profile.Id
                            , UserName='SysAdminTestuser@earth.org');
		insert user;

		/*Manager 및 2차승인자*/
		User user1 = new User(Alias = 'User1'
                            , Email='SysAdminTestuser1@earth.org'
                            , EmailEncodingKey='UTF-8'
                            , LastName='Testing1'
                            , LanguageLocaleKey='en_US'
                            , LocaleSidKey='en_US'
                            , EmployeeNumber='AC100001'
                            , TimeZoneSidKey='Asia/Seoul'
                            , ProfileId = profile.Id
                            , UserName='SysAdminTestuser1@earth.org'); 
		insert user1;
		user.ManagerId = user1.Id;
		update user;

		/*1차승인자*/
		User user2 = new User(Alias = 'User2'
                            , Email='SysAdminTestuser1@earth.org'
                            , EmailEncodingKey='UTF-8'
                            , LastName='Testing2'
                            , LanguageLocaleKey='en_US'
                            , LocaleSidKey='en_US'
                            , EmployeeNumber='AC100002'
                            , TimeZoneSidKey='Asia/Seoul'
                            , ProfileId = profile.Id
                            , UserName='SysAdminTestuser2@earth.org');                                                                                
		insert user2;

		/*변경할 1차승인자*/
		User user3 = new User(Alias = 'User3'
                            , Email='SysAdminTestuser3@earth.org'
                            , EmailEncodingKey='UTF-8'
                            , LastName='Testing2'
                            , LanguageLocaleKey='en_US'
                            , LocaleSidKey='en_US'
                            , EmployeeNumber='AC100003'
                            , TimeZoneSidKey='Asia/Seoul'
                            , ProfileId = profile.Id
                            , UserName='SysAdminTestuser3@earth.org');                                                                                
		insert user3;

		Holiday__c holiday = new Holiday__c();
		holiday.Holiday_User__c = user.Id;
		insert holiday;

		HolidayAction__c holidayAction = new HolidayAction__c();
		holidayAction.HolidayAction_Date1__c = system.today();
		holidayAction.HolidayAction_Type__c = 'Annual Holiday';
		holidayAction.OwnerId = user.Id;
		holidayAction.FirstHolidayRequest__c = user1.Id;
		holidayAction.SecondApproverSelection__c = false;
		holidayAction.HolidayAction_Parent__c = holiday.Id;
		insert holidayAction;

		holidayAction.FirstHolidayRequest__c = user3.Id;
		holidayAction.SecondApproverSelection__c = true;
		holidayAction.SecondApproverRequest__c = user1.Id;
		update holidayAction;

		Test.stopTest();
	}
	
}