PA_Education/TestMenifest/force-app/main/default/objects/Interview__c/Interview__c.object-meta.xml
<CustomObject>
    <description>신입 대상으로 진행한 면담일지 개체</description>
    <label>면담일지</label>
    <nameField>
        <displayFormat>No.{YYYY}-{MM}-{DD}/{00}</displayFormat>
        <label>면담일지</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Interview__c/fields/Intv_Date__c.field-meta.xml
<CustomField>
    <fullName>Intv_Date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>면담이 진행된 날짜를 기록</description>
    <label>면담 일시</label>
    <type>DateTime</type>
</CustomField>

ListViewButton/PrintPdfAndSave/force-app/main/default/classes/printInterviewListController_test.cls
@isTest
public class printInterviewListController_test {
    @isTest
    public static void testPrintInterviewListController() {
        //setup
        List<Interview__c> listInterviews = new List<Interview__c>();
        for (Integer i = 0; i < 3; i++) {
            listInterviews.add(new Interview__c(
                Intv_Date__c = Date.today().addDays(-i)
            ));
        }
        insert listInterviews;

        // StandardSetController 생성
        List<Interview__c> listSelectedInterviews = [SELECT Id FROM Interview__c LIMIT 2];
        ApexPages.StandardSetController stdSetController = new ApexPages.StandardSetController(listSelectedInterviews);

        
        Test.startTest();
        printInterviewListController controller = new printInterviewListController(stdSetController);
        Test.stopTest();
    }
}