PA_Education/TestMenifest/force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Oppty</label>
    <nameField>
        <label>영업기회 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Opportunity__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>상위 영업기회</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Opportunity__c/fields/Remark__c.field-meta.xml
<CustomField>
    <fullName>Remark__c</fullName>
    <label>비고</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/Opportunity_Remark_Update_tr.cls
public with sharing class Opportunity_Remark_Update_tr {
    public static void DoOpportunityRemarkUpdate(List<Task> objs) {
        List<String> splitList = new List<String>();
        string strSplit = '';
        string strSplitAll ='';
        List<Task> targetTask = new List<Task>();
        
        for(Task obj:objs){
            if(targetTask<>null) targetTask.add(obj);
        }
        
        if(!targetTask.isEmpty()){
            Set<Id> opportunityId = new Set<Id>();
            for (Task obj:targetTask){
                splitList.add('--------------일자 : '+obj.ActivityDate.format()+'--------------♬');
                splitList.add('제목 : ' + obj.Subject + '♬');
                splitList.add('내용 : ' + obj.Description + '♬');
                splitList.add('------------------------------------------------------♬♬');
                opportunityId.add(obj.WhatId);
            }
            
            if(splitList.size() > 0){
                for(String getList : splitList){
                    strSplit += getList.replaceAll('♬','\n');
                }
            }
            
            List<Opportunity__c> opptyList = new List<Opportunity__c>();
            opptyList = [ SELECT Id, Remark__c FROM Opportunity__c WHERE Id=:opportunityId];
            
            if(!opptyList.isEmpty()){
                for(Opportunity__c opptyobj:opptyList){
                    if(opptyobj.Remark__c <> null || opptyobj.Remark__c <> ''){
                        system.debug('opptyobj.Remark__c========>'+opptyobj.Remark__c);
                        strSplitAll += strSplit + '\n' + opptyobj.Remark__c;
                        opptyobj.Remark__c = strSplitAll.replaceAll('null','');
                    }
                    update opptyobj;
                }        
            }
        }
    }
/****************************************************************************************************
*   테스트메소드
****************************************************************************************************/
    
    @TestVisible private static Void testMe(Task objs){
        System.debug('----------------Opportunity_Remark_Update_tr Test Start');
        
        List<Task> testTask = new List<Task>();
        testTask.add(objs);
        
    }
    
}