PA_Education/TestMenifest/force-app/main/default/objects/Career__c/Career__c.object-meta.xml
<CustomObject>
    <label>Career</label>
    <nameField>
        <label>회사 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Career__c/fields/CareerExitDate__c.field-meta.xml
<CustomField>
    <fullName>CareerExitDate__c</fullName>
    <label>퇴사일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Career__c/fields/CareerJoinDate__c.field-meta.xml
<CustomField>
    <fullName>CareerJoinDate__c</fullName>
    <label>입사일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Career__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>사원 명</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipName>Re_Career</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EducationalHistory__c/EducationalHistory__c.object-meta.xml
<CustomObject>
    <label>학력사항</label>
    <nameField>
        <label>학교 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/EducationalHistory__c/fields/Degree__c.field-meta.xml
<CustomField>
    <fullName>Degree__c</fullName>
    <label>학위</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>박사</fullName>
            </value>
            <value>
                <fullName>박사 수료</fullName>
            </value>
            <value>
                <fullName>석사</fullName>
            </value>
            <value>
                <fullName>석사 수료</fullName>
            </value>
            <value>
                <fullName>학사</fullName>
            </value>
            <value>
                <fullName>전문학사</fullName>
            </value>
            <value>
                <fullName>고졸</fullName>
            </value>
            <value>
                <fullName>중졸</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EducationalHistory__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>사원 명</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>학력사항</relationshipLabel>
    <relationshipName>Re_Education</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EducationalHistory__c/fields/GraduatedDate__c.field-meta.xml
<CustomField>
    <fullName>GraduatedDate__c</fullName>
    <label>졸업일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Birthday__c.field-meta.xml
<CustomField>
    <fullName>Birthday__c</fullName>
    <label>생년월일</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Clear__c.field-meta.xml
<CustomField>
    <fullName>Clear__c</fullName>
    <label>금품청산 등</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/CurrentAddress__c.field-meta.xml
<CustomField>
    <fullName>CurrentAddress__c</fullName>
    <label>주거지 주소</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>부서</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Departments</valueSetName>
    </valueSet>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/Dependents__c.field-meta.xml
<CustomField>
    <fullName>Dependents__c</fullName>
    <label>부양가족</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

ListViewButton/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/DismissalDate__c.field-meta.xml
<CustomField>
    <fullName>DismissalDate__c</fullName>
    <label>해고일자</label>
    <type>Date</type>
</CustomField>

ListViewButton/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/ExitDate__c.field-meta.xml
<CustomField>
    <fullName>ExitDate__c</fullName>
    <label>퇴사일자</label>
    <type>Date</type>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/JoinDate__c.field-meta.xml
<CustomField>
    <fullName>JoinDate__c</fullName>
    <description>입사일자</description>
    <label>입사일자</label>
    <type>Date</type>
</CustomField>

ListViewButton/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/MilitaryServiceDiv__c.field-meta.xml
<CustomField>
    <fullName>MilitaryServiceDiv__c</fullName>
    <label>병역구분</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>해당없음</fullName>
                <default>true</default>
                <label>해당없음</label>
            </value>
            <value>
                <fullName>필</fullName>
            </value>
            <value>
                <fullName>미필</fullName>
            </value>
            <value>
                <fullName>면제</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ListViewButton/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/MilitaryType__c.field-meta.xml
<CustomField>
    <fullName>MilitaryType__c</fullName>
    <label>군별</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>육군</fullName>
            </value>
            <value>
                <fullName>공군</fullName>
            </value>
            <value>
                <fullName>해군</fullName>
            </value>
            <value>
                <fullName>해병대</fullName>
            </value>
            <value>
                <fullName>상근예비역</fullName>
            </value>
            <value>
                <fullName>의무경찰</fullName>
            </value>
            <value>
                <fullName>의무경찰(해양)</fullName>
            </value>
            <value>
                <fullName>의무소방</fullName>
            </value>
            <value>
                <fullName>사회복무요원</fullName>
            </value>
            <value>
                <fullName>예술·체육요원</fullName>
            </value>
            <value>
                <fullName>국제협력봉사요원</fullName>
            </value>
            <value>
                <fullName>전문연구요원</fullName>
            </value>
            <value>
                <fullName>산업기능요원(현역)</fullName>
            </value>
            <value>
                <fullName>산업기능요원(보충역)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/MobilePhone__c.field-meta.xml
<CustomField>
    <fullName>MobilePhone__c</fullName>
    <description>휴대폰번호</description>
    <label>휴대전화</label>
    <type>Phone</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>직급</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>총괄사장</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>대표이사</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>센터장</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>감사</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>부사장</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>전무</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>상무</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>수석</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>이사</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>부장</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>책임</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>차장</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>과장</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>대리</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>선임</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>선임(수습)</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>사원</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>사원(수습)</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>인턴</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>사유</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

ListViewButton/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/UpdateDate__c.field-meta.xml
<CustomField>
    <fullName>UpdateDate__c</fullName>
    <label>근로계약갱신일</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Qualification__c/Qualification__c.object-meta.xml
<CustomObject>
    <label>자격사항</label>
    <nameField>
        <label>자격명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Qualification__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>사원 명</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>자격사항</relationshipLabel>
    <relationshipName>Re_License</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/EmployeeDetailController.cls
/**
 * Created by attar on 2020-11-17.
 */

public with sharing class EmployeeDetailController {
    public static Employee objEmployees {get; set;}
    public static List<Qualification__c> empLicense {get; set;}
    public static List<Career> empCareer{get; set;}
    public static String location {get; set;}
    public static String work {get; set;}

    public EmployeeDetailController(ApexPages.standardController controller){
        if (objEmployees == null) {
            objEmployees = new Employee();
        }

        if (empLicense == null) {
            empLicense = new List<Qualification__c>();
        }

        if (empCareer == null) {
            empCareer = new List<Career>();
        }

        String recordId = ApexPages.currentPage().getParameters().get('recordId');
        objEmployees = doGetData(recordId);
    }

//    @AuraEnabled
//    public static Boolean doFind(String recordId) {
//        List<Employee__c> listObj = new List<Employee__c>([
//                SELECT Reason__c, Clear__c
//                FROM Employee__c
//                WHERE Id = :recordId
//        ]);
//
//        if (listObj.get(0).Reason__c == null && listObj.get(0).Clear__c == null) {
//            return true;
//        }
//        else {
//            return false;
//        }
//    }


    @AuraEnabled
    public static Employee doGetData(String recordId){
        Employee employee = new Employee();

        System.debug(recordId);
        List<Employee__c> listEmployee = new List<Employee__c>([
                SELECT Name, Birthday__c,
                        CurrentAddress__c, MobilePhone__c,
                        Department__c,
                        ExitDate__c,
                        MilitaryServiceDiv__c,
                        JoinDate__c,
                        UpdateDate__c,
                        Position__c,
                        Dependents__c,
                        DismissalDate__c,
                        Clear__c,
                        Reason__c
                FROM Employee__c
                WHERE Id =:recordId
        ]);

        List<Qualification__c> listLicense = new List<Qualification__c>([
                SELECT Name
                FROM Qualification__c
                WHERE Employee_Name__c =: recordId
        ]);

        List<EducationalHistory__c> listEducation = new List<EducationalHistory__c>([
                SELECT Degree__c
                FROM EducationalHistory__c
                WHERE Employee_Name__c =:recordId
                ORDER BY GraduatedDate__c DESC LIMIT 1
        ]);

        List<Career__c> listCareer = new List<Career__c>([
                SELECT Name, CareerExitDate__c, CareerJoinDate__c
                FROM Career__c
                WHERE Employee_Name__c =:recordId
        ]);

        Employee__c objEmployees = listEmployee.get(0);

        if (objEmployees.Position__c == '1' || objEmployees.Position__c == '10') {
            location = '본사';
            work = '관리 및 컨설팅';
        }

        else {
            location = '외주처';
            work = '시스템 개발';
        }

        if (!listLicense.isEmpty()) {
            for(Qualification__c objQualification : listLicense) {
                empLicense.add(objQualification);
            }
        }

        if (!listEducation.isEmpty()) {
            EducationalHistory__c objEducationalHistory = listEducation.get(0);
            employee.education = objEducationalHistory.Degree__c;
        }

        if (!listCareer.isEmpty()) {
            for(Career__c objCareer : listCareer) {
                Career obj = new Career();

                obj.company = objCareer.Name;
                if (objCareer.CareerExitDate__c != null && objCareer.CareerJoinDate__c != null) {
                    obj.period = String.valueOf(objCareer.CareerExitDate__c.year() - objCareer.CareerJoinDate__c.year() + 1);
                }
                empCareer.add(obj);
            }
        }
        else {
            Career obj = new Career();

            obj.company = '없음';
            obj.period = '';
            empCareer.add(obj);
        }

        if (objEmployees.Birthday__c != null) {
            String strBirthYear = String.valueOf(objEmployees.Birthday__c.year());
            String strBirthMonth = String.valueOf(objEmployees.Birthday__c.month());
            String strBirthDay = String.valueOf(objEmployees.Birthday__c.day());
            String strBirthDate = strBirthYear + '.' + strBirthMonth + '.' + strBirthDay;

            employee.birthday = strBirthDate;
        }
        else {
            employee.birthday = '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;년&nbsp;&nbsp;&nbsp;&nbsp;월&nbsp;&nbsp;&nbsp;&nbsp;일';
        }

        if (objEmployees.ExitDate__c != null) {
            String strExitYear = String.valueOf(objEmployees.ExitDate__c.year());
            String strExitMonth = String.valueOf(objEmployees.ExitDate__c.month());
            String strExitDay = String.valueOf(objEmployees.ExitDate__c.day());
            String strExitDate = strExitYear + '년' + strExitMonth + '월' + strExitDay + '일';

            employee.exitDate = strExitDate;
        }
        else {
            employee.exitDate = '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;년&nbsp;&nbsp;&nbsp;&nbsp;월&nbsp;&nbsp;&nbsp;&nbsp;일';
        }

        if (objEmployees.JoinDate__c != null) {
            String strJoinYear = String.valueOf(objEmployees.JoinDate__c.year());
            String strJoinMonth = String.valueOf(objEmployees.JoinDate__c.month());
            String strJoinDay = String.valueOf(objEmployees.JoinDate__c.day());
            String strJoinDate = strJoinYear + '년' + strJoinMonth + '월' + strJoinDay + '일';

            employee.joinDate = strJoinDate;
        }
        else {
            employee.joinDate = '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;년&nbsp;&nbsp;&nbsp;&nbsp;월&nbsp;&nbsp;&nbsp;&nbsp;일';
        }

        if (objEmployees.UpdateDate__c != null) {
            String strUpdateYear = String.valueOf(objEmployees.UpdateDate__c.year());
            String strUpdateMonth = String.valueOf(objEmployees.UpdateDate__c.month());
            String strUpdateDay = String.valueOf(objEmployees.UpdateDate__c.day());
            String strUpdateDate = strUpdateYear + '년' + strUpdateMonth + '월' + strUpdateDay + '일';

            employee.updateDate = strUpdateDate;
        }
        else {
            employee.updateDate = '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;년&nbsp;&nbsp;&nbsp;&nbsp;월&nbsp;&nbsp;&nbsp;&nbsp;일';
        }

        employee.name = objEmployees.Name;
        employee.currentAddress = objEmployees.CurrentAddress__c;
        employee.mobilePhone = objEmployees.MobilePhone__c;
        employee.department = objEmployees.Department__c;
        employee.reason = objEmployees.Reason__c;
        //employee.militaryType = objEmployees.MilitaryType__c;
        employee.militaryServiceDiv = objEmployees.MilitaryServiceDiv__c;
        //employee.clear = objEmployees.Clear__c;

        //2023.06.13 yj.kim 추가
        employee.dependents = objEmployees.Dependents__c;
        employee.goldClear = objEmployees.Clear__c;
        if (objEmployees.DismissalDate__c != null) {
            String strDismissalYear = String.valueOf(objEmployees.DismissalDate__c.year());
            String strDismissalMonth = String.valueOf(objEmployees.DismissalDate__c.month());
            String strDismissalDay = String.valueOf(objEmployees.DismissalDate__c.day());
            String strDismissalDate = strDismissalYear + '년' + strDismissalMonth + '월' + strDismissalDay + '일';

            employee.dismissalDate = strDismissalDate;
        }else{
            employee.dismissalDate = '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;년&nbsp;&nbsp;&nbsp;&nbsp;월&nbsp;&nbsp;&nbsp;&nbsp;일';
        }

        return employee;
    }

    @AuraEnabled
    public static void doSaveData(String paramReason, String paramClear, String recordId) {
        List<Employee__c> listObj = new List<Employee__c>([
                SELECT Name
                FROM Employee__c
                WHERE Id = :recordId
        ]);
/*        if (paramReason != null) {
            listObj.get(0).Reason__c = paramReason;
        }
        if (paramClear != null) {
            listObj.get(0).Clear__c = paramClear;
        }*/
        update listObj;
    }

    public class Employee {
        public String name{get; set;}
        public String birthday{get; set;}
        public String currentAddress{get; set;}
        public String mobilePhone{get; set;}
        public String department{get; set;}
        public String exitDate{get; set;}
        public String reason{get; set;}
        //public String militaryType{get; set;}
        public String militaryServiceDiv{get; set;}
        //public String clear{get; set;}
        public String joinDate{get; set;}
        public String education{get; set;}
        public String strId {get; set;}
        public String updateDate{get; set;}

        //2023.06.13 yj.kim 추가
        public String dependents {get; set;}
        public String dismissalDate {get; set;}
        public String goldClear {get; set;}
    }

    public class Career {
        public String company{get; set;}
        public String period{get; set;}
    }
}