PA_Education/TestMenifest/force-app/main/default/objects/Career__c/Career__c.object-meta.xml
<CustomObject>
    <label>Career</label>
    <nameField>
        <label>회사 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/JobPosition__c/JobPosition__c.object-meta.xml
<CustomObject>
    <description>채용공고, 인재채용 Object</description>
    <label>인재채용</label>
    <nameField>
        <displayFormat>인재채용-{0000}</displayFormat>
        <label>인재채용 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/JobPosition__c/fields/Career__c.field-meta.xml
<CustomField>
    <fullName>Career__c</fullName>
    <label>지원구분</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>신입</fullName>
            </value>
            <value>
                <fullName>경력</fullName>
            </value>
            <value>
                <fullName>무관</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/JobPosition__c/fields/OrderNum__c.field-meta.xml
<CustomField>
    <fullName>OrderNum__c</fullName>
    <label>OrderNum</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/JobPosition__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>포지션명</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administrator</fullName>
                <default>true</default>
                <label>Administrator</label>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/JobPosition__c/fields/RecruitmentCategory__c.field-meta.xml
<CustomField>
    <fullName>RecruitmentCategory__c</fullName>
    <label>모집 구분</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>공개채용</fullName>
            </value>
            <value>
                <fullName>특별채용</fullName>
            </value>
            <value>
                <fullName>상시채용</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/JobPosition__c/fields/WorkType__c.field-meta.xml
<CustomField>
    <fullName>WorkType__c</fullName>
    <label>근무형태</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>정규직</fullName>
            </value>
            <value>
                <fullName>계약직</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/JobPosition__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <description>인재채용 제목 용도의 Field
ex) 2021 2022</description>
    <label>년도</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/RenewalHPJobPositions_Test.cls
/************************************************************************************
 * File Name   : RenewalHPJobPositions_Test.cls
 * Author      : SungJu.Kang
 * Date        : 2022. 01. 03
 * Target      : RenewalHPJobPositions.cls
 * Description : RenewalHPJobPositions.cls Test Class
 * Modification Log
 * ===================================================================================
 * Ver      Date            Author              Modification
 * ===================================================================================
   1.0      2022. 01. 03   SungJu.Kang            Create
*************************************************************************************/

@IsTest
private class RenewalHPJobPositions_Test {
    @IsTest
    static void itShould() {
        Test.startTest();
        JobPosition__c objJobPosition = new JobPosition__c();
        objJobPosition.WorkType__c = '정규직';
        objJobPosition.RecruitmentCategory__c = '공개채용';
        objJobPosition.Position__c = 'Developer';
        objJobPosition.Career__c = '신입';
        objJobPosition.Year__c = '2022';
        objJobPosition.OrderNum__c = 1;
        insert objJobPosition;

        RenewalHPJobPositions.getPositions(true);
        RenewalHPJobPositions.getPositions(false);
        RenewalHPJobPositions.loadMorePositions(true);
        RenewalHPJobPositions.loadMorePositions(false);

        Map<String, Object> mapTarget = new Map<String, Object>();
        mapTarget.put('Mobile', 01024451509);
        mapTarget.put('Applicant','Applicant');
        mapTarget.put('JobPositionId', objJobPosition.Id);
        mapTarget.put('BirthDate' , Date.today());
        mapTarget.put('Email' , 'sjyk@naver.com');

        RenewalHPJobPositions.doSaveApplyTo(mapTarget,'testclass', 'testdate','jpg');





        Test.stopTest();
    }
}