PA_Education/TestMenifest/force-app/main/default/objects/CorporateCard__c/CorporateCard__c.object-meta.xml
<CustomObject>
    <label>법인카드</label>
    <nameField>
        <label>법인카드 이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCard__c/fields/CardCompany__c.field-meta.xml
<CustomField>
    <fullName>CardCompany__c</fullName>
    <label>카드사</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>비씨</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>국민</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>하나</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>삼성</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>신한</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>현대</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>롯데자사</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>씨티, 한미</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>NH채움</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>수협</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>신협</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>우리</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>하나SK</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>광주</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>전북</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>제주</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>산은캐피탈</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>해외비자</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>해외마스터</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>해외다이너스</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>해외AMX</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>해외JCB</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>우체국</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>저축은행</label>
            </value>
            <value>
                <fullName>34</fullName>
                <label>은련</label>
            </value>
            <value>
                <fullName>35</fullName>
                <label>새마을금고</label>
            </value>
            <value>
                <fullName>36</fullName>
                <label>KDB산업</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCard__c/fields/CardNumber__c.field-meta.xml
<CustomField>
    <fullName>CardNumber__c</fullName>
    <externalId>true</externalId>
    <label>카드번호</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCard__c/fields/EmployeeNo__c.field-meta.xml
<CustomField>
    <fullName>EmployeeNo__c</fullName>
    <description>Insert 시 사번으로 소유자 업데이트 (실사용자가 null일경우 실사용자도 업데이트), Update 시 실사용자의 사번으로 사번필드 업데이트</description>
    <label>사번</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCard__c/fields/RealUser__c.field-meta.xml
<CustomField>
    <fullName>RealUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>실사용자</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CorporateCard</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/EmployeeNo__c.field-meta.xml
<CustomField>
    <fullName>EmployeeNo__c</fullName>
    <label>사번</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>사원 Object를 User Object간 Relationship 생성</inlineHelpText>
    <label>사용자 명</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/CorporateCard_tr_test.cls
/************************************************************************************
* File Name   	    : CorporateCard_tr testClass
* Author	  		: Yeonlim
* Date				: 2024-01-17
* Modification Log
* ===================================================================================
* Ver      Date            Author          Modification
* ===================================================================================
* 1.0      2024-01-17      Yeonlim           Create
************************************************************************************/
@IsTest
public with sharing class CorporateCard_tr_test {
    @IsTest
    static void doTest() {
        User objUser = TestObjectCreator.objUser;
        insert objUser;

        Employee__c objEmp = TestObjectCreator.objEmployee;
        objEmp.User__c = objUser.Id;
        insert objEmp;

        CorporateCard__c objCC = new CorporateCard__c(
                CardNumber__c   = '0000000000000006',
                CardCompany__c  = '03',
                EmployeeNo__c   = [SELECT EmployeeNo__c FROM Employee__c WHERE Id =: objEmp.Id].EmployeeNo__c
        );
        insert objCC;

        User objUser2 = objUser.clone();
        objUser2.CommunityNickname  = 'test';
        objUser2.Username           = 'test@daeu.com';
        insert objUser2;

        objCC.RealUser__c = objUser2.Id;
        update objCC;
    }

}