PA_Education/TestMenifest/force-app/main/default/objects/CorporateCard__c/CorporateCard__c.object-meta.xml
<CustomObject>
    <label>법인카드</label>
    <nameField>
        <label>법인카드 이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCard__c/fields/CardNumber__c.field-meta.xml
<CustomField>
    <fullName>CardNumber__c</fullName>
    <externalId>true</externalId>
    <label>카드번호</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/CorporateCardBilling__c.object-meta.xml
<CustomObject>
    <label>법인카드청구내역</label>
    <nameField>
        <displayFormat>CB-{YY}{MM}-{00000}</displayFormat>
        <label>법인카드청구내역</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/fields/CardNumber__c.field-meta.xml
<CustomField>
    <fullName>CardNumber__c</fullName>
    <label>카드번호</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/fields/CorporateCard__c.field-meta.xml
<CustomField>
    <fullName>CorporateCard__c</fullName>
    <label>법인카드</label>
    <referenceTo>CorporateCard__c</referenceTo>
    <relationshipLabel>법인카드청구내역</relationshipLabel>
    <relationshipName>CorporateCardBilling_CorporateCard</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/CorporateCardBilling_tr.cls
/************************************************************************************
* File Name   	    : CorporateCardBilling_tr
* Author	  		: Yeonlim
* Date				: 2024-01-12
* Modification Log
* ===================================================================================
* Ver      Date            Author          Modification
* ===================================================================================
* 1.0      2024-01-12      Yeonlim         Create
************************************************************************************/
public with sharing class CorporateCardBilling_tr extends TriggerHandler {
    private static List<CorporateCardBilling__c> listNew {get; set;}
    private static List<CorporateCardBilling__c> listOld {get; set;}
    private static Map<Id, CorporateCardBilling__c> mapNew {get; set;}
    private static Map<Id, CorporateCardBilling__c> mapOld {get; set;}

    public CorporateCardBilling_tr() {
        listNew = (List<CorporateCardBilling__c>) Trigger.new;
        listOld = (List<CorporateCardBilling__c>) Trigger.old;
        mapNew  = (Map<Id, CorporateCardBilling__c>) Trigger.newMap;
        mapOld  = (Map<Id, CorporateCardBilling__c>) Trigger.oldMap;
    }

    public override void beforeInsert() {
        doSetCardNumber();
    }

    /**
    * Event : before insert
    * Author : Yeonlim
    * Description : 법인카드 청구내역의 카드번호로 들어오는 값과 일치하는 법인카드 Object(Master)를 찾아서 넣어줌
    */
    public void doSetCardNumber() {
        Set<String> setCardNum = new Set<String>();

        for (CorporateCardBilling__c obj : listNew) {
            if (String.isBlank(obj.CorporateCard__c) && String.isNotBlank(obj.CardNumber__c)) {
                setCardNum.add(obj.CardNumber__c);
            }
        }

        if (!setCardNum.isEmpty()) {
            Map<String, String> mapCardNumToCardId = new Map<String, String>();

            for (CorporateCard__c obj : [
                    SELECT Id, CardNumber__c
                    FROM CorporateCard__c
                    WHERE CardNumber__c IN: setCardNum
            ]) {
                mapCardNumToCardId.put(obj.CardNumber__c, obj.Id);
            }

            for (CorporateCardBilling__c obj : listNew) {
                obj.CorporateCard__c = mapCardNumToCardId.get(obj.CardNumber__c);
            }
        }
    }

}