PA_Education/TestMenifest/force-app/main/default/objects/CorporateCard__c/CorporateCard__c.object-meta.xml
<CustomObject>
    <label>법인카드</label>
    <nameField>
        <label>법인카드 이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCard__c/fields/CardCompany__c.field-meta.xml
<CustomField>
    <fullName>CardCompany__c</fullName>
    <label>카드사</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>비씨</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>국민</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>하나</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>삼성</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>신한</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>현대</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>롯데자사</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>씨티, 한미</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>NH채움</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>수협</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>신협</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>우리</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>하나SK</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>광주</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>전북</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>제주</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>산은캐피탈</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>해외비자</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>해외마스터</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>해외다이너스</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>해외AMX</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>해외JCB</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>우체국</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>저축은행</label>
            </value>
            <value>
                <fullName>34</fullName>
                <label>은련</label>
            </value>
            <value>
                <fullName>35</fullName>
                <label>새마을금고</label>
            </value>
            <value>
                <fullName>36</fullName>
                <label>KDB산업</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCard__c/fields/CardNickname__c.field-meta.xml
<CustomField>
    <fullName>CardNickname__c</fullName>
    <label>카드별칭</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCard__c/fields/CardNumber__c.field-meta.xml
<CustomField>
    <fullName>CardNumber__c</fullName>
    <externalId>true</externalId>
    <label>카드번호</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCard__c/fields/EffectiveMonth__c.field-meta.xml
<CustomField>
    <fullName>EffectiveMonth__c</fullName>
    <label>유효년월</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCard__c/fields/RealUser__c.field-meta.xml
<CustomField>
    <fullName>RealUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>실사용자</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CorporateCard</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/CorporateCardBilling__c.object-meta.xml
<CustomObject>
    <label>법인카드청구내역</label>
    <nameField>
        <displayFormat>CB-{YY}{MM}-{00000}</displayFormat>
        <label>법인카드청구내역</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/fields/BillingAmount__c.field-meta.xml
<CustomField>
    <fullName>BillingAmount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>결제금액</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/fields/BillingDate__c.field-meta.xml
<CustomField>
    <fullName>BillingDate__c</fullName>
    <label>결제일시</label>
    <type>DateTime</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/fields/CardNumber__c.field-meta.xml
<CustomField>
    <fullName>CardNumber__c</fullName>
    <label>카드번호</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/fields/CorporateCard__c.field-meta.xml
<CustomField>
    <fullName>CorporateCard__c</fullName>
    <label>법인카드</label>
    <referenceTo>CorporateCard__c</referenceTo>
    <relationshipLabel>법인카드청구내역</relationshipLabel>
    <relationshipName>CorporateCardBilling_CorporateCard</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/fields/StoreBusinessNumber__c.field-meta.xml
<CustomField>
    <fullName>StoreBusinessNumber__c</fullName>
    <label>사업자번호</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/fields/Tax_BusinessType1__c.field-meta.xml
<CustomField>
    <fullName>Tax_BusinessType1__c</fullName>
    <label>업태</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/fields/Tax_BusinessType2__c.field-meta.xml
<CustomField>
    <fullName>Tax_BusinessType2__c</fullName>
    <label>업종</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/fields/Tax_deduction1__c.field-meta.xml
<CustomField>
    <fullName>Tax_deduction1__c</fullName>
    <label>공제여부결정</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/fields/Tax_deduction2__c.field-meta.xml
<CustomField>
    <fullName>Tax_deduction2__c</fullName>
    <label>비고</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/fields/Tax_StoreType__c.field-meta.xml
<CustomField>
    <fullName>Tax_StoreType__c</fullName>
    <label>가맹점유형</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/TaxFileUploadController_test.cls
/**
 * Created by user on 2024-08-14.
 */
@IsTest
public with sharing class TaxFileUploadController_test {

    @IsTest
    static void testGetBillingList() {
        User testUser = new User(
                Alias = 'tuser',
                Email = 'testuser@example.com',
                EmailEncodingKey = 'ISO-8859-1',
                LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US',
                ProfileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1].Id,
                TimeZoneSidKey = 'America/Los_Angeles',
                UserName = 'testuser@example.comMMMMssdfs11',
                LastName = 'ttus'
        );
        insert testUser;
        User retrievedUser = [SELECT Id FROM User WHERE UserName = 'testuser@example.comMMMMssdfs11' LIMIT 1];
        User retrievedUser2 = [SELECT Id FROM User WHERE LastName = '전관우' LIMIT 1];


        CorporateCard__c testCard = new CorporateCard__c(
                Name = '하나 945081******8562',
                CardCompany__c = '03',
                CardNumber__c = '945081******8562',
                CardNickname__c = '별칭',
                EffectiveMonth__c =  '2028.02',
                RealUser__c = retrievedUser2.Id
        );
        insert testCard;

        CorporateCard__c retrievedCard = [SELECT Id FROM CorporateCard__c WHERE Name = '하나 945081******8562' LIMIT 1];

        Date testDate = Date.newInstance(2024, 1, 15);
        CorporateCardBilling__c testBilling = new CorporateCardBilling__c(
                CorporateCard__c = retrievedCard.Id,
                BillingDate__c = testDate,
                StoreBusinessNumber__c = '1234567890',
                BillingAmount__c = 30000
        );
        insert testBilling;

        Test.startTest();
        List<CorporateCardBilling__c> result = TaxFileUploadController.getBillingList(2024, 1);
        Test.stopTest();

        System.assertEquals(1, result.size(), 'There should be one billing record.');
    }
    @IsTest
    static void testUpdateBillingList() {
        User testUser = new User(
                Alias = 'tuser',
                Email = 'testuser@example.com',
                EmailEncodingKey = 'ISO-8859-1',
                LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US',
                ProfileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1].Id,
                TimeZoneSidKey = 'America/Los_Angeles',
                UserName = 'testuser@example.comMMMMssdfs11',
                LastName = 'ttus'
        );
        insert testUser;
        User retrievedUser = [SELECT Id FROM User WHERE UserName = 'testuser@example.comMMMMssdfs11' LIMIT 1];
        User retrievedUser2 = [SELECT Id FROM User LIMIT 1];


        CorporateCard__c testCard = new CorporateCard__c(
                Name = '하나 945081******8562',
                CardCompany__c = '03',
                CardNumber__c = '945081******8562',
                CardNickname__c = '별칭',
                EffectiveMonth__c =  '2028.02',
                RealUser__c = retrievedUser2.Id
        );
        insert testCard;

        CorporateCard__c retrievedCard = [SELECT Id,RealUser__c FROM CorporateCard__c WHERE Name = '하나 945081******8562' LIMIT 1];

        List<CorporateCardBilling__c> testBillingList = new List<CorporateCardBilling__c>();
        Date testDate = Date.newInstance(2024, 1, 15);
        CorporateCardBilling__c testBilling = new CorporateCardBilling__c(
                CorporateCard__c = retrievedCard.Id,
                BillingDate__c = testDate,
                StoreBusinessNumber__c = '1234567890',
                BillingAmount__c = 30000
        );
        testBillingList.add(testBilling);
        CorporateCardBilling__c testBilling2 = new CorporateCardBilling__c(
                CorporateCard__c = retrievedCard.Id,
                BillingDate__c = testDate,
                StoreBusinessNumber__c = '',
                BillingAmount__c = 30000
        );
        testBillingList.add(testBilling2);
        insert testBillingList;

        List<List<String>> data = new List<List<String>>();
        List<String> row = new List<String>();
        row.add('1234567890');    // Business number
        row.add('법인사업자');     // Store Type
        row.add('서비스');       // Business Type 1
        row.add('유료도로운영'); // Business Type 2
        row.add('공제');      // Deduction 1
        row.add('');        // Deduction 2
        data.add(row);
        row = new List<String>();
        row.add('');              // Business number
        row.add('법인사업자');     // Store Type
        row.add('서비스');       // Business Type 1
        row.add('유료도로운영'); // Business Type 2
        row.add('공제');      // Deduction 1
        row.add('');        // Deduction 2

        List<CorporateCardBilling__c> billingList = [SELECT Id, Name, StoreBusinessNumber__c FROM CorporateCardBilling__c];
        Test.startTest();
        Map<String, String> result = TaxFileUploadController.updateBillingList(billingList, data);
        Test.stopTest();

        System.assertEquals(1, result.size(), 'There should be one result.');


        // Validate that the record was updated correctly
        CorporateCardBilling__c updatedBilling = [SELECT Tax_StoreType__c, Tax_BusinessType1__c, Tax_BusinessType2__c, Tax_deduction1__c, Tax_deduction2__c FROM CorporateCardBilling__c WHERE Id = :testBilling.Id];
        System.assertEquals('법인사업자', updatedBilling.Tax_StoreType__c, 'The Store Type should be updated.');
        System.assertEquals('서비스', updatedBilling.Tax_BusinessType1__c, 'The Business Type 1 should be updated.');
        System.assertEquals('유료도로운영', updatedBilling.Tax_BusinessType2__c, 'The Business Type 2 should be updated.');
        System.assertEquals('공제', updatedBilling.Tax_deduction1__c, 'The Deduction 1 should be updated.');

    }
}