PA_Education/TestMenifest/force-app/main/default/objects/CorporateCard__c/CorporateCard__c.object-meta.xml
<CustomObject>
    <label>법인카드</label>
    <nameField>
        <label>법인카드 이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCard__c/fields/CardNickname__c.field-meta.xml
<CustomField>
    <fullName>CardNickname__c</fullName>
    <label>카드별칭</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCard__c/fields/RealUser__c.field-meta.xml
<CustomField>
    <fullName>RealUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>실사용자</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CorporateCard</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/CorporateCardBilling__c.object-meta.xml
<CustomObject>
    <label>법인카드청구내역</label>
    <nameField>
        <displayFormat>CB-{YY}{MM}-{00000}</displayFormat>
        <label>법인카드청구내역</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/fields/BillingAmount__c.field-meta.xml
<CustomField>
    <fullName>BillingAmount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>결제금액</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/fields/BillingDate__c.field-meta.xml
<CustomField>
    <fullName>BillingDate__c</fullName>
    <label>결제일시</label>
    <type>DateTime</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/fields/BusinessType__c.field-meta.xml
<CustomField>
    <fullName>BusinessType__c</fullName>
    <label>업종</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/fields/CorporateCard__c.field-meta.xml
<CustomField>
    <fullName>CorporateCard__c</fullName>
    <label>법인카드</label>
    <referenceTo>CorporateCard__c</referenceTo>
    <relationshipLabel>법인카드청구내역</relationshipLabel>
    <relationshipName>CorporateCardBilling_CorporateCard</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/fields/ExpenseDetail__c.field-meta.xml
<CustomField>
    <fullName>ExpenseDetail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>해당 청구내역이 Expense Detail에 사용되었을 경우 Lookup 필드 해당 Expense Detail로 업데이트</description>
    <label>Expense Detail</label>
    <referenceTo>ExpenseDetail__c</referenceTo>
    <relationshipLabel>법인카드청구내역</relationshipLabel>
    <relationshipName>CorporateCardBilling_ExpenseDetail</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/fields/fm_CardCompany__c.field-meta.xml
<CustomField>
    <fullName>fm_CardCompany__c</fullName>
    <formula>CASE(
     CorporateCard__r.CardCompany__c  ,
    &quot;01&quot;, &quot;비씨&quot;,
    &quot;02&quot;, &quot;국민&quot;,
    &quot;03&quot;, &quot;하나&quot;,
    &quot;04&quot;, &quot;삼성&quot;,
    &quot;06&quot;, &quot;신한&quot;,
    &quot;07&quot;, &quot;현대&quot;,
    &quot;08&quot;, &quot;롯데자사&quot;,
    &quot;11&quot;, &quot;씨티, 한미&quot;,
    &quot;12&quot;, &quot;NH채움&quot;,
    &quot;13&quot;, &quot;수협&quot;,
    &quot;14&quot;, &quot;신협&quot;,
    &quot;15&quot;, &quot;우리&quot;,
    &quot;16&quot;, &quot;하나SK&quot;,
    &quot;21&quot;, &quot;광주&quot;,
    &quot;22&quot;, &quot;전북&quot;,
    &quot;23&quot;, &quot;제주&quot;,
    &quot;24&quot;, &quot;산은캐피탈&quot;,
    &quot;25&quot;, &quot;해외비자&quot;,
    &quot;26&quot;, &quot;해외마스터&quot;,
    &quot;27&quot;, &quot;해외다이너스&quot;,
    &quot;28&quot;, &quot;해외AMX&quot;,
    &quot;29&quot;, &quot;해외JCB&quot;,
    &quot;32&quot;, &quot;우체국&quot;,
    &quot;33&quot;, &quot;저축은행&quot;,
    &quot;34&quot;, &quot;은련&quot;,
    &quot;35&quot;, &quot;새마을금고&quot;,
    &quot;36&quot;, &quot;KDB산업&quot;,
       &quot;&quot; 
)</formula>
    <label>카드사</label>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/fields/StoreAddress__c.field-meta.xml
<CustomField>
    <fullName>StoreAddress__c</fullName>
    <label>소재지</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardBilling__c/fields/StoreName__c.field-meta.xml
<CustomField>
    <fullName>StoreName__c</fullName>
    <label>가맹점명</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardOwner__c/CorporateCardOwner__c.object-meta.xml
<CustomObject>
    <description>법인카드가 무기명 카드인 경우 기간별 소유자 관리 (경비신청 시 소유자별 해당 기간에 대한 청구내역 조회를 위함)</description>
    <label>법인카드 기간별 소유자</label>
    <nameField>
        <displayFormat>CO-{000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardOwner__c/fields/CorporateCard__c.field-meta.xml
<CustomField>
    <fullName>CorporateCard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>법인카드</label>
    <referenceTo>CorporateCard__c</referenceTo>
    <relationshipLabel>법인카드 기간별 소유자</relationshipLabel>
    <relationshipName>CorporateCardOwner_CorporateCard</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardOwner__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>소지종료일</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardOwner__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>소지시작일</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/CorporateCardOwner__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>사용자</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CorporateCardOwner_User</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/ExpenseDetail__c.object-meta.xml
<CustomObject>
    <label>Expense Detail</label>
    <nameField>
        <displayFormat>EPD-{000000}</displayFormat>
        <label>경비신청 상세 ID</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/BillingAmount__c.field-meta.xml
<CustomField>
    <fullName>BillingAmount__c</fullName>
    <label>결제금액</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/BusinessType__c.field-meta.xml
<CustomField>
    <fullName>BusinessType__c</fullName>
    <label>업종</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/Category2__c.field-meta.xml
<CustomField>
    <fullName>Category2__c</fullName>
    <label>비용구분</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category2</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/CorporateCardBilling__c.field-meta.xml
<CustomField>
    <fullName>CorporateCardBilling__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>법인카드청구내역</label>
    <referenceTo>CorporateCardBilling__c</referenceTo>
    <relationshipLabel>Expense Detail</relationshipLabel>
    <relationshipName>CorporateCardBilling</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/StoreAddress__c.field-meta.xml
<CustomField>
    <fullName>StoreAddress__c</fullName>
    <label>소재지</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ExpenseDetail__c/fields/StoreName__c.field-meta.xml
<CustomField>
    <fullName>StoreName__c</fullName>
    <label>가맹점명</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/CardBillingModalController.cls
/**
 * Created by Kwanwoo.Jeon on 2024-01-04.
 */

public without sharing class CardBillingModalController {
    @AuraEnabled
    public static List<Map<String, Object>> getData(Integer intYear, Integer intMonth, String budgetType, List<Id> listSelected){
        Map<String, List<CorporateCardOwner__c>> mapCardOwnerDate = new Map<String, List<CorporateCardOwner__c>>();
        // 기간별 사용자의 경우 종료일이 기준월 -6 보다(12월 조회 시 6월종료 카드부터) 클 때 조회
        for (CorporateCardOwner__c obj: [
                SELECT CorporateCard__c, StartDate__c, EndDate__c
                FROM CorporateCardOwner__c
                WHERE User__c = :UserInfo.getUserId()
                AND EndDate__c >= :Date.newInstance(intYear, intMonth - 6, 1)
        ]){
            if (mapCardOwnerDate.get(obj.CorporateCard__c) == null) {
                mapCardOwnerDate.put(obj.CorporateCard__c, new List<CorporateCardOwner__c>{obj});
            }else{
                mapCardOwnerDate.get(obj.CorporateCard__c).add(obj);
            }
        }

        List<CorporateCardBilling__c> listCCB = new List<CorporateCardBilling__c>();
        // 24.01.22  하형석 이사님 요청으로 사용일자 기준으로 조회되던걸 그 달에 생성된 청구내역 조회하는것 으로 변경

        if (budgetType == '임원 및 감사님') {
            // 사용목적이 임원 및 감사님의 경우 대리상신 반영 : owner가 본인, 실사용 상관X  + 기간별 사용자
            // 자격증 외의 경우 레코드 생성날짜 기준으로 조회
            listCCB = [
                    SELECT  Id, CorporateCard__c, BillingDate__c, CorporateCard__r.CardNickname__c, fm_CardCompany__c, StoreName__c,
                            BusinessType__c, StoreAddress__c, BillingAmount__c, CurrencyIsoCode,
                            CorporateCard__r.RealUser__r.Name, CorporateCard__r.OwnerId
                    FROM    CorporateCardBilling__c
                    WHERE   (ExpenseDetail__c = NULL OR Id IN: listSelected)
                    AND     (CorporateCard__r.OwnerId = :UserInfo.getUserId() OR CorporateCard__c IN: mapCardOwnerDate.keySet())
                    AND     CreatedDate >= :Date.newInstance(intYear, intMonth + 1, 1)
                    AND     CreatedDate < :Date.newInstance(intYear, intMonth + 2, 1)
                    ORDER BY CorporateCard__r.CardNickname__c, BillingDate__c
            ];
        } else if(budgetType == '자격증') {
            // 임원 및 감사님 외의 사용목적은 Owner와 실사용자가 본인 + 기간별 사용자
            // 자격증의 경우 청구날짜 기준으로 조회
            listCCB = [
                    SELECT      Id, CorporateCard__c, BillingDate__c, CorporateCard__r.CardNickname__c, fm_CardCompany__c, StoreName__c,
                                BusinessType__c, StoreAddress__c, BillingAmount__c, CurrencyIsoCode,
                                CorporateCard__r.RealUser__r.Name, CorporateCard__r.OwnerId
                    FROM        CorporateCardBilling__c
                    WHERE       (ExpenseDetail__c = NULL OR Id IN: listSelected)
                    AND         ((CorporateCard__r.OwnerId = :UserInfo.getUserId() AND CorporateCard__r.RealUser__c = :UserInfo.getUserId()) OR CorporateCard__c in: mapCardOwnerDate.keySet())
                    AND         BillingDate__c >= :Date.newInstance(intYear, intMonth, 1)
                    AND         BillingDate__c < :Date.newInstance(intYear, intMonth + 1, 1)
                    ORDER BY    CorporateCard__r.CardNickname__c, BillingDate__c
            ];
        }else{
            // 임원 및 감사님 외의 사용목적은 Owner와 실사용자가 본인 + 기간별 사용자
            // 자격증 외의 경우 레코드 생성날짜 기준으로 조회
            listCCB = [
                    SELECT      Id, CorporateCard__c, BillingDate__c, CorporateCard__r.CardNickname__c, fm_CardCompany__c, StoreName__c,
                                BusinessType__c, StoreAddress__c, BillingAmount__c, CurrencyIsoCode,
                                CorporateCard__r.RealUser__r.Name, CorporateCard__r.OwnerId
                    FROM        CorporateCardBilling__c
                    WHERE       (ExpenseDetail__c = NULL OR Id IN: listSelected)
                    AND         ((CorporateCard__r.OwnerId = :UserInfo.getUserId() AND CorporateCard__r.RealUser__c = :UserInfo.getUserId())
                    OR          CorporateCard__c IN: mapCardOwnerDate.keySet())
                    AND         CreatedDate >= :Date.newInstance(intYear, intMonth + 1, 1)
                    AND         CreatedDate < :Date.newInstance(intYear, intMonth + 2, 1)
                    ORDER BY    CorporateCard__r.CardNickname__c, BillingDate__c
            ];
        }

        if (!mapCardOwnerDate.isEmpty() && !listCCB.isEmpty()) {
            for(Integer i = 0; i < listCCB.size(); i++){
                if (listCCB[i].CorporateCard__r.OwnerId != UserInfo.getUserId() && mapCardOwnerDate.containsKey(listCCB[i].CorporateCard__c)) {
                    Boolean check = false;
                    for (CorporateCardOwner__c objOwner : mapCardOwnerDate.get(listCCB[i].CorporateCard__c)){
                        if (listCCB[i].BillingDate__c >= objOwner.StartDate__c && listCCB[i].BillingDate__c <= objOwner.EndDate__c) {
                            check = true;
                        }
                    }
                    if (!check) {
                        listCCB.remove(i);
                        i--;
                    }
                }
            }
        }

        List<Map<String, Object>> listResult = new List<Map<String, Object>>();
        for (CorporateCardBilling__c obj : listCCB) {
            Map<String, Object> mapResult = new Map<String, Object>();
            mapResult.put('Id',                         obj.Id);
            mapResult.put('CorporateCard',              obj.CorporateCard__c);
            mapResult.put('BillingDate',                String.valueOf(obj.BillingDate__c));
            mapResult.put('CorporateCardNickName',      obj.CorporateCard__r.CardNickname__c);
            mapResult.put('CardCompany',                obj.fm_CardCompany__c);
            mapResult.put('StoreName',                  obj.StoreName__c);
            mapResult.put('BusinessType',               obj.BusinessType__c);
            mapResult.put('StoreAddress',               obj.StoreAddress__c);
            mapResult.put('BillingAmount',              obj.BillingAmount__c);
            mapResult.put('CurrencyIsoCode',            obj.CurrencyIsoCode);
            mapResult.put('CorporateCardRealUserName',  obj.CorporateCard__r.RealUser__r.Name);
            mapResult.put('CorporateCardOwnerId',       obj.CorporateCard__r.OwnerId);

            listResult.add(mapResult);
        }

        return listResult;
    }

    public class DataWrapper{
        public String  Category2 {get;set;}
        public Decimal amount {get;set;}
        public Integer cnt {get;set;}

        public DataWrapper(AggregateResult ar){
            Category2    = (String)ar.get('Category2__c');
            amount       = (Decimal)ar.get('Amount');
            cnt          = (Integer)ar.get('Cnt');
        }
    }
}