PA_Education/TestMenifest/force-app/main/default/objects/CompanyHistory__c/CompanyHistory__c.object-meta.xml
<CustomObject>
    <description>회사 연혁 소개 
홈페이지 노출용 Object</description>
    <label>회사 소개</label>
    <nameField>
        <displayFormat>회사소개-{0000}</displayFormat>
        <label>회사 연혁 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/CompanyHistory__c/fields/OrderNum__c.field-meta.xml
<CustomField>
    <fullName>OrderNum__c</fullName>
    <description>회사 소개 Front Output 순서</description>
    <label>OrderNum</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/RenewalHPDaeuProfile_Test.cls
/************************************************************************************
 * File Name   : RenewalHPDaeuProfile_Test.cls
 * Author      : SungJu.Kang
 * Date        : 2022. 01. 03
 * Target      : RenewalHPDaeuProfile.cls
 * Description : RenewalHPDaeuProfile.cls Test Class
 * Modification Log
 * ===================================================================================
 * Ver      Date            Author              Modification
 * ===================================================================================
   1.0      2022. 01. 03   SungJu.Kang            Create
*************************************************************************************/


@IsTest
private class RenewalHPDaeuProfile_Test {

    @IsTest
    static void itShould() {
        Test.startTest();

        CompanyHistory__c objCompanyHistory = new CompanyHistory__c();
        objCompanyHistory.OrderNum__c = 2;
        insert objCompanyHistory;

        RenewalHPDaeuProfile.doSearchCompanyHistory(true);
        RenewalHPDaeuProfile.doSearchCompanyHistory(false);

        Test.stopTest();


    }

}