PA_Education/TestMenifest/force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>재고</label>
    <nameField>
        <label>재고코드</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Outsoursing__c/Outsoursing__c.object-meta.xml
<CustomObject>
    <label>외주처리</label>
    <nameField>
        <displayFormat>OS{000000}</displayFormat>
        <label>외주처리 코드</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Outsoursing__c/fields/Inventory__c.field-meta.xml
<CustomField>
    <fullName>Inventory__c</fullName>
    <label>재고</label>
    <referenceTo>Inventory__c</referenceTo>
    <relationshipLabel>외주처리</relationshipLabel>
    <relationshipName>Outsoursing</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/OutsoursingResult__c/OutsoursingResult__c.object-meta.xml
<CustomObject>
    <label>외주처리결과</label>
    <nameField>
        <displayFormat>OSR{000000}</displayFormat>
        <label>외주처리결과 코드</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/OutsoursingResult__c/fields/Outsoursing__c.field-meta.xml
<CustomField>
    <fullName>Outsoursing__c</fullName>
    <label>외주처리</label>
    <referenceTo>Outsoursing__c</referenceTo>
    <relationshipLabel>외주처리결과</relationshipLabel>
    <relationshipName>OutsoursingResult</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/OutSoursingUtilTester.cls
/**
 * Object		: OutSoursingUtilTester.cls
 * Function		: 
 * Author		: Yohan.Kang.
 * Date			: 2015.5.31
 * Description	: 
 			OutSoursingUtil.Cls
 */
@isTest
private class OutSoursingUtilTester {
    static testMethod void myUnitTest() {
    	Inventory__c IV = OBjectCreateTester.IV;
    	insert IV;
    	
    	Outsoursing__c OS = new Outsoursing__c();
    	OS.Inventory__c = IV.Id;
    	insert OS;
    	
    	OutsoursingResult__c OSR = new OutsoursingResult__c();
    	OSR.Outsoursing__c = OS.Id;
    	insert OSR;
    	
		OutSoursingUtil con = new OutSoursingUtil();
        con.TestMe();
    }
}