PA_Education/TestMenifest/force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>재고</label>
    <nameField>
        <label>재고코드</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Inventory__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>제조사</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.IsTypePurchase__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>재고</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Inventory__c/fields/CntImport__c.field-meta.xml
<CustomField>
    <fullName>CntImport__c</fullName>
    <defaultValue>0</defaultValue>
    <label>입고수량</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Inventory__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>품목</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>재고</relationshipLabel>
    <relationshipName>Item</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Inventory__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>창고</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>재고</relationshipLabel>
    <relationshipName>Inventory</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>품목</label>
    <nameField>
        <label>품목명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>품목구분</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>제품</fullName>
                <default>true</default>
                <label>제품</label>
            </value>
            <value>
                <fullName>PBA</fullName>
            </value>
            <value>
                <fullName>재공품</fullName>
            </value>
            <value>
                <fullName>부품</fullName>
            </value>
            <value>
                <fullName>Tray</fullName>
            </value>
            <value>
                <fullName>Box</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ProcessInfo__c/ProcessInfo__c.object-meta.xml
<CustomObject>
    <label>제품 BOM</label>
    <nameField>
        <label>이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/ProcessInfo__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>모든 공정 후 생산되는 품목</description>
    <inlineHelpText>모든 공정 후 생산되는 품목</inlineHelpText>
    <label>최종품목</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipName>ProcessInfo</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ProcessInfo__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>TEXT(Item__r.Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>품목구분</label>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ProcessInfoDetail__c/ProcessInfoDetail__c.object-meta.xml
<CustomObject>
    <label>제품 BOM 상세</label>
    <nameField>
        <displayFormat>PID-{000000}</displayFormat>
        <label>공정상세정보 코드</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/ProcessInfoDetail__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>품목</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipName>ProcessInfoDetail</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ProcessInfoDetail__c/fields/ProcessInfo__c.field-meta.xml
<CustomField>
    <fullName>ProcessInfo__c</fullName>
    <label>공정정보</label>
    <referenceTo>ProcessInfo__c</referenceTo>
    <relationshipName>ProcessInfoDetail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>창고</label>
    <nameField>
        <label>창고명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Warehouse__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>구분</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>창고</fullName>
                <default>true</default>
                <label>창고</label>
            </value>
            <value>
                <fullName>공정</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/InventoryManageTester.cls
/**
 * Object		: InventoryManageTester.cls
 * Function		: 
 * Author		: Yohan.Kang.
 * Date			: 2015.2.28
 * Description	: 
 			InventoryManage.Cls
 */
@isTest
private class InventoryManageTester {
    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        
        Account AC = ObjectCreateTester.AC;
        insert AC;
        
        Warehouse__c WH = ObjectCreateTester.WH;
        WH.Type__c = '창고';
        insert WH;
        
        Item__c IT = ObjectCreateTester.IT;
        insert IT;
        
        Item__c subIT = ObjectCreateTester.subIT;
        insert subIT;
        
        ProcessInfo__c PI = ObjectCreateTester.PI;
        insert PI;
        
        ProcessInfoDetail__c PID = ObjectCreateTester.PID;
        insert PID;
        
        Inventory__c IV = ObjectCreateTester.IV;
        insert IV;
        
        Inventory__c subIV = new Inventory__c();
        subIV.Account__c = AC.Id;
        subIV.Warehouse__c = WH.Id;
        subIV.Item__c = subIT.Id;
        subIV.CntImport__c = 100;
        insert subIV;
        
        InventoryManage con = new InventoryManage();
        
        con.MyTest(IT);
    }
}