PA_Education/TestMenifest/force-app/main/default/objects/ApplicationTrainingCenter__c/ApplicationTrainingCenter__c.object-meta.xml
<CustomObject>
    <label>수련원 신청내역</label>
    <nameField>
        <displayFormat>AT-{YYYYMM}-{00}</displayFormat>
        <label>수련원 신청 번호</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/ApplicationTrainingCenter__c/fields/Date1__c.field-meta.xml
<CustomField>
    <fullName>Date1__c</fullName>
    <label>사용일1</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ApplicationTrainingCenter__c/fields/Date2__c.field-meta.xml
<CustomField>
    <fullName>Date2__c</fullName>
    <label>사용일2</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ApplicationTrainingCenter__c/fields/RoomType__c.field-meta.xml
<CustomField>
    <fullName>RoomType__c</fullName>
    <label>객실유형</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>본채</fullName>
            </value>
            <value>
                <fullName>글램핑1</fullName>
            </value>
            <value>
                <fullName>글램핑2</fullName>
            </value>
            <value>
                <fullName>글램핑3</fullName>
            </value>
            <value>
                <fullName>글램핑4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ApplicationTrainingCenter__c/fields/Sort__c.field-meta.xml
<CustomField>
    <fullName>Sort__c</fullName>
    <description>수련원 신청 활성/비활성 관리를 위한 필드 (일반 수련원 신청 레코드의 경우 빈칸). 활성 혹은 비활성인 레코드가 한 개도 없을 경우 수련원 캘린더 화면 표시되지 않음 (활성 혹은 비활성인 레코드 한 개 존재해야 함)</description>
    <inlineHelpText>수련원 신청 활성/비활성 관리를 위한 필드 (일반 수련원 신청 레코드의 경우 빈칸)</inlineHelpText>
    <label>구분</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>True</fullName>
                <label>수련원신청 - 활성</label>
            </value>
            <value>
                <fullName>False</fullName>
                <label>수련원신청 - 비활성</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ApplicationTrainingCenter__c/fields/Special__c.field-meta.xml
<CustomField>
    <fullName>Special__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>임직원 신청이 아닌 특별사유의 경우 체크해주세요</inlineHelpText>
    <label>특별사유</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ApplicationTrainingCenter__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>신청: 수련원 신청 상태, 확정: 수련원 신청 확정 상태, 실패: 수련원 신청 확정실패 상태, 취소: 수련원 신청 확정 이후 취소한 상태</inlineHelpText>
    <label>상태</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>신청</fullName>
                <default>true</default>
                <label>신청</label>
            </value>
            <value>
                <fullName>확정</fullName>
            </value>
            <value>
                <fullName>실패</fullName>
            </value>
            <value>
                <fullName>취소</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ApplicationTrainingCenter__c/fields/UseType__c.field-meta.xml
<CustomField>
    <fullName>UseType__c</fullName>
    <label>사용유형</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1박</fullName>
            </value>
            <value>
                <fullName>2박</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/ApplicationTrainingCenter_tr_test.cls
/**
 * Created by Kwanwoo.Jeon on 2024-03-22.
 */

@IsTest
private class ApplicationTrainingCenter_tr_test {
    @IsTest
    static void testBehavior() {
        Test.startTest();
        ApplicationTrainingCenter__c objATC = new ApplicationTrainingCenter__c(
                RoomType__c = '본채',
                UseType__c = '1박',
                Date1__c = Date.today(),
                Status__c = '확정',
                Sort__c = 'True'
        );
        Database.insert(objATC, false);
        System.debug(Database.delete(objATC, false));

        ApplicationTrainingCenter__c objATC2 = new ApplicationTrainingCenter__c(
                RoomType__c = '본채',
                UseType__c = '1박',
                Date1__c = Date.newInstance(date.today().year(), date.today().month()+1,3),
                Status__c = '신청',
                Special__c = FALSE
        );
        System.debug(Database.insert(objATC2, false));


        ApplicationTrainingCenter__c objATC3 = new ApplicationTrainingCenter__c(
                RoomType__c = '본채',
                UseType__c = '1박',
                Date1__c = Date.newInstance(date.today().year(), date.today().month()+1,3),
                Status__c = '신청',
                Special__c = FALSE
        );
        System.debug('33 :: ' + Database.insert(objATC3, false));

        objATC2.Status__c = '확정';
        Database.update(objATC2, false);

        System.debug('확정33 :: ' + Database.insert(objATC3, false));

        objATC2.Status__c = '취소';
        Database.update(objATC2, false);

        //특수사유 신청
        ApplicationTrainingCenter__c objATCSpecial = new ApplicationTrainingCenter__c(
                RoomType__c = '본채',
                UseType__c = '1박',
                Date1__c = Date.newInstance(date.today().year(), date.today().month()+1,10),
                Date2__c = Date.newInstance(date.today().year(), date.today().month()+1,11),
                Status__c = '확정',
                Special__c = True
        );
        System.debug('objATCSpecial :: ' + Database.insert(objATCSpecial, false));


        ApplicationTrainingCenter__c objATCSpecialTest = new ApplicationTrainingCenter__c(
                RoomType__c = '본채',
                UseType__c = '1박',
                Date1__c = Date.newInstance(date.today().year(), date.today().month()+1,9),
                Date2__c = Date.newInstance(date.today().year(), date.today().month()+1,10),
                Status__c = '확정',
                Special__c = false
        );
        System.debug('objATCSpecialTest :: ' + Database.insert(objATCSpecialTest, false));

        ApplicationTrainingCenter__c objATCSpecialTest2 = new ApplicationTrainingCenter__c(
                RoomType__c = '본채',
                UseType__c = '1박',
                Date1__c = Date.newInstance(date.today().year(), date.today().month()+1,11),
                Status__c = '확정',
                Special__c = false
        );
        System.debug('objATCSpecialTest :: ' + Database.insert(objATCSpecialTest2, false));



        Test.stopTest();

    }
}