PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/DeptPosition__c.field-meta.xml
<CustomField>
    <fullName>DeptPosition__c</fullName>
    <label>직책</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chairman</fullName>
                <label>총괄사장</label>
            </value>
            <value>
                <fullName>CEO</fullName>
                <label>대표이사</label>
            </value>
            <value>
                <fullName>부사장</fullName>
            </value>
            <value>
                <fullName>General Manager</fullName>
                <label>본부장</label>
            </value>
            <value>
                <fullName>Department Head</fullName>
                <label>부서장</label>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Pre-Sales</fullName>
            </value>
            <value>
                <fullName>Business Architecture</fullName>
                <label>Business Architect</label>
            </value>
            <value>
                <fullName>Platform Architecture</fullName>
                <label>Platform Architect</label>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Mgmt Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/MainRole__c.field-meta.xml
<CustomField>
    <fullName>MainRole__c</fullName>
    <label>직무</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Management</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>직급</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>총괄사장</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>대표이사</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>센터장</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>감사</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>부사장</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>전무</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>상무</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>수석</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>이사</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>부장</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>책임</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>차장</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>과장</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>대리</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>선임</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>선임(수습)</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>사원</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>사원(수습)</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>인턴</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItemManage__c/QuoteItemManage__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>견적상세관리</label>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/classes/QuoteItemNewController_test.cls
/************************************************************************************
 * File Name   : QuoteItemNewController_test.cls
 * Author      : Soyoung.Jung 
 * Date        : 2019.01.16
 * Target      : QuoteItemNewController.cls
 * Description : QuoteItemNewController.cls Test Class
 * Modification Log
 * ===================================================================================
 * Ver      Date            Author              Modification
 * ===================================================================================
   1.0      2019.01.16      Soyoung.Jung        Create
*************************************************************************************/

@isTest
private class QuoteItemNewController_test {

	@isTest
	static void itShould() {
		Test.startTest();
		
		Employee__c objEmployee = TestObjectCreator.objEmployee;
		objEmployee.DeptPosition__c = 'Platform Architecture';
		objEmployee.Position__c = '8';
		objEmployee.MainRole__c = 'Developer';
		insert objEmployee;

		QuoteItemNewController.getInitData();
		QuoteItemNewController.getDefaultValue(objEmployee.Id);

		Test.stopTest();
	}

	@testSetup 
	static void setData() {
		QuoteItemManage__c objQuoteItemManage = TestObjectCreator.objQuoteItemManage;
		insert objQuoteItemManage;
    }

}