PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

ListViewButton/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/AddressNumber__c.field-meta.xml
<CustomField>
    <fullName>AddressNumber__c</fullName>
    <label>우편번호</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/CurrentAddress__c.field-meta.xml
<CustomField>
    <fullName>CurrentAddress__c</fullName>
    <label>주거지 주소</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>부서</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Departments</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <inlineHelpText>Org ID(회사 이메일 주소). 외주인력의 경우 개인 또는 소속회사 이메일 주소 입력</inlineHelpText>
    <label>회사 이메일</label>
    <type>Email</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Emergency_Contact__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Contact__c</fullName>
    <inlineHelpText>응급상황 시 연락가능한 전화번호</inlineHelpText>
    <label>비상연락번호</label>
    <type>Phone</type>
</CustomField>

ListViewButton/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>성별</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>남성</fullName>
            </value>
            <value>
                <fullName>여성</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/IdNumber__c.field-meta.xml
<CustomField>
    <fullName>IdNumber__c</fullName>
    <description>주민등록번호</description>
    <inlineHelpText>123456-1234567</inlineHelpText>
    <label>주민등록번호</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/JoinDate__c.field-meta.xml
<CustomField>
    <fullName>JoinDate__c</fullName>
    <description>입사일자</description>
    <label>입사일자</label>
    <type>Date</type>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/MobilePhone__c.field-meta.xml
<CustomField>
    <fullName>MobilePhone__c</fullName>
    <description>휴대폰번호</description>
    <label>휴대전화</label>
    <type>Phone</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>직급</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>총괄사장</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>대표이사</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>센터장</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>감사</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>부사장</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>전무</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>상무</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>수석</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>이사</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>부장</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>책임</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>차장</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>과장</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>대리</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>선임</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>선임(수습)</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>사원</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>사원(수습)</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>인턴</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ListViewButton/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>구분</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>내부직원</fullName>
            </value>
            <value>
                <fullName>외부직원</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>사원 Object를 User Object간 Relationship 생성</inlineHelpText>
    <label>사용자 명</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/User_tr.cls
/**
 * ==================================================================================
 * File Name         : User_tr
 * Author            : yeonlim.jeong
 * Group             : Daeu Nextier
 * Description       :
 * Modification Logs
 * ==================================================================================
 *   Ver     Date          Author           Modification
 * ==================================================================================
 *   1.0   2023-12-19     yeonlim.jeong     User 생성 시 사원 오브젝트 레코드 생성
 *   1.1   2023-01-24     yeonlim.jeong     직책(Position__c)의 Label값을 Title에 Update
**/
public with sharing class User_tr extends TriggerHandler{
    private static List<User> listNew {get; set;}
    private static List<User> listOld {get; set;}
    private static Map<Id, User> mapNew {get; set;}
    private static Map<Id, User> mapOld {get; set;}

    public User_tr() {
        listNew = (List<User>) Trigger.new;
        listOld = (List<User>) Trigger.old;
        mapNew  = (Map<Id, User>) Trigger.newMap;
        mapOld  = (Map<Id, User>) Trigger.oldMap;
    }

    public override void beforeInsert() {
        doSetTitle();
    }

    public override void afterInsert() {
        checkUserId();
    }

    public void checkUserId() {
        Set<Id> setId = new Set<Id>();
        for (User obj : listNew) {
            setId.add(obj.Id);
        }

        if (!setId.isEmpty()) {
            createEmployeeRecord(setId);
        }
    }

    /**
    * Event : after insert
    * Author : Yeonlim
    * Description : User 생성 시 사원 오브젝트 레코드 생성
    */
    @Future
    public static void createEmployeeRecord(Set<Id> setId) {
        List<User> listUser = new List<User>([
                SELECT Id, Type__c, ProfileId, User_PersonalNo__c, Title, PostalCode, User_Address__c, Department, CreatedDate,
                        Email, User_JoinDate__c, MobilePhone, Alias, Position__c, toLabel(Position__c) labelPosition
                FROM User
                WHERE Id IN: setId
        ]);

        Set<String> setProfileId = new Set<String>();
        List<Employee__c> listEmployee = new List<Employee__c>();
        Map<Id, String> mapProfileIdToName = new Map<Id, String>();

        for (User obj : listUser) {
            if (obj.Type__c != null && (obj.Type__c == '내부직원' || obj.Type__c == '외부직원')) {
                setProfileId.add(obj.ProfileId);
            }
        }

        if (!setProfileId.isEmpty()) {
            for (Profile obj : [
                    SELECT Id, Name
                    FROM Profile
                    WHERE Id IN: setProfileId
            ]) {
                mapProfileIdToName.put(obj.Id, obj.Name);
            }

            if (!mapProfileIdToName.isEmpty()) {
                for (User obj : listUser) {
                    String profileName = mapProfileIdToName.get(obj.ProfileId);
                    if (profileName == 'Daeu Nextier Employee' || profileName == 'Daeu Nextier Financial' || profileName.contains('System Admin')) {
                        String gender = '';
                        if (String.isNotBlank(obj.User_PersonalNo__c) && obj.User_PersonalNo__c.length() >= 8) {
                            if (obj.User_PersonalNo__c.substring(7, 8) == '2' || obj.User_PersonalNo__c.substring(7, 8) == '4') {
                                gender = '여성';
                            } else if (obj.User_PersonalNo__c.substring(7, 8) == '1' || obj.User_PersonalNo__c.substring(7, 8) == '3') {
                                gender = '남성';
                            }
                        }

                        Employee__c objEmployee = new Employee__c(
                                AddressNumber__c     = obj.PostalCode,
                                CurrentAddress__c    = obj.User_Address__c,
                                Department__c        = obj.Department,
                                Email__c             = obj.Email,
                                Emergency_Contact__c = '010-',
                                Gender__c            = gender,
                                IdNumber__c          = obj.User_PersonalNo__c,
                                JoinDate__c          = obj.User_JoinDate__c != null && String.valueOf(obj.User_JoinDate__c) != '1900-01-01' ? obj.User_JoinDate__c : Date.valueOf(obj.CreatedDate),
                                MobilePhone__c       = obj.MobilePhone,
                                Name                 = obj.Alias,
                                Position__c          = obj.Position__c,
                                User__c              = obj.Id,
                                Type__c              = obj.Type__c,
                                OwnerId              = obj.Id
                        );
                        listEmployee.add(objEmployee);
                    }
                }

                System.debug('listEmployee : ' + listEmployee);

                if (!listEmployee.isEmpty()) {
                    insert listEmployee;
                }
            }
        }
    }

    /**
    * Event : before insert
    * Author : Yeonlim
    * Description : 직책(Position__c)의 Label값을 Title에 Update
    */
    public void doSetTitle() {
        Schema.SObjectType sobject_type = Schema.getGlobalDescribe().get('User');
        Schema.DescribeSObjectResult sobjectDescribe = sobject_type.getDescribe();
        Map<String, Schema.SObjectField> fieldMap = sobjectDescribe.fields.getMap();

        List<Schema.PicklistEntry> pickListValues = fieldMap.get('Position__c').getDescribe().getPicklistValues();

        Map<String, String> mapValueToLabel = new Map<String, String>();
        for (Schema.PicklistEntry pe : pickListValues) {
            mapValueToLabel.put(pe.getValue(), pe.getLabel());
        }

        for (User obj : listNew) {
            obj.Title = mapValueToLabel.get(obj.Position__c);
        }
    }

}