PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>부서</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Departments</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <inlineHelpText>Org ID(회사 이메일 주소). 외주인력의 경우 개인 또는 소속회사 이메일 주소 입력</inlineHelpText>
    <label>회사 이메일</label>
    <type>Email</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/Holiday__c.object-meta.xml
<CustomObject>
    <label>Holiday</label>
    <nameField>
        <displayFormat>H-{0000}</displayFormat>
        <label>Holiday No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/CarriedOverOfLastYear__c.field-meta.xml
<CustomField>
    <fullName>CarriedOverOfLastYear__c</fullName>
    <defaultValue>0</defaultValue>
    <description>대유넥스티어 연차 계산법 기준이 회계연도로 변경되어 필드 생성 (생성일: 2022-12-27, 생성자: hyunsoo.song@daeunextier.com)

* 필드 설명
이 필드는 매년 12월 31일 23시 00분에 &apos;HolidayLastYearUpdate 매년 12월 31일 업데이트&apos; 스케줄러로 업데이트됨.</description>
    <inlineHelpText>전년도에 발생한 연차일수</inlineHelpText>
    <label>전년도 연차일수</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Holiday</relationshipLabel>
    <relationshipName>Holiday</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/fm_Holiday_rewardRemainDays__c.field-meta.xml
<CustomField>
    <fullName>fm_Holiday_rewardRemainDays__c</fullName>
    <description>2023-12-14 Holiday_rewardRemainDays__c 사용하지 않고 해당 formula 필드로 사용 예정</description>
    <formula>Holiday_reward_Total_Count__c - Holiday_rewardDays__c - Holiday_BenefitPaymentDays__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>총 대체휴가일수 - 대체휴가 사용일수 - 대체휴가 수당 지급일수</inlineHelpText>
    <label>대체휴가 잔여일수</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_FamilyEvent_Count__c.field-meta.xml
<CustomField>
    <fullName>Holiday_FamilyEvent_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>경조휴가</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_LastActivity__c.field-meta.xml
<CustomField>
    <fullName>Holiday_LastActivity__c</fullName>
    <label>최종 사용 내역</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_PublicWorks_Count__c.field-meta.xml
<CustomField>
    <fullName>Holiday_PublicWorks_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>공가 사용일수</description>
    <label>공가</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_rewardDays__c.field-meta.xml
<CustomField>
    <fullName>Holiday_rewardDays__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>올해 대체휴가 사용일수</inlineHelpText>
    <label>대체휴가 사용일수</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_rewardRemainDays__c.field-meta.xml
<CustomField>
    <fullName>Holiday_rewardRemainDays__c</fullName>
    <defaultValue>0</defaultValue>
    <description>2023-12-14 formula 필드로 사용 예정</description>
    <inlineHelpText>총 대체휴가일수 - 대체휴가 사용일수 - 대체휴가 수당 지급일수</inlineHelpText>
    <label>대체휴가 잔여일수 (삭제예정)</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_SickLeave_Count__c.field-meta.xml
<CustomField>
    <fullName>Holiday_SickLeave_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>병가 사용 횟수</description>
    <label>병가</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_Total_Remain__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Total_Remain__c</fullName>
    <description>대유넥스티어 연차 계산법 기준이 회계연도로 변경되어 필드 생성 (생성일: 2022-12-27, 생성자: hyunsoo.song@daeunextier.com)

* 필드 설명
- 신규 입사자 &amp; 기존 입사자
: 올해 월차일수 + 올해 연차일수 + 전년도 연차 잔여일수 + 추가부여일수 - 사용일수</description>
    <formula>BLANKVALUE(Holiday_Monthly_Calculated__c, 0) +  BLANKVALUE(Holiday_Annual_Calculated__c, 0) + BLANKVALUE(HolidayRemainOfLastYear__c, 0) +  Holiday_GivenHolidays__c
-  Holiday_UseDays__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>총 연월차일수 + 추가 부여 일수 - 연월차 사용일수</inlineHelpText>
    <label>연월차 잔여일수</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_Uncountable__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Uncountable__c</fullName>
    <defaultValue>0</defaultValue>
    <label>공무</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_Unpaid__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Unpaid__c</fullName>
    <defaultValue>0</defaultValue>
    <label>무급휴가</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_UseDays__c.field-meta.xml
<CustomField>
    <fullName>Holiday_UseDays__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>올해 연월차 사용일수</inlineHelpText>
    <label>연월차 사용일수</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_WomenHoliday_Count__c.field-meta.xml
<CustomField>
    <fullName>Holiday_WomenHoliday_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>생리휴가 사용일수</description>
    <label>생리휴가</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/HolidayRemainOfLastYear__c.field-meta.xml
<CustomField>
    <fullName>HolidayRemainOfLastYear__c</fullName>
    <defaultValue>0.0</defaultValue>
    <description>대유넥스티어 연차 계산법 기준이 회계연도로 변경되어 필드 생성 (생성일: 2022-12-27, 생성자: hyunsoo.song@daeunextier.com)

* 필드 설명
이 필드는 매년 12월 31일 23시 00분에 &apos;HolidayLastYearUpdate 매년 12월 31일 업데이트&apos; 스케줄러로 업데이트됨.</description>
    <inlineHelpText>전년도에 발생한 연월차 사용 후 잔여일수</inlineHelpText>
    <label>전년도 연월차 잔여일수</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/UseDaysOfLastYear__c.field-meta.xml
<CustomField>
    <fullName>UseDaysOfLastYear__c</fullName>
    <defaultValue>0</defaultValue>
    <description>대유넥스티어 연차 계산법 기준이 회계연도로 변경되어 필드 생성 (생성일: 2022-12-27, 생성자: hyunsoo.song@daeunextier.com)

* 필드 설명
이 필드는 매년 12월 31일 23시 00분에 &apos;HolidayLastYearUpdate 매년 12월 31일 업데이트&apos; 스케줄러로 업데이트됨.</description>
    <inlineHelpText>전년도에 발생한 연월차 사용일수 - 전년도 추가부여일수</inlineHelpText>
    <label>전년도 연월차 사용일수</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/HolidayAction__c.object-meta.xml
<CustomObject>
    <description>HolidayAction__c</description>
    <label>휴가신청</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Departments</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>휴가신청</relationshipLabel>
    <relationshipName>HolidayActionV4Zc</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Days__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Days__c</fullName>
    <inlineHelpText>Women&apos;s Holiday 1.
Alternative Holiday 0.
Other Holidays from 1 to 5.</inlineHelpText>
    <label>Days</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_IsConfirm__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_IsConfirm__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Confirm?</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Parent__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Parent__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Holiday</label>
    <referenceTo>Holiday__c</referenceTo>
    <relationshipName>Holiday_Action</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Type__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Annual Holiday</fullName>
                <label>연차</label>
            </value>
            <value>
                <fullName>Half-day Leave</fullName>
                <label>반차</label>
            </value>
            <value>
                <fullName>Reward Holiday</fullName>
                <label>대체휴가</label>
            </value>
            <value>
                <fullName>Reward Half-Holiday</fullName>
                <label>대체휴가(반차)</label>
            </value>
            <value>
                <fullName>Public Works</fullName>
                <label>공가(공무)</label>
            </value>
            <value>
                <fullName>Family Leave</fullName>
                <label>경조휴가</label>
            </value>
            <value>
                <fullName>Sick Leave</fullName>
                <label>병가(무급)</label>
            </value>
            <value>
                <fullName>Women Holiday</fullName>
                <label>생리휴가</label>
            </value>
            <value>
                <fullName>가족돌봄휴가</fullName>
            </value>
            <value>
                <fullName>출산휴가</fullName>
            </value>
            <value>
                <fullName>휴직</fullName>
            </value>
            <value>
                <fullName>육아휴직</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/Is_Cancled__c.field-meta.xml
<CustomField>
    <fullName>Is_Cancled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>개인 사정으로 인해 승인된 휴가를 취소</description>
    <label>Is Canceled?</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/HolidayAction_tr.cls
/**
 * @description       : 휴가신청 트리거
 * @author            : Kwanwoo.Jeon
 * @group             : DaeuNextier
 * @Test Class        : HolidayActionUpdate_Test.apex
 * Modifications Log
 * Ver   Date         Author                    Modification
 * 1.0   2023-12-14   Kwanwoo.Jeon              기존 트리거 코드 이식 -> 수정 필요 (반복문 내 SOQL 조회문)
 * 1.1   2023-12-14   Kwanwoo.Jeon              대체휴가 신청 시 해당 유저의 일수 대체휴가 사용 필드에 체크
**/

public without sharing class HolidayAction_tr extends TriggerHandler{
    private static List<HolidayAction__c> listNew {get; set;}
    private static List<HolidayAction__c> listOld {get; set;}
    private static Map<Id, HolidayAction__c> mapNew {get; set;}
    private static Map<Id, HolidayAction__c> mapOld {get; set;}

    public HolidayAction_tr() {
        listNew = (List<HolidayAction__c>) Trigger.new;
        listOld = (List<HolidayAction__c>) Trigger.old;
        mapNew  = (Map<Id, HolidayAction__c>) Trigger.newMap;
        mapOld  = (Map<Id, HolidayAction__c>) Trigger.oldMap;
    }

    public override void beforeInsert() {
        methodBeforeInsert();
    }
    public override void beforeUpdate() {
        methodBeforeUpdate();
    }
    public override void afterInsert() {
        methodAfterInsert();
    }
    public override void afterUpdate() {
        doApprovalShareUpdate();
        methodAfterUpdate();
        UsingRewardHoliday();
    }

    // [2023-08-09] 휴가 신청 시, Employee Id 값 설정 (Employee 화면에서 휴가 신청내역 확인을 위함)
    public void methodBeforeInsert() {
        Set<Id> setHoliday = new Set<Id>();
        for (HolidayAction__c objHolidayAction : listNew) {
            if(objHolidayAction.HolidayAction_Parent__c != null) {
                setHoliday.add(objHolidayAction.HolidayAction_Parent__c);
            }
        }

        if(!setHoliday.isEmpty()) {
            Map<Id, Holiday__c> mapHoliday = new Map<Id, Holiday__c>([
                    SELECT Id, Employee__c
                    FROM Holiday__c
                    WHERE Id IN :setHoliday
            ]);
            for (HolidayAction__c objHolidayAction : listNew) {
                objHolidayAction.Employee__c = mapHoliday.get(objHolidayAction.HolidayAction_Parent__c) == null ?
                        null : mapHoliday.get(objHolidayAction.HolidayAction_Parent__c).Employee__c;
            }
        }
    }
    public void methodBeforeUpdate(){
        Map<Id, Holiday__c> hMap = new Map<Id, Holiday__c>();
//        List<HolidayAction__c> haLst = new List<HolidayAction__c>();

        for (HolidayAction__c ha : listNew) {
            Boolean oldStatus = mapOld.get(ha.Id).HolidayAction_IsConfirm__c;
            Boolean newStatus = ha.HolidayAction_IsConfirm__c;
            if (!oldStatus && newStatus) {
                Holiday__c h;
                if (hMap.containsKey(ha.HolidayAction_Parent__c)) {
                    h = hMap.get(ha.HolidayAction_Parent__c);
                } else {
                    h = [SELECT Id, Holiday_Total_Remain__c, Holiday_Uncountable__c, Holiday_Unpaid__c, Holiday_UseDays__c, CarriedOverOfLastYear__c, UseDaysOfLastYear__c, HolidayRemainOfLastYear__c, Holiday_FamilyEvent_Count__c,Holiday_SickLeave_Count__c, Holiday_WomenHoliday_Count__c, Holiday_PublicWorks_Count__c, Holiday_rewardDays__c, fm_Holiday_rewardRemainDays__c FROM Holiday__c WHERE Id = :ha.HolidayAction_Parent__c];
                }

                // 필드를 새로 추가했기 때문에 기존 레코드에서는 null값이여서 null check
                h.Holiday_FamilyEvent_Count__c  = (h.Holiday_FamilyEvent_Count__c == null)  ? 0 : h.Holiday_FamilyEvent_Count__c;
                h.Holiday_SickLeave_Count__c    = (h.Holiday_SickLeave_Count__c == null)    ? 0 : h.Holiday_SickLeave_Count__c;
                h.Holiday_WomenHoliday_Count__c = (h.Holiday_WomenHoliday_Count__c == null) ? 0 : h.Holiday_WomenHoliday_Count__c;
                h.Holiday_PublicWorks_Count__c  = (h.Holiday_PublicWorks_Count__c == null)  ? 0 : h.Holiday_PublicWorks_Count__c;
//                h.Holiday_rewardRemainDays__c   = (h.Holiday_rewardRemainDays__c == null)   ? 0 : h.Holiday_rewardRemainDays__c;
                h.Holiday_rewardDays__c         = (h.Holiday_rewardDays__c == null)         ? 0 : h.Holiday_rewardDays__c;

                // 사용내역 한글로 번역
                List<Schema.PicklistEntry> values = HolidayAction__c.HolidayAction_Type__c.getDescribe().getPicklistValues();
                Map<String,String> statusApiToLabelMap = new Map<String,String>();
                for(Schema.PicklistEntry sp : values) {
                    // Map to hold Picklist API as Key and Picklist Label as Value
                    statusApiToLabelMap.put(sp.getValue(), sp.getLabel());
                }
                System.debug('Label value of picklist >> ' + statusApiToLabelMap.get(ha.HolidayAction_Type__c));

                String lstActStr = statusApiToLabelMap.get(ha.HolidayAction_Type__c) + ' ' + String.valueOf(ha.HolidayAction_Days__c) + '일 사용';

                /**
                 * @author            : hyunsoo.song@daeunextier.com
                 * @description       : 연차 혹은 반차인 경우, 연차 사용일자로 카운팅 (전년도 연차 우선 사용 Control은 formula 필드단에서 함.)
                 * @last modified on  : 2023-01-16
                */
                if (ha.HolidayAction_Type__c == 'Monthly Holiday' || ha.HolidayAction_Type__c == 'Annual Holiday') { // 연월차
                    if(ha.HolidayAction_Days__c > h.Holiday_Total_Remain__c) ha.addError(Label.Cannot_Apply_Holiday);
                    h.Holiday_UseDays__c += ha.HolidayAction_Days__c;
                } else if (ha.HolidayAction_Type__c == 'Half-day Leave') { // 반차
                    if(ha.HolidayAction_Days__c > h.Holiday_Total_Remain__c) ha.addError(Label.Cannot_Apply_Holiday);
                    h.Holiday_UseDays__c += 0.5;
                } else if (ha.HolidayAction_Type__c == 'Reward Holiday') { // 대체휴가
                    if(ha.HolidayAction_Days__c > h.fm_Holiday_rewardRemainDays__c) ha.addError(Label.Cannot_Apply_Reward_Holiday);
                    h.Holiday_rewardDays__c += ha.HolidayAction_Days__c;
//                    h.Holiday_rewardRemainDays__c -= ha.HolidayAction_Days__c;
                } else if (ha.HolidayAction_Type__c == 'Reward Half-Holiday') { // 대체휴가(반차)
                    if(ha.HolidayAction_Days__c > h.fm_Holiday_rewardRemainDays__c) ha.addError(Label.Cannot_Apply_Reward_Holiday);
                    h.Holiday_rewardDays__c += 0.5;
//                    h.Holiday_rewardRemainDays__c -= 0.5;
                } else if (ha.HolidayAction_Type__c == 'Women Holiday') { // 생리휴가
                    h.Holiday_Unpaid__c += ha.HolidayAction_Days__c;
                    h.Holiday_WomenHoliday_Count__c += ha.HolidayAction_Days__c;
                } else if (ha.HolidayAction_Type__c == 'Public Works') { // 공가
                    h.Holiday_Uncountable__c += ha.HolidayAction_Days__c;
                    h.Holiday_PublicWorks_Count__c += ha.HolidayAction_Days__c;
                } else if (ha.HolidayAction_Type__c == 'Family Leave') { // 경조휴가
                    h.Holiday_Uncountable__c += ha.HolidayAction_Days__c;
                    h.Holiday_FamilyEvent_Count__c += ha.HolidayAction_Days__c;
                } else if (ha.HolidayAction_Type__c == 'Sick Leave') { // 병가
                    h.Holiday_Unpaid__c += ha.HolidayAction_Days__c;
                    h.Holiday_SickLeave_Count__c += ha.HolidayAction_Days__c;
                } else {
                    lstActStr = 'Add Alternative Holiday register.';
                }

                h.Holiday_LastActivity__c = lstActStr;
                hMap.put(h.Id, h);
            }

            // 취소 승인 되면 사용처리된 연차를 복구 함
            Boolean oldIsCancled = mapOld.get(ha.Id).Is_Cancled__c;
            Boolean newIsCancled = ha.Is_Cancled__c;

            if (!oldIsCancled && newIsCancled) { // 취소가 승인 false -> true로 바뀜
                Holiday__c h;
                if (hMap.containsKey(ha.HolidayAction_Parent__c)) {
                    h = hMap.get(ha.HolidayAction_Parent__c);
                } else {
                    h = [SELECT Id, Holiday_Uncountable__c, Holiday_Unpaid__c, Holiday_UseDays__c, CarriedOverOfLastYear__c, UseDaysOfLastYear__c, HolidayRemainOfLastYear__c, Holiday_FamilyEvent_Count__c,Holiday_SickLeave_Count__c, Holiday_WomenHoliday_Count__c, Holiday_PublicWorks_Count__c, Holiday_rewardDays__c, fm_Holiday_rewardRemainDays__c FROM Holiday__c WHERE Id = :ha.HolidayAction_Parent__c];
                }

                // 필드를 새로 추가했기 때문에 기존 레코드에서는 null값이여서 null check
                h.Holiday_FamilyEvent_Count__c  = (h.Holiday_FamilyEvent_Count__c == null)  ? 0 : h.Holiday_FamilyEvent_Count__c;
                h.Holiday_SickLeave_Count__c    = (h.Holiday_SickLeave_Count__c == null)    ? 0 : h.Holiday_SickLeave_Count__c;
                h.Holiday_WomenHoliday_Count__c = (h.Holiday_WomenHoliday_Count__c == null) ? 0 : h.Holiday_WomenHoliday_Count__c;
                h.Holiday_PublicWorks_Count__c  = (h.Holiday_PublicWorks_Count__c == null)  ? 0 : h.Holiday_PublicWorks_Count__c;
//                h.Holiday_rewardRemainDays__c   = (h.Holiday_rewardRemainDays__c == null)   ? 0 : h.Holiday_rewardRemainDays__c;
                h.Holiday_rewardDays__c         = (h.Holiday_rewardDays__c == null)         ? 0 : h.Holiday_rewardDays__c;

                List<Schema.PicklistEntry> values = HolidayAction__c.HolidayAction_Type__c.getDescribe().getPicklistValues();
                Map<String,String> statusApiToLabelMap = new Map<String,String>();
                for(Schema.PicklistEntry sp : values) {
                    // Map to hold Picklist API as Key and Picklist Label as Value
                    statusApiToLabelMap.put(sp.getValue(), sp.getLabel());
                }
                System.debug('Label value of picklist>>'+ statusApiToLabelMap.get(ha.HolidayAction_Type__c));

                String lstActStr = statusApiToLabelMap.get(ha.HolidayAction_Type__c) + ' ' + String.valueOf(ha.HolidayAction_Days__c) + '일 승인 취소';

                /**
                 * @author            : hyunsoo.song@daeunextier.com
                 * @description       : 연차 혹은 반차인 경우, 연차 사용일자로 카운팅 (전년도 연차 우선 사용 Control은 formula 필드단에서 함.)
                 * @last modified on  : 2023-01-16
                */
                if (ha.HolidayAction_Type__c == 'Monthly Holiday' || ha.HolidayAction_Type__c == 'Annual Holiday') { // 연월차
                    h.Holiday_UseDays__c -= ha.HolidayAction_Days__c;
                } else if (ha.HolidayAction_Type__c == 'Half-day Leave') { // 반차
                    h.Holiday_UseDays__c -= 0.5;
                } else if (ha.HolidayAction_Type__c == 'Reward Holiday') { // 대체휴가
                    h.Holiday_rewardDays__c -= ha.HolidayAction_Days__c;
//                    h.Holiday_rewardRemainDays__c += ha.HolidayAction_Days__c;
                } else if (ha.HolidayAction_Type__c == 'Reward Half-Holiday') { // 대체휴가(반차)
                    h.Holiday_rewardDays__c -= 0.5;
//                    h.Holiday_rewardRemainDays__c += 0.5;
                } else if (ha.HolidayAction_Type__c == 'Women Holiday') { // 생리휴가
                    h.Holiday_Unpaid__c -= ha.HolidayAction_Days__c;
                    h.Holiday_WomenHoliday_Count__c -= ha.HolidayAction_Days__c;
                } else if (ha.HolidayAction_Type__c == 'Public Works') { // 공가
                    h.Holiday_Uncountable__c -= ha.HolidayAction_Days__c;
                    h.Holiday_PublicWorks_Count__c -= ha.HolidayAction_Days__c;
                } else if (ha.HolidayAction_Type__c == 'Family Leave') { // 경조휴가
                    h.Holiday_Uncountable__c -= ha.HolidayAction_Days__c;
                    h.Holiday_FamilyEvent_Count__c -= ha.HolidayAction_Days__c;
                } else if (ha.HolidayAction_Type__c == 'Sick Leave') { // 병가
                    h.Holiday_Unpaid__c -= ha.HolidayAction_Days__c;
                    h.Holiday_SickLeave_Count__c -= ha.HolidayAction_Days__c;
                } else {
                    lstActStr = 'Add Alternative Holiday register.';
                }

                h.Holiday_LastActivity__c = lstActStr;
                hMap.put(h.Id, h);
            }
        }
//        update haLst;
        update hMap.values();

    }
    public void methodAfterInsert() {
        // 최초 경비 제출을 위한 Method
        ApprovalHolidayShare_tr.doApprovalShareInsert(listNew, mapOld);
    }
    public void doApprovalShareUpdate() {
        ApprovalHolidayShare_tr.doApprovalShareUpdate(listNew, mapOld);
    }

    public void methodAfterUpdate() {
        
        /**
         * @description       : 휴가 사용일수 카운팅 및 최종 승인 시, 사용자의 부서 및 포지션에 따른 이메일 발송
         *                      1) 프로젝트 투입 직원(수신자: 부대표님, 전무님, 해당 사업부장, 관리직원)
         *                      2) 임원 및 PM(수신자: 대표님, 부대표님, 전무님, 전사업부장, 관리직원)
         *                      3) 영업팀 및 본사근무직원(수신자: 대표님, 부대표님, 전무님, 전사업부장, 관리직원)
         * @author            : cj.sohn@daeunextier.com
         * @group             : DaeuNextier
         **/
        // 전체 사업부장 및 관리직원 리스트
        List<Employee__c> emailRecipients = [
                SELECT Id, Department__c, Name, Email__c, toLabel(Position__c)
                FROM Employee__c
                WHERE (DeptPosition__c = 'CEO'                                              //  대표님
                OR DeptPosition__c = '부사장'                                          //  부대표님
                OR DeptPosition__c = 'General Manager'                                //  전무, 상무님
                OR DeptPosition__c = 'Department Head'                                //  사업부장
                OR (Department__c = 'MGMT' AND DeptPosition__c = 'Mgmt Support'))     //  관리부
                AND Status__c = TRUE
        ];

        // 휴가 신청자가 프로젝트에 참여중인 경우, 프로젝트별 데이터 정리
        Set<Id> projectIds = new Set<Id>();
        Map<Id, Id> projectIdByHolidayAction = new Map<Id, Id>();
        for (HolidayAction__c hla : listNew) {
            if (hla.Project__c != null) {
                projectIds.add(hla.Project__c);
                projectIdByHolidayAction.put(hla.Id, hla.Project__c);
            }
        }

        Map<Id, Project__c> projects;
        if (projectIds.size() > 0) {
            projects = new Map<Id, Project__c>([SELECT Id, Name, Business__c FROM Project__c WHERE Id IN:projectIds ORDER BY LastModifiedDate LIMIT 1]);
        }

        List<HolidayAction__c> holidayActions = [
                SELECT Id, Position__c, HolidayAction_UserName__c, HolidayAction_Days__c, Holiday_Date_Detail__c, isSystemJob__c,
                        Name, HolidayAction_Description__c, FirstHolidayRequest__r.Name, Project__c, HolidayAction_Parent__r.Holiday_User__c
                FROM HolidayAction__c
                WHERE Id IN:Trigger.newMap.keySet()
        ];

        // 휴가 신청하는 사원정보 정리
        Set<Id> setUserIds = new Set<Id>();
        for (HolidayAction__c hla : holidayActions) {
            setUserIds.add(hla.HolidayAction_Parent__r.Holiday_User__c);
        }

        Map<Id, Employee__c> mapEmployeeByUserId = new Map<Id, Employee__c>();
        List<Employee__c> listApplicants = [SELECT Id, User__c, toLabel(Position__c) FROM Employee__c WHERE User__c IN:setUserIds];
        for (Employee__c employee : listApplicants) {
            mapEmployeeByUserId.put(employee.User__c, employee);
        }

        // 휴가 승인 시, 내부 관리자에게 이메일 발송
        for (HolidayAction__c hla : holidayActions) {
            if ( hla.isSystemJob__c == true ) continue;
            if (mapOld.get(hla.Id).HolidayAction_IsConfirm__c != mapNew.get(hla.Id).HolidayAction_IsConfirm__c && mapNew.get(hla.Id).HolidayAction_IsConfirm__c == true) {
                if (hla.Project__c != null) {
                    HolidayUtil.sendEmailForConfirmedHoliday(emailRecipients, projects.get(projectIdByHolidayAction.get(hla.Id)), hla, mapEmployeeByUserId.get(hla.HolidayAction_Parent__r.Holiday_User__c));
                } else {
                    HolidayUtil.sendEmailForConfirmedHoliday(emailRecipients, null, hla, mapEmployeeByUserId.get(hla.HolidayAction_Parent__r.Holiday_User__c));
                }
            }
        }
    }


    //대체휴가 시 승인 됐을경우 먼저들어온 대체휴가 부터 차감 로직 구현(대체휴가 사용으로 변경)
    //취소 승인 시 사용 휴가가 0보다 큰 대체휴가들 중 나중에 들어온 것 순으로 사용일자 차감(미사용으로 변경)
    public void UsingRewardHoliday(){
        Map<id, Decimal> mapHolidayToUsedRewardHolidaySum = new Map<id, Decimal>();
        Map<id, Decimal> mapHolidayToUsedRewardHolidayCancledSum = new Map<id, Decimal>();
        for(HolidayAction__c obj: listNew){
            //todo 취소 승인 시 로직  추가 필요
            if((obj.HolidayAction_Type__c == 'Reward Holiday' || obj.HolidayAction_Type__c == 'Reward Half-Holiday')){
                //휴가 승인
                if (obj.HolidayAction_IsConfirm__c && !mapOld.get(obj.Id).HolidayAction_IsConfirm__c) {
                    mapHolidayToUsedRewardHolidaySum.put(obj.HolidayAction_Parent__c, mapHolidayToUsedRewardHolidaySum.get(obj.HolidayAction_Parent__c) == null ? obj.HolidayAction_Days__c : mapHolidayToUsedRewardHolidaySum.get(obj.HolidayAction_Parent__c) + obj.HolidayAction_Days__c);
                //취소 승인
                }else if(obj.Is_Cancled__c && !mapOld.get(obj.Id).Is_Cancled__c){
                    mapHolidayToUsedRewardHolidayCancledSum.put(obj.HolidayAction_Parent__c, mapHolidayToUsedRewardHolidayCancledSum.get(obj.HolidayAction_Parent__c) == null ? obj.HolidayAction_Days__c : mapHolidayToUsedRewardHolidayCancledSum.get(obj.HolidayAction_Parent__c) + obj.HolidayAction_Days__c);
                }
            }
        }
        if (!mapHolidayToUsedRewardHolidaySum.isEmpty() || !mapHolidayToUsedRewardHolidayCancledSum.isEmpty()) {
            Map<String, String> mapUserToHoliday = new Map<String, String>();
            Map<String, String> mapUserToCancledHoliday = new Map<String, String>();
            list<Holiday__c> listHoliday = new List<Holiday__c>([
                                        SELECT Id, Holiday_rewardDays__c, Holiday_User__c
                                        FROM Holiday__c
                                        WHERE Id IN : mapHolidayToUsedRewardHolidaySum.keySet() OR Id IN : mapHolidayToUsedRewardHolidayCancledSum.keySet()]);

            for (Holiday__c objHoliday: listHoliday){
                if (mapHolidayToUsedRewardHolidaySum.keySet().contains(objHoliday.Id)) {
//                    objHoliday.Holiday_rewardDays__c += mapHolidayToUsedRewardHolidaySum.get(objHoliday.Id);
                    mapUserToHoliday.put(objHoliday.Holiday_User__c, objHoliday.Id);
                }

                if (mapHolidayToUsedRewardHolidayCancledSum.keySet().contains(objHoliday.Id)) {
//                    objHoliday.Holiday_rewardDays__c -= mapHolidayToUsedRewardHolidaySum.get(objHoliday.Id);
                    mapUserToCancledHoliday.put(objHoliday.Holiday_User__c, objHoliday.Id);
                }
            }
            System.debug('mapUserToHoliday :: ' + mapUserToHoliday);
            System.debug('mapUserToCancledHoliday :: ' + mapUserToCancledHoliday);
            System.debug('mapHolidayToUsedRewardHolidaySum :: ' + mapHolidayToUsedRewardHolidaySum);


            Map<Id, RewardHoliday__c> mapUpdateReward = new Map<Id, RewardHoliday__c>();

            if (!mapUserToCancledHoliday.isEmpty()) {
                //근무일자가 늦은 대체 휴가부터 복구
                list<RewardHoliday__c> listReward = new List<RewardHoliday__c>([
                        SELECT id, Use_Holiday__c, WorkUser__c
                        FROM RewardHoliday__c
                        WHERE WorkUser__c IN : mapUserToCancledHoliday.keySet()
                        AND Use_Holiday__c > 0
                        ORDER BY WorkingDate__c desc]);
                System.debug('listReward :: ' + listReward);
                if (!listReward.isEmpty()) {
                    for (RewardHoliday__c objReward: listReward){
                        System.debug(' 123 ' + mapHolidayToUsedRewardHolidayCancledSum.get(mapUserToCancledHoliday.get(objReward.WorkUser__c)));
                        if (mapHolidayToUsedRewardHolidayCancledSum.get(mapUserToCancledHoliday.get(objReward.WorkUser__c)) >= 0) {
                            if (objReward.Use_Holiday__c < mapHolidayToUsedRewardHolidayCancledSum.get(mapUserToCancledHoliday.get(objReward.WorkUser__c))) {
                                mapHolidayToUsedRewardHolidayCancledSum.put(mapUserToCancledHoliday.get(objReward.WorkUser__c), mapHolidayToUsedRewardHolidayCancledSum.get(mapUserToCancledHoliday.get(objReward.WorkUser__c)) - objReward.Use_Holiday__c);
                                objReward.Use_Holiday__c = 0;
                            }else{
                                Decimal temp = mapHolidayToUsedRewardHolidayCancledSum.get(mapUserToCancledHoliday.get(objReward.WorkUser__c));
                                mapHolidayToUsedRewardHolidayCancledSum.put(mapUserToCancledHoliday.get(objReward.WorkUser__c), 0);
                                objReward.Use_Holiday__c -= temp;
                            }
                            mapUpdateReward.put(objReward.Id, objReward);
                        }
                    }
                }
            }


            if (!mapUserToHoliday.isEmpty()) {
                //근무일자가 빠른 대체 휴가부터 소진
                list<RewardHoliday__c> listReward = new List<RewardHoliday__c>([
                                        SELECT id, Use_Holiday__c, WorkUser__c, Remain_Holiday__c, OccurHoliday__c
                                        FROM RewardHoliday__c
                                        WHERE WorkUser__c IN : mapUserToHoliday.keySet()
                                        AND (Remain_Holiday__c > 0
                                        OR Id IN :mapUpdateReward.keySet())
                                        ORDER BY WorkingDate__c
                                        ]);


                if (!listReward.isEmpty()) {
                    for (RewardHoliday__c objReward: listReward){
                        if (mapHolidayToUsedRewardHolidaySum.get(mapUserToHoliday.get(objReward.WorkUser__c)) >= 0) {
                            System.debug('mapHolidayToUsedRewardHolidaySum.get(mapUserToHoliday.get(objReward.WorkUser__c)) :: ' + mapHolidayToUsedRewardHolidaySum.get(mapUserToHoliday.get(objReward.WorkUser__c)));

                            if (objReward.Remain_Holiday__c <= mapHolidayToUsedRewardHolidaySum.get(mapUserToHoliday.get(objReward.WorkUser__c))) {
                                mapHolidayToUsedRewardHolidaySum.put(mapUserToHoliday.get(objReward.WorkUser__c), mapHolidayToUsedRewardHolidaySum.get(mapUserToHoliday.get(objReward.WorkUser__c)) - objReward.Remain_Holiday__c);
                                objReward.Use_Holiday__c = objReward.OccurHoliday__c;
                            }else{
                                Decimal temp = mapHolidayToUsedRewardHolidaySum.get(mapUserToHoliday.get(objReward.WorkUser__c));
                                objReward.Use_Holiday__c += temp;
                                mapHolidayToUsedRewardHolidaySum.put(mapUserToHoliday.get(objReward.WorkUser__c), 0);
                            }
                            System.debug('objReward :: ' + objReward);
                            mapUpdateReward.put(objReward.Id, objReward);
                        }
                    }
                }
            }

            System.debug('mapUpdateReward :: ' + mapUpdateReward);
            if (!mapUpdateReward.isEmpty()) {
                update mapUpdateReward.values();
            }
        }
    }


}