PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(ISBLANK( ExitDate__c) ||  ExitDate__c    &gt;    TODAY()  , TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>재직여부</label>
    <type>Checkbox</type>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>사원 Object를 User Object간 Relationship 생성</inlineHelpText>
    <label>사용자 명</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWork__c/HolidayWork__c.object-meta.xml
<CustomObject>
    <label>휴일근무</label>
    <nameField>
        <label>휴일근무이름 (자동입력)</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWork__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>근무 월</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1월</fullName>
            </value>
            <value>
                <fullName>2월</fullName>
            </value>
            <value>
                <fullName>3월</fullName>
            </value>
            <value>
                <fullName>4월</fullName>
            </value>
            <value>
                <fullName>5월</fullName>
            </value>
            <value>
                <fullName>6월</fullName>
            </value>
            <value>
                <fullName>7월</fullName>
            </value>
            <value>
                <fullName>8월</fullName>
            </value>
            <value>
                <fullName>9월</fullName>
            </value>
            <value>
                <fullName>10월</fullName>
            </value>
            <value>
                <fullName>11월</fullName>
            </value>
            <value>
                <fullName>12월</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWork__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>휴일근무</relationshipLabel>
    <relationshipName>Project2</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWork__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>단계</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>계획작성중</fullName>
                <default>true</default>
                <label>계획작성중</label>
            </value>
            <value>
                <fullName>계획승인요청</fullName>
            </value>
            <value>
                <fullName>계획승인</fullName>
            </value>
            <value>
                <fullName>계획취소승인요청</fullName>
            </value>
            <value>
                <fullName>근무승인요청</fullName>
            </value>
            <value>
                <fullName>근무승인</fullName>
            </value>
            <value>
                <fullName>승인거절</fullName>
                <isActive>false</isActive>
                <label>승인거절</label>
            </value>
            <value>
                <fullName>승인완료</fullName>
                <isActive>false</isActive>
                <label>승인완료</label>
            </value>
            <value>
                <fullName>승인요청</fullName>
                <isActive>false</isActive>
                <label>승인요청</label>
            </value>
            <value>
                <fullName>작성중</fullName>
                <isActive>false</isActive>
                <label>작성중</label>
            </value>
            <value>
                <fullName>취소승인완료</fullName>
                <isActive>false</isActive>
                <label>취소승인완료</label>
            </value>
            <value>
                <fullName>취소승인요청</fullName>
                <isActive>false</isActive>
                <label>취소승인요청</label>
            </value>
            <value>
                <fullName>회수</fullName>
                <isActive>false</isActive>
                <label>회수</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWork__c/fields/WorkingTime__c.field-meta.xml
<CustomField>
    <fullName>WorkingTime__c</fullName>
    <label>근무일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWork__c/fields/WorkOrderUser__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>1차 승인자</label>
    <referenceTo>User</referenceTo>
    <relationshipName>HolidayWorkUser</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWork__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>근무년도</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2022년</fullName>
            </value>
            <value>
                <fullName>2023년</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWorkDetail__c/HolidayWorkDetail__c.object-meta.xml
<CustomObject>
    <label>휴일근무 상세</label>
    <nameField>
        <displayFormat>HW-{YY}{MM}-{0000}</displayFormat>
        <label>휴일근무 상세 코드</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWorkDetail__c/fields/HolidayWork__c.field-meta.xml
<CustomField>
    <fullName>HolidayWork__c</fullName>
    <label>휴일근무</label>
    <referenceTo>HolidayWork__c</referenceTo>
    <relationshipName>HWD_HolidayWork</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWorkDetail__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트 명</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>HolidayWorkDetailProject</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWorkDetail__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>진행단계</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Design &amp; Build</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
            <value>
                <fullName>Deploy</fullName>
            </value>
            <value>
                <fullName>Closing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWorkDetail__c/fields/WorkDetail__c.field-meta.xml
<CustomField>
    <fullName>WorkDetail__c</fullName>
    <label>작업내용</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWorkDetail__c/fields/WorkingDate__c.field-meta.xml
<CustomField>
    <fullName>WorkingDate__c</fullName>
    <label>근무일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWorkDetail__c/fields/WorkingTime__c.field-meta.xml
<CustomField>
    <fullName>WorkingTime__c</fullName>
    <label>근무시간</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>4</fullName>
                <label>0.5일 (4시간)</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>1일 (8시간)</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>근무하지 않음</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWorkDetail__c/fields/WorkOrderUser__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>작업지시자</label>
    <referenceTo>User</referenceTo>
    <relationshipName>HolidayWorkDetailUser</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWorkDetail__c/fields/WorkUser__c.field-meta.xml
<CustomField>
    <fullName>WorkUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>휴일근무자</label>
    <referenceTo>User</referenceTo>
    <relationshipName>HolidayWorkUserDetail</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/PerformProject__c.object-meta.xml
<CustomObject>
    <label>프로젝트 수행팀</label>
    <nameField>
        <displayFormat>PJ-{0000}</displayFormat>
        <label>Seq</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>프로젝트에 참여한 사원 이름</inlineHelpText>
    <label>사원 명</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>수행 프로젝트</relationshipLabel>
    <relationshipName>EmployeePerformPjt</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/IsPM__c.field-meta.xml
<CustomField>
    <fullName>IsPM__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PM여부</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트 명</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>프로젝트 수행팀</relationshipLabel>
    <relationshipName>Project</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>프로젝트에 대한 기본정보를 관리하며, Deal Closing 이후 생성한다. 영업담당자가 계약 체결 후 기초 데이터를 작성하며, 프로젝트 진행 중에는 PM이 관리하고, 대금청구/지급 관련 정보는 회계에서 관리한다.</description>
    <label>프로젝트</label>
    <nameField>
        <label>프로젝트 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <label>사업부</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Departments</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/fields/PM__c.field-meta.xml
<CustomField>
    <fullName>PM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트 관리자</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PM</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/recordTypes/Project.recordType-meta.xml
<RecordType>
    <fullName>Project</fullName>
    <active>true</active>
    <description>프로젝트 사항 입력하는 Record Type</description>
    <label>프로젝트</label>
</RecordType>

PA_Education/TestMenifest/force-app/main/default/classes/HolidayWorkDetailTrigger_Test.cls
/**
 * @description       : HolidayWorkDetailTrigger.trigger에 대한 Test Class
 * @author            : jinwoo.jang@daeunextier.com
 * @group             : DaeuNextier
 * Modifications Log 
 * Ver   Date         Author                        Modification
 * 1.0   2023-02-08   jinwoo.jang@daeunextier.com   Initial Version
**/
@IsTest
private class HolidayWorkDetailTrigger_Test {
    @TestSetup
    static void testSetup() {
        Profile objProfile = [SELECT Id, Name FROM Profile WHERE Name = 'Daeu Nextier Employee' LIMIT 1];
        User objUser = TestObjectCreator.objUser;
        objUser.Username = 'test@demo.co.kr';
        insert objUser;
    }

    @IsTest
    static void testInsertHolidayWork() {
        User objUser = [SELECT Id, UserRole.Name FROM User ORDER BY CreatedDate DESC LIMIT 1];

        Test.startTest();
        System.runAs(objUser) {
            HolidayWork__c objHW = new HolidayWork__c();
            objHW.Status__c = '계획승인';
            objHW.Month__c = '2월';
            objHW.Year__c = '2023년';
            objHW.WorkOrderUser__c = objUser.Id;
            insert objHW;

            HolidayWorkDetail__c objHWD = new HolidayWorkDetail__c();
            objHWD.HolidayWork__c   = objHW.Id;
            objHWD.WorkUser__c      = objUser.Id;
            objHWD.Stage__c         = 'Design & Build';
            objHWD.WorkingDate__c   = Date.newInstance(2023, 2, 22);
            objHWD.WorkingTime__c   = '4';
            objHWD.WorkDetail__c    = '작업 내용';
            insert objHWD;

            objHWD.WorkUser__c = objUser.Id;
            update objHWD;
        }

        Test.stopTest();
    }

    @IsTest
    static void testInsertHolidayWork2() {
            User objUser = [SELECT Id, Username FROM User ORDER BY CreatedDate DESC LIMIT 1];

            Test.startTest();
            System.runAs(objUser) {
                Project__c project = TestObjectCreator.objProject;
                project.Business__c = 'LG Service';
                insert project;

                Employee__c objEmployee = TestObjectCreator.objEmployee;
                objEmployee.User__c = objUser.Id;
                insert objEmployee;

                PerformProject__c objPP = new PerformProject__c();
                objPP.Project__c  = project.Id;
                objPP.Employee__c = objEmployee.Id;
                objPP.IsPM__c = true;
                insert objPP;

                HolidayWork__c objHW2 = new HolidayWork__c();
                objHW2.Project__c       = project.Id;
                objHW2.Status__c        = '계획작성중';
                objHW2.Month__c         = '2월';
                objHW2.Year__c          = '2023년';
                objHW2.WorkOrderUser__c = objUser.Id;
                insert objHW2;

                HolidayWorkDetail__c objHWD = new HolidayWorkDetail__c();
                objHWD.HolidayWork__c   = objHW2.Id;
                objHWD.WorkUser__c      = objUser.Id;
                objHWD.Stage__c         = 'Design & Build';
                objHWD.WorkingDate__c   = Date.newInstance(2023, 2, 22);
                objHWD.WorkDetail__c    = '작업 내용';
                insert objHWD;

                HolidayWorkDetail__c objHWD2 = objHWD.clone();
                insert objHWD2;

                update objHWD;
            }

            Test.stopTest();
    }

    @IsTest
    static void testInsertHolidayWork3() {
        Test.startTest();
        Project__c project = TestObjectCreator.objProject;
        project.PM__c = UserInfo.getUserId();
        project.Business__c = 'LG Service';
        project.PM__c = UserInfo.getUserId();
        insert project;

        HolidayWork__c objHW2 = new HolidayWork__c();
        objHW2.Project__c = project.Id;
        objHW2.Status__c = '계획작성중';
        objHW2.Month__c = '2월';
        objHW2.Year__c = '2023년';
        objHW2.WorkOrderUser__c = UserInfo.getUserId();
        insert objHW2;

        HolidayWorkDetail__c objHWD = new HolidayWorkDetail__c();
        objHWD.HolidayWork__c   = objHW2.Id;
        objHWD.WorkUser__c      = UserInfo.getUserId();
        objHWD.Stage__c         = 'Design & Build';
        objHWD.WorkingDate__c   = Date.newInstance(2023, 2, 22);
        objHWD.WorkDetail__c    = '작업 내용';
        insert objHWD;

        Test.stopTest();
    }
}