PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Qualification__c/Qualification__c.object-meta.xml
<CustomObject>
    <label>자격사항</label>
    <nameField>
        <label>자격명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Qualification__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>사원 명</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>자격사항</relationshipLabel>
    <relationshipName>Re_License</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Qualification__c/fields/ExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>ExpirationDate__c</fullName>
    <label>만료일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/ContentDocumentLink_tr_test.cls
/**
 * Created by 최지수 on 2022-12-28.
 */
@IsTest
private with sharing class ContentDocumentLink_tr_test {
    @IsTest
    static void doTest(){
        String myString = 'StringToBlob';
        Blob myBlob = Blob.valueOf(myString);

        Employee__c ep = new Employee__c();
        ep.Id = null;
        insert ep;

        Qualification__c Qlf = new Qualification__c();
        Qlf.Employee_Name__c = ep.Id;
        Qlf.ExpirationDate__c = Date.newInstance(2099, 12, 31);
        insert Qlf;

        ContentVersion cv = new ContentVersion();
        cv.Title = 'test';
        cv.PathOnClient = 'test';
        cv.VersionData = myBlob;
        insert cv;

        Test.startTest();
        ContentDocumentLink Cdl = new ContentDocumentLink(
                ContentDocumentId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv.Id].ContentDocumentId,
                LinkedEntityId = Qlf.Id
        );
        insert Cdl;
        Test.stopTest();
    }
}