PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/FormRequest__c/FormRequest__c.object-meta.xml
<CustomObject>
    <description>재직증명서등(추후 추가될 수 있음)을 요청
승인 출력하기위한 오브젝트</description>
    <label>증명서</label>
    <nameField>
        <displayFormat>DNT. {YY}-{MM}{000}</displayFormat>
        <label>문서번호</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/FormRequest__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <label>사원 명</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>증명서</relationshipLabel>
    <relationshipName>FormRequest_Employee</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/FormRequest__c/fields/EngName__c.field-meta.xml
<CustomField>
    <fullName>EngName__c</fullName>
    <label>사원 명(영문)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/FormRequest__c/fields/FormRequest_Purpose__c.field-meta.xml
<CustomField>
    <fullName>FormRequest_Purpose__c</fullName>
    <label>용도</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/FormRequest__c/fields/FormRequest_Title__c.field-meta.xml
<CustomField>
    <fullName>FormRequest_Title__c</fullName>
    <defaultValue>$User.Title</defaultValue>
    <inlineHelpText>사용자 정보에 있는 값이 기본값이며 
값이 없거나 다를 경우 입력하세요.</inlineHelpText>
    <label>직급</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/FormRequest__c/fields/FormRequest_ToSubmit__c.field-meta.xml
<CustomField>
    <fullName>FormRequest_ToSubmit__c</fullName>
    <label>제출처</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/FormRequest__c/fields/FormRequest_Type__c.field-meta.xml
<CustomField>
    <fullName>FormRequest_Type__c</fullName>
    <description>신청문서</description>
    <inlineHelpText>신청하는 문서의 종류를 선택하세요.
(재직증명서 외 필요한 문서가 있을 경우 개발의뢰 요청하세요.)</inlineHelpText>
    <label>신청문서</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>재직증명서</fullName>
                <default>true</default>
                <label>재직증명서</label>
            </value>
            <value>
                <fullName>경력증명서</fullName>
                <isActive>false</isActive>
                <label>경력증명서</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/FormRequest__c/fields/LanguageType__c.field-meta.xml
<CustomField>
    <fullName>LanguageType__c</fullName>
    <label>구분</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>국문</fullName>
            </value>
            <value>
                <fullName>영문</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/FormRequestControllerTest.cls
/**
 * Created by choiyuna on 2022-11-14.
 */
@IsTest
public with sharing class FormRequestControllerTest {
    @IsTest(SeeAllData=true)
    public static void test() {
        Test.startTest();

        createPageRefByRecordId(createFormRequestRecord('대표이사').Id);
        System.assertEquals('CEO', getFormRequestController().title_Eng);

        createPageRefByRecordId(createFormRequestRecord('부사장').Id);
        System.assertEquals('Vice President', getFormRequestController().title_Eng);

        createPageRefByRecordId(createFormRequestRecord('전무').Id);
        System.assertEquals('Executive Vice President', getFormRequestController().title_Eng);

        createPageRefByRecordId(createFormRequestRecord('상무').Id);
        System.assertEquals('Managing Director', getFormRequestController().title_Eng);

        createPageRefByRecordId(createFormRequestRecord('이사').Id);
        System.assertEquals('Director', getFormRequestController().title_Eng);

        //todo test
        createPageRefByRecordId(createFormRequestRecord('부장').Id);
        System.assertEquals('General Manager', getFormRequestController().title_Eng);

        createPageRefByRecordId(createFormRequestRecord('차장').Id);
        System.assertEquals('Deputy General Manager', getFormRequestController().title_Eng);

        createPageRefByRecordId(createFormRequestRecord('과장').Id);
        System.assertEquals('Manager', getFormRequestController().title_Eng);

        createPageRefByRecordId(createFormRequestRecord('대리').Id);
        System.assertEquals('Assistant Manager', getFormRequestController().title_Eng);

        createPageRefByRecordId(createFormRequestRecord('사원').Id);
        System.assertEquals('Staff', getFormRequestController().title_Eng);

        createPageRefByRecordId(createFormRequestRecord('센터장').Id);
        System.assertEquals('Head of GDC center', getFormRequestController().title_Eng);

        createPageRefByRecordId(createFormRequestRecord('인턴').Id);
        System.assertEquals('Intern', getFormRequestController().title_Eng);

        Test.stopTest();
    }

    public static FormRequest__c createFormRequestRecord(String testTitle) {
        Employee__c testEmployee = new Employee__c();
        testEmployee.Name = '김김김';
        insert testEmployee;

        FormRequest__c testFormRequest = new FormRequest__c();
        testFormRequest.EngName__c = 'kimyee';
        testFormRequest.FormRequest_Type__c = '재직증명서';
        testFormRequest.FormRequest_Purpose__c = 'test';
        testFormRequest.FormRequest_ToSubmit__c = 'test';
        testFormRequest.Employee_Name__c = testEmployee.Id;
        testFormRequest.FormRequest_Title__c = testTitle;
        testFormRequest.LanguageType__c = '국문';
        insert testFormRequest;

        return testFormRequest;
    }

    public static void createPageRefByRecordId(Id recordId) {
        PageReference pageRef = Page.FormRequestRenderPageEng;
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('id', recordId);
    }

    public static FormRequestController getFormRequestController() {
        FormRequest__c objFormRequest = new FormRequest__c();
        objFormRequest.LanguageType__c = '국문';

        return new FormRequestController(new ApexPages.StandardController(objFormRequest));
    }

}