PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>사원 Object를 User Object간 Relationship 생성</inlineHelpText>
    <label>사용자 명</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/PerformProject__c.object-meta.xml
<CustomObject>
    <label>프로젝트 수행팀</label>
    <nameField>
        <displayFormat>PJ-{0000}</displayFormat>
        <label>Seq</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>프로젝트에 참여한 사원 이름</inlineHelpText>
    <label>사원 명</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>수행 프로젝트</relationshipLabel>
    <relationshipName>EmployeePerformPjt</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/Fm_First_Evaluation_Check__c.field-meta.xml
<CustomField>
    <fullName>Fm_First_Evaluation_Check__c</fullName>
    <description>외부직원이며 투입일자가 30일이 경과 했을 경우 1차 평가 발송을 위한 포뮬라 필드</description>
    <formula>IF(
				AND(ISPICKVAL(Employee__r.Type__c, &apos;외부직원&apos;), 
								(TODAY() - InputDate__c &gt; 29)
								),
				TRUE,
				FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>1차평가 필요여부</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트 명</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>프로젝트 수행팀</relationshipLabel>
    <relationshipName>Project</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>프로젝트에 대한 기본정보를 관리하며, Deal Closing 이후 생성한다. 영업담당자가 계약 체결 후 기초 데이터를 작성하며, 프로젝트 진행 중에는 PM이 관리하고, 대금청구/지급 관련 정보는 회계에서 관리한다.</description>
    <label>프로젝트</label>
    <nameField>
        <label>프로젝트 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/fields/PM__c.field-meta.xml
<CustomField>
    <fullName>PM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트 관리자</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PM</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/fields/PMEmail__c.field-meta.xml
<CustomField>
    <fullName>PMEmail__c</fullName>
    <label>PMEmail</label>
    <type>Email</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/PerformProject_tr.cls
/************************************************************************************
* File Name   	    : PerformProject_tr
* Author	  		: Yeonlim
* Date				: 2024-01-02
* Modification Log
* ===================================================================================
* Ver      Date            Author          Modification
* ===================================================================================
* 1.0      2024-01-02      Yeonlim          Create (기존 Trigger Handler 이식 + Approval Line 업데이트)
************************************************************************************/
public without sharing class PerformProject_tr extends TriggerHandler {
    public PerformProject_tr() {
        listNew = (List<PerformProject__c>) Trigger.new;
        listOld = (List<PerformProject__c>) Trigger.old;
        mapNew = (Map<Id, PerformProject__c>) Trigger.newMap;
        mapOld = (Map<Id, PerformProject__c>) Trigger.oldMap;
    }

    /** TriggerHandler */
    private List<PerformProject__c> listNew { get; set; }
    private List<PerformProject__c> listOld { get; set; }
    private Map<Id, PerformProject__c> mapNew { get; set; }
    private Map<Id, PerformProject__c> mapOld { get; set; }

    public override void afterInsert() {
        updateApprovalLine();
    }
    public override void beforeUpdate() {
        sendPMEmail();
    }
    public override void afterUpdate() {
        updateApprovalLine();
    }

    /**
    * Event : after insert, after update
    * Author : Yeonlim
    * Description : 프로젝트 수행팀 변경 시 Approval Line1에 휴가신청라인 업데이트
    */
    private void updateApprovalLine() {
        Map<Id, Id> mapEmployeeToProject = new Map<Id, Id>();
        for(PerformProject__c obj : listNew){
            if (obj.Project__c != null && obj.Employee__c != null) {
                if (Trigger.isInsert || mapOld.get(obj.Id).Employee__c != obj.Employee__c) {
                    mapEmployeeToProject.put(obj.Employee__c, obj.Project__c);
                }
            }
        }

        if (!mapEmployeeToProject.isEmpty()) {
            Map<Id, Id> mapProjectToPM = new Map<Id, Id>();
            for(Project__c obj : [
                    SELECT Id, PM__c
                    FROM Project__c
                    WHERE Id IN: mapEmployeeToProject.values()
            ]) {
                mapProjectToPM.put(obj.Id, obj.PM__c);
            }

            Map<Id, Id> mapUserToEmployee = new Map<Id, Id>();
            for (Employee__c obj : [
                    SELECT Id, User__c
                    FROM Employee__c
                    WHERE Id IN: mapEmployeeToProject.keySet()
            ]) {
                mapUserToEmployee.put(obj.User__c, obj.Id);
            }

            List<User> listUser = new List<User>();
            for (User obj : [
                    SELECT Id, ApprovalLine1__c
                    FROM User
                    WHERE Id IN: mapUserToEmployee.keySet()
            ]) {
                User objUser = new User(
                        Id = obj.Id,
                        ApprovalLine1__c = '휴가신청라인/ApprovalLine1/' + mapProjectToPM.get(mapEmployeeToProject.get(mapUserToEmployee.get(obj.Id)))
                );
                listUser.add(objUser);
            }

            if (!listUser.isEmpty()) {
                update listUser;
            }
        }
    }

    /**
    * Event : before update
    * Author : Yeojin
    * Description : [2023-07-10 추가] 1차평가 필요여부 = true 일때, 투입인력 평가 이메일 전송
    */
    private void sendPMEmail() {
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();

        List<String> setEmail = new List<String>();
        List<String> setProjectId = new List<String>();
        String projectName = '';

        for (PerformProject__c obj : listNew) {
            if(mapOld.get(obj.Id).Fm_First_Evaluation_Check__c == false && obj.Fm_First_Evaluation_Check__c == true){
                setProjectId.add(obj.Project__c);
            }
        }

        if(!setProjectId.isEmpty()){
            List<Project__c> projectList = [
                    SELECT PMEmail__c, Name
                    FROM Project__c
                    WHERE Id =: setProjectId
                    LIMIT 1
            ];

            if(!projectList.isEmpty()){
                setEmail.add(projectList[0].PMEmail__c);
                projectName = projectList[0].Name;
            }

            if(!setEmail.isEmpty()){
                email.setToAddresses(setEmail);
                email.setSubject('[' + projectList[0].Name + '] 프로젝트 외주인력평가 안내');
                String body = '안녕하세요, <br/>';
                body += '[' + projectList[0].Name + '] 프로젝트 투입 1개월차 외주인력 평가를 진행해 주시기 바랍니다. <br/><br/>';
                body += '아래 링크를 누르시면 해당 프로젝트 레코드로 이동합니다. <br/>';
                body += '화면에서 [투입인력평가서] 버튼을 누르신 후 평가를 진행해주시기 바랍니다.';
                body += 'https://daeunextier.lightning.force.com/lightning/r/Project__c/' + listNew[0].Id + '/view <br/><br/>';
                body += '감사합니다.';
                email.setHtmlBody(body);

                OrgWideEmailAddress[] owea = [SELECT Id FROM OrgWideEmailAddress WHERE Address = 'admin@daeunextier.com'];
                System.debug('owea : ' + owea);
                if ( owea.size() > 0 ) {
                    email.setOrgWideEmailAddressId(owea.get(0).Id);
                }

                try{
                    if(!Test.isRunningTest()) Messaging.sendEmail(new Messaging.SingleEmailMessage[] { email });
                    System.debug('success');
                }catch(Exception e){
                    System.debug('error');
                }
            }
        }
    }
}