PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>부서</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Departments</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>직급</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>총괄사장</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>대표이사</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>센터장</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>감사</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>부사장</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>전무</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>상무</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>수석</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>이사</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>부장</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>책임</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>차장</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>과장</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>대리</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>선임</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>선임(수습)</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>사원</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>사원(수습)</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>인턴</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>사원 Object를 User Object간 Relationship 생성</inlineHelpText>
    <label>사용자 명</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/Holiday__c.object-meta.xml
<CustomObject>
    <label>Holiday</label>
    <nameField>
        <displayFormat>H-{0000}</displayFormat>
        <label>Holiday No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Holiday</relationshipLabel>
    <relationshipName>Holiday</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_User__c.field-meta.xml
<CustomField>
    <fullName>Holiday_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>임직원</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Holiday</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/HolidayAction__c.object-meta.xml
<CustomObject>
    <description>HolidayAction__c</description>
    <label>휴가신청</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Departments</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>휴가신청</relationshipLabel>
    <relationshipName>HolidayActionV4Zc</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/FirstHolidayRequest__c.field-meta.xml
<CustomField>
    <fullName>FirstHolidayRequest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>1차 승인자 지정</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Holiday_Action1</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Date1__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Date1__c</fullName>
    <label>Date1</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Days__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Days__c</fullName>
    <inlineHelpText>Women&apos;s Holiday 1.
Alternative Holiday 0.
Other Holidays from 1 to 5.</inlineHelpText>
    <label>Days</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Parent__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Parent__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Holiday</label>
    <referenceTo>Holiday__c</referenceTo>
    <relationshipName>Holiday_Action</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Type__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Annual Holiday</fullName>
                <label>연차</label>
            </value>
            <value>
                <fullName>Half-day Leave</fullName>
                <label>반차</label>
            </value>
            <value>
                <fullName>Reward Holiday</fullName>
                <label>대체휴가</label>
            </value>
            <value>
                <fullName>Reward Half-Holiday</fullName>
                <label>대체휴가(반차)</label>
            </value>
            <value>
                <fullName>Public Works</fullName>
                <label>공가(공무)</label>
            </value>
            <value>
                <fullName>Family Leave</fullName>
                <label>경조휴가</label>
            </value>
            <value>
                <fullName>Sick Leave</fullName>
                <label>병가(무급)</label>
            </value>
            <value>
                <fullName>Women Holiday</fullName>
                <label>생리휴가</label>
            </value>
            <value>
                <fullName>가족돌봄휴가</fullName>
            </value>
            <value>
                <fullName>출산휴가</fullName>
            </value>
            <value>
                <fullName>휴직</fullName>
            </value>
            <value>
                <fullName>육아휴직</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>프로젝트 PM</fullName>
            </value>
            <value>
                <fullName>프로젝트 팀원</fullName>
            </value>
            <value>
                <fullName>본사근무</fullName>
            </value>
            <value>
                <fullName>임원</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Project_HolidayAction</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/PerformProject__c.object-meta.xml
<CustomObject>
    <label>프로젝트 수행팀</label>
    <nameField>
        <displayFormat>PJ-{0000}</displayFormat>
        <label>Seq</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>프로젝트에 참여한 사원 이름</inlineHelpText>
    <label>사원 명</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>수행 프로젝트</relationshipLabel>
    <relationshipName>EmployeePerformPjt</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/fm_FromDate__c.field-meta.xml
<CustomField>
    <fullName>fm_FromDate__c</fullName>
    <formula>BLANKVALUE( InputDate__c ,  Project__r.StartDate__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>시작일</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/fm_ToDate__c.field-meta.xml
<CustomField>
    <fullName>fm_ToDate__c</fullName>
    <formula>BLANKVALUE( WithdrawDate__c ,  Project__r.EndDate__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>종료일</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/InputDate__c.field-meta.xml
<CustomField>
    <fullName>InputDate__c</fullName>
    <label>투입 일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/IsPM__c.field-meta.xml
<CustomField>
    <fullName>IsPM__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PM여부</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트 명</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>프로젝트 수행팀</relationshipLabel>
    <relationshipName>Project</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/WithdrawDate__c.field-meta.xml
<CustomField>
    <fullName>WithdrawDate__c</fullName>
    <label>철수 일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>프로젝트에 대한 기본정보를 관리하며, Deal Closing 이후 생성한다. 영업담당자가 계약 체결 후 기초 데이터를 작성하며, 프로젝트 진행 중에는 PM이 관리하고, 대금청구/지급 관련 정보는 회계에서 관리한다.</description>
    <label>프로젝트</label>
    <nameField>
        <label>프로젝트 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/classes/HolidayActionLightningExtension.cls
/*
* Component Name                : HolidayActionLightning.cmp
* Component Controller          : HolidayActionLightningController.js
* Component Helper              : HolidayActionLightningHelper.js
* Component Contorlller Class   : HolidayActionLightningExtension.cls
* Test Class                    : HolidayActionLightningExtension_Test.cls
* Description                   : 휴일관리 라이트닝 신청 폼
* Modification Log 
* =============================================================== 
* Ver     Date          Author           Modification
* ===============================================================
  1.0   2018.08.27      JK.lee              Create
  1.1   2019.04.26                          Modified
  2.0   2021.01.18      CJ.Sohn             Modified(승인자 자동 할당, 사원 정보 및 프로젝트 수행팀 이력(오늘 날짜 기준) 조회)
*/  

global without sharing class HolidayActionLightningExtension {
    
    @AuraEnabled
    @RemoteAction
    public static String doHolidayAction(HolidayAction__c saveList , String currentUserId){
        system.debug('saveList :: ' + saveList);
        String checkMessage = '';

        try { 
            String userId = UserInfo.getUserId();
            //String userId = saveList.CreatedById            
            saveList.OwnerId = currentUserId;
            system.debug('userId : :'+ userId);
            system.debug('currentUserId : :'+currentUserId);

            system.debug('--holidayActionSh--');
            if(String.valueOf(saveList.HolidayAction_Parent__c) == ''){
                string parentId = [SELECT Id FROM Holiday__c WHERE Holiday_User__c = :currentUserId  limit 1].Id;
                saveList.HolidayAction_Parent__c = parentId;
                system.debug('여기걸림 ? HolidayActionParent 삽입 : ' + saveList.HolidayAction_Parent__c);
            }

            //반차 Half- PM/AM 추가 
            if(saveList.HolidayAction_Type__c =='Half-day Leave'){
                saveList.HolidayAction_Days__c= 0.5;
            }
            system.debug('saveList.HolidayAction_Parent__c :: ' + saveList.HolidayAction_Parent__c);

            if(saveList.HolidayAction_Type__c =='Women Holiday') {
               integer year = system.today().year();                
               integer mon = system.today().month();
               Date fromdt = date.newInstance(year, mon, 1);
               integer cnt = [SELECT Id FROM HolidayAction__c WHERE HolidayAction_Parent__c =:saveList.HolidayAction_Parent__c AND HolidayAction_Date1__c >= :fromdt AND HolidayAction_Type__c ='Women Holiday'].size();
               system.debug('cnt ::: '+ cnt);
               system.debug('year ::: '+ year);
               system.debug('mon ::: '+ mon);
               system.debug('fromdt :::' +fromdt);

                if(cnt > 0) {
                    checkMessage = 'Already applied a Women Holiday this month : 이미 이번달 여성 보건휴가를 신청했습니다.';
                    return checkMessage;
                }
            }
          
            insert saveList;
            System.debug('saveList: ' + saveList);

            //레코드 공유 규칙
            if(userId != currentUserId){

                HolidayAction__Share holidaySh = new HolidayAction__Share();
                holidaySh.ParentId = saveList.Id;
                holidaySh.UserOrGroupId = userId;
                holidaySh.AccessLevel = 'Edit';
                // holidaySh.UserOrGroupId = obj.FirstHolidayRequest__c;
                // holidaySh.RowCause = Schema.HolidayAction__Share.RowCause.ActionForAll__c;

                insert holidaySh;
		    }
        } catch(System.DmlException e) {
            for (Integer i = 0; i < e.getNumDml(); i++) {
                system.debug(' ==>'); // boolean->string 메세지가 2개이상이기 때문에 boolean값으로 받지 못한다.
                system.debug(e);
                system.debug(i);
                system.debug('e.getStackTraceString(): ' + e.getStackTraceString());
                system.debug('e.getLineNumber(): ' + e.getLineNumber());
                system.debug('e.getCause(): ' + e.getCause());
                checkMessage = String.valueof(e.getDmlMessage(i)); // string value를 integer로 받기
                System.debug('checkMessage================================='+checkMessage);

                return checkMessage;
            }
        }
        return checkMessage;
    }


    @AuraEnabled
    public static List<String> getSelectFieldName() {
        List<String> fieldName = new List<String>();
        Schema.DescribeSObjectResult objDescribe = HolidayAction__c.SObjectType.getDescribe();
        Map<String, Schema.SObjectField> fieldMap = objDescribe.fields.getMap();
        System.debug('fieldMap============='+fieldMap);
        for(String strKey : fieldMap.keySet()){
            Schema.SObjectField field = fieldMap.get(strKey);
            Schema.DescribeFieldResult fieldDescribe = field.getDescribe();
            fieldName.add(fieldDescribe.getName());
        }

        return fieldName;
    }

    @AuraEnabled
    public static String selfApproverCheck() {
        Id userId = UserInfo.getUserId();
        String.valueOf(userId);
        return userId;
    }

    /**
     * @description       : 사용자의 ApprovalLine1 필드의 1차 승인자를 리턴
     * @author            : cj.sohn@daeunextier.com
     * @group             : DaeuNextier
    **/
    @AuraEnabled
    public static String[] getApproverId() {
        List<User> listUsers = [SELECT Id, ApprovalLine1__c FROM User WHERE Id =: UserInfo.getUserId() LIMIT 1];
        if(listUsers.size() > 0) {
            return String.valueOf(listUsers.get(0).ApprovalLine1__c).split('/');
        } else {
            return null;
        }
    }

    /**
     * @description       : 사용자의 사원 정보(부서, 직급)와 프로젝트 수행팀 정보(현재 투입되어있는지 유무)를 리턴
     * @author            : cj.sohn@daeunextier.com
     * @group             : DaeuNextier
    **/
    @AuraEnabled
    public static List<Employee__c> employeeStatus(){
        List<Employee__c> userStatus = [SELECT Id, Name, Department__c, toLabel(Position__c), (SELECT Id, Project__c, IsPM__c, fm_FromDate__c, fm_ToDate__c FROM EmployeePerformPjt__r WHERE InputDate__c <=: System.today() AND ((WithdrawDate__c != null AND WithdrawDate__c >=: System.today()) OR WithdrawDate__c = null) ORDER BY LastModifiedDate DESC) FROM Employee__c WHERE Employee__c.User__c =: UserInfo.getUserId()];
        if(userStatus.size() > 0) {
            return userStatus;
        } else {
            return null;
        }
    }
}