PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/MainRole__c.field-meta.xml
<CustomField>
    <fullName>MainRole__c</fullName>
    <label>직무</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Management</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/O_Company__c.field-meta.xml
<CustomField>
    <fullName>O_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>외주계약사</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Employee</relationshipLabel>
    <relationshipName>Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

ListViewButton/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>구분</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>내부직원</fullName>
            </value>
            <value>
                <fullName>외부직원</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/PerformProject__c.object-meta.xml
<CustomObject>
    <label>프로젝트 수행팀</label>
    <nameField>
        <displayFormat>PJ-{0000}</displayFormat>
        <label>Seq</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>프로젝트에 참여한 사원 이름</inlineHelpText>
    <label>사원 명</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>수행 프로젝트</relationshipLabel>
    <relationshipName>EmployeePerformPjt</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/Final_Evaluation_YN__c.field-meta.xml
<CustomField>
    <fullName>Final_Evaluation_YN__c</fullName>
    <defaultValue>false</defaultValue>
    <label>최종평가 여부</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/First_evaluation_YN__c.field-meta.xml
<CustomField>
    <fullName>First_evaluation_YN__c</fullName>
    <defaultValue>false</defaultValue>
    <description>외주인력 대상 투입 30일 후 진행할 1차 평가 여부</description>
    <label>1차평가 여부</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/Fm_First_Evaluation_Check__c.field-meta.xml
<CustomField>
    <fullName>Fm_First_Evaluation_Check__c</fullName>
    <description>외부직원이며 투입일자가 30일이 경과 했을 경우 1차 평가 발송을 위한 포뮬라 필드</description>
    <formula>IF(
				AND(ISPICKVAL(Employee__r.Type__c, &apos;외부직원&apos;), 
								(TODAY() - InputDate__c &gt; 29)
								),
				TRUE,
				FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>1차평가 필요여부</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/fm_FromDate__c.field-meta.xml
<CustomField>
    <fullName>fm_FromDate__c</fullName>
    <formula>BLANKVALUE( InputDate__c ,  Project__r.StartDate__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>시작일</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/fm_ToDate__c.field-meta.xml
<CustomField>
    <fullName>fm_ToDate__c</fullName>
    <formula>BLANKVALUE( WithdrawDate__c ,  Project__r.EndDate__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>종료일</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/InputDate__c.field-meta.xml
<CustomField>
    <fullName>InputDate__c</fullName>
    <label>투입 일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/IsPM__c.field-meta.xml
<CustomField>
    <fullName>IsPM__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PM여부</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트 명</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>프로젝트 수행팀</relationshipLabel>
    <relationshipName>Project</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/WithdrawDate__c.field-meta.xml
<CustomField>
    <fullName>WithdrawDate__c</fullName>
    <label>철수 일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PJT_Employee_evaluation__c/PJT_Employee_evaluation__c.object-meta.xml
<CustomObject>
    <description>프로젝트 투입인력에 대한 평가 저장</description>
    <label>프로젝트 인력평가</label>
    <nameField>
        <displayFormat>No.{0000}</displayFormat>
        <label>Evaluation No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/PJT_Employee_evaluation__c/fields/Additional_Comment__c.field-meta.xml
<CustomField>
    <fullName>Additional_Comment__c</fullName>
    <label>비고 (기타의견)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PJT_Employee_evaluation__c/fields/Addtional_Work__c.field-meta.xml
<CustomField>
    <fullName>Addtional_Work__c</fullName>
    <label>기타 수행업무</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PJT_Employee_evaluation__c/fields/Attitude__c.field-meta.xml
<CustomField>
    <fullName>Attitude__c</fullName>
    <label>Attitude</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PJT_Employee_evaluation__c/fields/Communication_Skill__c.field-meta.xml
<CustomField>
    <fullName>Communication_Skill__c</fullName>
    <label>Communication Skill</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PJT_Employee_evaluation__c/fields/Competency__c.field-meta.xml
<CustomField>
    <fullName>Competency__c</fullName>
    <label>Competency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PJT_Employee_evaluation__c/fields/Cooperation__c.field-meta.xml
<CustomField>
    <fullName>Cooperation__c</fullName>
    <label>Cooperation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PJT_Employee_evaluation__c/fields/Evaluation_Type__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_Type__c</fullName>
    <description>1차평가, 최종평가 구분값</description>
    <label>평가구분</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PJT_Employee_evaluation__c/fields/InputDate__c.field-meta.xml
<CustomField>
    <fullName>InputDate__c</fullName>
    <label>투입일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PJT_Employee_evaluation__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>이름</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>프로젝트 인력평가</relationshipLabel>
    <relationshipName>ProjectEvaluation</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PJT_Employee_evaluation__c/fields/Passion__c.field-meta.xml
<CustomField>
    <fullName>Passion__c</fullName>
    <label>Passion</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PJT_Employee_evaluation__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>프로젝트 인력평가</relationshipLabel>
    <relationshipName>Proejct_evaluation</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PJT_Employee_evaluation__c/fields/WithdrawDate__c.field-meta.xml
<CustomField>
    <fullName>WithdrawDate__c</fullName>
    <label>철수일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>프로젝트에 대한 기본정보를 관리하며, Deal Closing 이후 생성한다. 영업담당자가 계약 체결 후 기초 데이터를 작성하며, 프로젝트 진행 중에는 PM이 관리하고, 대금청구/지급 관련 정보는 회계에서 관리한다.</description>
    <label>프로젝트</label>
    <nameField>
        <label>프로젝트 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/fields/Completed__c.field-meta.xml
<CustomField>
    <fullName>Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>프로젝트가 종료되면 체크함.</inlineHelpText>
    <label>완료 여부</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/recordTypes/Project.recordType-meta.xml
<RecordType>
    <fullName>Project</fullName>
    <active>true</active>
    <description>프로젝트 사항 입력하는 Record Type</description>
    <label>프로젝트</label>
</RecordType>

PA_Education/TestMenifest/force-app/main/default/classes/EmployeeEvaluationBtnController.cls
/**
 * Created by yj.kim on 2023-07-04.
 */

public without sharing class EmployeeEvaluationBtnController {

    public String recordId { get; set; }

    public EmployeeEvaluationBtnController(ApexPages.StandardController controller) {
        recordId = ApexPages.currentPage().getParameters().get('Id');
        System.debug('recordId : ' + recordId);
    }

    @AuraEnabled
    public static Map<String, Object> doInit(String recordId){
        System.debug('doInit recordId : ' + recordId);

        List<InternalWrapper> listInWrapper = new List<InternalWrapper>();
        List<externalWrapper> listExWrapper = new List<externalWrapper>();

        List<PerformProject__c> projectTeam = new List<PerformProject__c>();

        String projectName = '';
        Boolean firstEvaluation = false;

        Project__c projectObj = [
                SELECT Completed__c
                FROM Project__c
                WHERE Id =: recordId
        ];
        System.debug('완료여부 : ' + projectObj.Completed__c);

        //외주직원 1차평가
        if(projectObj.Completed__c == false){
            System.debug('외주직원 1차평가');
            projectTeam = [
                    SELECT Id, Project__c, Employee__c, Employee__r.Type__c, Employee__r.Name, Project__r.Name, Employee__r.MainRole__c,
                            Employee__r.O_Company__r.Name, fm_FromDate__c, fm_ToDate__c
                    FROM PerformProject__c
                    WHERE Project__c =: recordId AND IsPM__c = FALSE AND Fm_First_Evaluation_Check__c = TRUE AND First_evaluation_YN__c = FALSE
            ];

            if(!projectTeam.isEmpty()){
                firstEvaluation = true;
            }
        }

        //최종평가
        if(projectObj.Completed__c == true){
            System.debug('최종평가');
            projectTeam = [
                    SELECT Id, Project__c, Employee__c, Employee__r.Type__c, Employee__r.Name, Project__r.Name, Employee__r.MainRole__c,
                            Employee__r.O_Company__r.Name, fm_FromDate__c, fm_ToDate__c
                    FROM PerformProject__c
                    WHERE Project__c =: recordId AND IsPM__c = FALSE
            ];
        }

        System.debug('projectTeam : ' + projectTeam);
        if(!projectTeam.isEmpty()){
            projectName = projectTeam[0].Project__r.Name;
            for(PerformProject__c obj : projectTeam){
                if(obj.Employee__r.Type__c == '내부직원'){

                    InternalWrapper inObj = new InternalWrapper();
                    inObj.performProjectId = obj.Id;
                    inObj.project = obj.Project__c;
                    inObj.employeeId = obj.Employee__c;
                    inObj.employeeName = obj.Employee__r.Name;
                    inObj.mainRole = obj.Employee__r.MainRole__c;
                    inObj.competency = null;
                    inObj.communication = null;
                    inObj.cooperation = null;
                    inObj.passion = null;
                    inObj.attitude = null;
                    inObj.addWork = null;
                    inObj.addComment = null;
                    inObj.fromDate = obj.fm_FromDate__c;
                    inObj.toDate = obj.fm_ToDate__c;

                    listInWrapper.add(inObj);
                }else if(obj.Employee__r.Type__c == '외부직원'){

                    externalWrapper exObj = new externalWrapper();
                    exObj.performProjectId = obj.Id;
                    exObj.project = obj.Project__c;
                    exObj.employeeId = obj.Employee__c;
                    exObj.employeeName = obj.Employee__r.Name;
                    exObj.mainRole = obj.Employee__r.O_Company__r.Name;
                    exObj.competency = null;
                    exObj.communication = null;
                    exObj.cooperation = null;
                    exObj.passion = null;
                    exObj.attitude = null;
                    exObj.addWork = null;
                    exObj.addComment = null;
                    exObj.fromDate = obj.fm_FromDate__c;
                    exObj.toDate = obj.fm_ToDate__c;

                    listExWrapper.add(exObj);
                }
            }
        }

        Map<String, Object> mapReturnValue = new Map<String, Object>{
                'projectName'     => projectName,
                'InternalWrapper' => listInWrapper,
                'externalWrapper' => listExWrapper,
                'firstEvaluation' => firstEvaluation
        };
        System.debug('mapReturnValue : ' + mapReturnValue);

        return mapReturnValue;
    }

    @AuraEnabled
    public static Map<String, Object> doSave(List<Map<String, Object>> inList, List<Map<String, Object>> exList, Boolean firstEvaluation){
        System.debug('inList : ' + inList);
        System.debug('exList : ' + exList);
        System.debug('firstEvaluation : ' + firstEvaluation);

        Map<String, Object> mapInListData = new Map<String, Object>();
        Map<String, Object> mapExListData = new Map<String, Object>();
        List<PJT_Employee_evaluation__c> insertList = new List<PJT_Employee_evaluation__c>();

        List<String> firstPerformList = new List<String>();
        List<String> finalPerformList = new List<String>();

        String status = 'SUCCESS';
        String message = '성공적으로 저장되었습니다.';

        try {
            //내부직원이 있을시
            if (!inList.isEmpty()) {
                for(Object obj : inList){
                    mapInListData = (Map<String, Object>) obj;
                    PJT_Employee_evaluation__c evalObj = new PJT_Employee_evaluation__c();
                    if(firstEvaluation == false){
                        evalObj.Evaluation_Type__c = '최종평가';
                        finalPerformList.add(String.valueOf(mapInListData.get('performProjectId')));
                    }
                    evalObj.Project__c = String.valueOf(mapInListData.get('project'));                          //프로젝트 Id
                    evalObj.Name__c = String.valueOf(mapInListData.get('employeeId'));                          //이름
                    System.debug('fromDate : ' + mapInListData.get('fromDate'));
                    System.debug('toDate : ' + mapInListData.get('toDate'));
                    evalObj.InputDate__c = mapInListData.get('fromDate') != null ? formatToDate(String.valueOf(mapInListData.get('fromDate'))) : null;   //투입일자
                    evalObj.WithdrawDate__c = mapInListData.get('toDate') != null ? formatToDate(String.valueOf(mapInListData.get('toDate'))) : null;    //철수일자                                  //철수일자
                    evalObj.Competency__c = String.valueOf(mapInListData.get('competency'));                    //competency
                    evalObj.Communication_Skill__c = String.valueOf(mapInListData.get('communication'));           //Communication Skill
                    evalObj.Cooperation__c = String.valueOf(mapInListData.get('cooperation'));                   //Cooperation
                    evalObj.Passion__c = String.valueOf(mapInListData.get('passion'));                       //Passion
                    evalObj.Attitude__c = String.valueOf(mapInListData.get('attitude'));                        //attitude
                    evalObj.Addtional_Work__c = String.valueOf(mapInListData.get('addWork'));                   //기타수행업무
                    evalObj.Additional_Comment__c = String.valueOf(mapInListData.get('addComment'));            //비고(기타의견)
                    insertList.add(evalObj);
                }
            }

            if(!exList.isEmpty()){
                for(Object obj : exList){
                    mapExListData = (Map<String, Object>) obj;
                    PJT_Employee_evaluation__c evalObj = new PJT_Employee_evaluation__c();
                    if(firstEvaluation == true){
                        evalObj.Evaluation_Type__c = '1차평가';
                        firstPerformList.add(String.valueOf(mapExListData.get('performProjectId')));
                    }else if(firstEvaluation == false){
                        evalObj.Evaluation_Type__c = '최종평가';
                        finalPerformList.add(String.valueOf(mapExListData.get('performProjectId')));
                    }
                    evalObj.Project__c = String.valueOf(mapExListData.get('project'));                          //프로젝트 Id
                    evalObj.Name__c = String.valueOf(mapExListData.get('employeeId'));                          //이름
                    evalObj.InputDate__c = mapExListData.get('fromDate') != null ? formatToDate(String.valueOf(mapExListData.get('fromDate'))) : null;   //투입일자
                    evalObj.WithdrawDate__c = mapExListData.get('toDate') != null ? formatToDate(String.valueOf(mapExListData.get('toDate'))) : null;    //철수일자
                    evalObj.Competency__c = String.valueOf(mapExListData.get('competency'));                    //competency
                    evalObj.Communication_Skill__c = String.valueOf(mapExListData.get('communication'));           //Communication Skill
                    evalObj.Cooperation__c = String.valueOf(mapExListData.get('cooperation'));                   //Cooperation
                    evalObj.Passion__c = String.valueOf(mapExListData.get('passion'));                       //Passion
                    evalObj.Attitude__c = String.valueOf(mapExListData.get('attitude'));                        //attitude
                    evalObj.Addtional_Work__c = String.valueOf(mapExListData.get('addWork'));                   //기타수행업무
                    evalObj.Additional_Comment__c = String.valueOf(mapExListData.get('addComment'));            //비고(기타의견)
                    insertList.add(evalObj);
                }
            }

            if(!insertList.isEmpty()){
                insert insertList;

                List<PerformProject__c> updateList = new List<PerformProject__c>();
                //1차평가 완료될경우, 프로젝트 수행팀 1차평가 여부 Field Update
                if(!firstPerformList.isEmpty()){
                    List<PerformProject__c> ppObj = [
                            SELECT Id
                            FROM PerformProject__c
                            WHERE Id =: firstPerformList
                    ];
                    System.debug('ppObj : ' + ppObj);
                    for(PerformProject__c obj : ppObj){
                        obj.First_evaluation_YN__c = true;
                        updateList.add(obj);
                    }
                    update updateList;
                }
                //최종평가 완료될경우, 최종평가 여부 Field Update
                if(!finalPerformList.isEmpty()){
                    List<PerformProject__c> ppObj = [
                            SELECT Id
                            FROM PerformProject__c
                            WHERE Id =: finalPerformList
                    ];
                    System.debug('ppObj : ' + ppObj);
                    for(PerformProject__c obj : ppObj){
                        obj.Final_Evaluation_YN__c = true;
                        updateList.add(obj);
                    }
                    update updateList;
                }

            }
        }catch(Exception e){
            System.debug('doSave line : ' + e.getLineNumber());
            System.debug('doSave message : ' + e.getMessage());
            status = 'ERROR';
            message = e.getMessage();
        }

        Map<String, Object> mapReturnValue = new Map<String, Object>{
            'status'  => status,
            'message' => message
        };
        return mapReturnValue;
    }

    public static Date formatToDate(String beforeDate){
        Date afterDate = Date.newInstance(Integer.valueOf(beforeDate.left(4)), Integer.valueOf(beforeDate.mid(5,2)), Integer.valueOf(beforeDate.right(2)));
        return afterDate;
    }

    //내부직원
    public class InternalWrapper {
        @AuraEnabled
        public Id project {get; set;}             //프로젝트명
        @AuraEnabled
        public Id employeeId {get; set;}          //Employee Id
        @AuraEnabled
        public String employeeName {get; set;}    //이름
        @AuraEnabled
        public String mainRole {get; set;}        //역할
        @AuraEnabled
        public String competency {get; set;}      //프로젝트 수행능력
        @AuraEnabled
        public String communication {get; set;}   //Skill 소통능력
        @AuraEnabled
        public String cooperation {get; set;}     //협업
        @AuraEnabled
        public String passion {get; set;}         //열정, 적극성
        @AuraEnabled
        public String attitude {get; set;}        //업무수행 태도, 자세
        @AuraEnabled
        public String addWork {get; set;}         //기타 수행업무
        @AuraEnabled
        public String addComment {get; set;}      //평가자의견
        @AuraEnabled
        public Date fromDate {get; set;}          //시작일
        @AuraEnabled
        public Date toDate {get; set;}            //종료일
        @AuraEnabled
        public Id performProjectId {get; set;}    //프로젝트 수행팀 Id
    }

    //외부직원
    public class externalWrapper {
        @AuraEnabled
        public Id project {get; set;}             //프로젝트명
        @AuraEnabled
        public Id employeeId {get; set;}          //Employee Id
        @AuraEnabled
        public String employeeName {get; set;}    //이름
        @AuraEnabled
        public String mainRole {get; set;}        //역할[외주계약사]
        @AuraEnabled
        public String competency {get; set;}      //프로젝트 수행능력
        @AuraEnabled
        public String communication {get; set;}   //Skill 소통능력
        @AuraEnabled
        public String cooperation {get; set;}     //협업
        @AuraEnabled
        public String passion {get; set;}         //열정, 적극성
        @AuraEnabled
        public String attitude {get; set;}        //업무수행 태도, 자세
        @AuraEnabled
        public String addWork {get; set;}         //기타 수행업무
        @AuraEnabled
        public String addComment {get; set;}      //평가자의견
        @AuraEnabled
        public Date fromDate {get; set;}          //시작일
        @AuraEnabled
        public Date toDate {get; set;}            //종료일
        @AuraEnabled
        public Id performProjectId {get; set;}    //프로젝트 수행팀 Id
    }

}