PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/DeptPosition__c.field-meta.xml
<CustomField>
    <fullName>DeptPosition__c</fullName>
    <label>직책</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chairman</fullName>
                <label>총괄사장</label>
            </value>
            <value>
                <fullName>CEO</fullName>
                <label>대표이사</label>
            </value>
            <value>
                <fullName>부사장</fullName>
            </value>
            <value>
                <fullName>General Manager</fullName>
                <label>본부장</label>
            </value>
            <value>
                <fullName>Department Head</fullName>
                <label>부서장</label>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Pre-Sales</fullName>
            </value>
            <value>
                <fullName>Business Architecture</fullName>
                <label>Business Architect</label>
            </value>
            <value>
                <fullName>Platform Architecture</fullName>
                <label>Platform Architect</label>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Mgmt Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Fm_Level__c.field-meta.xml
<CustomField>
    <fullName>Fm_Level__c</fullName>
    <formula>IF(
	VALUE(TEXT(Position__c)) &gt;= 8
	, $Setup.QuoteItemManage__c.Level1__c 
	, IF(VALUE(TEXT(Position__c)) &gt;= 6 
		, $Setup.QuoteItemManage__c.Level2__c
		, $Setup.QuoteItemManage__c.Level3__c
	)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fm_Level</label>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/MainRole__c.field-meta.xml
<CustomField>
    <fullName>MainRole__c</fullName>
    <label>직무</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Management</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>직급</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>총괄사장</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>대표이사</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>센터장</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>감사</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>부사장</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>전무</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>상무</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>수석</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>이사</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>부장</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>책임</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>차장</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>과장</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>대리</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>선임</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>선임(수습)</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>사원</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>사원(수습)</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>인턴</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/QuoteItem__c.object-meta.xml
<CustomObject>
    <description>견적을 구성하는 Consulting 자원 또는 License 목록</description>
    <label>견적 상세</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItemManage__c/QuoteItemManage__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>견적상세관리</label>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/classes/QuoteItemNewController.cls
/************************************************************************************
 * File Name   : QuoteItemNewController.cls
 * Author      : Soyoung.Jung 
 * Date        : 2019.01.14
 * Tester      : QuoteItemNewController_test.cls
 * Description : 견적 상세 생성 모달 컴포넌트 컨트롤러
 * Modification Log
 * ===================================================================================
 * Ver      Date            Author              Modification
 * ===================================================================================
   1.0      2019.01.14      Soyoung.Jung        Create
*************************************************************************************/

public with sharing class QuoteItemNewController {

	@AuraEnabled
	public static Map<String, Object> getInitData() {
		// 현재 유저가 사용 가능한 레코드 타입 조회
		Set<Id> setIdRecordTypeAvailable = new Set<Id>();
		List<Schema.RecordTypeInfo> listRecordTypes = QuoteItem__c.SObjectType.getDescribe().getRecordTypeInfos();

		for(Schema.RecordTypeInfo objRecordTypeInfo : listRecordTypes) {
			if(objRecordTypeInfo.isAvailable()) {
				setIdRecordTypeAvailable.add(objRecordTypeInfo.getRecordTypeId());
			}
		}

		// QuoteItem__c Record type list
		List<RecordType> listRecordTypeQI = [SELECT 	Id, Name, DeveloperName, Description
											 FROM 		RecordType
											 WHERE 		SObjectType = 'QuoteItem__c'
											 AND 		Id IN :setIdRecordTypeAvailable
											 ORDER BY 	DeveloperName];

		List<Map<String, String>> listRecordTypeReturn = new List<Map<String, String>>();
		Map<String, String> mapRecordTypeId = new Map<String, String>();
		for(RecordType objRecordType : listRecordTypeQI) {
			String sLabel = objRecordType.Name + ' (' + objRecordType.Description + ')';

			listRecordTypeReturn.add(new Map<String, String>{'label' => sLabel, 'value' => objRecordType.DeveloperName});
			mapRecordTypeId.put(objRecordType.DeveloperName, objRecordType.Id);
		}

		// Return map
		Map<String, Object> mapReturnValue = new Map<String, Object>{
			'listRecordTypeQI' => listRecordTypeReturn,
			'mapRecordTypeId' => mapRecordTypeId
		};

		return mapReturnValue;
	}

	@AuraEnabled
	public static Map<String, Object> getDefaultValue(Id idEmployee) {
		// Employee__c Info
		Employee__c objEmployee = [SELECT 	Id, Name, DeptPosition__c, Position__c, Fm_Level__c, MainRole__c
								   FROM 	Employee__c
								   WHERE 	Id = :idEmployee];

		System.debug('objEmployee : ' + objEmployee.Fm_Level__c);

		WrapperEmployee wrapEmployee = new WrapperEmployee(objEmployee);

		// Return map
		Map<String, Object> mapReturnValue = new Map<String, Object>{
			'wrapEmployee' => wrapEmployee
		};

		return mapReturnValue;
	}
	
	/************************************************************************************
    * 	직책과 직급에 따라 견적 단가 계산
    *************************************************************************************/
	private static Decimal doCalcListPrice(String sDept, String sConsultLevel) {
		// 견적상세관리 Custom Settings
		QuoteItemManage__c objQuoteItemManage = QuoteItemManage__c.getInstance();

		// 포지션과 등급에 따른 단가 산정
		String sListPrice = String.valueOf(objQuoteItemManage.get(sDept + sConsultLevel + '__c'));
		Decimal dListPrice = Decimal.valueOf(sListPrice);

		return dListPrice;
	}


	public class WrapperEmployee {
		@AuraEnabled public Employee__c objEmployee {get; set;}
		@AuraEnabled public Decimal dConsultListPrice {get; set;}

		public WrapperEmployee(Employee__c objEmployee) {
			this.objEmployee = objEmployee;
			this.dConsultListPrice = doCalcListPrice(objEmployee.MainRole__c, objEmployee.Fm_Level__c);
		}
	}

}