PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(ISBLANK( ExitDate__c) ||  ExitDate__c    &gt;    TODAY()  , TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>재직여부</label>
    <type>Checkbox</type>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>사원 Object를 User Object간 Relationship 생성</inlineHelpText>
    <label>사용자 명</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/Holiday__c.object-meta.xml
<CustomObject>
    <label>Holiday</label>
    <nameField>
        <displayFormat>H-{0000}</displayFormat>
        <label>Holiday No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Holiday</relationshipLabel>
    <relationshipName>Holiday</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_reward_Total_Count__c.field-meta.xml
<CustomField>
    <fullName>Holiday_reward_Total_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>올해 발생한 대체휴가일수 + 전년도 대체휴가 잔여일수</inlineHelpText>
    <label>총 대체휴가일수</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_rewardRemainDays__c.field-meta.xml
<CustomField>
    <fullName>Holiday_rewardRemainDays__c</fullName>
    <defaultValue>0</defaultValue>
    <description>2023-12-14 formula 필드로 사용 예정</description>
    <inlineHelpText>총 대체휴가일수 - 대체휴가 사용일수 - 대체휴가 수당 지급일수</inlineHelpText>
    <label>대체휴가 잔여일수 (삭제예정)</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_User__c.field-meta.xml
<CustomField>
    <fullName>Holiday_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>임직원</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Holiday</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWork__c/HolidayWork__c.object-meta.xml
<CustomObject>
    <label>휴일근무</label>
    <nameField>
        <label>휴일근무이름 (자동입력)</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWork__c/fields/Is_Canceled__c.field-meta.xml
<CustomField>
    <fullName>Is_Canceled__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>계획취소가 승인된 경우 체크됩니다.</inlineHelpText>
    <label>Is Canceled?</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWork__c/fields/Is_Confirm__c.field-meta.xml
<CustomField>
    <fullName>Is_Confirm__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>근무가 승인된 경우 체크됩니다.</inlineHelpText>
    <label>Is Confirm?</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWork__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>휴일근무</relationshipLabel>
    <relationshipName>Project2</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWork__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>단계</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>계획작성중</fullName>
                <default>true</default>
                <label>계획작성중</label>
            </value>
            <value>
                <fullName>계획승인요청</fullName>
            </value>
            <value>
                <fullName>계획승인</fullName>
            </value>
            <value>
                <fullName>계획취소승인요청</fullName>
            </value>
            <value>
                <fullName>근무승인요청</fullName>
            </value>
            <value>
                <fullName>근무승인</fullName>
            </value>
            <value>
                <fullName>승인거절</fullName>
                <isActive>false</isActive>
                <label>승인거절</label>
            </value>
            <value>
                <fullName>승인완료</fullName>
                <isActive>false</isActive>
                <label>승인완료</label>
            </value>
            <value>
                <fullName>승인요청</fullName>
                <isActive>false</isActive>
                <label>승인요청</label>
            </value>
            <value>
                <fullName>작성중</fullName>
                <isActive>false</isActive>
                <label>작성중</label>
            </value>
            <value>
                <fullName>취소승인완료</fullName>
                <isActive>false</isActive>
                <label>취소승인완료</label>
            </value>
            <value>
                <fullName>취소승인요청</fullName>
                <isActive>false</isActive>
                <label>취소승인요청</label>
            </value>
            <value>
                <fullName>회수</fullName>
                <isActive>false</isActive>
                <label>회수</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWork__c/fields/WorkingTime__c.field-meta.xml
<CustomField>
    <fullName>WorkingTime__c</fullName>
    <label>근무일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWorkDetail__c/HolidayWorkDetail__c.object-meta.xml
<CustomObject>
    <label>휴일근무 상세</label>
    <nameField>
        <displayFormat>HW-{YY}{MM}-{0000}</displayFormat>
        <label>휴일근무 상세 코드</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWorkDetail__c/fields/fm_Hours__c.field-meta.xml
<CustomField>
    <fullName>fm_Hours__c</fullName>
    <formula>CASE(WorkingTime__c, &quot;4&quot;, 4, &quot;8&quot;, 8, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>근무시간(계산)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWorkDetail__c/fields/fm_RewardDays__c.field-meta.xml
<CustomField>
    <fullName>fm_RewardDays__c</fullName>
    <formula>CASE(WorkingTime__c, &quot;4&quot;, 0.75, &quot;8&quot;, 1.5, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>대체휴가일수</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWorkDetail__c/fields/HolidayWork__c.field-meta.xml
<CustomField>
    <fullName>HolidayWork__c</fullName>
    <label>휴일근무</label>
    <referenceTo>HolidayWork__c</referenceTo>
    <relationshipName>HWD_HolidayWork</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWorkDetail__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트 명</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>HolidayWorkDetailProject</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWorkDetail__c/fields/WorkingDate__c.field-meta.xml
<CustomField>
    <fullName>WorkingDate__c</fullName>
    <label>근무일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWorkDetail__c/fields/WorkingTime__c.field-meta.xml
<CustomField>
    <fullName>WorkingTime__c</fullName>
    <label>근무시간</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>4</fullName>
                <label>0.5일 (4시간)</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>1일 (8시간)</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>근무하지 않음</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWorkDetail__c/fields/WorkUser__c.field-meta.xml
<CustomField>
    <fullName>WorkUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>휴일근무자</label>
    <referenceTo>User</referenceTo>
    <relationshipName>HolidayWorkUserDetail</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/PerformProject__c.object-meta.xml
<CustomObject>
    <label>프로젝트 수행팀</label>
    <nameField>
        <displayFormat>PJ-{0000}</displayFormat>
        <label>Seq</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>프로젝트에 참여한 사원 이름</inlineHelpText>
    <label>사원 명</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>수행 프로젝트</relationshipLabel>
    <relationshipName>EmployeePerformPjt</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/IsPM__c.field-meta.xml
<CustomField>
    <fullName>IsPM__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PM여부</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트 명</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>프로젝트 수행팀</relationshipLabel>
    <relationshipName>Project</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>프로젝트에 대한 기본정보를 관리하며, Deal Closing 이후 생성한다. 영업담당자가 계약 체결 후 기초 데이터를 작성하며, 프로젝트 진행 중에는 PM이 관리하고, 대금청구/지급 관련 정보는 회계에서 관리한다.</description>
    <label>프로젝트</label>
    <nameField>
        <label>프로젝트 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/fields/PM__c.field-meta.xml
<CustomField>
    <fullName>PM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트 관리자</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PM</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/RewardHoliday__c/RewardHoliday__c.object-meta.xml
<CustomObject>
    <description>대체휴가 발생 이력 관리용 Object</description>
    <label>대체휴가</label>
    <nameField>
        <displayFormat>RH-{000000}</displayFormat>
        <label>대체휴가 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/RewardHoliday__c/fields/HolidayWork__c.field-meta.xml
<CustomField>
    <fullName>HolidayWork__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>휴일근무</label>
    <referenceTo>HolidayWork__c</referenceTo>
    <relationshipLabel>대체휴가</relationshipLabel>
    <relationshipName>HolidayWork2</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/RewardHoliday__c/fields/OccurHoliday__c.field-meta.xml
<CustomField>
    <fullName>OccurHoliday__c</fullName>
    <formula>CASE(TEXT(WorkingTime__c), &quot;0.5일 (4시간)&quot;, 0.75, &quot;1일 (8시간)&quot;, 1.5, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>발생휴가</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/RewardHoliday__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>대체휴가</relationshipLabel>
    <relationshipName>HR_Project</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/RewardHoliday__c/fields/WorkingDate__c.field-meta.xml
<CustomField>
    <fullName>WorkingDate__c</fullName>
    <label>근무일자</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/RewardHoliday__c/fields/WorkingTime__c.field-meta.xml
<CustomField>
    <fullName>WorkingTime__c</fullName>
    <label>근무시간</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0.5일 (4시간)</fullName>
            </value>
            <value>
                <fullName>1일 (8시간)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/RewardHoliday__c/fields/WorkUser__c.field-meta.xml
<CustomField>
    <fullName>WorkUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>휴일근무자</description>
    <label>휴일근무자</label>
    <referenceTo>User</referenceTo>
    <relationshipName>HR_WorkUser</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/HolidayWork_tr.cls
/**
 * ==================================================================================
 * File Name         : HolidayWork_tr
 * Author            : yj.kim
 * Group             : Daeu Nextier
 * Description       :
 * Modification Logs
 * ==================================================================================
 *   Ver     Date          Author           Modification
 * ==================================================================================
 *   1.0   2023-06-07     yj.kim            휴일근무 승인완료일때, 대체휴가에 대한 이력 관리 + Holiday__c Object 대체휴가 잔여일수 Update
 *   2.0   2023-12-12     kwanwoo.jeon      휴일근무 최종 근무 승인 반려 혹은 recall 시 HolidayWorkDetail의 근무시간 Null로 변경
 *   2.1   2023-12-19     yeonlim.jeong     프로젝트가 없을 경우 Role이 CEO, Business Management, Sales Manager인 사용자만, 프로젝트가 있을 경우 프로젝트의 PM만 생성 가능
 *   2.2   2023-01-02     yeonlim.jeong     프로젝트가 있을 경우 PM 여부, 프로젝트 관리자에게 Manual Sharing
**/
public without sharing class HolidayWork_tr extends TriggerHandler{
    public HolidayWork_tr() {
        listNew = (List<HolidayWork__c>) Trigger.new;
        listOld = (List<HolidayWork__c>) Trigger.old;
        mapNew = (Map<Id, HolidayWork__c>) Trigger.newMap;
        mapOld = (Map<Id, HolidayWork__c>) Trigger.oldMap;
    }

    /** TriggerHandler */
    private List<HolidayWork__c> listNew { get; set; }
    private List<HolidayWork__c> listOld { get; set; }
    private Map<Id, HolidayWork__c> mapNew { get; set; }
    private Map<Id, HolidayWork__c> mapOld { get; set; }

    public override void beforeInsert() {
        isCheckProject();
    }
    public override void afterInsert() {
        doSharePM();
    }
    public override void beforeUpdate() {
        doInsertRewardHoliday();
    }
    public override void afterUpdate() {
        resetWorkingTime();
    }

    public void doInsertRewardHoliday() {
        Set<String> setHolidayWorkId = new Set<String>();
//        Set<String> setCancelId = new Set<String>();
        Map<String, Decimal> workUserToHours = new Map<String, Decimal>();
//        Map<String, Decimal> deleteUserToHours = new Map<String, Decimal>();

        for(HolidayWork__c obj : listNew){
            if(obj.Is_Confirm__c == true && mapOld.get(obj.Id).Is_Confirm__c != true){
                setHolidayWorkId.add(obj.Id);
            }

//            if(obj.Is_Canceled__c == true && mapOld.get(obj.Id).Is_Canceled__c != true){
//                setCancelId.add(obj.Id);
//            }
        }
        System.debug('setHolidayWorkId : ' + setHolidayWorkId);

        List<RewardHoliday__c> updateRewardList = new List<RewardHoliday__c>();
        Map<Id, Holiday__c> hMap = new Map<Id, Holiday__c>();

        //승인완료인 휴일근무(HolidayWork__c)에 한해 HolidayWorkDetail__c 레코드들 가져와서 이력관리(RewardHoliday__c)에 Insert
        if(!setHolidayWorkId.isEmpty()){
            List<HolidayWorkDetail__c> workDeList = [
                    SELECT HolidayWork__c, HolidayWork__r.Project__c, WorkUser__c, WorkingDate__c, fm_Hours__c, fm_RewardDays__c, HolidayWork__r.WorkingTime__c
                    FROM HolidayWorkDetail__c
                    WHERE HolidayWork__c =: setHolidayWorkId
                    AND fm_Hours__c != 0

            ];

            if(!workDeList.isEmpty()){
                for(HolidayWorkDetail__c workDe : workDeList){
                    RewardHoliday__c obj = new RewardHoliday__c();
                    obj.Project__c = workDe.HolidayWork__r.Project__c;
                    obj.WorkUser__c = workDe.WorkUser__c;
                    obj.WorkingDate__c = workDe.HolidayWork__r.WorkingTime__c;
                    obj.HolidayWork__c = workDe.HolidayWork__c;
                    if(workDe.fm_Hours__c == 4){
                        obj.WorkingTime__c = '0.5일 (4시간)';
                    }else if(workDe.fm_Hours__c == 8){
                        obj.WorkingTime__c = '1일 (8시간)';
                    }

                    //근무자(WorkUser__c)의 총 휴일근무 시간 구하기
                    if (workUserToHours.containsKey(obj.WorkUser__c)) {
                        Decimal totalHours = workUserToHours.get(obj.WorkUser__c);
                        totalHours += workDe.fm_RewardDays__c;
                        workUserToHours.put(obj.WorkUser__c, totalHours);
                    } else {
                        workUserToHours.put(obj.WorkUser__c, workDe.fm_RewardDays__c);
                    }

                    updateRewardList.add(obj);
                }
            }
        }

        if(!updateRewardList.isEmpty()){
            //Holiday Object 근무자별 대체휴가 잔여일수 Update
            if(!workUserToHours.isEmpty()){
                List<Holiday__c> h = [
                        SELECT Id, Holiday_User__c, Holiday_reward_Total_Count__c
                        FROM Holiday__c
                        WHERE Holiday_User__c =: workUserToHours.keySet()
                ];
                System.debug('h : ' + h);

                for(Holiday__c holidayObj : h){
                    if(holidayObj.Holiday_reward_Total_Count__c != null) {
                        holidayObj.Holiday_reward_Total_Count__c += workUserToHours.get(holidayObj.Holiday_User__c);
                    }else{
                        holidayObj.Holiday_reward_Total_Count__c = workUserToHours.get(holidayObj.Holiday_User__c);
                    }
                    hMap.put(holidayObj.Id, holidayObj);
                }
                System.debug('hMap : ' + hMap);
                insert updateRewardList;
                update hMap.values();
            }
        }

        // 취소 승인 되면 관련 이력관리(RewardHoliday__c) 레코드 delete, Holiday Object 근무자별 대체휴가 잔여일수 Update
        //2023.12.12 취소승인이 근무계획에 대한 취소승인으로 변경됨에 따라 해당 로직 제거
//        Map<Id, Holiday__c> h2Map = new Map<Id, Holiday__c>();
//        if(!setCancelId.isEmpty()){
//            List<RewardHoliday__c> rewardList = [
//                    SELECT Id, WorkUser__c, OccurHoliday__c
//                    FROM RewardHoliday__c
//                    WHERE HolidayWork__c =: setCancelId
//            ];
//
//            if(!rewardList.isEmpty()){
//                for(RewardHoliday__c rh : rewardList){
//                    if (deleteUserToHours.containsKey(rh.WorkUser__c)) {
//                        Decimal totalHours = deleteUserToHours.get(rh.WorkUser__c);
//                        totalHours += rh.OccurHoliday__c;
//                        deleteUserToHours.put(rh.WorkUser__c, totalHours);
//                    } else {
//                        deleteUserToHours.put(rh.WorkUser__c, rh.OccurHoliday__c);
//                    }
//                }
//                delete rewardList;
//            }
//
//            if(!deleteUserToHours.isEmpty()){
//                List<Holiday__c> h = [
//                        SELECT Id, Holiday_User__c, Holiday_rewardRemainDays__c
//                        FROM Holiday__c
//                        WHERE Holiday_User__c =: deleteUserToHours.keySet()
//                ];
//                System.debug('h : ' + h);
//
//                for(Holiday__c holidayObj : h){
//                    if(holidayObj.Holiday_rewardRemainDays__c != null) {
//                        holidayObj.Holiday_rewardRemainDays__c -= deleteUserToHours.get(holidayObj.Holiday_User__c);
//                    }else{
//                        holidayObj.Holiday_rewardRemainDays__c = deleteUserToHours.get(holidayObj.Holiday_User__c);
//                    }
//                    h2Map.put(holidayObj.Id, holidayObj);
//                }
//                update h2Map.values();
//            }
//        }
    }

    /**
    * Event : after Update
    * Author : kwanwoo.jeon
    * Description : 2023.12.12 최종 근무 승인 반려 혹은 recall 시 HolidayWorkDetail의 근무시간 Null로 변경
    */
    public void resetWorkingTime(){
        list<Id> listTargetId = new List<Id>();
        for (HolidayWork__c obj: listNew){
            if (obj.Status__c == '계획승인' && mapOld.get(obj.Id).Status__c == '근무승인요청') {
                listTargetId.add(obj.Id);
            }
        }

        if (!listTargetId.isEmpty()) {
            list<HolidayWorkDetail__c> listHWDetail = new List<HolidayWorkDetail__c>([SELECT id, WorkingTime__c from HolidayWorkDetail__c where HolidayWork__c in: listTargetId]);
            if (!listHWDetail.isEmpty()) {
                for (HolidayWorkDetail__c obj: listHWDetail){
                    obj.WorkingTime__c = null;
                }
                update listHWDetail;
            }
        }

    }

    /**
    * Event : before insert
    * Author : Yeonlim
    * Description : 프로젝트가 없을 경우 Role이 CEO, Business Management, Sales Manager인 사용자만, 프로젝트가 있을 경우 프로젝트의 PM만 생성 가능 (어드민은 Validation 제외)
    */
    public void isCheckProject() {
        // 시스템 어드민일 경우 해당 X
        if ([SELECT Name FROM Profile WHERE Id =: UserInfo.getProfileId()].Name == 'System Administrator') {
            return ;
        }

        Set<String> setProjectId = new Set<String>();
        Set<String> setValidProjectId = new Set<String>();
        for (HolidayWork__c obj : listNew) {
            setProjectId.add(obj.Project__c);
        }

        // 1. 프로젝트가 있을 경우
        if (!setProjectId.contains(null)) {
            Id userId = UserInfo.getUserId();
            Set<String> setCheckPerformProjectId = new Set<String>();
            // 1-1. 프로젝트의 PM인지 체크
            for(Project__c obj : [
                    SELECT Id, PM__c
                    FROM Project__c
                    WHERE Id IN: setProjectId
            ]) {
                if (obj.PM__c != userId) {
                    setCheckPerformProjectId.add(obj.Id);
                } else {
                    setValidProjectId.add(obj.Id);
                }
            }

            // 1-2. 프로젝트 수행팀의 PM인지 체크
            if (!setCheckPerformProjectId.isEmpty()) {
                List<Employee__c> listEmployee = [
                        SELECT Id
                        FROM Employee__c
                        WHERE User__c =: UserInfo.getUserId()
                ];

                if (listEmployee.isEmpty()) {
                    for (HolidayWork__c obj : listNew) {
                        obj.addError('현재 User의 Employee가 존재하지 않습니다.');
                        return ;
                    }
                } else {
                    for (PerformProject__c obj : [
                            SELECT Id, IsPM__c, Project__c
                            FROM PerformProject__c
                            WHERE Project__c IN: setCheckPerformProjectId
                            AND Employee__c =: listEmployee[0].Id
                    ]) {
                        if (obj.IsPM__c) {
                            setValidProjectId.add(obj.Project__c);
                        }
                    }
                }
            }
        } else { // 2. 프로젝트가 없을 경우 Role이 CEO, Business Management, Sales Manager 인지 체크
            for (UserRole obj : [
                    SELECT Id, DeveloperName
                    FROM UserRole
                    WHERE Id =: UserInfo.getUserRoleId()
            ]) {
                if (obj.DeveloperName == 'CEO' || obj.DeveloperName == 'Business_Management' || obj.DeveloperName == 'Sales_Manager') {
                    setValidProjectId.add(null);
                }
            }
        }

        for (HolidayWork__c obj : listNew) {
            if (!setValidProjectId.contains(obj.Project__c)) {
                obj.addError('휴일근무의 프로젝트가 없을 경우 Role이 CEO, Business Management, Sales Manager인 사용자만, 프로젝트가 있을 경우 프로젝트의 PM만 생성 가능합니다.');
            }
        }

    }

    /**
    * Event : after insert
    * Author : Yeonlim
    * Description : 프로젝트가 있을 경우 PM 여부, 프로젝트 관리자에게 Manual Sharing
    */
    public void doSharePM() {
        Set<Id> setProjectId = new Set<Id>();
        for (HolidayWork__c obj : listNew) {
            if (obj.Project__c != null) {
                setProjectId.add(obj.Project__c);
            }
        }

        if (!setProjectId.isEmpty()) {
            Id userId = UserInfo.getUserId();

            Map<String, List<String>> mapProjectIdToListPM = new Map<String, List<String>>();
            // 1. 프로젝트 - 프로젝트 관리자
            for (Project__c obj : [
                    SELECT Id, PM__c
                    FROM Project__c
                    WHERE Id IN: setProjectId
                    AND PM__c != :userId
            ]) {
                List<String> listPM = mapProjectIdToListPM.get(obj.Id);

                if (listPM == null) {
                    listPM = new List<String>();
                    mapProjectIdToListPM.put(obj.Id, listPM);
                }

                listPM.add(obj.PM__c);
            }

            // 2. 프로젝트 수행팀 - PM 여부 체크된 사용자
            for (PerformProject__c obj : [
                    SELECT Id, Project__c, Employee__r.User__c
                    FROM PerformProject__c
                    WHERE Project__c IN: setProjectId
                    AND IsPM__c = TRUE
                    AND Employee__r.User__c != :userId
            ]) {
                List<String> listPM = mapProjectIdToListPM.get(obj.Project__c);

                if (listPM == null) {
                    listPM = new List<String>();
                    mapProjectIdToListPM.put(obj.Project__c, listPM);
                }

                listPM.add(obj.Employee__r.User__c);
            }

            if (!mapProjectIdToListPM.isEmpty()) {
                List<HolidayWork__Share> listHWShare = new List<HolidayWork__Share>();

                for (HolidayWork__c obj : listNew) {
                    for (String pmId : mapProjectIdToListPM.get(obj.Project__c)) {
                        if(pmId != null){
                            HolidayWork__Share objHWShare = new HolidayWork__Share(
                                    ParentId      = obj.Id,
                                    UserOrGroupId = pmId,
                                    AccessLevel   = 'Read',
                                    RowCause      = 'Manual'
                            );
                            listHWShare.add(objHWShare);
                        }
                    }
                }

                System.debug('listHWShare : ' + listHWShare);
                if (!listHWShare.isEmpty()) {
                    insert listHWShare;
                }
            }

        }
    }

}