PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/HolidayAction__c.object-meta.xml
<CustomObject>
    <description>HolidayAction__c</description>
    <label>휴가신청</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>휴가신청</relationshipLabel>
    <relationshipName>HolidayActionV4Zc</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Date1__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Date1__c</fullName>
    <label>Date1</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Date2__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Date2__c</fullName>
    <label>Date2</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Date3__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Date3__c</fullName>
    <label>Date3</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Date4__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Date4__c</fullName>
    <label>Date4</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Date5__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Date5__c</fullName>
    <label>Date5</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Days__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Days__c</fullName>
    <inlineHelpText>Women&apos;s Holiday 1.
Alternative Holiday 0.
Other Holidays from 1 to 5.</inlineHelpText>
    <label>Days</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_IsConfirm__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_IsConfirm__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Confirm?</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/PerformProject__c.object-meta.xml
<CustomObject>
    <label>프로젝트 수행팀</label>
    <nameField>
        <displayFormat>PJ-{0000}</displayFormat>
        <label>Seq</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>프로젝트에 참여한 사원 이름</inlineHelpText>
    <label>사원 명</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>수행 프로젝트</relationshipLabel>
    <relationshipName>EmployeePerformPjt</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/InputDate__c.field-meta.xml
<CustomField>
    <fullName>InputDate__c</fullName>
    <label>투입 일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/WithdrawDate__c.field-meta.xml
<CustomField>
    <fullName>WithdrawDate__c</fullName>
    <label>철수 일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/ViewHRInfoController_test.cls
@isTest
private class ViewHRInfoController_test {
    
    @isTest
    static void itShould() {
        System.debug(ViewHRInfoController.getInitData(TestObjectCreator.objPerformProject.Employee__c, '2019-01-06', '2019-12-31'));
    }
    
    @testSetup
    static void setData() {
        PerformProject__c objPerformProject = TestObjectCreator.objPerformProject;
        objPerformProject.InputDate__c 	 	= Date.valueOf('2019-01-01');
		objPerformProject.WithdrawDate__c 	= Date.valueOf('2019-12-31');        
        insert objPerformProject;
        
        
        HolidayAction__c objHolidayAction = TestObjectCreator.objHolidayAction;
		objHolidayAction.HolidayAction_Days__c  = 5;
		objHolidayAction.HolidayAction_Date1__c = Date.valueOf('2019-01-14');
		objHolidayAction.HolidayAction_Date2__c = Date.valueOf('2019-01-15');
		objHolidayAction.HolidayAction_Date3__c = Date.valueOf('2019-01-16');
		objHolidayAction.HolidayAction_Date4__c = Date.valueOf('2019-01-17');
		objHolidayAction.HolidayAction_Date5__c = Date.valueOf('2019-01-18');
        // objHolidayAction.HolidayAction_IsConfirm__c = true;

		insert objHolidayAction;
        
    }
}