PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/JoinDate__c.field-meta.xml
<CustomField>
    <fullName>JoinDate__c</fullName>
    <description>입사일자</description>
    <label>입사일자</label>
    <type>Date</type>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>사원 Object를 User Object간 Relationship 생성</inlineHelpText>
    <label>사용자 명</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/Holiday__c.object-meta.xml
<CustomObject>
    <label>Holiday</label>
    <nameField>
        <displayFormat>H-{0000}</displayFormat>
        <label>Holiday No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_Additionaldays__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Additionaldays__c</fullName>
    <formula>FLOOR((Holiday_RuleWorkingYears__c  - 1) / 2)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>추가연차일수</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_Annual_Calculated__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Annual_Calculated__c</fullName>
    <description>대유넥스티어 연차 계산법 기준이 회계연도로 변경되어 새로운 연차일수 계산 필드 생성 (생성일: 2022-12-27, 생성자: hyunsoo.song@daeunextier.com)

* 필드 설명 
- 1월 1일에 연차 일괄 부여
월차만료일 존재 X -&gt; 기존입사자 : 연차일수 15개 + 추가 연차일수
월차만료일 존재 -&gt; 신규입사자 : 반올림((12.31 - 입사월일)/365*15) 

ex1) 오늘 2023년 1월 1일
사원A: 입사일 2022-05-16 → 월차만료일 존재 → 입사월일(05.16~12.31)/365*15 → 10개
사원C: 입사일 2022-01-01 → 월차만료일 존재 X → 15 + 0 → 15개
사원D: 입사일 2019-09-04 → 월차만료일 존재 X → 15 + 1 → 16개

ex2) 오늘 2022년 12월 27일
사원A: 입사일 2022-05-16 -&gt; 월차만료일 존재 -&gt; 0개</description>
    <formula>IF(
    ISNULL(Holiday_Monthly_Period__c),
    15 + MIN(Holiday_Additionaldays__c, 10),
    IF(
        DATE(YEAR(Holiday_JoinDate__c) + 1, 1, 1) &lt;= TODAY(),
        CEILING((DATE(YEAR(Holiday_JoinDate__c), 12, 31) - Holiday_JoinDate__c + 1 ) / 365 * 15), 0
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>올해 발생한 연차일수</inlineHelpText>
    <label>올해 연차일수</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_Calculated__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Calculated__c</fullName>
    <description>대유넥스티어 사내 규칙에 맞는 연차여부 필드 수정으로 인한 예시 변경(수정일: 2021-12-31, 수정자: cj.sohn@daeunextier.com)
* 연차여부 수식 수정:
입사기준일인 경우, 입사일 + 365일
연차기준일(2020. 1. 1)인 경우, 입사일 다음년도 (연차 기준일)월 (연차 기준일)일 - 1

필드 설명
연차여부가 TRUE일 때, 15일 + 추가연차일수
연차여부가 FALSE일 때, 12 - (입사월 + 1)
ex)  오늘 2022년 3월 17일
       사원A: 입사일 2020-03-17 → 연차적용시작일(2020-12-31) → 연차여부 = TRUE → 15 + 0 개
       사원B: 입사일 2021-12-07 → 연차적용시작일(2021-12-31) → 연차여부 = TRUE → 15 + 0 개
       사원C: 입사일 2022-01-01 → 연차적용시작일(2022-12-31) → 연차여부 = FALSE → 12 - 1 = 11개
       사원D: 입사일 2022-01-04 → 연차적용시작일(2022-12-31) → 연차여부 = FALSE → 12 - (1 + 1) = 10개

휴가 연차일수 부여 개편으로 인한 수정(필드 수식 수정일: 2021-01-12, 필드 수정자: cj.sohn@daeunextier.com)
연차여부 수식 수정 이전 예시:
ex)  오늘 2021년 2월 4일
       사원A: 입사일 2020-12-07 → 연차적용시작일(2021-01-01) → 연차여부 = TRUE → 15 + 0 개
       사원B: 입사일 2021-01-01 → 연차적용시작일(2022-01-01) → 연차여부 = FALSE → 12 - 1 = 11개
       사원C: 입사일 2021-01-04 → 연차적용시작일(2022-01-01) → 연차여부 = FALSE → 12 - (1 + 1) = 10개</description>
    <formula>IF(
	Holiday_IsAnnualleave__c,
	15 + MIN(Holiday_Additionaldays__c , 10 ),
        IF(
                DAY(Holiday_JoinDate__c) = 1,
                IF(
	        	12 - (MONTH(Holiday_JoinDate__c) + 1) &lt; 0, 
	        	1,
	        	12 - MONTH(Holiday_JoinDate__c)
        	),
               	IF(
	        	12 - (MONTH(Holiday_JoinDate__c) + 1) &lt; 0, 
	        	0,
	        	12 - (MONTH(Holiday_JoinDate__c) + 1)
        	)
        )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>연차일수</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_GivenHolidays__c.field-meta.xml
<CustomField>
    <fullName>Holiday_GivenHolidays__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>추가적으로 부여된 연월차일수</inlineHelpText>
    <label>추가 부여 일수</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_IsActive__c.field-meta.xml
<CustomField>
    <fullName>Holiday_IsActive__c</fullName>
    <formula>!ISBLANK(Employee__c) &amp;&amp; Employee__r.Status__c</formula>
    <label>재직여부</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_IsAnnualleave__c.field-meta.xml
<CustomField>
    <fullName>Holiday_IsAnnualleave__c</fullName>
    <formula>Holiday_StartDate__c &lt;=  TODAY()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>연차여부</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_JoinDate__c.field-meta.xml
<CustomField>
    <fullName>Holiday_JoinDate__c</fullName>
    <label>입사일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_LastActivity__c.field-meta.xml
<CustomField>
    <fullName>Holiday_LastActivity__c</fullName>
    <label>최종 사용 내역</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_Monthly_Calculated__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Monthly_Calculated__c</fullName>
    <description>대유넥스티어 연차 계산법 기준이 회계연도로 변경되어 필드 생성 (생성일: 2022-12-27, 생성자: hyunsoo.song@daeunextier.com)

* 필드 설명
1. 입사 1년차 이상 (월차 만료일 == BLANK || 전년도 월차일수 == 11개)
: 0

2. 신규입사자
: 입사연도 다음 해로 변경될 시 다시 1부터 Count (단, 입사일자의 DAY에 해당하는 일자 하루 전 날 부여됨)

ex) 오늘 2023년 01월 13일
사원A: 입사일 2022-05-16 → 월차 만료일(2023-12-31) →  0개	(매달 15일에 월차 부여)
사원B: 입사일 2022-12-13 → 월차 만료일(2023-12-31) → 1개 	(매달 12일에 월차 부여)

사원C: 입사일 2022-01-01 → 월차 만료일(2023-12-31) → 0개	(전년도 월차 11개, 올해 월차 0개)
사원D: 입사일 2021-09-04 → 월차 만료일(BLANK) → 0개</description>
    <formula>IF(
    ISBLANK(Holiday_Monthly_Period__c) || MonthlyOfLastYear__c = 11, 0,
    IF(
        YEAR(Holiday_Monthly_Period__c) = YEAR(TODAY()),
        11 - MonthlyOfLastYear__c,
        IF(
            FLOOR((DATE(YEAR(TODAY()), 12, 31) - Holiday_JoinDate__c - 1) / 30) &gt; 11,
            11,
            FLOOR((DATE(YEAR(TODAY()), 12, 31) - Holiday_JoinDate__c - 1) / 30)
        )
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>올해 발생한 월차일수 (월차는 입사일에 해당하는 일자 하루 전 날 부여됩니다.)</inlineHelpText>
    <label>올해 월차일수</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_Monthly_Period__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Monthly_Period__c</fullName>
    <formula>IF( 
    YEAR(ADDMONTHS(Holiday_JoinDate__c, 12)) &lt; YEAR(TODAY()), 
    NULL, 
    DATE(YEAR(ADDMONTHS(Holiday_JoinDate__c, 12)), 12, 31)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>월차 만료일</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_NoticeLevel__c.field-meta.xml
<CustomField>
    <fullName>Holiday_NoticeLevel__c</fullName>
    <label>공지 단계</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Need</fullName>
                <default>true</default>
                <label>Not Need</label>
            </value>
            <value>
                <fullName>1st Notice</fullName>
            </value>
            <value>
                <fullName>2nd Notice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_PeriodEnd__c.field-meta.xml
<CustomField>
    <fullName>Holiday_PeriodEnd__c</fullName>
    <description>수식 필드에 대한 상세설명 작성(필드 상세설명 수정일: 2021-12-23, 수정자: cj.sohn@daeunextier.com)
1. 입사일 기준여부가 TRUE일 때,
1-1) 금연도 입사월일이 오늘보다 작을 때, 금연도 입사월일 - 1 + 365
1-2) 금연도 입사월일이 오늘보다 크거나 같을 때, 금연도 입사월일 -1 + 0

ex) 오늘: 2021년 12월 23일
사원A: 입사일 2019-12-15 →  금연도 입사월일 (2021-12-15) → 연차만료일: 2022-12-15
사원B: 입사일 2020-12-28 → 금연도 입사월일 (2021-12-28) → 연차만료일: 2021-12-28
사원C: 입사일 2021-12-23 →  금연도 입사월일 (2021-12-23) → 연차만료일: 2022-12-22

2. 입사일 기준여부가 FALSE일 때,
2-1) 금연도 말일이 오늘보다 클 때, 전연도 말일 + 365
2-2) 금연도 말일이 오늘보다 작거나 같을 때, 전연도 말일 + 0 (가능성 0%)

ex) 오늘: 2021년 2월 4일, 금연도 말일: 2021년 12월 31일 → 연차만료일: 2021년 12월 31일

* 참고사항
Custom Setting(HolidaySetting__c)의 필드 및 값 정리 (2021-12-23 기준)
- 연차기준일(HoldayRuleDate__c): 2000. 1. 1
- 갱신일 이전 일수 차감여부(IsCeil__c): true
- 입사일 기준여부(JoinDateRule__c): false</description>
    <formula>IF(
    $Setup.HolidaySetting__c.JoinDateRule__c,
    DATE( YEAR(TODAY()), MONTH(Holiday_JoinDate__c), DAY(Holiday_JoinDate__c) ) - 1 +
    IF(
        DATE( YEAR(TODAY()), MONTH(Holiday_JoinDate__c), DAY(Holiday_JoinDate__c) ) &lt; TODAY(),
        365,
        0
    ),
    DATE( YEAR(TODAY()), MONTH($Setup.HolidaySetting__c.HoldayRuleDate__c ), DAY($Setup.HolidaySetting__c.HoldayRuleDate__c) ) - 1 +
    IF(
        DATE( YEAR(TODAY()), MONTH($Setup.HolidaySetting__c.HoldayRuleDate__c), DAY($Setup.HolidaySetting__c.HoldayRuleDate__c) ) &lt; TODAY(),
        365,
        0
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>연차만료일</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_Remain__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Remain__c</fullName>
    <description>4월1일 이전인 경우, 잔여일수=연차일수-사용일수+전년도 연차 잔여일수
3월31일 이후인 경우, 잔여일수=연차일수-사용일수

22.03.31
임시로 기준일을 12월 31일로 변경
변경전: TODAY() &lt;  DATE(YEAR(TODAY()), 4, 1)
변경후: TODAY() &lt;=  DATE(YEAR(TODAY()), 12, 31)</description>
    <formula>IF(
    TODAY() &lt;  DATE(YEAR(TODAY()), 4, 1),
    NULLVALUE( Holiday_Calculated__c , 0) -  NULLVALUE(Holiday_UseDays__c  , 0) +  Holiday_GivenHolidays__c + RemainOfLastYear__c ,
    NULLVALUE( Holiday_Calculated__c , 0) -  NULLVALUE(Holiday_UseDays__c  , 0) +  Holiday_GivenHolidays__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>전년도 잔여연차 사용을 임시로 올해 12월 31일까지 사용 가능하도록 변경되었습니다.</inlineHelpText>
    <label>잔여일수</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_StartDate__c.field-meta.xml
<CustomField>
    <fullName>Holiday_StartDate__c</fullName>
    <description>대유넥스티어 사내 규칙에 맞는 연차여부 필드 수정(수정일: 2021-12-31, 수정자: cj.sohn@daeunextier.com)
입사기준일인 경우, 입사일 + 365일
연차기준일인 경우, 입사일 다음년도 (연차 기준일)월 (연차 기준일)일 - 1

변경 전 수식
필드 설명 추가(수정일: 2021-01-12, 수정자: cj.sohn@daeunextier.com)
입사기준일인 경우, 입사일 + 365일
연차기준일인 경우, 입사일 다음년도 (연차 기준일)월 (연차 기준일)일
IF(
    $Setup.HolidaySetting__c.JoinDateRule__c, 
    Holiday_JoinDate__c + 365,
    Date(Year(Holiday_JoinDate__c)+1, MONTH($Setup.HolidaySetting__c.HoldayRuleDate__c), DAY($Setup.HolidaySetting__c.HoldayRuleDate__c))
)</description>
    <formula>IF(
    $Setup.HolidaySetting__c.JoinDateRule__c, 
    Holiday_JoinDate__c + 365,
    Date(Year(Holiday_JoinDate__c)+1, MONTH($Setup.HolidaySetting__c.HoldayRuleDate__c), DAY($Setup.HolidaySetting__c.HoldayRuleDate__c))-1
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>연차적용시작일</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_Uncountable__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Uncountable__c</fullName>
    <defaultValue>0</defaultValue>
    <label>공무</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_Unpaid__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Unpaid__c</fullName>
    <defaultValue>0</defaultValue>
    <label>무급휴가</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_UseDays__c.field-meta.xml
<CustomField>
    <fullName>Holiday_UseDays__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>올해 연월차 사용일수</inlineHelpText>
    <label>연월차 사용일수</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_User__c.field-meta.xml
<CustomField>
    <fullName>Holiday_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>임직원</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Holiday</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_WorkingYears__c.field-meta.xml
<CustomField>
    <fullName>Holiday_WorkingYears__c</fullName>
    <description>입사일 기준 근속 년수</description>
    <formula>YEAR(TODAY()) - YEAR(Holiday_JoinDate__c) 
+ IF(
   MONTH(TODAY()) * 100 + DAY(TODAY()) &gt;= 
   MONTH(Holiday_JoinDate__c) * 100 + 
   DAY( Holiday_JoinDate__c) 
   , 0 
   , -1
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>근속연수</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/HolidayRemainOfLastYear__c.field-meta.xml
<CustomField>
    <fullName>HolidayRemainOfLastYear__c</fullName>
    <defaultValue>0.0</defaultValue>
    <description>대유넥스티어 연차 계산법 기준이 회계연도로 변경되어 필드 생성 (생성일: 2022-12-27, 생성자: hyunsoo.song@daeunextier.com)

* 필드 설명
이 필드는 매년 12월 31일 23시 00분에 &apos;HolidayLastYearUpdate 매년 12월 31일 업데이트&apos; 스케줄러로 업데이트됨.</description>
    <inlineHelpText>전년도에 발생한 연월차 사용 후 잔여일수</inlineHelpText>
    <label>전년도 연월차 잔여일수</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/RemainOfLastYear__c.field-meta.xml
<CustomField>
    <fullName>RemainOfLastYear__c</fullName>
    <formula>CarriedOverOfLastYear__c - UseDaysOfLastYear__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>전년도 연차 잔여일수</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/HolidayManageController.cls
/**
 * @description       : HolidayManage.cmp(휴일 관리(관리자용))에서 호출하는 Apex Class
 * @author            : 알 수 없음
 * Modifications Log
 * Ver   Date         Author                        Modification
 * 2.0   2021.01.12   cj.sohn@daeunextier.com       Modified
 * 2.1   2022.06.14   yc.park@daeunextier.com       Modified
 * 2.2   2022.12.27   hyunsoo.song@daeunextier.com  Modified
**/
public class HolidayManageController {
    private static Map<String, String> pickListValuesList;
    private static Boolean isFirst = true;

    /**
     * @param pIsChecked
     * 휴가관리 탭화면 Init 함수
     * @return List<HolidayEmployeeWrapper>
     */
    @AuraEnabled
    public static List<HolidayEmployeeWrapper> getData(Boolean pIsChecked) {
        pIsChecked = !pIsChecked;
        List<Holiday__c> hldLst = [
                SELECT Id, Name, Holiday_Additionaldays__c, Holiday_Calculated__c, Holiday_GivenHolidays__c, Holiday_IsActive__c, Holiday_IsAnnualleave__c, Holiday_JoinDate__c,
                        Holiday_LastActivity__c, Holiday_NoticeLevel__c, Holiday_PeriodEnd__c, Holiday_Remain__c, Holiday_StartDate__c, Holiday_Uncountable__c, Holiday_Unpaid__c, Holiday_UseDays__c,
                        Holiday_User__c, Holiday_User__r.Name, Holiday_User__r.UserRole.Name, Holiday_User__r.Title, Holiday_WorkingYears__c, Holiday_Monthly_Calculated__c,
                        Holiday_Annual_Calculated__c, Holiday_Monthly_Period__c, HolidayRemainOfLastYear__c, RemainOfLastYear__c, Holiday_Total_Remain__c, Holiday_rewardDays__c,
                        Holiday_WomenHoliday_Count__c, Holiday_SickLeave_Count__c, Holiday_FamilyEvent_Count__c, Holiday_PublicWorks_Count__c, MonthlyOfLastYear__c, Holiday_Total_Count__c,
                        fm_Holiday_rewardRemainDays__c, Holiday_reward_Total_Count__c, Holiday_BenefitPaymentDays__c
                FROM Holiday__c
                WHERE Holiday_IsActive__c = :pIsChecked
                ORDER BY Employee__r.EmployeeNo__c
        ];
        System.debug('hldLst : ' + hldLst);

        Map<Id, Employee__c> mapEmployee = new Map<Id, Employee__c>();
        for (Employee__c objEmp : [SELECT Department__c, Position__c, User__c, EmployeeNo__c FROM Employee__c WHERE Status__c = :pIsChecked]) {
            mapEmployee.put(objEmp.User__c, objEmp);
        }
        System.debug('mapEmployee : ' + mapEmployee);

        List<HolidayEmployeeWrapper> listWrapper = new List<HolidayEmployeeWrapper>();
        for (Holiday__c objHoliday : hldLst) {

            HolidayEmployeeWrapper objHEW = new HolidayEmployeeWrapper(objHoliday, mapEmployee.get(objHoliday.Holiday_User__c));
            System.debug('HolidayEmployeeWrapper : ' + objHEW);
            listWrapper.add(objHEW);
        }
        System.debug(String.format('List<HolidayEmployeeWrapper> (size : {0}) : {1}', new List<Object>{ listWrapper.size(), listWrapper }));

        return listWrapper;
    }

    @AuraEnabled
    public static String doSave(List<Holiday__c> hldLst) {
        System.debug(String.format('List<Holiday__c> (size : {0}) : {1}', new List<Object>{ hldLst.size(), hldLst }));
        for (Holiday__c obj : hldLst) {
            System.debug('Holiday__c : ' + obj);
        }

        try {
            update hldLst;
            return '저장되었습니다.';
        } catch (DmlException dmlExcept) {
            System.debug(String.format('[Error] {0}, Line : {1}', new List<Object>{ dmlExcept.getMessage(), dmlExcept.getLineNumber() }));
            return '에러가 발생했습니다. / ' + dmlExcept.getMessage();
        }
    }

    /**
     * @description       : 휴가 추가 일수 타입 변경 (Integer->Decimal)
     * @author            : yc.park@daeunextier.com
     * @group             : DaeuNextier
     * @return            : String
    **/
    @AuraEnabled
    public static String doModify(List<Map<String, Object>> hldLst, Decimal addDays, String addDesc) {

        Decimal day = 0;
        String msg = UserInfo.getLastName();
        try {
            day = addDays;
        } catch (Exception e) {
            System.debug(String.format('[Error] {0}, Line : {1}', new List<Object>{ e.getMessage(), e.getLineNumber() }));
        }

        msg += ' had adding ' + String.valueOf(day) + ' day(s). Reason : ';
        msg += String.format(' had adding {0} day(s). Reason : {1}', new List<Object>{ String.valueOf(day), (addDesc == null || addDesc == '') ? 'Additional Holidays.' : addDesc});

        //2023.06.13 yj.kim 수정 - 에러발생
        System.debug('hldLst : ' + hldLst);
        System.debug('day : ' + day);
        Map<String, Object> mapTarget = new Map<String, Object>();
        List<Holiday__c> updateList = new List<Holiday__c>();
        for (Object hld : hldLst) {
            mapTarget = (Map<String, Object>) hld;

            System.debug('Holiday_GivenHolidays__c : ' + mapTarget.get('GivenHolidays'));
            Holiday__c obj = new Holiday__c();

            obj.Id = String.valueOf(mapTarget.get('Id'));
            if(mapTarget.get('GivenHolidays') != null){
                System.debug('1');
                obj.Holiday_GivenHolidays__c = Double.valueOf(mapTarget.get('GivenHolidays')) + day ;
            }else{
                System.debug('2');
                obj.Holiday_GivenHolidays__c = Double.valueOf(mapTarget.get('GivenHolidays'));
            }
            obj.Holiday_LastActivity__c = msg ;

            updateList.add(obj);
        }

        try {
            update updateList;
            return '저장되었습니다.';
        } catch (Exception e) {
            System.debug(String.format('[Error] {0}, Line : {1}', new List<Object>{ e.getMessage(), e.getLineNumber() }));
            return '에러가 발생했습니다. / ' + e.getMessage();
        }
    }

    @AuraEnabled
    public static String doSend(List<Holiday__c> hldLst) {
        try {
            List<User> usrLst = new List<User>();
            Set<Id> usrIdSet = new Set<Id>();
            for (Holiday__c hld : hldLst) {
                usrIdSet.add(hld.Holiday_User__c);
            }
            usrLst = [SELECT Email, Name FROM User WHERE Id = :usrIdSet];
            Map<Id, User> usrMap = new Map<Id, User>();
            for (User usr : usrLst) {
                usrMap.put(usr.Id, usr);
            }
            Integer sendCnt = 0;
            Integer errCnt = 0;
            for (Holiday__c hld : hldLst) {
                Boolean finish = HolidayUtil.sendEmail('Info', usrMap.get(hld.Holiday_User__c), hld);
                if (finish) {
                    sendCnt++;
                } else {
                    errCnt++;
                }
            }
            return '발송이 완료되었습니다. 성공 : ' + String.valueOf(sendCnt) + '건, 실패 : ' + String.valueOf(errCnt) + '건.';
        } catch (Exception dmlExcept) {
            System.debug(String.format('[Error] {0}, Line : {1}', new List<Object>{ dmlExcept.getMessage(), dmlExcept.getLineNumber() }));
            return '에러가 발생했습니다. / ' + dmlExcept.getMessage();
        }
    }
    
    @AuraEnabled
    public static String doReset(List<Holiday__c> hldLst, String type) {
        String msg = UserInfo.getLastName() + ' had reset ' + type + ' holidays.';
        for (Holiday__c hld : hldLst) {
            if (type == 'unpaid') {
                hld.Holiday_Unpaid__c = 0;
            } else if (type == 'uncountable') {
                hld.Holiday_Uncountable__c = 0;
            }

            hld.Holiday_LastActivity__c = msg ;
        }
        try {
            update hldLst;
            return '저장되었습니다.';
        } catch (DmlException dmlExcept) {
            System.debug(String.format('[Error] {0}, Line : {1}', new List<Object>{ dmlExcept.getMessage(), dmlExcept.getLineNumber() }));
            return '에러가 발생했습니다. / ' + dmlExcept.getMessage();
        }
    }

    @AuraEnabled
    public static String doCreate() {
        try {
            List<User> usrLst = [SELECT Id, CreatedDate FROM User WHERE Id NOT IN (SELECT Holiday_User__c FROM Holiday__c) AND IsActive = TRUE AND UserType = 'Standard'];
            if (usrLst.isEmpty()) {
                return 'There is no new employee.';
            }

            /**
             * @author            : cj.sohn@daeunextier.com
             * @description       : 사용자에 해당하는 사원 정보를 조회하여 사용자별 입사일을 맵핑하도록 수정.
             * @last modified on  : 2021-01-12
            **/
            Set<Id> setUserIds = new Set<Id>();
            for (User usr : usrLst) {
                setUserIds.add(usr.Id);
            }
            List<Employee__c> listEmployees = [SELECT Id, User__c, JoinDate__c FROM Employee__c WHERE User__c IN :setUserIds];
            Map<Id, Employee__c> mapJoinDateByUserId = new Map<Id, Employee__c>();
            if (listEmployees.size() > 0) {
                for (Employee__c employee : listEmployees) {
                    mapJoinDateByUserId.put(employee.User__c, employee);
                }
            }

            List<Holiday__c> hLst = new List<Holiday__c>();
            for (User usr : usrLst) {
                Date joinDate = mapJoinDateByUserId.get(usr.Id) == null || mapJoinDateByUserId.get(usr.Id).JoinDate__c == null ? Date.valueOf(usr.CreatedDate) : mapJoinDateByUserId.get(usr.Id).JoinDate__c;
                Id employeeId = mapJoinDateByUserId.get(usr.Id) == null ? null : mapJoinDateByUserId.get(usr.Id).Id;
                Holiday__c h = new Holiday__c(Holiday_JoinDate__c = joinDate, Employee__c = employeeId, Holiday_LastActivity__c = 'Created.', Holiday_NoticeLevel__c = 'Not Need', Holiday_User__c = usr.Id);
                hLst.add(h);
            }
            insert hLst;
            /** ===============================END=============================== **/

            List<Holiday__Share> hsLst = new List<Holiday__Share>();
            for (Holiday__c h : hLst) {
                Holiday__Share hldShr = new Holiday__Share();
                hldShr.ParentId = h.Id;
                hldShr.RowCause = Schema.Holiday__Share.RowCause.Holiday_Owner__c;
                hldShr.UserOrGroupId = h.Holiday_User__c ;
                hldShr.AccessLevel = 'Read';
                hsLst.add(hldShr);
            }
            insert hsLst;
            return String.valueOf(hsLst.size()) + '명의 휴일정보가 생성되었습니다.';

        } catch (DmlException dmlExcept) {
            System.debug(String.format('[Error] {0}, Line : {1}', new List<Object>{ dmlExcept.getMessage(), dmlExcept.getLineNumber() }));
            return '에러가 발생했습니다. / ' + dmlExcept.getMessage();
        }
    }

    /**
     * @description       : 임직원 정보를 Employee__c에서 수정 시 업데이트 버튼을 통해 Holiday__c에 존재하는 직원 정보 업데이트
     * @author            : hyunsoo.song@daeunextier.com
     * @group             : DaeuNextier
     * @return            : String
    **/
    @AuraEnabled
    public static String doUpdate() {
        try {
            // 등록된 직원 리스트
            List<Employee__c> listEmployees = [SELECT Id, User__c, Name, JoinDate__c, Status__c FROM Employee__c];
            if (listEmployees.size() > 0) {
                Map<Id, Employee__c> mapJoinDateByUserId = new Map<Id, Employee__c>();
                for (Employee__c employee : listEmployees) {
                    mapJoinDateByUserId.put(employee.User__c, employee);
                }

                Boolean changeFlag = false;
                Map<Id, Holiday__c> mapJoinDateHoliday = new Map<Id, Holiday__c>();
                for (Holiday__c holiday : [SELECT Id, Holiday_JoinDate__c, Holiday_User__c, Holiday_IsActive__c, Employee__c FROM Holiday__c WHERE Holiday_User__c != NULL]) {
                    changeFlag = false;

                    // 입사일자
                    if (mapJoinDateByUserId.get(holiday.Holiday_User__c) != null && (mapJoinDateByUserId.get(holiday.Holiday_User__c).JoinDate__c != holiday.Holiday_JoinDate__c)) {
                        holiday.Holiday_JoinDate__c = mapJoinDateByUserId.get(holiday.Holiday_User__c).JoinDate__c;
                        changeFlag = true;
                    }

                    // Employee
                    if (holiday.Employee__c == null && mapJoinDateByUserId.get(holiday.Holiday_User__c) != null) {
                        holiday.Employee__c = mapJoinDateByUserId.get(holiday.Holiday_User__c).Id;
                        changeFlag = true;
                    }

                    if(changeFlag) {
                        mapJoinDateHoliday.put(holiday.Id, holiday);
                    }
                }

                if (mapJoinDateHoliday.size() > 0) {
                    update mapJoinDateHoliday.values();
                    return String.valueOf(mapJoinDateHoliday.size()) + '명의 임직원 정보가 업데이트 되었습니다.';
                }
            }

            return '정보가 수정된 임직원이 존재하지 않습니다.';
        } catch (DmlException dmlExcept) {
            System.debug('dmlExcept.getMessage() : ' + dmlExcept.getMessage() + ' line : ' + dmlExcept.getLineNumber());
            return '에러가 발생했습니다. / ' + dmlExcept.getMessage();
        }
    }

    public class HolidayEmployeeWrapper {
        @AuraEnabled public String Id;                              // Holiday__c
        @AuraEnabled public String Name;                            // Holiday__c
        @AuraEnabled public String User;                            // Holiday__c
        @AuraEnabled public String UserName;                        // Holiday__c
        @AuraEnabled public Date JoinDate;                          // Holiday__c
        @AuraEnabled public String SumMonthly;                      // Holiday__c
        @AuraEnabled public String MonthlyPeriod;                   // Holiday__c
        @AuraEnabled public String RemainOfLastYear;                // Holiday__c
        @AuraEnabled public String AnnualCalculated;                // Holiday__c
        @AuraEnabled public String SumAnnualCalcRemainLastYear;     // Holiday__c
        @AuraEnabled public String PublicWorksCount;                // Holiday__c
        @AuraEnabled public String GivenHolidays;                   // Holiday__c
        @AuraEnabled public String UseDays;                         // Holiday__c
        @AuraEnabled public String TotalRemain;                     // Holiday__c
        @AuraEnabled public String FamilyEventCount;                // Holiday__c
        @AuraEnabled public String SickLeaveCount;                  // Holiday__c
        @AuraEnabled public String WomenHolidayCount;               // Holiday__c
        @AuraEnabled public String rewardDaysCount;                 // Holiday__c
        @AuraEnabled public String rewardRemainDays;                // Holiday__c
        @AuraEnabled public String totalrewardDays;                 // Holiday__c
        @AuraEnabled public String BenefitPaymentDays;              // Holiday__c

        @AuraEnabled public String Department;                      // Employee__c
        @AuraEnabled public String Position;                        // Employee__c
        @AuraEnabled public String EmployeeNo;                      // Employee__c

        public HolidayEmployeeWrapper(Holiday__c objHoliday, Employee__c objEmployee) {
            this.Id                             = objHoliday.Id;
            this.Name                           = objHoliday.Name;
            this.User                           = objHoliday.Holiday_User__c;
            this.UserName                       = objHoliday.Holiday_User__r.Name;
            this.JoinDate                       = objHoliday.Holiday_JoinDate__c;
            this.SumMonthly                     = objHoliday.MonthlyOfLastYear__c != null ? String.valueOf(objHoliday.Holiday_Monthly_Calculated__c + objHoliday.MonthlyOfLastYear__c) : String.valueOf(objHoliday.Holiday_Monthly_Calculated__c);
            this.MonthlyPeriod                  = String.valueOf(objHoliday.Holiday_Monthly_Period__c);
            this.RemainOfLastYear               = String.valueOf(objHoliday.HolidayRemainOfLastYear__c);
            this.AnnualCalculated               = String.valueOf(objHoliday.Holiday_Annual_Calculated__c);

            // 총 연월차 (전년도 연월차 잔여일수 + 올해 월차일수 + 올해 연차일수)
            this.SumAnnualCalcRemainLastYear    = String.valueOf(objHoliday.Holiday_Total_Count__c);
            this.PublicWorksCount               = String.valueOf(objHoliday.Holiday_PublicWorks_Count__c);
            this.GivenHolidays                  = String.valueOf(objHoliday.Holiday_GivenHolidays__c);
            this.UseDays                        = String.valueOf(objHoliday.Holiday_UseDays__c);
            this.TotalRemain                    = String.valueOf(objHoliday.Holiday_Total_Remain__c);
            this.FamilyEventCount               = String.valueOf(objHoliday.Holiday_FamilyEvent_Count__c);
            this.SickLeaveCount                 = String.valueOf(objHoliday.Holiday_SickLeave_Count__c);
            this.WomenHolidayCount              = String.valueOf(objHoliday.Holiday_WomenHoliday_Count__c);
            this.rewardDaysCount                = String.valueOf(objHoliday.Holiday_rewardDays__c);
            this.rewardRemainDays               = String.valueOf(objHoliday.fm_Holiday_rewardRemainDays__c);
            this.totalrewardDays                = String.valueOf(objHoliday.Holiday_reward_Total_Count__c);
            this.BenefitPaymentDays             = String.valueOf(objHoliday.Holiday_BenefitPaymentDays__c);

            if (objEmployee != null) {
                this.Department                 = objEmployee.Department__c;
                if (isFirst) pickListValuesList = getPositionLabel();
                this.Position                   = pickListValuesList.get(objEmployee.Position__c);
                this.EmployeeNo                 = objEmployee.EmployeeNo__c;
            }
        }

        public Map<String, String> getPositionLabel() {
            isFirst = false;
            pickListValuesList = new Map<String, String>();

            List<Schema.PicklistEntry> ple = Employee__c.Position__c.getDescribe().getPicklistValues();
            for (Schema.PicklistEntry pickListVal : ple) {
                pickListValuesList.put(pickListVal.getValue(), pickListVal.getLabel());
            }

            return pickListValuesList;
        }
    }
}