PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

ListViewButton/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>구분</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>내부직원</fullName>
            </value>
            <value>
                <fullName>외부직원</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/PerformProject__c.object-meta.xml
<CustomObject>
    <label>프로젝트 수행팀</label>
    <nameField>
        <displayFormat>PJ-{0000}</displayFormat>
        <label>Seq</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>프로젝트에 참여한 사원 이름</inlineHelpText>
    <label>사원 명</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>수행 프로젝트</relationshipLabel>
    <relationshipName>EmployeePerformPjt</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/InputDate__c.field-meta.xml
<CustomField>
    <fullName>InputDate__c</fullName>
    <label>투입 일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/PerformProject_tr_test.cls
/************************************************************************************
* File Name   	    : PerformProject_tr testclass
* Author	  		: Yeonlim
* Date				: 2024-01-02
* Modification Log
* ===================================================================================
* Ver      Date            Author          Modification
* ===================================================================================
* 1.0      2024-01-02      Yeonlim           Create
************************************************************************************/
@IsTest
public with sharing class PerformProject_tr_test {
    @IsTest
    static void doTest() {
        Employee__c objEmployee = TestObjectCreator.objEmployee;
        objEmployee.Type__c = '외부직원';
        insert objEmployee;

        PerformProject__c objPerformProject = TestObjectCreator.objPerformProject;
        objPerformProject.InputDate__c = Date.today();
        insert objPerformProject;

        objPerformProject.InputDate__c = Date.today().addMonths(-3);
        update objPerformProject;
    }
}