PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>부서</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Departments</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>직급</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>총괄사장</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>대표이사</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>센터장</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>감사</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>부사장</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>전무</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>상무</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>수석</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>이사</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>부장</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>책임</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>차장</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>과장</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>대리</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>선임</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>선임(수습)</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>사원</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>사원(수습)</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>인턴</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>사원 Object를 User Object간 Relationship 생성</inlineHelpText>
    <label>사용자 명</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/Holiday__c.object-meta.xml
<CustomObject>
    <label>Holiday</label>
    <nameField>
        <displayFormat>H-{0000}</displayFormat>
        <label>Holiday No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Holiday</relationshipLabel>
    <relationshipName>Holiday</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/fm_Holiday_rewardRemainDays__c.field-meta.xml
<CustomField>
    <fullName>fm_Holiday_rewardRemainDays__c</fullName>
    <description>2023-12-14 Holiday_rewardRemainDays__c 사용하지 않고 해당 formula 필드로 사용 예정</description>
    <formula>Holiday_reward_Total_Count__c - Holiday_rewardDays__c - Holiday_BenefitPaymentDays__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>총 대체휴가일수 - 대체휴가 사용일수 - 대체휴가 수당 지급일수</inlineHelpText>
    <label>대체휴가 잔여일수</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_Total_Remain__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Total_Remain__c</fullName>
    <description>대유넥스티어 연차 계산법 기준이 회계연도로 변경되어 필드 생성 (생성일: 2022-12-27, 생성자: hyunsoo.song@daeunextier.com)

* 필드 설명
- 신규 입사자 &amp; 기존 입사자
: 올해 월차일수 + 올해 연차일수 + 전년도 연차 잔여일수 + 추가부여일수 - 사용일수</description>
    <formula>BLANKVALUE(Holiday_Monthly_Calculated__c, 0) +  BLANKVALUE(Holiday_Annual_Calculated__c, 0) + BLANKVALUE(HolidayRemainOfLastYear__c, 0) +  Holiday_GivenHolidays__c
-  Holiday_UseDays__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>총 연월차일수 + 추가 부여 일수 - 연월차 사용일수</inlineHelpText>
    <label>연월차 잔여일수</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_User__c.field-meta.xml
<CustomField>
    <fullName>Holiday_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>임직원</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Holiday</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/HolidayAction__c.object-meta.xml
<CustomObject>
    <description>HolidayAction__c</description>
    <label>휴가신청</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Departments</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>휴가신청</relationshipLabel>
    <relationshipName>HolidayActionV4Zc</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/FirstHolidayRequest__c.field-meta.xml
<CustomField>
    <fullName>FirstHolidayRequest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>1차 승인자 지정</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Holiday_Action1</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Date1__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Date1__c</fullName>
    <label>Date1</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Days__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Days__c</fullName>
    <inlineHelpText>Women&apos;s Holiday 1.
Alternative Holiday 0.
Other Holidays from 1 to 5.</inlineHelpText>
    <label>Days</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Parent__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Parent__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Holiday</label>
    <referenceTo>Holiday__c</referenceTo>
    <relationshipName>Holiday_Action</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Type__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Annual Holiday</fullName>
                <label>연차</label>
            </value>
            <value>
                <fullName>Half-day Leave</fullName>
                <label>반차</label>
            </value>
            <value>
                <fullName>Reward Holiday</fullName>
                <label>대체휴가</label>
            </value>
            <value>
                <fullName>Reward Half-Holiday</fullName>
                <label>대체휴가(반차)</label>
            </value>
            <value>
                <fullName>Public Works</fullName>
                <label>공가(공무)</label>
            </value>
            <value>
                <fullName>Family Leave</fullName>
                <label>경조휴가</label>
            </value>
            <value>
                <fullName>Sick Leave</fullName>
                <label>병가(무급)</label>
            </value>
            <value>
                <fullName>Women Holiday</fullName>
                <label>생리휴가</label>
            </value>
            <value>
                <fullName>가족돌봄휴가</fullName>
            </value>
            <value>
                <fullName>출산휴가</fullName>
            </value>
            <value>
                <fullName>휴직</fullName>
            </value>
            <value>
                <fullName>육아휴직</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>프로젝트 PM</fullName>
            </value>
            <value>
                <fullName>프로젝트 팀원</fullName>
            </value>
            <value>
                <fullName>본사근무</fullName>
            </value>
            <value>
                <fullName>임원</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Project_HolidayAction</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/PerformProject__c.object-meta.xml
<CustomObject>
    <label>프로젝트 수행팀</label>
    <nameField>
        <displayFormat>PJ-{0000}</displayFormat>
        <label>Seq</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>프로젝트에 참여한 사원 이름</inlineHelpText>
    <label>사원 명</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>수행 프로젝트</relationshipLabel>
    <relationshipName>EmployeePerformPjt</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/fm_FromDate__c.field-meta.xml
<CustomField>
    <fullName>fm_FromDate__c</fullName>
    <formula>BLANKVALUE( InputDate__c ,  Project__r.StartDate__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>시작일</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/fm_ToDate__c.field-meta.xml
<CustomField>
    <fullName>fm_ToDate__c</fullName>
    <formula>BLANKVALUE( WithdrawDate__c ,  Project__r.EndDate__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>종료일</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/InputDate__c.field-meta.xml
<CustomField>
    <fullName>InputDate__c</fullName>
    <label>투입 일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/IsPM__c.field-meta.xml
<CustomField>
    <fullName>IsPM__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PM여부</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트 명</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>프로젝트 수행팀</relationshipLabel>
    <relationshipName>Project</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/WithdrawDate__c.field-meta.xml
<CustomField>
    <fullName>WithdrawDate__c</fullName>
    <label>철수 일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>프로젝트에 대한 기본정보를 관리하며, Deal Closing 이후 생성한다. 영업담당자가 계약 체결 후 기초 데이터를 작성하며, 프로젝트 진행 중에는 PM이 관리하고, 대금청구/지급 관련 정보는 회계에서 관리한다.</description>
    <label>프로젝트</label>
    <nameField>
        <label>프로젝트 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/fields/PM__c.field-meta.xml
<CustomField>
    <fullName>PM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트 관리자</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PM</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/NewHolidayLightningExtension.cls
/**
* Component Name                : HolidayActionLightning.cmp
* Component Controller          : HolidayActionLightningController.js
* Component Helper              : HolidayActionLightningHelper.js
* Component Contorlller Class   : HolidayActionLightningExtension.cls
* Test Class                    : HolidayActionLightningExtension_Test.cls
* Description                   : 휴일관리 라이트닝 신청 폼
* Modification Log
* ===============================================================
* Ver     Date          Author           Modification
* ===============================================================
  1.0   2018.08.27      JK.lee              Create
  1.1   2019.04.26                          Modified
  2.0   2021.01.18      CJ.Sohn             Modified(승인자 자동 할당, 사원 정보 및 프로젝트 수행팀 이력(오늘 날짜 기준) 조회)
*/
global without sharing class NewHolidayLightningExtension {

    @AuraEnabled
    @RemoteAction
    public static Map<String, String> doHolidayAction(HolidayAction__c saveList) {
        String checkMessage = '';
        String createdRecordId = '';
        System.debug('saveList :: ' + saveList);

        try {
            String userId = UserInfo.getUserId();
            saveList.OwnerId = userId;

            Holiday__c objHoliday = [SELECT Id, Holiday_Total_Remain__c, fm_Holiday_rewardRemainDays__c FROM Holiday__c WHERE Holiday_User__c = :userId LIMIT 1];
            if(String.valueOf(saveList.HolidayAction_Parent__c) == '') {
                saveList.HolidayAction_Parent__c = objHoliday.Id;
                System.debug('HolidayActionParent 삽입 : ' + saveList.HolidayAction_Parent__c);
            }
            System.debug('saveList.HolidayAction_Parent__c :: ' + saveList.HolidayAction_Parent__c);

            // 반차 Half 및 대체휴가(반차) 일 경우, 사용일수를 0.5로 설정
            if(saveList.HolidayAction_Type__c == 'Half-day Leave' || saveList.HolidayAction_Type__c == 'Reward Half-Holiday') {
                saveList.HolidayAction_Days__c = 0.5;
            }

            // 휴가 타입 별, 유효성 체크 (생리휴가)
            if(saveList.HolidayAction_Type__c == 'Women Holiday') {
                Integer year = System.today().year();
                Integer mon  = System.today().month();
                Date fromdt  = Date.newInstance(year, mon, 1);
                Integer cnt  = [SELECT Id FROM HolidayAction__c WHERE HolidayAction_Parent__c = :saveList.HolidayAction_Parent__c AND HolidayAction_Date1__c >= :fromdt AND HolidayAction_Type__c = 'Women Holiday'].size();
                System.debug('cnt ::: ' + cnt);
                System.debug('year ::: ' + year);
                System.debug('mon ::: ' + mon);
                System.debug('fromdt :::' + fromdt);

                if(cnt > 0) {
                    checkMessage = 'Already applied a Women Holiday this month : 이미 이번달 여성 보건휴가를 신청했습니다.';
                    return new Map<String, String> {
                            'checkMessage' => checkMessage
                    };
                }
            }

            // 휴가 타입 별, 유효성 체크 (연차 및 반차)
            else if(saveList.HolidayAction_Type__c == 'Annual Holiday' || saveList.HolidayAction_Type__c == 'Half-day Leave') {
                System.debug(String.format('휴가 신청일 수 : {0}, 연월차 잔여일수 : {1}', new List<Object>{ saveList.HolidayAction_Days__c, objHoliday.Holiday_Total_Remain__c }));
                if(saveList.HolidayAction_Days__c > objHoliday.Holiday_Total_Remain__c) {
                    checkMessage = String.format('{0} :: 휴가 신청일 수 : {1}, 연월차 잔여일수 : {2}', new List<Object>{ Label.Cannot_Apply_Holiday, saveList.HolidayAction_Days__c, objHoliday.Holiday_Total_Remain__c });
                    return new Map<String, String> {
                            'checkMessage' => checkMessage
                    };
                }
            }

            // 휴가 타입 별, 유효성 체크 (대체휴가 및 대체휴가(반차))
            else if(saveList.HolidayAction_Type__c == 'Reward Holiday' || saveList.HolidayAction_Type__c == 'Reward Half-Holiday') {
                System.debug(String.format('휴가 신청일 수 : {0}, 대체휴가 잔여일수 : {1}', new List<Object>{ saveList.HolidayAction_Days__c, objHoliday.fm_Holiday_rewardRemainDays__c }));
                if(saveList.HolidayAction_Days__c > objHoliday.fm_Holiday_rewardRemainDays__c) {
                    checkMessage = String.format('{0} :: 휴가 신청일 수 : {1}, 대체휴가 잔여일수 : {2}', new List<Object>{ Label.Cannot_Apply_Reward_Holiday, saveList.HolidayAction_Days__c, objHoliday.fm_Holiday_rewardRemainDays__c });
                    return new Map<String, String> {
                            'checkMessage' => checkMessage
                    };
                }
            }

            // insert saveList 대신 saveresult를 통해 결과값 return 받기
            Database.SaveResult saveResult = Database.insert(saveList, true);
            createdRecordId = saveResult.getId();
            System.debug('saveList: ' + saveList);
            System.debug('created recordId:: ' + saveResult.getId());

            //레코드 공유 규칙
            /*
            if(userId != userId){ // NOTE : 이걸 내가 아닌 다른 사용자가 호출할 수 도 있는건가??
                HolidayAction__Share holidaySh = new HolidayAction__Share();
                holidaySh.ParentId = saveList.Id;
                holidaySh.UserOrGroupId = userId;
                //holidaySh.UserOrGroupId = obj.FirstHolidayRequest__c;
                holidaySh.AccessLevel = 'Edit';
                // holidaySh.RowCause = Schema.HolidayAction__Share.RowCause.ActionForAll__c;

                insert holidaySh;
            }
            */
        } catch (System.DmlException e) {
            for (Integer i = 0; i < e.getNumDml(); i++) {
                System.debug(' ==>'); // Boolean -> String 메세지가 2개이상이기 때문에 boolean값으로 받지 못한다.
                System.debug(e);
                System.debug(i);
                System.debug('e.getStackTraceString(): ' + e.getStackTraceString());
                System.debug('e.getLineNumber(): ' + e.getLineNumber());
                System.debug('e.getCause(): ' + e.getCause());
                checkMessage = String.valueOf(e.getDmlMessage(i)); // String value를 Integer로 받기
                System.debug('checkMessage=================================' + checkMessage);

                return new Map<String, String> {
                        'checkMessage' => checkMessage
                };
            }
        }

        System.debug('checkMessage :: ' + checkMessage);
        System.debug('createdRecordId :: ' + createdRecordId);

        return new Map<String, String> {
                'checkMessage' => checkMessage,
                'createdRecordId' => createdRecordId
        };
    }

    @AuraEnabled
    public static List<String> getSelectFieldName() {
        List<String> fieldName = new List<String>();
        Schema.DescribeSObjectResult objDescribe = HolidayAction__c.SObjectType.getDescribe();
        Map<String, Schema.SObjectField> fieldMap = objDescribe.fields.getMap();
        System.debug('fieldMap=============' + fieldMap);
        for (String strKey : fieldMap.keySet()) {
            Schema.SObjectField field = fieldMap.get(strKey);
            Schema.DescribeFieldResult fieldDescribe = field.getDescribe();
            fieldName.add(fieldDescribe.getName());
        }

        return fieldName;
    }

    @AuraEnabled
    public static String selfApproverCheck() {
        Id userId = UserInfo.getUserId();
        String.valueOf(userId);
        return userId;
    }

    /**
     * @description       : 사용자의 ApprovalLine1 필드의 1차 승인자를 리턴
     * @author            : cj.sohn@daeunextier.com
     * @group             : DaeuNextier
    */
    @AuraEnabled
    public static String[] getApproverId() {
        System.debug('getApproverId Apex====================');
        List<User> listUsers = [SELECT Id, ApprovalLine1__c FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];
        System.debug('listUsers :: ' + listUsers);
        System.debug('UserInfo.getUserId() :: ' + UserInfo.getUserId());
        if (listUsers.size() > 0) {
            return String.valueOf(listUsers.get(0).ApprovalLine1__c).split('/');
        } else {
            List<String> strings = new List<String>();
            strings.add(UserInfo.getUserId());
            return strings;
        }
    }

    /**
     * @description       : 사용자의 사원 정보(부서, 직급)와 프로젝트 수행팀 정보(현재 투입되어있는지 유무)를 리턴
     * @author            : cj.sohn@daeunextier.com
     * @group             : DaeuNextier
    */
    @AuraEnabled
    public static Map<String, Object> employeeStatus() {
        Map<String, Object> mapResult = new Map<String, Object>();

        List<Employee__c> userStatus = [
                SELECT Id, Name, Department__c, toLabel(Position__c), (
                        SELECT Id, Project__c, IsPM__c, fm_FromDate__c, fm_ToDate__c
                        FROM EmployeePerformPjt__r
                        WHERE InputDate__c <= :System.today()
                        AND ((WithdrawDate__c != NULL AND WithdrawDate__c >= :System.today())
                        OR WithdrawDate__c = NULL)
                        ORDER BY LastModifiedDate DESC
                )
                FROM Employee__c
                WHERE Employee__c.User__c = :UserInfo.getUserId()
        ];

        if (userStatus.size() > 0) {
            mapResult.put('userStatus', userStatus);

            if(!userStatus.get(0).EmployeePerformPjt__r.isEmpty()) {
//                PerformProject__c objPerformProject = [SELECT Id, Employee__r.User__c FROM PerformProject__c WHERE Project__c = :userStatus.get(0).EmployeePerformPjt__r.get(0).Project__c AND IsPM__c = true LIMIT 1];
                Project__c objProject = [SELECT Id, PM__c FROM Project__c WHERE Id = :userStatus.get(0).EmployeePerformPjt__r.get(0).Project__c  LIMIT 1];
                mapResult.put('pmId', objProject != null && objProject.PM__c != null ? objProject.PM__c : '');
            }

            return mapResult;
        } else {
            return null;
        }
    }

    /**
     * @description       : Position이 "프로젝트 팀원" 일 경우, 프로젝트 변경 시 프로젝트 관리자의 ID값 응답
     * @author            : jinwoo.jang@daeunextier.com
     * @group             : DaeuNextier
    */
    @AuraEnabled
    public static Map<String, Object> getProjectPmId(Id projectId) {
        Map<String, Object> mapResult = new Map<String, Object>();

//        List<PerformProject__c> objPerformProject = [SELECT Id, Employee__r.User__c FROM PerformProject__c WHERE Project__c = :projectId AND IsPM__c = true LIMIT 1];
        List<Project__c> objProject = [SELECT Id, PM__c FROM Project__c WHERE Id = :projectId  LIMIT 1];
        if (objProject != null && objProject.size() > 0) {
            mapResult.put('pmId', objProject.get(0).PM__c);
        }

        return mapResult;
    }

    /**
     * @description       : 사용자의 잔여 휴가일수, 잔여 대체휴가일수 조회
     * @author            : yj.kim@daeunextier.com
     * @group             : DaeuNextier
    */
    @AuraEnabled
    public static Map<String, Object> getHolidayRemain() {

        List<Holiday__c> listHoliday = [
                SELECT Holiday_Total_Remain__c, fm_Holiday_rewardRemainDays__c
                FROM Holiday__c
                WHERE Holiday_User__c =: UserInfo.getUserId()
        ];

        Map<String, Object> mapReturnValue = new Map<String, Object> {
                'totalRemain' => !listHoliday.isEmpty() && listHoliday.get(0).Holiday_Total_Remain__c != null       ?  listHoliday.get(0).Holiday_Total_Remain__c : 0 ,
                'rewardRemain' => !listHoliday.isEmpty() && listHoliday.get(0).fm_Holiday_rewardRemainDays__c != null  ?  listHoliday.get(0).fm_Holiday_rewardRemainDays__c : 0
        };

        return mapReturnValue;
    }


}