PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>직급</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>총괄사장</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>대표이사</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>센터장</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>감사</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>부사장</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>전무</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>상무</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>수석</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>이사</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>부장</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>책임</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>차장</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>과장</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>대리</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>선임</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>선임(수습)</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>사원</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>사원(수습)</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>인턴</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(ISBLANK( ExitDate__c) ||  ExitDate__c    &gt;    TODAY()  , TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>재직여부</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/PerformProject__c.object-meta.xml
<CustomObject>
    <label>프로젝트 수행팀</label>
    <nameField>
        <displayFormat>PJ-{0000}</displayFormat>
        <label>Seq</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>프로젝트에 참여한 사원 이름</inlineHelpText>
    <label>사원 명</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>수행 프로젝트</relationshipLabel>
    <relationshipName>EmployeePerformPjt</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트 명</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>프로젝트 수행팀</relationshipLabel>
    <relationshipName>Project</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>프로젝트에 대한 기본정보를 관리하며, Deal Closing 이후 생성한다. 영업담당자가 계약 체결 후 기초 데이터를 작성하며, 프로젝트 진행 중에는 PM이 관리하고, 대금청구/지급 관련 정보는 회계에서 관리한다.</description>
    <label>프로젝트</label>
    <nameField>
        <label>프로젝트 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>종료 일자</label>
    <type>Date</type>
</CustomField>

Test/force-app/main/default/classes/ChangeProjectMemberController_test.cls
@IsTest
public with sharing class ChangeProjectMemberController_test {

    @TestSetup
    static void makeData(){
        Project__c testProject1=new Project__c();
        testProject1.Name='Test IsProjectActive';
        testProject1.EndDate__c=Date.today().addDays(-1);
        testProject1.Status__c='종료';

        Project__c testProject2=new Project__c();
        testProject2.Name='Test In progressing';
        testProject2.EndDate__c=Date.today().addDays(1);
        testProject2.Status__c='진행중';

        insert testProject1;
        insert testProject2;

        Employee__c testEmployee1=new Employee__c();
        testEmployee1.EmployeeName__c='Test1';

        Employee__c testEmployee2=new Employee__c();
        testEmployee2.EmployeeName__c='Test2';

        insert testEmployee1;
        insert testEmployee2;

        ProjectMember__c testProjectMember=new ProjectMember__c();
        testProjectMember.Employee__c=testEmployee1.Id;
        testProjectMember.Project__c=testProject1.Id;
        testProjectMember.Position__c='PL';


        ProjectMember__c testProjectMember2=new ProjectMember__c();
        testProjectMember2.Employee__c=testEmployee2.Id;
        testProjectMember2.Project__c=testProject2.Id;
        testProjectMember2.Position__c='PM';

        insert testProjectMember;
        insert testProjectMember2;
    }
   @IsTest
    public static void testIsProjectActive() {
        Project__c testProjectActive=[
            SELECT Project__c.id, Project__c.Status__c
            FROM Project__c
            WHERE Project__c.Name='Test IsProjectActive'];

        System.Test.startTest();
        boolean result=ChangeProjectMemberController.isProjectActive(testProjectActive.id);
        System.Test.stopTest();
        System.assertEquals(false, result);
    }

    @IsTest
    public static void testGetProjectMembers(){
        Project__c testProject=[
            SELECT Id
            FROM Project__c
            WHERE Project__c.Name='Test IsProjectActive'
        ];
        
        System.Test.startTest();
        List<ProjectMember__c> testProjectMember=new List<ProjectMember__c>();
        testProjectMember=ChangeProjectMemberController.GetProjectMembers(testProject.Id);
        System.Test.stopTest();
        System.assertEquals(1, testProjectMember.size());
    }

    @IsTest
    public static void testGetMemberPosition(){
        ProjectMember__c testProjectMember=[
            SELECT Id
            FROM ProjectMember__c
            WHERE Project__r.Name='Test IsProjectActive'
        ];

        System.Test.startTest();
        String result=ChangeProjectMemberController.GetMemberPosition(testProjectMember.Id);
        System.Test.stopTest();
        System.assertEquals('PL', result);
    }
    
    @IsTest
    public static void testGetAvailableEmployees(){
        System.Test.startTest();
        List<Employee__c> testAvailableEmployees=new List<Employee__c>();
        testAvailableEmployees=ChangeProjectMemberController.GetAvailableEmployees();
        System.Test.stopTest();
        System.assertEquals(1, testAvailableEmployees.size());
    }

    @IsTest
public static void testReplaceProjectMember(){
    ProjectMember__c testProjectMember = [
        SELECT Id
        FROM ProjectMember__c
        WHERE Project__r.Name='Test In progressing'
    ];
    
    

    Employee__c testEmployee= [
        SELECT Id
        FROM Employee__c
        WHERE EmployeeName__c='Test1'
    ];

    System.Test.startTest();
    ChangeProjectMemberController.ReplaceProjectMember(testProjectMember.Id, testEmployee.Id);
    System.Test.stopTest();

    ProjectMember__c resultProjectMember = [
        SELECT Employee__r.EmployeeName__c
        FROM ProjectMember__c
        WHERE Id = :testProjectMember.Id
    ];

    System.assertEquals('Test1', resultProjectMember.Employee__r.EmployeeName__c);
}
}