PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Emergency_Contact__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Contact__c</fullName>
    <inlineHelpText>응급상황 시 연락가능한 전화번호</inlineHelpText>
    <label>비상연락번호</label>
    <type>Phone</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/ProfilePictureController_Test.cls
@isTest
Private class ProfilePictureController_Test{

    @IsTest static void ProfilePictureController_Test(){

        Test.startTest();

        /*00e90000001qLEaAAM*/
        Profile p = [select id from Profile where Name='System Administrator'];
        //p = TestDataFactory.getProfile('System Administrator');   

        /*실제신청자*/
        User user = new User(Alias = 'testUser'
                            , Email='SysAdminTestuser@earth.org'
                            , EmailEncodingKey='UTF-8'
                            , LastName='Testing'
                            , LanguageLocaleKey='en_US'
                            , LocaleSidKey='en_US'
                            , EmployeeNumber='AC100000'
                            , ProfileId = p.Id
                            , TimeZoneSidKey='Asia/Seoul'
                            , UserName='SysAdminTestuser@earth.org');
                                
        insert user;
        Employee__c emp = new Employee__c();
        emp.Emergency_Contact__c = '123';
        insert emp;
        
        string before = 'Testing base 64 encode';
        Blob beforeblob = Blob.valueOf(before);
        string paramvalue = EncodingUtil.base64Encode(beforeblob);

        ProfilePictureController.saveAttachment(emp.Id, 'test file name', paramvalue , 'image/png');
        ProfilePictureController.getProfilePicture(emp.Id);
        
        Test.stopTest();   
    }
}