PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>부서</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Departments</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/DeptPosition__c.field-meta.xml
<CustomField>
    <fullName>DeptPosition__c</fullName>
    <label>직책</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chairman</fullName>
                <label>총괄사장</label>
            </value>
            <value>
                <fullName>CEO</fullName>
                <label>대표이사</label>
            </value>
            <value>
                <fullName>부사장</fullName>
            </value>
            <value>
                <fullName>General Manager</fullName>
                <label>본부장</label>
            </value>
            <value>
                <fullName>Department Head</fullName>
                <label>부서장</label>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Pre-Sales</fullName>
            </value>
            <value>
                <fullName>Business Architecture</fullName>
                <label>Business Architect</label>
            </value>
            <value>
                <fullName>Platform Architecture</fullName>
                <label>Platform Architect</label>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Mgmt Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>직급</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>총괄사장</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>대표이사</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>센터장</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>감사</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>부사장</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>전무</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>상무</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>수석</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>이사</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>부장</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>책임</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>차장</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>과장</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>대리</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>선임</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>선임(수습)</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>사원</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>사원(수습)</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>인턴</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>사원 Object를 User Object간 Relationship 생성</inlineHelpText>
    <label>사용자 명</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/Holiday__c.object-meta.xml
<CustomObject>
    <label>Holiday</label>
    <nameField>
        <displayFormat>H-{0000}</displayFormat>
        <label>Holiday No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Holiday</relationshipLabel>
    <relationshipName>Holiday</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_reward_Total_Count__c.field-meta.xml
<CustomField>
    <fullName>Holiday_reward_Total_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>올해 발생한 대체휴가일수 + 전년도 대체휴가 잔여일수</inlineHelpText>
    <label>총 대체휴가일수</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/HolidayAction__c.object-meta.xml
<CustomObject>
    <description>HolidayAction__c</description>
    <label>휴가신청</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Departments</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>휴가신청</relationshipLabel>
    <relationshipName>HolidayActionV4Zc</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Days__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Days__c</fullName>
    <inlineHelpText>Women&apos;s Holiday 1.
Alternative Holiday 0.
Other Holidays from 1 to 5.</inlineHelpText>
    <label>Days</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_IsConfirm__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_IsConfirm__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Confirm?</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Type__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Annual Holiday</fullName>
                <label>연차</label>
            </value>
            <value>
                <fullName>Half-day Leave</fullName>
                <label>반차</label>
            </value>
            <value>
                <fullName>Reward Holiday</fullName>
                <label>대체휴가</label>
            </value>
            <value>
                <fullName>Reward Half-Holiday</fullName>
                <label>대체휴가(반차)</label>
            </value>
            <value>
                <fullName>Public Works</fullName>
                <label>공가(공무)</label>
            </value>
            <value>
                <fullName>Family Leave</fullName>
                <label>경조휴가</label>
            </value>
            <value>
                <fullName>Sick Leave</fullName>
                <label>병가(무급)</label>
            </value>
            <value>
                <fullName>Women Holiday</fullName>
                <label>생리휴가</label>
            </value>
            <value>
                <fullName>가족돌봄휴가</fullName>
            </value>
            <value>
                <fullName>출산휴가</fullName>
            </value>
            <value>
                <fullName>휴직</fullName>
            </value>
            <value>
                <fullName>육아휴직</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/Is_Cancled__c.field-meta.xml
<CustomField>
    <fullName>Is_Cancled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>개인 사정으로 인해 승인된 휴가를 취소</description>
    <label>Is Canceled?</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>프로젝트 PM</fullName>
            </value>
            <value>
                <fullName>프로젝트 팀원</fullName>
            </value>
            <value>
                <fullName>본사근무</fullName>
            </value>
            <value>
                <fullName>임원</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Project_HolidayAction</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/PerformProject__c.object-meta.xml
<CustomObject>
    <label>프로젝트 수행팀</label>
    <nameField>
        <displayFormat>PJ-{0000}</displayFormat>
        <label>Seq</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>프로젝트에 참여한 사원 이름</inlineHelpText>
    <label>사원 명</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>수행 프로젝트</relationshipLabel>
    <relationshipName>EmployeePerformPjt</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트 명</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>프로젝트 수행팀</relationshipLabel>
    <relationshipName>Project</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>프로젝트에 대한 기본정보를 관리하며, Deal Closing 이후 생성한다. 영업담당자가 계약 체결 후 기초 데이터를 작성하며, 프로젝트 진행 중에는 PM이 관리하고, 대금청구/지급 관련 정보는 회계에서 관리한다.</description>
    <label>프로젝트</label>
    <nameField>
        <label>프로젝트 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <label>사업부</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Departments</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/recordTypes/Project.recordType-meta.xml
<RecordType>
    <fullName>Project</fullName>
    <active>true</active>
    <description>프로젝트 사항 입력하는 Record Type</description>
    <label>프로젝트</label>
</RecordType>

PA_Education/TestMenifest/force-app/main/default/classes/HolidayActionUpdate_Test.cls
/**
 * @description       : HolidayActionUpdate.trigger에 대한 Test Class
 * @author            : cj.sohn@daeunextier.com
 * @group             : DaeuNextier
 * Modifications Log 
 * Ver   Date         Author                            Modification
 * 1.0   2021-01-20   cj.sohn@daeunextier.com           Initial Version
 * @.0   2023-12-22   kwanwoo.jeon@daeunextier.com      HolidayActionUpdate.trigger에서 HolidayAction_tr.apex로 이관 후 대체휴가 관련 테스트 추가
**/

@IsTest
private class HolidayActionUpdate_Test {
    @TestSetup
    static void setup() {
        List<User> listUser = new List<User>();
        for(Integer i = 0; i < 3; i++){
            User user = TestObjectCreator.objUser;
            if(i != 0){
                user = TestObjectCreator.objUser.clone();
                user.Id = null;
                user.Username = user.UserName + '.' + String.valueOf(i);
                user.LastName = user.LastName + String.valueOf(i);
                user.FirstName = user.FirstName + String.valueOf(i);
                user.Alias = user.Alias + String.valueOf(i);
                user.CommunityNickname = user.CommunityNickname + String.valueOf(i);
            }
            listUser.add(user);
            System.debug(user);
        }
        insert listUser;

        List<Employee__c> listEmployee = new List<Employee__c>();
        for(Integer i = 0; i < 3; i++){
            Employee__c employee = TestObjectCreator.objEmployee;
            if(i != 0){
                employee = TestObjectCreator.objEmployee.clone();
                employee.Id = null;
            }
            employee.User__c = listUser.get(i).Id;
            switch on i {
                when 0{
                    employee.Department__c = '사업본부';
                }
                when 1{
                    employee.Department__c = '사업1부';
                }
                when 2{
                    employee.Department__c = '사업2부';
                    employee.DeptPosition__c = 'Department Head';
                }
            }
            listEmployee.add(employee);
        }
        insert listEmployee;

        Holiday__c holiday = TestObjectCreator.objHoliday;
        holiday.Holiday_reward_Total_Count__c = 10;

        insert holiday;

        HolidayAction__c holidayAction = TestObjectCreator.objHolidayAction;
        holidayAction.HolidayAction_Days__c = 1;
        holidayAction.Position__c = '프로젝트 팀원';
        holidayAction.Department__c = '사업1부';
        holidayAction.HolidayAction_IsConfirm__c = false;
        insert holidayAction;

        Project__c project = TestObjectCreator.objProject;
        project.Business__c = '사업2부';
        insert project;

//        PerformProject__c performProject = TestObjectCreator.objPerformProject;
//        insert performProject;
    }
    
    @IsTest
    static void testAnnualHoliday() {
        HolidayAction__c holidayAction = [SELECT Id FROM HolidayAction__c LIMIT 1];
        Project__c project = [SELECT Id FROM Project__c LIMIT 1];
        Test.startTest();
        holidayAction.HolidayAction_IsConfirm__c = true;
        holidayAction.Project__c = project.Id;
        update holidayAction;

        holidayAction.Is_Cancled__c = true;
        update holidayAction;
        Test.stopTest();
    }

    @IsTest
    static void testMonthlyHoliday() {
        HolidayAction__c holidayAction = [SELECT Id FROM HolidayAction__c LIMIT 1];
        Project__c project = [SELECT Id FROM Project__c LIMIT 1];
        Test.startTest();
        holidayAction.HolidayAction_Type__c = 'Monthly Holiday';
        holidayAction.HolidayAction_IsConfirm__c = true;
        holidayAction.Project__c = project.Id;
        update holidayAction;

        holidayAction.Is_Cancled__c = true;
        update holidayAction;
        Test.stopTest();
    }

    @IsTest
    static void testHalfdayLeave() {
        HolidayAction__c holidayAction = [SELECT Id FROM HolidayAction__c LIMIT 1];
        Project__c project = [SELECT Id FROM Project__c LIMIT 1];
        Test.startTest();
        holidayAction.HolidayAction_Type__c = 'Half-day Leave';
        holidayAction.HolidayAction_IsConfirm__c = true;
        holidayAction.Project__c = project.Id;
        update holidayAction;

        holidayAction.Is_Cancled__c = true;
        update holidayAction;
        Test.stopTest();
    }

    @IsTest
    static void testWomenHoliday() {
        HolidayAction__c holidayAction = [SELECT Id FROM HolidayAction__c LIMIT 1];
        Project__c project = [SELECT Id FROM Project__c LIMIT 1];
        Test.startTest();
        holidayAction.HolidayAction_Type__c = 'Women Holiday';
        holidayAction.HolidayAction_IsConfirm__c = true;
        holidayAction.Project__c = project.Id;
        update holidayAction;

        holidayAction.Is_Cancled__c = true;
        update holidayAction;
        Test.stopTest();
    }

    @IsTest
    static void testPublicWorks() {
        HolidayAction__c holidayAction = [SELECT Id FROM HolidayAction__c LIMIT 1];
        Project__c project = [SELECT Id FROM Project__c LIMIT 1];
        Test.startTest();
        holidayAction.HolidayAction_Type__c = 'Public Works';
        holidayAction.HolidayAction_IsConfirm__c = true;
        holidayAction.Project__c = project.Id;
        update holidayAction;

        holidayAction.Is_Cancled__c = true;
        update holidayAction;
        Test.stopTest();
    }

    @IsTest
    static void testSickLeave() {
        HolidayAction__c holidayAction = [SELECT Id FROM HolidayAction__c LIMIT 1];
        Project__c project = [SELECT Id FROM Project__c LIMIT 1];
        Test.startTest();
        holidayAction.HolidayAction_Type__c = 'Sick Leave';
        holidayAction.HolidayAction_IsConfirm__c = true;
        holidayAction.Project__c = project.Id;
        update holidayAction;

        holidayAction.Is_Cancled__c = true;
        update holidayAction;
        Test.stopTest();
    }

    @IsTest
    static void testRewardHoliday() {
        HolidayAction__c holidayAction = [SELECT Id FROM HolidayAction__c LIMIT 1];
        Project__c project = [SELECT Id FROM Project__c LIMIT 1];
        Test.startTest();
        holidayAction.HolidayAction_Type__c = 'Reward Holiday';
        holidayAction.HolidayAction_IsConfirm__c = true;
        holidayAction.Project__c = project.Id;
        update holidayAction;

        holidayAction.Is_Cancled__c = true;
        update holidayAction;
        Test.stopTest();
    }
}