PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>직급</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>총괄사장</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>대표이사</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>센터장</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>감사</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>부사장</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>전무</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>상무</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>수석</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>이사</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>부장</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>책임</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>차장</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>과장</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>대리</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>선임</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>선임(수습)</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>사원</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>사원(수습)</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>인턴</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>프로젝트에 대한 기본정보를 관리하며, Deal Closing 이후 생성한다. 영업담당자가 계약 체결 후 기초 데이터를 작성하며, 프로젝트 진행 중에는 PM이 관리하고, 대금청구/지급 관련 정보는 회계에서 관리한다.</description>
    <label>프로젝트</label>
    <nameField>
        <label>프로젝트 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

Test/force-app/main/default/classes/ProjectMember_tr.cls
public with sharing class ProjectMember_tr extends TriggerHandler {
   
    private List<ProjectMember__c> listProjectMemNew{get;set;}
    


    public ProjectMember_tr(){
       
        listProjectMemNew=(List<ProjectMember__c>) Trigger.new;
    }
    public override void beforeInsert(){
        beforeNameInsert();
        
    }

    public override void afterInsert(){
        
    }

    public override void beforeUpdate(){
        beforeNameInsert();
    }

    public override void afterUpdate(){
    }

    public override void beforeDelete(){
       
    }

    

    public void beforeNameInsert(){
        Set<Id> setProjectId = new Set<Id>();
        Set<Id> setEmployeeId = new Set<Id>();
    
        for(ProjectMember__c pm : listProjectMemNew) {
             setProjectId.add(pm.Project__c);
             setEmployeeId.add(pm.Employee__c);
        }
        
        Map<Id, Project__c> mapProject = new Map<Id, Project__c>([
            SELECT Name
            FROM Project__c
            WHERE Id IN :setProjectId
        ]);
        
        Map<Id, Employee__c> mapEmployee = new Map<Id, Employee__c>([
            SELECT EmployeeName__c
            FROM Employee__c
            WHERE Id IN :setEmployeeId
        ]);
        
        for(ProjectMember__c pm : listProjectMemNew) {
            String projectName = mapProject.get(pm.Project__c).Name;
            String employeeName = mapEmployee.get(pm.Employee__c).EmployeeName__c;
            String position = pm.Position__c ;
            
            pm.Name = projectName + '_' + position + '_' + employeeName;
        }

    }



}