PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/EmployeeNo__c.field-meta.xml
<CustomField>
    <fullName>EmployeeNo__c</fullName>
    <label>사번</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/MainRole__c.field-meta.xml
<CustomField>
    <fullName>MainRole__c</fullName>
    <label>직무</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Management</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>직급</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>총괄사장</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>대표이사</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>센터장</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>감사</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>부사장</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>전무</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>상무</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>수석</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>이사</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>부장</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>책임</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>차장</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>과장</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>대리</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>선임</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>선임(수습)</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>사원</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>사원(수습)</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>인턴</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(ISBLANK( ExitDate__c) ||  ExitDate__c    &gt;    TODAY()  , TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>재직여부</label>
    <type>Checkbox</type>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>사원 Object를 User Object간 Relationship 생성</inlineHelpText>
    <label>사용자 명</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/EmployeeProfileExportController.cls
/************************************************************************************
 * File Name   : EmployeeProfileExportController.cls
 * Author      : Soyoung.Jung 
 * Date        : 2019.01.09
 * Tester      : EmployeeProfileExportController_test.cls
 * Description : 사원 프로필 문서 생성 및 로컬 다운로드 컴포넌트 컨트롤러
 * Modification Log
 * ===================================================================================
 * Ver      Date            Author              Modification
 * ===================================================================================
   1.0      2019.01.09      Soyoung.Jung        Create
*************************************************************************************/

public without sharing class EmployeeProfileExportController {

	/************************************************************************************
    *   초기 데이터 셋팅
    * 	사원 오브젝트의 레코드 전체 갯수, 하위 오브젝트 리스트(픽리스트)
    *************************************************************************************/
	@AuraEnabled
	public static Map<String, Object> getInitData() {
		// 사원 오브젝트의 레코드 전체 갯수
		String sQuery = '';

		sQuery += 'SELECT 	COUNT(Id) iTotalCnt';
		sQuery += '  FROM 	Employee__c';

		if(!hasPermission) {
			sQuery += ' WHERE User__c = :idCurrentUser';
		}

		AggregateResult result = Database.query(sQuery);

        Integer iTotalCnt = (Integer) result.get('iTotalCnt');

        // 사원 오브젝트의 하위 연관 오브젝트 리스트
        List<Map<String, String>> listChildObject = new List<Map<String, String>>();

		Schema.DescribeSObjectResult describeSObj = Employee__c.SObjectType.getDescribe();
		for(Schema.ChildRelationship child : describeSObj.getChildRelationships()) {
			if(child.getRelationshipName() != null) {
				String sValue = String.valueOf(child.getRelationshipName());                          
				String sLabel = String.valueOf(child.getChildSObject());

				Schema.DescribeSObjectResult describe = Schema.getGlobalDescribe().get(sLabel).getDescribe();

				if(describe.isCustom()) {
					sLabel = String.valueOf(describe.getLabel());
					if(sLabel == '증명서'){continue;}
					listChildObject.add(new Map<String, String>{'value' => sValue, 'label' => sLabel});	
				}
			}
		}

		// 결과 맵 생성 및 리턴
		Map<String, Object> mapReturnValue = new Map<String, Object>{
			'iTotalCnt' 		=> iTotalCnt,
			'listChildObject' 	=> listChildObject
		};

		return mapReturnValue;
	}

	/************************************************************************************
    * 	사원 오브젝트 리스트
    *************************************************************************************/
    @AuraEnabled
    public static List<Employee__c> getListEmployee(Integer limits, Integer offsets) {
    	System.debug('limits : ' + limits + ', offsets : ' + offsets);

        limits  = Integer.valueOf(limits);
        offsets = Integer.valueOf(offsets);

        String sQuery = '';

        sQuery += 'SELECT 	Id, Name, MainRole__c, toLabel(Position__c) Position__c, EmployeeNo__c, User__c';
        sQuery += '  FROM 	Employee__c';
        sQuery += ' WHERE 	Status__c = true';

        if(!hasPermission) {
        	sQuery += ' AND User__c = :idCurrentUser';
        }

        sQuery += ' ORDER BY MainRole__c, Position__c, EmployeeNo__c';
        sQuery += ' LIMIT ' + limits;
        sQuery += ' OFFSET ' + offsets;

        List<Employee__c> listEmployee = Database.query(sQuery);

        System.debug('listEmployee : ' + listEmployee);

        return listEmployee;
    }

    /************************************************************************************
    * 	사원 리스트 권한 체크
    * 	접속한 유저가 HRGroup에 속한 경우 사원 목록 전체를 출력하고, 그렇지 않은 경우 본인만 출력
    *************************************************************************************/
    private static Boolean hasPermission {
    	get {
    		if(hasPermission == null) {
    			hasPermission = setIdHRGroupMember.contains(idCurrentUser);
    		}

    		return hasPermission;
    	}
    	set;
    }

    private static Set<Id> setIdHRGroupMember {
    	get {
    		if(setIdHRGroupMember == null) {
    			List<GroupMember> listGroupMember = [SELECT Id, UserOrGroupId
    												 FROM 	GroupMember
    												 WHERE 	Group.DeveloperName = 'HRGroup'];

				setIdHRGroupMember = new Set<Id>();    			
    			for(GroupMember objGroupMember : listGroupMember) {
    				setIdHRGroupMember.add(objGroupMember.UserOrGroupId);
    			}
    		}

    		return setIdHRGroupMember;
    	}
    	set;
    }

    private static Id idCurrentUser {
    	get {
    		if(idCurrentUser == null) {
    			idCurrentUser = UserInfo.getUserId();
    		}

    		return idCurrentUser;
    	}
    	set;
    }

}