PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>사원 Object를 User Object간 Relationship 생성</inlineHelpText>
    <label>사용자 명</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/Holiday__c.object-meta.xml
<CustomObject>
    <label>Holiday</label>
    <nameField>
        <displayFormat>H-{0000}</displayFormat>
        <label>Holiday No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Holiday</relationshipLabel>
    <relationshipName>Holiday</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_GivenHolidays__c.field-meta.xml
<CustomField>
    <fullName>Holiday_GivenHolidays__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>추가적으로 부여된 연월차일수</inlineHelpText>
    <label>추가 부여 일수</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_LastActivity__c.field-meta.xml
<CustomField>
    <fullName>Holiday_LastActivity__c</fullName>
    <label>최종 사용 내역</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_NoticeLevel__c.field-meta.xml
<CustomField>
    <fullName>Holiday_NoticeLevel__c</fullName>
    <label>공지 단계</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Need</fullName>
                <default>true</default>
                <label>Not Need</label>
            </value>
            <value>
                <fullName>1st Notice</fullName>
            </value>
            <value>
                <fullName>2nd Notice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_User__c.field-meta.xml
<CustomField>
    <fullName>Holiday_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>임직원</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Holiday</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/PeriodStartDate__c.field-meta.xml
<CustomField>
    <fullName>PeriodStartDate__c</fullName>
    <description>연차 발생당시 근속연수를 구하기 위한 연차 시작일</description>
    <label>당해연차시작일</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/HolidayTrigger_Test.cls
/**
 * Created by attar on 2020-11-23.
 */

@IsTest
private class HolidayTrigger_Test {

    @TestSetup
    static void setData() {
        User objUser = TestObjectCreator.objUser;
        insert objUser;

        Employee__c objEmployee = TestObjectCreator.objEmployee;
        objEmployee.User__c = objUser.Id;
        insert objEmployee;

        Holiday__c objHoliday = TestObjectCreator.objHoliday;
        objHoliday.Holiday_User__c = objUser.Id;
        insert objHoliday;
    }
    @IsTest
    static void test() {
        Test.startTest();

        Holiday__c objHoliday = [SELECT Id FROM Holiday__c LIMIT 1];
        objHoliday.Holiday_GivenHolidays__c = 5;
        objHoliday.Holiday_NoticeLevel__c = '1st Notice';
        objHoliday.PeriodStartDate__c = Date.today();
        objHoliday.Holiday_LastActivity__c = 'test';
        update objHoliday;

        Test.stopTest();
    }
}