PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>부서</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Departments</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/DeptPosition__c.field-meta.xml
<CustomField>
    <fullName>DeptPosition__c</fullName>
    <label>직책</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chairman</fullName>
                <label>총괄사장</label>
            </value>
            <value>
                <fullName>CEO</fullName>
                <label>대표이사</label>
            </value>
            <value>
                <fullName>부사장</fullName>
            </value>
            <value>
                <fullName>General Manager</fullName>
                <label>본부장</label>
            </value>
            <value>
                <fullName>Department Head</fullName>
                <label>부서장</label>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Pre-Sales</fullName>
            </value>
            <value>
                <fullName>Business Architecture</fullName>
                <label>Business Architect</label>
            </value>
            <value>
                <fullName>Platform Architecture</fullName>
                <label>Platform Architect</label>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Mgmt Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>직급</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>총괄사장</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>대표이사</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>센터장</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>감사</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>부사장</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>전무</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>상무</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>수석</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>이사</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>부장</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>책임</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>차장</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>과장</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>대리</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>선임</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>선임(수습)</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>사원</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>사원(수습)</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>인턴</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>사원 Object를 User Object간 Relationship 생성</inlineHelpText>
    <label>사용자 명</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense Application</label>
    <nameField>
        <displayFormat>EP-{YYYYMM}-{000000}</displayFormat>
        <label>경비신청 코드</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/Approver1__c.field-meta.xml
<CustomField>
    <fullName>Approver1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ExpenseApprover1</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/Approver2__c.field-meta.xml
<CustomField>
    <fullName>Approver2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ExpenseApprover2</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/Approver3__c.field-meta.xml
<CustomField>
    <fullName>Approver3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 3</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ExpenseApprover3</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/Approver4__c.field-meta.xml
<CustomField>
    <fullName>Approver4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 4</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ExpenseApprover4</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/BudgetType__c.field-meta.xml
<CustomField>
    <fullName>BudgetType__c</fullName>
    <label>사용목적</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BudgetType</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Expense Application</relationshipLabel>
    <relationshipName>ExpenseApplication</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/PerformProject__c.object-meta.xml
<CustomObject>
    <label>프로젝트 수행팀</label>
    <nameField>
        <displayFormat>PJ-{0000}</displayFormat>
        <label>Seq</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>프로젝트에 참여한 사원 이름</inlineHelpText>
    <label>사원 명</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>수행 프로젝트</relationshipLabel>
    <relationshipName>EmployeePerformPjt</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트 명</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>프로젝트 수행팀</relationshipLabel>
    <relationshipName>Project</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PriorExpenseApplication__c/PriorExpenseApplication__c.object-meta.xml
<CustomObject>
    <label>경비사전승인</label>
    <nameField>
        <label>경비사전승인 이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/PriorExpenseApplication__c/fields/Approver1__c.field-meta.xml
<CustomField>
    <fullName>Approver1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ExpensePreApprover1</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PriorExpenseApplication__c/fields/Approver2__c.field-meta.xml
<CustomField>
    <fullName>Approver2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ExpensePreApprover2</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PriorExpenseApplication__c/fields/Approver3__c.field-meta.xml
<CustomField>
    <fullName>Approver3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 3</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ExpensePreApprover3</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PriorExpenseApplication__c/fields/Approver4__c.field-meta.xml
<CustomField>
    <fullName>Approver4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver 4</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ExpensePreApprover4</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PriorExpenseApplication__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>경비사전승인</relationshipLabel>
    <relationshipName>ExpenseProject</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>프로젝트에 대한 기본정보를 관리하며, Deal Closing 이후 생성한다. 영업담당자가 계약 체결 후 기초 데이터를 작성하며, 프로젝트 진행 중에는 PM이 관리하고, 대금청구/지급 관련 정보는 회계에서 관리한다.</description>
    <label>프로젝트</label>
    <nameField>
        <label>프로젝트 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <label>사업부</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Departments</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/fields/PM__c.field-meta.xml
<CustomField>
    <fullName>PM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트 관리자</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PM</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/ApprovalLineCreateController.cls
public without sharing class ApprovalLineCreateController {

	// sharing TEST SJ 0726
	public static String accessLevel = 'Read';
	public static String rowCause    = 'Manual';

	@AuraEnabled
	public static String doSave(String insertValue, String fieldName, User objUser){
		System.debug('insertValue : ' + insertValue);
		System.debug('fieldName : ' + fieldName);
		System.debug('objUser : ' + objUser);
        String returnValue = '';
        try {
        	fieldName = fieldName + '__c';
        	objUser.put( fieldName , insertValue);

        	update objUser;
            returnValue = 'success/성공적으로 저장되었습니다./' + objUser.Id ;
        } catch(Exception e) {
            returnValue = 'error/' + e.getMessage();
        }
        return returnValue;
	}

	@AuraEnabled
	public static String doSubmit(String sObjectName, String sComments, String sHistoryRecordId, List<User> objListUser){
		System.debug('sObjectName : '+ sObjectName + ' / sComments : '+ sComments +' / sHistoryRecordId : '+ sHistoryRecordId );

		//user이름 들어있는 리스트 listApprovalLine 으로 칭함.
		String returnValue;
		try{
			List<String> userList = new List<String>();
			for(Integer i = 0; i < objListUser.size(); i++){
				userList.add(objListUser[i].Id);
			}

			System.debug(userList);

			Integer iUserCnt = userList.size();
			String sQuery   = 'SELECT Id FROM '+ sObjectName +' WHERE Id = \''+ sHistoryRecordId + '\''   ;
			SObject obj = Database.query(sQuery);

			switch on iUserCnt {
				when 1 { obj.put('Approver1__c', userList[0]); obj.put('Approver2__c', ''); 	obj.put('Approver3__c', ''); 	obj.put('Approver4__c', '');}
				when 2 { obj.put('Approver1__c', userList[0]); obj.put('Approver2__c', userList[1]); 	obj.put('Approver3__c', ''); 	obj.put('Approver4__c', '');}
				when 3 { obj.put('Approver1__c', userList[0]); obj.put('Approver2__c', userList[1]); 	obj.put('Approver3__c', userList[2]); 	obj.put('Approver4__c', '');}
				when 4 { obj.put('Approver1__c', userList[0]); obj.put('Approver2__c', userList[1]); 	obj.put('Approver3__c', userList[2]); 	obj.put('Approver4__c', userList[3]);}
			}
			update obj;

			if(sObjectName == 'Expense__c'){
				List<Expense__Share> expenseShares = new List<Expense__Share>();

				for(User u : objListUser) {
					Expense__Share expenseSh = new Expense__Share();
					expenseSh.ParentId       = sHistoryRecordId;
					expenseSh.AccessLevel 	 = accessLevel;
					expenseSh.RowCause	     = rowCause;
					if(u.Id ==  UserInfo.getUserId()) continue;
					expenseSh.UserOrGroupId  = u.Id;

					expenseShares.add(expenseSh);
				}

				if (!expenseShares.isEmpty()) {
					insert expenseShares;
				}
			}else if(sObjectName == 'PriorExpenseApplication__c'){
				List<PriorExpenseApplication__Share> PriorExpenseApplicationShares = new List<PriorExpenseApplication__Share>();

				for(User u : objListUser) {
					PriorExpenseApplication__Share expenseSh = new PriorExpenseApplication__Share();
					expenseSh.ParentId       = sHistoryRecordId;
					expenseSh.AccessLevel 	 = accessLevel;
					expenseSh.RowCause	     = rowCause;
					if(u.Id ==  UserInfo.getUserId()) continue;
					expenseSh.UserOrGroupId  = u.Id;

					PriorExpenseApplicationShares.add(expenseSh);
				}
				if (!PriorExpenseApplicationShares.isEmpty()) {
					insert PriorExpenseApplicationShares;
				}
			}


			Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
	        req1.setComments(sComments);
	        req1.setObjectId(sHistoryRecordId);
	        Approval.ProcessResult result = Approval.process(req1);

			returnValue = 'success/성공적으로 저장되었습니다./' + sHistoryRecordId ;

		} catch (Exception e) {
			returnValue = 'error/' + e.getMessage() + '클래스에러' +sHistoryRecordId;
		}

		return returnValue;
	}

	//2024.11.14 kc
	@AuraEnabled
	public static Map<String, Object> checkProject(String recordId){	//sObjectName가 expense__c 이고 BudgetType__c이 프로젝트 일 때 편의를 위한 approval line default 값 생성

		List<Expense__c> listExp = [
				SELECT 	Id, BudgetType__c, Project__c, Project__r.PM__r.Id, Project__r.PM__r.Name, Project__r.Business__c
				FROM 	Expense__c
				WHERE 	Id = :recordId
				LIMIT 	1
		];

		if (listExp.size() != 1 || listExp[0].BudgetType__c != '프로젝트') {
			System.debug('[Debug] 프로젝트 없음');
			return null;
		}

		List<User> listMd = [
				SELECT 	Id, Name
				FROM 	User
				WHERE 	Name = '경영지원부'
				LIMIT 	1
		];
		if(listMd.size() != 1){
			System.debug('[Debug] 경영지원부 없음');
			return null;
		}
		
		List<Employee__c> listRp = [
				SELECT 	Id, Name, User__r.Id, User__r.Name
				FROM 	Employee__c
				WHERE 	Position__c = '1'
				LIMIT 	1
		];
		if(listRp.size() != 1){
			System.debug('[Debug] 대표이사 없음');
			return null;
		}

		List<Employee__c> listDh = [
				SELECT 	Id, Name, Department__c, User__r.Id, User__r.Name
				FROM 	Employee__c
				WHERE 	Department__c = :listExp[0].Project__r.Business__c
				AND 	DeptPosition__c = 'Department Head'
				LIMIT 	1
		];

		if(listDh.size() != 1){
			System.debug('[Debug] 부서장 없음');
			return null;
		}

		if(listExp[0].Project__r.PM__c == null){
			System.debug('[Debug] PM 없음');
			return null;
		}

		List<User> listMe = [
				SELECT	Id, Name
				FROM	User
				WHERE	Id =: UserInfo.getUserId()
				LIMIT	1
		];

		Map<String, Object> returnVal = new Map<String, Object>{
				'PmId'		=> listExp[0].Project__r.PM__r.Id,		//프로젝트 메니저
				'PmName'	=> listExp[0].Project__r.PM__r.Name,
				'MdId'		=> listMd[0].Id,						//영업지원부
				'MdName'	=> listMd[0].Name,
				'DhId'		=> listDh[0].User__r.Id,				//부서장
				'DhName'	=> listDh[0].User__r.Name,
				'MyId'		=> listMe[0].Id,						//나 자신
				'MyName'	=> listMe[0].Name,
				'RpId'		=> listRp[0].User__r.Id,				//대표이사
				'RpName'	=> listRp[0].User__r.Name
		};

		return returnVal;

	}


}