PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>부서</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Departments</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/DeptPosition__c.field-meta.xml
<CustomField>
    <fullName>DeptPosition__c</fullName>
    <label>직책</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chairman</fullName>
                <label>총괄사장</label>
            </value>
            <value>
                <fullName>CEO</fullName>
                <label>대표이사</label>
            </value>
            <value>
                <fullName>부사장</fullName>
            </value>
            <value>
                <fullName>General Manager</fullName>
                <label>본부장</label>
            </value>
            <value>
                <fullName>Department Head</fullName>
                <label>부서장</label>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Pre-Sales</fullName>
            </value>
            <value>
                <fullName>Business Architecture</fullName>
                <label>Business Architect</label>
            </value>
            <value>
                <fullName>Platform Architecture</fullName>
                <label>Platform Architect</label>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Mgmt Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>직급</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>총괄사장</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>대표이사</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>센터장</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>감사</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>부사장</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>전무</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>상무</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>수석</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>이사</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>부장</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>책임</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>차장</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>과장</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>대리</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>선임</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>선임(수습)</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>사원</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>사원(수습)</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>인턴</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense Application</label>
    <nameField>
        <displayFormat>EP-{YYYYMM}-{000000}</displayFormat>
        <label>경비신청 코드</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/BudgetType__c.field-meta.xml
<CustomField>
    <fullName>BudgetType__c</fullName>
    <label>사용목적</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BudgetType</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Expense__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Expense Application</relationshipLabel>
    <relationshipName>ExpenseApplication</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PriorExpenseApplication__c/PriorExpenseApplication__c.object-meta.xml
<CustomObject>
    <label>경비사전승인</label>
    <nameField>
        <label>경비사전승인 이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/PriorExpenseApplication__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>경비사전승인</relationshipLabel>
    <relationshipName>ExpenseProject</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>프로젝트에 대한 기본정보를 관리하며, Deal Closing 이후 생성한다. 영업담당자가 계약 체결 후 기초 데이터를 작성하며, 프로젝트 진행 중에는 PM이 관리하고, 대금청구/지급 관련 정보는 회계에서 관리한다.</description>
    <label>프로젝트</label>
    <nameField>
        <label>프로젝트 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <label>사업부</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Departments</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/fields/PM__c.field-meta.xml
<CustomField>
    <fullName>PM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트 관리자</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PM</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/ApprovalLineCreateController_Test.cls
@isTest
private class ApprovalLineCreateController_Test {

    @isTest
    static void doTest() {
        Test.startTest();
        
        User user1 = TestObjectCreator.objUser;
        User user2 = user1.clone(false);
        User user3 = user1.clone(false);
        User user4 = user1.clone(false);
        User user5 = user1.clone(false);
        User user6 = user1.clone(false);
        
        user2.Email               = 'atest@test.com';
        user2.Username            = 'atestclass@test.com';
        user2.Alias               = 'auser';
        user2.CommunityNickname   = 'auser';

        user3.Email               = 'aatest@test.com';
        user3.Username            = 'aatestclass@test.com';
        user3.CommunityNickname   = 'ausedr';

        user4.Email               = 'aatest@test.com';
        user4.Username            = 'aatesgtclass@test.com';
        user4.CommunityNickname   = 'ausera';

        user5.FirstName           = '';
        user5.LastName            = '경영지원부';
        user5.Username            = 'aatesgtclassss331@test.com';
        user5.CommunityNickname   = 'auserae';

//        user5.FirstName           = 'RpName';
//        user5.Username            = 'aatesgtclasrpss331@test.com';
//        user5.CommunityNickname   = 'auserrpaae';


        insert user1;
        insert user2;
        insert user3;
        insert user4;


        // user1.ApprovalLine1__c = 'ApprovalLine1__c/ApprovalLine1__c/'+ user2.Id;
        user1.ApprovalLine2__c = 'ApprovalLine2__c/ApprovalLine2__c/'+ user2.Id;
        user1.ApprovalLine3__c = 'ApprovalLine3__c/ApprovalLine3__c/'+ user2.Id +'/'+ user3.Id;
        user1.ApprovalLine4__c = 'ApprovalLine4__c/ApprovalLine4__c/'+ user2.Id;
        update user1;

        String insertValue = 'ApprovalLine1__c/ApprovalLine1__c/'+ user2.Id;
        String fieldName   = 'ApprovalLine1';

        List<User> objListUser = new List<User>();
        objListUser.add(user1);
        objListUser.add(user2);
        objListUser.add(user3);
        objListUser.add(user4);

        //Project__c
        Project__c project1     = TestObjectCreator.objProject;
        project1.Business__c    = '사업1부';
        project1.PM__c          = user4.Id;

        insert project1;

        //Expense__c
        Expense__c objExpense       = TestObjectCreator.objExpense;
        Expense__c objExpense2      = objExpense.clone(false);
        objExpense2.BudgetType__c   = '프로젝트';
        objExpense2.Project__c      = project1.Id;

        insert objExpense;
        insert objExpense2;

        ApprovalLineCreateController.doSave(insertValue, fieldName, user1);
        ApprovalLineCreateController.doSave('error', 'error', user1);
        ApprovalLineCreateController.doSubmit('Expense__c', '코멘트입니다.', objExpense.Id, objListUser);
        ApprovalLineCreateController.doSubmit('Expense__c', '코멘트입니다.', '213456435', objListUser);

        //PriorExpenseApplication__c
        PriorExpenseApplication__c objPriorExpense = TestObjectCreator.objPriorExpense;
        insert objPriorExpense;

        ApprovalLineCreateController.doSave(insertValue, fieldName, user1);
        ApprovalLineCreateController.doSave('error', 'error', user1);
        ApprovalLineCreateController.doSubmit('PriorExpenseApplication__c', '코멘트입니다.', objPriorExpense.Id, objListUser);
        ApprovalLineCreateController.doSubmit('PriorExpenseApplication__c', '코멘트입니다.', '213456435', objListUser);

        ApprovalLineCreateController.checkProject(objExpense.Id);
        ApprovalLineCreateController.checkProject(objExpense2.Id);
        insert user5;
        Employee__c emp = TestObjectCreator.objEmployee;
        emp.DeptPosition__c = 'Department Head';
        emp.Department__c   = '사업1부';
        emp.Position__c     = '1';
        insert emp;

        ApprovalLineCreateController.checkProject(objExpense2.Id);


        Test.stopTest();
    }
}