PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>부서</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Departments</valueSetName>
    </valueSet>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>사원 Object를 User Object간 Relationship 생성</inlineHelpText>
    <label>사용자 명</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/Holiday__c.object-meta.xml
<CustomObject>
    <label>Holiday</label>
    <nameField>
        <displayFormat>H-{0000}</displayFormat>
        <label>Holiday No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Holiday</relationshipLabel>
    <relationshipName>Holiday</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_Calculated__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Calculated__c</fullName>
    <description>대유넥스티어 사내 규칙에 맞는 연차여부 필드 수정으로 인한 예시 변경(수정일: 2021-12-31, 수정자: cj.sohn@daeunextier.com)
* 연차여부 수식 수정:
입사기준일인 경우, 입사일 + 365일
연차기준일(2020. 1. 1)인 경우, 입사일 다음년도 (연차 기준일)월 (연차 기준일)일 - 1

필드 설명
연차여부가 TRUE일 때, 15일 + 추가연차일수
연차여부가 FALSE일 때, 12 - (입사월 + 1)
ex)  오늘 2022년 3월 17일
       사원A: 입사일 2020-03-17 → 연차적용시작일(2020-12-31) → 연차여부 = TRUE → 15 + 0 개
       사원B: 입사일 2021-12-07 → 연차적용시작일(2021-12-31) → 연차여부 = TRUE → 15 + 0 개
       사원C: 입사일 2022-01-01 → 연차적용시작일(2022-12-31) → 연차여부 = FALSE → 12 - 1 = 11개
       사원D: 입사일 2022-01-04 → 연차적용시작일(2022-12-31) → 연차여부 = FALSE → 12 - (1 + 1) = 10개

휴가 연차일수 부여 개편으로 인한 수정(필드 수식 수정일: 2021-01-12, 필드 수정자: cj.sohn@daeunextier.com)
연차여부 수식 수정 이전 예시:
ex)  오늘 2021년 2월 4일
       사원A: 입사일 2020-12-07 → 연차적용시작일(2021-01-01) → 연차여부 = TRUE → 15 + 0 개
       사원B: 입사일 2021-01-01 → 연차적용시작일(2022-01-01) → 연차여부 = FALSE → 12 - 1 = 11개
       사원C: 입사일 2021-01-04 → 연차적용시작일(2022-01-01) → 연차여부 = FALSE → 12 - (1 + 1) = 10개</description>
    <formula>IF(
	Holiday_IsAnnualleave__c,
	15 + MIN(Holiday_Additionaldays__c , 10 ),
        IF(
                DAY(Holiday_JoinDate__c) = 1,
                IF(
	        	12 - (MONTH(Holiday_JoinDate__c) + 1) &lt; 0, 
	        	1,
	        	12 - MONTH(Holiday_JoinDate__c)
        	),
               	IF(
	        	12 - (MONTH(Holiday_JoinDate__c) + 1) &lt; 0, 
	        	0,
	        	12 - (MONTH(Holiday_JoinDate__c) + 1)
        	)
        )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>연차일수</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_GivenHolidays__c.field-meta.xml
<CustomField>
    <fullName>Holiday_GivenHolidays__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>추가적으로 부여된 연월차일수</inlineHelpText>
    <label>추가 부여 일수</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_IsAnnualleave__c.field-meta.xml
<CustomField>
    <fullName>Holiday_IsAnnualleave__c</fullName>
    <formula>Holiday_StartDate__c &lt;=  TODAY()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>연차여부</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_JoinDate__c.field-meta.xml
<CustomField>
    <fullName>Holiday_JoinDate__c</fullName>
    <label>입사일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_PeriodEnd__c.field-meta.xml
<CustomField>
    <fullName>Holiday_PeriodEnd__c</fullName>
    <description>수식 필드에 대한 상세설명 작성(필드 상세설명 수정일: 2021-12-23, 수정자: cj.sohn@daeunextier.com)
1. 입사일 기준여부가 TRUE일 때,
1-1) 금연도 입사월일이 오늘보다 작을 때, 금연도 입사월일 - 1 + 365
1-2) 금연도 입사월일이 오늘보다 크거나 같을 때, 금연도 입사월일 -1 + 0

ex) 오늘: 2021년 12월 23일
사원A: 입사일 2019-12-15 →  금연도 입사월일 (2021-12-15) → 연차만료일: 2022-12-15
사원B: 입사일 2020-12-28 → 금연도 입사월일 (2021-12-28) → 연차만료일: 2021-12-28
사원C: 입사일 2021-12-23 →  금연도 입사월일 (2021-12-23) → 연차만료일: 2022-12-22

2. 입사일 기준여부가 FALSE일 때,
2-1) 금연도 말일이 오늘보다 클 때, 전연도 말일 + 365
2-2) 금연도 말일이 오늘보다 작거나 같을 때, 전연도 말일 + 0 (가능성 0%)

ex) 오늘: 2021년 2월 4일, 금연도 말일: 2021년 12월 31일 → 연차만료일: 2021년 12월 31일

* 참고사항
Custom Setting(HolidaySetting__c)의 필드 및 값 정리 (2021-12-23 기준)
- 연차기준일(HoldayRuleDate__c): 2000. 1. 1
- 갱신일 이전 일수 차감여부(IsCeil__c): true
- 입사일 기준여부(JoinDateRule__c): false</description>
    <formula>IF(
    $Setup.HolidaySetting__c.JoinDateRule__c,
    DATE( YEAR(TODAY()), MONTH(Holiday_JoinDate__c), DAY(Holiday_JoinDate__c) ) - 1 +
    IF(
        DATE( YEAR(TODAY()), MONTH(Holiday_JoinDate__c), DAY(Holiday_JoinDate__c) ) &lt; TODAY(),
        365,
        0
    ),
    DATE( YEAR(TODAY()), MONTH($Setup.HolidaySetting__c.HoldayRuleDate__c ), DAY($Setup.HolidaySetting__c.HoldayRuleDate__c) ) - 1 +
    IF(
        DATE( YEAR(TODAY()), MONTH($Setup.HolidaySetting__c.HoldayRuleDate__c), DAY($Setup.HolidaySetting__c.HoldayRuleDate__c) ) &lt; TODAY(),
        365,
        0
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>연차만료일</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_Remain__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Remain__c</fullName>
    <description>4월1일 이전인 경우, 잔여일수=연차일수-사용일수+전년도 연차 잔여일수
3월31일 이후인 경우, 잔여일수=연차일수-사용일수

22.03.31
임시로 기준일을 12월 31일로 변경
변경전: TODAY() &lt;  DATE(YEAR(TODAY()), 4, 1)
변경후: TODAY() &lt;=  DATE(YEAR(TODAY()), 12, 31)</description>
    <formula>IF(
    TODAY() &lt;  DATE(YEAR(TODAY()), 4, 1),
    NULLVALUE( Holiday_Calculated__c , 0) -  NULLVALUE(Holiday_UseDays__c  , 0) +  Holiday_GivenHolidays__c + RemainOfLastYear__c ,
    NULLVALUE( Holiday_Calculated__c , 0) -  NULLVALUE(Holiday_UseDays__c  , 0) +  Holiday_GivenHolidays__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>전년도 잔여연차 사용을 임시로 올해 12월 31일까지 사용 가능하도록 변경되었습니다.</inlineHelpText>
    <label>잔여일수</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_UseDays__c.field-meta.xml
<CustomField>
    <fullName>Holiday_UseDays__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>올해 연월차 사용일수</inlineHelpText>
    <label>연월차 사용일수</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_User__c.field-meta.xml
<CustomField>
    <fullName>Holiday_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>임직원</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Holiday</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/HolidayAction__c.object-meta.xml
<CustomObject>
    <description>HolidayAction__c</description>
    <label>휴가신청</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Departments</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>휴가신청</relationshipLabel>
    <relationshipName>HolidayActionV4Zc</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Date1__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Date1__c</fullName>
    <label>Date1</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Date2__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Date2__c</fullName>
    <label>Date2</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Date3__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Date3__c</fullName>
    <label>Date3</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Date4__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Date4__c</fullName>
    <label>Date4</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Date5__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Date5__c</fullName>
    <label>Date5</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Days__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Days__c</fullName>
    <inlineHelpText>Women&apos;s Holiday 1.
Alternative Holiday 0.
Other Holidays from 1 to 5.</inlineHelpText>
    <label>Days</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_HalfdayTime__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_HalfdayTime__c</fullName>
    <label>Half-day leave Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Type__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Annual Holiday</fullName>
                <label>연차</label>
            </value>
            <value>
                <fullName>Half-day Leave</fullName>
                <label>반차</label>
            </value>
            <value>
                <fullName>Reward Holiday</fullName>
                <label>대체휴가</label>
            </value>
            <value>
                <fullName>Reward Half-Holiday</fullName>
                <label>대체휴가(반차)</label>
            </value>
            <value>
                <fullName>Public Works</fullName>
                <label>공가(공무)</label>
            </value>
            <value>
                <fullName>Family Leave</fullName>
                <label>경조휴가</label>
            </value>
            <value>
                <fullName>Sick Leave</fullName>
                <label>병가(무급)</label>
            </value>
            <value>
                <fullName>Women Holiday</fullName>
                <label>생리휴가</label>
            </value>
            <value>
                <fullName>가족돌봄휴가</fullName>
            </value>
            <value>
                <fullName>출산휴가</fullName>
            </value>
            <value>
                <fullName>휴직</fullName>
            </value>
            <value>
                <fullName>육아휴직</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/PerformProject__c.object-meta.xml
<CustomObject>
    <label>프로젝트 수행팀</label>
    <nameField>
        <displayFormat>PJ-{0000}</displayFormat>
        <label>Seq</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>프로젝트에 참여한 사원 이름</inlineHelpText>
    <label>사원 명</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>수행 프로젝트</relationshipLabel>
    <relationshipName>EmployeePerformPjt</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/HolidayUtil_Test.cls
/**
 * @description       : HolidayUtil Class에 대한 Test Class
 * @author            : cj.sohn@daeunextier.com
 * @group             : DaeuNextier
 * Modifications Log 
 * Ver   Date         Author                    Modification
 * 1.0   2021-01-20   cj.sohn@daeunextier.com   Initial Version
**/
@IsTest
public with sharing class HolidayUtil_Test {
    @IsTest
    static void createEventTest(){
        HolidayAction__c holidayAction = TestObjectCreator.objHolidayAction;
        holidayAction.HolidayAction_Days__c = 5;
        holidayAction.HolidayAction_Date2__c = holidayAction.HolidayAction_Date1__c.addDays(1);
        holidayAction.HolidayAction_Date3__c = holidayAction.HolidayAction_Date2__c.addDays(1);
        holidayAction.HolidayAction_Date4__c = holidayAction.HolidayAction_Date3__c.addDays(1);
        holidayAction.HolidayAction_Date5__c = holidayAction.HolidayAction_Date4__c.addDays(1);
        holidayAction.OwnerId = UserInfo.getUserId();
        insert holidayAction;

        Test.startTest();
        HolidayUtil.createEvent(holidayAction);
        Test.stopTest();
    }

    @IsTest
    static void setEventTest(){
        HolidayAction__c holidayAction = TestObjectCreator.objHolidayAction;
        holidayAction.HolidayAction_Type__c = 'Half-day Leave';
        holidayAction.HolidayAction_HalfdayTime__c = 'PM';
        holidayAction.OwnerId = UserInfo.getUserId();
        insert holidayAction;

        Test.startTest();
        HolidayUtil.setEvent(holidayAction, Date.today());
        Test.stopTest();
    }

    @IsTest
    static void sendEmailTest(){
        User user = TestObjectCreator.objUser;
        Holiday__c holiday = TestObjectCreator.objHoliday;
        holiday.Holiday_JoinDate__c = Date.today().addYears(-1);
        holiday.Holiday_GivenHolidays__c = 0;
        insert holiday;
        Holiday__c searchedHoliday = [SELECT Id, Holiday_IsAnnualleave__c, Holiday_User__c, Holiday_UseDays__c, Holiday_JoinDate__c, Holiday_PeriodEnd__c, Holiday_GivenHolidays__c, Holiday_Calculated__c, Holiday_Remain__c FROM Holiday__c WHERE Id =: holiday.Id LIMIT 1];
        System.debug(searchedHoliday);

        Test.startTest();
        HolidayUtil.sendEmail('Info', user, searchedHoliday);
        HolidayUtil.sendEmail('1st', user, searchedHoliday);
        HolidayUtil.sendEmail('2nd', user, searchedHoliday);
        Test.stopTest();
    }

    @IsTest
    static void sendEmailForConfirmedHoliday(){
        List<User> listUser = new List<User>();
        for(Integer i = 0; i < 5; i++){
            User user = TestObjectCreator.objUser;
            user = TestObjectCreator.objUser.clone();
            user.Id = null;
            user.Username = user.UserName + '.' + String.valueOf(i);
            user.LastName = user.LastName + String.valueOf(i);
            user.FirstName = user.FirstName + String.valueOf(i);
            user.Alias = user.Alias + String.valueOf(i);
            user.CommunityNickname = user.CommunityNickname + String.valueOf(i);
            listUser.add(user);
            System.debug(user);
        }
        insert listUser;

        List<Employee__c> listEmployee = new List<Employee__c>();
        for(Integer i = 0; i < 5; i++){
            Employee__c employee = TestObjectCreator.objEmployee;
            if(i != 0){
                employee = TestObjectCreator.objEmployee.clone();
                employee.Id = null;
            }
            employee.User__c = listUser.get(i).Id;
            switch on i {
                when 0{
                    employee.Department__c = 'LG Service';
                }
                when 1{
                    employee.Department__c = 'MGMT';
                }
                when 2{
                    employee.Department__c = 'LG Service';
                    employee.DeptPosition__c = 'Department Head';
                }
                when 3{
                    employee.Department__c = 'MGMT';
                    employee.DeptPosition__c = '부사장';
                }
                when 4{
                    employee.Department__c = 'MGMT';
                    employee.DeptPosition__c = 'General Manager';
                }
            }
            listEmployee.add(employee);
        }
        insert listEmployee;

        Project__c project = TestObjectCreator.objProject;
        project.Business__c = 'LG Service';
        insert project;

//        PerformProject__c performProject = TestObjectCreator.objPerformProject;
//        insert performProject;

        Holiday__c holiday = TestObjectCreator.objHoliday;
        insert holiday;

        HolidayAction__c holidayAction = TestObjectCreator.objHolidayAction;
        holidayAction.HolidayAction_Days__c = 1;
        holidayAction.Position__c = '프로젝트 팀원';
        holidayAction.Department__c = 'LG Service';
        holidayAction.HolidayAction_IsConfirm__c = false;
        holidayAction.Project__c = project.Id;
        insert holidayAction;

        List<Employee__c> emailRecipients = new List<Employee__c>();
        emailRecipients.add(listEmployee.get(1));
        emailRecipients.add(listEmployee.get(2));

        Test.startTest();
        HolidayUtil.sendEmailForConfirmedHoliday(emailRecipients, project, holidayAction, listEmployee.get(0));
        Test.stopTest();
    }

    @IsTest
    static void shareFinance(){
        HolidayAction__c holidayAction = TestObjectCreator.objHolidayAction;
        holidayAction.HolidayAction_Days__c = 1;
        holidayAction.OwnerId = UserInfo.getUserId();
        insert holidayAction;

        Test.startTest();
        HolidayUtil.shareFinance(holidayAction);
        Test.stopTest();
    }
}