PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>부서</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Departments</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/DeptPosition__c.field-meta.xml
<CustomField>
    <fullName>DeptPosition__c</fullName>
    <label>직책</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chairman</fullName>
                <label>총괄사장</label>
            </value>
            <value>
                <fullName>CEO</fullName>
                <label>대표이사</label>
            </value>
            <value>
                <fullName>부사장</fullName>
            </value>
            <value>
                <fullName>General Manager</fullName>
                <label>본부장</label>
            </value>
            <value>
                <fullName>Department Head</fullName>
                <label>부서장</label>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Pre-Sales</fullName>
            </value>
            <value>
                <fullName>Business Architecture</fullName>
                <label>Business Architect</label>
            </value>
            <value>
                <fullName>Platform Architecture</fullName>
                <label>Platform Architect</label>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Mgmt Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>직급</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>총괄사장</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>대표이사</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>센터장</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>감사</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>부사장</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>전무</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>상무</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>수석</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>이사</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>부장</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>책임</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>차장</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>과장</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>대리</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>선임</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>선임(수습)</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>사원</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>사원(수습)</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>인턴</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(ISBLANK( ExitDate__c) ||  ExitDate__c    &gt;    TODAY()  , TRUE, FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>재직여부</label>
    <type>Checkbox</type>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>사원 Object를 User Object간 Relationship 생성</inlineHelpText>
    <label>사용자 명</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/Holiday__c.object-meta.xml
<CustomObject>
    <label>Holiday</label>
    <nameField>
        <displayFormat>H-{0000}</displayFormat>
        <label>Holiday No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/CarriedOverOfLastYear__c.field-meta.xml
<CustomField>
    <fullName>CarriedOverOfLastYear__c</fullName>
    <defaultValue>0</defaultValue>
    <description>대유넥스티어 연차 계산법 기준이 회계연도로 변경되어 필드 생성 (생성일: 2022-12-27, 생성자: hyunsoo.song@daeunextier.com)

* 필드 설명
이 필드는 매년 12월 31일 23시 00분에 &apos;HolidayLastYearUpdate 매년 12월 31일 업데이트&apos; 스케줄러로 업데이트됨.</description>
    <inlineHelpText>전년도에 발생한 연차일수</inlineHelpText>
    <label>전년도 연차일수</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Holiday</relationshipLabel>
    <relationshipName>Holiday</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_Annual_Calculated__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Annual_Calculated__c</fullName>
    <description>대유넥스티어 연차 계산법 기준이 회계연도로 변경되어 새로운 연차일수 계산 필드 생성 (생성일: 2022-12-27, 생성자: hyunsoo.song@daeunextier.com)

* 필드 설명 
- 1월 1일에 연차 일괄 부여
월차만료일 존재 X -&gt; 기존입사자 : 연차일수 15개 + 추가 연차일수
월차만료일 존재 -&gt; 신규입사자 : 반올림((12.31 - 입사월일)/365*15) 

ex1) 오늘 2023년 1월 1일
사원A: 입사일 2022-05-16 → 월차만료일 존재 → 입사월일(05.16~12.31)/365*15 → 10개
사원C: 입사일 2022-01-01 → 월차만료일 존재 X → 15 + 0 → 15개
사원D: 입사일 2019-09-04 → 월차만료일 존재 X → 15 + 1 → 16개

ex2) 오늘 2022년 12월 27일
사원A: 입사일 2022-05-16 -&gt; 월차만료일 존재 -&gt; 0개</description>
    <formula>IF(
    ISNULL(Holiday_Monthly_Period__c),
    15 + MIN(Holiday_Additionaldays__c, 10),
    IF(
        DATE(YEAR(Holiday_JoinDate__c) + 1, 1, 1) &lt;= TODAY(),
        CEILING((DATE(YEAR(Holiday_JoinDate__c), 12, 31) - Holiday_JoinDate__c + 1 ) / 365 * 15), 0
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>올해 발생한 연차일수</inlineHelpText>
    <label>올해 연차일수</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_IsActive__c.field-meta.xml
<CustomField>
    <fullName>Holiday_IsActive__c</fullName>
    <formula>!ISBLANK(Employee__c) &amp;&amp; Employee__r.Status__c</formula>
    <label>재직여부</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_UseDays__c.field-meta.xml
<CustomField>
    <fullName>Holiday_UseDays__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>올해 연월차 사용일수</inlineHelpText>
    <label>연월차 사용일수</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_User__c.field-meta.xml
<CustomField>
    <fullName>Holiday_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>임직원</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Holiday</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/HolidayRemainOfLastYear__c.field-meta.xml
<CustomField>
    <fullName>HolidayRemainOfLastYear__c</fullName>
    <defaultValue>0.0</defaultValue>
    <description>대유넥스티어 연차 계산법 기준이 회계연도로 변경되어 필드 생성 (생성일: 2022-12-27, 생성자: hyunsoo.song@daeunextier.com)

* 필드 설명
이 필드는 매년 12월 31일 23시 00분에 &apos;HolidayLastYearUpdate 매년 12월 31일 업데이트&apos; 스케줄러로 업데이트됨.</description>
    <inlineHelpText>전년도에 발생한 연월차 사용 후 잔여일수</inlineHelpText>
    <label>전년도 연월차 잔여일수</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/UseDaysOfLastYear__c.field-meta.xml
<CustomField>
    <fullName>UseDaysOfLastYear__c</fullName>
    <defaultValue>0</defaultValue>
    <description>대유넥스티어 연차 계산법 기준이 회계연도로 변경되어 필드 생성 (생성일: 2022-12-27, 생성자: hyunsoo.song@daeunextier.com)

* 필드 설명
이 필드는 매년 12월 31일 23시 00분에 &apos;HolidayLastYearUpdate 매년 12월 31일 업데이트&apos; 스케줄러로 업데이트됨.</description>
    <inlineHelpText>전년도에 발생한 연월차 사용일수 - 전년도 추가부여일수</inlineHelpText>
    <label>전년도 연월차 사용일수</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/HolidayAction__c.object-meta.xml
<CustomObject>
    <description>HolidayAction__c</description>
    <label>휴가신청</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Departments</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>휴가신청</relationshipLabel>
    <relationshipName>HolidayActionV4Zc</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Date1__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Date1__c</fullName>
    <label>Date1</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Parent__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Parent__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Holiday</label>
    <referenceTo>Holiday__c</referenceTo>
    <relationshipName>Holiday_Action</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>프로젝트 PM</fullName>
            </value>
            <value>
                <fullName>프로젝트 팀원</fullName>
            </value>
            <value>
                <fullName>본사근무</fullName>
            </value>
            <value>
                <fullName>임원</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/PerformProject__c.object-meta.xml
<CustomObject>
    <label>프로젝트 수행팀</label>
    <nameField>
        <displayFormat>PJ-{0000}</displayFormat>
        <label>Seq</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>프로젝트에 참여한 사원 이름</inlineHelpText>
    <label>사원 명</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>수행 프로젝트</relationshipLabel>
    <relationshipName>EmployeePerformPjt</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/HolidayLastYearUpdate_test.cls
/**
 * @description       : 
 *                      
 * @author            : hyunsoo.song@daeunextier.com
 * @group             :
 * @last modified on  : 2023-01-02
 * @last modified by  : hyunsoo.song@daeunextier.com
 * Modifications Log
 * Ver     Date             Author               Modification
 * 1.0   2023-01-02   hyunsoo.song@daeunextier.com   Initial Version
 */

@IsTest
private class HolidayLastYearUpdate_test {
    @TestSetup
    static void testSetup() {

        if([SELECT id FROM Employee__c WHERE User__c = :UserInfo.getUserId()].isEmpty()){
            Employee__c employee = TestObjectCreator.objEmployee;
            insert employee;
        }



        Holiday__c objHoliday = new Holiday__c();
        objHoliday.Holiday_User__c = UserInfo.getUserId();
        objHoliday.Employee__c = [SELECT id, Status__c FROM Employee__c WHERE User__c = :UserInfo.getUserId() LIMIT 1].Id;
        objHoliday.Holiday_UseDays__c = 2;
        objHoliday.HolidayRemainOfLastYear__c = 1;
        objHoliday.CarriedOverOfLastYear__c = 10;
        objHoliday.UseDaysOfLastYear__c = 9;
        insert objHoliday;

        System.debug('tt :: ' + [SELECT id, Holiday_Annual_Calculated__c, Holiday_IsActive__c  FROM Holiday__c WHERE Id = :objHoliday.Id]);
        System.debug('tt2 :: ' + [SELECT id, Status__c FROM Employee__c WHERE User__c = :UserInfo.getUserId()]);

        List<User> listUser = new List<User>();
        for(Integer i = 0; i < 3; i++){
            User user = TestObjectCreator.objUser;
            if(i != 0){
                user = TestObjectCreator.objUser.clone();
                user.Id = null;
                user.Username = user.UserName + '.' + String.valueOf(i);
                user.LastName = user.LastName + String.valueOf(i);
                user.FirstName = user.FirstName + String.valueOf(i);
                user.Alias = user.Alias + String.valueOf(i);
                user.CommunityNickname = user.CommunityNickname + String.valueOf(i);
            }
            listUser.add(user);
            System.debug(user);
        }
        insert listUser;

        List<Employee__c> listEmployee = new List<Employee__c>();
        for(Integer i = 0; i < 3; i++){
            Employee__c employee = TestObjectCreator.objEmployee;
            if(i != 0){
                employee = TestObjectCreator.objEmployee.clone();

            }
            employee.Id = null;
            employee.User__c = listUser.get(i).Id;
            switch on i {
                when 0{
                    employee.Department__c = 'LG Service';
                }
                when 1{
                    employee.Department__c = 'MGMT';
                }
                when 2{
                    employee.Department__c = 'LG Service';
                    employee.DeptPosition__c = 'Department Head';
                }
            }
            listEmployee.add(employee);
        }
        insert listEmployee;

//        Holiday__c holiday = TestObjectCreator.objHoliday;
//        insert holiday;

//        HolidayAction__c holidayAction = TestObjectCreator.objHolidayAction;
        HolidayAction__c holidayAction = new HolidayAction__c();
        holidayAction.HolidayAction_Parent__c = objHoliday.Id;
        holidayAction.HolidayAction_Date1__c = Date.newInstance(date.today().year()+1 , 1,10);
        holidayAction.HolidayAction_Type__c = 'Annual Holiday';
        holidayAction.FirstHolidayRequest__c = listUser[0].Id;

        holidayAction.HolidayAction_Days__c = 1;
        holidayAction.Position__c = '프로젝트 팀원';
        holidayAction.Department__c = 'LG Service';
        holidayAction.HolidayAction_IsConfirm__c = false;

        insert holidayAction;
//
//        Project__c project = TestObjectCreator.objProject;
//        project.Business__c = 'LG Service';
//        insert project;
//
//        PerformProject__c performProject = TestObjectCreator.objPerformProject;
//        insert performProject;

    }

    @IsTest
    static void doTest() {
        Test.startTest();

        ProcessInstanceWorkitem wi = [SELECT Id FROM ProcessInstanceWorkitem order BY CreatedDate DESC LIMIT 1];
        Approval.ProcessWorkitemRequest req2 = new Approval.ProcessWorkitemRequest();
        req2.setComments('Approving request.');
        req2.setAction('Approve');
        req2.setNextApproverIds(new Id[] {UserInfo.getUserId()});
        req2.setWorkitemId(wi.Id);
        Approval.ProcessResult result2 =  Approval.process(req2);

        String CRON_EXP = '0 0 0 ? * *';
        System.schedule('testBatch', CRON_EXP, new HolidayLastYearUpdate_sc());
        Test.stopTest();
    }
}