PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/MainRole__c.field-meta.xml
<CustomField>
    <fullName>MainRole__c</fullName>
    <label>직무</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Management</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>사원 Object를 User Object간 Relationship 생성</inlineHelpText>
    <label>사용자 명</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/HolidayAction__c.object-meta.xml
<CustomObject>
    <description>HolidayAction__c</description>
    <label>휴가신청</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>휴가신청</relationshipLabel>
    <relationshipName>HolidayActionV4Zc</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/fm_MaxDate__c.field-meta.xml
<CustomField>
    <fullName>fm_MaxDate__c</fullName>
    <formula>CASE(
  Max(
    YEAR(HolidayAction_Date1__c) * 10000 + MONTH(HolidayAction_Date1__c) * 100  + DAY(HolidayAction_Date1__c),
    BLANKVALUE(YEAR(HolidayAction_Date2__c) * 10000 + MONTH(HolidayAction_Date2__c) * 100  + DAY(HolidayAction_Date2__c), 1),
    BLANKVALUE(YEAR(HolidayAction_Date3__c) * 10000 + MONTH(HolidayAction_Date3__c) * 100  + DAY(HolidayAction_Date3__c), 1),
    BLANKVALUE(YEAR(HolidayAction_Date4__c) * 10000 + MONTH(HolidayAction_Date4__c) * 100  + DAY(HolidayAction_Date4__c), 1),
    BLANKVALUE(YEAR(HolidayAction_Date5__c) * 10000 + MONTH(HolidayAction_Date5__c) * 100  + DAY(HolidayAction_Date5__c), 1) 
  ),
  YEAR(HolidayAction_Date1__c) * 10000 + MONTH(HolidayAction_Date1__c) * 100  + DAY(HolidayAction_Date1__c), HolidayAction_Date1__c, 
  YEAR(HolidayAction_Date2__c) * 10000 + MONTH(HolidayAction_Date2__c) * 100  + DAY(HolidayAction_Date2__c), HolidayAction_Date2__c, 
  YEAR(HolidayAction_Date3__c) * 10000 + MONTH(HolidayAction_Date3__c) * 100  + DAY(HolidayAction_Date3__c), HolidayAction_Date3__c, 
  YEAR(HolidayAction_Date4__c) * 10000 + MONTH(HolidayAction_Date4__c) * 100  + DAY(HolidayAction_Date4__c), HolidayAction_Date4__c,
  HolidayAction_Date5__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Max Date</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/fm_MinDate__c.field-meta.xml
<CustomField>
    <fullName>fm_MinDate__c</fullName>
    <formula>CASE(
  MIN(
    YEAR(HolidayAction_Date1__c) * 10000 + MONTH(HolidayAction_Date1__c) * 100  + DAY(HolidayAction_Date1__c),
    BLANKVALUE(YEAR(HolidayAction_Date2__c) * 10000 + MONTH(HolidayAction_Date2__c) * 100  + DAY(HolidayAction_Date2__c),99999999),
    BLANKVALUE(YEAR(HolidayAction_Date3__c) * 10000 + MONTH(HolidayAction_Date3__c) * 100  + DAY(HolidayAction_Date3__c),99999999),
    BLANKVALUE(YEAR(HolidayAction_Date4__c) * 10000 + MONTH(HolidayAction_Date4__c) * 100  + DAY(HolidayAction_Date4__c),99999999),
    BLANKVALUE(YEAR(HolidayAction_Date5__c) * 10000 + MONTH(HolidayAction_Date5__c) * 100  + DAY(HolidayAction_Date5__c),99999999) ),
  YEAR(HolidayAction_Date1__c) * 10000 + MONTH(HolidayAction_Date1__c) * 100  + DAY(HolidayAction_Date1__c), HolidayAction_Date1__c, 
  YEAR(HolidayAction_Date2__c) * 10000 + MONTH(HolidayAction_Date2__c) * 100  + DAY(HolidayAction_Date2__c), HolidayAction_Date2__c, 
  YEAR(HolidayAction_Date3__c) * 10000 + MONTH(HolidayAction_Date3__c) * 100  + DAY(HolidayAction_Date3__c), HolidayAction_Date3__c, 
  YEAR(HolidayAction_Date4__c) * 10000 + MONTH(HolidayAction_Date4__c) * 100  + DAY(HolidayAction_Date4__c), HolidayAction_Date4__c,
  HolidayAction_Date5__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Min Date</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/Holiday_Date_Detail__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Date_Detail__c</fullName>
    <formula>IF( TEXT(HolidayAction_Date1__c) &lt;&gt; &quot;&quot;, TEXT(HolidayAction_Date1__c),&quot;&quot;) + 
IF( TEXT(HolidayAction_Date2__c) &lt;&gt; &quot;&quot;, &quot;, &quot;+TEXT(HolidayAction_Date2__c),&quot;&quot;) + 
IF( TEXT(HolidayAction_Date3__c) &lt;&gt; &quot;&quot;, &quot;, &quot;+TEXT(HolidayAction_Date3__c),&quot;&quot;) + 
IF( TEXT(HolidayAction_Date4__c) &lt;&gt; &quot;&quot;, &quot;, &quot;+TEXT(HolidayAction_Date4__c),&quot;&quot;) + 
IF( TEXT(HolidayAction_Date5__c) &lt;&gt; &quot;&quot;, &quot;, &quot;+TEXT(HolidayAction_Date5__c),&quot;&quot;) + 
IF( TEXT(HolidayAction_Date6__c) &lt;&gt; &quot;&quot;, &quot;, &quot;+TEXT(HolidayAction_Date6__c),&quot;&quot;) + 
IF( TEXT(HolidayAction_Date7__c) &lt;&gt; &quot;&quot;, &quot;, &quot;+TEXT(HolidayAction_Date7__c),&quot;&quot;) + 
IF( TEXT(HolidayAction_Date8__c) &lt;&gt; &quot;&quot;, &quot;, &quot;+TEXT(HolidayAction_Date8__c),&quot;&quot;) + 
IF( TEXT(HolidayAction_Date9__c) &lt;&gt; &quot;&quot;, &quot;, &quot;+TEXT(HolidayAction_Date9__c),&quot;&quot;) + 
IF( TEXT(HolidayAction_Date10__c) &lt;&gt; &quot;&quot;, &quot;, &quot;+TEXT(HolidayAction_Date10__c),&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>휴가일자 상세</label>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Days__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Days__c</fullName>
    <inlineHelpText>Women&apos;s Holiday 1.
Alternative Holiday 0.
Other Holidays from 1 to 5.</inlineHelpText>
    <label>Days</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_IsConfirm__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_IsConfirm__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Confirm?</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Type__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Annual Holiday</fullName>
                <label>연차</label>
            </value>
            <value>
                <fullName>Half-day Leave</fullName>
                <label>반차</label>
            </value>
            <value>
                <fullName>Reward Holiday</fullName>
                <label>대체휴가</label>
            </value>
            <value>
                <fullName>Reward Half-Holiday</fullName>
                <label>대체휴가(반차)</label>
            </value>
            <value>
                <fullName>Public Works</fullName>
                <label>공가(공무)</label>
            </value>
            <value>
                <fullName>Family Leave</fullName>
                <label>경조휴가</label>
            </value>
            <value>
                <fullName>Sick Leave</fullName>
                <label>병가(무급)</label>
            </value>
            <value>
                <fullName>Women Holiday</fullName>
                <label>생리휴가</label>
            </value>
            <value>
                <fullName>가족돌봄휴가</fullName>
            </value>
            <value>
                <fullName>출산휴가</fullName>
            </value>
            <value>
                <fullName>휴직</fullName>
            </value>
            <value>
                <fullName>육아휴직</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_UserName__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_UserName__c</fullName>
    <formula>HolidayAction_Parent__r.Holiday_User__r.LastName &amp;  HolidayAction_Parent__r.Holiday_User__r.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>User Name</label>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Project_HolidayAction</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/PerformProject__c.object-meta.xml
<CustomObject>
    <label>프로젝트 수행팀</label>
    <nameField>
        <displayFormat>PJ-{0000}</displayFormat>
        <label>Seq</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>프로젝트에 참여한 사원 이름</inlineHelpText>
    <label>사원 명</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>수행 프로젝트</relationshipLabel>
    <relationshipName>EmployeePerformPjt</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/EmpNm__c.field-meta.xml
<CustomField>
    <fullName>EmpNm__c</fullName>
    <formula>Employee__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>사원명</label>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/fm_FromDate__c.field-meta.xml
<CustomField>
    <fullName>fm_FromDate__c</fullName>
    <formula>BLANKVALUE( InputDate__c ,  Project__r.StartDate__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>시작일</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/fm_Term__c.field-meta.xml
<CustomField>
    <fullName>fm_Term__c</fullName>
    <formula>Text( InputDate__c ) &amp; &quot; ~ &quot; &amp;  TEXT(WithdrawDate__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>수행기간</label>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/fm_ToDate__c.field-meta.xml
<CustomField>
    <fullName>fm_ToDate__c</fullName>
    <formula>BLANKVALUE( WithdrawDate__c ,  Project__r.EndDate__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>종료일</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트 명</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>프로젝트 수행팀</relationshipLabel>
    <relationshipName>Project</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/Ratio__c.field-meta.xml
<CustomField>
    <fullName>Ratio__c</fullName>
    <inlineHelpText>투입비율: 1%~100%</inlineHelpText>
    <label>투입비율</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>프로젝트에 대한 기본정보를 관리하며, Deal Closing 이후 생성한다. 영업담당자가 계약 체결 후 기초 데이터를 작성하며, 프로젝트 진행 중에는 PM이 관리하고, 대금청구/지급 관련 정보는 회계에서 관리한다.</description>
    <label>프로젝트</label>
    <nameField>
        <label>프로젝트 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/classes/ViewHRInfoController.cls
public with sharing class ViewHRInfoController {

	/*라이트닝에서 식별할 수 있도록 해주는 어노테이션*/
	@AuraEnabled
	public static Map<String, Object> getInitData(String idEmployee, String pFromDt, String pToDt) {
		/*System.debug('param1 : ' + param1); Id 받을애*/

		Date dFromDt = Date.valueOf(pFromDt);
        Date dToDt   = Date.valueOf(pToDt);
 

		/*프로젝트에서 프로젝트명, 기간, 비율(/100해야함), 이름, 사원테이블의 롤*/
		List<PerformProject__c> pjList = new List<PerformProject__c>();
		pjList = [SELECT    Id, Project__r.Name,  fm_Term__c, Ratio__c, EmpNm__c, Employee__r.MainRole__c
				  FROM      PerformProject__c
				  WHERE     Employee__c = :idEmployee 
				  AND       fm_FromDate__c <= :dToDt
                  AND       fm_ToDate__c   >= :dFromDt
                  ORDER BY 	fm_FromDate__c];
		System.debug('pjList : ' + pjList);

		Employee__c emUser = [SELECT User__c, Name
				  			  FROM   Employee__c
				  			  WHERE  Id = :idEmployee];


		/*휴가 Table에서 휴가명, 휴가일, 휴가날짜1-5, 휴가타입 받아오기*/

		/*where조건*/
		/*Employee__c에 있는 Id가 오너ID랑 일치할 경우*/
		/*parma1이 지금 Employee__c에 Id값을 대입한거잖아*/
		  
		List<HolidayAction__c> haList = new List<HolidayAction__c>(); 
		haList = [SELECT 	HolidayAction_UserName__c, HolidayAction_Days__c, Name, Holiday_Date_Detail__c, HolidayAction_Type__c
				  FROM 		HolidayAction__c
				  WHERE  	OwnerId = :emUser.User__c
				  AND 	 	HolidayAction_IsConfirm__c = true
				  AND       fm_MinDate__c <= :dToDt
                  AND       fm_MaxDate__c >= :dFromDt
				  ORDER BY  Holiday_Date_Detail__c ASC ];
		System.debug('haList : ' + haList);


 		/*리턴해줄 맵 생성*/
 		/*object는 최상위 객체 이니까 list/map 다 가능가능*/
 		/*'key' => value  ('key'의 값은 value로 하겠다)*/    
		Map<String, Object> mapReturnValue = new Map<String, Object> {
			'pjList' => pjList,
			'haList' => haList,
			'emUser' => emUser
		};

		return mapReturnValue;
	}//getInitData

}//ViewHRInfoController