PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Emergency_Contact__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Contact__c</fullName>
    <inlineHelpText>응급상황 시 연락가능한 전화번호</inlineHelpText>
    <label>비상연락번호</label>
    <type>Phone</type>
</CustomField>

ListViewButton/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>구분</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>내부직원</fullName>
            </value>
            <value>
                <fullName>외부직원</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>사원 Object를 User Object간 Relationship 생성</inlineHelpText>
    <label>사용자 명</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/PerformProject__c.object-meta.xml
<CustomObject>
    <label>프로젝트 수행팀</label>
    <nameField>
        <displayFormat>PJ-{0000}</displayFormat>
        <label>Seq</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>프로젝트에 참여한 사원 이름</inlineHelpText>
    <label>사원 명</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>수행 프로젝트</relationshipLabel>
    <relationshipName>EmployeePerformPjt</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/InputDate__c.field-meta.xml
<CustomField>
    <fullName>InputDate__c</fullName>
    <label>투입 일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/IsPM__c.field-meta.xml
<CustomField>
    <fullName>IsPM__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PM여부</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트 명</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>프로젝트 수행팀</relationshipLabel>
    <relationshipName>Project</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>프로젝트에 대한 기본정보를 관리하며, Deal Closing 이후 생성한다. 영업담당자가 계약 체결 후 기초 데이터를 작성하며, 프로젝트 진행 중에는 PM이 관리하고, 대금청구/지급 관련 정보는 회계에서 관리한다.</description>
    <label>프로젝트</label>
    <nameField>
        <label>프로젝트 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/fields/Completed__c.field-meta.xml
<CustomField>
    <fullName>Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>프로젝트가 종료되면 체크함.</inlineHelpText>
    <label>완료 여부</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>종료 일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/fields/OpeningDate__c.field-meta.xml
<CustomField>
    <fullName>OpeningDate__c</fullName>
    <label>오픈 일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/fields/PM__c.field-meta.xml
<CustomField>
    <fullName>PM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트 관리자</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PM</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/fields/PMEmail__c.field-meta.xml
<CustomField>
    <fullName>PMEmail__c</fullName>
    <label>PMEmail</label>
    <type>Email</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/fields/Salesforce_Industry__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Industry__c</fullName>
    <label>Salesforce 산업분류</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>자동차</fullName>
            </value>
            <value>
                <fullName>통신</fullName>
            </value>
            <value>
                <fullName>소비재</fullName>
            </value>
            <value>
                <fullName>교육</fullName>
            </value>
            <value>
                <fullName>에너지 및 유틸리티</fullName>
            </value>
            <value>
                <fullName>금융 서비스</fullName>
            </value>
            <value>
                <fullName>공공부문</fullName>
            </value>
            <value>
                <fullName>헬프케어 및 생명과학</fullName>
            </value>
            <value>
                <fullName>제조업</fullName>
            </value>
            <value>
                <fullName>미디어</fullName>
            </value>
            <value>
                <fullName>비영리</fullName>
            </value>
            <value>
                <fullName>리테일</fullName>
            </value>
            <value>
                <fullName>기술</fullName>
            </value>
            <value>
                <fullName>운송 및 호스피탈리티</fullName>
            </value>
            <value>
                <fullName>직접입력</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/fields/Salesforce_Product__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Product__c</fullName>
    <label>Salesforce 제품분류</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales Cloud</fullName>
            </value>
            <value>
                <fullName>Service Cloud</fullName>
            </value>
            <value>
                <fullName>Marketing Cloud</fullName>
            </value>
            <value>
                <fullName>Commerce Cloud</fullName>
            </value>
            <value>
                <fullName>Tableau</fullName>
            </value>
            <value>
                <fullName>MuleSoft</fullName>
            </value>
            <value>
                <fullName>Salesforce Platform</fullName>
            </value>
            <value>
                <fullName>Net Zero Cloud</fullName>
            </value>
            <value>
                <fullName>Nonprofit Cloud</fullName>
            </value>
            <value>
                <fullName>Experience Cloud</fullName>
            </value>
            <value>
                <fullName>직접입력</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>착수 일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/recordTypes/Project.recordType-meta.xml
<RecordType>
    <fullName>Project</fullName>
    <active>true</active>
    <description>프로젝트 사항 입력하는 Record Type</description>
    <label>프로젝트</label>
</RecordType>

PA_Education/TestMenifest/force-app/main/default/classes/EmployeeEvaluationBtnController_Test.cls
/**
 * Created by yj.kim on 2023-07-12.
 */
@IsTest
public with sharing class EmployeeEvaluationBtnController_Test {
    @IsTest
    static void testEvaluation(){
        User userObj = TestObjectCreator.objUser;
        insert userObj;

        User userObj2 = new User();
        userObj2.Email               = 'test2@test.com';
        userObj2.LastName            = 'testUser2';
        userObj2.FirstName           = 'testUser2';
        userObj2.ProfileId           = UserInfo.getProfileId();
        userObj2.Emailencodingkey    = 'ks_c_5601-1987';
        userObj2.Languagelocalekey   = 'en_US';
        userObj2.IsActive            = true;
        userObj2.Username            = 'testUser2@daeunextier.com';
        userObj2.Alias               = 'user2';
        userObj2.CommunityNickname   = 'user2';
        userObj2.TimeZoneSidKey      = 'Asia/Seoul';
        userObj2.LocaleSidKey        = 'ko_KR';
        insert userObj2;

        User userObj3 = new User();
        userObj3.Email               = 'testUser3@test.com';
        userObj3.LastName            = 'testUser3';
        userObj3.FirstName           = 'testUser3';
        userObj3.ProfileId           = UserInfo.getProfileId();
        userObj3.Emailencodingkey    = 'ks_c_5601-1987';
        userObj3.Languagelocalekey   = 'en_US';
        userObj3.IsActive            = true;
        userObj3.Username            = 'testUser3@daeunextier.com';
        userObj3.Alias               = 'User3';
        userObj3.CommunityNickname   = 'User3';
        userObj3.TimeZoneSidKey      = 'Asia/Seoul';
        userObj3.LocaleSidKey        = 'ko_KR';
        insert userObj3;

        Employee__c em1 = TestObjectCreator.objEmployee;
        em1.Type__c = '내부직원';
        insert em1;

        Employee__c em2 = new Employee__c();
        em2.Name = 'Test Employee2';
        em2.Emergency_Contact__c = '01000000000';
        em2.User__c = userObj2.Id;
        em2.Type__c = '내부직원';
        insert em2;

        Employee__c em3 = new Employee__c();
        em3.Name = 'Test Employee3';
        em3.Emergency_Contact__c = '010000000100';
        em3.User__c = userObj3.Id;
        em3.Type__c = '외부직원';
        insert em3;

        Project__c projectObj = new Project__c();
        projectObj.Name = 'testProject';
        projectObj.PMEmail__c = 'test@daeunextier.com';
        projectObj.Salesforce_Product__c = 'Sales Cloud';
        projectObj.Salesforce_Industry__c = '자동차';
        projectObj.OpeningDate__c = Date.today().addDays(60);
        projectObj.StartDate__c = Date.today();
        projectObj.EndDate__c = Date.today().addDays(60);
        projectObj.PM__c = userObj2.Id;
        projectObj.Completed__c = true;
        insert projectObj;

        PerformProject__c performObj = new PerformProject__c();
        performObj.Project__c = projectObj.Id;
        performObj.Employee__c = em1.Id;
        performObj.InputDate__c = Date.today().addDays(-30);
        performObj.IsPM__c = true;
        insert performObj;

        PerformProject__c performObj2 = new PerformProject__c();
        performObj2.Project__c = projectObj.Id;
        performObj2.Employee__c = em2.Id;
        performObj2.InputDate__c = Date.today().addDays(-30);
        insert performObj2;

        PerformProject__c performObj3 = new PerformProject__c();
        performObj3.Project__c = projectObj.Id;
        performObj3.Employee__c = em3.Id;
        performObj3.InputDate__c = Date.today().addDays(-30);
        insert performObj3;

        PerformProject__c updateObj = new PerformProject__c();
        updateObj.Id = performObj.Id;
        updateObj.InputDate__c = Date.today().addDays(-60);
        update updateObj;

        List<Map<String, Object>> inList = new List<Map<String, Object>>();
        Map<String, Object> inMap = new Map<String, Object>();
        List<Map<String, Object>> exList = new List<Map<String, Object>>();
        Map<String, Object> exMap = new Map<String, Object>();

        inMap.put('performProjectId', performObj2.Id);
        inMap.put('project', projectObj.Id);
        inMap.put('employeeId', em2.Id);
        inMap.put('fromDate', Date.today());
        inMap.put('toDate', Date.today());
        inMap.put('competency', 'S');
        inMap.put('communication', 'S');
        inMap.put('cooperation', 'S');
        inMap.put('passion', 'S');
        inMap.put('attitude', 'S');
        inMap.put('addWork', '');
        inMap.put('addComment', '');
        inList.add(inMap);

        exMap.put('performProjectId', performObj2.Id);
        exMap.put('project', projectObj.Id);
        exMap.put('employeeId', em3.Id);
        exMap.put('fromDate', Date.today());
        exMap.put('toDate', Date.today());
        exMap.put('competency', 'S');
        exMap.put('communication', 'S');
        exMap.put('cooperation', 'S');
        exMap.put('passion', 'S');
        exMap.put('attitude', 'S');
        exMap.put('addWork', '');
        exMap.put('addComment', '');
        exList.add(inMap);

        Test.startTest();
        EmployeeEvaluationBtnController.doInit(projectObj.Id);
        EmployeeEvaluationBtnController.doSave(inList, exList, false);
        Test.stopTest();



    }
}