PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/JoinDate__c.field-meta.xml
<CustomField>
    <fullName>JoinDate__c</fullName>
    <description>입사일자</description>
    <label>입사일자</label>
    <type>Date</type>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>사원 Object를 User Object간 Relationship 생성</inlineHelpText>
    <label>사용자 명</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/Holiday__c.object-meta.xml
<CustomObject>
    <label>Holiday</label>
    <nameField>
        <displayFormat>H-{0000}</displayFormat>
        <label>Holiday No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Holiday</relationshipLabel>
    <relationshipName>Holiday</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_Additionaldays__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Additionaldays__c</fullName>
    <formula>FLOOR((Holiday_RuleWorkingYears__c  - 1) / 2)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>추가연차일수</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_Annual_Calculated__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Annual_Calculated__c</fullName>
    <description>대유넥스티어 연차 계산법 기준이 회계연도로 변경되어 새로운 연차일수 계산 필드 생성 (생성일: 2022-12-27, 생성자: hyunsoo.song@daeunextier.com)

* 필드 설명 
- 1월 1일에 연차 일괄 부여
월차만료일 존재 X -&gt; 기존입사자 : 연차일수 15개 + 추가 연차일수
월차만료일 존재 -&gt; 신규입사자 : 반올림((12.31 - 입사월일)/365*15) 

ex1) 오늘 2023년 1월 1일
사원A: 입사일 2022-05-16 → 월차만료일 존재 → 입사월일(05.16~12.31)/365*15 → 10개
사원C: 입사일 2022-01-01 → 월차만료일 존재 X → 15 + 0 → 15개
사원D: 입사일 2019-09-04 → 월차만료일 존재 X → 15 + 1 → 16개

ex2) 오늘 2022년 12월 27일
사원A: 입사일 2022-05-16 -&gt; 월차만료일 존재 -&gt; 0개</description>
    <formula>IF(
    ISNULL(Holiday_Monthly_Period__c),
    15 + MIN(Holiday_Additionaldays__c, 10),
    IF(
        DATE(YEAR(Holiday_JoinDate__c) + 1, 1, 1) &lt;= TODAY(),
        CEILING((DATE(YEAR(Holiday_JoinDate__c), 12, 31) - Holiday_JoinDate__c + 1 ) / 365 * 15), 0
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>올해 발생한 연차일수</inlineHelpText>
    <label>올해 연차일수</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_Calculated__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Calculated__c</fullName>
    <description>대유넥스티어 사내 규칙에 맞는 연차여부 필드 수정으로 인한 예시 변경(수정일: 2021-12-31, 수정자: cj.sohn@daeunextier.com)
* 연차여부 수식 수정:
입사기준일인 경우, 입사일 + 365일
연차기준일(2020. 1. 1)인 경우, 입사일 다음년도 (연차 기준일)월 (연차 기준일)일 - 1

필드 설명
연차여부가 TRUE일 때, 15일 + 추가연차일수
연차여부가 FALSE일 때, 12 - (입사월 + 1)
ex)  오늘 2022년 3월 17일
       사원A: 입사일 2020-03-17 → 연차적용시작일(2020-12-31) → 연차여부 = TRUE → 15 + 0 개
       사원B: 입사일 2021-12-07 → 연차적용시작일(2021-12-31) → 연차여부 = TRUE → 15 + 0 개
       사원C: 입사일 2022-01-01 → 연차적용시작일(2022-12-31) → 연차여부 = FALSE → 12 - 1 = 11개
       사원D: 입사일 2022-01-04 → 연차적용시작일(2022-12-31) → 연차여부 = FALSE → 12 - (1 + 1) = 10개

휴가 연차일수 부여 개편으로 인한 수정(필드 수식 수정일: 2021-01-12, 필드 수정자: cj.sohn@daeunextier.com)
연차여부 수식 수정 이전 예시:
ex)  오늘 2021년 2월 4일
       사원A: 입사일 2020-12-07 → 연차적용시작일(2021-01-01) → 연차여부 = TRUE → 15 + 0 개
       사원B: 입사일 2021-01-01 → 연차적용시작일(2022-01-01) → 연차여부 = FALSE → 12 - 1 = 11개
       사원C: 입사일 2021-01-04 → 연차적용시작일(2022-01-01) → 연차여부 = FALSE → 12 - (1 + 1) = 10개</description>
    <formula>IF(
	Holiday_IsAnnualleave__c,
	15 + MIN(Holiday_Additionaldays__c , 10 ),
        IF(
                DAY(Holiday_JoinDate__c) = 1,
                IF(
	        	12 - (MONTH(Holiday_JoinDate__c) + 1) &lt; 0, 
	        	1,
	        	12 - MONTH(Holiday_JoinDate__c)
        	),
               	IF(
	        	12 - (MONTH(Holiday_JoinDate__c) + 1) &lt; 0, 
	        	0,
	        	12 - (MONTH(Holiday_JoinDate__c) + 1)
        	)
        )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>연차일수</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_GivenHolidays__c.field-meta.xml
<CustomField>
    <fullName>Holiday_GivenHolidays__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>추가적으로 부여된 연월차일수</inlineHelpText>
    <label>추가 부여 일수</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_IsActive__c.field-meta.xml
<CustomField>
    <fullName>Holiday_IsActive__c</fullName>
    <formula>!ISBLANK(Employee__c) &amp;&amp; Employee__r.Status__c</formula>
    <label>재직여부</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_IsAnnualleave__c.field-meta.xml
<CustomField>
    <fullName>Holiday_IsAnnualleave__c</fullName>
    <formula>Holiday_StartDate__c &lt;=  TODAY()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>연차여부</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_JoinDate__c.field-meta.xml
<CustomField>
    <fullName>Holiday_JoinDate__c</fullName>
    <label>입사일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_LastActivity__c.field-meta.xml
<CustomField>
    <fullName>Holiday_LastActivity__c</fullName>
    <label>최종 사용 내역</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_Monthly_Calculated__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Monthly_Calculated__c</fullName>
    <description>대유넥스티어 연차 계산법 기준이 회계연도로 변경되어 필드 생성 (생성일: 2022-12-27, 생성자: hyunsoo.song@daeunextier.com)

* 필드 설명
1. 입사 1년차 이상 (월차 만료일 == BLANK || 전년도 월차일수 == 11개)
: 0

2. 신규입사자
: 입사연도 다음 해로 변경될 시 다시 1부터 Count (단, 입사일자의 DAY에 해당하는 일자 하루 전 날 부여됨)

ex) 오늘 2023년 01월 13일
사원A: 입사일 2022-05-16 → 월차 만료일(2023-12-31) →  0개	(매달 15일에 월차 부여)
사원B: 입사일 2022-12-13 → 월차 만료일(2023-12-31) → 1개 	(매달 12일에 월차 부여)

사원C: 입사일 2022-01-01 → 월차 만료일(2023-12-31) → 0개	(전년도 월차 11개, 올해 월차 0개)
사원D: 입사일 2021-09-04 → 월차 만료일(BLANK) → 0개</description>
    <formula>IF(
    ISBLANK(Holiday_Monthly_Period__c) || MonthlyOfLastYear__c = 11, 0,
    IF(
        YEAR(Holiday_Monthly_Period__c) = YEAR(TODAY()),
        11 - MonthlyOfLastYear__c,
        IF(
            FLOOR((DATE(YEAR(TODAY()), 12, 31) - Holiday_JoinDate__c - 1) / 30) &gt; 11,
            11,
            FLOOR((DATE(YEAR(TODAY()), 12, 31) - Holiday_JoinDate__c - 1) / 30)
        )
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>올해 발생한 월차일수 (월차는 입사일에 해당하는 일자 하루 전 날 부여됩니다.)</inlineHelpText>
    <label>올해 월차일수</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_Monthly_Period__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Monthly_Period__c</fullName>
    <formula>IF( 
    YEAR(ADDMONTHS(Holiday_JoinDate__c, 12)) &lt; YEAR(TODAY()), 
    NULL, 
    DATE(YEAR(ADDMONTHS(Holiday_JoinDate__c, 12)), 12, 31)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>월차 만료일</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_NoticeLevel__c.field-meta.xml
<CustomField>
    <fullName>Holiday_NoticeLevel__c</fullName>
    <label>공지 단계</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Need</fullName>
                <default>true</default>
                <label>Not Need</label>
            </value>
            <value>
                <fullName>1st Notice</fullName>
            </value>
            <value>
                <fullName>2nd Notice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_PeriodEnd__c.field-meta.xml
<CustomField>
    <fullName>Holiday_PeriodEnd__c</fullName>
    <description>수식 필드에 대한 상세설명 작성(필드 상세설명 수정일: 2021-12-23, 수정자: cj.sohn@daeunextier.com)
1. 입사일 기준여부가 TRUE일 때,
1-1) 금연도 입사월일이 오늘보다 작을 때, 금연도 입사월일 - 1 + 365
1-2) 금연도 입사월일이 오늘보다 크거나 같을 때, 금연도 입사월일 -1 + 0

ex) 오늘: 2021년 12월 23일
사원A: 입사일 2019-12-15 →  금연도 입사월일 (2021-12-15) → 연차만료일: 2022-12-15
사원B: 입사일 2020-12-28 → 금연도 입사월일 (2021-12-28) → 연차만료일: 2021-12-28
사원C: 입사일 2021-12-23 →  금연도 입사월일 (2021-12-23) → 연차만료일: 2022-12-22

2. 입사일 기준여부가 FALSE일 때,
2-1) 금연도 말일이 오늘보다 클 때, 전연도 말일 + 365
2-2) 금연도 말일이 오늘보다 작거나 같을 때, 전연도 말일 + 0 (가능성 0%)

ex) 오늘: 2021년 2월 4일, 금연도 말일: 2021년 12월 31일 → 연차만료일: 2021년 12월 31일

* 참고사항
Custom Setting(HolidaySetting__c)의 필드 및 값 정리 (2021-12-23 기준)
- 연차기준일(HoldayRuleDate__c): 2000. 1. 1
- 갱신일 이전 일수 차감여부(IsCeil__c): true
- 입사일 기준여부(JoinDateRule__c): false</description>
    <formula>IF(
    $Setup.HolidaySetting__c.JoinDateRule__c,
    DATE( YEAR(TODAY()), MONTH(Holiday_JoinDate__c), DAY(Holiday_JoinDate__c) ) - 1 +
    IF(
        DATE( YEAR(TODAY()), MONTH(Holiday_JoinDate__c), DAY(Holiday_JoinDate__c) ) &lt; TODAY(),
        365,
        0
    ),
    DATE( YEAR(TODAY()), MONTH($Setup.HolidaySetting__c.HoldayRuleDate__c ), DAY($Setup.HolidaySetting__c.HoldayRuleDate__c) ) - 1 +
    IF(
        DATE( YEAR(TODAY()), MONTH($Setup.HolidaySetting__c.HoldayRuleDate__c), DAY($Setup.HolidaySetting__c.HoldayRuleDate__c) ) &lt; TODAY(),
        365,
        0
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>연차만료일</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_Remain__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Remain__c</fullName>
    <description>4월1일 이전인 경우, 잔여일수=연차일수-사용일수+전년도 연차 잔여일수
3월31일 이후인 경우, 잔여일수=연차일수-사용일수

22.03.31
임시로 기준일을 12월 31일로 변경
변경전: TODAY() &lt;  DATE(YEAR(TODAY()), 4, 1)
변경후: TODAY() &lt;=  DATE(YEAR(TODAY()), 12, 31)</description>
    <formula>IF(
    TODAY() &lt;  DATE(YEAR(TODAY()), 4, 1),
    NULLVALUE( Holiday_Calculated__c , 0) -  NULLVALUE(Holiday_UseDays__c  , 0) +  Holiday_GivenHolidays__c + RemainOfLastYear__c ,
    NULLVALUE( Holiday_Calculated__c , 0) -  NULLVALUE(Holiday_UseDays__c  , 0) +  Holiday_GivenHolidays__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>전년도 잔여연차 사용을 임시로 올해 12월 31일까지 사용 가능하도록 변경되었습니다.</inlineHelpText>
    <label>잔여일수</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_StartDate__c.field-meta.xml
<CustomField>
    <fullName>Holiday_StartDate__c</fullName>
    <description>대유넥스티어 사내 규칙에 맞는 연차여부 필드 수정(수정일: 2021-12-31, 수정자: cj.sohn@daeunextier.com)
입사기준일인 경우, 입사일 + 365일
연차기준일인 경우, 입사일 다음년도 (연차 기준일)월 (연차 기준일)일 - 1

변경 전 수식
필드 설명 추가(수정일: 2021-01-12, 수정자: cj.sohn@daeunextier.com)
입사기준일인 경우, 입사일 + 365일
연차기준일인 경우, 입사일 다음년도 (연차 기준일)월 (연차 기준일)일
IF(
    $Setup.HolidaySetting__c.JoinDateRule__c, 
    Holiday_JoinDate__c + 365,
    Date(Year(Holiday_JoinDate__c)+1, MONTH($Setup.HolidaySetting__c.HoldayRuleDate__c), DAY($Setup.HolidaySetting__c.HoldayRuleDate__c))
)</description>
    <formula>IF(
    $Setup.HolidaySetting__c.JoinDateRule__c, 
    Holiday_JoinDate__c + 365,
    Date(Year(Holiday_JoinDate__c)+1, MONTH($Setup.HolidaySetting__c.HoldayRuleDate__c), DAY($Setup.HolidaySetting__c.HoldayRuleDate__c))-1
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>연차적용시작일</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_Uncountable__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Uncountable__c</fullName>
    <defaultValue>0</defaultValue>
    <label>공무</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_Unpaid__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Unpaid__c</fullName>
    <defaultValue>0</defaultValue>
    <label>무급휴가</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_UseDays__c.field-meta.xml
<CustomField>
    <fullName>Holiday_UseDays__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>올해 연월차 사용일수</inlineHelpText>
    <label>연월차 사용일수</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_User__c.field-meta.xml
<CustomField>
    <fullName>Holiday_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>임직원</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Holiday</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_WorkingYears__c.field-meta.xml
<CustomField>
    <fullName>Holiday_WorkingYears__c</fullName>
    <description>입사일 기준 근속 년수</description>
    <formula>YEAR(TODAY()) - YEAR(Holiday_JoinDate__c) 
+ IF(
   MONTH(TODAY()) * 100 + DAY(TODAY()) &gt;= 
   MONTH(Holiday_JoinDate__c) * 100 + 
   DAY( Holiday_JoinDate__c) 
   , 0 
   , -1
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>근속연수</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/HolidayRemainOfLastYear__c.field-meta.xml
<CustomField>
    <fullName>HolidayRemainOfLastYear__c</fullName>
    <defaultValue>0.0</defaultValue>
    <description>대유넥스티어 연차 계산법 기준이 회계연도로 변경되어 필드 생성 (생성일: 2022-12-27, 생성자: hyunsoo.song@daeunextier.com)

* 필드 설명
이 필드는 매년 12월 31일 23시 00분에 &apos;HolidayLastYearUpdate 매년 12월 31일 업데이트&apos; 스케줄러로 업데이트됨.</description>
    <inlineHelpText>전년도에 발생한 연월차 사용 후 잔여일수</inlineHelpText>
    <label>전년도 연월차 잔여일수</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/HolidayManageContoller_Test.cls
@isTest
public class HolidayManageContoller_Test {
    @testSetup
    static void setup() {
        Profile pf = [SELECT Id FROM Profile WHERE Name= 'System Administrator'];
        List<User> usrLst = new List<User>();
        for(Integer i = 0 ; i < 10 ; i++){
            User usr = new User(Alias = 'testUser'
                    , Email='SysAdminTestuser@earth.org' + String.valueOf(i)
                    , EmailEncodingKey='UTF-8'
                    , LastName='Testing'
                    , LanguageLocaleKey='en_US'
                    , LocaleSidKey='en_US'
                    , EmployeeNumber='AC100000' + String.valueOf(i)
                    , ProfileId = pf.Id
                    , TimeZoneSidKey='Asia/Seoul'
                    , UserName='SysAdminTestuser@earth.org' + String.valueOf(i)
//                    , IsActive= Math.mod(i,2)==0?true:false
                    , IsActive= true
            );
            usrLst.add(usr);
        }
//        Database.insert(usrLst, false);
        insert usrLst;
//
        List<Employee__c> listEmployee = new List<Employee__c>();
        for(User objUser : usrLst) {
            Employee__c objEmployee = new Employee__c();
            objEmployee.User__c = objUser.Id;
            objEmployee.Name = objUser.UserName;
            objEmployee.JoinDate__c = date.today();
            listEmployee.add(objEmployee);
        }
        insert listEmployee;
    }
    @isTest
    static void testHolidayManageController() {
        Test.startTest();
        HolidayManageController.doCreate();
        List<HolidayManageController.HolidayEmployeeWrapper> hldLst = HolidayManageController.getData(true);
        hldLst = HolidayManageController.getData(false);

        Set<Id> setHldId = new Set<Id>();
        for(HolidayManageController.HolidayEmployeeWrapper obj : hldLst) {
            setHldId.add(obj.Id);
        }

        List<Holiday__c> listHolidays = [
                SELECT Id, Name, Holiday_Additionaldays__c, Holiday_Calculated__c, Holiday_GivenHolidays__c, Holiday_IsActive__c, Holiday_IsAnnualleave__c, Holiday_JoinDate__c,
                        Holiday_LastActivity__c, Holiday_NoticeLevel__c, Holiday_PeriodEnd__c, Holiday_Remain__c, Holiday_StartDate__c, Holiday_Uncountable__c, Holiday_Unpaid__c, Holiday_UseDays__c,
                        Holiday_User__c, Holiday_User__r.Name, Holiday_User__r.UserRole.Name, Holiday_User__r.Title, Holiday_WorkingYears__c, Holiday_Monthly_Calculated__c,
                        Holiday_Annual_Calculated__c, Holiday_Monthly_Period__c, HolidayRemainOfLastYear__c, RemainOfLastYear__c, Holiday_Total_Remain__c,
                        Holiday_WomenHoliday_Count__c, Holiday_SickLeave_Count__c, Holiday_FamilyEvent_Count__c, Holiday_PublicWorks_Count__c, MonthlyOfLastYear__c
                FROM Holiday__c
                WHERE Id IN :setHldId
                ORDER BY Holiday_JoinDate__c
        ];

        for(Integer i = 0;i < hldLst.size();i++) {
            Holiday__c hld = listHolidays[i];
            hld.Holiday_JoinDate__c = Date.today().addYears(-i);
        }

        List<Map<String,Object>> objList = new List<Map<String,Object>>();
        Map<String,Object> objMap = new Map<String,Object>();

        for(Holiday__c obj : listHolidays){
            objMap.put('Id', obj.Id);
            objMap.put('GivenHolidays', '3');
            objList.add(objMap);
        }


        HolidayManageController.doSave(listHolidays);
        HolidayManageController.doModify(objList,3,'test');
//        HolidayManageController.doModify(objList,3,'');
//        HolidayManageController.doModify(objList,4,'');
        HolidayManageController.doUpdate();
        HolidayManageController.doSend(listHolidays);
        HolidayManageController.doReset(listHolidays,'unpaid');
        HolidayManageController.doReset(listHolidays,'uncountable');
        HolidayManageController.doCreate();
        Test.stopTest();
    }
}