PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/EmployeeNo__c.field-meta.xml
<CustomField>
    <fullName>EmployeeNo__c</fullName>
    <label>사번</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/JoinDate__c.field-meta.xml
<CustomField>
    <fullName>JoinDate__c</fullName>
    <description>입사일자</description>
    <label>입사일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>직급</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>총괄사장</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>대표이사</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>센터장</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>감사</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>부사장</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>전무</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>상무</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>수석</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>이사</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>부장</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>책임</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>차장</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>과장</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>대리</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>선임</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>선임(수습)</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>사원</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>사원(수습)</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>인턴</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ListViewButton/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>구분</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>내부직원</fullName>
            </value>
            <value>
                <fullName>외부직원</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>사원 Object를 User Object간 Relationship 생성</inlineHelpText>
    <label>사용자 명</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/Employee_tr_test.cls
/************************************************************************************
* File Name   	    : Employee_tr TestClass
* Author	  		: Yeonlim
* Date				: 2023-12-18
* Modification Log
* ===================================================================================
* Ver      Date            Author          Modification
* ===================================================================================
* 1.0      2023-12-18      Yeonlim           Create
************************************************************************************/
@IsTest
public with sharing class Employee_tr_test {
    @TestSetup
    public static void testSetUp(){
        Profile objProfile = [SELECT Id, Name FROM Profile WHERE Name = 'Daeu Nextier Employee' LIMIT 1];
        User objUser = TestObjectCreator.objUser;
        objUser.LastName = 'testest';
        objUser.ProfileId = objProfile.Id;
        objUser.Position__c = '9';
        insert objUser;
    }

    @IsTest
    public static void Employee_tr_test() {
        User objUser = [SELECT id,name, LastName from User WHERE LastName = 'testest' LIMIT 1];

        Employee__c objEmployee = new Employee__c(
                Name  = 'TEST2',
                Type__c = '내부직원',
                User__c = objUser.Id,
                JoinDate__c = Date.today()
        );

        insert objEmployee;

        objEmployee.Position__c = '8';
        update objEmployee;

    }

    @IsTest
    public static void Employee_tr_test2() {

        User objUser = [
                SELECT Id, Name, LastName
                FROM User
                WHERE LastName = 'testest'
                LIMIT 1
        ];

        Employee__c objEmployee = new Employee__c(
                Name  = 'TEST2',
                Type__c = '내부직원',
                User__c = objUser.Id,
                JoinDate__c = Date.today()
        );
        insert objEmployee;

        User resultUser = [
                SELECT Id, LastName, EmployeeNumber
                FROM User
                WHERE LastName = 'testest'
                LIMIT 1
        ];
        Employee__c resultEmployee = [
                SELECT Id, EmployeeNo__c
                FROM Employee__c
                WHERE User__c = :objUser.Id
                LIMIT 1
        ];
        System.assertEquals(resultUser.EmployeeNumber, resultEmployee.EmployeeNo__c);
    }
}