PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>부서</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Departments</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/Holiday__c.object-meta.xml
<CustomObject>
    <label>Holiday</label>
    <nameField>
        <displayFormat>H-{0000}</displayFormat>
        <label>Holiday No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Holiday</relationshipLabel>
    <relationshipName>Holiday</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_Calculated__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Calculated__c</fullName>
    <description>대유넥스티어 사내 규칙에 맞는 연차여부 필드 수정으로 인한 예시 변경(수정일: 2021-12-31, 수정자: cj.sohn@daeunextier.com)
* 연차여부 수식 수정:
입사기준일인 경우, 입사일 + 365일
연차기준일(2020. 1. 1)인 경우, 입사일 다음년도 (연차 기준일)월 (연차 기준일)일 - 1

필드 설명
연차여부가 TRUE일 때, 15일 + 추가연차일수
연차여부가 FALSE일 때, 12 - (입사월 + 1)
ex)  오늘 2022년 3월 17일
       사원A: 입사일 2020-03-17 → 연차적용시작일(2020-12-31) → 연차여부 = TRUE → 15 + 0 개
       사원B: 입사일 2021-12-07 → 연차적용시작일(2021-12-31) → 연차여부 = TRUE → 15 + 0 개
       사원C: 입사일 2022-01-01 → 연차적용시작일(2022-12-31) → 연차여부 = FALSE → 12 - 1 = 11개
       사원D: 입사일 2022-01-04 → 연차적용시작일(2022-12-31) → 연차여부 = FALSE → 12 - (1 + 1) = 10개

휴가 연차일수 부여 개편으로 인한 수정(필드 수식 수정일: 2021-01-12, 필드 수정자: cj.sohn@daeunextier.com)
연차여부 수식 수정 이전 예시:
ex)  오늘 2021년 2월 4일
       사원A: 입사일 2020-12-07 → 연차적용시작일(2021-01-01) → 연차여부 = TRUE → 15 + 0 개
       사원B: 입사일 2021-01-01 → 연차적용시작일(2022-01-01) → 연차여부 = FALSE → 12 - 1 = 11개
       사원C: 입사일 2021-01-04 → 연차적용시작일(2022-01-01) → 연차여부 = FALSE → 12 - (1 + 1) = 10개</description>
    <formula>IF(
	Holiday_IsAnnualleave__c,
	15 + MIN(Holiday_Additionaldays__c , 10 ),
        IF(
                DAY(Holiday_JoinDate__c) = 1,
                IF(
	        	12 - (MONTH(Holiday_JoinDate__c) + 1) &lt; 0, 
	        	1,
	        	12 - MONTH(Holiday_JoinDate__c)
        	),
               	IF(
	        	12 - (MONTH(Holiday_JoinDate__c) + 1) &lt; 0, 
	        	0,
	        	12 - (MONTH(Holiday_JoinDate__c) + 1)
        	)
        )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>연차일수</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_GivenHolidays__c.field-meta.xml
<CustomField>
    <fullName>Holiday_GivenHolidays__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>추가적으로 부여된 연월차일수</inlineHelpText>
    <label>추가 부여 일수</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_IsAnnualleave__c.field-meta.xml
<CustomField>
    <fullName>Holiday_IsAnnualleave__c</fullName>
    <formula>Holiday_StartDate__c &lt;=  TODAY()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>연차여부</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_JoinDate__c.field-meta.xml
<CustomField>
    <fullName>Holiday_JoinDate__c</fullName>
    <label>입사일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_PeriodEnd__c.field-meta.xml
<CustomField>
    <fullName>Holiday_PeriodEnd__c</fullName>
    <description>수식 필드에 대한 상세설명 작성(필드 상세설명 수정일: 2021-12-23, 수정자: cj.sohn@daeunextier.com)
1. 입사일 기준여부가 TRUE일 때,
1-1) 금연도 입사월일이 오늘보다 작을 때, 금연도 입사월일 - 1 + 365
1-2) 금연도 입사월일이 오늘보다 크거나 같을 때, 금연도 입사월일 -1 + 0

ex) 오늘: 2021년 12월 23일
사원A: 입사일 2019-12-15 →  금연도 입사월일 (2021-12-15) → 연차만료일: 2022-12-15
사원B: 입사일 2020-12-28 → 금연도 입사월일 (2021-12-28) → 연차만료일: 2021-12-28
사원C: 입사일 2021-12-23 →  금연도 입사월일 (2021-12-23) → 연차만료일: 2022-12-22

2. 입사일 기준여부가 FALSE일 때,
2-1) 금연도 말일이 오늘보다 클 때, 전연도 말일 + 365
2-2) 금연도 말일이 오늘보다 작거나 같을 때, 전연도 말일 + 0 (가능성 0%)

ex) 오늘: 2021년 2월 4일, 금연도 말일: 2021년 12월 31일 → 연차만료일: 2021년 12월 31일

* 참고사항
Custom Setting(HolidaySetting__c)의 필드 및 값 정리 (2021-12-23 기준)
- 연차기준일(HoldayRuleDate__c): 2000. 1. 1
- 갱신일 이전 일수 차감여부(IsCeil__c): true
- 입사일 기준여부(JoinDateRule__c): false</description>
    <formula>IF(
    $Setup.HolidaySetting__c.JoinDateRule__c,
    DATE( YEAR(TODAY()), MONTH(Holiday_JoinDate__c), DAY(Holiday_JoinDate__c) ) - 1 +
    IF(
        DATE( YEAR(TODAY()), MONTH(Holiday_JoinDate__c), DAY(Holiday_JoinDate__c) ) &lt; TODAY(),
        365,
        0
    ),
    DATE( YEAR(TODAY()), MONTH($Setup.HolidaySetting__c.HoldayRuleDate__c ), DAY($Setup.HolidaySetting__c.HoldayRuleDate__c) ) - 1 +
    IF(
        DATE( YEAR(TODAY()), MONTH($Setup.HolidaySetting__c.HoldayRuleDate__c), DAY($Setup.HolidaySetting__c.HoldayRuleDate__c) ) &lt; TODAY(),
        365,
        0
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>연차만료일</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_Remain__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Remain__c</fullName>
    <description>4월1일 이전인 경우, 잔여일수=연차일수-사용일수+전년도 연차 잔여일수
3월31일 이후인 경우, 잔여일수=연차일수-사용일수

22.03.31
임시로 기준일을 12월 31일로 변경
변경전: TODAY() &lt;  DATE(YEAR(TODAY()), 4, 1)
변경후: TODAY() &lt;=  DATE(YEAR(TODAY()), 12, 31)</description>
    <formula>IF(
    TODAY() &lt;  DATE(YEAR(TODAY()), 4, 1),
    NULLVALUE( Holiday_Calculated__c , 0) -  NULLVALUE(Holiday_UseDays__c  , 0) +  Holiday_GivenHolidays__c + RemainOfLastYear__c ,
    NULLVALUE( Holiday_Calculated__c , 0) -  NULLVALUE(Holiday_UseDays__c  , 0) +  Holiday_GivenHolidays__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>전년도 잔여연차 사용을 임시로 올해 12월 31일까지 사용 가능하도록 변경되었습니다.</inlineHelpText>
    <label>잔여일수</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Holiday__c/fields/Holiday_UseDays__c.field-meta.xml
<CustomField>
    <fullName>Holiday_UseDays__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>올해 연월차 사용일수</inlineHelpText>
    <label>연월차 사용일수</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/HolidayAction__c.object-meta.xml
<CustomObject>
    <description>HolidayAction__c</description>
    <label>휴가신청</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Departments</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>휴가신청</relationshipLabel>
    <relationshipName>HolidayActionV4Zc</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Date1__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Date1__c</fullName>
    <label>Date1</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Date2__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Date2__c</fullName>
    <label>Date2</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Date3__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Date3__c</fullName>
    <label>Date3</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Date4__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Date4__c</fullName>
    <label>Date4</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Date5__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Date5__c</fullName>
    <label>Date5</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Days__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Days__c</fullName>
    <inlineHelpText>Women&apos;s Holiday 1.
Alternative Holiday 0.
Other Holidays from 1 to 5.</inlineHelpText>
    <label>Days</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Description__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_HalfdayTime__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_HalfdayTime__c</fullName>
    <label>Half-day leave Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Type__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Annual Holiday</fullName>
                <label>연차</label>
            </value>
            <value>
                <fullName>Half-day Leave</fullName>
                <label>반차</label>
            </value>
            <value>
                <fullName>Reward Holiday</fullName>
                <label>대체휴가</label>
            </value>
            <value>
                <fullName>Reward Half-Holiday</fullName>
                <label>대체휴가(반차)</label>
            </value>
            <value>
                <fullName>Public Works</fullName>
                <label>공가(공무)</label>
            </value>
            <value>
                <fullName>Family Leave</fullName>
                <label>경조휴가</label>
            </value>
            <value>
                <fullName>Sick Leave</fullName>
                <label>병가(무급)</label>
            </value>
            <value>
                <fullName>Women Holiday</fullName>
                <label>생리휴가</label>
            </value>
            <value>
                <fullName>가족돌봄휴가</fullName>
            </value>
            <value>
                <fullName>출산휴가</fullName>
            </value>
            <value>
                <fullName>휴직</fullName>
            </value>
            <value>
                <fullName>육아휴직</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Project_HolidayAction</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/HolidayUtil.cls
public with sharing class HolidayUtil{
    public static void createEvent(HolidayAction__c hlAct){
        date date1 = hlAct.HolidayAction_Date1__c;
        date date2 = hlAct.HolidayAction_Date2__c;
        date date3 = hlAct.HolidayAction_Date3__c;
        date date4 = hlAct.HolidayAction_Date4__c;
        date date5 = hlAct.HolidayAction_Date5__c;
        Event e;
        if(hlAct.HolidayAction_Days__c >= 1){
            e = setEvent(hlAct,date1);
            insert e;
        }
        if(hlAct.HolidayAction_Days__c > 1){
            e = setEvent(hlAct,date2);
            insert e;
        }
        if(hlAct.HolidayAction_Days__c > 2){
            e = setEvent(hlAct,date3);
            insert e;
        }
        if(hlAct.HolidayAction_Days__c > 3){
            e = setEvent(hlAct,date4);
            insert e;
        }
        if(hlAct.HolidayAction_Days__c > 4){
            e = setEvent(hlAct,date5);
            insert e;
        }
        shareFinance(hlAct);
    }
    
    public static Event setEvent(HolidayAction__c hlAct,date dt){
        string userId = hlAct.OwnerId;
        string actId = hlAct.Id;
        string subject = hlAct.Name;
        Event e = new Event();
        e.OwnerId = hlAct.OwnerId;
        e.ActivityDate = dt;
        e.EndDateTime = dt;
        e.StartDateTime = dt;
        e.IsAllDayEvent = true;        
        e.Subject = 'On holiday';
        e.ShowAs = 'OutOfOffice';
        if(hlAct.HolidayAction_Type__c =='Half-day Leave'){
            e.IsAllDayEvent = false;
            e.Subject = 'Half-day Leave';
            if(hlAct.HolidayAction_HalfdayTime__c == 'AM')
                e.EndDateTime = e.EndDateTime.addHours(3);
            else{
                e.StartDateTime = e.EndDateTime.addHours(3);
                e.ActivityDateTime = e.EndDateTime.addHours(3);
                e.ActivityDate = e.ActivityDateTime.date();
                e.EndDateTime = e.EndDateTime.addHours(9);            
            }
        }
        e.Description = hlAct.HolidayAction_Description__c;
        e.WhatId = hlAct.Id;
        
        return e;
    }
    
    public static boolean sendEmail(string pType, User pUsr, Holiday__c pHld){
        try{
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            String[] toAddresses = new string[]{pUsr.Email};
            string subject = '';
            string msgBody =  pUsr.Name + '님 안녕하세요. \r\n\r\n';
            if(pHld.Holiday_IsAnnualleave__c)
                subject = '연차';
            else
                subject = '월차';
            if(pType == 'Info'){
                msgBody += '귀하의 '+ subject + '내역에 대한 안내 메일입니다. \r\n';
                subject += ' 내역 안내';
            }
            else if(pType == '1st'){
                subject += ' 사용 촉진 안내';
                msgBody += '근로기준법 제60조제1항·제3항 및 제4항에 따른 유급휴가의 사용 촉진 안내 메일입니다. \r\n';
                msgBody += '10일 내로 서면을 통해 사용 계획을 회신 부탁드립니다. \r\n';
            }
            else if(pType == '2nd'){
                subject += ' 소멸 안내';
                msgBody += '근로기준법 제60조제7항에 따른 유급휴가의 소멸 안내 메일입니다. \r\n';
                msgBody += '사용기한까지 사용하지 않은 휴가는 소멸되오니 계획 등록 부탁드립니다. \r\n';
                msgBody += '단 프로젝트 일정등의 이유로 사용이 불가피한 경우 기한 만료 후 관리자에게 문의 하시기 바랍니다. \r\n';
            }
            msgBody += '아래의 휴가 관련 내역을 휴가 사용에 참고하시기 바랍니다. \r\n\r\n';
            msgBody += '입사일자 : ' + date.valueOf(pHld.Holiday_JoinDate__c).format() + '\r\n';
            msgBody += '사용기한 : ' + date.valueOf(pHld.Holiday_PeriodEnd__c != null ? pHld.Holiday_PeriodEnd__c : Date.newInstance(Date.today().year(), 12, 31)).format() + '\r\n';
            msgBody += '휴가일수 : ' + string.valueOf(pHld.Holiday_Calculated__c) + '일\r\n';
            msgBody += '추가일수 : ' + string.valueOf(pHld.Holiday_GivenHolidays__c) + '일\r\n';
            msgBody += '사용일수 : ' + string.valueOf(pHld.Holiday_UseDays__c) + '일\r\n';
            msgBody += '잔여일수 : ' + string.valueOf(pHld.Holiday_Remain__c) + '일\r\n';
            msgBody += '\r\n';
            msgBody += '자세한 내역은 ' + URL.getSalesforceBaseUrl().toExternalForm() + '/_ui/core/userprofile/UserProfilePage?tab=My_Holiday_Info 에서 확인 가능합니다.\r\n';
            msgBody += '귀하의 노고에 감사드립니다.\r\n\r\n';
            msgBody += 'DaeU NexTier Inc.\r\n';
            msgBody += '\r\n';
            msgBody += 'Tel: 82-2-553-9981 | Email: admin@daeunextier.com\r\n';
            msgBody += 'Web: www.daeunextier.com | Facebook: www.facebook.com/daeunextier\r\n';
            msgBody += 'YouTube: 쉽고 빠르고 합리적인 가격의 IT 서비스';
            email.setSubject(subject);
            email.setToAddresses(toAddresses);
            email.setPlainTextBody(msgBody );
            
            if(!Test.isRunningTest()) Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
        }catch(Exception e){
            return false;
        }
        return true;
    }

    /**
     *  @author            : cj.sohn@daeunextier.com
     *  @description       : 휴가 최종 승인 안내 메일 발송
     *                      [프로젝트 투입 직원] → 부대표님, 전무님, 해당 사업부장, 관리직원
                            [본사근무직원] → 대표님, 부대표님, 전무님, 전사업부장, 관리직원
                            [영업팀] → 대표님, 부대표님, 전무님, 전사업부장, 관리직원
                            [임원 및 PM] → 대표님, 전사업부장, 관리직원
     *  @last modified on  : 2021-01-18
     **/
    public static boolean sendEmailForConfirmedHoliday(List<Employee__c> fEmailRecipients, Project__c fProject, HolidayAction__c fHolidayAction, Employee__c fEmployee){
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        String[] to = new String[]{};
        String[] cc = new String[]{};

        //  부서별 사원 정리
        Map<String, List<Employee__c>> employeesByDepartments = new Map<String, List<Employee__c>>();
        for(Employee__c employee : fEmailRecipients){
            if(employeesByDepartments.containsKey(employee.Department__c)){
                employeesByDepartments.get(employee.Department__c).add(employee);
            }else{
                employeesByDepartments.put(employee.Department__c, new List<Employee__c>());
                employeesByDepartments.get(employee.Department__c).add(employee);
            }
        }
        if(fHolidayAction.Project__c != null){
            if(fHolidayAction.Position__c.equals('프로젝트 팀원') && (fEmployee != null && fEmployee.Position__c != '임원')){
                //  [프로젝트 투입 직원] → 부대표님, 전무님, 해당 사업부장, 관리직원
                List<Employee__c> recipients = (employeesByDepartments.get(fProject.Business__c) == null ? new List<Employee__c>() : employeesByDepartments.get(fProject.Business__c));
                //  부대표님 + 관리직원
                if(employeesByDepartments.get('MGMT') != null && employeesByDepartments.get('MGMT').size() > 0){
                    recipients.addAll(employeesByDepartments.get('MGMT'));
                }
                //  이응도 전무님
                if(employeesByDepartments.get('General Manager') != null && employeesByDepartments.get('General Manager').size() > 0){
                    for(Employee__c objEmployee : employeesByDepartments.get('General Manager')){
                        if(objEmployee.Name == '이응도')
                            recipients.add(objEmployee);
                    }
                }
                //  해당 사업부장
                for(Employee__c employee: recipients){
                    to.add(employee.Email__c);
                }
            }else{
                //  [임원 및 PM] → 대표님, 전사업부장, 관리직원
                for(Employee__c employee : fEmailRecipients){
                    to.add(employee.Email__c);
                }
            }
        }else{
            //  [본사근무직원] → 대표님, 부대표님, 전무님, 전사업부장, 관리직원
            //  [영업팀] → 대표님, 부대표님, 전무님, 전사업부장, 관리직원
            for(Employee__c employee : fEmailRecipients){
                to.add(employee.Email__c);
            }
        }
        email.setToAddresses(to);
        email.setSubject('[' + fHolidayAction.HolidayAction_UserName__c + '] 휴가 사용 안내');
        String body = fHolidayAction.HolidayAction_UserName__c + ' 휴가 안내드립니다.<br/>';
        body += '휴가 기간(총 ' + fHolidayAction.HolidayAction_Days__c +'일): ' + fHolidayAction.Holiday_Date_Detail__c + '<br/>';
        body += '휴가 사유: ' + fHolidayAction.Name + (fHolidayAction.HolidayAction_Description__c != null ? '(' + fHolidayAction.HolidayAction_Description__c + ')<br/>' : '<br/>');
        body += '승인자: ' + fHolidayAction.FirstHolidayRequest__r.Name + '<br/>';
        if(fProject != null){
            body += '진행중인 프로젝트: ' + fProject.Name + '<br/>';
        }
        body += '<hr/>';
        body += '(주)대유넥스티어 | Tel: 82-2-553-9981<br/>';
        body += 'Web: www.daeunextier.com | Facebook: www.facebook.com/daeunextier';
        email.setHtmlBody(body);

        OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where Address = 'admin@daeunextier.com'];
        if ( owea.size() > 0 ) {
            email.setOrgWideEmailAddressId(owea.get(0).Id);
        }

        try{
            if(!Test.isRunningTest()) Messaging.sendEmail(new Messaging.SingleEmailMessage[] { email });
        }catch(exception e){
            return false;
        }
        return true;
    }
    
    public static boolean shareFinance(HolidayAction__c hlAct){
        try{
            hlAct = [SELECT Owner.Name, HolidayAction_Type__c, HolidayAction_Days__c, HolidayAction_Date1__c, HolidayAction_Date2__c,
                            HolidayAction_Date3__c, HolidayAction_Date4__c, HolidayAction_Date5__c, HolidayAction_HalfdayTime__c
                       FROM HolidayAction__c 
                      WHERE Id = :hlAct.Id];
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            HolidayShare__C hs = HolidayShare__C.getOrgDefaults();
            String[] toAddresses = new string[]{hs.Addresses__c};
            string subject = '[휴가사용] - '+ hlAct.Owner.Name;
            string msgBody = hs.Name__c + '님 안녕하세요. \r\n\r\n';
            msgBody += hlAct.Owner.Name + '님의 휴가 사용내역 공유 드립니다.\r\n';
            msgBody += '휴가 유형 : ' + hlAct.HolidayAction_Type__c + '\r\n';
            msgBody += '휴가 일수 : ' + (hlAct.HolidayAction_Type__c=='Half-day Leave' ? '0.5' : String.valueOf(hlAct.HolidayAction_Days__c))+ '일\r\n';
            
            if(hlAct.HolidayAction_Days__c >= 1)
                msgBody += '휴가 일자 : ' + hlAct.HolidayAction_Date1__c.format() + 
                           (hlAct.HolidayAction_Type__c=='Half-day Leave' ? ' ' + String.valueOf(hlAct.HolidayAction_HalfdayTime__c) : '') + '\r\n';
            if(hlAct.HolidayAction_Days__c > 1)
                msgBody += '휴가 일자 : ' + hlAct.HolidayAction_Date2__c + '\r\n';
            if(hlAct.HolidayAction_Days__c > 2)
                msgBody += '휴가 일자 : ' + hlAct.HolidayAction_Date3__c + '\r\n';
            if(hlAct.HolidayAction_Days__c > 3)
                msgBody += '휴가 일자 : ' + hlAct.HolidayAction_Date4__c + '\r\n';
            if(hlAct.HolidayAction_Days__c > 4)
                msgBody += '휴가 일자 : ' + hlAct.HolidayAction_Date5__c + '\r\n';
                
            msgBody += '\r\n';            
            msgBody += '자세한 내역은 ' + URL.getSalesforceBaseUrl().toExternalForm() + '/' + hlAct.Id + ' 에서 확인 가능합니다.\r\n';
            msgBody += '고맙습니다.\r\n\r\n';
            msgBody += 'DaeU NexTier Inc.\r\n';
            msgBody += '\r\n';
            msgBody += 'Tel: 82-2-553-9981 | Email: admin@daeunextier.com\r\n';
            msgBody += 'Web: www.daeunextier.com | Facebook: www.facebook.com/daeunextier\r\n';
            msgBody += 'YouTube: 쉽고 빠르고 합리적인 가격의 IT 서비스';
            email.setSubject(subject);
            email.setToAddresses(toAddresses);
            email.setPlainTextBody(msgBody );
            
            if(!Test.isRunningTest()) Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
        }catch(Exception e){
            return false;
        }
        return true;
    }
}