DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/SignaturePhotoId__c.field-meta.xml
<CustomField>
    <fullName>SignaturePhotoId__c</fullName>
    <label>SignaturePhotoId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Interview__c/Interview__c.object-meta.xml
<CustomObject>
    <description>신입 대상으로 진행한 면담일지 개체</description>
    <label>면담일지</label>
    <nameField>
        <displayFormat>No.{YYYY}-{MM}-{DD}/{00}</displayFormat>
        <label>면담일지</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Interview__c/fields/Intv_Date__c.field-meta.xml
<CustomField>
    <fullName>Intv_Date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>면담이 진행된 날짜를 기록</description>
    <label>면담 일시</label>
    <type>DateTime</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Interview__c/fields/Intv_Mentee__c.field-meta.xml
<CustomField>
    <fullName>Intv_Mentee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>면담 대상자인 멘티</description>
    <label>사원</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>면담일지 (피면담자 명)</relationshipLabel>
    <relationshipName>Intv_Mentee</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Interview__c/fields/Intv_Mentor__c.field-meta.xml
<CustomField>
    <fullName>Intv_Mentor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>면담을 진행하고 레코드를 작성한 멘토</description>
    <inlineHelpText>빈 값일 때 현재 사용자가 자동으로 등록됩니다.</inlineHelpText>
    <label>담당 멘토</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>면담일지</relationshipLabel>
    <relationshipName>Intv_Mentor</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Interview__c/fields/Intv_Name__c.field-meta.xml
<CustomField>
    <fullName>Intv_Name__c</fullName>
    <label>면담 일지</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Interview__c/fields/Intv_Others__c.field-meta.xml
<CustomField>
    <fullName>Intv_Others__c</fullName>
    <label>기 타</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Interview__c/fields/Intv_Training__c.field-meta.xml
<CustomField>
    <fullName>Intv_Training__c</fullName>
    <label>훈련 관련</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Interview__c/fields/Intv_Work__c.field-meta.xml
<CustomField>
    <fullName>Intv_Work__c</fullName>
    <label>근로 관련</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/classes/getInterviewListController.cls
public with sharing class getInterviewListController {
    public List<Map<String, Object>> listMapInterviews { get; set; }

    public getInterviewListController() {
        String recordIds = ApexPages.currentPage().GetParameters().get('recordId');

        List<String> listRecordsId = recordIds.split(',');
        //System.debug('recordIds: ' + recordIds);

        List<Interview__c> listInterviews = [
            SELECT Id, Intv_Name__c, Intv_Training__c, Intv_Work__c, Intv_Others__c, Intv_Mentor__r.SignaturePhotoId__c,
                   Intv_Mentor__r.Name, Intv_Mentee__r.Name, Intv_Date__c
            FROM Interview__c
            WHERE Id IN :listRecordsId
            ORDER BY Intv_Mentee__r.Name,Intv_Date__c  
        ];

        listMapInterviews = new List<Map<String, Object>>();

        for (Interview__c objInterview : listInterviews) {
            Map<String, Object> mapInterviews = new Map<String, Object>();
            mapInterviews.put('Id', objInterview.Id);
            mapInterviews.put('Name', objInterview.Intv_Name__c);
            mapInterviews.put('Intv_Training', objInterview.Intv_Training__c!=null? objInterview.Intv_Training__c:'내용 없음');
            mapInterviews.put('Intv_Work', objInterview.Intv_Work__c!=null ?objInterview.Intv_Work__c: '내용 없음');
            mapInterviews.put('Intv_Others', objInterview.Intv_Others__c!=null ?objInterview.Intv_Others__c: '내용 없음');
            mapInterviews.put('Intv_Mentor_Name', objInterview.Intv_Mentor__r.Name);
            mapInterviews.put('Intv_Mentee_Name', objInterview.Intv_Mentee__r.Name);
            mapInterviews.put('Intv_Mentor_SignaturePhotoId', objInterview.Intv_Mentor__r.SignaturePhotoId__c!=null ? objInterview.Intv_Mentor__r.SignaturePhotoId__c: '');

            

            // 날짜 변환
            if (objInterview.Intv_Date__c != null) {
                DateTime localDateTime = objInterview.Intv_Date__c.addHours(9); // 시간대 변환 (한국 표준시)
                String formattedDate = localDateTime.format('yyyy. MM. d a hh:mm', 'ko');
                mapInterviews.put('Intv_Date', formattedDate);
            } else {
                mapInterviews.put('Intv_Date', '날짜 없음');
            }

            listMapInterviews.add(mapInterviews);
        }

        //System.debug('listMapInterviews: ' + listMapInterviews);
    }

    @AuraEnabled
    public static String generatePDF(String vfPageUrl) {
        try {
            //테스트 class를 위함 (Test.isRunningTest() 활용)
            if (Test.isRunningTest()) {
                return EncodingUtil.base64Encode(Blob.valueOf('Mock PDF Content'));
            }

            PageReference pdfPage = new PageReference(vfPageUrl);
            Blob pdfBlob = pdfPage.getContentAsPDF();
            

            // Base64로 변환하여 반환
            return EncodingUtil.base64Encode(pdfBlob);

        } catch (Exception e) {
            throw new AuraHandledException('PDF 생성 실패: ' + e.getMessage());
        }
    }

    @AuraEnabled
    public static Boolean checkRecordType(String listSelectId){
        System.debug('listSeectId: '+listSelectId);

            List<String> listRecordsId=new List<String>();
            listRecordsId=listSelectId.split(',');
            System.debug('listRecordsId: '+listRecordsId);
            
            List<Interview__c> listInterviews=new List<Interview__c>();
            listInterviews=[
                SELECT RecordType.Name
                FROM Interview__c
                WHERE Id IN :listRecordsId
            ];

            for(Interview__c objInterview:listInterviews){
                if(objInterview.RecordType.Name!='IPP'){
                    return false;
                }
            }
            return true;
    }

    @AuraEnabled
    public static Boolean checkMonth(String listSelectId){
        List<String> listRecordsId=new List<String>();
            listRecordsId=listSelectId.split(',');

            // listRecordsId.add('a3lF7000000WEuIIAW');
            // listRecordsId.add('a3lF7000000WEuwIAG');
            // listRecordsId.add('a3lF7000000WEsqIAG');
            List<Interview__c> listInterviews=new List<Interview__c>();
            listInterviews=[
                SELECT Intv_Date__c 
                FROM Interview__c 
                WHERE Id IN :listRecordsId
            ];

            Integer month=listInterviews[0].Intv_Date__c.Month();
            for(Interview__c objInterview:listInterviews){
                if(month!=objInterview.Intv_Date__c.Month()){
                    // System.debug('month: '+month);
                    // System.debug('objMonth: '+objInterview.Intv_Date__c.Month());
                    return false;
                }
            }

            return true;
    }

}