DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/SignaturePhotoId__c.field-meta.xml
<CustomField>
    <fullName>SignaturePhotoId__c</fullName>
    <label>SignaturePhotoId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/classes/PrintMentorController.cls
public with sharing class PrintMentorController {

    // public List<String> imgUrls { get; set; }

    // public PrintMentorController() {
    //     Id recordId = ApexPages.currentPage().GetParameters().get('recordId');

    //     //선택한 일지의 담당 멘토에 해당하는 ContentDocumentId 조회
    //     Employee__c objEmp=new Employee__c();
    //     objEmp=[
    //         SELECT SignaturePhotoId__c
    //         FROM Employee__c
    //         WHERE Id = :recordId
    //     ];

    //     // 이미지 URL 생성
    //     imgUrls = '/sfc/servlet.shepherd/version/download/' + objEmp.SignaturePhotoId__c;
    // }
}