ListViewButton/PrintPdfAndSave/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/MainRole__c.field-meta.xml
<CustomField>
    <fullName>MainRole__c</fullName>
    <label>직무</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Management</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ListViewButton/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/MentorUser__c.field-meta.xml
<CustomField>
    <fullName>MentorUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>담당멘토 명</label>
    <referenceTo>User</referenceTo>
    <relationshipName>MentorUser</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>직급</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>총괄사장</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>대표이사</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>센터장</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>감사</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>부사장</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>전무</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>상무</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>수석</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>이사</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>부장</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>책임</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>차장</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>과장</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>대리</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>선임</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>선임(수습)</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>사원</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>사원(수습)</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>인턴</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Interview__c/Interview__c.object-meta.xml
<CustomObject>
    <description>신입 대상으로 진행한 면담일지 개체</description>
    <label>면담일지</label>
    <nameField>
        <displayFormat>No.{YYYY}-{MM}-{DD}/{00}</displayFormat>
        <label>면담일지</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Interview__c/fields/Intv_Date__c.field-meta.xml
<CustomField>
    <fullName>Intv_Date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>면담이 진행된 날짜를 기록</description>
    <label>면담 일시</label>
    <type>DateTime</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Interview__c/fields/Intv_Mentee__c.field-meta.xml
<CustomField>
    <fullName>Intv_Mentee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>면담 대상자인 멘티</description>
    <label>사원</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>면담일지 (피면담자 명)</relationshipLabel>
    <relationshipName>Intv_Mentee</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Interview__c/fields/Intv_Mentor__c.field-meta.xml
<CustomField>
    <fullName>Intv_Mentor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>면담을 진행하고 레코드를 작성한 멘토</description>
    <inlineHelpText>빈 값일 때 현재 사용자가 자동으로 등록됩니다.</inlineHelpText>
    <label>담당 멘토</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>면담일지</relationshipLabel>
    <relationshipName>Intv_Mentor</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Interview__c/fields/Intv_Name__c.field-meta.xml
<CustomField>
    <fullName>Intv_Name__c</fullName>
    <label>면담 일지</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

ListViewButton/PrintPdfAndSave/force-app/main/default/classes/InterviewName_tr_test2.cls
@isTest
public class InterviewName_tr_test2 {
    @TestSetup
    static void setupData(){
        User userThis=[
            SELECT Id, Name, Profile.Name, UserRole.Name
            FROM User
            WHERE Id = :UserInfo.getUserId()
        ];
        
        System.runAs(userThis){
            // Create a test user
            Profile p = [SELECT Id FROM Profile WHERE Name='Standard User' LIMIT 1];
            UserRole r = [SELECT Id FROM UserRole WHERE Name='Platform Member'];

            User userMentor=new User(
                alias = 'mentor', email='jsmith@acme.com', 
                emailencodingkey='UTF-8', lastname='test1', 
                languagelocalekey='en_US', 
                localesidkey='en_US', profileid = p.Id, userroleid = r.Id,
                timezonesidkey='America/Los_Angeles', 
                username='test12@test21.com');
                
                insert userMentor;

            User userNew=new User(
                alias = 'new', email='jsmith@acme.com', 
                emailencodingkey='UTF-8', lastname='test2', 
                languagelocalekey='en_US', 
                localesidkey='en_US', profileid = p.Id, userroleid = r.Id,
                timezonesidkey='America/Los_Angeles', 
                username='test21@test12.com');

                insert userNew;
            
                //employee 생성
            Employee__c empMentor = new Employee__c(
                Name = 'Test Employee1',
                OwnerId = userMentor.Id,
                MainRole__c = 'Developer',
                Position__c = '12'
            );
            insert empMentor;

            Employee__c empNew=new Employee__c(
                Name = 'Test Employee2',
                OwnerId = userNew.Id,
                MainRole__c = 'Developer',
                Position__c = '9',
                MentorUser__c=empMentor.OwnerId
            );
            insert empNew;

            Interview__c objInt=new Interview__c();
            objInt.Intv_Date__c=Date.today();
            objInt.Intv_Mentor__c = empMentor.Id;
            objInt.Intv_Mentee__c=empNew.Id;
            insert objInt;
        }
    }

    @isTest
    static void testbeforeInsert() {
        Employee__c empMentee = [SELECT Name FROM Employee__c WHERE Name = 'Test Employee2'];
        Employee__c empMentor = [SELECT Name FROM Employee__c WHERE Name = 'Test Employee1'];

        Test.startTest();
        Interview__c newInterview = new Interview__c();
        newInterview.Intv_Date__c = Date.today().addDays(-1);
        newInterview.Intv_Mentee__c = empMentee.Id;
        newInterview.Intv_Mentor__c = empMentor.Id;
        insert newInterview;
        Test.stopTest();
    }

    @isTest
    static void testafterInsert() {
        Employee__c empMentee = [SELECT Name FROM Employee__c WHERE Name = 'Test Employee2'];
        Employee__c empMentor = [SELECT Name FROM Employee__c WHERE Name = 'Test Employee1'];

        Test.startTest();
        Interview__c newInterview = new Interview__c();
        newInterview.Intv_Date__c = Date.today().addDays(-1);
        newInterview.Intv_Mentee__c = empMentee.Id;
        newInterview.Intv_Mentor__c = empMentor.Id;
        insert newInterview;
        Test.stopTest();
    }

    @isTest
    static void testafterUpdate() {
        Employee__c empMentee = [SELECT Name FROM Employee__c WHERE Name = 'Test Employee2'];
        Employee__c empMentor = [SELECT Name FROM Employee__c WHERE Name = 'Test Employee1'];
        Interview__c newInterview = new Interview__c();
        newInterview.Intv_Date__c = Date.today().addDays(-1);
        newInterview.Intv_Mentee__c = empMentee.Id;
        newInterview.Intv_Mentor__c = empMentor.Id;
        insert newInterview;

        Test.startTest();
        Interview__c updateInterview=[
            SELECT Intv_Name__c, Intv_Mentee__c,Intv_Date__c, Intv_Mentor__c
            FROM Interview__c 
            WHERE Id = :newInterview.Id];
            updateInterview.Intv_Date__c = Date.today().addDays(-2);
            update updateInterview;
        Test.stopTest();
    }

    @isTest
    static void testafterDelete() {
        Employee__c empMentee = [SELECT Name FROM Employee__c WHERE Name = 'Test Employee2'];
        Employee__c empMentor = [SELECT Name FROM Employee__c WHERE Name = 'Test Employee1'];
        Interview__c newInterview = new Interview__c();
        newInterview.Intv_Date__c = Date.today().addDays(-1);
        newInterview.Intv_Mentee__c = empMentee.Id;
        newInterview.Intv_Mentor__c = empMentor.Id;
        insert newInterview;

        Test.startTest();
        Interview__c deleteInterview=[
            SELECT Intv_Name__c, Intv_Mentee__c,Intv_Date__c, Intv_Mentor__c
            FROM Interview__c 
            WHERE Id = :newInterview.Id];
            delete deleteInterview;
        Test.stopTest();
    }
}