PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/QuoteItem__c.object-meta.xml
<CustomObject>
    <description>견적을 구성하는 Consulting 자원 또는 License 목록</description>
    <label>견적 상세</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_ConsultAmount__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_ConsultAmount__c</fullName>
    <formula>IF( QuoteItem_FOC__c ,0, 
IF(QuoteItem_ConsultDiscountedPrice__c == 0 , QuoteItem_ConsultListPrice__c,QuoteItem_ConsultDiscountedPrice__c) * QuoteItem_ConsultManMonths__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>할인후 금액</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_ConsultDiscountAmount__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_ConsultDiscountAmount__c</fullName>
    <formula>QuoteItem_ConsultListAmount__c - QuoteItem_ConsultAmount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>할인액</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_ConsultDiscountedPrice__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_ConsultDiscountedPrice__c</fullName>
    <label>할인 후 단가</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_ConsultLevel__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_ConsultLevel__c</fullName>
    <description>투입인력의 등급을 견적서에 표기를 원할 경우를 대비한 항목</description>
    <inlineHelpText>견적서에 투입인력 등급 표기 요청을 받은 경우 선택하십시요.</inlineHelpText>
    <label>등급</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chief</fullName>
            </value>
            <value>
                <fullName>Principal</fullName>
            </value>
            <value>
                <fullName>Supervisor</fullName>
                <default>true</default>
                <label>Supervisor</label>
            </value>
            <value>
                <fullName>특급</fullName>
            </value>
            <value>
                <fullName>고급</fullName>
            </value>
            <value>
                <fullName>중급</fullName>
            </value>
            <value>
                <fullName>초급</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
            <value>
                <fullName>Intermediate</fullName>
            </value>
            <value>
                <fullName>Junior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_ConsultListAmount__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_ConsultListAmount__c</fullName>
    <formula>IF(QuoteItem_FOC__c,0, QuoteItem_ConsultListPrice__c * QuoteItem_ConsultManMonths__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>표준금액</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_ConsultListPrice__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_ConsultListPrice__c</fullName>
    <inlineHelpText>SFDC Consultant	Chief	   26,000,000 
SFDC Consultant	Principal	   22,000,000 
SFDC Consultant	Supervisor  16,000,000 
SFDC Developer	Chief	   22,000,000 
SFDC Developer	Principal	   16,000,000 
SFDC Developer	Supervisor  12,000,000</inlineHelpText>
    <label>표준단가 M/M</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_ConsultManMonths__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_ConsultManMonths__c</fullName>
    <label>투입 M/M</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_ConsultName__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_ConsultName__c</fullName>
    <defaultValue>&apos;TBD&apos;</defaultValue>
    <label>이름</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_ConsultRemark__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_ConsultRemark__c</fullName>
    <label>비고</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_ConsultType__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_ConsultType__c</fullName>
    <description>투입인력의 구분</description>
    <inlineHelpText>투입인력이 여러 역할을 담당한 경우 다중 선택하십시요.</inlineHelpText>
    <label>인력구분</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Business Leader</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Project Leader</fullName>
            </value>
            <value>
                <fullName>Business Analyst</fullName>
            </value>
            <value>
                <fullName>SFDC Administrator</fullName>
            </value>
            <value>
                <fullName>SFDC Platform Developer</fullName>
            </value>
            <value>
                <fullName>SFDC Consultant</fullName>
            </value>
            <value>
                <fullName>SFDC Pardot Consultant</fullName>
            </value>
            <value>
                <fullName>SFDC Sales Cloud Consultant</fullName>
            </value>
            <value>
                <fullName>SFDC Service Cloud Consultant</fullName>
            </value>
            <value>
                <fullName>SFDC Marketing Cloud Consultant</fullName>
            </value>
            <value>
                <fullName>SFDC Field Service Lightning Consultant</fullName>
            </value>
            <value>
                <fullName>SFDC System Architect</fullName>
            </value>
            <value>
                <fullName>SFDC Technical Architect</fullName>
            </value>
            <value>
                <fullName>SFDC Application Architect</fullName>
            </value>
            <value>
                <fullName>I/F Specialist</fullName>
            </value>
            <value>
                <fullName>Migration Expert</fullName>
            </value>
            <value>
                <fullName>Front-end Developer</fullName>
            </value>
            <value>
                <fullName>Mobile Developer</fullName>
            </value>
            <value>
                <fullName>App Developer</fullName>
            </value>
            <value>
                <fullName>Web Publisher</fullName>
            </value>
            <value>
                <fullName>Web Designer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_LicenseAmount__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_LicenseAmount__c</fullName>
    <formula>NULLVALUE(QuoteItem_LicenseDiscountedPriceYear__c, QuoteItem_LicenseListPriceYear__c) * QuoteItem_LicenseNumberOfUser__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>할인 후 금액(년)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_LicenseDiscountAmount__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_LicenseDiscountAmount__c</fullName>
    <formula>QuoteItem_LicenseListAmount__c - QuoteItem_LicenseAmount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>할인액(년)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_LicenseDiscountedPrice__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_LicenseDiscountedPrice__c</fullName>
    <label>할인사용료(월)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_LicenseDiscountedPriceYear__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_LicenseDiscountedPriceYear__c</fullName>
    <formula>IF(QuoteItem_LicenseDiscountedPrice__c==0, QuoteItem_LicenseListPrice__c ,QuoteItem_LicenseDiscountedPrice__c) * 12</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>사용료(년)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_LicenseListAmount__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_LicenseListAmount__c</fullName>
    <formula>QuoteItem_LicenseListPriceYear__c * QuoteItem_LicenseNumberOfUser__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>표준금액(년)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_LicenseListPrice__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_LicenseListPrice__c</fullName>
    <label>표준사용료(월)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_LicenseListPriceYear__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_LicenseListPriceYear__c</fullName>
    <formula>QuoteItem_LicenseListPrice__c * 12</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>표준사용료(년)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_LicenseNumberOfUser__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_LicenseNumberOfUser__c</fullName>
    <label>사용자</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_LicenseRemark__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_LicenseRemark__c</fullName>
    <label>비고</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_LicenseType__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_LicenseType__c</fullName>
    <label>라이선스 구분</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_Quote__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_Quote__c</fullName>
    <description>견적 마스터</description>
    <label>견적</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>견적 상세</relationshipLabel>
    <relationshipName>QuoteItem</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_SortOrder__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_SortOrder__c</fullName>
    <inlineHelpText>구분,등급,단가 순서보다 우선 적용되는 표기 순번입니다.</inlineHelpText>
    <label>순서</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_TrainingCount__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_TrainingCount__c</fullName>
    <label>수강인원</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_TrainingDescription__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_TrainingDescription__c</fullName>
    <label>상세항목</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_TrainingRemark__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_TrainingRemark__c</fullName>
    <label>비고</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_TrainingSalesAmount__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_TrainingSalesAmount__c</fullName>
    <formula>QuoteItem_TrainingSalesPrice__c *  QuoteItem_TrainingCount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>할인 후 수강료</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_TrainingSalesPrice__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_TrainingSalesPrice__c</fullName>
    <label>할인 후 단가</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/QuoteItem__c/fields/QuoteItem_TrainingStandardPrice__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem_TrainingStandardPrice__c</fullName>
    <label>표준수강료</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/QuoteRenderController.cls
public class QuoteRenderController{
    public List<QuoteItem__c> consultLst {get;set;}
    public List<QuoteItem__c> licenseLst {get;set;}
    public List<QuoteItem__c> trainingLst {get;set;}
    public Boolean hasCon {get;set;}
    public Boolean hasLis {get;set;}
    public Boolean hasTrn {get;set;}
    public String extUrl {get;set;}
    
    public QuoteRenderController(ApexPages.StandardController stdCtrl){
        String qId = stdCtrl.getId();
        extUrl = URL.getSalesforceBaseUrl().toExternalForm();
        consultLst = new List<QuoteItem__c>();
        licenseLst = new List<QuoteItem__c>();
        trainingLst = new List<QuoteItem__c>();
        hasCon = false;
        hasLis = false;
        hasTrn = false;
        List<QuoteItem__c> qiLst = [SELECT  Name,QuoteItem_ConsultAmount__c,QuoteItem_ConsultDiscountAmount__c,QuoteItem_ConsultDiscountedPrice__c,QuoteItem_ConsultLevel__c,
                                                 QuoteItem_ConsultListAmount__c,QuoteItem_ConsultListPrice__c,QuoteItem_ConsultManMonths__c,QuoteItem_ConsultName__c,QuoteItem_ConsultRemark__c,
                                                 QuoteItem_ConsultType__c,QuoteItem_LicenseAmount__c,QuoteItem_LicenseDiscountAmount__c,QuoteItem_LicenseDiscountedPriceYear__c,
                                                 QuoteItem_LicenseDiscountedPrice__c,QuoteItem_LicenseListAmount__c,QuoteItem_LicenseListPriceYear__c,QuoteItem_LicenseListPrice__c,
                                                 QuoteItem_LicenseNumberOfUser__c,QuoteItem_LicenseRemark__c,QuoteItem_LicenseType__c,QuoteItem_Quote__c,RecordType.Name,
                                                 QuoteItem_TrainingRemark__c, QuoteItem_TrainingDescription__c, QuoteItem_TrainingCount__c, QuoteItem_TrainingSalesAmount__c,
                                                 QuoteItem_TrainingSalesPrice__c, QuoteItem_TrainingStandardPrice__c
                                            FROM QuoteItem__c
                                           WHERE QuoteItem_Quote__c = :qId
                                        ORDER BY QuoteItem_SortOrder__c,Name ];
        for(QuoteItem__c qi : qiLst){
            system.debug(qi.RecordType.Name);
            if(qi.RecordType.Name == '컨설팅')
                consultLst.add(qi);      
            else if(qi.RecordType.Name == '라이센스')
                licenseLst.add(qi);         
            else if(qi.RecordType.Name == '교육')
                trainingLst.add(qi);         
        }
        if(consultLst.size()>0) hasCon = true;
        if(licenseLst.size()>0) hasLis = true;
        if(trainingLst.size()>0) hasTrn = true;
    }
}