PA_Education/TestMenifest/force-app/main/default/objects/Applyto__c/Applyto__c.object-meta.xml
<CustomObject>
    <description>지원자 정보, 지원 Object</description>
    <label>지원</label>
    <nameField>
        <displayFormat>지원-{0000}</displayFormat>
        <label>지원 번호</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Applyto__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <label>지원자 이름</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Applyto__c/fields/ApplyDate__c.field-meta.xml
<CustomField>
    <fullName>ApplyDate__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>지원일시</label>
    <type>DateTime</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Applyto__c/fields/Birthday__c.field-meta.xml
<CustomField>
    <fullName>Birthday__c</fullName>
    <label>생년월일</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Applyto__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>이메일</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Applyto__c/fields/fm_subject__c.field-meta.xml
<CustomField>
    <fullName>fm_subject__c</fullName>
    <formula>JobPosition__r.fm_subject__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>채용 명</label>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Applyto__c/fields/JobPosition__c.field-meta.xml
<CustomField>
    <fullName>JobPosition__c</fullName>
    <description>인재채용 - Master Detail
지원자가 지원하는 포지션</description>
    <label>포지션 명</label>
    <referenceTo>JobPosition__c</referenceTo>
    <relationshipLabel>지원</relationshipLabel>
    <relationshipName>JobPositionDetail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Applyto__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>휴대폰</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Applyto__c/fields/PersonalInformationUseAgreement__c.field-meta.xml
<CustomField>
    <fullName>PersonalInformationUseAgreement__c</fullName>
    <defaultValue>false</defaultValue>
    <description>인재채용 지원 시, 개인정보 수집 및 활용 동의 Field</description>
    <label>개인정보 수집 및 활용 동의</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Career__c/Career__c.object-meta.xml
<CustomObject>
    <label>Career</label>
    <nameField>
        <label>회사 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Education__c/Education__c.object-meta.xml
<CustomObject>
    <label>Education</label>
    <nameField>
        <displayFormat>ED-{000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/JobPosition__c/JobPosition__c.object-meta.xml
<CustomObject>
    <description>채용공고, 인재채용 Object</description>
    <label>인재채용</label>
    <nameField>
        <displayFormat>인재채용-{0000}</displayFormat>
        <label>인재채용 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/JobPosition__c/fields/Career__c.field-meta.xml
<CustomField>
    <fullName>Career__c</fullName>
    <label>지원구분</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>신입</fullName>
            </value>
            <value>
                <fullName>경력</fullName>
            </value>
            <value>
                <fullName>무관</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/JobPosition__c/fields/CareerEng__c.field-meta.xml
<CustomField>
    <fullName>CareerEng__c</fullName>
    <label>지원구분 (English)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Experienced</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/JobPosition__c/fields/Education__c.field-meta.xml
<CustomField>
    <fullName>Education__c</fullName>
    <label>학력</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>학력무관</fullName>
            </value>
            <value>
                <fullName>고졸</fullName>
            </value>
            <value>
                <fullName>대졸(2~3년제) 이상</fullName>
            </value>
            <value>
                <fullName>대졸(4년제) 이상</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/JobPosition__c/fields/EducationEng__c.field-meta.xml
<CustomField>
    <fullName>EducationEng__c</fullName>
    <label>학력 (English)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Academic Background Required</fullName>
            </value>
            <value>
                <fullName>Graduated High School</fullName>
            </value>
            <value>
                <fullName>Associate Degree</fullName>
            </value>
            <value>
                <fullName>Bachelor’s Degree</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/JobPosition__c/fields/fm_subject__c.field-meta.xml
<CustomField>
    <fullName>fm_subject__c</fullName>
    <formula>Year__c  + &apos;년 &apos; + TEXT(RecruitmentCategory__c) + &apos; &apos; + TEXT(Position__c) + &apos; &apos; + TEXT(Career__c) + &apos; 모집&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>채용 명</label>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/JobPosition__c/fields/fm_subjectEng__c.field-meta.xml
<CustomField>
    <fullName>fm_subjectEng__c</fullName>
    <formula>Year__c + &apos; &apos; + TEXT(RecruitmentCategoryEng__c) + &apos; for &apos; + if(TEXT(CareerEng__c)==&apos;NEW&apos;, &apos;Beginner&apos;, &apos;Experienced&apos;) + &apos; &apos; + TEXT(Position__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>채용 명 (English)</label>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/JobPosition__c/fields/MainBusiness__c.field-meta.xml
<CustomField>
    <fullName>MainBusiness__c</fullName>
    <description>인재채용 대상의 주요업무 기재</description>
    <label>주요업무</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/JobPosition__c/fields/MainBusinessEng__c.field-meta.xml
<CustomField>
    <fullName>MainBusinessEng__c</fullName>
    <label>주요업무 (English)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/JobPosition__c/fields/OrderNum__c.field-meta.xml
<CustomField>
    <fullName>OrderNum__c</fullName>
    <label>OrderNum</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/JobPosition__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>포지션명</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administrator</fullName>
                <default>true</default>
                <label>Administrator</label>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/JobPosition__c/fields/preferentialTreatment__c.field-meta.xml
<CustomField>
    <fullName>preferentialTreatment__c</fullName>
    <label>우대사항</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/JobPosition__c/fields/preferentialTreatmentEng__c.field-meta.xml
<CustomField>
    <fullName>preferentialTreatmentEng__c</fullName>
    <label>우대사항 (English)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/JobPosition__c/fields/Qualifications__c.field-meta.xml
<CustomField>
    <fullName>Qualifications__c</fullName>
    <label>자격요건</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/JobPosition__c/fields/QualificationsEng__c.field-meta.xml
<CustomField>
    <fullName>QualificationsEng__c</fullName>
    <label>자격요건 (English)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/JobPosition__c/fields/RecruitmentCategory__c.field-meta.xml
<CustomField>
    <fullName>RecruitmentCategory__c</fullName>
    <label>모집 구분</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>공개채용</fullName>
            </value>
            <value>
                <fullName>특별채용</fullName>
            </value>
            <value>
                <fullName>상시채용</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/JobPosition__c/fields/RecruitmentCategoryEng__c.field-meta.xml
<CustomField>
    <fullName>RecruitmentCategoryEng__c</fullName>
    <label>모집 구분(English)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open Recruitment</fullName>
            </value>
            <value>
                <fullName>Special Recruitment</fullName>
            </value>
            <value>
                <fullName>Normal Recruitment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/JobPosition__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>채용중</fullName>
            </value>
            <value>
                <fullName>마감</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/JobPosition__c/fields/StatusEng__c.field-meta.xml
<CustomField>
    <fullName>StatusEng__c</fullName>
    <label>Status (English)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/JobPosition__c/fields/WorkingPlace__c.field-meta.xml
<CustomField>
    <fullName>WorkingPlace__c</fullName>
    <label>근무지역</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>서울</fullName>
            </value>
            <value>
                <fullName>경기</fullName>
            </value>
            <value>
                <fullName>인천</fullName>
            </value>
            <value>
                <fullName>수원</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/JobPosition__c/fields/WorkingPlaceEng__c.field-meta.xml
<CustomField>
    <fullName>WorkingPlaceEng__c</fullName>
    <label>근무지역 (English)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Seoul</fullName>
            </value>
            <value>
                <fullName>Gyeonggi</fullName>
            </value>
            <value>
                <fullName>Incheon</fullName>
            </value>
            <value>
                <fullName>Suwon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/JobPosition__c/fields/WorkType__c.field-meta.xml
<CustomField>
    <fullName>WorkType__c</fullName>
    <label>근무형태</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>정규직</fullName>
            </value>
            <value>
                <fullName>계약직</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/JobPosition__c/fields/WorkTypeEng__c.field-meta.xml
<CustomField>
    <fullName>WorkTypeEng__c</fullName>
    <inlineHelpText>계약직 = Full-time Contract</inlineHelpText>
    <label>근무형태 (English)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Permanent</fullName>
            </value>
            <value>
                <fullName>Full-time Contract</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/RenewalHPJobPositions.cls
/**
 * =============================================
 * File Name    : RenewalHPJobPositions.cls
 * Author       : Chan Kang
 * Group        : Boundary
 * Date         : 2021. 12. 24
 * Description  : 채용 공고 Open Positions
 * Modification Log
 * ===================================================================================
 * Ver      Date            Author              Modification
 * ===================================================================================
   1.0      2021. 12. 24    Chan Kang           Create
   1.1      2022. 04. 15    Gyubin Lee          Use optimized query constructor
                                                Add query to fetch data in English
*/

public without sharing class RenewalHPJobPositions {
  @AuraEnabled
  public static List<JobPosition__c> getPositions(Boolean isEnglish) {
    //        List<JobPosition__c> positions = [
    //                SELECT Id, fm_subject__c, WorkType__c, Career__c, Education__c, RecruitmentCategory__c, Position__c, Qualifications__c, preferentialTreatment__c, Status__c, MainBusiness__c
    //                FROM JobPosition__c
    //                WHERE OrderNum__c != NULL AND OrderNum__c != 0
    //                ORDER BY OrderNum__c ASC
    //                LIMIT 9
    //        ];

    String head = isEnglish
      ? 'Id, ' +
        'fm_subjectEng__c, ' +
        'WorkTypeEng__c, ' +
        'CareerEng__c, ' +
        'EducationEng__c, ' +
        'RecruitmentCategoryEng__c, ' +
        'Position__c, ' +
        'QualificationsEng__c, ' +
        'preferentialTreatmentEng__c, ' +
        'StatusEng__c, ' +
        'MainBusinessEng__c, ' +
        'WorkingPlaceEng__c'
      : 'Id, ' +
        'fm_subject__c, ' +
        'WorkType__c, ' +
        'Career__c, ' +
        'Education__c, ' +
        'RecruitmentCategory__c, ' +
        'Position__c, ' +
        'Qualifications__c, ' +
        'preferentialTreatment__c, ' +
        'Status__c, ' +
        'MainBusiness__c, ' +
        'WorkingPlace__c';
    String body = 'JobPosition__c WHERE OrderNum__c != NULL AND OrderNum__c != 0 ORDER BY OrderNum__c ASC LIMIT 9';
    return Database.query(RenewalHPUtility.queryConstructor(head, body));
  }

  @AuraEnabled
  public static List<JobPosition__c> loadMorePositions(Boolean isEnglish) {
    //        List<JobPosition__c> positions = [
    //                SELECT Id, fm_subject__c, WorkType__c, Career__c, Education__c, RecruitmentCategory__c, Position__c, Qualifications__c, preferentialTreatment__c, Status__c, MainBusiness__c
    //                FROM JobPosition__c
    //                ORDER BY OrderNum__c ASC
    //        ];

    String head = isEnglish
      ? 'Id, fm_subjectEng__c, ' +
        'WorkTypeEng__c, ' +
        'CareerEng__c, ' +
        'EducationEng__c, ' +
        'RecruitmentCategoryEng__c, ' +
        //'PositionEng__c, ' +
        'Position__c, ' +
        'QualificationsEng__c, ' +
        'preferentialTreatmentEng__c, ' +
        'StatusEng__c, ' +
        'MainBusinessEng__c, ' +
        'WorkingPlaceEng__c'
      : 'Id, fm_subject__c, WorkType__c, Career__c, Education__c, RecruitmentCategory__c, Position__c, Qualifications__c, preferentialTreatment__c, Status__c, MainBusiness__c, WorkingPlace__c';
    String body = 'JobPosition__c ORDER BY OrderNum__c ASC';

    return Database.query(RenewalHPUtility.queryConstructor(head, body));
  }

  @AuraEnabled
  public static String doSaveApplyTo(
    Map<String, Object> paramMap,
    String fileName,
    String base64Data,
    String contentType
  ) {
    System.debug('STart doSaveApplyTo >>>>>>' + paramMap);

    String Mobile = String.valueOf(paramMap.get('Mobile'));
    String Applicant = String.valueOf(paramMap.get('Applicant'));
    String Email = String.valueOf(paramMap.get('Email'));
    String JobPositionId = String.valueOf(paramMap.get('JobPositionId'));
    String BirthDate = String.valueOf(paramMap.get('BirthDate'));

    System.debug('fileName >>' + fileName);
    System.debug('base64Data >>' + base64Data);
    System.debug('contentType >>' + contentType);

    Applyto__c objApplyto = new Applyto__c();
    objApplyto.Mobile__c = Mobile;
    objApplyto.Email__c = Email;
    objApplyto.Applicant__c = Applicant;
    objApplyto.JobPosition__c = JobPositionId;
    objApplyto.ApplyDate__c = Datetime.now();
    objApplyto.Birthday__c = Date.valueOf(BirthDate);
    objApplyto.PersonalInformationUseAgreement__c = true;

    insert objApplyto;

    base64Data = EncodingUtil.urlDecode(base64Data, 'UTF-8');
    ContentVersion contentVersion = new ContentVersion(
      VersionData = EncodingUtil.base64Decode(base64Data),
      Title = fileName,
      PathOnClient = '/' + fileName,
      FirstPublishLocationId = objApplyto.Id
    );

    insert contentVersion;

    return '0';
  }
}