PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/HolidayAction__c.object-meta.xml
<CustomObject>
    <description>HolidayAction__c</description>
    <label>휴가신청</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/HolidayAction_Type__c.field-meta.xml
<CustomField>
    <fullName>HolidayAction_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Annual Holiday</fullName>
                <label>연차</label>
            </value>
            <value>
                <fullName>Half-day Leave</fullName>
                <label>반차</label>
            </value>
            <value>
                <fullName>Reward Holiday</fullName>
                <label>대체휴가</label>
            </value>
            <value>
                <fullName>Reward Half-Holiday</fullName>
                <label>대체휴가(반차)</label>
            </value>
            <value>
                <fullName>Public Works</fullName>
                <label>공가(공무)</label>
            </value>
            <value>
                <fullName>Family Leave</fullName>
                <label>경조휴가</label>
            </value>
            <value>
                <fullName>Sick Leave</fullName>
                <label>병가(무급)</label>
            </value>
            <value>
                <fullName>Women Holiday</fullName>
                <label>생리휴가</label>
            </value>
            <value>
                <fullName>가족돌봄휴가</fullName>
            </value>
            <value>
                <fullName>출산휴가</fullName>
            </value>
            <value>
                <fullName>휴직</fullName>
            </value>
            <value>
                <fullName>육아휴직</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayAction__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Project_HolidayAction</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>프로젝트에 대한 기본정보를 관리하며, Deal Closing 이후 생성한다. 영업담당자가 계약 체결 후 기초 데이터를 작성하며, 프로젝트 진행 중에는 PM이 관리하고, 대금청구/지급 관련 정보는 회계에서 관리한다.</description>
    <label>프로젝트</label>
    <nameField>
        <label>프로젝트 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/classes/NewHolidayLightningExtension_Test.cls
/**
 * Created by JWJANG on 2023-01-18.
 */

@isTest
public with sharing class NewHolidayLightningExtension_Test {
    @isTest
    static void NewHolidayLightningExtension_Test() {
        test.startTest();

        HolidayAction__c objHA = TestObjectCreator.objHolidayAction;
        HolidayAction__c objHA2 = objHa.clone();
        objHA2.HolidayAction_Type__c = 'Half-day Leave';
        HolidayAction__c objHA3 = objHa.clone();
        objHA3.HolidayAction_Type__c = 'Women Holiday';
        HolidayAction__c objHA3_1 = objHa3.clone();
        HolidayAction__c objHA4 = objHa.clone();
        objHA4.HolidayAction_Type__c = 'Reward Holiday';

        NewHolidayLightningExtension.doHolidayAction(new HolidayAction__c());
        Map<String, String> mapResult = NewHolidayLightningExtension.doHolidayAction(objHA);
        mapResult = NewHolidayLightningExtension.doHolidayAction(objHA2);
        mapResult = NewHolidayLightningExtension.doHolidayAction(objHA3);
        mapResult = NewHolidayLightningExtension.doHolidayAction(objHA3_1);
        mapResult = NewHolidayLightningExtension.doHolidayAction(objHA4);
        System.debug('testClass :: ' + mapResult);

        NewHolidayLightningExtension.getSelectFieldName();
        NewHolidayLightningExtension.selfApproverCheck();
        List<User> listUsers = [SELECT Id, ApprovalLine1__c FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];
        User objUser = TestObjectCreator.objUser;
        update objUser;
        if (!listUsers.isEmpty()) {
            listUsers[0].ApprovalLine1__c = objUser.Id;
        }
        update listUsers;


        NewHolidayLightningExtension.getApproverId();
        NewHolidayLightningExtension.employeeStatus();
        Project__c objPrj = TestObjectCreator.objProject;
        insert objPrj;
        NewHolidayLightningExtension.getProjectPmId(objPrj.Id);
        NewHolidayLightningExtension.getHolidayRemain();

        test.stopTest();

    }
}