PA_Education/TestMenifest/force-app/main/default/objects/HolidayWork__c/HolidayWork__c.object-meta.xml
<CustomObject>
    <label>휴일근무</label>
    <nameField>
        <label>휴일근무이름 (자동입력)</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWork__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>근무 월</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1월</fullName>
            </value>
            <value>
                <fullName>2월</fullName>
            </value>
            <value>
                <fullName>3월</fullName>
            </value>
            <value>
                <fullName>4월</fullName>
            </value>
            <value>
                <fullName>5월</fullName>
            </value>
            <value>
                <fullName>6월</fullName>
            </value>
            <value>
                <fullName>7월</fullName>
            </value>
            <value>
                <fullName>8월</fullName>
            </value>
            <value>
                <fullName>9월</fullName>
            </value>
            <value>
                <fullName>10월</fullName>
            </value>
            <value>
                <fullName>11월</fullName>
            </value>
            <value>
                <fullName>12월</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWork__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>단계</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>계획작성중</fullName>
                <default>true</default>
                <label>계획작성중</label>
            </value>
            <value>
                <fullName>계획승인요청</fullName>
            </value>
            <value>
                <fullName>계획승인</fullName>
            </value>
            <value>
                <fullName>계획취소승인요청</fullName>
            </value>
            <value>
                <fullName>근무승인요청</fullName>
            </value>
            <value>
                <fullName>근무승인</fullName>
            </value>
            <value>
                <fullName>승인거절</fullName>
                <isActive>false</isActive>
                <label>승인거절</label>
            </value>
            <value>
                <fullName>승인완료</fullName>
                <isActive>false</isActive>
                <label>승인완료</label>
            </value>
            <value>
                <fullName>승인요청</fullName>
                <isActive>false</isActive>
                <label>승인요청</label>
            </value>
            <value>
                <fullName>작성중</fullName>
                <isActive>false</isActive>
                <label>작성중</label>
            </value>
            <value>
                <fullName>취소승인완료</fullName>
                <isActive>false</isActive>
                <label>취소승인완료</label>
            </value>
            <value>
                <fullName>취소승인요청</fullName>
                <isActive>false</isActive>
                <label>취소승인요청</label>
            </value>
            <value>
                <fullName>회수</fullName>
                <isActive>false</isActive>
                <label>회수</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWork__c/fields/WorkingTime__c.field-meta.xml
<CustomField>
    <fullName>WorkingTime__c</fullName>
    <label>근무일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWork__c/fields/WorkOrderUser__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>1차 승인자</label>
    <referenceTo>User</referenceTo>
    <relationshipName>HolidayWorkUser</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWork__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>근무년도</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2022년</fullName>
            </value>
            <value>
                <fullName>2023년</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWorkDetail__c/HolidayWorkDetail__c.object-meta.xml
<CustomObject>
    <label>휴일근무 상세</label>
    <nameField>
        <displayFormat>HW-{YY}{MM}-{0000}</displayFormat>
        <label>휴일근무 상세 코드</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWorkDetail__c/fields/HolidayWork__c.field-meta.xml
<CustomField>
    <fullName>HolidayWork__c</fullName>
    <label>휴일근무</label>
    <referenceTo>HolidayWork__c</referenceTo>
    <relationshipName>HWD_HolidayWork</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWorkDetail__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>진행단계</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Design &amp; Build</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
            <value>
                <fullName>Deploy</fullName>
            </value>
            <value>
                <fullName>Closing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWorkDetail__c/fields/WorkDetail__c.field-meta.xml
<CustomField>
    <fullName>WorkDetail__c</fullName>
    <label>작업내용</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWorkDetail__c/fields/WorkingDate__c.field-meta.xml
<CustomField>
    <fullName>WorkingDate__c</fullName>
    <label>근무일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWorkDetail__c/fields/WorkingTime__c.field-meta.xml
<CustomField>
    <fullName>WorkingTime__c</fullName>
    <label>근무시간</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>4</fullName>
                <label>0.5일 (4시간)</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>1일 (8시간)</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>근무하지 않음</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWorkDetail__c/fields/WorkOrderUser__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>작업지시자</label>
    <referenceTo>User</referenceTo>
    <relationshipName>HolidayWorkDetailUser</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWorkDetail__c/fields/WorkUser__c.field-meta.xml
<CustomField>
    <fullName>WorkUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>휴일근무자</label>
    <referenceTo>User</referenceTo>
    <relationshipName>HolidayWorkUserDetail</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/SubmitForApprovalController_test.cls
@IsTest
public with sharing class SubmitForApprovalController_test {
    @TestSetup
    static void testSetup() {
        Profile objProfile = [SELECT Id, Name FROM Profile WHERE Name = 'Daeu Nextier Employee' LIMIT 1];
        User objUser = TestObjectCreator.objUser;
        objUser.ProfileId = objProfile.Id;
        objUser.Username = 'test@demo.co.kr';
        objUser.Position__c = '9';
        insert objUser;
    }

    @IsTest
    static void doTest(){
        test.startTest();
        User objUser = [SELECT Id FROM User ORDER BY CreatedDate DESC LIMIT 1];
        HolidayWork__c objHW = new HolidayWork__c();
        objHW.Status__c = '계획승인';
        objHW.Month__c = '2월';
        objHW.Year__c = '2023년';
        objHW.WorkOrderUser__c = objUser.Id;
        insert objHW;

        HolidayWorkDetail__c objHWD = new HolidayWorkDetail__c();
        objHWD.HolidayWork__c   = objHW.Id;
        objHWD.WorkUser__c      = objUser.Id;
        objHWD.Stage__c         = 'Design & Build';
        objHWD.WorkingDate__c   = Date.newInstance(2023, 2, 22);
        objHWD.WorkingTime__c   = '4';
        objHWD.WorkDetail__c    = '작업 내용';
        insert objHWD;

        objHWD.WorkUser__c = objUser.Id;

        SubmitForApprovalController.doApproval(objHW.Id, '');

        update objHWD;
        test.stopTest();
    }
}