PA_Education/TestMenifest/force-app/main/default/objects/HolidayWork__c/HolidayWork__c.object-meta.xml
<CustomObject>
    <label>휴일근무</label>
    <nameField>
        <label>휴일근무이름 (자동입력)</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWork__c/fields/WorkingTime__c.field-meta.xml
<CustomField>
    <fullName>WorkingTime__c</fullName>
    <label>근무일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWorkDetail__c/HolidayWorkDetail__c.object-meta.xml
<CustomObject>
    <label>휴일근무 상세</label>
    <nameField>
        <displayFormat>HW-{YY}{MM}-{0000}</displayFormat>
        <label>휴일근무 상세 코드</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWorkDetail__c/fields/HolidayWork__c.field-meta.xml
<CustomField>
    <fullName>HolidayWork__c</fullName>
    <label>휴일근무</label>
    <referenceTo>HolidayWork__c</referenceTo>
    <relationshipName>HWD_HolidayWork</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWorkDetail__c/fields/PlanningTime__c.field-meta.xml
<CustomField>
    <fullName>PlanningTime__c</fullName>
    <label>계획시간</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>4</fullName>
                <label>0.5일 (4시간)</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>1일 (8시간)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWorkDetail__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>진행단계</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Design &amp; Build</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
            <value>
                <fullName>Deploy</fullName>
            </value>
            <value>
                <fullName>Closing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWorkDetail__c/fields/WorkDetail__c.field-meta.xml
<CustomField>
    <fullName>WorkDetail__c</fullName>
    <label>작업내용</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWorkDetail__c/fields/WorkingTime__c.field-meta.xml
<CustomField>
    <fullName>WorkingTime__c</fullName>
    <label>근무시간</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>4</fullName>
                <label>0.5일 (4시간)</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>1일 (8시간)</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>근무하지 않음</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWorkDetail__c/fields/WorkUser__c.field-meta.xml
<CustomField>
    <fullName>WorkUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>휴일근무자</label>
    <referenceTo>User</referenceTo>
    <relationshipName>HolidayWorkUserDetail</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/HolidayWorkApprovalLinesController_test.cls
/**
 * Created by Kwanwoo.Jeon on 2024-02-01.
 */

@IsTest
private class HolidayWorkApprovalLinesController_test {
    @IsTest
    static void testBehavior() {
        Test.startTest();

        User user1 = [SELECT Id FROM User WHERE Id =: UserInfo.getUserId()];
        User user2 = TestObjectCreator.objUser;
        User user3 = user2.clone(false);
        User user4 = user2.clone(false);

        user2.Email               = 'atest@test.com';
        user2.Username            = 'atestclass@test.com';
        user2.Alias               = 'auser';
        user2.CommunityNickname   = 'auser';

        user3.Email               = 'aatest@test.com';
        user3.Username            = 'aatestclass@test.com';
        user3.CommunityNickname   = 'ausedr';

        user4.Email               = 'aatest@test.com';
        user4.Username            = 'aatesgtclass@test.com';
        user4.CommunityNickname   = 'ausera';

        insert user2;
        insert user3;
        insert user4;

        // user1.ApprovalLine1__c = 'ApprovalLine1__c/ApprovalLine1__c/'+ user2.Id;
        user1.ApprovalLine2__c = 'ApprovalLine2__c/ApprovalLine2__c/'+ user2.Id;
        user1.ApprovalLine3__c = 'ApprovalLine3__c/ApprovalLine3__c/'+ user2.Id +'/'+ user3.Id;
        user1.ApprovalLine4__c = 'ApprovalLine4__c/ApprovalLine4__c/'+ user2.Id;
        update user1;

//        String insertValue = 'ApprovalLine1__c/ApprovalLine1__c/'+ user2.Id;
//        String fieldName   = 'ApprovalLine1';

        List<User> objListUser = new List<User>();
        objListUser.add(user1);
        objListUser.add(user2);
        objListUser.add(user3);
        objListUser.add(user4);

        HolidayWork__c objHW = new HolidayWork__c();
        objHW.WorkingTime__c = Date.today();
        insert objHW;


        HolidayWorkDetail__c objHWD = new HolidayWorkDetail__c();
        objHWD.HolidayWork__c = objHW.Id;
        objHWD.WorkUser__c = user1.Id;
        objHWD.Stage__c = 'Planning';
        objHWD.PlanningTime__c = '4';
        objHWD.WorkDetail__c = '4';
        insert objHWD;

        HolidayWorkApprovalLinesController.getApprovalLines();
        HolidayWorkApprovalLinesController.doSubmit('HolidayWork__c', '코멘트입니다.', objHW.Id, objListUser);
        HolidayWorkApprovalLinesController.doSubmit('HolidayWork__c', '코멘트입니다.', '213456435', objListUser);




        Test.stopTest();
    }
}