PA_Education/TestMenifest/force-app/main/default/objects/HolidayWork__c/HolidayWork__c.object-meta.xml
<CustomObject>
    <label>휴일근무</label>
    <nameField>
        <label>휴일근무이름 (자동입력)</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWork__c/fields/WorkingTime__c.field-meta.xml
<CustomField>
    <fullName>WorkingTime__c</fullName>
    <label>근무일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWorkDetail__c/HolidayWorkDetail__c.object-meta.xml
<CustomObject>
    <label>휴일근무 상세</label>
    <nameField>
        <displayFormat>HW-{YY}{MM}-{0000}</displayFormat>
        <label>휴일근무 상세 코드</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWorkDetail__c/fields/HolidayWork__c.field-meta.xml
<CustomField>
    <fullName>HolidayWork__c</fullName>
    <label>휴일근무</label>
    <referenceTo>HolidayWork__c</referenceTo>
    <relationshipName>HWD_HolidayWork</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWorkDetail__c/fields/PlanningTime__c.field-meta.xml
<CustomField>
    <fullName>PlanningTime__c</fullName>
    <label>계획시간</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>4</fullName>
                <label>0.5일 (4시간)</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>1일 (8시간)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWorkDetail__c/fields/WorkDetail__c.field-meta.xml
<CustomField>
    <fullName>WorkDetail__c</fullName>
    <label>작업내용</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWorkDetail__c/fields/WorkingTime__c.field-meta.xml
<CustomField>
    <fullName>WorkingTime__c</fullName>
    <label>근무시간</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>4</fullName>
                <label>0.5일 (4시간)</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>1일 (8시간)</label>
            </value>
            <value>
                <fullName>0</fullName>
                <label>근무하지 않음</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/HolidayWorkDetail__c/fields/WorkUser__c.field-meta.xml
<CustomField>
    <fullName>WorkUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>휴일근무자</label>
    <referenceTo>User</referenceTo>
    <relationshipName>HolidayWorkUserDetail</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/HolidayWorkApprovalController.cls
/**
 * Created by Kwanwoo.Jeon on 2023-12-07.
 */

public without sharing class HolidayWorkApprovalController {

    @AuraEnabled
    public static dataWrapper doInit(String recordId) {
        System.debug('doInit - recordId : ' + recordId);
        dataWrapper dw = new dataWrapper();
        list<DetailWrapper> listDetail = new List<DetailWrapper>();

        for (HolidayWorkDetail__c obj : [   SELECT Id, Name, WorkUser__r.Name, PlanningTime__c, WorkingTime__c, WorkDetail__c
                                            from HolidayWorkDetail__c
                                            WHERE HolidayWork__c =: recordId]){
            listDetail.add(new DetailWrapper(obj));
        }
        System.debug('listDetail :: ' + listDetail);

        dw.timePicklist = DN_Util.getPickListValues('HolidayWorkDetail__c', 'WorkingTime__c', true);
        dw.listDetailWrapper = listDetail;

        return dw;
    }

    @AuraEnabled
    public static dataWrapper doSave(list<Map<String,String>> listDetail, String strComments, String recordId) {
        dataWrapper dw = new dataWrapper();
        dw.status = 'SUCCESS';
        list<HolidayWorkDetail__c> listHWD = new List<HolidayWorkDetail__c>();

        System.debug('listDetail :: ' + listDetail);
        for(Map<String,String> obj: listDetail){
            listHWD.add(new HolidayWorkDetail__c(Id = obj.get('Id'),WorkingTime__c = obj.get('WorkingTime')));
        }

        if (!listHWD.isEmpty()) {
            Savepoint sp = Database.setSavepoint();
            try{
                list<database.SaveResult> listSR = database.update(listHWD, true);
                system.debug(listSR);

                Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
                req1.setComments(strComments);
                req1.setObjectId(recordId);
                Approval.ProcessResult result = Approval.process(req1);
                dw.message = '근무 승인 요청 되었습니다.';

            }catch(Exception e){
                System.debug('Error ::' + e.getMessage() + ' : ' + e.getLineNumber());
                Database.rollback(sp);
                dw.status = 'Error';
                dw.message = e.getMessage();
            }
        }
        return dw;
    }

    public class dataWrapper{
        @AuraEnabled
        public list<Map<String, String>> timePicklist {get;set;}
        @AuraEnabled
        public list<DetailWrapper> listDetailWrapper {get;set;}
        @AuraEnabled
        public String status {get;set;}
        @AuraEnabled
        public String message {get;set;}
    }


    public class DetailWrapper {
        @AuraEnabled
        public Boolean checked {get;set;}
        @AuraEnabled
        public String Id {get;set;}
        @AuraEnabled
        public String Name {get;set;}
        @AuraEnabled
        public String WorkUserName {get;set;}
        @AuraEnabled
        public String PlanningTime {get;set;}
        @AuraEnabled
        public String WorkingTime {get;set;}
        @AuraEnabled
        public String WorkDetail {get;set;}

        DetailWrapper(HolidayWorkDetail__c obj){
            this.checked = false;
            this.Id = obj.id;
            this.Name = obj.Name;
            this.WorkUserName = obj.WorkUser__r.Name;
            this.PlanningTime = obj.PlanningTime__c;
            this.WorkingTime = obj.WorkingTime__c;
            this.WorkDetail = obj.WorkDetail__c;
        }

    }
}