PA_Education/TestMenifest/force-app/main/default/objects/EformsignDocument__c/EformsignDocument__c.object-meta.xml
<CustomObject>
    <description>이폼사인 문서 - 템플릿을 통해 생성(발송)된 문서</description>
    <label>eformsign Document</label>
    <nameField>
        <label>eformsign Document Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignDocument__c/fields/TargetObjectRecordId__c.field-meta.xml
<CustomField>
    <fullName>TargetObjectRecordId__c</fullName>
    <label>대상 개체 레코드 Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignToken__c/EformsignToken__c.object-meta.xml
<CustomObject>
    <label>eformsign Token</label>
    <nameField>
        <label>eformsign Token Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignToken__c/fields/AccessToken__c.field-meta.xml
<CustomField>
    <fullName>AccessToken__c</fullName>
    <label>Access Token</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignToken__c/fields/ExpireIn__c.field-meta.xml
<CustomField>
    <fullName>ExpireIn__c</fullName>
    <label>Expire In</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignToken__c/fields/RefreshToken__c.field-meta.xml
<CustomField>
    <fullName>RefreshToken__c</fullName>
    <label>Refresh Token</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignToken__c/fields/TokenIssuedDateTime__c.field-meta.xml
<CustomField>
    <fullName>TokenIssuedDateTime__c</fullName>
    <label>Token Issued DateTime</label>
    <type>DateTime</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignToken__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>eformsign_Token</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/EformsignDocumentCtrl_Test.cls
/************************************************************************************
 * Description :  EformsignDocumentCtrl,EformsignTokenizedApiWorkflow
 * Ver      Date           Author          Modification
 * ===================================================================================
   1.0      2024-06-27     hs.jung          Create
*************************************************************************************/
@IsTest
private class EformsignDocumentCtrl_Test {


    @IsTest
    static void testBehavior() {
        Account objAcc = TestObjectCreator.objAccount;
        insert objAcc;

        EformsignToken__c objEformsignToken = new EformsignToken__c();
        objEformsignToken.Name = 'test';
        objEformsignToken.AccessToken__c = 'test';
        objEformsignToken.RefreshToken__c = null;
        objEformsignToken.User__c = UserInfo.getUserId();
        objEformsignToken.TokenIssuedDateTime__c = System.today() + 2 ;
        objEformsignToken.ExpireIn__c = 3600;
        insert objEformsignToken;

        EformsignDocument__c objEfsDoc = new EformsignDocument__c();
        objEfsDoc.Name =' test';
        objEfsDoc.TargetObjectRecordId__c = objAcc.Id;
        insert objEfsDoc;

        Test.startTest();
        EformsignDocumentCtrl.getRelatedTemplatesBySObject('Account');
        EformsignDocumentCtrl.getDocument(objEfsDoc.Id);
        EformsignDocumentCtrl.getRelatedDocs(objEfsDoc.TargetObjectRecordId__c);
        EformsignDocumentCtrl.downloadDocument(objEfsDoc.Id, true);
        EformsignDocumentCtrl.syncDocumentInfo(objEfsDoc.Id);
        EformsignDocumentCtrl.deleteDocument(objEfsDoc.Id);
        EformsignDocumentCtrl.cancelDocument(objEfsDoc.Id,'test');
        Test.stopTest();
    }
    @IsTest
    static void testBehavior2() {
        Account objAcc = TestObjectCreator.objAccount;
        insert objAcc;

        EformsignDocument__c objEfsDoc = new EformsignDocument__c();
        objEfsDoc.Name =' test';
        objEfsDoc.TargetObjectRecordId__c = objAcc.Id;
        insert objEfsDoc;

        Test.startTest();
        EformsignDocumentCtrl.downloadDocument(objEfsDoc.Id, true);

        Test.stopTest();
    }

}