PA_Education/TestMenifest/force-app/main/default/objects/EformsignDocument__c/EformsignDocument__c.object-meta.xml
<CustomObject>
    <description>이폼사인 문서 - 템플릿을 통해 생성(발송)된 문서</description>
    <label>eformsign Document</label>
    <nameField>
        <label>eformsign Document Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignDocument__c/fields/DocumentCurrentStatus__c.field-meta.xml
<CustomField>
    <fullName>DocumentCurrentStatus__c</fullName>
    <label>문서 상태</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>false</fullName>
            </value>
            <value>
                <fullName>001</fullName>
            </value>
            <value>
                <fullName>003</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignDocument__c/fields/DocumentId__c.field-meta.xml
<CustomField>
    <fullName>DocumentId__c</fullName>
    <label>문서Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignDocument__c/fields/EformsignTemplate__c.field-meta.xml
<CustomField>
    <fullName>EformsignTemplate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>이폼사인 템플릿</label>
    <referenceTo>EformsignTemplate__c</referenceTo>
    <relationshipLabel>eformsign Document</relationshipLabel>
    <relationshipName>eformsign_Document</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignDocument__c/fields/TargetObjectRecordId__c.field-meta.xml
<CustomField>
    <fullName>TargetObjectRecordId__c</fullName>
    <label>대상 개체 레코드 Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignEnvironment__c/EformsignEnvironment__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Eformsign Environment</label>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignEnvironment__c/fields/ApiBaseUrl__c.field-meta.xml
<CustomField>
    <fullName>ApiBaseUrl__c</fullName>
    <label>Api Base Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignEnvironment__c/fields/ApiKey__c.field-meta.xml
<CustomField>
    <fullName>ApiKey__c</fullName>
    <label>API Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignEnvironment__c/fields/CompanyId__c.field-meta.xml
<CustomField>
    <fullName>CompanyId__c</fullName>
    <label>Company ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignEnvironment__c/fields/Privatekey__c.field-meta.xml
<CustomField>
    <fullName>Privatekey__c</fullName>
    <label>Private key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignEnvironment__c/fields/RepresentativeAdminEmail__c.field-meta.xml
<CustomField>
    <fullName>RepresentativeAdminEmail__c</fullName>
    <label>Representative Admin Email</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignTemplate__c/EformsignTemplate__c.object-meta.xml
<CustomObject>
    <description>이폼싸인 템플릿</description>
    <label>eformsign Template</label>
    <nameField>
        <label>eformsign Template Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignTemplate__c/fields/ObjectApiName__c.field-meta.xml
<CustomField>
    <fullName>ObjectApiName__c</fullName>
    <label>대상 개체명</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignTemplate__c/fields/TemplateId__c.field-meta.xml
<CustomField>
    <fullName>TemplateId__c</fullName>
    <externalId>true</externalId>
    <label>Template Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignToken__c/EformsignToken__c.object-meta.xml
<CustomObject>
    <label>eformsign Token</label>
    <nameField>
        <label>eformsign Token Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignToken__c/fields/AccessToken__c.field-meta.xml
<CustomField>
    <fullName>AccessToken__c</fullName>
    <label>Access Token</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignToken__c/fields/ExpireIn__c.field-meta.xml
<CustomField>
    <fullName>ExpireIn__c</fullName>
    <label>Expire In</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignToken__c/fields/RefreshToken__c.field-meta.xml
<CustomField>
    <fullName>RefreshToken__c</fullName>
    <label>Refresh Token</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignToken__c/fields/TokenIssuedDateTime__c.field-meta.xml
<CustomField>
    <fullName>TokenIssuedDateTime__c</fullName>
    <label>Token Issued DateTime</label>
    <type>DateTime</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/EformsignToken__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>eformsign_Token</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/EformsignDocumentManager_Test.cls
/************************************************************************************
 * Description :
 * Ver      Date           Author          Modification
 * ===================================================================================
   1.0      2024-06-28     hs.jung          Create
*************************************************************************************/
@isTest
public class EformsignDocumentManager_Test {
    @isTest
    static void testDownloadClassInstantiation() {
        Test.setMock(HttpCalloutMock.class, new HttpCalloutSuccessMock());
        Account objAcc = TestObjectCreator.objAccount;
        insert objAcc;

        EformsignEnvironment__c defaultConfig = new EformsignEnvironment__c();
        defaultConfig.ApiKey__c = 'apiKey';
        defaultConfig.Privatekey__c = 'privateKey';
        defaultConfig.CompanyId__c = 'companyId';
        defaultConfig.RepresentativeAdminEmail__c = 'https://kr-api.eformsign.com';
        defaultConfig.ApiBaseUrl__c = 'https://kr-api.eformsign.com';
        insert defaultConfig;

        EformsignToken__c objEformsignToken = new EformsignToken__c();
        objEformsignToken.Name = 'eftkName';
        objEformsignToken.AccessToken__c = 'et54345344535632sdfsdrt32';
        objEformsignToken.RefreshToken__c = 'et54345344535632sdfsdrt3223';
        objEformsignToken.User__c = UserInfo.getUserId();
        objEformsignToken.TokenIssuedDateTime__c = System.today() + 2 ;
        objEformsignToken.ExpireIn__c = 3600;
        insert objEformsignToken;

        EformsignTemplate__c objEformsignTemplate = new EformsignTemplate__c();
        objEformsignTemplate.Name = 'test';
        objEformsignTemplate.ObjectApiName__c = 'Account';
        objEformsignTemplate.TemplateId__c = 'TemplateId';
        insert objEformsignTemplate;

        EformsignDocument__c objEfsDoc = new EformsignDocument__c();
        objEfsDoc.Name =' test';
        objEfsDoc.DocumentId__c =' test1';
        objEfsDoc.DocumentCurrentStatus__c =' 1';
        objEfsDoc.EformsignTemplate__c  = objEformsignTemplate.Id;
        objEfsDoc.TargetObjectRecordId__c = objAcc.Id;
        insert objEfsDoc;

        String myString = 'StringToBlob';
        Blob myBlob = Blob.valueOf(myString);
        ContentVersion cv = new ContentVersion();
        cv.Title = 'test';
        cv.PathOnClient = 'test';
        cv.VersionData = myBlob;
        insert cv;

        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.ContentDocumentId = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id =: cv.Id].ContentDocumentId;
        cdl.ShareType = 'V';
        cdl.LinkedEntityId = objEfsDoc.Id;
        insert cdl;

        test.startTest();
        EformsignDocumentManager.Download efDownloadInstance = new EformsignDocumentManager.Download(objEfsDoc.Id, true);
        efDownloadInstance.execute();
        EformsignDocumentManager.StatusSyncer efStatusSyncer = new EformsignDocumentManager.StatusSyncer(objEfsDoc.Id);
        efStatusSyncer.execute();
//        efStatusSyncer.databaseLogic();
        EformsignDocumentManager.Cancelation efCancelation = new EformsignDocumentManager.Cancelation(objEfsDoc.Id, '');
        efCancelation.execute();
        EformsignDocumentManager.Deletion efDeletion = new EformsignDocumentManager.Deletion(objEfsDoc.Id);
        efDeletion.execute();

//        HttpResponse response = efDownloadInstance.sendRequest();
        test.stopTest();
    }

    @isTest
    static void testForStatusSyncer() {
        Test.setMock(HttpCalloutMock.class, new HttpCalloutSuccessMock());
        Account objAcc = TestObjectCreator.objAccount;
        insert objAcc;

        EformsignEnvironment__c defaultConfig = new EformsignEnvironment__c();
        defaultConfig.ApiKey__c = 'apiKey';
        defaultConfig.Privatekey__c = 'privateKey';
        defaultConfig.CompanyId__c = 'companyId';
        defaultConfig.RepresentativeAdminEmail__c = 'https://kr-api.eformsign.com';
        defaultConfig.ApiBaseUrl__c = 'https://kr-api.eformsign.com';
        insert defaultConfig;

        EformsignToken__c objEformsignToken = new EformsignToken__c();
        objEformsignToken.Name = 'eftkName';
        objEformsignToken.AccessToken__c = 'et54345344535632sdfsdrt32';
        objEformsignToken.RefreshToken__c = 'et54345344535632sdfsdrt3223';
        objEformsignToken.User__c = UserInfo.getUserId();
        objEformsignToken.TokenIssuedDateTime__c = System.today() + 2 ;
        objEformsignToken.ExpireIn__c = 3600;
        insert objEformsignToken;

        EformsignTemplate__c objEformsignTemplate = new EformsignTemplate__c();
        objEformsignTemplate.Name = 'test';
        objEformsignTemplate.ObjectApiName__c = 'Account';
        objEformsignTemplate.TemplateId__c = 'TemplateId';
        insert objEformsignTemplate;

        EformsignDocument__c objEfsDoc = new EformsignDocument__c();
        objEfsDoc.Name =' test';
        objEfsDoc.DocumentId__c =' test1';
        objEfsDoc.DocumentCurrentStatus__c =' 1';
        objEfsDoc.EformsignTemplate__c  = objEformsignTemplate.Id;
        objEfsDoc.TargetObjectRecordId__c = objAcc.Id;
        insert objEfsDoc;

        String myString = 'StringToBlob';
        Blob myBlob = Blob.valueOf(myString);
        ContentVersion cv = new ContentVersion();
        cv.Title = 'test';
        cv.PathOnClient = 'test';
        cv.VersionData = myBlob;
        insert cv;

        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.ContentDocumentId = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id =: cv.Id].ContentDocumentId;
        cdl.ShareType = 'V';
        cdl.LinkedEntityId = objEfsDoc.Id;
        insert cdl;

        Event objEvent = new Event();
        objEvent.DurationInMinutes = 1;
        objEvent.ActivityDateTime =System.today();
        insert objEvent;

        test.startTest();
        EformsignDocumentManager.StatusSyncer efStatusSyncer = new EformsignDocumentManager.StatusSyncer(objEfsDoc.Id);
        efStatusSyncer.execute();

        test.stopTest();
    }

    @isTest
    static void testForDeletion() {
        Test.setMock(HttpCalloutMock.class, new HttpCalloutSuccessMock());
        Account objAcc = TestObjectCreator.objAccount;
        insert objAcc;

        EformsignEnvironment__c defaultConfig = new EformsignEnvironment__c();
        defaultConfig.ApiKey__c = 'apiKey';
        defaultConfig.Privatekey__c = 'privateKey';
        defaultConfig.CompanyId__c = 'companyId';
        defaultConfig.RepresentativeAdminEmail__c = 'https://kr-api.eformsign.com';
        defaultConfig.ApiBaseUrl__c = 'https://kr-api.eformsign.com';
        insert defaultConfig;

        EformsignToken__c objEformsignToken = new EformsignToken__c();
        objEformsignToken.Name = 'eftkName';
        objEformsignToken.AccessToken__c = 'et54345344535632sdfsdrt32';
        objEformsignToken.RefreshToken__c = 'et54345344535632sdfsdrt3223';
        objEformsignToken.User__c = UserInfo.getUserId();
        objEformsignToken.TokenIssuedDateTime__c = System.today() + 2 ;
        objEformsignToken.ExpireIn__c = 3600;
        insert objEformsignToken;

        EformsignTemplate__c objEformsignTemplate = new EformsignTemplate__c();
        objEformsignTemplate.Name = 'test';
        objEformsignTemplate.ObjectApiName__c = 'Account';
        objEformsignTemplate.TemplateId__c = 'TemplateId';
        insert objEformsignTemplate;

        EformsignDocument__c objEfsDoc = new EformsignDocument__c();
        objEfsDoc.Name =' test';
        objEfsDoc.DocumentId__c =' test1';
        objEfsDoc.DocumentCurrentStatus__c =' 1';
        objEfsDoc.EformsignTemplate__c  = objEformsignTemplate.Id;
        objEfsDoc.TargetObjectRecordId__c = objAcc.Id;
        insert objEfsDoc;

        String myString = 'StringToBlob';
        Blob myBlob = Blob.valueOf(myString);
        ContentVersion cv = new ContentVersion();
        cv.Title = 'test';
        cv.PathOnClient = 'test';
        cv.VersionData = myBlob;
        insert cv;

        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.ContentDocumentId = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id =: cv.Id].ContentDocumentId;
        cdl.ShareType = 'V';
        cdl.LinkedEntityId = objEfsDoc.Id;
        insert cdl;

        Event objEvent = new Event();
        objEvent.DurationInMinutes = 1;
        objEvent.ActivityDateTime =System.today();
        insert objEvent;

        test.startTest();
        EformsignDocumentManager.Deletion efDeletion = new EformsignDocumentManager.Deletion(objEfsDoc.Id);
        efDeletion.execute();

        test.stopTest();
    }

    @isTest
    static void testDownloadClassInstantiation2() {
        Test.setMock(HttpCalloutMock.class, new HttpCalloutSuccessMock());
        Account objAcc = TestObjectCreator.objAccount;
        insert objAcc;

        EformsignEnvironment__c defaultConfig = new EformsignEnvironment__c();
        defaultConfig.ApiKey__c = 'apiKey';
        defaultConfig.Privatekey__c = 'privateKey';
        defaultConfig.CompanyId__c = 'companyId';
        defaultConfig.RepresentativeAdminEmail__c = 'https://kr-api.eformsign.com';
        defaultConfig.ApiBaseUrl__c = 'https://kr-api.eformsign.com';
        insert defaultConfig;

        EformsignToken__c objEformsignToken = new EformsignToken__c();
        objEformsignToken.Name = 'eftkName';
        objEformsignToken.AccessToken__c = 'et54345344535632sdfsdrt32';
        objEformsignToken.RefreshToken__c = 'et54345344535632sdfsdrt3223';
        objEformsignToken.User__c = UserInfo.getUserId();
        objEformsignToken.TokenIssuedDateTime__c = System.today() + 2 ;
        objEformsignToken.ExpireIn__c = 3600;
        insert objEformsignToken;

        EformsignTemplate__c objEformsignTemplate = new EformsignTemplate__c();
        objEformsignTemplate.Name = 'test';
        objEformsignTemplate.ObjectApiName__c = 'Account';
        objEformsignTemplate.TemplateId__c = 'TemplateId';
        insert objEformsignTemplate;

        EformsignDocument__c objEfsDoc = new EformsignDocument__c();
        objEfsDoc.Name =' test';
        objEfsDoc.DocumentId__c =' test1';
        objEfsDoc.DocumentCurrentStatus__c =' 1';
        objEfsDoc.EformsignTemplate__c  = objEformsignTemplate.Id;
        objEfsDoc.TargetObjectRecordId__c = objAcc.Id;
        insert objEfsDoc;

        test.startTest();
        EformsignDocumentManager.Cancelation efCancelation = new EformsignDocumentManager.Cancelation(objEfsDoc.Id, '');
        efCancelation.execute();
        efCancelation.databaseLogic();
        EformsignDocumentManager.Deletion efDeletion = new EformsignDocumentManager.Deletion(objEfsDoc.Id);
        efDeletion.execute();

        test.stopTest();
    }



    // Http response
    private static HttpResponse newResponse(Integer statusCode) {
        HttpResponse response = new HttpResponse();

        response.setStatusCode(statusCode);
        response.setBody('{}');

        response.setHeader('Content-Type', 'application/json');
//        response.setHeader('Content-Disposition', '234');
        response.setHeader('Authorization', 'Bearer ' + 'accessToken');

        String json = '{'+
                '    \"id\": \"233cf8f58dd944ffb32bc5421c5efdf2\",'+
                '    \"document_number\": \"\",'+
                '    \"template\": {'+
                '        \"id\": \"820fde07ff8043a8ae78342dff0ba4ee\",'+
                '        \"name\": \"개인정보제공동의서\"'+
                '    },'+
                '    \"document_name\": \"test docu5123535\",'+
                '    \"creator\": {'+
                '        \"recipient_type\": \"01\",'+
                '        \"id\": \"ben@mz.co.kr\",'+
                '        \"name\": \"이명현\"'+
                '    },'+
                '    \"created_date\": 1698897340459,'+
                '    \"last_editor\": {'+
                '        \"recipient_type\": \"01\",'+
                '        \"id\": \"ben@mz.co.kr\",'+
                '        \"name\": \"이명현\"'+
                '    },'+
                '    \"updated_date\": 1698897340473,'+
                '    \"current_status\": {'+
                '        \"status_type\": \"060\",'+
                '        \"status_doc_type\": \"01\",'+
                '        \"status_doc_detail\": \"060\",'+
                '        \"step_type\": \"05\",'+
                '        \"step_index\": \"2\",'+
                '        \"step_name\": \"고객 동의 요청\",'+
                '        \"step_recipients\": ['+
                '            {'+
                '                \"recipient_type\": \"02\",'+
                '                \"name\": \"테스트 184224\",'+
                '                \"email\": \"chois940713@gmail.com\"'+
                '            }'+
                '        ],'+
                '        \"step_group\": 3,'+
                '        \"expired_date\": 1699502140473,'+
                '        \"_expired\": false'+
                '    },'+
                '    \"fields\": ['+
                '        {'+
                '            \"id\": \"고객명\",'+
                '            \"value\": \"\",'+
                '            \"type\": \"string\"'+
                '        },'+
                '        {'+
                '            \"id\": \"서명\",'+
                '            \"value\": \"X\",'+
                '            \"type\": \"binary\"'+
                '        },'+
                '        {'+
                '            \"id\": \"회사명\",'+
                '            \"value\": \"회사명\",'+
                '            \"type\": \"string\"'+
                '        },'+
                '        {'+
                '            \"id\": \"서명일\",'+
                '            \"value\": \"2023년 11월 02일\",'+
                '            \"type\": \"date_yyyy-MM-dd\"'+
                '        }'+
                '    ],'+
                '    \"next_status\": [],'+
                '    \"previous_status\": [],'+
                '    \"histories\": ['+
                '        {'+
                '            \"step_type\": \"00\",'+
                '            \"step_name\": \"시작\",'+
                '            \"action_type\": \"002\",'+
                '            \"executor\": {'+
                '                \"recipient_type\": \"01\",'+
                '                \"id\": \"ben@mz.co.kr\",'+
                '                \"name\": \"이명현\"'+
                '            },'+
                '            \"executed_date\": 1698897340459,'+
                '            \"comment\": \"테스트 184224\",'+
                '            \"sms_histories\": []'+
                '        },'+
                '        {'+
                '            \"step_type\": \"05\",'+
                '            \"step_name\": \"고객 동의 요청\",'+
                '            \"action_type\": \"060\",'+
                '            \"executor\": {'+
                '                \"recipient_type\": \"01\",'+
                '                \"id\": \"ben@mz.co.kr\",'+
                '                \"name\": \"이명현\"'+
                '            },'+
                '            \"executed_date\": 1698897340473,'+
                '            \"comment\": \"\",'+
                '            \"sms_histories\": []'+
                '        }'+
                '    ],'+
                '    \"recipients\": []'+
                '}';
//        response.setBody('{"api_key": {"company": {"api_url": "' + 'https://kr-api.eformsign.com' + '"}}}');
        response.setBody(json);
        return response;
    }

    // StatusCode 200 Mock
    private class HttpCalloutSuccessMock implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest request) {
            HttpResponse response = newResponse(200);

            return response;
        }
    }
}