PA_Education/TestMenifest/force-app/main/default/objects/EducationalHistory__c/EducationalHistory__c.object-meta.xml
<CustomObject>
    <label>학력사항</label>
    <nameField>
        <label>학교 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/EducationalHistory__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>사원 명</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>학력사항</relationshipLabel>
    <relationshipName>Re_Education</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/PerformProject__c.object-meta.xml
<CustomObject>
    <label>프로젝트 수행팀</label>
    <nameField>
        <displayFormat>PJ-{0000}</displayFormat>
        <label>Seq</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/PerformProject__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>프로젝트에 참여한 사원 이름</inlineHelpText>
    <label>사원 명</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>수행 프로젝트</relationshipLabel>
    <relationshipName>EmployeePerformPjt</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Qualification__c/Qualification__c.object-meta.xml
<CustomObject>
    <label>자격사항</label>
    <nameField>
        <label>자격명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Qualification__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>사원 명</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>자격사항</relationshipLabel>
    <relationshipName>Re_License</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/ResourceProfileController_test.cls
/************************************************************************************
 * File Name   : ResourceProfileController_test.cls
 * Author      : Soyoung.Jung 
 * Date        : 2019.01.14
 * Target      : ResourceProfileController.cls
 * Description : ResourceProfileController.cls Test Class
 * Modification Log
 * ===================================================================================
 * Ver      Date            Author              Modification
 * ===================================================================================
   1.0      2019.01.14      Soyoung.Jung        Create
*************************************************************************************/

@isTest
private class ResourceProfileController_test {

	@isTest
	static void itShould() {
		Test.startTest();

		Employee__c objEmployee = TestObjectCreator.objEmployee;
		insert objEmployee;

		PageReference pageRef = Page.ResourceProfile_doc;
        Test.setCurrentPage(pageRef);

        ApexPages.currentPage().getParameters().put('ids', JSON.serialize(new List<String>{objEmployee.Id}));
        ApexPages.currentPage().getParameters().put('child', JSON.serialize(new List<String>{'Re_Education__r', 'Re_License__r', 'EmployeePerformPjt__r'}));

        ApexPages.StandardController stdController = new ApexPages.StandardController(objEmployee);
        ResourceProfileController controller = new ResourceProfileController(stdController);
        //controller.WrapperEmployee wrap = new controller.WrapperEmployee();
        //ResourceProfileController.WrapperEmployee wrap = new ResourceProfileController.WrapperEmployee();


        System.debug(controller.listWrapperEmployee);
        System.debug(controller.mapSummary);
        System.debug(controller.baseURL);
        System.debug(controller.sFileName);
        System.debug(controller.mapImage);
        System.debug(controller.listEmployee);
        System.debug(controller.mapChildLabel);

		Test.stopTest();
	}

}