PA_Education/TestMenifest/force-app/main/default/objects/GoogleAuthentication__c/GoogleAuthentication__c.object-meta.xml
<CustomObject>
    <description>구글 클라우드 플랫폼 인증 정보</description>
    <label>구글 인증정보</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/GoogleAuthentication__c/fields/AccessTokenUpdated__c.field-meta.xml
<CustomField>
    <fullName>AccessTokenUpdated__c</fullName>
    <label>Access Token Updated</label>
    <type>DateTime</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/GoogleAuthentication__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>GoogleAuthenticationIeI9</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/GoogleContactController_Test.cls
@isTest
private class GoogleContactController_Test {
    
    @isTest(SeeAllData=true)
    public static void isShould() {
        Test.startTest();
        
        GoogleAuthentication__c objGoogleAuthentication = new GoogleAuthentication__c();
        objGoogleAuthentication.User__c = UserInfo.getUserId();
        objGoogleAuthentication.AccessToken__c = 'testAccessToken';
        objGoogleAuthentication.AccessTokenUpdated__c = System.now();
        insert objGoogleAuthentication;
 
        Map<String, Object> paramMap = new Map<String, Object>();
        paramMap.put('name', 'testName TEST');
        paramMap.put('companyName', 'testCompanyName');
        paramMap.put('address', 'testAddress');
        paramMap.put('billingAddress_state', 'testState');
        paramMap.put('billingAddress_street', 'testStreet');
        paramMap.put('billingAddress_city', 'testCity');
        paramMap.put('phone', 'testPhone');
        paramMap.put('email', 'testEmail@test.com');
        paramMap.put('position', 'testPosition');
        paramMap.put('googleId', 'testGoogleId');

        GoogleContactController.getInitialData();
        GoogleContactController.doUpdateAuthentication('updateTestAccessToken');
        GoogleContactController.getContact(Datetime.now().format('yyyy-MM-dd'));
        GoogleContactController.createContact(System.JSON.serialize(paramMap));

        Test.stopTest();
    }
}