PA_Education/TestMenifest/force-app/main/default/objects/SolutionDelivery__c/SolutionDelivery__c.object-meta.xml
<CustomObject>
    <description>Solution Delivery 등록시, Title 및 Description 이 카드형식으로 노출</description>
    <label>Solution Delivery</label>
    <nameField>
        <displayFormat>Solution Delivery-{0000}</displayFormat>
        <label>Solution Delivery Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/SolutionDelivery__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Solution Delivery Name</description>
    <label>솔루션 명</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/RenewalHPServiceSolution_Test.cls
/************************************************************************************
 * File Name   : RenewalHPServiceSolution_Test.cls
 * Author      : SungJu.Kang
 * Date        : 2022. 01. 03
 * Target      : RenewalHPServiceSolution.cls
 * Description : RenewalHPServiceSolution.cls Test Class
 * Modification Log
 * ===================================================================================
 * Ver      Date            Author              Modification
 * ===================================================================================
   1.0      2022. 01. 03   SungJu.Kang            Create
*************************************************************************************/

@IsTest
private class RenewalHPServiceSolution_Test {
    @IsTest
    static void itShould() {
        Test.startTest();
        SolutionDelivery__c objSolutionDelivery = new SolutionDelivery__c();
        objSolutionDelivery.Title__c = 'TestTitle';
        insert objSolutionDelivery;

        RenewalHPServiceSolution.getDeliveries(true);
        RenewalHPServiceSolution.getDeliveries(false);
        //RenewalHPServiceSolution.loadMoreDeliveries();
        RenewalHPServiceSolution.getDeliveryById(objSolutionDelivery.Id, true);
        RenewalHPServiceSolution.getDeliveryById(objSolutionDelivery.Id, false);

        Test.stopTest();

    }
}