PA_Education/TestMenifest/force-app/main/default/objects/SolutionDelivery__c/SolutionDelivery__c.object-meta.xml
<CustomObject>
    <description>Solution Delivery 등록시, Title 및 Description 이 카드형식으로 노출</description>
    <label>Solution Delivery</label>
    <nameField>
        <displayFormat>Solution Delivery-{0000}</displayFormat>
        <label>Solution Delivery Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/SolutionDelivery__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Solution Delivery Description</description>
    <label>내용</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/SolutionDelivery__c/fields/DescriptionEng__c.field-meta.xml
<CustomField>
    <fullName>DescriptionEng__c</fullName>
    <label>주요기능 (English)</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/SolutionDelivery__c/fields/Subtitle__c.field-meta.xml
<CustomField>
    <fullName>Subtitle__c</fullName>
    <description>부제목</description>
    <inlineHelpText>홈페이지 표시 부제목</inlineHelpText>
    <label>부제목</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/SolutionDelivery__c/fields/Summary__c.field-meta.xml
<CustomField>
    <fullName>Summary__c</fullName>
    <label>솔루션 개요</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/SolutionDelivery__c/fields/SummaryEng__c.field-meta.xml
<CustomField>
    <fullName>SummaryEng__c</fullName>
    <label>솔루션 개요 (English)</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/SolutionDelivery__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Solution Delivery Name</description>
    <label>솔루션 명</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/RenewalHPServiceSolution.cls
/**
 * =============================================
 * File Name    : RenewalHPServiceSolution.cls
 * Author       : Chan Kang
 * Group        : Boundary
 * Date         : 2021. 12. 24
 * Description  : 서비스 솔루션 찾기
 * Modification Log
 * ===================================================================================
 * Ver      Date            Author              Modification
 * ===================================================================================
   1.0      2021. 12. 24    Chan Kang           Create
   1.1      2022. 04. 15    Gunwoo Kim          Use optimized query constructor
                                                Add query to fetch data in English
*/

public without sharing class RenewalHPServiceSolution {
  @AuraEnabled
  public static List<SolutionDelivery__c> getDeliveries(Boolean isEnglish) {
    //        List<SolutionDelivery__c> deliveries = [
    //            SELECT Id, Title__c, Summary__c, Description__c FROM SolutionDelivery__c ORDER BY Id DESC LIMIT 5
    //        ];
    //        return deliveries;

    String body = isEnglish
      ? 'Id, Title__c, SummaryEng__c, DescriptionEng__c, SubTitle__c'
      : 'Id, Title__c, Summary__c, Description__c, SubTitle__c';
    String tail = 'SolutionDelivery__c ORDER BY Name ASC LIMIT 5';
    return Database.query(RenewalHPUtility.queryConstructor(body, tail));
  }

  //    @AuraEnabled
  //    public static List<SolutionDelivery__c> loadMoreDeliveries(Boolean isEnglish) {
  //        List<SolutionDelivery__c> deliveries = [
  //                SELECT Id, Title__c, Description__c, Summary__c FROM SolutionDelivery__c ORDER BY Id DESC
  //        ];
  //        return deliveries;
  //
  //    }

  @AuraEnabled
  public static SolutionDelivery__c getDeliveryById(
    String recordId,
    Boolean isEnglish
  ) {
    SolutionDelivery__c delivery = new SolutionDelivery__c();
    if (isEnglish) {
      delivery = [
        SELECT Id, Title__c, DescriptionEng__c, SummaryEng__c, Subtitle__c
        FROM SolutionDelivery__c
        WHERE Id = :recordId
      ];
    } else {
      delivery = [
        SELECT Id, Title__c, Description__c, Summary__c, Subtitle__c
        FROM SolutionDelivery__c
        WHERE Id = :recordId
      ];
    }

    return delivery;
  }
}