PA_Education/TestMenifest/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>프로젝트에 대한 기본정보를 관리하며, Deal Closing 이후 생성한다. 영업담당자가 계약 체결 후 기초 데이터를 작성하며, 프로젝트 진행 중에는 PM이 관리하고, 대금청구/지급 관련 정보는 회계에서 관리한다.</description>
    <label>프로젝트</label>
    <nameField>
        <label>프로젝트 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/ProjectBudget__c/ProjectBudget__c.object-meta.xml
<CustomObject>
    <label>프로젝트 비용 예산</label>
    <nameField>
        <label>프로젝트 비용 예산 신청명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/ProjectBudget__c/fields/BusinessManager__c.field-meta.xml
<CustomField>
    <fullName>BusinessManager__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>작성자가 사업부장일 경우에 체크</inlineHelpText>
    <label>사업부장</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ProjectBudget__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>프로젝트</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>프로젝트 비용 예산</relationshipLabel>
    <relationshipName>ProjectBudget</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ProjectBudget__c/fields/ru_TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>ru_TotalAmount__c</fullName>
    <label>총 예산 금액</label>
    <summarizedField>ProjectBudgetDetail__c.Amount__c</summarizedField>
    <summaryForeignKey>ProjectBudgetDetail__c.ProjectBudget__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ProjectBudget__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>승인상태</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>작성중</fullName>
                <default>true</default>
                <label>작성중</label>
            </value>
            <value>
                <fullName>승인중</fullName>
            </value>
            <value>
                <fullName>승인완료</fullName>
            </value>
            <value>
                <fullName>반려</fullName>
            </value>
            <value>
                <fullName>회수</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ProjectBudgetDetail__c/ProjectBudgetDetail__c.object-meta.xml
<CustomObject>
    <label>프로젝트 비용 예산 상세</label>
    <nameField>
        <displayFormat>P-EXP-{YY}{MM}-{000}</displayFormat>
        <label>프로젝트 예산</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/ProjectBudgetDetail__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <formula>UnitPrice__c  *  Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>단가 * 수량</inlineHelpText>
    <label>금액</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ProjectBudgetDetail__c/fields/Category2__c.field-meta.xml
<CustomField>
    <fullName>Category2__c</fullName>
    <label>예산 구분</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Category2</valueSetName>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ProjectBudgetDetail__c/fields/Memo__c.field-meta.xml
<CustomField>
    <fullName>Memo__c</fullName>
    <inlineHelpText>비용 에산을 산출한 근거를 기록. ex) 인원수 3명 * 주5일 * 2달 * 2회</inlineHelpText>
    <label>비고(산출근거)</label>
    <type>TextArea</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ProjectBudgetDetail__c/fields/ProjectBudget__c.field-meta.xml
<CustomField>
    <fullName>ProjectBudget__c</fullName>
    <label>프로젝트 비용 예산</label>
    <referenceTo>ProjectBudget__c</referenceTo>
    <relationshipLabel>프로젝트 비용 예산 상세</relationshipLabel>
    <relationshipName>ProjectBudgetDetail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ProjectBudgetDetail__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>수량</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/ProjectBudgetDetail__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <defaultValue>0</defaultValue>
    <label>단가</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/ProjectBudgetController.cls
public class ProjectBudgetController {
	@AuraEnabled
	public static Map<String, Object> getInitData(Id recordId, Id parentId) {
        //String objectType = recordId.getsobjecttype().getDescribe().getLabel();
        ProjectBudget__c prjBgt; 
        List<ProjectBudgetDetail__c> prjBgtDtlLst;
        if(recordId == null){
            Project__c prj = [SELECT Id, Name FROM Project__c WHERE Id = :parentId limit 1];
            prjBgt = new ProjectBudget__c(Name = prj.Name + ' 예산 신청', Project__c = prj.Id, Status__c = '작성중');
        }
        else{
            prjBgt = [SELECT Id, Name, Status__c, Project__c,ru_TotalAmount__c, BusinessManager__c FROM ProjectBudget__c WHERE Id = :recordId];
            prjBgtDtlLst = [SELECT Id, Amount__c, UnitPrice__c, Memo__c, Quantity__c, Category2__c, ProjectBudget__c FROM ProjectBudgetDetail__c WHERE ProjectBudget__c = :recordId];
        }
        Map<String, Object> mapReturnValue = new Map<String, Object>{
        	'prjBgt' => prjBgt,
            'prjBgtDtlLst' => prjBgtDtlLst,
            'typePckLst' => getPicklistValue('ProjectBudgetDetail__c', 'Category2__c'),
            'bizMngHlpTxt' => ProjectBudget__c.BusinessManager__c.getDescribe().getInlineHelpText()
		};
        return mapReturnValue;
    }
    
     public static List<Map<String, String>> getPicklistValue(String sObjectStr, String fieldName) {
		List<Map<String, String>> options = new List<Map<String, String>>();
		
		Schema.SObjectType sobject_type = Schema.getGlobalDescribe().get(sObjectStr);
		Schema.DescribeSObjectResult sobjectDescribe = sobject_type.getDescribe();
		Map<String, Schema.SObjectField> fieldMap = sobjectDescribe.fields.getMap();
		
		List<Schema.PicklistEntry> pickListValues = fieldMap.get(fieldName).getDescribe().getPickListValues();
		
		for(Schema.PicklistEntry pickListEntry : pickListValues) { 
			if (pickListEntry.isActive()) options.add(new Map<String, String>{'value' => pickListEntry.getValue(), 'label' => pickListEntry.getLabel(), 'default' => String.valueOf(pickListEntry.isDefaultValue())}); 
		}
		
		return options;
	}
    @AuraEnabled
	public static String doSave(ProjectBudget__c prjBgt, List<ProjectBudgetDetail__c> prjBgtDtlLst, Id recordId) {

		try {
			if(prjBgtDtlLst == null)
                prjBgtDtlLst = new List<ProjectBudgetDetail__c>();
			
			upsert prjBgt;
            if(recordId == null){
                for(ProjectBudgetDetail__c prjBgtDtl : prjBgtDtlLst){
                    prjBgtDtl.ProjectBudget__c = prjBgt.Id;
                }
            }
            upsert prjBgtDtlLst;
			return '저장되었습니다. / '+ prjBgt.Name;		

		} catch(DMLException dmlExcep) {
			System.debug('dmlExcep.getMessage() : ' + dmlExcep.getMessage());
			return '에러가 발생했습니다. / '+dmlExcep.getMessage();
		} 
	}
}