PA_Education/TestMenifest/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>프로젝트에 대한 기본정보를 관리하며, Deal Closing 이후 생성한다. 영업담당자가 계약 체결 후 기초 데이터를 작성하며, 프로젝트 진행 중에는 PM이 관리하고, 대금청구/지급 관련 정보는 회계에서 관리한다.</description>
    <label>프로젝트</label>
    <nameField>
        <label>프로젝트 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/fields/Completed__c.field-meta.xml
<CustomField>
    <fullName>Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>프로젝트가 종료되면 체크함.</inlineHelpText>
    <label>완료 여부</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>종료 일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/fields/OpeningDate__c.field-meta.xml
<CustomField>
    <fullName>OpeningDate__c</fullName>
    <label>오픈 일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/fields/PM__c.field-meta.xml
<CustomField>
    <fullName>PM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>프로젝트 관리자</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PM</relationshipName>
    <type>Lookup</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/fields/PMEmail__c.field-meta.xml
<CustomField>
    <fullName>PMEmail__c</fullName>
    <label>PMEmail</label>
    <type>Email</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/fields/Salesforce_Industry__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Industry__c</fullName>
    <label>Salesforce 산업분류</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>자동차</fullName>
            </value>
            <value>
                <fullName>통신</fullName>
            </value>
            <value>
                <fullName>소비재</fullName>
            </value>
            <value>
                <fullName>교육</fullName>
            </value>
            <value>
                <fullName>에너지 및 유틸리티</fullName>
            </value>
            <value>
                <fullName>금융 서비스</fullName>
            </value>
            <value>
                <fullName>공공부문</fullName>
            </value>
            <value>
                <fullName>헬프케어 및 생명과학</fullName>
            </value>
            <value>
                <fullName>제조업</fullName>
            </value>
            <value>
                <fullName>미디어</fullName>
            </value>
            <value>
                <fullName>비영리</fullName>
            </value>
            <value>
                <fullName>리테일</fullName>
            </value>
            <value>
                <fullName>기술</fullName>
            </value>
            <value>
                <fullName>운송 및 호스피탈리티</fullName>
            </value>
            <value>
                <fullName>직접입력</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/fields/Salesforce_Product__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Product__c</fullName>
    <label>Salesforce 제품분류</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales Cloud</fullName>
            </value>
            <value>
                <fullName>Service Cloud</fullName>
            </value>
            <value>
                <fullName>Marketing Cloud</fullName>
            </value>
            <value>
                <fullName>Commerce Cloud</fullName>
            </value>
            <value>
                <fullName>Tableau</fullName>
            </value>
            <value>
                <fullName>MuleSoft</fullName>
            </value>
            <value>
                <fullName>Salesforce Platform</fullName>
            </value>
            <value>
                <fullName>Net Zero Cloud</fullName>
            </value>
            <value>
                <fullName>Nonprofit Cloud</fullName>
            </value>
            <value>
                <fullName>Experience Cloud</fullName>
            </value>
            <value>
                <fullName>직접입력</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Project__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>착수 일자</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/Project_tr_Test.cls
/**
 * Created by yj.kim on 2023-07-12.
 */
@IsTest
public with sharing class Project_tr_Test {
    @IsTest
    static void testUpdate(){

        User userObj = TestObjectCreator.objUser;
        insert userObj;

        User userObj2 = new User();
        userObj2.Email               = 'test2@test.com';
        userObj2.LastName            = 'testUser2';
        userObj2.FirstName           = 'testUser2';
        userObj2.ProfileId           = UserInfo.getProfileId();
        userObj2.Emailencodingkey    = 'ks_c_5601-1987';
        userObj2.Languagelocalekey   = 'en_US';
        userObj2.IsActive            = true;
        userObj2.Username            = 'testUser2@daeunextier.com';
        userObj2.Alias               = 'user2';
        userObj2.CommunityNickname   = 'user2';
        userObj2.TimeZoneSidKey      = 'Asia/Seoul';
        userObj2.LocaleSidKey        = 'ko_KR';
        insert userObj2;

        Project__c projectObj = new Project__c();
        projectObj.Name = 'testProject';
        projectObj.PMEmail__c = 'test@daeunextier.com';
        projectObj.Salesforce_Product__c = 'Sales Cloud';
        projectObj.Salesforce_Industry__c = '자동차';
        projectObj.OpeningDate__c = Date.today().addDays(60);
        projectObj.StartDate__c = Date.today();
        projectObj.EndDate__c = Date.today().addDays(60);
        projectObj.PM__c = userObj.Id;
        projectObj.Completed__c = false;
        insert projectObj;

        Test.startTest();

        Project__c obj = new Project__c();
        obj.Id = projectObj.Id;
        obj.PM__c = userObj2.Id;
        obj.Completed__c = true;
        update obj;

        Test.stopTest();
    }

}