PA_Education/TestMenifest/force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>강의 Object</description>
    <label>Training</label>
    <nameField>
        <displayFormat>강의-{0000}</displayFormat>
        <label>강의 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

ListViewButton/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/AddressNumber__c.field-meta.xml
<CustomField>
    <fullName>AddressNumber__c</fullName>
    <label>우편번호</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Birthday__c.field-meta.xml
<CustomField>
    <fullName>Birthday__c</fullName>
    <label>생년월일</label>
    <type>Date</type>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>계급</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Clear__c.field-meta.xml
<CustomField>
    <fullName>Clear__c</fullName>
    <label>금품청산 등</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/CurrentAddress__c.field-meta.xml
<CustomField>
    <fullName>CurrentAddress__c</fullName>
    <label>주거지 주소</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/Dependents__c.field-meta.xml
<CustomField>
    <fullName>Dependents__c</fullName>
    <label>부양가족</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/DischargeDate__c.field-meta.xml
<CustomField>
    <fullName>DischargeDate__c</fullName>
    <label>전역일</label>
    <type>Date</type>
</CustomField>

ListViewButton/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/DismissalDate__c.field-meta.xml
<CustomField>
    <fullName>DismissalDate__c</fullName>
    <label>해고일자</label>
    <type>Date</type>
</CustomField>

ListViewButton/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/EnglishName__c.field-meta.xml
<CustomField>
    <fullName>EnglishName__c</fullName>
    <label>영문명</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ListViewButton/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>성별</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>남성</fullName>
            </value>
            <value>
                <fullName>여성</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/IdNumber__c.field-meta.xml
<CustomField>
    <fullName>IdNumber__c</fullName>
    <description>주민등록번호</description>
    <inlineHelpText>123456-1234567</inlineHelpText>
    <label>주민등록번호</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

ListViewButton/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/JoinArmyDate__c.field-meta.xml
<CustomField>
    <fullName>JoinArmyDate__c</fullName>
    <label>입대일</label>
    <type>Date</type>
</CustomField>

ListViewButton/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/MilitaryServiceDiv__c.field-meta.xml
<CustomField>
    <fullName>MilitaryServiceDiv__c</fullName>
    <label>병역구분</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>해당없음</fullName>
                <default>true</default>
                <label>해당없음</label>
            </value>
            <value>
                <fullName>필</fullName>
            </value>
            <value>
                <fullName>미필</fullName>
            </value>
            <value>
                <fullName>면제</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ListViewButton/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/MilitaryType__c.field-meta.xml
<CustomField>
    <fullName>MilitaryType__c</fullName>
    <label>군별</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>육군</fullName>
            </value>
            <value>
                <fullName>공군</fullName>
            </value>
            <value>
                <fullName>해군</fullName>
            </value>
            <value>
                <fullName>해병대</fullName>
            </value>
            <value>
                <fullName>상근예비역</fullName>
            </value>
            <value>
                <fullName>의무경찰</fullName>
            </value>
            <value>
                <fullName>의무경찰(해양)</fullName>
            </value>
            <value>
                <fullName>의무소방</fullName>
            </value>
            <value>
                <fullName>사회복무요원</fullName>
            </value>
            <value>
                <fullName>예술·체육요원</fullName>
            </value>
            <value>
                <fullName>국제협력봉사요원</fullName>
            </value>
            <value>
                <fullName>전문연구요원</fullName>
            </value>
            <value>
                <fullName>산업기능요원(현역)</fullName>
            </value>
            <value>
                <fullName>산업기능요원(보충역)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/MilitaryTypeDescription__c.field-meta.xml
<CustomField>
    <fullName>MilitaryTypeDescription__c</fullName>
    <label>미필사유</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>사유</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

ListViewButton/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/UpdateDate__c.field-meta.xml
<CustomField>
    <fullName>UpdateDate__c</fullName>
    <label>근로계약갱신일</label>
    <type>Date</type>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>사원 Object를 User Object간 Relationship 생성</inlineHelpText>
    <label>사용자 명</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/WeddingAnniversary__c.field-meta.xml
<CustomField>
    <fullName>WeddingAnniversary__c</fullName>
    <label>결혼기념일</label>
    <type>Date</type>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/classes/EmployeeController.cls
public with sharing class EmployeeController {

    @AuraEnabled
    public static Boolean isCheck(Id recordId){
        String userId=UserInfo.getUserId();
        Boolean flag=false;

        List<Employee__c> listUserName=new List<Employee__c>();
        listUserName=[
            SELECT OwnerId
            FROM Employee__c
            WHERE Id=:recordId
        ];

        if(listUserName[0].OwnerId==userId){
            flag=true;
        }

        return flag;
    }

    @AuraEnabled
    public static Employee__c getEmployeeSecret(){
        Id recordId='a2O0k000004DqJ4EAK';
        List<Employee__c> listEmp=new List<Employee__c>();

        listEmp=[
            SELECT Id, Gender__c, CurrentAddress__c, Birthday__c, EnglishName__c, 
            IdNumber__c, AddressNumber__c, WeddingAnniversary__c,
            JoinArmyDate__c, DischargeDate__c, MilitaryServiceDiv__c, 
            MilitaryType__c, Class__c, MilitaryTypeDescription__c, 
            Dependents__c, UpdateDate__c, DismissalDate__c, Reason__c, 
            Clear__c, OwnerId, User__c
            FROM Employee__c
            where Id=:recordId
        ];

        System.debug(listEmp[0]);
        return listEmp[0];
    }

    @AuraEnabled(cacheable=true)
    public static List<String> getPicklistValues(String objectName, String fieldName) {
        List<String> picklistValues = new List<String>();
            
        // Describe the object's field and get picklist values
        Schema.DescribeFieldResult fieldResult = Schema.getGlobalDescribe().get(objectName).getDescribe().fields.getMap().get(fieldName).getDescribe();
        List<Schema.PicklistEntry> picklistEntries = fieldResult.getPicklistValues();
            
        // Add each picklist value to the list
        for (Schema.PicklistEntry entry : picklistEntries) {
            if (entry.isActive()) {
                picklistValues.add(entry.getLabel()); // or use entry.getValue() if you need the API name
            }
        }
            
        return picklistValues;
    }

    @AuraEnabled
    public static Boolean updateEmpInfo(Employee__c employee){
        try {
            System.debug('emp: '+employee.Gender__c);
            update employee;
            return true;
        } catch (Exception e) {
            return false;
        }
    }
    
}