PA_Education/TestMenifest/force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>강의 Object</description>
    <label>Training</label>
    <nameField>
        <displayFormat>강의-{0000}</displayFormat>
        <label>강의 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

ListViewButton/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/AddressNumber__c.field-meta.xml
<CustomField>
    <fullName>AddressNumber__c</fullName>
    <label>우편번호</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Birthday__c.field-meta.xml
<CustomField>
    <fullName>Birthday__c</fullName>
    <label>생년월일</label>
    <type>Date</type>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>계급</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Clear__c.field-meta.xml
<CustomField>
    <fullName>Clear__c</fullName>
    <label>금품청산 등</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/CurrentAddress__c.field-meta.xml
<CustomField>
    <fullName>CurrentAddress__c</fullName>
    <label>주거지 주소</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/Dependents__c.field-meta.xml
<CustomField>
    <fullName>Dependents__c</fullName>
    <label>부양가족</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/DischargeDate__c.field-meta.xml
<CustomField>
    <fullName>DischargeDate__c</fullName>
    <label>전역일</label>
    <type>Date</type>
</CustomField>

ListViewButton/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/DismissalDate__c.field-meta.xml
<CustomField>
    <fullName>DismissalDate__c</fullName>
    <label>해고일자</label>
    <type>Date</type>
</CustomField>

ListViewButton/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/EnglishName__c.field-meta.xml
<CustomField>
    <fullName>EnglishName__c</fullName>
    <label>영문명</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ListViewButton/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>성별</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>남성</fullName>
            </value>
            <value>
                <fullName>여성</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/IdNumber__c.field-meta.xml
<CustomField>
    <fullName>IdNumber__c</fullName>
    <description>주민등록번호</description>
    <inlineHelpText>123456-1234567</inlineHelpText>
    <label>주민등록번호</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

ListViewButton/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/JoinArmyDate__c.field-meta.xml
<CustomField>
    <fullName>JoinArmyDate__c</fullName>
    <label>입대일</label>
    <type>Date</type>
</CustomField>

ListViewButton/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/MilitaryServiceDiv__c.field-meta.xml
<CustomField>
    <fullName>MilitaryServiceDiv__c</fullName>
    <label>병역구분</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>해당없음</fullName>
                <default>true</default>
                <label>해당없음</label>
            </value>
            <value>
                <fullName>필</fullName>
            </value>
            <value>
                <fullName>미필</fullName>
            </value>
            <value>
                <fullName>면제</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ListViewButton/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/MilitaryType__c.field-meta.xml
<CustomField>
    <fullName>MilitaryType__c</fullName>
    <label>군별</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>육군</fullName>
            </value>
            <value>
                <fullName>공군</fullName>
            </value>
            <value>
                <fullName>해군</fullName>
            </value>
            <value>
                <fullName>해병대</fullName>
            </value>
            <value>
                <fullName>상근예비역</fullName>
            </value>
            <value>
                <fullName>의무경찰</fullName>
            </value>
            <value>
                <fullName>의무경찰(해양)</fullName>
            </value>
            <value>
                <fullName>의무소방</fullName>
            </value>
            <value>
                <fullName>사회복무요원</fullName>
            </value>
            <value>
                <fullName>예술·체육요원</fullName>
            </value>
            <value>
                <fullName>국제협력봉사요원</fullName>
            </value>
            <value>
                <fullName>전문연구요원</fullName>
            </value>
            <value>
                <fullName>산업기능요원(현역)</fullName>
            </value>
            <value>
                <fullName>산업기능요원(보충역)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/MilitaryTypeDescription__c.field-meta.xml
<CustomField>
    <fullName>MilitaryTypeDescription__c</fullName>
    <label>미필사유</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>직급</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>총괄사장</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>대표이사</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>센터장</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>감사</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>부사장</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>전무</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>상무</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>수석</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>이사</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>부장</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>책임</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>차장</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>과장</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>대리</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>선임</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>선임(수습)</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>사원</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>사원(수습)</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>인턴</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>사유</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

ListViewButton/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/UpdateDate__c.field-meta.xml
<CustomField>
    <fullName>UpdateDate__c</fullName>
    <label>근로계약갱신일</label>
    <type>Date</type>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>사원 Object를 User Object간 Relationship 생성</inlineHelpText>
    <label>사용자 명</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/WeddingAnniversary__c.field-meta.xml
<CustomField>
    <fullName>WeddingAnniversary__c</fullName>
    <label>결혼기념일</label>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/sensitiveInformationViewController_test.cls
@isTest
private class sensitiveInformationViewController_test {

    static String uniqueUsername;
    static String uniqueNickname;

    @testSetup 
    static void setupTestData() { 
        String orgId = UserInfo.getOrganizationId();
        String dateString = String.valueOf(Datetime.now()).replace(' ', '').replace(':', '').replace('-', '');
        Integer randomInt = Integer.valueOf(Math.rint(Math.random() * 1000000));
        uniqueUsername = orgId + dateString + randomInt + '@test' + orgId + '.org';  
        uniqueNickname = orgId + dateString;

        UserRole r = [SELECT Id FROM UserRole WHERE Name='Platform Member'];
        Profile p = [SELECT Id FROM Profile WHERE Name='Daeu Nextier Employee'];
        
        User testUser = new User(
            LastName = '대유',     
            Alias = '대유',
            Email = 'Daeu@nextier.com',
            Username = uniqueUsername,
            CommunityNickname = uniqueNickname,
            UserRoleId = r.Id, 
            ProfileId = p.Id,  
            EmailEncodingKey = 'UTF-8', 
            TimeZoneSidKey = 'Asia/Seoul', 
            LocaleSidKey = 'ko_KR',  
            LanguageLocaleKey = 'ko', 
            CurrencyIsoCode = 'KRW', 
            IsActive = true,  
            Position__c = '13' 
        );

        insert testUser;

        System.runAs(testUser) { //System.DmlException
            Employee__c employee = new Employee__c(
                User__c = testUser.Id,
                Gender__c = '남성',
                CurrentAddress__c = '상원12길34',
                Birthday__c = Date.newInstance(1990, 1, 1),
                EnglishName__c = 'Daeu',
                IdNumber__c = '123456-1234567',
                AddressNumber__c = '01010',
                WeddingAnniversary__c = Date.newInstance(2015, 5, 10),
                JoinArmyDate__c = Date.newInstance(2010, 6, 1),
                DischargeDate__c = Date.newInstance(2012, 6, 1),
                MilitaryServiceDiv__c = '미필',
                MilitaryType__c = '공군',
                Class__c = '상병',
                MilitaryTypeDescription__c = '가나다라마',
                Dependents__c = '4',
                UpdateDate__c = Date.newInstance(2018, 11, 01),
                DismissalDate__c = Date.newInstance(2025, 11, 01),
                Reason__c = '건강 악화',
                Clear__c = '청산 완료',
                Position__c = '13',  // 직급을 채워줘야 함
                OwnerId = testUser.Id
            );

            insert employee;

            // PermissionSetAssignment 추가
            PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'ViewPersonalInfoPermission' LIMIT 1];
            PermissionSetAssignment psa = new PermissionSetAssignment(
                AssigneeId = testUser.Id,
                PermissionSetId = ps.Id
            );
            insert psa;
        }
    }

    @isTest
    static void testGetEmpInfo() {
        setupTestData();
        
        User currentUser = [SELECT Id FROM User WHERE Username =: uniqueUsername LIMIT 1];
        Employee__c employee = [SELECT Id FROM Employee__c WHERE User__c =: currentUser.Id LIMIT 1];
        
        System.runAs(currentUser) {
            Test.startTest();
            Employee__c result = sensitiveInformationViewController.getEmpInfo(employee.Id);
            Test.stopTest();

            System.assertNotEquals(null, result, '직원정보가 null값');
            System.assertEquals('남성', result.Gender__c, '성별이 남성으로 나와야함');
            System.assertEquals('Daeu', result.EnglishName__c, '영어이름이 Daeu로 나와야함');
        }
    }

    @isTest
    static void testIsCheck() {
        setupTestData();

        User currentUser = [SELECT Id FROM User WHERE Username =: uniqueUsername LIMIT 1];
        Employee__c employee = [SELECT Id, User__c FROM Employee__c WHERE User__c = :currentUser.Id LIMIT 1];

        // 테스트용 UserRole 변경 (CEO 또는 관리부)
        UserRole ceoRole = [SELECT Id FROM UserRole WHERE Name='CEO' LIMIT 1];
        currentUser.UserRoleId = ceoRole.Id;
        update currentUser;
        
        System.runAs(currentUser) {
            Test.startTest();
            Boolean result = sensitiveInformationViewController.isCheck(employee.Id);
            Test.stopTest();

            System.assertEquals(true, result, '로그인한 유저의 Id와 Emp 레코드의 User__c Id값이 일치 또는 역할이 CEO일 경우');
        }
    }

    @isTest
    static void testUpdateEmpInfo() {
        setupTestData();
        
        User currentUser = [SELECT Id FROM User WHERE Username =: uniqueUsername LIMIT 1];
        Employee__c employee = [SELECT Id, Gender__c FROM Employee__c WHERE User__c = :currentUser.Id LIMIT 1];
        employee.Gender__c = '여성';  

        System.runAs(currentUser) {
            Test.startTest();
            Boolean result = sensitiveInformationViewController.updateEmpInfo(employee);
            Test.stopTest();

            System.assertEquals(true, result, '업데이트 성공');
            System.assertEquals('여성', [SELECT Gender__c FROM Employee__c WHERE Id = :employee.Id].Gender__c, '성별이 여성으로 데이터가 나와야함');
        }
    }

    @isTest
    static void testGetPicklistValues() {
        setupTestData();

        User currentUser = [SELECT Id FROM User WHERE Username =: uniqueUsername LIMIT 1];

        System.runAs(currentUser) {
            Test.startTest();
            Map<String, List<String>> result = sensitiveInformationViewController.getPicklistValues();
            Test.stopTest();

            System.assertNotEquals(null, result, 'pickValue가 Null값이기에 오류발생');
            System.assert(result.containsKey('Gender__c'), '픽리스트에 성별에 대한 리스트가 나와야함');
            System.assert(result.containsKey('MilitaryServiceDiv__c'), '픽리스트에 병역구분에 대한 리스트가 나와야함');
            System.assert(result.containsKey('MilitaryType__c'), '픽리스트에 군별 대한 리스트가 나와야함');
        }
    }

    @isTest
    static void testHasPermissionSet() {
        setupTestData();

        User currentUser = [SELECT Id FROM User WHERE Username =: uniqueUsername LIMIT 1];
        
        System.runAs(currentUser) {
            Test.startTest();
            Boolean result = sensitiveInformationViewController.hasPermissionSet();
            Test.stopTest();

            System.assertEquals(true, result, 'PermissionSet이 제대로 할당되었는지 확인');
        }
    }
}