PA_Education/TestMenifest/force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>강의 Object</description>
    <label>Training</label>
    <nameField>
        <displayFormat>강의-{0000}</displayFormat>
        <label>강의 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>사원 명</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

ListViewButton/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/AddressNumber__c.field-meta.xml
<CustomField>
    <fullName>AddressNumber__c</fullName>
    <label>우편번호</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Birthday__c.field-meta.xml
<CustomField>
    <fullName>Birthday__c</fullName>
    <label>생년월일</label>
    <type>Date</type>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>계급</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Clear__c.field-meta.xml
<CustomField>
    <fullName>Clear__c</fullName>
    <label>금품청산 등</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/CurrentAddress__c.field-meta.xml
<CustomField>
    <fullName>CurrentAddress__c</fullName>
    <label>주거지 주소</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/Dependents__c.field-meta.xml
<CustomField>
    <fullName>Dependents__c</fullName>
    <label>부양가족</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/DischargeDate__c.field-meta.xml
<CustomField>
    <fullName>DischargeDate__c</fullName>
    <label>전역일</label>
    <type>Date</type>
</CustomField>

ListViewButton/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/DismissalDate__c.field-meta.xml
<CustomField>
    <fullName>DismissalDate__c</fullName>
    <label>해고일자</label>
    <type>Date</type>
</CustomField>

ListViewButton/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/EnglishName__c.field-meta.xml
<CustomField>
    <fullName>EnglishName__c</fullName>
    <label>영문명</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ListViewButton/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>성별</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>남성</fullName>
            </value>
            <value>
                <fullName>여성</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/IdNumber__c.field-meta.xml
<CustomField>
    <fullName>IdNumber__c</fullName>
    <description>주민등록번호</description>
    <inlineHelpText>123456-1234567</inlineHelpText>
    <label>주민등록번호</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

ListViewButton/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/JoinArmyDate__c.field-meta.xml
<CustomField>
    <fullName>JoinArmyDate__c</fullName>
    <label>입대일</label>
    <type>Date</type>
</CustomField>

ListViewButton/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/MilitaryServiceDiv__c.field-meta.xml
<CustomField>
    <fullName>MilitaryServiceDiv__c</fullName>
    <label>병역구분</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>해당없음</fullName>
                <default>true</default>
                <label>해당없음</label>
            </value>
            <value>
                <fullName>필</fullName>
            </value>
            <value>
                <fullName>미필</fullName>
            </value>
            <value>
                <fullName>면제</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ListViewButton/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/MilitaryType__c.field-meta.xml
<CustomField>
    <fullName>MilitaryType__c</fullName>
    <label>군별</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>육군</fullName>
            </value>
            <value>
                <fullName>공군</fullName>
            </value>
            <value>
                <fullName>해군</fullName>
            </value>
            <value>
                <fullName>해병대</fullName>
            </value>
            <value>
                <fullName>상근예비역</fullName>
            </value>
            <value>
                <fullName>의무경찰</fullName>
            </value>
            <value>
                <fullName>의무경찰(해양)</fullName>
            </value>
            <value>
                <fullName>의무소방</fullName>
            </value>
            <value>
                <fullName>사회복무요원</fullName>
            </value>
            <value>
                <fullName>예술·체육요원</fullName>
            </value>
            <value>
                <fullName>국제협력봉사요원</fullName>
            </value>
            <value>
                <fullName>전문연구요원</fullName>
            </value>
            <value>
                <fullName>산업기능요원(현역)</fullName>
            </value>
            <value>
                <fullName>산업기능요원(보충역)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/MilitaryTypeDescription__c.field-meta.xml
<CustomField>
    <fullName>MilitaryTypeDescription__c</fullName>
    <label>미필사유</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Employee__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>사유</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

ListViewButton/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/UpdateDate__c.field-meta.xml
<CustomField>
    <fullName>UpdateDate__c</fullName>
    <label>근로계약갱신일</label>
    <type>Date</type>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>사원 Object를 User Object간 Relationship 생성</inlineHelpText>
    <label>사용자 명</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/objects/Employee__c/fields/WeddingAnniversary__c.field-meta.xml
<CustomField>
    <fullName>WeddingAnniversary__c</fullName>
    <label>결혼기념일</label>
    <type>Date</type>
</CustomField>

DaeuOrg/PrintPdfAndSave/force-app/main/default/classes/sensitiveInformationViewController.cls
public with sharing class sensitiveInformationViewController {
    @AuraEnabled
    public static Employee__c getEmpInfo(Id recordId) {
 
        // Id currentUserId = UserInfo.getUserId();
        //Id currentUserId='0052v00000fjMgvAAE';
 
        Employee__c employee = [SELECT Id, Gender__c, CurrentAddress__c, Birthday__c, EnglishName__c,
                                       IdNumber__c, AddressNumber__c, WeddingAnniversary__c,
                                       JoinArmyDate__c, DischargeDate__c, MilitaryServiceDiv__c,
                                       MilitaryType__c, Class__c, MilitaryTypeDescription__c,
                                       Dependents__c, UpdateDate__c, DismissalDate__c, Reason__c,
                                       Clear__c, OwnerId, User__c
                                FROM Employee__c
                                WHERE Id = :recordId //0052v00000fjMgvAAE(User__c) == 0052v00000fjMgvAAE
                                LIMIT 1];
 
        if (employee == null) {
            return null;
        }
 
        return employee;
    }
 
    @AuraEnabled
    public static Boolean isCheck(Id recordId) {
        Id userId = UserInfo.getUserId(); // 현재 로그인한 사용자 ID
        // Id userId = '0052v00000jUvMzAAK'; // 현재 로그인한 사용자 ID
   
        Boolean flag = false;
   
        // Employee__c 레코드에서 해당 기록의 User__c 필드 값 가져오기
        List<Employee__c> listUserName = [
            SELECT User__c
            FROM Employee__c
            WHERE Id = :recordId
            // WHERE Id = : ('a2O0k000004DqJ4EAK')
        ];
   
        // 사용자의 역할이 'CEO' 또는 '관리부'인지 확인
        List<User> listUser = [
            SELECT Id, UserRole.Name
            FROM User
            WHERE UserRole.Name IN ('CEO', '관리부') AND Id = :userId
        ];
   
        // 사용자가 'ViewPersonalInfoPermission' 권한을 갖고 있는지 확인
        List<PermissionSetAssignment> listUserPer = [
            SELECT PermissionSet.Id, PermissionSet.Name
            FROM PermissionSetAssignment
            WHERE Assignee.Id = :userId
            AND PermissionSet.Name = 'ViewPersonalInfoPermission'
            LIMIT 1
        ];
   
        // 사용자 이름이 일치하거나, 역할이 맞거나, 권한이 맞으면 flag를 true로 설정
        Boolean isUser = !listUserName.isEmpty() && listUserName[0].User__c == userId;
        Boolean isRoleValid = !listUser.isEmpty();
        Boolean isPermiValid = !listUserPer.isEmpty();
        System.debug(isUser);
        System.debug(isRoleValid);
        System.debug(isPermiValid);
        // 조건을 만족하면 flag를 true로 설정
        if (isUser || isRoleValid || isPermiValid) {
            flag = true;
        }
        System.debug(flag);
       
        return flag;  // flag를 반환
    }
   
   
 
    @AuraEnabled
    public static Boolean updateEmpInfo(Employee__c employee){
        try {
            update employee;
            return true;
        } catch (Exception e) {
            return false;
        }
    }
   
    @AuraEnabled
    public static Boolean hasPermissionSet() {
        Id userId = UserInfo.getUserId();
        // Id userId = '0052v00000jUvMzAAK';
 
        try {
            // 사용자에게 할당된 PermissionSet을 쿼리
            PermissionSetAssignment psa = [
                SELECT PermissionSet.Id, PermissionSet.Name
                FROM PermissionSetAssignment
                WHERE Assignee.Id = :userId
                AND PermissionSet.Name = 'ViewPersonalInfoPermission'
                LIMIT 1
            ];
           
            // 만약 권한 세트가 존재하면 true 반환
            if (psa != null) {
                return true;
            } else {
                return false;
            }
        } catch (QueryException e) {
            // 쿼리에서 예외가 발생하면 false를 반환
            System.debug('Error occurred while querying PermissionSetAssignment: ' + e.getMessage());
            return false;
        }
    }
 
    @AuraEnabled
    public static Map<String, List<String>> getPicklistValues() {
        Map<String, List<String>> picklistMap = new Map<String, List<String>>();
 
        List<String> picklistFields = new List<String>{ 'Gender__c', 'MilitaryServiceDiv__c', 'MilitaryType__c' };
 
        for (String fieldName : picklistFields) {
            List<String> options = new List<String>();
            Schema.DescribeFieldResult fieldResult = Schema.SObjectType.employee__c.fields.getMap().get(fieldName).getDescribe();
            List<Schema.PicklistEntry> picklist = fieldResult.getPicklistValues();
           
            for (Schema.PicklistEntry entry : picklist) {
                options.add(entry.getLabel() + ':' + entry.getValue()); // Label:Value 형식으로 저장
            }
           
            picklistMap.put(fieldName, options); // 필드 이름을 키로 사용
        }
        System.debug('picklistMap : '+picklistMap);
 
        return picklistMap;
    }
}