PA_Education/TestMenifest/force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>강의 Object</description>
    <label>Training</label>
    <nameField>
        <displayFormat>강의-{0000}</displayFormat>
        <label>강의 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Class__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>과정 시작시간</description>
    <label>시작시간</label>
    <type>DateTime</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Class__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>진행하는 과정의 이름</description>
    <label>과정명</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Class__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>강의 유형 : 내부(Internal) , 외부(external)</description>
    <label>강의 유형</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>내부</fullName>
                <default>true</default>
                <label>내부</label>
            </value>
            <value>
                <fullName>외부</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>잠재고객</label>
    <nameField>
        <label>이름</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Lead__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>솔루션 문의</fullName>
            </value>
            <value>
                <fullName>컨설팅 문의</fullName>
            </value>
            <value>
                <fullName>제휴 문의</fullName>
            </value>
            <value>
                <fullName>유지보수, 하자보수문의</fullName>
            </value>
            <value>
                <fullName>기타 문의</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/RenewalHPContactFormController_Test.cls
/**
 * @description       : Test Class for RenewalHPContactFormController.cls
 * @author            : CJSohn
 * Modifications Log 
 * Ver   Date         Author        Modification
 * 1.0   2022-01-30   CJSohn        Initial Version
**/
@IsTest
private class RenewalHPContactFormController_Test {
    @IsTest
    static void itShould() {
        Test.startTest();

        Class__c objClass = new Class__c();
        objClass.StartDate__c = Datetime.now();
        objClass.Subject__c = 'TestSubject';
        insert objClass;

        RenewalHPContactFormController.getPickListValues('Lead__c','Type__c');

        Map<String, Object> mapTarget = new Map<String, Object>();
        mapTarget.put('Name', 'CJ Sohn');
        mapTarget.put('Company', 'Daeu Nextier');
        mapTarget.put('Mobile', '010-4231-3017');
        mapTarget.put('Email', 'cj.sohn@daeunextier.com');
        mapTarget.put('LeadType', '');
        mapTarget.put('Subject', 'Subject');
        mapTarget.put('Description', 'Description');

        RenewalHPContactFormController.doSave(mapTarget);

        Test.stopTest();
    }
}