PA_Education/TestMenifest/force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>강의 Object</description>
    <label>Training</label>
    <nameField>
        <displayFormat>강의-{0000}</displayFormat>
        <label>강의 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Class__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>과정 시작시간</description>
    <label>시작시간</label>
    <type>DateTime</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Class__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>진행하는 과정의 이름</description>
    <label>과정명</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/HPClassViewController_Test.cls
/**
 * Created by sjhyk on 2022-01-20.
 */

@IsTest
private class HPClassViewController_Test {
    @IsTest
    static  void itShould() {
        Test.startTest();
        Class__c objClass = new Class__c();
        objClass.StartDate__c = Datetime.now();
        objClass.Subject__c = 'TestSubject';
        insert objClass;

        Map<String, Object> mapTarget = new Map<String, Object>();
        mapTarget.put('Mobile', 01024451509);
        mapTarget.put('Register','테스트');
        mapTarget.put('ClassId', objClass.Id);
        mapTarget.put('BirthDate' , Date.today());

        HPClassViewController.doSaveApplyTo(mapTarget);

        HPClassViewController.doSearchClasses();
        HPClassViewController.getRecordById(objClass.Id);

        Test.stopTest();
    }
}