PA_Education/TestMenifest/force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>강의 Object</description>
    <label>Training</label>
    <nameField>
        <displayFormat>강의-{0000}</displayFormat>
        <label>강의 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Class__c/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <formula>TEXT(YEAR(DATEVALUE(StartDate__c))) + &apos; &apos; + Times__c + &apos; &apos; + TEXT(Target__c) + &apos; 교육&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>교육공고</label>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Class__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>종료시간</label>
    <type>DateTime</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Class__c/fields/fm_Status__c.field-meta.xml
<CustomField>
    <fullName>fm_Status__c</fullName>
    <formula>IF( TODAY() &gt; DATEVALUE(StartDate__c  ) , &apos;신청마감&apos;, &apos;신청진행중&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Class__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>과정 시작시간</description>
    <label>시작시간</label>
    <type>DateTime</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Class__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>진행하는 과정의 이름</description>
    <label>과정명</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Class__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <description>과정 수강자 대상</description>
    <label>과정 대상</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administrator</fullName>
                <default>true</default>
                <label>Administrator</label>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>시스템 관리자</fullName>
                <isActive>false</isActive>
                <label>시스템 관리자</label>
            </value>
            <value>
                <fullName>컨설턴트</fullName>
                <isActive>false</isActive>
                <label>컨설턴트</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Class__c/fields/Times__c.field-meta.xml
<CustomField>
    <fullName>Times__c</fullName>
    <description>ex) 24회차 10회차 
강의가 진행되는 차수</description>
    <label>차수</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Class__c/fields/Tuition__c.field-meta.xml
<CustomField>
    <fullName>Tuition__c</fullName>
    <label>수강료</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <description>강의 수강신청 Object</description>
    <label>수강신청</label>
    <nameField>
        <displayFormat>수강신청-{0000}</displayFormat>
        <label>수강신청 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Registration__c/fields/Birthdate__c.field-meta.xml
<CustomField>
    <fullName>Birthdate__c</fullName>
    <description>강의 신청 수강자 생년월일</description>
    <label>생년월일</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Registration__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>강의 과정 명</description>
    <label>강의과정 명</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>수강신청</relationshipLabel>
    <relationshipName>Class</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Registration__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <description>강의 수강 신청자의 연락처</description>
    <label>연락처</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Registration__c/fields/PersonalInformationUseAgreement__c.field-meta.xml
<CustomField>
    <fullName>PersonalInformationUseAgreement__c</fullName>
    <defaultValue>false</defaultValue>
    <description>강의 신청자의 개인정보 수집 및 활용 동의</description>
    <label>개인정보 수집 및 활용 동의</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Registration__c/fields/Register__c.field-meta.xml
<CustomField>
    <fullName>Register__c</fullName>
    <description>강의 수강 신청자</description>
    <label>수강자</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/HPClassViewController.cls
/************************************************************************************
* File Name   		: HPClassViewController.cls
* Author	  		: SJ.Kang
* Date				: 2021.12.06
* Tester	  		: HPClassViewController.cls
* Description 		:
* Modification Log
* ===================================================================================
* Ver      Date            Author          Modification
* ===================================================================================
1.0      2021.12.06        SJ.Kang          Create
1.1      2022.01.19        CJ.Sohn          조회 레코드 및 강의 신청 메소드 수정
*************************************************************************************/

public without sharing class HPClassViewController {
    @AuraEnabled
    public static List<WrapperClass> doSearchClasses() {
        //  전체 실적 리스트를 받아 리턴.
        List<Class__c> listClasses = new List<Class__c>();
        listClasses = [
                SELECT Id, ClassName__c, Subject__c, Target__c, Times__c, Tuition__c, FORMAT(StartDate__c), FORMAT(EndDate__c), OrderNum__c
                FROM   Class__c
                ORDER BY StartDate__c DESC ,CreatedDate DESC
        ];

        List<WrapperClass> listWrapperClasses = new List<WrapperClass>();
        if(!listClasses.isEmpty()){
            Integer idx = 1;
            for(Class__c objClass : listClasses){
                listWrapperClasses.add(new WrapperClass(idx, objClass));
                idx++;
            }
        }

        return listWrapperClasses;
    }

    @AuraEnabled
    public static Class__c getRecordById(String recordId) {
        Class__c objClass = [
                SELECT Id, ClassName__c, Subject__c, Target__c, Times__c, Tuition__c, FORMAT(StartDate__c), FORMAT(EndDate__c), OrderNum__c, fm_Status__c
                FROM   Class__c
                WHERE Id = :recordId
        ];

        return objClass;
    }

    @AuraEnabled
    public static String doSaveApplyTo(Map<String, Object> paramMap){
        String Mobile = String.valueOf(paramMap.get('Mobile'));
        String Register = String.valueOf(paramMap.get('Register'));
        String ClassId = String.valueOf(paramMap.get('ClassId'));
        String BirthDate = String.valueOf(paramMap.get('BirthDate'));

        Registration__c objRegistration = new Registration__c();
        objRegistration.Mobile__c = Mobile;
        objRegistration.Register__c = Register;
        objRegistration.Class__c = ClassId;
        objRegistration.Birthdate__c = Date.valueOf(BirthDate);
        objRegistration.PersonalInformationUseAgreement__c = true;

        insert objRegistration;

        return '0';
    }

    public class WrapperClass {
        @AuraEnabled public String IndexNumber;
        @AuraEnabled public String Id;
        @AuraEnabled public String ClassName;
        @AuraEnabled public String Subject;
        @AuraEnabled public String Target;
        @AuraEnabled public String Times;
        @AuraEnabled public String StartDate;
        @AuraEnabled public String EndDate;
        @AuraEnabled public String IsEnd;
        @AuraEnabled public String Tuition;
        @AuraEnabled public Integer OrderNum;

        public WrapperClass(Integer idx, Class__c objClass){
            this.IndexNumber = idx == null ? '' : String.valueOf(idx);
            this.Id = objClass.Id == null ? '' : String.valueOf(objClass.Id);
            this.ClassName = objClass.ClassName__c == null ? '' : objClass.ClassName__c;
            this.Subject = objClass.Subject__c == null ? '' : objClass.Subject__c;
            this.Target = objClass.Target__c == null ? '' : objClass.Target__c;
            this.Times = objClass.Times__c == null ? '1' : objClass.Times__c;
            this.Tuition = objClass.Tuition__c == null ? '0' : String.valueOf(Integer.valueOf(objClass.Tuition__c));
            this.StartDate = objClass.StartDate__c == null ? '' : objClass.StartDate__c.format('yyyy-MM-dd HH:MM');
            this.EndDate = objClass.EndDate__c == null ? '' : objClass.EndDate__c.format('yyyy-MM-dd HH:MM');
            this.IsEnd = (objClass.EndDate__c != null && DateTime.now() <= objClass.EndDate__c) ? 'false' : 'true';
            this.OrderNum = objClass.OrderNum__c == null ? 0 : Integer.valueOf(objClass.OrderNum__c);
        }
    }
}