PA_Education/TestMenifest/force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>강의 Object</description>
    <label>Training</label>
    <nameField>
        <displayFormat>강의-{0000}</displayFormat>
        <label>강의 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Class__c/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <formula>TEXT(YEAR(DATEVALUE(StartDate__c))) + &apos; &apos; + Times__c + &apos; &apos; + TEXT(Target__c) + &apos; 교육&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>교육공고</label>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Class__c/fields/ClassNameEng__c.field-meta.xml
<CustomField>
    <fullName>ClassNameEng__c</fullName>
    <formula>TEXT(YEAR(DATEVALUE(StartDate__c))) + &apos; &apos; + Times__c + &apos; &apos; + TEXT(Target__c) + &apos; Training&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>교육공고 (English)</label>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Class__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>종료시간</label>
    <type>DateTime</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Class__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>과정 시작시간</description>
    <label>시작시간</label>
    <type>DateTime</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Class__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>진행하는 과정의 이름</description>
    <label>과정명</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Class__c/fields/SubjectEng__c.field-meta.xml
<CustomField>
    <fullName>SubjectEng__c</fullName>
    <label>과정명 (English)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Class__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <description>과정 수강자 대상</description>
    <label>과정 대상</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administrator</fullName>
                <default>true</default>
                <label>Administrator</label>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>시스템 관리자</fullName>
                <isActive>false</isActive>
                <label>시스템 관리자</label>
            </value>
            <value>
                <fullName>컨설턴트</fullName>
                <isActive>false</isActive>
                <label>컨설턴트</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Class__c/fields/Times__c.field-meta.xml
<CustomField>
    <fullName>Times__c</fullName>
    <description>ex) 24회차 10회차 
강의가 진행되는 차수</description>
    <label>차수</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Class__c/fields/Tuition__c.field-meta.xml
<CustomField>
    <fullName>Tuition__c</fullName>
    <label>수강료</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Class__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>강의 유형 : 내부(Internal) , 외부(external)</description>
    <label>강의 유형</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>내부</fullName>
                <default>true</default>
                <label>내부</label>
            </value>
            <value>
                <fullName>외부</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <description>강의 수강신청 Object</description>
    <label>수강신청</label>
    <nameField>
        <displayFormat>수강신청-{0000}</displayFormat>
        <label>수강신청 Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PA_Education/TestMenifest/force-app/main/default/objects/Registration__c/fields/Birthdate__c.field-meta.xml
<CustomField>
    <fullName>Birthdate__c</fullName>
    <description>강의 신청 수강자 생년월일</description>
    <label>생년월일</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Registration__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>강의 과정 명</description>
    <label>강의과정 명</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>수강신청</relationshipLabel>
    <relationshipName>Class</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Registration__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <description>강의 수강 신청자의 연락처</description>
    <label>연락처</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Registration__c/fields/PersonalInformationUseAgreement__c.field-meta.xml
<CustomField>
    <fullName>PersonalInformationUseAgreement__c</fullName>
    <defaultValue>false</defaultValue>
    <description>강의 신청자의 개인정보 수집 및 활용 동의</description>
    <label>개인정보 수집 및 활용 동의</label>
    <type>Checkbox</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/objects/Registration__c/fields/Register__c.field-meta.xml
<CustomField>
    <fullName>Register__c</fullName>
    <description>강의 수강 신청자</description>
    <label>수강자</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

PA_Education/TestMenifest/force-app/main/default/classes/RenewalHPClassInformation.cls
/**
 * =============================================
 * File Name    : RenewalHPClassInformation.cls
 * Author       : Chan Kang
 * Group        : Boundary
 * Date         : 2021. 12. 24
 * Description  : 교육 커리큘럼 찾기, 생성
 * Modification Log
 * ===================================================================================
 * Ver      Date            Author              Modification
 * ===================================================================================
   1.0      2021. 12. 24    Chan Kang           Create
   1.1      2022. 04. 15    Gunwoo Kim          Use optimized query constructor
                                                Add query to fetch data in English
*/

public without sharing class RenewalHPClassInformation {
    @AuraEnabled
    public static List<Class__c> getClassInformation(Boolean isEnglish) {
//        List<Class__c> classInformation = [
//            SELECT Id, Subject__c, Type__c, Target__c, StartDate__c, EndDate__c, Tuition__c, Times__c, ClassName__c
//            FROM Class__c
//            WHERE OrderNum__c != NULL AND OrderNum__c != 0
//            ORDER BY OrderNum__c ASC
//            LIMIT 9
//        ];
//        return classInformation;
        String body = isEnglish
                ? 'Id, SubjectEng__c, Type__c, Target__c, StartDate__c, EndDate__c, Tuition__c, Times__c, ClassNameEng__c'
                : 'Id, Subject__c, Type__c, Target__c, StartDate__c, EndDate__c, Tuition__c, Times__c, ClassName__c';
        String tail = 'Class__c WHERE OrderNum__c != NULL AND OrderNum__c != 0 ORDER BY OrderNum__c ASC LIMIT 9';
        return Database.query(RenewalHPUtility.queryConstructor(body, tail));
    }


    @AuraEnabled
    public static List<Class__c> loadMoreClasses(Boolean isEnglish) {
//        List<Class__c> classInformation = [
//                SELECT Id, Subject__c, Type__c, Target__c, StartDate__c, EndDate__c, Tuition__c, Times__c, ClassName__c
//                FROM Class__c
//                ORDER BY Id DESC
//        ];
        String body = isEnglish
                ? 'Id, SubjectEng__c, Type__c, Target__c, StartDate__c, EndDate__c, Tuition__c, Times__c, ClassNameEng__c'
                : 'Id, Subject__c, Type__c, Target__c, StartDate__c, EndDate__c, Tuition__c, Times__c, ClassName__c';
        String tail = 'Class__c ORDER BY Id DESC';
        return Database.query(RenewalHPUtility.queryConstructor(body, tail));
//        return classInformation;
    }

    @AuraEnabled
    public static String doSaveApplyTo(Map<String, Object> paramMap,String fileName, String base64Data, String contentType){
        String Mobile = String.valueOf(paramMap.get('Mobile'));
        String Register = String.valueOf(paramMap.get('Register'));
        String ClassId = String.valueOf(paramMap.get('ClassId'));
        String BirthDate = String.valueOf(paramMap.get('BirthDate'));

        Registration__c objRegistration = new Registration__c();

        objRegistration.Mobile__c = Mobile;
        objRegistration.Register__c = Register;
        objRegistration.Class__c = ClassId;
        objRegistration.Birthdate__c = Date.valueOf(BirthDate);
        objRegistration.PersonalInformationUseAgreement__c = true;

        insert objRegistration;

        return '0';
    }
}